Update pdf-over from 4.2.3,1 to 4.3.1
Homebrew/homebrew-cask pull request #100127
Opened 2021-02-21 12:52 UTC by voukpaw

Created with `brew bump-cask-pr`.

2021-02-22 03:44 UTC, vitorgalvao requested changes

2021-02-22 03:44 UTC, vitorgalvao commented on Casks/pdf-over.rb
> +  version "4.3.1"
Downloaded the app, and I’m seeing `4.1.3`.

2021-02-23 05:09 UTC, miccal commented on Casks/pdf-over.rb
> +  version "4.3.1"
`brew bump-unversioned-casks pdf-over` reports `4.1.3,1`.

2021-02-23 05:48 UTC, miccal commented
Closing in favour of ???

2021-02-23 05:48 UTC, closed without merging