OnionShare 2.3
Homebrew/homebrew-cask pull request #100219
Opened 2021-02-22 01:35 UTC by micahflee

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).
- [x] `brew audit --cask {{cask_file}}` is error-free.
- [x] `brew style --fix {{cask_file}}` reports no offenses.

OnionShare 2.3 changed from distributing as a `pkg` to a `dmg`.

2021-02-22 03:33 UTC, vitorgalvao requested changes

2021-02-22 03:33 UTC, vitorgalvao commented on Casks/onionshare.rb
> +  url "https://onionshare.org/dist/#{version}/OnionShare-#{version}.dmg"
This isn’t a GitHub releases URL; the `livecheck` won’t work as is. Please see [the documentation](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/livecheck.md). You’ll need a `page_match`.

2021-02-23 11:35 UTC, vitorgalvao commented on Casks/onionshare.rb
> +  url "https://github.com/micahflee/onionshare/releases/download/v#{version}/OnionShare-#{version}.dmg",
Which this `url`, `livecheck` can likely be removed.

2021-02-23 18:49 UTC, micahflee commented
Opened a separate very similar PR https://github.com/Homebrew/homebrew-cask/pull/100290

2021-02-23 18:49 UTC, closed without merging