outline-manager: add zap entries
Homebrew/homebrew-cask pull request #100281
Opened 2021-02-23 14:51 UTC by kidonng

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).
- [ ] `brew audit --cask {{cask_file}}` is error-free.
- [ ] `brew style --fix {{cask_file}}` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask {{cask_file}}` worked successfully.
- [ ] `brew install --cask {{cask_file}}` worked successfully.
- [ ] `brew uninstall --cask {{cask_file}}` worked successfully.

2021-02-27 00:51 UTC, vitorgalvao requested changes

2021-02-27 00:51 UTC, vitorgalvao commented on Casks/outline-manager.rb
> +  livecheck do
Because the `url` is from Github releases, `livecheck` is unlikely to be needed. Have you tried `brew livecheck` after removing `appcast` and `livecheck`?

2021-02-27 00:51 UTC, vitorgalvao commented on Casks/outline-manager.rb
> +    regex(/version: ([\d.]+)/i)
Tangentially, the version checking regex should be `(\d+(?:\.\d+)*)` (except if it doesn't work).

2021-03-04 14:30 UTC, kidonng commented on Casks/outline-manager.rb
> +  livecheck do
```
❯ brew livecheck outline-manager
outline-manager : 1.6.1 ==> 1612542200
```

Outline seems to have a daily release as their latest GitHub release by mistake:

![image](https://user-images.githubusercontent.com/44045911/109978741-26a6b700-7d39-11eb-9678-b54df776c961.png)

2021-03-04 14:36 UTC, kidonng commented on Casks/outline-manager.rb
> +    regex(/version: ([\d.]+)/i)
Good to know I should actually use this one from the docs.

2021-03-04 15:44 UTC, vitorgalvao commented on Casks/outline-manager.rb
> +  livecheck do
Thank you for checking.

2021-03-04 15:44 UTC, vitorgalvao approved these changes

2021-03-04 15:44 UTC, merged