Add Bob Wallet v0.6.2
Homebrew/homebrew-cask pull request #100309
Opened 2021-02-24 10:00 UTC by nlydv

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [ x ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).
- [ x ] `brew audit --cask {{cask_file}}` is error-free.
- [ x ] `brew style --fix {{cask_file}}` reports no offenses.

Additionally, **if adding a new cask**:

- [ x ] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [ x ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ x ] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).
- [ x ] `brew audit --new-cask {{cask_file}}` worked successfully.
- [ x ] `brew install --cask {{cask_file}}` worked successfully.
- [ x ] `brew uninstall --cask {{cask_file}}` worked successfully.

2021-02-27 00:31 UTC, vitorgalvao requested changes, later dismissed

2021-02-27 00:31 UTC, vitorgalvao commented on Casks/bob-wallet.rb
> +cask "bob-wallet" do
Does not follow the [token reference](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md). Needs to be `kyokan-bob`. The file would also require the rename.

2021-02-27 00:31 UTC, vitorgalvao commented on Casks/bob-wallet.rb
> +  url "https://github.com/kyokan/bob-wallet/releases/download/v0.6.2/Bob-#{version}.dmg",
```suggestion
  url "https://github.com/kyokan/bob-wallet/releases/download/v#{version}/Bob-#{version}.dmg",
```

2021-02-27 00:31 UTC, vitorgalvao commented on Casks/bob-wallet.rb
> +  appcast "https://github.com/kyokan/bob-wallet/releases.atom"
If you remove this line and run `brew livecheck kyokan-bob` (after the rename), does it find the correct version? If so (likely), you can delete this line.

2021-02-27 00:31 UTC, vitorgalvao commented on Casks/bob-wallet.rb
> +  caveats "
From the [`caveats` documentation](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/caveats.md):

> To avoid flooding users with too many messages (thus desensitising them to the important ones), `caveats` should be used sparingly and exclusively for installation-related matters.

From the [Homebrew Cask is not a discoverability service FAQ document](https://github.com/Homebrew/brew/blob/master/docs/Acceptable-Casks.md#homebrew-cask-is-not-a-discoverability-service)

> users are expected to have reasonable knowledge about the apps they’re installing through us before doing so.

2021-02-27 00:31 UTC, vitorgalvao commented
Welcome, and thank you for the contribution! It just needs a few changes.

2021-02-28 00:43 UTC, nlydv commented
@vitorgalvao I've made the requested changes. The `brew livecheck kyokan-bob` output was inaccurate so I kept those lines in. Let me know if there's anything else.

2021-03-01 04:04 UTC, miccal commented
Thank you for your contribution to `homebrew-cask` @nlydv.

2021-03-01 04:04 UTC, miccal approved these changes

2021-03-01 04:04 UTC, merged