Update decrediton from 1.6.0 to 1.6.1
Homebrew/homebrew-cask pull request #100354
Opened 2021-02-25 14:10 UTC by josser

Created with `brew bump-cask-pr`.

2021-02-27 00:09 UTC, vitorgalvao requested changes

2021-02-27 00:09 UTC, vitorgalvao commented on Casks/decrediton.rb
> +  desc "Cross-platform GUI for decred written in node.js using Electron"
This should explain what the software is or does; the technology used to build it is irrelevant.

2021-03-01 09:52 UTC, josser commented on Casks/decrediton.rb
> +  desc "Cross-platform GUI for decred written in node.js using Electron"
Fixed; 
At the same time, it may be still worth to mention such things somewhere because some people treat electron-based apps as something second-rate. 
I.e if there is choice between native and electron based some would like to choose native.

2021-03-01 15:51 UTC, vitorgalvao commented on Casks/decrediton.rb
> +  desc "Cross-platform GUI for decred written in node.js using Electron"
[Homebrew Cask is not a discoverability service](https://github.com/Homebrew/brew/blob/master/docs/Acceptable-Casks.md#homebrew-cask-is-not-a-discoverability-service):

> users are expected to have reasonable knowledge about the apps they’re installing through us before doing so.

`desc` helps with searchability and disambiguation; if you care about an app’s technology, that’s on you to figure out. Plus, adding the technology to the description is one more thing to keep track of because that can change.

2021-03-01 15:51 UTC, vitorgalvao submitted a review, later dismissed

2021-03-02 05:28 UTC, miccal commented
/rebase

2021-03-02 05:49 UTC, miccal commented
Thank you @josser.

2021-03-02 05:49 UTC, miccal approved these changes

2021-03-02 05:49 UTC, merged