Add ZuluFX 15.0.2
Homebrew/homebrew-cask pull request #100357
Opened 2021-02-25 15:58 UTC by lebdron

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).
- [x] `brew audit --cask {{cask_file}}` is error-free.
- [x] `brew style --fix {{cask_file}}` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask {{cask_file}}` worked successfully.
- [x] `brew install --cask {{cask_file}}` worked successfully.
- [x] `brew uninstall --cask {{cask_file}}` worked successfully.

2021-02-27 00:07 UTC, vitorgalvao requested changes

2021-02-27 00:07 UTC, vitorgalvao commented on Casks/zulufx.rb
> +  desc "Zulu with OpenJFX"
The `name` is a better description. As it is, `desc` is only clear to people who already know what this is.

2021-02-27 09:04 UTC, lebdron commented on Casks/zulufx.rb
> +  desc "Zulu with OpenJFX"
Good point! That was not a good fix for error of missing `desc` from original Zulu Cask.

2021-02-28 00:42 UTC, vitorgalvao approved these changes

2021-02-28 00:42 UTC, merged