Add MailTrackerBlocker v0.3.15
Homebrew/homebrew-cask pull request #100509
Opened 2021-03-02 13:15 UTC by apparition47

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).
- [x] `brew audit --cask {{cask_file}}` is error-free.
- [x] `brew style --fix {{cask_file}}` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask {{cask_file}}` worked successfully.
- [x] `brew install --cask {{cask_file}}` worked successfully.
- [x] `brew uninstall --cask {{cask_file}}` worked successfully.

2021-03-03 00:58 UTC, miccal commented
Thank you for your contribution to `homebrew-cask` @apparition47.

Could you please try to add a [`zap` stanza](https://github.com/homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/zap.md), thanks.

2021-03-03 02:52 UTC, apparition47 commented
Does the `zap` stanza run after the `uninstall` stanza? All my (only 1) of my files should already be covered in `uninstall`.

Also tried the suggested `createzap`:

```bash
$ brew createzap mailtrackerblocker
No mailtrackerblocker settings found.
```

2021-03-04 13:14 UTC, vitorgalvao requested changes

2021-03-04 13:14 UTC, vitorgalvao commented on Casks/mailtrackerblocker.rb
> +  def caveats
From the [`caveats` documentation](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/caveats.md):

> To avoid flooding users with too many messages (thus desensitising them to the important ones), `caveats` should be used sparingly and exclusively for installation-related matters.

From the [Homebrew Cask is not a discoverability service FAQ document](https://github.com/Homebrew/brew/blob/master/docs/Acceptable-Casks.md#homebrew-cask-is-not-a-discoverability-service)

> users are expected to have reasonable knowledge about the apps they’re installing through us before doing so.

Also, we don’t use emoji in cask caveats. Please remove this.

2021-03-04 13:14 UTC, vitorgalvao commented on Casks/mailtrackerblocker.rb
> +            quit:    ["com.apple.mail"]
Is this *needed* for the uninstall to work? Not too comfortable closing another app without warning.

2021-03-04 13:24 UTC, apparition47 commented on Casks/mailtrackerblocker.rb
> +            quit:    ["com.apple.mail"]
Sure, It won't prevent the uninstallation but it will create user confusion if someone decides **to uninstall with my plugin enabled while Mail is open**. The plugin will still be activated but with all the localized strings missing (see screenshot). As the user, I'd expect all remnants of this plugin to be gone upon uninstall and that doesn't happen until Mail is closed to allow the plugin to be finally released from memory.

![](https://user-images.githubusercontent.com/19980081/109478265-5031bb00-7a79-11eb-9092-480c6005e3ce.png)

2021-03-04 13:33 UTC, apparition47 commented on Casks/mailtrackerblocker.rb
> +  def caveats
Removed the caveat completely since it isn't "installation-related".

2021-03-04 15:08 UTC, vitorgalvao commented on Casks/mailtrackerblocker.rb
> +            quit:    ["com.apple.mail"]
Agreed it may cause some confusion, but that’s better than the alternative of closing an another application from under the user’s feet, which may have consequences we aren’t envisioning.

We could check at uninstall time if Mail.app is running, and if yes, print a message (untested code):

```ruby
uninstall_postflight do
  if system_command("ps", args: ["x"]).stdout.match?("Mail.app/Contents/MacOS/Mail")
    opoo "Restart Mail.app to finish uninstalling #{token}"
  end
end
```

2021-03-04 15:36 UTC, vitorgalvao commented on Casks/mailtrackerblocker.rb
> +            quit:    "com.apple.mail"
The goal of the `uninstall_postflight` is so we can remove this.

2021-03-04 15:37 UTC, vitorgalvao commented on Casks/mailtrackerblocker.rb
> +  uninstall_postflight do
Is this working as is? Meaning, if Mail.app is is running and we `brew uninstall mailtrackerblocker`, it shows the message?

2021-03-04 15:39 UTC, apparition47 commented on Casks/mailtrackerblocker.rb
> +  uninstall_postflight do
Yes, seems to work

```bash
brew remove mailtrackerblocker
==> Uninstalling Cask mailtrackerblocker
==> Uninstalling packages:
com.onefatgiraffe.mailtrackerblocker
==> Removing files:
/Library/Mail/Bundles/MailTrackerBlocker.mailbundle
Warning: Restart Mail.app to finish uninstalling mailtrackerblocker
==> Purging files for version 0.3.16 of Cask mailtrackerblocker
```

2021-03-04 15:43 UTC, vitorgalvao commented on Casks/mailtrackerblocker.rb
> +  uninstall_postflight do
Great! I asked because untested code that works on the first try is always suspicious.

Thank you for the submission, the fast changes, and for working on something that makes it harder to be tracked.

2021-03-04 15:43 UTC, vitorgalvao approved these changes

2021-03-04 15:43 UTC, merged