Add VeePN.app v2.0.1
Homebrew/homebrew-cask pull request #100951
Opened 2021-03-09 17:03 UTC by box000

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).
- [x] `brew audit --cask {{cask_file}}` is error-free.
- [x] `brew style --fix {{cask_file}}` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask {{cask_file}}` worked successfully.
- [x] `brew install --cask {{cask_file}}` worked successfully.
- [x] `brew uninstall --cask {{cask_file}}` worked successfully.

2021-03-09 20:07 UTC, vitorgalvao requested changes

2021-03-09 20:08 UTC, vitorgalvao commented
Welcome. Looking good so far. Made a few requests.

2021-03-09 21:03 UTC, box000 commented on Casks/veepn.rb
> +  desc "VPN client for secure internet access and private browsing"
+

2021-03-09 21:03 UTC, box000 commented on Casks/veepn.rb
> +  uninstall launchctl: "com.veepn.macos.helper"
+

2021-03-09 21:14 UTC, vitorgalvao approved these changes, later dismissed

2021-03-09 21:14 UTC, vitorgalvao commented
Great! Thank you.

2021-03-10 13:45 UTC, vitorgalvao approved these changes

2021-03-10 13:45 UTC, merged