Add Around.co installer
Homebrew/homebrew-cask pull request #100988
Opened 2021-03-10 20:30 UTC by claudiosv

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version). ➡️ There is only one version publicly available, which they label as a beta. I do not consider this unstable software.
- [x] `brew audit --cask {{cask_file}}` is error-free.
- [x] `brew style --fix {{cask_file}}` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask {{cask_file}}` worked successfully.
- [x] `brew install --cask {{cask_file}}` worked successfully.
- [x] `brew uninstall --cask {{cask_file}}` worked successfully.

2021-03-10 20:36 UTC, ran-dall requested changes, later dismissed
@claudiosv You should also add a [LiveCheck](https://github.com/Homebrew/brew/blob/master/docs/Brew-Livecheck.md)

2021-03-10 20:36 UTC, ran-dall commented on Casks/around.rb
> +  sha256 :no_check
@claudiosv We really try to stay away from unversioned casks, to the point where we've denied PRs because of this. Is there a way we can find a version number?

2021-03-12 15:29 UTC, claudiosv commented on Casks/around.rb
> +  sha256 :no_check
@ran-dall I understand, I also prefer casks to be versioned but unfortunately I couldn't find anything for Around in the URL, so I took a different approach using a LiveCheck for the JSON endpoint the download page uses to fetch the current app version. Please let me know if that's better.

Thanks for the feedback.

2021-03-15 21:54 UTC, claudiosv commented
@ran-dall Any update since my last commit? Happy to make more changes.

2021-03-15 22:06 UTC, ran-dall commented
@claudiosv You need to add a `sha256`. A simple way to do that is to just run `openssl sha256 /path/to/installer`

2021-03-15 22:13 UTC, claudiosv commented
@ran-dall

> Use `sha256 :no_check` when URL is unversioned.

Unfortunately there is no versioned URL available.

2021-03-16 06:40 UTC, miccal commented
Thank you for your contribution to `homebrew-cask` @claudiosv.

Could you please try to add a [`zap` stanza](https://github.com/homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/zap.md), thanks.

2021-03-16 19:30 UTC, claudiosv commented
Thanks @miccal, how does [`e9dcc0f`](https://github.com/Homebrew/homebrew-cask/pull/100988/commits/e9dcc0f1116200828832c1ee7d069fc82d66fdf0) look?

2021-03-17 00:49 UTC, miccal commented
Thank you @claudiosv.

2021-03-17 00:50 UTC, miccal approved these changes

2021-03-17 00:50 UTC, merged