Add Coinomi Wallet 1.2.4
Homebrew/homebrew-cask pull request #101374
Opened 2021-03-18 23:09 UTC by danielbayley

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).
- [x] `brew audit --cask {{cask_file}}` is error-free.
- [x] `brew style --fix {{cask_file}}` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask {{cask_file}}` worked successfully.
- [ ] `brew install --cask {{cask_file}}` worked successfully.
- [ ] `brew uninstall --cask {{cask_file}}` worked successfully.

2021-03-18 23:49 UTC, danielbayley commented
No idea why this is failing…

2021-03-22 19:02 UTC, vitorgalvao requested changes, later dismissed

2021-03-22 19:02 UTC, vitorgalvao commented on Casks/coinomi-wallet.rb
> +  appcast "https://coinomi.com/downloads"
Please convert to a [`livecheck`](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/livecheck.md).

2021-03-23 15:04 UTC, danielbayley commented on Casks/coinomi-wallet.rb
> +  appcast "https://coinomi.com/downloads"
> Please convert to a [`livecheck`](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/livecheck.md).

@vitorgalvao Interesting… I missed this development. Does this break `brew audit --appcast`? Is there an equivalent test like `brew audit --livecheck` or something?

Also, there seems to be `strategy`s missing from that documentation… Namely `:git`, `:github_latest`, `:electron_builder` that I have come across.

2021-03-23 15:49 UTC, danielbayley commented
@vitorgalvao Looks like the `livecheck` `regex()` is failing on the raw HTML fetched with `:page_match` (`curl`?)… Should something like `CGI.unescapeHTML` be applied inside that method?

2021-03-23 16:07 UTC, danielbayley commented
> Please convert to a [`livecheck`](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/livecheck.md).

@vitorgalvao Interesting… I missed this development. Does this break `brew audit --appcast`? Is there an equivalent test like `brew audit --livecheck` or something?

Also, there seems to be `strategy`s missing from that documentation… Namely `:git`, `:github_latest`, `:electron_builder` that I have come across.

2021-03-25 05:57 UTC, miccal commented
Thank you @danielbayley.

2021-03-25 05:58 UTC, miccal approved these changes

2021-03-25 05:58 UTC, merged

2021-03-27 19:29 UTC, vitorgalvao commented
@danielbayley `livecheck` already existed for formulae and I’m not intimately familiar with the inner workings. You can test it with `brew livecheck --debug CASK_NAME`.

There’s also a [`livecheck` document in the core’s repo](https://github.com/Homebrew/brew/blob/master/docs/Brew-Livecheck.md) which [links to the strategies](https://rubydoc.brew.sh/Homebrew/Livecheck/Strategy.html). But I wouldn’t be opposed to making them clearer in the markdown documentation.