ibm-aspera-connect: fix uninstall script path and move log deletion to zap
Homebrew/homebrew-cask pull request #101412
Opened 2021-03-19 21:25 UTC by cho-m

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).
- [ ] `brew audit --cask {{cask_file}}` is error-free.
- [ ] `brew style --fix {{cask_file}}` reports no offenses.

Fixes #99043

**Uninstall Output**
```console
❯ brew uninstall ibm-aspera-connect
==> Uninstalling Cask ibm-aspera-connect
==> Running uninstall script /Users/cho-m/Library/Application Support/Aspera/Aspera Connect/uninstall_connect.sh
forcing full uninstall
Uninstalling Aspera Connect for user cho-m
Keeping /Users/cho-m/Applications directory since it is not empty
Keeping /Users/cho-m/Library/Logs/Aspera_Connect directory since it is not empty
Aspera Connect has successfully been uninstalled
==> Purging files for version 3.11.1.58 of Cask ibm-aspera-connect
```

**Forced zap cleanup**
```console
❯ brew uninstall --cask --zap --force ibm-aspera-connect
==> Implied `brew uninstall --cask ibm-aspera-connect`
==> Running uninstall script /Users/cho-m/Library/Application Support/Aspera/Aspera Connect/uninstall_connect.sh
Warning: uninstall script /Users/cho-m/Library/Application Support/Aspera/Aspera Connect/uninstall_connect.sh does not exist; skipping.
==> Dispatching zap stanza
==> Trashing files:
~/Library/Application Scripts/com.aspera.connect.SafariExtension
~/Library/Application Scripts/com.aspera.drive.SendToExtension
~/Library/Containers/com.aspera.connect.SafariExtension
~/Library/Containers/com.aspera.drive.SendToExtension
~/Library/Group Containers/group.com.aspera.connect
~/Library/Logs/Aspera_Connect
~/Library/Preferences/com.aspera.connect.plist
~/Library/Saved Application State/com.aspera.connect.savedState
==> Removing all staged versions of Cask 'ibm-aspera-connect'

❯ ls ~/.Trash
 Aspera_Connect
 com.aspera.connect.SafariExtension
'com.aspera.connect.SafariExtension 14-09-39-193.SafariExtension'
 com.aspera.connect.savedState
 com.aspera.drive.SendToExtension
'com.aspera.drive.SendToExtension 14-09-39-194.SendToExtension'
 group.com.aspera.connect
 com.aspera.connect.plist
```

**Audit/Style**
```console
❯ brew audit --cask ibm-aspera-connect
audit for ibm-aspera-connect: passed

❯ brew style --fix ibm-aspera-connect

1 file inspected, no offenses detected
```

2021-03-22 01:23 UTC, vitorgalvao requested changes

2021-03-22 01:23 UTC, vitorgalvao commented on Casks/ibm-aspera-connect.rb
> +    executable: "#{ENV["HOME"]}/Library/Application Support/Aspera/Aspera Connect/uninstall_connect.sh",
Please keep this as `~`. This should be fixed at the source, not have different solutions for each cask.

2021-03-28 09:04 UTC, cho-m commented on Casks/ibm-aspera-connect.rb
> +    executable: "#{ENV["HOME"]}/Library/Application Support/Aspera/Aspera Connect/uninstall_connect.sh",
Created https://github.com/Homebrew/brew/pull/10956 for `~` support.
Will edit this in a bit.

2021-03-28 14:51 UTC, vitorgalvao approved these changes

2021-03-28 14:51 UTC, merged