add SonoBus cask
Homebrew/homebrew-cask pull request #102787
Opened 2021-03-28 13:56 UTC by leolabs

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

Homepage: https://sonobus.net/

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).
- [x] `brew audit --cask {{cask_file}}` is error-free.
- [x] `brew style --fix {{cask_file}}` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask {{cask_file}}` worked successfully.
- [x] `brew install --cask {{cask_file}}` worked successfully.
- [x] `brew uninstall --cask {{cask_file}}` worked successfully.

2021-03-28 23:16 UTC, vitorgalvao requested changes

2021-03-28 23:16 UTC, vitorgalvao commented on Casks/sonobus.rb
> +    regex(%r{href="releases/.*?-(.+)-mac\.dmg}i)
Use the example in `livecheck`—`(\d+(?:\.\d+)*)`—instead of the generic `(.+)`.

2021-03-28 23:16 UTC, vitorgalvao commented on Casks/sonobus.rb
> +end
Please add a [`zap`](https://github.com/homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/zap.md). See [`homebrew-createzap`](https://github.com/nrlquaker/homebrew-createzap) for an external project which can help.

2021-03-29 13:37 UTC, leolabs commented
Thanks for your review! I've fixed the points you mentioned :)

2021-03-29 23:34 UTC, vitorgalvao approved these changes

2021-03-29 23:34 UTC, merged