Initial calmly writer
Homebrew/homebrew-cask pull request #104014
Opened 2021-04-15 05:57 UTC by cadojo

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [X] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).
- [X] `brew audit --cask {{cask_file}}` is error-free.
- [X] `brew style --fix {{cask_file}}` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [X] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).
- [X] `brew audit --new-cask {{cask_file}}` worked successfully.
- [X] `brew install --cask {{cask_file}}` worked successfully.
- [X] `brew uninstall --cask {{cask_file}}` worked successfully.

2021-04-15 08:17 UTC, miccal commented
```
Error: Failure while executing; `/usr/bin/sudo -E -- /usr/bin/env LOGNAME=runner USER=runner USERNAME=runner /usr/sbin/installer -pkg /usr/local/Caskroom/calmly-writer/2.0.25/Calmly\ Writer-2.0.25.pkg -target /` exited with 1. Here's the output:
installer: Error - Calmly Writer can’t be installed on this computer.
```
I am _guessing_ that the error has something to do with the space in the `pkg` name:
```
|-> curl -sLI https://calmlywriter.com/releases/x64/download.php | grep -i Location
Location: https://www.calmlywriter.com/releases/x64/Calmly Writer-2.0.25.pkg
```

2021-04-15 12:33 UTC, cadojo commented
> I am _guessing_ that the error has something to do with the space in the `pkg` name:

Thanks for looking into this. I ran into a similar issue when installing locally, but adding the `%20` in the download name fixed the issue.

2021-04-15 14:54 UTC, vitorgalvao requested changes

2021-04-15 14:54 UTC, vitorgalvao commented on Casks/calmly-writer.rb
> +  desc "Editor designed to focus on what you want to tell"
From the [`desc` documentation](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/desc.md):

> `desc` is not for app slogans! Vendors’ descriptions tend to be filled with generic adjectives such as “modern” and “lightweight”. Those are meaningless marketing fluff (do you ever see apps proudly describing themselves as outdated and bulky?) which must the deleted. It’s fine to use the information on the software’s website as a starting point, but it will require editing in almost all cases.

2021-04-15 14:54 UTC, vitorgalvao commented on Casks/calmly-writer.rb
> +end
Please add a [`zap`](https://github.com/homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/zap.md). See [`homebrew-createzap`](https://github.com/nrlquaker/homebrew-createzap) for an external project which can help.

2021-04-16 06:37 UTC, cho-m commented on Casks/calmly-writer.rb
> +  url "https://www.calmlywriter.com/releases/arm64/Calmly%20Writer-#{version}.pkg"
```suggestion

  if Hardware::CPU.intel?
    sha256 "269dffa6f93deb8116c865001e8862b0d97ff9246269ca29609aba5a0102a520"
    
    url "https://www.calmlywriter.com/releases/x64/Calmly%20Writer-#{version}.pkg"
  else
    sha256 "92223bc82ca7af4718f41097edfa85da724f59b87b1a75d01a92db995325d48e"

    url "https://www.calmlywriter.com/releases/arm64/Calmly%20Writer-#{version}.pkg"
  end

```

Currently, the cask is always using ARM64 version.
The checks are run on Intel 10.15, so probably causing install failure due to architecture difference.

2021-04-16 18:55 UTC, cadojo reviewed
I've added these changes!

2021-04-16 18:57 UTC, cadojo commented
This PR is telling me there's changes that are requested, but I've addressed everything that I can see. It seems the automated tests are blocked or something

2021-04-16 19:14 UTC, cho-m commented
@cadojo The CI checks reran but failed on uninstall:
```
Error: Some packages are still installed, add them to uninstall pkgutil:
calmlywriter
```

Looks like there is some things left over on uninstall.

2021-04-17 11:37 UTC, vitorgalvao commented on Casks/calmly-writer.rb
> +  uninstall pkgutil: "Calmly Writer-#{version}.pkg"
This doesn’t look right. It’s not the name of the file, [see the documentation](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/uninstall.md#uninstall-key-pkgutil).

2021-04-17 11:38 UTC, vitorgalvao approved these changes

2021-04-17 11:45 UTC, merged