Add BudgetBudget 1.0.0-beta.17
Homebrew/homebrew-cask pull request #104193
Opened 2021-04-18 09:28 UTC by MichaelSp

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).
- [x] `brew audit --cask {{cask_file}}` is error-free.
- [x] `brew style --fix {{cask_file}}` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask {{cask_file}}` worked successfully.
- [x] `brew install --cask {{cask_file}}` worked successfully.
- [x] `brew uninstall --cask {{cask_file}}` worked successfully.

2021-04-18 09:33 UTC, MichaelSp commented
The links are not pointing to a place that explains anything about stable versions or exceptions...

 > The submission is for **a stable version**  or **documented exception.**

2021-04-21 15:08 UTC, vitorgalvao requested changes

2021-04-21 15:08 UTC, vitorgalvao commented on Casks/budgetbudget.rb
> +  desc "Gain confidence in financial decisions and plan monthly budgets with MoneyMoney"
From the [`desc` documentation](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/desc.md):

> `desc` is not for app slogans! Vendors’ descriptions tend to be filled with generic adjectives such as “modern” and “lightweight”. Those are meaningless marketing fluff (do you ever see apps proudly describing themselves as outdated and bulky?) which must the deleted. It’s fine to use the information on the software’s website as a starting point, but it will require editing in almost all cases.

2021-04-21 15:08 UTC, vitorgalvao commented on Casks/budgetbudget.rb
> +    url :url
You’re checking the download URL itself? `Livecheck` is to check for new versions.

2021-04-23 14:46 UTC, MichaelSp commented
Thanks for the review @vitorgalvao 
I'll make the PR "ready for review" once budgetbudget hits a stable release.

2021-04-23 17:19 UTC, vitorgalvao commented
Thank you, but we’ll be rejecting this on account of [not being notable enough](https://github.com/Homebrew/brew/blob/master/docs/Acceptable-Casks.md#rejected-casks):

> + The Cask is too obscure. Examples:
>   + An app from a code repository that is not notable enough (under 30 forks, 30 watchers, 75 stars).
>   + [Electronic Identification (eID) software](https://github.com/Homebrew/homebrew-cask/issues/59021).

Apologies as I forgot to close this before.

> I'll make the PR "ready for review" once budgetbudget hits a stable release.

We don’t like having PRs hanging waiting for an external change which may never come.

2021-04-23 17:19 UTC, closed without merging