Update qt-creator from 4.14.1 to 4.14.2 and add livecheck
Homebrew/homebrew-cask pull request #104923
Opened 2021-05-02 15:51 UTC by cho-m

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask {{cask_file}}` is error-free.
- [x] `brew style --fix {{cask_file}}` reports no offenses.

---

For `livecheck`:
- Can't use `page.match` since https://download.qt.io/official_releases/qtcreator/ shows empty upcoming release number 4.15, so need to at least go through first 2 (4.15 and 4.14) to find latest version
- Using `lazy` with selecting first non-nil to try to avoid doing 9 extra HTTP GETs. The versions are ordered with newest first.

2021-05-03 07:08 UTC, SMillerDev commented on Casks/qt-creator.rb
> +  end
@nandahkrishna and @samford?

2021-05-03 11:52 UTC, nandahkrishna commented on Casks/qt-creator.rb
> +  end
Can possibly use `url "https://download.qt.io/official_releases/qtcreator/?C=N;O=D"` to ensure that we have a descending order for versions.

2021-05-03 11:55 UTC, nandahkrishna commented on Casks/qt-creator.rb
> +  end
Similarly, we could use `Net::HTTP.get(URI.parse("#{url}#{match[0]}/?C=N;O=D"))` for the subdirectories.

2021-05-03 12:25 UTC, nandahkrishna commented on Casks/qt-creator.rb
> +      end.reject(&:nil?).first
I should've also mentioned that there would be additional changes based on my previous comments, so here's a suggestion:
```suggestion
    url "https://download.qt.io/official_releases/qtcreator/?C=N;O=D"
    strategy :page_match do |page|
      page.scan(%r{href="(\d+(?:\.\d+)*)/"}i).lazy.map do |match|
        version_page = Net::HTTP.get(URI.parse("#{url.split("?")[0]}#{match[0]}/C=N;O=D"))
        version_page[%r{href="(\d+(?:\.\d+)*)/"}i, 1]
      end.reject(&:nil?).first
```
Not sure if there's a better way to remove the GET parameters than using `split("?")`.

2021-05-03 14:38 UTC, samford commented on Casks/qt-creator.rb
> +  end
The suggested `livecheck` block and feedback in #104889 should apply here as well, since the situation is the same (files in major/minor version directories). In general: use the query string parameters for sorting instead of relying on the default, use `Strategy#page_content` instead of `Net::HTTP#get`, align the regexes with current standards, etc.

I would add that the approach in #104889 is preferable to the `scan.lazy.map` approach here. In my testing, this made three HTTP requests when we should only be making two (one for the `qtcreator` directory listing page and one for the newest major/minor version directory page).

2021-05-03 15:19 UTC, samford requested changes

2021-05-03 15:19 UTC, samford commented on Casks/qt-creator.rb
> +  end
```suggestion
  # It's necessary to check within a major/minor version directory
  # (fetching an additional page) to obtain the full version.
  livecheck do
    url "https://download.qt.io/official_releases/qtcreator/?C=M;O=D"
    strategy :page_match do |page|
      # These version directories can sometimes be empty, so this will 
      page.scan(%r{href=["']?v?(\d+(?:\.\d+)+)/?["' >]}i).lazy.map do |match|
        version_page = Homebrew::Livecheck::Strategy.page_content(url.sub("/?", "/#{match[0]}/?"))
        next if version_page[:content].blank?

        versions = version_page[:content].scan(%r{href=["']?v?(\d+(?:\.\d+)+)/?["' >]}i).map(&:first)
        next if versions.blank?

        versions
      end.reject(&:nil?).first
    end
  end
```

Here's a suggestion that synthesizes the approaches in #104889 and this PR. I won't repeat the lengthy explanation from #104889 but some of the same feedback applies here.

2021-05-07 16:54 UTC, NikolausDemmel commented
4.15 is out now :-)

2021-05-07 17:14 UTC, cho-m commented on Casks/qt-creator.rb
> +  end
Thanks @nandahkrishna and @samford.
I have added the recommendations and will look into update the some other Casks when I have the chance.

2021-05-07 20:38 UTC, miccal approved these changes

2021-05-07 20:38 UTC, merged