sublime-merge: add livecheck
Homebrew/homebrew-cask pull request #104912
Opened 2021-05-02 08:48 UTC by cho-m

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask {{cask_file}}` is error-free.
- [x] `brew style --fix {{cask_file}}` reports no offenses.

2021-05-03 07:07 UTC, SMillerDev submitted a review, later dismissed

2021-05-03 15:40 UTC, samford requested changes

2021-05-03 15:40 UTC, samford commented on Casks/sublime-merge.rb
> +    strategy :page_match
```suggestion
```

From the `brew livecheck` documentation:

> **Only use `strategy` when it's necessary**. For example, if livecheck is already using `Git` for a URL, it's not necessary to use `strategy :git`. However, if `Git` applies to a URL but we need to use `PageMatch`, it's necessary to specify `strategy :page_match`.

This URL uses `PageMatch` by default, so `strategy :page_match` isn't necessary and doesn't make a difference at the moment.

2021-05-04 02:45 UTC, miccal approved these changes

2021-05-04 02:45 UTC, merged