Use File instead of IO for file operations
Homebrew/homebrew-cask pull request #105367
Opened 2021-05-08 15:43 UTC by Rylan12

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask {{cask_file}}` is error-free.
- [x] `brew style --fix {{cask_file}}` reports no offenses.

See https://github.com/Homebrew/brew/pull/11140

Replace `IO.write` and `IO.read` with `File.write` and `File.read`, respectively, in `j`, `minecraft-server`, and `openzfs`.

Note that I was unable to test this for `openzfs` because it depends on certain macOS versions that I don't have access to (i.e. doesn't work on Big Sur).

2021-05-08 17:12 UTC, Rylan12 commented
CC @samford because I'm not sure about some of these `livecheck` blocks (especially `j`)

2021-05-08 19:46 UTC, vitorgalvao approved these changes, later dismissed

2021-05-09 14:35 UTC, samford requested changes

2021-05-09 14:35 UTC, samford commented on Casks/minecraft-server.rb
> +      "#{match[2]},#{match[1]}"
```suggestion
    url "https://minecraft.net/en-us/download/server/"
    strategy :page_match do |page|
      page.scan(%r{href=.*?/objects/(\h+)/server\.jar[^>]*>minecraft[_-]server[._-]v?(\d+(?:\.\d+)*)\.jar}i)
          .map do |match|
        "#{match[1]},#{match[0]}"
```

The `minecraft.net` URL redirects to `www.minecraft.net`, so we can update the URL to avoid the redirection.

In general, I would say it's better to always use `page.scan(regex).map do |match|` instead of `match = page.match(regex)`, as `#scan` will match all occurrences of a regex but `#match` only matches the first occurrence. `PageMatch` uses `#scan` internally and we simply leave it up to livecheck to go through the matched versions and determine which is newest (using `Version` comparison).

Basically, `#scan` will continue to work properly if the page is updated to list more than one version whereas `#match` could potentially return an incorrect result. It's a small change but it can help reduce the maintenance burden over time.

2021-05-09 14:35 UTC, samford commented on Casks/openzfs.rb
> +      "#{match[2]},#{match[1]}"
```suggestion
      page.scan(%r{href=['"]?/w/images/\d/(\h+)/openzfs[_-]on[_-]os[_-]x[._-](\d+(?:\.\d+)*)\.dmg}i).map do |match|
        "#{match[1]},#{match[0]}"
      end
```

As above, this suggestion uses `#scan` instead of `#match`.

2021-05-09 14:46 UTC, Rylan12 commented on Casks/j.rb
> +    regex(/^jv?(\d+(?:\.\d+)*)-release$/i)
Yeah, this is much better. I missed the fact that the `ReleaseNotes` pages were different from the `Installation` pages so I figured that wouldn't work. Glad it does though, this is much better 👍

2021-05-09 15:24 UTC, samford commented on Casks/minecraft-server.rb
> +      "#{match[2]},#{match[1]}"
I usually check the `homepage`, `stable`/`url`, etc. when I find a redirection somewhere in a formula/cask and update any URLs that are redirecting. In this case, the `homepage` also redirects to `https://www.minecraft.net/`, so we may want to update that while we're at it.

2021-05-09 18:33 UTC, Rylan12 commented on Casks/minecraft-server.rb
> +      "#{match[2]},#{match[1]}"
I'm happy to do whatever you prefer but the reason I split it up was because `brew style` complained that the line was too long.

2021-05-10 15:30 UTC, Bo98 approved these changes, later dismissed

2021-05-10 15:31 UTC, Bo98 commented
Thanks!

2021-05-10 15:44 UTC, samford commented on Casks/minecraft-server.rb
> +      "#{match[2]},#{match[1]}"
It may be easy to overlook but I addressed the line length issue in the suggestion above by having `.map` on a separate line (indented to align with `.scan`). This is what the current `PageMatch` `strategy` block example in the `brew livecheck` documentation (following the homebrew/cask style) does to work around longer regexes that go past the line length limit.

2021-05-10 16:18 UTC, Rylan12 commented on Casks/minecraft-server.rb
> +      "#{match[2]},#{match[1]}"
Ah, gotcha 👍

2021-05-11 06:43 UTC, SMillerDev approved these changes

2021-05-11 13:05 UTC, merged