Add initial enclave cask
Homebrew/homebrew-cask pull request #105634
Opened 2021-05-12 15:04 UTC by enclave-alistair

Initial Release of the Enclave homebrew cask.

See https://enclave.io for additional context.  I work at Enclave, and once this is accepted I'll integrate `brew bump-cask-pr` into our CI/CD flow.

---

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask {{cask_file}}` is error-free.
- [x] `brew style --fix {{cask_file}}` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask {{cask_file}}` worked successfully.
- [x] `brew install --cask {{cask_file}}` worked successfully.
- [x] `brew uninstall --cask {{cask_file}}` worked successfully.

2021-05-12 15:17 UTC, SMillerDev commented on Casks/enclave.rb
> +  end
https://docs.enclave.io/setup/windows/ seems to have the latest package version as a download link, why not make a similar page for macOS

2021-05-12 15:19 UTC, enclave-alistair commented on Casks/enclave.rb
> +  end
We absolutely will, just waiting on the homebrew cask to be publicly available (as that is intended as the primary deployment method). I can add the section before-hand if you'd rather?

2021-05-12 20:00 UTC, SMillerDev commented on Casks/enclave.rb
> +  end
If it's not released yet it actually shouldn't be a cask AFAIK.

2021-05-12 20:38 UTC, alistairjevans commented on Casks/enclave.rb
> +  end
This is the first stable release on macOS (this is not a beta or anything, I'm aware those should go elsewhere).

2021-05-12 20:40 UTC, enclave-alistair commented
This is the first stable release on macOS (this is not a beta or anything,
I'm aware those should go elsewhere).

On Wed, 12 May 2021, 21:38 Alistair Evans, ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In Casks/enclave.rb
> <https://github.com/Homebrew/homebrew-cask/pull/105634#discussion_r631380787>
> :
>
> > +  livecheck do
> +    url "https://install.enclave.io/latest/osx-homebrew-version.txt"
> +    strategy :page_match
> +    regex(/^(.*)$/)
> +  end
>
> This is the first stable release on macOS (this is not a beta or anything,
> I'm aware those should go elsewhere).
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Homebrew/homebrew-cask/pull/105634#discussion_r631380787>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQEZ2HPK5Y746EQ2Q5ORKGLTNLRMHANCNFSM44YZKQLQ>
> .
>

2021-05-12 20:44 UTC, enclave-alistair commented on Casks/enclave.rb
> +  end
This is the first stable release on macOS (this is not a beta or anything, I'm aware those should go elsewhere).

*Apologies for the extra notifications, tried to respond on email and it messed up the reply chain.

2021-05-17 09:26 UTC, enclave-alistair commented
@vitorgalvao/@miccal, is there anything additional I can do to help progress this PR? Any information you need from us?

2021-05-18 00:56 UTC, vitorgalvao requested changes
In the future, please don’t disable the checkbox that allows edits from maintainers. I could’ve already merged the required changes.

2021-05-18 00:56 UTC, vitorgalvao commented on Casks/enclave.rb
> +    strategy :page_match
Not needed.

2021-05-18 00:56 UTC, vitorgalvao commented on Casks/enclave.rb
> +    regex(/^(.*)$/)
Do `regex(/(\d+(?:\.\d+)*)/)`, for consistency with other casks.

2021-05-18 00:56 UTC, vitorgalvao commented on Casks/enclave.rb
> +  end
> I can add the section before-hand if you'd rather?

We’d rather have the page exist before accepting the cask, yes.

2021-05-18 06:19 UTC, enclave-alistair commented on Casks/enclave.rb
> +    strategy :page_match
Removed

2021-05-18 06:19 UTC, enclave-alistair commented on Casks/enclave.rb
> +    regex(/^(.*)$/)
Used new regex.

2021-05-18 06:20 UTC, enclave-alistair commented on Casks/enclave.rb
> +  end
macOS install page exists, both for deploy docs and livecheck content.

2021-05-18 06:22 UTC, enclave-alistair commented
Thanks @vitorgalvao; all requested changes are done. I did not intentionally uncheck "allow edits from maintainers", but I will make sure it is always checked on future PRs. 👍

2021-05-18 08:59 UTC, enclave-alistair commented
Looks like the `test enclave (macos-10.15)` CI stage failed due to a Github error, "GitHub Actions has encountered an internal error when running your job."

This appears to have made the `conclusion` stage get stuck somehow? It's been 'started' for 15 minutes.

2021-05-19 01:15 UTC, vitorgalvao approved these changes

2021-05-19 01:15 UTC, merged