Update pop from 5.0.4 to 5.0.10
Homebrew/homebrew-cask pull request #105992
Opened 2021-05-18 21:04 UTC by lotia

Created with `brew bump-cask-pr`.

2021-05-18 23:17 UTC, carlocab approved these changes, later dismissed

2021-05-19 03:35 UTC, cho-m commented
Looks like Pop has changed behavior of website that we were using for `livecheck`.

I couldn't find an alternative, but will wait to see if anyone else finds one.
If nothing is available, we will probably need to just skip livecheck.

From basic scan through network capture, I only see some version information being passed over WebSocket (wss://).

2021-05-19 12:31 UTC, lotia commented
Thanks for the comments and for looking into it @cho-m I had a look at the available strategies and none of them look like they will work for the updated download page.

My *clearly limited* understanding of the PageMatch and Git strategies is that they both depend on some parseable content being returned at the specified livecheck URL. There isn't a page that returns version parseable data that can be used to determine a version. I've updated the PR having skipped the livecheck.

2021-05-19 23:17 UTC, carlocab commented
@samford or @nandahkrishna may have ideas here. (Sorry, both. Had to call in the experts...)

2021-05-19 23:20 UTC, nandahkrishna commented
Seems like we might be able to check https://pop.com/download/mac? There's some text there (`Version 5.0.10`) which we can match.

2021-05-19 23:23 UTC, samford commented
> Seems like we might be able to check https://pop.com/download/mac? There's some text there (`Version 5.0.10`) which we can match.

Unfortunately it's rendered using JavaScript (i.e., the text isn't in the HTML). I'm digging around to see if I can find where the version information comes from.

2021-05-19 23:25 UTC, cho-m commented
When I last checked, the version was sent over WebSockets
If I block firebase.io, the version is not able to display.

2021-05-19 23:42 UTC, samford requested changes
I didn't see any available alternatives that we can check, so I'm fine with skipping this. I've added some suggestions that explain the situation in a preceding comment and clarify the `skip` message.

2021-05-19 23:42 UTC, samford commented on Casks/pop.rb
>    livecheck do
```suggestion
  # The download page (https://pop.com/download/mac) is rendered using
  # JavaScript and the version information is sent over a WebSocket connection.
  # As such, we can't check it and there don't appear to be any alternatives.
  livecheck do
```

2021-05-19 23:42 UTC, samford commented on Casks/pop.rb
> +    skip "File listing unavailable"
```suggestion
    skip "Version information not available in a checkable format"
```

2021-05-19 23:53 UTC, vitorgalvao approved these changes

2021-05-19 23:59 UTC, merged

2021-05-20 00:02 UTC, samford commented on Casks/pop.rb
> +    # As such, we can't check it and there don't appear to be any alternatives.
@vitorgalvao  For what it's worth, we originally standardized on putting the explanatory comment before the `livecheck` block in homebrew/livecheck and this has remained true in homebrew/core. I would prefer to continue the existing approach, so this information is always in the same place.

We do have some brief inline comments within `livecheck` blocks in a small number of instances (mostly `strategy` blocks) but the general explanatory comment always comes before the `livecheck` block.

Unfortunately I wasn't fast enough to catch this before it auto-merged.

2021-05-20 00:04 UTC, vitorgalvao commented on Casks/pop.rb
> +    # As such, we can't check it and there don't appear to be any alternatives.
https://github.com/Homebrew/homebrew-cask/pull/106034

2021-05-20 09:09 UTC, lotia commented
Thanks for providing super valuable demonstration of how to do it right. Much appreciated.