Add instatus out 1.0.8
Homebrew/homebrew-cask pull request #106062
Opened 2021-05-20 13:22 UTC by ymadd

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask {{cask_file}}` is error-free.
- [x] `brew style --fix {{cask_file}}` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [] `brew audit --new-cask {{cask_file}}` worked successfully.
- [x] `brew install --cask {{cask_file}}` worked successfully.
- [x] `brew uninstall --cask {{cask_file}}` worked successfully.

2021-05-20 20:29 UTC, vitorgalvao requested changes

2021-05-20 20:29 UTC, vitorgalvao commented on Casks/instatus-out.rb
> +  livecheck do
Likely not needed. Try it without.

2021-05-20 20:29 UTC, vitorgalvao commented on Casks/instatus-out.rb
> +  name "instatus-out"
```suggestion
  name "Instatus Out"
```

This is the name of the app, not a repetition of the token.

2021-05-21 01:07 UTC, miccal commented
Thank you @ymadd.

2021-05-21 01:07 UTC, miccal approved these changes

2021-05-21 01:08 UTC, merged