Add gnosis-safe 3.1.3
Homebrew/homebrew-cask pull request #106031
Opened 2021-05-19 18:05 UTC by jcvernaleo

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [ ] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask {{cask_file}}` is error-free.
- [ ] `brew style --fix {{cask_file}}` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask {{cask_file}}` worked successfully.
- [ ] `brew install --cask {{cask_file}}` worked successfully.
- [ ] `brew uninstall --cask {{cask_file}}` worked successfully.

2021-05-19 23:50 UTC, vitorgalvao requested changes

2021-05-19 23:50 UTC, vitorgalvao commented on Casks/gnosis-safe.rb
> +  url "https://github.com/gnosis/safe-react/releases/download/v#{version}/Safe-Multisig-#{version}.dmg",
I don’t see anything on the homepage linking here.

2021-05-19 23:50 UTC, vitorgalvao commented on Casks/gnosis-safe.rb
> +  version "3.1.3"
This is not the latest version on Github.

2021-05-19 23:50 UTC, vitorgalvao commented on Casks/gnosis-safe.rb
> +  livecheck do
Likely unnecessary in this case.

2021-05-19 23:50 UTC, vitorgalvao commented on Casks/gnosis-safe.rb
> +  desc "Gnosis Safe Multisig Desktop Application"
From the [`desc` documentation](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/desc.md):

> `desc` is not for app slogans! Vendors’ descriptions tend to be filled with generic adjectives such as “modern” and “lightweight”. Those are meaningless marketing fluff (do you ever see apps proudly describing themselves as outdated and bulky?) which must the deleted. It’s fine to use the information on the software’s website as a starting point, but it will require editing in almost all cases.

“Desktop Application” is redundant; that’s what casks are.

2021-05-19 23:50 UTC, vitorgalvao commented on Casks/gnosis-safe.rb
> +cask "gnosis-safe" do
Doesn’t follow the [token reference](https://github.com/Homebrew/brew/blob/master/docs/Cask-Cookbook.md#token-reference).

2021-05-19 23:50 UTC, vitorgalvao commented on Casks/gnosis-safe.rb
> +  zap trash: [
If it’s just one path, it should be a string instead of an array.

2021-05-20 15:09 UTC, jcvernaleo commented on Casks/gnosis-safe.rb
> +  version "3.1.3"
I updated to 3.2.1 which is the last full release (the other tags in the release directory lack builds so they aren't useful).

2021-05-20 15:09 UTC, jcvernaleo commented on Casks/gnosis-safe.rb
> +  livecheck do
Removed.

2021-05-20 15:10 UTC, jcvernaleo commented on Casks/gnosis-safe.rb
> +  desc "Gnosis Safe Multisig Desktop Application"
Updated.  Hopefully this is better.

2021-05-20 15:10 UTC, jcvernaleo commented on Casks/gnosis-safe.rb
> +cask "gnosis-safe" do
Changed to match the name of the actual app and hopefully follow the standard.

2021-05-20 15:10 UTC, jcvernaleo commented on Casks/gnosis-safe.rb
> +  zap trash: [
Updated.

2021-05-20 15:11 UTC, vitorgalvao commented on Casks/safe-multisig.rb
> +  auto_updates false
Remove this. We only use it when it’s `true`, never when `false`.

2021-05-20 15:12 UTC, vitorgalvao commented
Good progress. But if using GitHub for the `livecheck` isn’t good enough (due to tags not having downloads), `livecheck` will need to be done base on the page.

2021-05-20 15:52 UTC, jcvernaleo commented on Casks/safe-multisig.rb
> +  auto_updates false
removed.

2021-05-20 15:53 UTC, jcvernaleo commented
Thanks for all the help!

I'm trying to work out a good livecheck scheme for this.  The fact that so many of the tags lack downloadable files complicated it a bunch of course.  Trying to find some canonical place to get the 'best' version.

2021-05-20 17:51 UTC, vitorgalvao commented
This will work:

```ruby
  livecheck do
    url "https://api.github.com/repos/gnosis/safe-react/releases"
    strategy :page_match
    regex(/(\d+(?:\.\d+)*).dmg/)
  end
```

Check the URL to see what it outputs. Then we grab on to whatever `.dmg` they have.

Pinging @samford, our resident `livecheck` expert in case there’s something better. Sam, quick recap:

* Some GitHub tags for this app do not have downloads, so they’re no good.
* Checking network connections on the home page does yield a file which has the version information, but it’s https://gnosis-safe.io/component---src-pages-index-tsx-ba83e56c466f979407fd.js and that string at the end might indicate that it’s not a fixed, long-term bet.

2021-05-21 02:57 UTC, samford requested changes

2021-05-21 02:57 UTC, samford commented on Casks/safe-multisig.rb
> +    regex(/(\d+(?:\.\d+)*).dmg/)
```suggestion
  # It's necessary to check the GitHub releases page and match versions
  # from dmg files, as not all releases provide a dmg file. Normally we avoid
  # checking the releases page and use the Git or, if necessary, GithubLatest
  # strategy but this is an exception.
  livecheck do
    url "https://github.com/gnosis/safe-react/releases"
    regex(/href=.*?Safe-Multisig[._-]v?(\d+(?:\.\d+)+)\.dmg/i)
    strategy :page_match
```

Some feedback on the previous `livecheck` block:

* `strategy` should come after other DSL method calls in a `livecheck` block (i.e., after `regex` in this instance). [The idea behind this is that we sometimes reference variables that are defined in the `livecheck` block within a `strategy` block and the values need to be set before the `strategy` block. We're not doing that here but we still standardize on having `strategy` come after other DSL method calls because it allows us to easily modify an existing `strategy` call to use a block without having to move anything around.]
* I generally try to anchor the start/end of the regex to ensure that we're only matching what we want to be matching. The standard pattern for matching the version from the filename in an `href` attribute on an HTML page does this and that's what I'm using here (though the end isn't as strict as it could be). Alternatively, if we went with the previous api.github.com check, I would have modified the regex to the following: `/["']["']*?Safe-Multisig[._-]v?(\d+(?:\.\d+)+)\.dmg["']/i` (anchoring the start/end with the quotes).
* We use case-insensitive regexes (i.e., the trailing `i` flag in `/.../i`) unless we specifically need it to be case sensitive to match. Case-sensitivity is almost always unnecessary for livecheck and avoiding it prevents checks from breaking due to simple changes in case upstream.
* It's important to remember to escape periods (`\.`) when we intend to match a period, as `.` matches anything.

---

One thing to note is that we don't use `api.github.com` in any other `livecheck` blocks in homebrew/core or homebrew/cask because it's rate limited and the limit is pretty low (60 requests an hour, I believe?). It's higher if we use authentication but we don't do this in livecheck, so we can hit the limit in certain circumstances (or if more checks using api.github.com were added over time). github.com may also do some rate limiting but it's not advertised in response headers and it seems to be much more forgiving in practice.

As a rule, we avoid checking the `releases` page for a GitHub repository if the `Git` strategy is sufficient, as the `releases` page is paginated (10 releases per page) but `Git` provides all the tags in the repository. Sometimes `Git` isn't sufficient and it's necessary to use `GithubLatest`. Between these two strategies, we almost never check a `releases` page itself.

However, for a small number of casks (zero formulae), it's necessary to check the `releases` page and match versions from an attached file (there isn't an alternative to this). This cask is one of those exceptions, so I've added an explanatory comment before the `livecheck` block in the suggestion to make it clear that this behavior shouldn't be copied under normal circumstances.

2021-05-21 13:37 UTC, jcvernaleo commented
Thanks.  All those changes you did make sense.

I don't love having to do such a special case here, but that seems to just be the way upstream works.

2021-05-23 21:12 UTC, vitorgalvao approved these changes

2021-05-23 21:12 UTC, merged