Add PortX.app version 1.1.1
Homebrew/homebrew-cask pull request #106320
Opened 2021-05-26 13:17 UTC by NetSarangComputer

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [ ] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask {{cask_file}}` is error-free.
- [ ] `brew style --fix {{cask_file}}` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask {{cask_file}}` worked successfully.
- [ ] `brew install --cask {{cask_file}}` worked successfully.
- [ ] `brew uninstall --cask {{cask_file}}` worked successfully.

2021-05-26 13:22 UTC, SMillerDev commented on Casks/portx.rb
> +  desc "Aims to provide unparalleled cross-platform session management and usability"
Is `unparalleled` a technical description? Otherwise there is no need to add it. Descriptions should not feature marketing terms.

2021-05-26 13:23 UTC, SMillerDev commented
Please add a [`zap`](https://docs.brew.sh/Cask-Cookbook#stanza-zap) stanza and a [`livecheck`](https://docs.brew.sh/Cask-Cookbook#stanza-livecheck) block

2021-05-26 13:26 UTC, NetSarangComputer commented
zap, livecheck Is it a must?

2021-05-26 13:26 UTC, NetSarangComputer commented on Casks/portx.rb
> +  desc "Aims to provide unparalleled cross-platform session management and usability"
I didn't know. I'll edit it and upload it. Thank you.

2021-05-26 14:48 UTC, SMillerDev commented on Casks/portx.rb
> +    skip "No version information available"
There is no page anywhere that shows the current latest version?

2021-05-27 00:45 UTC, miccal commented on Casks/portx.rb
> +  homepage "https://www.netsarang.com/en/"
I do not see anything on the `homepage` for this app?

2021-05-27 00:48 UTC, NetSarangComputer commented on Casks/portx.rb
> +    skip "No version information available"
Yes, sir. Not yet

2021-05-27 00:50 UTC, NetSarangComputer commented on Casks/portx.rb
> +  homepage "https://www.netsarang.com/en/"
Yes, I haven't prepared the homepage yet, so I put in the sashimi website.

2021-05-27 07:17 UTC, SMillerDev commented on Casks/portx.rb
> +    skip "No version information available"
If it's not there yet, is the app even released?

2021-05-27 07:28 UTC, NetSarangComputer commented on Casks/portx.rb
> +    skip "No version information available"
Yes, I plan to focus on the app first and create a homepage later

2021-05-27 07:31 UTC, SMillerDev commented on Casks/portx.rb
> +    skip "No version information available"
So how would people who don't use Homebrew know where to find the app?

2021-05-27 07:33 UTC, SMillerDev commented on Casks/portx.rb
> +    skip "No version information available"
> The Cask is for an app with no information on the homepage (example: a GitHub repository without a README).

https://docs.brew.sh/Acceptable-Casks#rejected-casks

2021-05-27 07:34 UTC, NetSarangComputer commented on Casks/portx.rb
> +    skip "No version information available"
Um... I haven't thought of that far.

2021-05-27 07:42 UTC, NetSarangComputer commented on Casks/portx.rb
> +    skip "No version information available"
I'm sorry. I don't understand, so please let me know what needs to be changed.

2021-05-27 08:28 UTC, NetSarangComputer commented on Casks/portx.rb
> +    skip "No version information available"
Found url to check latest version. Thank you.

2021-05-27 18:52 UTC, vitorgalvao requested changes

2021-05-27 18:52 UTC, vitorgalvao commented on Casks/portx.rb
> +  homepage "https://www.netsarang.com/en/"
Then this isn’t really a homepage and we can’t accept this cask. Software downloadable as casks must be accessible manually as well, otherwise you’re just using us as your distribution channel and adding to our maintenance burden for something few people will use.

2021-05-27 18:52 UTC, vitorgalvao commented on Casks/portx.rb
> +  desc "Let's manage all the servers by session"
From the [`desc` documentation](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/desc.md):

> `desc` is not for app slogans! Vendors’ descriptions tend to be filled with generic adjectives such as “modern” and “lightweight”. Those are meaningless marketing fluff (do you ever see apps proudly describing themselves as outdated and bulky?) which must the deleted. It’s fine to use the information on the software’s website as a starting point, but it will require editing in almost all cases.

2021-05-27 18:52 UTC, vitorgalvao commented on Casks/portx.rb
> +  url "https://cdn.netsarang.net/0ac7ea20/PortX-#{version}.dmg", verified: "cdn.netsarang.net"
Two lines; `verified` on the second.

2021-06-08 06:49 UTC, closed without merging

2021-06-08 06:49 UTC, NetSarangComputer commented
The product needs to be upgraded and newly opened