Add superintendent 1.0.0
Homebrew/homebrew-cask pull request #106866
Opened 2021-06-07 13:58 UTC by Keating950

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

2021-06-07 14:11 UTC, vitorgalvao requested changes

2021-06-07 14:11 UTC, vitorgalvao commented on Casks/superintendent.rb
> +  app "superintendent.app"
Please add a [`zap`](https://github.com/homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/zap.md). See [`homebrew-createzap`](https://github.com/nrlquaker/homebrew-createzap) for an external project which can help.

2021-06-07 14:11 UTC, vitorgalvao commented on Casks/superintendent.rb
> +  sha256 :no_check
`sha256` also needs to be set. You can find what it is by running `shasum --algorithm 256` on the downloaded file.

2021-06-08 08:10 UTC, miccal commented
Thank you for your submission @Keating950, but we cannot accept it at this time because it does not meet our [minimum notability requirements](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/rejected_casks.md):

> + The Cask is for an app that is too obscure. Examples:
>   + An app from a code repository that is not notable enough (under 30 forks, 30 watchers, 75 stars).

Please consider hosting this [in your own Tap](https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap) and if it gets notable enough we would then be happy to consider adding this to `homebrew-cask`.

2021-06-08 08:10 UTC, closed without merging