Vial branch
Homebrew/homebrew-cask pull request #108010
Opened 2021-07-02 11:04 UTC by Technofrikus

Added Vial as a cask, v0.3, has livecheck

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for a [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference). -- used the generate task token script
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask). -- I hope I understood everything correctly, but this is a stable version, even though it is still Beta.
- [x] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

2021-07-02 11:15 UTC, SMillerDev reviewed
Please add a [`zap` stanza](https://docs.brew.sh/Cask-Cookbook#stanza-zap) here. The [CreateZap](https://github.com/nrlquaker/homebrew-createzap) tool can help you with this.

2021-07-02 11:15 UTC, SMillerDev commented on Casks/vial.rb
> +  url "https://github.com/vial-kb/vial-gui/releases/download/v#{version}/Vial-v#{version}.dmg", verified: "https://github.com/vial-kb/vial-gui"
```suggestion
  url "https://github.com/vial-kb/vial-gui/releases/download/v#{version}/Vial-v#{version}.dmg",
        verified: "https://github.com/vial-kb/vial-gui"
```

2021-07-02 11:15 UTC, SMillerDev commented on Casks/vial.rb
> +  end
This is the default

2021-07-02 17:26 UTC, Technofrikus commented
> Please add a [`zap` stanza](https://docs.brew.sh/Cask-Cookbook#stanza-zap) here. The [CreateZap](https://github.com/nrlquaker/homebrew-createzap) tool can help you with this.

Not sure if I have to comment. I added the zap stanza.

2021-07-03 00:42 UTC, bevanjkay commented
@Technofrikus Can you try to fix the style errors? Running `brew style --fix vial` in your branch should fix most of them, and flag any that can't be fixed automatically.

2021-07-03 10:04 UTC, Technofrikus commented
It seems the only problem now is that it is not stable version, just beta. But Vial can be considered stable in my experience and there is not stable version. So it should be added to the main repo nonetheless in my opinion.

2021-07-03 10:53 UTC, bevanjkay commented
@Technofrikus Pending feedback from other maintainers, #108050 should allow the CI to pass

2021-07-03 13:00 UTC, vitorgalvao requested changes

2021-07-03 13:00 UTC, vitorgalvao commented on Casks/vial.rb
> +  livecheck do
Why did you readd this? I removed it for a reason. As @SMillerDev said, this is the default, it’s redundant in this case and works without it.

2021-07-03 13:20 UTC, Technofrikus commented on Casks/vial.rb
> +  livecheck do
I am new to really committing on github and find the interface and system pretty complicated. Wasnt on purpose, sorry.  And honestly dont know what you or SMillerDev are referring to. I cant see a difference to my livecheck code.

2021-07-03 13:23 UTC, bevanjkay commented on Casks/vial.rb
> +  livecheck do
@technofrikus The livecheck code isn't necessary when the download URL is from Github. It is inferred from the URL.

2021-07-03 13:32 UTC, vitorgalvao submitted a review, later dismissed

2021-07-03 13:35 UTC, vitorgalvao commented
Verified locally. Merging due to https://github.com/Homebrew/homebrew-cask/pull/108050#issuecomment-873408387.

2021-07-03 13:36 UTC, merged