Add sleek v1.0.8
Homebrew/homebrew-cask pull request #108139
Opened 2021-07-05 20:26 UTC by ransome1

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

2021-07-05 20:31 UTC, ransome1 commented
Dear reviewers.

I (the maintainer and one of the developers of sleek) understand this project has not reached 30 watchers yet, but it has already thrice the stars that are the minimum requirement and almost 30 forks. sleek is being actively developed and I'm sure quite some users would appreciate the app to be available on brew.

2021-07-06 12:53 UTC, bevanjkay requested changes

2021-07-06 12:53 UTC, bevanjkay commented on Casks/sleek.rb
> +  end
@ransome1 The livecheck stanza can be removed as it is implied when the URL stanza is from Github.

2021-07-06 12:54 UTC, bevanjkay requested changes, later dismissed

2021-07-06 12:54 UTC, bevanjkay commented on Casks/sleek.rb
> +  zap trash: "~/Library/Application Support/sleek"
There are some files/folders missing from the zap stanza

```suggestion
zap trash: [
    "~/Library/Application Support/sleek",
    "~/Library/Saved Application State/RobinAhle.sleektodomanager.savedState",
    "~/Library/Preferences/RobinAhle.sleektodomanager.plist",
  ]
```

2021-07-06 14:49 UTC, ransome1 commented on Casks/sleek.rb
> +  zap trash: "~/Library/Application Support/sleek"
Thanks!

2021-07-08 01:49 UTC, bevanjkay approved these changes

2021-07-08 01:54 UTC, merged

2021-07-08 01:55 UTC, bevanjkay commented
Thanks @ransome1

2021-07-08 04:07 UTC, ransome1 commented
@bevanjkay thanks for your help!