Update aqua-data-studio from 21.0.3 to 22.0.0
Homebrew/homebrew-cask pull request #109121
Opened 2021-07-25 18:36 UTC by FnControlOption

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

2021-07-26 02:36 UTC, bevanjkay commented
Ping @samford for review

2021-07-26 15:07 UTC, samford requested changes
I've added a suggestion that follows the same basic idea but makes fewer assumptions. The suggested `livecheck` block is more in line with how we've approached checks in homebrew/core that require fetching more than one page.

A few things to note:

* I removed the `path` variable, as I would prefer to avoid establishing a precedent of defining variables outside of the provided `livecheck` block DSL methods. We can avoid duplicating the URL by using `URI#join` to combine the base `url` with the path to the changelog page for a given version. This also stands a better chance of continuing to work if the URLs on the changelog page are modified in the future.
* I've tweaked the regex to capture the entire `href` attribute value (to feed to `URI#join`) and I've made the preceding path a little looser (i.e., we usually include the minimum that's necessary to accurately match what we want).
* This gracefully fails when we're unable to match major/minor versions from URLs on the changelog page.
* This sorts versions from the changelog page, parsing the major/minor version strings as `Version`s and comparing them. This allows us to identify the newest major/minor version without assuming that the first match on the page will always be the newest version.
* This doesn't assume that the version from the changelog page URLs will always be only a major/minor version. I modified the regex to be able to match longer versions (whereas the existing regex would fail if this was changed) and this only appends `.0` to the `changelog_version` if it has fewer than three numeric parts separated by dots.

2021-07-26 22:13 UTC, samford requested changes

2021-07-27 03:27 UTC, miccal commented
Thank you @FnControlOption and @samford.

2021-07-27 03:27 UTC, merged