Add tidelift CLI v1.0.0
Homebrew/homebrew-cask pull request #111569
Opened 2021-09-21 19:01 UTC by tyrelsouza

Initial addition of Tidelift CLI version 1.0.0

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

2021-09-21 23:05 UTC, bevanjkay requested changes

2021-09-21 23:05 UTC, bevanjkay commented on Casks/tidelift.rb
> +  binary "tidelift", target: "tidelift"
```suggestion
  binary "tidelift"
```

Target is not required unless it needs to be changed from the original.

2021-09-21 23:05 UTC, bevanjkay commented on Casks/tidelift.rb
> +    regex(%r{^.*/cli/([^/]+)/darwin/tidelift">}i)
```suggestion
    regex(%r{href=.*?/cli/v?(\d+(?:\.\d+)+)/darwin/tidelift}i)
```

2021-09-24 00:04 UTC, miccal commented
Thank you @tyrelsouza.

2021-09-24 00:04 UTC, merged