Add coolterm livecheck
Homebrew/homebrew-cask pull request #111787
Opened 2021-09-27 13:59 UTC by unitof

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask <cask>` is error-free.
- [ ] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask <cask>` worked successfully.
- [ ] `brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

2021-09-27 14:08 UTC, SMillerDev commented on Casks/coolterm.rb
> +    regex(%r{<center>([0-9.]+)<br>05/31/2021</center>}i)
I don't think that will work with the next update (when the date changes). https://freeware.the-meiers.org/CoolTerm_ReadMe.txt.html is likely a better location to check.

2021-09-27 14:09 UTC, unitof commented on Casks/coolterm.rb
> +    regex(%r{<center>([0-9.]+)<br>05/31/2021</center>}i)
lol, forgot I had hardcoded the date while testing—but good point on the README. On it.

2021-09-27 15:15 UTC, SMillerDev commented
@samford @nandahkrishna opinions?

2021-09-27 16:20 UTC, samford requested changes
I'm good with checking the `README` page, as it would be challenging to reliably identify the `coolterm` version on the homepage. Neither the RSS feed nor the "Announcements" section of the forum contain the latest version (`1.9.0`), so we can also rule those out.

As an aside, if we were to check the homepage, we would use `url :homepage` here. The trailing `#CoolTerm` fragment doesn't make a difference in this particular context and we avoid creating a duplicate URL in a `livecheck` block that can be referenced with a symbol (e.g., `url`/`homepage` for casks, `stable`/`homepage`/`head` for formulae).

I've added a suggested regex for the `README` page below.

2021-09-27 17:35 UTC, unitof commented on Casks/coolterm.rb
> +    regex(/VERSION HISTORY.*\n=+(?:<br>|\n)+([0-9.]+):/i)
Thanks for the rundown!

The app does weirdly have a `Check for updates…` menu option which display a dialogue box showing current & newest version (though it doesn't auto-update). This would indicate to me there's a machine-readable version number _somewhere_, but Charles Proxy isn't showing me _anything_ detectible when I run it, even intentionally downloading an old version of CoolTerm.

2021-09-27 18:38 UTC, samford commented on Casks/coolterm.rb
> +    regex(/VERSION HISTORY.*\n=+(?:<br>|\n)+([0-9.]+):/i)
I had to use the proxy setting in the app preferences (not the macOS system-wide proxy) to capture it. The app appears to check `http://freeware.the-meiers.org/version/CoolTerm.ver`, which simply returns `1.9.0.3.1.948` (`Content-Type` is `application/octet-stream`). It's possible to check this (e.g., `regex(/^\s*v?(\d+(?:\.\d+)+)\s*$/i)`) but we would have to either modify the cask `version` or selectively use the first three numeric parts of the upstream version.

This would align with the update-checking functionality in the application but I'll defer to our homebrew/cask maintainers about whether this approach would be more desirable. I know we have some other cask `livecheck` blocks that work with a response like this but I'm unsure of how we would want to handle the version mismatch.

In general, I'm not overly fond of the idea of naively truncating the longer version to the first three numeric parts, as that wouldn't work correctly if they ever released a version with four numeric parts in the future like `1.9.0.1` (unlikely but not impossible). From my perspective, it's more a question of whether updating the cask to use the longer version makes sense.

2021-09-27 23:54 UTC, bevanjkay commented on Casks/coolterm.rb
> +    regex(/VERSION HISTORY.*\n=+(?:<br>|\n)+([0-9.]+):/i)
I would support using the longer version formatting as the app version.

The `info.plist` inside the `CoolTerm.app` includes;
```
   <key>CFBundleVersion</key>
   <string>1.9.0.3.948</string>
```

I am not sure where the extra `.1` is coming from in the returned version from upstream, but as the download is unversioned for this cask, we simply use the livecheck to return that upstream is reporting a new version available (which in this case should then align with the in-app updating experience).

@unitof We should also include `auto_updates true` - so that `brew upgrade` only updates `coolterm` when the `--greedy` flag is passed.

2021-09-28 00:08 UTC, unitof commented on Casks/coolterm.rb
> +    regex(/VERSION HISTORY.*\n=+(?:<br>|\n)+([0-9.]+):/i)
Note that it does **not** auto-upgrade. Just kicks off to the homepage. My understanding of the docs is that it should not be marked `auto_update` for that.

PS: nice catch @samford!

2021-09-28 00:21 UTC, unitof commented
Okay, working on a `livecheck` that simply pulls the version returned from http://freeware.the-meiers.org/version/CoolTerm.ver.

I do wish the current version were listed at http://freeware.the-meiers.org/previous/, but indeed only past versions are.

2021-09-28 01:00 UTC, bevanjkay commented on Casks/coolterm.rb
> +    regex(/VERSION HISTORY.*\n=+(?:<br>|\n)+([0-9.]+):/i)
> Note that it does **not** auto-upgrade. Just kicks off to the homepage when a newer version is detected. My understanding of the docs is that it should not be marked `auto_update` for that.

No worries, I hadn't noticed that.

2021-09-28 01:00 UTC, samford requested changes

2021-09-28 01:12 UTC, unitof commented on Casks/coolterm.rb
> +    regex(/([0-9.]+)/i)
Right! Thanks for reminder—done.

2021-09-28 01:25 UTC, samford requested changes

2021-09-28 01:25 UTC, samford commented on Casks/coolterm.rb
> +    url "http://freeware.the-meiers.org/version/CoolTerm.ver"
```suggestion
    url "https://freeware.the-meiers.org/version/CoolTerm.ver"
```

I overlooked this when I was commenting on the regex but let's use the HTTPS URL here, since the upstream server supports it.

2021-09-28 01:28 UTC, samford approved these changes
I can't approve/merge this (I don't have commit access in homebrew/cask) but the changes look good to me at this point. Thanks, @unitof!

2021-09-28 01:32 UTC, merged

2021-09-28 01:32 UTC, bevanjkay commented
Thanks @unitof 
And as always @samford huge appreciation for your detailed responses!