Add IBM Semeru Cask
Homebrew/homebrew-cask pull request #112084
Opened 2021-10-04 19:07 UTC by mbarbero

I've verified that:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask ibm-semeru-jdk-open` is error-free.
- [x] `brew style --fix ibm-semeru-jdk-open` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask ibm-semeru-jdk-open` worked successfully.
- [x] `brew install --cask ibm-semeru-jdk-open` worked successfully.
- [x] `brew uninstall --cask ibm-semeru-jdk-open` worked successfully.

2021-10-04 19:13 UTC, gdams requested changes
A few changes, also reading the [token-reference](https://docs.brew.sh/Cask-Cookbook#token-reference) document, my interpretation would be that this cask should be called `semuru-jdk-open` (remove the `IBM`)

2021-10-04 19:13 UTC, gdams commented on Casks/ibm-semeru-jdk-open.rb
> +  arch = "x64"
The `arch` definition is not really needed here. I'd suggest putting it inline

2021-10-04 19:13 UTC, gdams commented on Casks/ibm-semeru-jdk-open.rb
> +  openj9 = "openj9-0.27.0"
I'd prefer to have the OpenJ9 version as part of the version string

2021-10-04 19:14 UTC, gdams commented on Casks/ibm-semeru-jdk-open.rb
> +cask "ibm-semeru-jdk-open" do
Change the cask name to `semuru-jdk-open`

2021-10-04 19:21 UTC, gdams commented
Much of the background/context of IBM Semuru/OpenJ9 is discussed in https://github.com/docker-library/official-images/pull/10666.

2021-10-05 09:39 UTC, bevanjkay commented
@mbarbero Can you please reopen this PR from a branch on your fork so that `homebrew-cask` maintainers can push commits here?

2021-10-05 09:41 UTC, mbarbero commented
> @mbarbero Can you please reopen this PR from a branch on your fork so that `homebrew-cask` maintainers can push commits here?

Sure. Closing this one then.

2021-10-05 09:41 UTC, closed without merging

2021-10-05 09:54 UTC, bevanjkay commented
Thanks @mbarbero