Add AppFlowy 0.0.2
Homebrew/homebrew-cask pull request #115114
Opened 2021-11-30 19:33 UTC by stephengroat

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

2021-11-30 20:41 UTC, bevanjkay commented on Casks/appflowy.rb
> +  desc "Open-source alternative to Notion"
@stephengroat The `desc` should describe what the software does (including for somebody who doesn't know what Notion is). See the [`desc` docs](https://docs.brew.sh/Cask-Cookbook#stanza-desc) for examples.

2021-11-30 20:41 UTC, bevanjkay requested changes
@stephengroat Thanks for your contribution.
Please try to add a [zap stanza](https://docs.brew.sh/Cask-Cookbook#stanza-zap). The linked documentation provides some recommended methods to create it.

2021-11-30 23:34 UTC, stephengroat commented on Casks/appflowy.rb
> +  desc "Open-source alternative to Notion"
addressed in 562be83

2021-11-30 23:34 UTC, stephengroat commented
> @stephengroat Thanks for your contribution. Please try to add a [zap stanza](https://docs.brew.sh/Cask-Cookbook#stanza-zap). The linked documentation provides some recommended methods to create it.

addressed in 562be83

2021-11-30 23:35 UTC, bevanjkay submitted a review, later dismissed

2021-12-01 00:07 UTC, miccal commented
/rebase

2021-12-01 08:51 UTC, bevanjkay commented
/rebase

2021-12-01 09:03 UTC, merged

2021-12-01 09:03 UTC, bevanjkay commented
Thank you @stephengroat