Update cask to include URLs for Intel and ARM packages
Homebrew/homebrew-cask pull request #118623
Opened 2022-02-03 17:46 UTC by vkarve-chef

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask <cask>` worked successfully.
- [ ] `brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

2022-02-04 03:20 UTC, miccal requested changes

2022-02-04 03:20 UTC, miccal commented on Casks/chef-workstation.rb
> +  end
```suggestion
  version "22.1.778"

  if Hardware::CPU.intel?
    sha256 "b957dca3a7be28373a718e95f88290c5be928985ac08b37b8c83b1ac1330d4db"
  else
    sha256 "728ff9458a7f73618a9a34ccd5cb41962ce061f2d67ef2e58e19dd0251c528a5"
  end
```

2022-02-04 05:26 UTC, vkarve-chef commented on Casks/chef-workstation.rb
> +  end
@miccal, an earlier version did have the sha256 as specified in the suggested change. i intentionally moved it outside the if-else block. we have a script that updates the package version, sha256 values and then creates a PR. writing it this way makes it easier for find-replace using regex.
if bump-cask-pr automation handles the condition based sha256 update, please let me know. i can then update cask as you suggest.

2022-02-04 05:38 UTC, miccal commented on Casks/chef-workstation.rb
> +  end
Yes `bump-cask-pr` handles this fine -- please change it to be consistent with our other Casks.

2022-02-04 14:44 UTC, vkarve-chef commented on Casks/chef-workstation.rb
> +  end
done

2022-02-04 14:44 UTC, vkarve-chef commented on Casks/chef-workstation.rb
> +  end
done

2022-02-04 15:25 UTC, carlocab commented on Casks/chef-workstation.rb
> +  macos_version = Hardware::CPU.intel? ? "10.15" : "11"
```suggestion
  arch, macos_version = Hardware::CPU.intel? ? ["x86_64", "10.15"] : ["arm64", "11"]
```

2022-02-07 13:25 UTC, carlocab commented
/rebase

2022-02-07 15:17 UTC, vkarve-chef commented
closing as the same changes are added in another [PR](https://github.com/Homebrew/homebrew-cask/pull/118816) that addresses the merge conflict.

2022-02-07 15:17 UTC, closed without merging