add zap to mechvibes
Homebrew/homebrew-cask pull request #119087
Opened 2022-02-12 18:46 UTC by spinofdoom

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask <cask>` worked successfully.
- [ ] `brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

2022-02-13 12:35 UTC, bevanjkay commented on Casks/mechvibes.rb
> +    "~/mechvibes_custom",
@spinofdoom Are you able to verify what files are stored in the `mechvibes_custom` folder?

I would like to confirm that the following won't be deleted;
-  `Files created by the user directly.`
See https://docs.brew.sh/Cask-Cookbook#stanza-zap

2022-02-13 20:56 UTC, spinofdoom commented on Casks/mechvibes.rb
> +    "~/mechvibes_custom",
It's an empty directory: 
`$ ls -A ~/mechvibes_custom`
`$`

2022-02-13 21:55 UTC, neutric commented on Casks/mechvibes.rb
> +    "~/mechvibes_custom",
Empty here means "to be filled by user". This directory holds [custom sound packs added by the user](https://mechvibes.com/index.php/soundpacks/), so shouldn't be zapped.

2022-02-14 01:02 UTC, miccal requested changes

2022-02-14 01:14 UTC, miccal commented
Thank you @spinofdoom.

2022-02-14 01:14 UTC, miccal approved these changes

2022-02-14 01:14 UTC, merged