add zap to copytranslator
Homebrew/homebrew-cask pull request #119106
Opened 2022-02-12 22:04 UTC by spinofdoom

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask <cask>` worked successfully.
- [ ] `brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

2022-02-13 22:00 UTC, neutric commented on Casks/copytranslator.rb
> +    "~/copytranslator",
> Vast interface language to choose from and you are able to create or download locale language files.

says https://github.com/CopyTranslator/CopyTranslator. `locales` shouldn't be zapped.

2022-02-14 01:06 UTC, miccal requested changes

2022-02-14 01:06 UTC, miccal commented on Casks/copytranslator.rb
> +    "~/copytranslator",
```suggestion
    "~/copytranslator/copytranslator.json",
    "~/copytranslator/localShortcuts.json",
    "~/copytranslator/shortcuts.json",
    "~/copytranslator/styles.css",
  ],
      rmdir: "~/copytranslator/locales"
```

2022-02-14 01:14 UTC, miccal approved these changes

2022-02-14 01:18 UTC, merged