Add libcblite and libcblite-community v3.0.0
Homebrew/homebrew-cask pull request #119690
Opened 2022-02-26 00:43 UTC by borrrden

- [X] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [X] `brew audit --cask <cask>` is error-free.
- [X] `brew style --fix <cask>` reports no offenses.
- [X] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [X] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [X] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [X] `brew audit --new-cask <cask>` worked successfully.
- [X] `brew install --cask <cask>` worked successfully.
- [X] `brew uninstall --cask <cask>` worked successfully.

2022-02-26 01:09 UTC, borrrden commented
I tried to retroactively please the check commit format bot, but I guess once the failed label is present it never goes away.

2022-02-26 06:44 UTC, bevanjkay requested changes, later dismissed

2022-02-26 06:44 UTC, bevanjkay commented on Casks/libcblite.rb
> +    regex(/^\d+\.\d+\.\d+(?:-[a-z0-9]+)?$/i)
The following adheres to prevailing standards for livecheck regex.
Unless the version is subject to change in format?

```suggestion
    regex(/^(\d+(?:\.\d+)+)$/i)
```

2022-02-26 06:44 UTC, bevanjkay commented on Casks/libcblite.rb
> +  artifact "libcblite-#{version.split("-").first}/include/cbl", target: "#{HOMEBREW_PREFIX}/include/cbl"
Is there `version.split` required?

2022-02-26 06:44 UTC, bevanjkay commented on Casks/libcblite.rb
> +end
Please try to add a [zap stanza](https://docs.brew.sh/Cask-Cookbook#stanza-zap). The linked documentation provides some recommended methods to create it.

2022-02-28 11:59 UTC, borrrden commented on Casks/libcblite.rb
> +    regex(/^\d+\.\d+\.\d+(?:-[a-z0-9]+)?$/i)
I initially made this regex to accommodate potential beta versions (e.g. 3.0.0-beta02) but now I realize that it's not appropriate here since beta versions go to a different repo.  I'll simplify this.

2022-02-28 12:00 UTC, borrrden commented on Casks/libcblite.rb
> +  artifact "libcblite-#{version.split("-").first}/include/cbl", target: "#{HOMEBREW_PREFIX}/include/cbl"
Not for stable versions, will remove.

2022-02-28 12:04 UTC, borrrden commented on Casks/libcblite.rb
> +end
I saw the zap stanza information but I still don't quite understand the purpose.  If I put this logic into a zap stanza then by default the uninstall leaves these symlinks dangling behind pointing to nothing right?  Is there an advantage to doing it this way?  Should I put all of the uninstall postflight logic into zap?

2022-02-28 22:59 UTC, borrrden commented on Casks/libcblite.rb
> +end
Furthermore, if the user forgets to zap then the package can no longer be installed as the files created by the postflight already exist and cause an error.

2022-03-01 00:36 UTC, bevanjkay commented on Casks/libcblite.rb
> +end
@borrrden Sorry for the confusion, the reference to the [zap stanza](https://docs.brew.sh/Cask-Cookbook#stanza-zap) should not have corresponded with your uninstall stanza (it was meant to be commented at the end of the file. Have a look at the docs and it will provide some ways to find out if there are extra files that could be optionally removed on uninstall.

2022-03-01 01:43 UTC, borrrden commented on Casks/libcblite.rb
> +end
Ah ok, sorry I misunderstood then.  I tried running the `createzap` command and it said no settings found.  This is an SDK and the two symlinks I make in postflight are literally all that are created aside from the normal artifact fanfare.  I followed the lead of some other PRs I found and added a comment indicating no zap.  I hope this is sufficient.

2022-03-01 01:57 UTC, miccal requested changes

2022-03-01 01:57 UTC, miccal commented on Casks/libcblite.rb
> +    regex(/^\d+\.\d+\.\d+$/i)
```suggestion
    regex(/(\d+(?:\.\d+)+)/i)
```

2022-03-01 01:57 UTC, miccal commented on Casks/libcblite.rb
> +  name "libcblite"
```suggestion
  name "Couchbase Lite (Enterprise)"
```

2022-03-01 01:57 UTC, miccal commented on Casks/libcblite-community.rb
> +  name "libcblite-community"
```suggestion
  name "Couchbase Lite (Community)"
```

2022-03-01 02:26 UTC, borrrden commented on Casks/libcblite.rb
> +    regex(/^\d+\.\d+\.\d+$/i)
Our versions always have exactly three digits in them.  Even so, is this regex preferred for some reason?

2022-03-01 02:28 UTC, miccal commented on Casks/libcblite.rb
> +    regex(/^\d+\.\d+\.\d+$/i)
Yes please, it is standard for our `livecheck` blocks.

2022-03-01 02:47 UTC, miccal approved these changes

2022-03-01 02:48 UTC, miccal commented
Thank you @borrrden, great work here.

2022-03-01 02:48 UTC, merged