Add pingnoo version 2021.04.30
Homebrew/homebrew-cask pull request #120000
Opened 2022-03-04 07:30 UTC by chmac

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

2022-03-04 10:47 UTC, SMillerDev requested changes
Please add a [`zap` stanza](https://docs.brew.sh/Cask-Cookbook#stanza-zap) here. The [CreateZap](https://github.com/nrlquaker/homebrew-createzap) tool can help you with this.

2022-03-04 10:47 UTC, SMillerDev commented on Casks/pingnoo.rb
> +  version "2021.04.30-develop"
Is this a pre-release?

2022-03-04 13:30 UTC, neutric commented on Casks/pingnoo.rb
> +  end
`version` is identical with the tag on GitHub, so the whole `livecheck` block can be dropped in favor of the default, implicit `livecheck`.

2022-03-04 13:32 UTC, neutric commented on Casks/pingnoo.rb
> +  version "2021.04.30-develop"
There aren't any stable versions yet, they are all labelled with `-develop`.

2022-03-04 18:47 UTC, chmac commented on Casks/pingnoo.rb
> +  version "2021.04.30-develop"
This is the "latest" version, but it's not yet at a 1.0 "stable" release is my understanding. I asked the question [here](https://github.com/nedrysoft/pingnoo/issues/96) and that's what I understood. I also tried to figure out if only stable software is accepted in brew casks but I couldn't understand that from the docs. Sorry if I missed something crucial and this cask doesn't meet the requirements.

2022-03-04 18:49 UTC, chmac commented on Casks/pingnoo.rb
> +  end
Okay, I'll try that, I think I got the format wrong for GithubLatest because I tried it but that didn't work.

2022-03-04 23:01 UTC, neutric commented on Casks/pingnoo.rb
> +  version "2021.04.30-develop"
All good, see [relevant](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version) passage in the docs. :)

2022-03-04 23:09 UTC, neutric commented on Casks/pingnoo.rb
> +  end
You most likely didn't give it a regex to account for the non-standard `version` (add on new line after `strategy :github_latest`, apologies for not including that earlier: `regex(%r{href=.*?/tag/v?(\d+(?:\.\d+)+-develop)["' >]}i)`

2022-03-05 00:29 UTC, neutric commented on Casks/pingnoo.rb
> +
One more thing: please add `depends_on macos: ">= :high_sierra"` as per `homepage`.

2022-03-08 09:45 UTC, chmac commented on Casks/pingnoo.rb
> +  end
@neutric It seems that something isn't working with the GitHub latest strategy:

```
brew livecheck --debug pingnoo

Cask:             pingnoo
Livecheckable?:   Yes

URL (url):        https://github.com/nedrysoft/pingnoo/releases/download/2021.04.30-develop/Pingnoo.2021.04.30-develop.universal.dmg
Strategy:         GithubLatest
URL (strategy):   https://github.com/nedrysoft/pingnoo/releases/latest
URL (final):      https://github.com/nedrysoft/pingnoo/releases/tag/2021.04.30-develop
Regex (strategy): /href=.*?\/tag\/v?(\d+(?:\.\d+)+)["' >]/i
Error: pingnoo: Unable to get versions
```

I tried debugging it before submitting the PR and I always got this:

```
audit for pingnoo: failed
 - Version '2021.04.30-develop' differs from '' retrieved by livecheck.
Error: 1 problem in 1 cask detected
```

What do you think makes sense? Try to submit a bug report for the GitHub latest strategy and then wait for that to be fixed? Stick with the regex approach? Something else?

2022-03-08 09:47 UTC, chmac commented on Casks/pingnoo.rb
> +
I've added this and force pushed. I have it in my head that it's only supposed to be 1 commit in the PR, but maybe that's not accurate. Anyway, added the dependency.

Thanks for the tip, I hadn't thought about that at all.

2022-03-08 09:53 UTC, chmac commented
> Please add a [`zap` stanza](https://docs.brew.sh/Cask-Cookbook#stanza-zap) here. The [CreateZap](https://github.com/nrlquaker/homebrew-createzap) tool can help you with this.

No zap is required, so I added a `# No zap stanza required` comment.

2022-03-08 10:37 UTC, SMillerDev submitted a review, later dismissed
Lgtm

2022-03-08 11:35 UTC, neutric commented on Casks/pingnoo.rb
> +  end
@chmac Looks like the `-develop` part is missing from the regex I posted in my previous msg. Try with that, please.

2022-03-08 11:39 UTC, neutric commented
> Lgtm

Please don't merge. `strategy :github_latest` with a non-default regex works and is preferrable to scraping the website.

2022-03-08 20:36 UTC, chmac commented on Casks/pingnoo.rb
> +  end
@neutric Ah, gotcha, sorry, I misunderstood, I didn't realise that the regex property was also possible alongside the GitHub Latest strategy, my bad. You're right, adding the regex does absolutely work.

I've tweaked the regex a little, I'm worried it will break if there's a version which is not `-develop` so I reworked it to accept any `NNNN.NN.NN-x` where N is digit and x is a word. If you think your version was more appropriate, just let me know and I'll happily update it.

Otherwise, thanks for all the help to get this merged, my ruby skills are zero so even just your snipped showing how to actually use the `:github_latest` strategy was a huge help.

2022-03-08 20:41 UTC, chmac commented
I think this is ready to go now. Thanks a lot @neutric for walking me through the live check stuff, I was way out of my depth there.

2022-03-09 03:30 UTC, neutric commented on Casks/pingnoo.rb
> +
Multiple commits per PR are totally fine as long as they are concerned with the same cask or, if dealing with multiple casks, are the same kind of change (e.g. updating `homepage` if upstream moved to a new domain). Force-pushing removes context which may or may not be detrimental.

2022-03-09 03:35 UTC, neutric commented on Casks/pingnoo.rb
> +  end
> I've tweaked the regex a little, I'm worried it will break if there's a version which is not `-develop` so I reworked it to accept any `NNNN.NN.NN-x` where N is digit and x is a word.

Fine with making it less rigid around `-develop` but please reinstate `v?(\d+(?:\.\d+)+`. This is a Homebrew-wide default regex for dealing with version numbers and your tweak made this part more rigid. A quick bugfix might very well be versioned `NNNN.NN.NN.N` or the like.

2022-03-09 08:31 UTC, chmac commented on Casks/pingnoo.rb
> +  end
@neutric Sure thing, makes sense, pushed that change as a new commit now.

2022-03-09 08:32 UTC, chmac commented
There was another change requested from @neutric which I've added. Guessing this is ready now. 🤞

2022-03-09 08:50 UTC, chmac commented on Casks/pingnoo.rb
> +  end
Darnit, missed the last part of the regex, fixed and pushed now, hopefully this time the tests pass!

2022-03-09 10:35 UTC, chmac commented on Casks/pingnoo.rb
> +  # No zap stanza required
@neutric Haha, by this point you've written more of the Cask than me! Thanks.

I've pushed this change now and I'm going to stop saying that I think this is ready!

2022-03-09 22:53 UTC, bevanjkay commented
Thank you @chmac and @neutric 🥳

2022-03-09 22:53 UTC, merged