Add unicopedia-plus
Homebrew/homebrew-cask pull request #120734
Opened 2022-03-20 02:48 UTC by dahlia

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

2022-03-20 09:27 UTC, bevanjkay commented
@dahlia Please try to add a [zap stanza](https://docs.brew.sh/Cask-Cookbook#stanza-zap). The linked documentation provides some recommended methods to create it.

2022-03-20 13:23 UTC, dahlia commented
@bevanjkay Added a `zap` stanza.  Please take a look again!

2022-03-23 00:39 UTC, dahlia commented
@bevanjkay @carlocab @miccal  Friendly ping.  Could anybody review this for me?

2022-03-23 00:41 UTC, bevanjkay commented
@dahlia It looks like the tests are failing at the moment.

2022-03-23 00:43 UTC, dahlia commented
@bevanjkay Sorry to bother you!  Apparently I made a mistake during rebasing the commit.  I believe it's no problem now.  Could you take a look again?

2022-03-23 00:44 UTC, bevanjkay requested changes

2022-03-23 00:44 UTC, bevanjkay commented on Casks/unicopedia-plus.rb
> +  version "11.2.1"
Update to latest version

2022-03-23 00:44 UTC, bevanjkay commented on Casks/unicopedia-plus.rb
> +  url "https://github.com/tonton-pixel/unicopedia-plus/releases/download/v11.2.2/unicopedia-plus-mac-universal-11.2.2.dmg"
@dahlia This should still use interpolation to provide the version dynamically

```
  url "https://github.com/tonton-pixel/unicopedia-plus/releases/download/v#{version}/unicopedia-plus-mac-universal-#{version}.dmg"
```

2022-03-23 00:46 UTC, dahlia commented on Casks/unicopedia-plus.rb
> +  version "11.2.1"
Oh I missed that new release.  Fixed, thanks!

2022-03-23 00:46 UTC, dahlia commented on Casks/unicopedia-plus.rb
> +  url "https://github.com/tonton-pixel/unicopedia-plus/releases/download/v11.2.2/unicopedia-plus-mac-universal-11.2.2.dmg"
Thank you for letting me the better way.  Thanks, I fixed!

2022-03-23 01:07 UTC, bevanjkay approved these changes

2022-03-23 01:07 UTC, merged

2022-03-23 01:11 UTC, dahlia commented
Thank you for reviewing!