Add Vertcoin-Qt.app - Vertcoin-Core 0.18.0
Homebrew/homebrew-cask pull request #121692
Opened 2022-04-08 03:00 UTC by vertiond

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

2022-04-11 11:15 UTC, SMillerDev commented on Casks/vertcoin-core.rb
> +  end
Both of these would be good to report to the developers too, since they would also affect non-brew installs.

2022-04-11 11:15 UTC, SMillerDev commented on Casks/vertcoin-core.rb
> +    url "https://github.com/vertcoin/vertcoin"
This should work
```suggestion
    url :stable
```

2022-04-12 03:37 UTC, bevanjkay requested changes

2022-04-12 03:37 UTC, bevanjkay commented on Casks/vertcoin-core.rb
> +  end
The livecheck block should be able to be omitted as it will be inferred automatically from the url.

2022-04-19 13:43 UTC, vertiond commented
@bevanjkay Is there anything else needed?

2022-04-19 13:53 UTC, bevanjkay approved these changes, later dismissed

2022-04-25 09:43 UTC, SMillerDev commented on Casks/vertcoin-core.rb
> +
This shouldn't be skipped, but just removed from the file
```suggestion
```

2022-04-25 17:28 UTC, vertiond commented on Casks/vertcoin-core.rb
> +
From CI with this change
```
 audit for vertcoin-core: failed
 - Version '0.18.0' differs from '30924551bae033e81e1b' retrieved by livecheck.
Error: 1 problem in 1 cask detected
```

2022-04-25 18:02 UTC, SMillerDev commented on Casks/vertcoin-core.rb
> +
I'm not sure where it's getting that. @nandahkrishna or @samford any ideas?

2022-04-25 18:11 UTC, samford commented on Casks/vertcoin-core.rb
> +
`30924551bae033e81e1b` comes from an `untagged-30924551bae033e81e1b` tag (i.e., the default `Git` strategy regex simply removes leading text before the first digit). There are a variety of other unrelated tags in the repository but we're only interested in stable tags like `0.18.0`. I'll add a `livecheck` block suggestion in a moment.

2022-04-25 18:16 UTC, samford commented on Casks/vertcoin-core.rb
> +
```suggestion

  livecheck do
    url :url
    regex(/href=.*?vertcoin[._-]v?(\d+(?:\.\d+)+)(?:[._-]osx)?\.dmg/i)
    strategy :github_latest
  end
```

It's technically possible to check the Git tags using the standard regex for tags like 1.2.3/v1.2.3 (`/^v?(\d+(?:\.\d+)+)$/i`) but this cask uses a release download, so we need to check releases instead. For now, this can simply use the `GithubLatest` strategy (with a regex that matches the version from the dmg file).

If this fails in the future (e.g., a release doesn't include the dmg file), we can switch to checking the releases page (while omitting prerelease versions using `?q=prerelease%3Afalse` in the URL).

2022-04-26 15:48 UTC, SMillerDev approved these changes

2022-04-26 23:04 UTC, merged