[google-chat-electron] add apple silicon support
Homebrew/homebrew-cask pull request #121925
Opened 2022-04-13 05:15 UTC by AdamCoulterOz

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

2022-04-13 05:32 UTC, bevanjkay commented
@AdamCoulterOz We should not be encouraging users to remove the quarantine attribute in this way as Homebrew goes to great lengths to ensure that downloaded files are quarantined.

Here is an example of an alternative caveat that could apply - https://github.com/Homebrew/homebrew-cask/pull/98527/files#diff-df256926e1a55a622db61a0ff695bd5da69b8edafef0dacc43f31c868281eb21R18-R25

2022-04-13 06:26 UTC, bevanjkay requested changes

2022-04-13 06:26 UTC, bevanjkay commented on Casks/google-chat-electron.rb
> +    WARNING: quarantining is a macOS security feature and you disable it at your own risk!
@AdamCoulterOz Please use the same structure as the referenced commit - https://github.com/Homebrew/homebrew-cask/pull/98527/files#diff-df256926e1a55a622db61a0ff695bd5da69b8edafef0dacc43f31c868281eb21R18-R25

1. Include a link to documentation upstream
2. Do not suggest running the `xattr -d com.apple.quarantine` command.

2022-04-13 06:33 UTC, AdamCoulterOz commented on Casks/google-chat-electron.rb
> +    WARNING: quarantining is a macOS security feature and you disable it at your own risk!
done

2022-04-13 06:35 UTC, bevanjkay approved these changes, later dismissed

2022-04-13 07:14 UTC, SMillerDev requested changes

2022-04-13 07:14 UTC, SMillerDev commented on Casks/google-chat-electron.rb
> +    According to the vendor (https://github.com/ankurk91/google-chat-electron#installation-mac),
The issue the developer is describing here is documented in our FAQ: https://docs.brew.sh/FAQ#why-cant-i-open-a-mac-app-from-an-unidentified-developer and doesn't actually need the quarantine removed. This caveat is therefore not needed.

2022-04-13 07:16 UTC, AdamCoulterOz commented on Casks/google-chat-electron.rb
> +    According to the vendor (https://github.com/ankurk91/google-chat-electron#installation-mac),
@SMillerDev not quite what's happening in this case, macOS doesn't say it's from an unknown developer, it says the package is corrupted.

2022-04-13 07:21 UTC, AdamCoulterOz commented on Casks/google-chat-electron.rb
> +    According to the vendor (https://github.com/ankurk91/google-chat-electron#installation-mac),
Also my I suggest that having a user need to go look at the FAQ in order to install an app where this is probably the most common problem with all cask installs isn't a great user experience. Perhaps add an additional field (or two, if you also want the developer doc reference) to the cask schema which can be marked true if the cask requires quarantine removal in order to function correctly. This way you can standardise the message to users and prompt them to look at the FAQ or whatever.

2022-04-13 07:29 UTC, SMillerDev commented on Casks/google-chat-electron.rb
> +    According to the vendor (https://github.com/ankurk91/google-chat-electron#installation-mac),
Users don't need to be reminded of documentation on every install though, once they know how to solve this issue they can use that knowledge everywhere.

Additionally, re-reading the upstream documentation there don't seem to be any issues with `brew install --cask` so that would suggest this isn't needed at all.

2022-04-13 07:41 UTC, AdamCoulterOz commented on Casks/google-chat-electron.rb
> +    According to the vendor (https://github.com/ankurk91/google-chat-electron#installation-mac),
> Users don't need to be reminded of documentation on every install though, once they know how to solve this issue they can use that knowledge everywhere.

I'm not suggesting printing out the documentation in the console, just a flag that informs them of the additional step they need to take to make it work.

> Additionally, re-reading the upstream documentation there don't seem to be any issues with `brew install --cask` so that would suggest this isn't needed at all.

No idea what you are talking about. I've just spent the last 3 hours testing this, it won't open without changing the attribute. Either it will say `unknown developer` if it's running on `darwin_x64` or `package corrupted` if its on `darwin_arm64`.

2022-04-13 07:54 UTC, AdamCoulterOz commented on Casks/google-chat-electron.rb
> +    According to the vendor (https://github.com/ankurk91/google-chat-electron#installation-mac),
<img width="467" alt="Screen Shot 2022-04-13 at 5 52 59 pm" src="https://user-images.githubusercontent.com/6822248/163127687-d0b0d0b1-51ab-425f-9939-677a6c11da54.png">

<img width="268" alt="Screen Shot 2022-04-13 at 5 53 05 pm" src="https://user-images.githubusercontent.com/6822248/163127723-fcd5bc96-e09f-4b57-8e03-1eb5ec08fd44.png">

2022-04-13 07:56 UTC, SMillerDev commented on Casks/google-chat-electron.rb
> +    According to the vendor (https://github.com/ankurk91/google-chat-electron#installation-mac),
> No idea what you are talking about. This is the line in the instructions in the upstream link I provided:

That line is for manual downloads though, not for the `brew cask` install method.

> The vendor has been getting heaps of people reporting the package corrupted issue and there needs to be a prompt for them.

All 3 of the reports on GitHub are for manual downloads though, not for brew.

2022-04-13 08:14 UTC, AdamCoulterOz commented on Casks/google-chat-electron.rb
> +    According to the vendor (https://github.com/ankurk91/google-chat-electron#installation-mac),
This rb file _is_ the definition of the brew install script. The issue of corrupted package is new as of this release which now includes darwin_arm64 for the first time. Brew casks _are a wrapper_ around the vendors manual install method. So the manual install problems _are the only relevant reference_.

We are meeting the homebrew interface contract for publishing a brew cask. You should _only_ be manually checking we've met that where you can't automate it.

2022-04-13 08:19 UTC, AdamCoulterOz commented on Casks/google-chat-electron.rb
> +    According to the vendor (https://github.com/ankurk91/google-chat-electron#installation-mac),
Also, how is that logical? Is there some magical unicorns who make the brew script running _the exact same command and package as the manual method_ make it somehow work while quarantined?

2022-04-13 11:06 UTC, AdamCoulterOz commented on Casks/google-chat-electron.rb
> +    According to the vendor (https://github.com/ankurk91/google-chat-electron#installation-mac),
> The issue the developer is describing here is documented in our FAQ: https://docs.brew.sh/FAQ#why-cant-i-open-a-mac-app-from-an-unidentified-developer and doesn't actually need the quarantine removed. This caveat is therefore not needed.

I have proven this is not the case with my screenshots, and you've now moved the goal posts. Can you please qualify what you are trying to achieve by blocking this?

2022-04-13 11:40 UTC, SMillerDev commented on Casks/google-chat-electron.rb
> +    According to the vendor (https://github.com/ankurk91/google-chat-electron#installation-mac),
> Can you please qualify what you are trying to achieve by blocking this?

Make sure bad security advice given by brew only happens when it is absolutely required.

---

After downloading the binary to check the signature:
```
$ codesign -v -f  google-chat-electron.app
> google-chat-electron.app: code has no resources but signature indicates they must be present
```

So it seems it's actually incorrectly signed and the command only disables the check Apple does before opening apps.

2022-04-15 06:09 UTC, AdamCoulterOz commented on Casks/google-chat-electron.rb
> +    According to the vendor (https://github.com/ankurk91/google-chat-electron#installation-mac),
Thanks for checking that @SMillerDev, I can follow up with the vendor now.

https://github.com/ankurk91/google-chat-electron/issues/85#issuecomment-1099881091

2022-04-15 06:12 UTC, AdamCoulterOz commented on Casks/google-chat-electron.rb
> +    According to the vendor (https://github.com/ankurk91/google-chat-electron#installation-mac),
@SMillerDev I've removed the caveat regarding quarantine completely now, but there should still be a better user experience for unknown developers than this.

2022-04-15 06:26 UTC, SMillerDev approved these changes
Thanks @AdamCoulterOz  ! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

2022-04-15 06:26 UTC, merged