Add Groestlcoin Core 22.0
Homebrew/homebrew-cask pull request #122063
Opened 2022-04-15 18:14 UTC by gruve-p

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [X] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [X] `brew audit --cask <cask>` is error-free.
- [X] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [X] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [X] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [X] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [X] `brew audit --new-cask <cask>` worked successfully.
- [X] `brew install --cask <cask>` worked successfully.
- [X] `brew uninstall --cask <cask>` worked successfully.

2022-04-19 14:43 UTC, gruve-p commented
@bevanjkay what kind of feedback is expected?

2022-04-22 07:55 UTC, gruve-p commented
@bevanjkay Why has this the label `awaiting maintainer feedback` ?

2022-04-22 08:05 UTC, bevanjkay commented
@gruve-p because the PR is waiting for a maintainer to have a proper look at. Generally, PRs won't be accepted until CI is green, but this could be a case where it may be accepted.

2022-04-22 08:13 UTC, gruve-p commented
Ahh I thought it was waiting for my feedback, thanks for the clarification !

2022-05-11 01:04 UTC, miccal requested changes

2022-05-11 01:04 UTC, miccal commented on Casks/groestlcoin-core.rb
> +  end
Please remove the `livecheck` block, as it should be automatically determined from the GitHub `url`.

2022-05-11 07:39 UTC, gruve-p commented on Casks/groestlcoin-core.rb
> +  end
The 'livecheck' block is needed to check the releases and skip the pre releases and tags.
Context: https://github.com/Homebrew/homebrew-cask/pull/121692#discussion_r857902820

2022-05-11 08:17 UTC, miccal commented on Casks/groestlcoin-core.rb
> +  end
There are no pre-releases at the moment and I have confirmed locally that the `livecheck` block is not required here, so please remove it.

2022-05-11 10:43 UTC, gruve-p commented on Casks/groestlcoin-core.rb
> +  end
Done

2022-05-11 10:53 UTC, miccal commented
Thank you @gruve-p.

2022-05-11 10:53 UTC, miccal approved these changes

2022-05-11 10:53 UTC, merged