Add keysafe v1.1.0
Homebrew/homebrew-cask pull request #122006
Opened 2022-04-14 18:13 UTC by grahammiln

Add Miln Keysafe v1.1.0 from https://miln.eu/keysafe

Tested with tap `miln-eu/miln-eu`.

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask keysafe` is error-free.
- [x] `brew style --fix keysafe` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask keysafe` worked successfully.
- [x] `brew install --cask keysafe` worked successfully.
- [x] `brew uninstall --cask keysafe` worked successfully.

2022-04-18 07:35 UTC, bevanjkay requested changes

2022-04-18 07:35 UTC, bevanjkay commented on Casks/keysafe.rb
> +    regex(/miln-keysafe-v(\d+\.\d+\.\d+)-darwin-universal\.zip/i)
```suggestion
    regex(/miln-keysafe[._-]v?(\d+(?:\.\d+)+)-darwin-universal\.zip/i)
```

2022-04-19 08:37 UTC, bevanjkay approved these changes

2022-04-19 08:45 UTC, SMillerDev approved these changes

2022-04-19 12:30 UTC, merged