Add TomatoBar.app v3.3.0
Homebrew/homebrew-cask pull request #122799
Opened 2022-05-01 15:44 UTC by cayacdev

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

2022-05-01 23:12 UTC, bevanjkay requested changes
Please try to add a [zap stanza](https://docs.brew.sh/Cask-Cookbook#stanza-zap). The linked documentation provides some recommended methods to create it.

2022-05-01 23:12 UTC, bevanjkay commented on Casks/tomatobar.rb
> +  desc "🍅 World's neatest Pomodoro timer for menu bar"
From the Cask cookbook - [Do not use empty marketing jargon.](https://docs.brew.sh/Cask-Cookbook#stanza-desc)
```suggestion
  desc "Menu bar pomodoro timer"
```

2022-05-02 17:40 UTC, cayacdev commented
> Please try to add a [zap stanza](https://docs.brew.sh/Cask-Cookbook#stanza-zap). The linked documentation provides some recommended methods to create it.

Thank you for your review. I added a zap stanza and applied your suggestion for the description.

2022-05-02 23:32 UTC, bevanjkay requested changes

2022-05-02 23:32 UTC, bevanjkay commented on Casks/tomatobar.rb
> +  name "tomato-bar"
```suggestion
  name "TomatoBar"
```

2022-05-03 00:11 UTC, bevanjkay commented on Casks/tomatobar.rb
> +  name "tomato-bar"
@cayacdev After this last change it should be good to go.

2022-05-08 10:14 UTC, bevanjkay approved these changes

2022-05-08 10:14 UTC, merged