Add Mx Power Gadget 1.2 to cask
Homebrew/homebrew-cask pull request #122797
Opened 2022-05-01 14:35 UTC by mavethee

I've noticed there is AMD and Intel Power Gadgets available but the one for M1s is missing so here it is

2022-05-01 14:37 UTC, bevanjkay commented
Please try to add a [zap stanza](https://docs.brew.sh/Cask-Cookbook#stanza-zap). The linked documentation provides some recommended methods to create it.

2022-05-01 14:52 UTC, mavethee commented
> Please try to add a [zap stanza](https://docs.brew.sh/Cask-Cookbook#stanza-zap). The linked documentation provides some recommended methods to create it.

Done, it's seems to share same kinds of files like Intel Power Gadget, should be fine now, no idea what to do with failing audit.

2022-05-01 14:54 UTC, bevanjkay commented
@mavethee run `brew style --fix mx-power-gadget`
and also note from CI - 
```
Use `sha256 :no_check` when URL is unversioned.
```

2022-05-02 09:00 UTC, bevanjkay requested changes
Please also run `brew style --fix mx-power-gadget` again also

2022-05-02 09:00 UTC, bevanjkay commented on Casks/mx-power-gadget.rb
> +    sha256 "702f6ee1e533334bd6ffa42c168b20ad4d39a4c9a197fd0ece7e4b196bfdb929"
@mavethee Because the `url` is unversioned we cannot provide a shasum.
```suggestion
  sha256 :no_check
```

2022-05-04 09:43 UTC, bevanjkay submitted a review, later dismissed

2022-05-08 08:31 UTC, mavethee commented
Any ideas on that cask failing for ubuntu? if that really matters?

2022-05-08 08:54 UTC, bevanjkay commented
@mavethee It is failing the style checks - running `brew style --fix mx-power-gadget` and committing the changes should clear it up.

2022-05-08 09:08 UTC, mavethee commented
> brew style --fix mx-power-gadget

Well I did, no offenses detected

2022-05-08 09:14 UTC, mavethee commented
Thanks!

2022-05-08 09:30 UTC, bevanjkay approved these changes

2022-05-08 09:31 UTC, merged