Add Nitro PDF Pro.app v13.2.1
Homebrew/homebrew-cask pull request #122866
Opened 2022-05-03 19:22 UTC by rqelibari

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

2022-05-04 08:05 UTC, SMillerDev commented
Please add a [`zap` stanza](https://docs.brew.sh/Cask-Cookbook#stanza-zap) here. The [CreateZap](https://github.com/nrlquaker/homebrew-createzap) tool can help you with this.

2022-05-04 08:07 UTC, rqelibari commented
The tool says `No nitro-pdf-pro settings found`.

2022-05-04 12:10 UTC, bevanjkay requested changes

2022-05-04 12:10 UTC, bevanjkay commented on Casks/nitro-pdf-pro.rb
> +    strategy :page_match
```suggestion
```
This line can be removed because it is the default strategy.

2022-05-04 12:10 UTC, bevanjkay commented on Casks/nitro-pdf-pro.rb
> +      verified: "https://downloads.gonitro.com/macos/Nitro%20PDF%20Pro%20Retail_#{version}.dmg"
```suggestion
      verified: "downloads.gonitro.com/macos/"
```

2022-05-05 13:49 UTC, rqelibari commented on Casks/nitro-pdf-pro.rb
> +      verified: "https://downloads.gonitro.com/macos/Nitro%20PDF%20Pro%20Retail_#{version}.dmg"
This shorter URL does not point anywhere. The server responds with a blank page. Shall we use that nonetheless?

2022-05-06 07:06 UTC, rqelibari commented
Why is this PR being closed?

2022-05-06 07:08 UTC, bevanjkay commented
@rqelibari I'm honestly not sure. It wasn't closed by a user/maintainer, so you may need to reopen in a new PR.

2022-05-06 07:16 UTC, bevanjkay approved these changes

2022-05-06 07:17 UTC, merged