Add Trivial 1.0.6
Homebrew/homebrew-cask pull request #123907
Opened 2022-05-17 16:25 UTC by neersighted

Introduce a new cask: Trivial (1.0.6), a simple file transfer server by Decisive Tactics

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

2022-05-17 21:29 UTC, miccal commented
Thank you for your contribution to `homebrew-cask` @neersighted.

Could you please try to add a [`zap` stanza](https://docs.brew.sh/Cask-Cookbook#stanza-zap), thanks.

2022-05-17 23:09 UTC, bevanjkay requested changes, later dismissed

2022-05-17 23:09 UTC, bevanjkay commented on Casks/trivial.rb
> +  name "trivial"
```suggestion
  name "Trivial"
```

2022-05-18 00:29 UTC, neersighted commented
`uninstall` and `zap` stanzas added.

2022-05-18 00:40 UTC, miccal approved these changes

2022-05-18 00:41 UTC, merged