Use qlcolorcode for m1 on arm64
Homebrew/homebrew-cask pull request #124744
Opened 2022-06-02 14:02 UTC by eduardbosch

Update the QlColorCode cask for Apple M1 chipset.
The original repository does not support the M1 chipset but in [this discussion](https://github.com/anthonygelibert/QLColorCode/issues/88#issuecomment-927783435) @jpc has fixed it

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [ ] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask --online <cask>` is error-free.
- [ ] `brew style --fix <cask>` reports no offenses.

2022-06-02 20:29 UTC, SMillerDev requested changes
That should be a new cask, it's a very confusing concept to pick a different vendor based on the cpu architecture.

2022-06-04 22:21 UTC, miccal commented
Thank you @eduardbosch, but please submit this as a separate Cask following our [toke reference rules for conflicting names](https://docs.brew.sh/Acceptable-Casks#forks-and-apps-with-conflicting-names), thanks.

2022-06-04 22:21 UTC, closed without merging

2022-06-06 06:31 UTC, eduardbosch-jt commented
Sorry @SMillerDev @miccal 

Thanks for pointing out how to upload this cask ❤️

I've opened a new PR https://github.com/Homebrew/homebrew-cask/pull/124931

2022-06-06 06:33 UTC, eduardbosch commented
Sorry @SMillerDev @miccal 

Thanks for pointing out how to upload this cask ❤️

I've opened a new PR https://github.com/Homebrew/homebrew-cask/pull/124931

2022-06-10 07:41 UTC, massisenergy commented
> That should be a new cask, it's a very confusing concept to pick a different vendor based on the cpu architecture.

Currently it's `jpc-qlcolorcode`, and good work but something like `qlcolorcode-m1` (or `m1-qlcolorcode`) is much more friendly to end user like me.