FreeCAD: Bump version & fix livecheck
Homebrew/homebrew-cask pull request #125912
Opened 2022-06-17 05:34 UTC by p-linnane

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [X] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [X] `brew audit --cask --online <cask>` is error-free.
- [X] `brew style --fix <cask>` reports no offenses.

2022-06-17 11:59 UTC, SMillerDev requested changes, later dismissed

2022-06-17 11:59 UTC, SMillerDev commented on Casks/freecad.rb
> +  url "https://github.com/FreeCAD/FreeCAD/releases/download/#{version.major_minor}/FreeCAD-#{version}-OSX-i386.dmg",
That looks like a bad idea, seeing how any modern macOS is x86 only.

2022-06-17 14:42 UTC, p-linnane commented on Casks/freecad.rb
> +  url "https://github.com/FreeCAD/FreeCAD/releases/download/#{version.major_minor}/FreeCAD-#{version}-OSX-i386.dmg",
Though the filename contains i386, it is a 64-bit binary. This is the only binary they've released for macOS. I tested it on my machine running Monterey.

<img width="515" alt="Screen Shot 2022-06-17 at 07 41 36" src="https://user-images.githubusercontent.com/105994585/174320621-129c1176-6b4b-49b0-a951-d86dcc3ca1ba.png">

2022-06-18 01:01 UTC, bevanjkay approved these changes

2022-06-19 06:05 UTC, closed without merging