Add new cask `v2ray-desktop`
Homebrew/homebrew-cask pull request #127296
Opened 2022-07-07 06:01 UTC by JounQin

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask --online <cask>` is error-free.
    
  `2.4.0` has been released for months, related issue https://github.com/Dr-Incognito/V2Ray-Desktop/issues/88

- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask <cask>` worked successfully.

  It's just the app's name.

- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

2022-07-07 13:45 UTC, bevanjkay requested changes

2022-07-07 13:45 UTC, bevanjkay commented on Casks/v2ray-desktop.rb
> +  name "v2ray-desktop"
```suggestion
  name "V2Ray Desktop"
```

2022-07-21 02:00 UTC, JounQin commented on Casks/v2ray-desktop.rb
> +cask "v2ray-desktop" do
`v2ray` is a well-known brand, this cask is using it as library, remove the suffix could be confusing.

2022-07-21 02:05 UTC, bevanjkay commented on Casks/v2ray-desktop.rb
> +cask "v2ray-desktop" do
@JounQin If the application is not a product of the the developers of `v2ray` then we would need to adjust the token to specify this.
https://docs.brew.sh/Cask-Cookbook#potentially-misleading-name

Affixing `-desktop` to the end does not solve the issue with the token in this case. We may to prefix the token with the vendor name to avoid confusion.

2022-07-21 02:12 UTC, JounQin commented on Casks/v2ray-desktop.rb
> +cask "v2ray-desktop" do
Would `unofficial-v2ray` be acceptable?

2022-07-21 02:15 UTC, bevanjkay commented on Casks/v2ray-desktop.rb
> +cask "v2ray-desktop" do
@JounQin If going that direction we would go with `v2ray-unofficial` - can you push that change and we'll see what the other maintainers think?

2022-07-21 02:20 UTC, JounQin commented on Casks/v2ray-desktop.rb
> +cask "v2ray-desktop" do
OK, I'll adapt this soon.

2022-08-02 17:46 UTC, vitorgalvao submitted a review, later dismissed

2022-08-02 23:06 UTC, bevanjkay approved these changes

2022-08-02 23:17 UTC, merged