Add Astrofox.app v1.4.0
Homebrew/homebrew-cask pull request #128071
Opened 2022-07-18 09:00 UTC by devsjc

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

2022-07-18 09:05 UTC, bevanjkay requested changes
Please try to add a [`zap` stanza](https://docs.brew.sh/Cask-Cookbook#stanza-zap) here. The [CreateZap](https://github.com/nrlquaker/homebrew-createzap) tool can help you with this.

2022-07-18 09:05 UTC, bevanjkay commented on Casks/astrofox.rb
> +    regex(/href=.*?Astrofox[._-]?(\d+(?:\.\d+)+)\.dmg/i)
```suggestion
    regex(/href=.*?Astrofox[._-]v?(\d+(?:\.\d+)+)\.dmg/i)
```

2022-07-18 10:34 UTC, devsjc reviewed
Added in commit 0e2c9eea7b3260a0349fed1b6d0dff4175e1e909

2022-07-19 01:19 UTC, bevanjkay approved these changes

2022-07-19 01:19 UTC, merged