Add @MichaelSteeber's Apple Store Time Machine
Homebrew/homebrew-cask pull request #128569
Opened 2022-07-25 19:56 UTC by unitof

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [ ] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask --online <cask>` is error-free.
- [ ] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask <cask>` worked successfully.
- [ ] `brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

2022-07-26 10:01 UTC, bevanjkay requested changes

2022-07-26 10:01 UTC, bevanjkay commented on Casks/apple-store-time-machine.rb
>  cask "apple-store-time-machine" do
Following the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference) guidelines in the cask cookbook -

```suggestion
cask "shop-different" do
```

The filename would need to be also updated to `shop-different.rb`

2022-07-27 07:26 UTC, SMillerDev approved these changes

2022-07-28 09:37 UTC, bevanjkay approved these changes

2022-07-28 09:37 UTC, merged