Added Gittyup.app v1.1.1
Homebrew/homebrew-cask pull request #129279
Opened 2022-08-06 14:22 UTC by HNKNTA

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

2022-08-06 21:37 UTC, SMillerDev requested changes
Please add a [`zap` stanza](https://docs.brew.sh/Cask-Cookbook#stanza-zap) here. The [CreateZap](https://github.com/nrlquaker/homebrew-createzap) tool can help you with this.

2022-08-07 08:16 UTC, HNKNTA commented
> Please add a [`zap` stanza](https://docs.brew.sh/Cask-Cookbook#stanza-zap) here. The [CreateZap](https://github.com/nrlquaker/homebrew-createzap) tool can help you with this.

Done, sorry for the inconvenience.

2022-08-07 08:18 UTC, SMillerDev commented on Casks/gittyup.rb
> +  livecheck do
What's wrong with the default livecheck?

2022-08-07 08:21 UTC, HNKNTA commented on Casks/gittyup.rb
> +  livecheck do
There are old tags there, the tool is a fork of non-actively developed [Gitahead](https://github.com/gitahead/gitahead).
https://github.com/Murmele/Gittyup/tags

2022-08-07 10:37 UTC, SMillerDev approved these changes
Thanks @HNKNTA  ! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

2022-08-09 06:21 UTC, merged