Undeprecate and upgrade cerebro to v0.10.0
Homebrew/homebrew-cask pull request #136676
Opened 2022-11-28 22:51 UTC by ChFlick

Since I kind of took ownership of cerebro on mac, I thought I might un-deprecate and update it again on brew :)

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask <cask>` worked successfully.
- [ ] `brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

2022-11-28 23:39 UTC, bevanjkay requested changes, later dismissed

2022-11-28 23:39 UTC, bevanjkay commented on Casks/cerebro.rb
> +  end
The [`:git`](https://rubydoc.brew.sh/Homebrew/Livecheck/Strategy/Git.html) strategy is used by `livecheck` automatically when the binary is pulled from a GitHub URL. In this case, we shouldn't need to specify `:github_latest` as it can cause rate-limiting errors, if the `:git` strategy is working.

2022-11-29 09:57 UTC, ChFlick commented on Casks/cerebro.rb
> +  end
Ah that's neat. I've removed the livecheck section to make use of that!

2022-11-29 10:31 UTC, miccal commented
Thank you @ChFlick.

2022-11-29 10:31 UTC, miccal approved these changes

2022-11-29 10:32 UTC, merged