ci: Update GitHub Actions to avoid set-output deprecation
Homebrew/homebrew-cask pull request #138689
Opened 2022-12-28 11:31 UTC by shuuji3

Starting 1st June 2023 (planned) workflows, `::set-output name=<name>::<value>` syntax cannot be used. You can see the example warnings here: https://github.com/Homebrew/homebrew-cask/actions/runs/3791792830

ref. [GitHub Actions: Deprecating save-state and set-output commands | GitHub Changelog](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)

This PR fixes the issue by using the `GITHUB_OUTPUT` environment file as instructed in the above article.

(I think this doesn't change the cask itself so I remain the checklist unchecked.)

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [ ] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask --online <cask>` is error-free.
- [ ] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask <cask>` worked successfully.
- [ ] `brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

2023-01-19 06:58 UTC, SMillerDev submitted a review, later dismissed

2023-01-27 02:54 UTC, Bo98 requested changes

2023-01-27 02:54 UTC, Bo98 commented on .github/workflows/ci.yml
> +              puts "formula_dependencies=#{JSON.generate(formula_dependencies)}"
```suggestion
              f.puts "was_installed=#{JSON.generate(was_installed)}"
              f.puts "manual_installer=#{JSON.generate(manual_installer)}"
              f.puts "macos_requirement_satisfied=#{JSON.generate(macos_requirement_satisfied)}"
              f.puts "cask_conflicts=#{JSON.generate(cask_conflicts)}"
              f.puts "cask_dependencies=#{JSON.generate(cask_dependencies)}"
              f.puts "formula_conflicts=#{JSON.generate(formula_conflicts)}"
              f.puts "formula_dependencies=#{JSON.generate(formula_dependencies)}"
```

2023-01-27 02:54 UTC, Bo98 commented on .github/workflows/ci.yml
> +              puts "before=#{JSON.generate(Check.all)}"
```suggestion
              f.puts "before=#{JSON.generate(Check.all)}"
```

2023-01-27 02:54 UTC, Bo98 commented on cmd/lib/generate-matrix.rb
> +  puts "matrix=#{JSON.generate(matrix)}"
```suggestion
  f.puts "matrix=#{JSON.generate(matrix)}"
```

2023-01-27 03:28 UTC, shuuji3 commented
Applied suggestions. Thanks for reviewing.

2023-01-27 03:34 UTC, Bo98 commented on .github/actions/sync/templates.rb
> +File.open(ENV['GITHUB_OUTPUT'], 'a') do |f|
```suggestion
File.open(ENV.fetch('GITHUB_OUTPUT'), 'a') do |f|
```

2023-01-27 03:34 UTC, Bo98 commented on .github/workflows/ci.yml
> +            File.open(ENV['GITHUB_OUTPUT'], 'a') do |f|
```suggestion
            File.open(ENV.fetch('GITHUB_OUTPUT'), 'a') do |f|
```

2023-01-27 03:34 UTC, Bo98 commented on .github/workflows/ci.yml
> +            File.open(ENV['GITHUB_OUTPUT'], 'a') do |f|
```suggestion
            File.open(ENV.fetch('GITHUB_OUTPUT'), 'a') do |f|
```

2023-01-27 03:34 UTC, Bo98 commented on cmd/lib/generate-matrix.rb
> +File.open(ENV['GITHUB_OUTPUT'], 'a') do |f|
```suggestion
File.open(ENV.fetch('GITHUB_OUTPUT'), 'a') do |f|
```

2023-01-27 03:37 UTC, Bo98 commented
Appreciate the patience here. There were a few lower level changes to `setup-homebrew` that we had to make first, which were non-trival and took some time.

Thanks for the PR!

2023-01-27 03:38 UTC, Bo98 approved these changes

2023-01-27 03:45 UTC, merged

2023-01-27 03:58 UTC, shuuji3 commented
No worries, I understand.

I'm happy to help this fix for Homebrew that I use daily for many years. 🙂