Warn that Maccy's Login Item won't work with the quarantine attribute set
Homebrew/homebrew-cask pull request #139403
Opened 2023-01-10 22:17 UTC by Kentzo

Currently the login item will silently fail if Maccy was installed without the "--no-quarantine" flag.

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask --online <cask>` is error-free.
- [ ] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask <cask>` worked successfully.
- [ ] `brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

2023-01-10 23:58 UTC, p-linnane commented
Wouldn't the quarantine attribute be removed upon first launch?

2023-01-11 00:05 UTC, Kentzo commented
It wasn't for me. Why would it be?

2023-01-11 03:35 UTC, p-linnane commented
Looks like the login item is an `.app` within the main `.app`. That would not have quarantine removed upon launching the main app.

2023-01-11 03:52 UTC, Kentzo commented
Right, when I initially discovered that the login item is failing because the quarantine attribute is set, I run `ls -@ /Applications/Maccy.app` and the _Contents_ dir had it. Looks like launching cleared the top level directory only.

2023-01-11 06:38 UTC, SMillerDev commented
The correct fix here is signing the app properly. Not removing security features.

2023-01-11 06:40 UTC, SMillerDev requested changes
We don't recommend people remove quarantine attributes.

2023-01-11 06:46 UTC, Kentzo commented
> The correct fix here is signing the app properly. Not removing security features.

The app appears to be signed properly. Here is the output of codesign of the app as it was installed by brew:

```
$ codesign --verify -vvv /Applications/Maccy.app
--prepared:/Applications/Maccy.app/Contents/Frameworks/libswiftAppKit.dylib
--validated:/Applications/Maccy.app/Contents/Frameworks/libswiftAppKit.dylib
--prepared:/Applications/Maccy.app/Contents/Frameworks/libswiftCore.dylib
--validated:/Applications/Maccy.app/Contents/Frameworks/libswiftCore.dylib
--prepared:/Applications/Maccy.app/Contents/Frameworks/libswiftXPC.dylib
--validated:/Applications/Maccy.app/Contents/Frameworks/libswiftXPC.dylib
--prepared:/Applications/Maccy.app/Contents/Frameworks/libswiftObjectiveC.dylib
--validated:/Applications/Maccy.app/Contents/Frameworks/libswiftObjectiveC.dylib
--prepared:/Applications/Maccy.app/Contents/Frameworks/libswiftCoreImage.dylib
--validated:/Applications/Maccy.app/Contents/Frameworks/libswiftCoreImage.dylib
--prepared:/Applications/Maccy.app/Contents/Frameworks/libswiftCoreGraphics.dylib
--validated:/Applications/Maccy.app/Contents/Frameworks/libswiftCoreGraphics.dylib
--prepared:/Applications/Maccy.app/Contents/XPCServices/org.sparkle-project.Downloader.xpc
--validated:/Applications/Maccy.app/Contents/XPCServices/org.sparkle-project.Downloader.xpc
--prepared:/Applications/Maccy.app/Contents/XPCServices/org.sparkle-project.InstallerConnection.xpc
--validated:/Applications/Maccy.app/Contents/XPCServices/org.sparkle-project.InstallerConnection.xpc
--prepared:/Applications/Maccy.app/Contents/XPCServices/org.sparkle-project.InstallerLauncher.xpc
--validated:/Applications/Maccy.app/Contents/XPCServices/org.sparkle-project.InstallerLauncher.xpc
--prepared:/Applications/Maccy.app/Contents/XPCServices/org.sparkle-project.InstallerStatus.xpc
--validated:/Applications/Maccy.app/Contents/XPCServices/org.sparkle-project.InstallerStatus.xpc
--prepared:/Applications/Maccy.app/Contents/Library/LoginItems/LaunchAtLoginHelper.app
--validated:/Applications/Maccy.app/Contents/Library/LoginItems/LaunchAtLoginHelper.app
--prepared:/Applications/Maccy.app/Contents/Frameworks/Sparkle.framework/Versions/Current/.
--validated:/Applications/Maccy.app/Contents/Frameworks/Sparkle.framework/Versions/Current/.
--prepared:/Applications/Maccy.app/Contents/Frameworks/libswiftCoreData.dylib
--validated:/Applications/Maccy.app/Contents/Frameworks/libswiftCoreData.dylib
--prepared:/Applications/Maccy.app/Contents/Frameworks/libswiftMetal.dylib
--validated:/Applications/Maccy.app/Contents/Frameworks/libswiftMetal.dylib
--prepared:/Applications/Maccy.app/Contents/Frameworks/libswiftos.dylib
--validated:/Applications/Maccy.app/Contents/Frameworks/libswiftos.dylib
--prepared:/Applications/Maccy.app/Contents/Frameworks/libswiftQuartzCore.dylib
--validated:/Applications/Maccy.app/Contents/Frameworks/libswiftQuartzCore.dylib
--prepared:/Applications/Maccy.app/Contents/Frameworks/libswiftDarwin.dylib
--validated:/Applications/Maccy.app/Contents/Frameworks/libswiftDarwin.dylib
--prepared:/Applications/Maccy.app/Contents/Frameworks/libswiftDispatch.dylib
--validated:/Applications/Maccy.app/Contents/Frameworks/libswiftDispatch.dylib
--prepared:/Applications/Maccy.app/Contents/Frameworks/libswiftFoundation.dylib
--validated:/Applications/Maccy.app/Contents/Frameworks/libswiftFoundation.dylib
--prepared:/Applications/Maccy.app/Contents/Frameworks/libswiftCoreFoundation.dylib
--validated:/Applications/Maccy.app/Contents/Frameworks/libswiftCoreFoundation.dylib
--prepared:/Applications/Maccy.app/Contents/Frameworks/libswiftIOKit.dylib
--validated:/Applications/Maccy.app/Contents/Frameworks/libswiftIOKit.dylib
--prepared:/Applications/Maccy.app/Contents/Frameworks/libswiftIntents.dylib
--validated:/Applications/Maccy.app/Contents/Frameworks/libswiftIntents.dylib
--prepared:/Applications/Maccy.app/Contents/Frameworks/libswiftCoreLocation.dylib
--validated:/Applications/Maccy.app/Contents/Frameworks/libswiftCoreLocation.dylib
/Applications/Maccy.app: valid on disk
/Applications/Maccy.app: satisfies its Designated Requirement

$ codesign --display -vvv /Applications/Maccy.app         
Executable=/Applications/Maccy.app/Contents/MacOS/Maccy
Identifier=org.p0deje.Maccy
Format=app bundle with Mach-O universal (x86_64 arm64)
CodeDirectory v=20500 size=6460 flags=0x10000(runtime) hashes=191+7 location=embedded
Hash type=sha256 size=32
CandidateCDHash sha256=fab018cde6fe6239b18e2a5a9055b9b6c0ca7ee2
CandidateCDHashFull sha256=fab018cde6fe6239b18e2a5a9055b9b6c0ca7ee2f1d34d9cb8e114a1f72b28b5
Hash choices=sha256
CMSDigest=fab018cde6fe6239b18e2a5a9055b9b6c0ca7ee2f1d34d9cb8e114a1f72b28b5
CMSDigestType=2
Launch Constraints:
	None
CDHash=fab018cde6fe6239b18e2a5a9055b9b6c0ca7ee2
Signature size=8981
Authority=Developer ID Application: Alexey Rodionov (MN3X4648SC)
Authority=Developer ID Certification Authority
Authority=Apple Root CA
Timestamp=Aug 31, 2022 at 2:21:06 PM
Info.plist entries=29
TeamIdentifier=MN3X4648SC
Runtime Version=12.3.0
Sealed Resources version=2 rules=13 files=186
Internal requirements count=1 size=208
```

2023-01-11 07:21 UTC, SMillerDev commented
In that case quarantine won't block it. As far as I know gatekeeper really only checks quarantined apps for known malware and missing signatures so if it's signed correctly there should be no issues with quarantine.

2023-01-11 18:34 UTC, Kentzo commented
I did the following:

1. Quit Maccy
2. Run `brew uninstall --cask maccy`
3. Logged out
4. Logged in
5. Run `brew install --cask maccy`.
6. Launched it. The macOS shown the warning to which I agreed. 
7. In Maccy's settings enabled the login item
8. Logged out
9. Logged in. Maccy did not launch and the following warning was in launchd.log:

```
2023-01-11 10:23:16.220710 (gui/501/org.p0deje.Maccy-LaunchAtLoginHelper) <Notice>: service state: spawning
2023-01-11 10:23:16.220771 (gui/501/org.p0deje.Maccy-LaunchAtLoginHelper) <Notice>: launching: semaphore
2023-01-11 10:23:16.222385 (gui/501/org.p0deje.Maccy-LaunchAtLoginHelper [16190]) <Notice>: xpcproxy spawned with pid 16190
2023-01-11 10:23:16.222415 (gui/501/org.p0deje.Maccy-LaunchAtLoginHelper [16190]) <Notice>: internal event: SPAWNED, code = 0
2023-01-11 10:23:16.222423 (gui/501/org.p0deje.Maccy-LaunchAtLoginHelper [16190]) <Notice>: service state: xpcproxy
2023-01-11 10:23:16.222428 (gui/501/org.p0deje.Maccy-LaunchAtLoginHelper [16190]) <Notice>: deferred event: domain spawn response: 0
2023-01-11 10:23:16.222436 (gui/501/org.p0deje.Maccy-LaunchAtLoginHelper [16190]) <Notice>: internal event: SOURCE_ATTACH, code = 0
2023-01-11 10:23:16.251279 (pid/16190 [xpcproxy]) <Notice>: deferring exec source uncork
2023-01-11 10:23:16.251286 (pid/16190 [xpcproxy]) <Notice>: created
2023-01-11 10:23:16.251296 (pid/16190 [xpcproxy]) <Warning>: failed lookup: name = com.apple.filesystems.netfs.PlugInLibraryService, requestor = xpcproxy[16190], error = 3: No such process
    >>> 2023-01-11 10:23:16.258575 (gui/501/org.p0deje.Maccy-LaunchAtLoginHelper [16190]) <Warning>: Could not find and/or execute program specified by service: 155: Refusing to execute/trust quarantined program/file: org.p0deje.Maccy-LaunchAtLoginHelper <<<
2023-01-11 10:23:16.258582 (gui/501/org.p0deje.Maccy-LaunchAtLoginHelper [16190]) <Error>: Service could not initialize: copy_bundle4id(org.p0deje.Maccy, 13, org.p0deje.Maccy-LaunchAtLoginHelper), error 0x6f - Invalid or missing Program/ProgramArguments
2023-01-11 10:23:16.258585 (gui/501/org.p0deje.Maccy-LaunchAtLoginHelper [16190]) <Error>: initialization failure: 22C65: xpcproxy + 20260 [482][160B6684-D927-3EC1-A73F-985BE610A79B]: 0x6f
2023-01-11 10:23:16.258587 (gui/501/org.p0deje.Maccy-LaunchAtLoginHelper [16190]) <Notice>: internal event: INIT, code = 111
2023-01-11 10:23:16.258589 (gui/501/org.p0deje.Maccy-LaunchAtLoginHelper [16190]) <Notice>: job state = spawn failed
2023-01-11 10:23:16.259141 (gui/501/org.p0deje.Maccy-LaunchAtLoginHelper [16190]) <Notice>: xpcproxy exited due to exit(78)
2023-01-11 10:23:16.259198 (gui/501/org.p0deje.Maccy-LaunchAtLoginHelper [16190]) <Notice>: exited due to exit(78)
2023-01-11 10:23:16.259276 (gui/501/org.p0deje.Maccy-LaunchAtLoginHelper [16190]) <Notice>: already handled failed init, ignoring
2023-01-11 10:23:16.259281 (gui/501/org.p0deje.Maccy-LaunchAtLoginHelper [16190]) <Notice>: service state: exited
2023-01-11 10:23:16.260047 (gui/501/org.p0deje.Maccy-LaunchAtLoginHelper [16190]) <Notice>: internal event: EXITED, code = 0
2023-01-11 10:23:16.260051 (gui/501 [100313]) <Notice>: service inactive: org.p0deje.Maccy-LaunchAtLoginHelper
2023-01-11 10:23:16.260072 (gui/501/org.p0deje.Maccy-LaunchAtLoginHelper [16190]) <Notice>: service state: not running
2023-01-11 10:23:16.260078 (gui/501/org.p0deje.Maccy-LaunchAtLoginHelper) <Notice>: Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
2023-01-11 10:23:16.260150 (gui/501/org.p0deje.Maccy-LaunchAtLoginHelper) <Notice>: internal event: WILL_SPAWN, code = 0
2023-01-11 10:23:16.260156 (gui/501/org.p0deje.Maccy-LaunchAtLoginHelper) <Notice>: service state: spawn scheduled
2023-01-11 10:23:16.260158 (gui/501/org.p0deje.Maccy-LaunchAtLoginHelper) <Notice>: service throttled by 10 seconds
2023-01-11 10:23:16.260169 (pid/16190 [xpcproxy]) <Notice>: shutting down
2023-01-11 10:23:16.260174 (pid/16190 [xpcproxy]) <Notice>: uncorking exec source for disposal
2023-01-11 10:23:16.260181 (pid/16190 [xpcproxy]) <Notice>: cleaning up
```
10. Run `ls -lA@ /Applications/Maccy.app`, the quarantine attribute was not removed:
```
$ ls -la@ /Applications/Maccy.app                   
total 0
drwxr-xr-x@  3 kentzo  staff    96 Aug 31 14:20 .
	com.apple.macl	  72 
	com.apple.provenance	  11 
	com.apple.quarantine	  67 
drwxrwxr-x  84 root    admin  2688 Jan 11 10:20 ..
drwxr-xr-x@ 11 kentzo  staff   352 Aug 31 14:29 Contents
	com.apple.quarantine	  67 
```

@SMillerDev Are you not able to reproduce the issue?

2023-01-11 19:34 UTC, SMillerDev commented
Quarantine attributes aren't removed when you open the app. The app is just stored as trusted in the system.

There's not much Homebrew can do here though since we're just activating a macOS security feature. The same should happen if you download the app with chrome or safari.

This is also why I don't want to merge a change that recommends disabling it. It's not a fix, it's a workaround.

2023-01-11 21:37 UTC, Kentzo commented
I did the following:

1. Run brew uninstall --cask maccy
2. Logged out
3. Logged in
4. Downloaded Maccy from the website, unpacked the zip file and moved it to /Applications
5. Launched it. The macOS shown the warning to which I agreed
6. In Maccy's settings enabled the login item
7. Logged out
8. Logged in. Maccy did launch, there were no warnings in lauchd.log
9. Run `ls -lA@ /Applications/Maccy.app`, the quarantine attribute was not removed:
```
$ ls -la@ /Applications/Maccy.app    
total 0
drwxr-xr-x@  3 kentzo  staff    96 Aug 31 14:20 .
	com.apple.macl	  72 
	com.apple.provenance	  11 
	com.apple.quarantine	  57 
drwxrwxr-x  84 root    admin  2688 Jan 11 13:29 ..
drwxr-xr-x@ 11 kentzo  staff   352 Aug 31 14:29 Contents
	com.apple.quarantine	  57 
```
10. Run `codesign --verify -vvv /Applications/Maccy.app`, it passed the test:
```
$ codesign --verify -vvv /Applications/Maccy.app
--prepared:/Applications/Maccy.app/Contents/Frameworks/libswiftObjectiveC.dylib
--validated:/Applications/Maccy.app/Contents/Frameworks/libswiftObjectiveC.dylib
--prepared:/Applications/Maccy.app/Contents/Frameworks/libswiftCore.dylib
--validated:/Applications/Maccy.app/Contents/Frameworks/libswiftCore.dylib
--prepared:/Applications/Maccy.app/Contents/Frameworks/libswiftCoreImage.dylib
--validated:/Applications/Maccy.app/Contents/Frameworks/libswiftCoreImage.dylib
--prepared:/Applications/Maccy.app/Contents/Frameworks/libswiftAppKit.dylib
--validated:/Applications/Maccy.app/Contents/Frameworks/libswiftAppKit.dylib
--prepared:/Applications/Maccy.app/Contents/Frameworks/libswiftXPC.dylib
--validated:/Applications/Maccy.app/Contents/Frameworks/libswiftXPC.dylib
--prepared:/Applications/Maccy.app/Contents/Library/LoginItems/LaunchAtLoginHelper.app
--validated:/Applications/Maccy.app/Contents/Library/LoginItems/LaunchAtLoginHelper.app
--prepared:/Applications/Maccy.app/Contents/XPCServices/org.sparkle-project.InstallerStatus.xpc
--validated:/Applications/Maccy.app/Contents/XPCServices/org.sparkle-project.InstallerStatus.xpc
--prepared:/Applications/Maccy.app/Contents/XPCServices/org.sparkle-project.InstallerConnection.xpc
--validated:/Applications/Maccy.app/Contents/XPCServices/org.sparkle-project.InstallerConnection.xpc
--prepared:/Applications/Maccy.app/Contents/XPCServices/org.sparkle-project.InstallerLauncher.xpc
--validated:/Applications/Maccy.app/Contents/XPCServices/org.sparkle-project.InstallerLauncher.xpc
--prepared:/Applications/Maccy.app/Contents/Frameworks/libswiftCoreGraphics.dylib
--validated:/Applications/Maccy.app/Contents/Frameworks/libswiftCoreGraphics.dylib
--prepared:/Applications/Maccy.app/Contents/XPCServices/org.sparkle-project.Downloader.xpc
--validated:/Applications/Maccy.app/Contents/XPCServices/org.sparkle-project.Downloader.xpc
--prepared:/Applications/Maccy.app/Contents/Frameworks/Sparkle.framework/Versions/Current/.
--validated:/Applications/Maccy.app/Contents/Frameworks/Sparkle.framework/Versions/Current/.
--prepared:/Applications/Maccy.app/Contents/Frameworks/libswiftos.dylib
--validated:/Applications/Maccy.app/Contents/Frameworks/libswiftos.dylib
--prepared:/Applications/Maccy.app/Contents/Frameworks/libswiftDispatch.dylib
--validated:/Applications/Maccy.app/Contents/Frameworks/libswiftDispatch.dylib
--prepared:/Applications/Maccy.app/Contents/Frameworks/libswiftMetal.dylib
--validated:/Applications/Maccy.app/Contents/Frameworks/libswiftMetal.dylib
--prepared:/Applications/Maccy.app/Contents/Frameworks/libswiftDarwin.dylib
--validated:/Applications/Maccy.app/Contents/Frameworks/libswiftDarwin.dylib
--prepared:/Applications/Maccy.app/Contents/Frameworks/libswiftFoundation.dylib
--validated:/Applications/Maccy.app/Contents/Frameworks/libswiftFoundation.dylib
--prepared:/Applications/Maccy.app/Contents/Frameworks/libswiftCoreFoundation.dylib
--validated:/Applications/Maccy.app/Contents/Frameworks/libswiftCoreFoundation.dylib
--prepared:/Applications/Maccy.app/Contents/Frameworks/libswiftIntents.dylib
--validated:/Applications/Maccy.app/Contents/Frameworks/libswiftIntents.dylib
--prepared:/Applications/Maccy.app/Contents/Frameworks/libswiftQuartzCore.dylib
--validated:/Applications/Maccy.app/Contents/Frameworks/libswiftQuartzCore.dylib
--prepared:/Applications/Maccy.app/Contents/Frameworks/libswiftIOKit.dylib
--validated:/Applications/Maccy.app/Contents/Frameworks/libswiftIOKit.dylib
--prepared:/Applications/Maccy.app/Contents/Frameworks/libswiftCoreData.dylib
--validated:/Applications/Maccy.app/Contents/Frameworks/libswiftCoreData.dylib
--prepared:/Applications/Maccy.app/Contents/Frameworks/libswiftCoreLocation.dylib
--validated:/Applications/Maccy.app/Contents/Frameworks/libswiftCoreLocation.dylib
/Applications/Maccy.app: valid on disk
/Applications/Maccy.app: satisfies its Designated Requirement
```
11. Run codesign --display -vvv /Applications/Maccy.app, the app shows a proper certificate chain and matches the one from Maccy installed via Homebrew:
```
$ codesign --display -vvv /Applications/Maccy.app
Executable=/Applications/Maccy.app/Contents/MacOS/Maccy
Identifier=org.p0deje.Maccy
Format=app bundle with Mach-O universal (x86_64 arm64)
CodeDirectory v=20500 size=6460 flags=0x10000(runtime) hashes=191+7 location=embedded
Hash type=sha256 size=32
CandidateCDHash sha256=fab018cde6fe6239b18e2a5a9055b9b6c0ca7ee2
CandidateCDHashFull sha256=fab018cde6fe6239b18e2a5a9055b9b6c0ca7ee2f1d34d9cb8e114a1f72b28b5
Hash choices=sha256
CMSDigest=fab018cde6fe6239b18e2a5a9055b9b6c0ca7ee2f1d34d9cb8e114a1f72b28b5
CMSDigestType=2
Launch Constraints:
	None
CDHash=fab018cde6fe6239b18e2a5a9055b9b6c0ca7ee2
Signature size=8981
Authority=Developer ID Application: Alexey Rodionov (MN3X4648SC)
Authority=Developer ID Certification Authority
Authority=Apple Root CA
Timestamp=Aug 31, 2022 at 2:21:06 PM
Info.plist entries=29
TeamIdentifier=MN3X4648SC
Runtime Version=12.3.0
Sealed Resources version=2 rules=13 files=186
Internal requirements count=1 size=208
```

It works when downloaded via Safari and manually copied into /Applications.

2023-01-13 20:17 UTC, Kentzo commented
Looks like either a bug by macOS or simply unsupported in the security model I want (running brew as non-current low privileged user). See the thread of Apple's forums.

2023-01-13 20:17 UTC, closed without merging