orbstack: Link orb and orbctl CLI binaries
Homebrew/homebrew-cask pull request #143981
Opened 2023-03-29 08:22 UTC by kdrag0n

`orbctl` and the shorter `orb` command are CLI tools for using and managing OrbStack and its Linux machines. They're usually symlinked at first launch, but managing them with Homebrew should be better for cask users. The app will detect brew's symlinks and leave them alone.

OrbStack also includes Docker tools similar to Docker Desktop, but it's probably better to let the app decide what it needs to link at launch. There's no requirement to use any particular versions of the Docker tools, so for example, users with Docker installed via Homebrew may want to keep using their existing ones.

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

2023-03-29 10:41 UTC, bevanjkay requested changes

2023-03-29 10:41 UTC, bevanjkay commented on Casks/orbstack.rb
> +  binary "#{appdir}/OrbStack.app/Contents/MacOS/bin/orb", target: "orb"
@kdrag0n I don't believe that `target` is required here, as it will already be set. It's only used when the binary itself is renamed.

2023-03-30 01:05 UTC, kdrag0n commented on Casks/orbstack.rb
> +  binary "#{appdir}/OrbStack.app/Contents/MacOS/bin/orb", target: "orb"
Removed `target`, thanks.

2023-03-30 01:07 UTC, bevanjkay submitted a review, later dismissed

2023-03-30 10:54 UTC, bevanjkay approved these changes

2023-03-30 10:54 UTC, merged