Update Double-Commander to 1.1.0
Homebrew/homebrew-cask pull request #144732
Opened 2023-04-08 10:25 UTC by rich2014

Update Double-Commander to 1.1.0.

1. Double Commander for MacOS has regained official support

2. audit / sytle / install / uninstall have been tested

3. both AArch64 and x86_64 versions have beed inclued in official down page:
https://sourceforge.net/p/doublecmd/wiki/Download/

4. offical homepage:
https://doublecmd.sourceforge.io

2023-04-08 11:21 UTC, bevanjkay submitted a review, later dismissed

2023-04-08 11:21 UTC, bevanjkay commented on Casks/double-commander.rb
>    end
@rich2014 Why are the attributes being removed from the file?

2023-04-08 11:39 UTC, rich2014 commented on Casks/double-commander.rb
>    end
@bevanjkay

1. Apps downloaded from the Internet will be added with attributes by MacOS.

2. if the app has not been submitted to Apple for review by the Apple Developer ID, when the user opens the app, they will be warned and cannot open it directly.

3. many open source free software have the same problem, such as CudaText:
https://cudatext.github.io/download.html

2023-04-08 11:43 UTC, bevanjkay commented on Casks/double-commander.rb
>    end
@rich2014 we have gone to great lengths to support Apple's quarantine attribute for cask downloads, so we do not support removing of these attributes.

2023-04-08 11:46 UTC, reitermarkus commented on Casks/double-commander.rb
>    end
Homebrew adds these attributes to quarantine the download. This defeats the quarantining.

2023-04-08 12:11 UTC, rich2014 commented on Casks/double-commander.rb
>    end
So can we prompt the user some message like this?

```
On macOS Catalina or later, you may get a warning that "the developer cannot be verified". you can:
1. Ctrl+Click and open the APP
2. or disabled in the "Security & Privacy" preferences panel
3. or by running the following command:
    xattr -cr "#{target_dir}"
```

2023-04-08 19:27 UTC, reitermarkus commented on Casks/double-commander.rb
>    end
I don't think we need a message.

Users are supposed to know what they are downloading. This message would need to be displayed for virtually every cask.

You would need to follow the same steps if you install this manually.

2023-04-08 22:47 UTC, razvanazamfirei requested changes, later dismissed

2023-04-08 22:47 UTC, razvanazamfirei commented on Casks/double-commander.rb
> +  end
```suggestion
  livecheck do
    url "https://sourceforge.net/projects/doublecmd/rss"
    regex(/doublecmd[._-](\d+(?:\.\d+)+)[._-](\d+)\./i)
    strategy :page_match do |page, regex|
      page.scan(regex).map { |match| "#{match[0]},#{match[1]}" }
    end
  end
```

2023-04-08 22:47 UTC, razvanazamfirei commented on Casks/double-commander.rb
> +  desc "File Manager with double panels"
```suggestion
  desc "File manager with double panels"
```

2023-04-08 22:47 UTC, razvanazamfirei commented on Casks/double-commander.rb
>  end
Please include a [zap stanza](https://docs.brew.sh/Cask-Cookbook#stanza-zap).

2023-04-08 22:50 UTC, razvanazamfirei commented on Casks/double-commander.rb
>    end
I agree! I think the entire preflight stanza should be removed.

2023-04-09 15:12 UTC, rich2014 commented
@reitermarkus @razvanazamfirei 

thx.

issue fixed, check it please.

2023-04-09 17:46 UTC, reitermarkus approved these changes

2023-04-09 17:46 UTC, reitermarkus commented
Thanks, @rich2014!

2023-04-09 18:57 UTC, merged