Update citrix-workspace livecheck
Homebrew/homebrew-cask pull request #145221
Opened 2023-04-15 22:02 UTC by Teko012

- [X] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [X] `brew audit --cask --online <cask>` is error-free.
- [X] `brew style --fix <cask>` reports no offenses.

2023-04-15 22:59 UTC, razvanazamfirei requested changes
Hi, @Teko012! This is great work! 👍 I have some quick questions and suggestions.

2023-04-15 22:59 UTC, razvanazamfirei commented on Casks/citrix-workspace.rb
> +  arch arm: "Universal", intel: "Intel"
Is there any advantage to using a universal build for ARM and an intel-only build for Intel?

2023-04-15 22:59 UTC, razvanazamfirei commented on Casks/citrix-workspace.rb
>    end
This might be a bit simpler. Matching on `ShortDescription` as `HDX RealTime Media Engine` is included in this file.
```suggestion
  livecheck do
    url "https://downloadplugins.citrix.com/ReceiverUpdates/Prod/catalog_macos2.xml"
    regex(%r{<short\S*?>.*?workspace.*?</short\S*?>.*?<version>v?(\d+(?:\.\d+)+)</version>}i)
  end
```

2023-04-15 23:06 UTC, Teko012 commented on Casks/citrix-workspace.rb
> +  arch arm: "Universal", intel: "Intel"
I'm not sure, at the moment, they still separate it, with a [note on the website](https://docs.citrix.com/en-us/citrix-workspace-app-for-mac/apple-silicon.html), that doesn't disclose their future plans.

2023-04-15 23:10 UTC, Teko012 commented on Casks/citrix-workspace.rb
>    end
Sure, although for RTME, the platform is `Any` currently.

2023-04-15 23:42 UTC, Teko012 commented
@razvanazamfirei Updated it

2023-04-15 23:56 UTC, razvanazamfirei commented on Casks/citrix-workspace.rb
>    end
Good catch!

2023-04-15 23:58 UTC, razvanazamfirei commented on Casks/citrix-workspace.rb
> +  arch arm: "Universal", intel: "Intel"
It looks like they mention they will deprecate the Intel version.
>However, Citrix will soon deprecate the Citrix Workspace app for Mac that uses Rosetta emulation. Keep a look out for an announcement in the [Deprecation](https://docs.citrix.com/en-us/citrix-workspace-app-for-mac.html#deprecation) section.

2023-04-16 00:00 UTC, razvanazamfirei approved these changes

2023-04-16 00:00 UTC, razvanazamfirei commented
Looks great! 👍

2023-04-16 00:04 UTC, merged