Add Red Canary Mac Monitor.app v1.0.3
Homebrew/homebrew-cask pull request #146071
Opened 2023-04-28 01:34 UTC by Brandon7CC

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `red-canary-mac-monitor` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.
  - **Red Canary Mac Monitor does have the platform in the description because it's a "macOS threat research tool"** 

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

2023-04-28 01:45 UTC, bevanjkay requested changes

2023-04-28 01:45 UTC, bevanjkay commented on Casks/red-canary-mac-monitor.rb
> +  desc "Dynamic analysis tool for macOS security research and malware triage"
```suggestion
  desc "Analysis tool for security research and malware triage"
```

`homebrew-cask` only supports MacOS so including the platform in the description is redundant.

2023-04-28 01:47 UTC, bevanjkay commented on Casks/red-canary-mac-monitor.rb
> +  end
@Brandon7CC The `:github_latest` livecheck strategy should only be used where the default `:git` strategy cannot be used due to the use of pre-releases. If the default `:git` strategy can be used here, the entire `livecheck` block can omitted as it will be inferred automatically from the `url`.

2023-04-28 01:48 UTC, bevanjkay commented
Also from the test failure -
```
Some packages are still installed, add them to
uninstall pkgutil: com.redcanary.agent
```

2023-04-28 02:25 UTC, Brandon7CC commented on Casks/red-canary-mac-monitor.rb
> +  end
@bevanjkay thank you! I went ahead and removed this.

2023-04-28 02:25 UTC, Brandon7CC commented on Casks/red-canary-mac-monitor.rb
> +  desc "Dynamic analysis tool for macOS security research and malware triage"
Thank you :)

2023-04-28 02:59 UTC, bevanjkay commented on Casks/red-canary-mac-monitor.rb
> +  ]
@Brandon7CC These should be combined in to one `uninstall` stanza.

```suggestion
  uninstall pkgutil: "com.redcanary.agent",
                 script:   {
                   executable: "#{appdir}/Red Canary Mac Monitor.app/Contents/SharedSupport/uninstall.sh",
                   sudo:            false,
                 }
```

This may fail style.

2023-04-28 03:01 UTC, Brandon7CC commented
Please note that we're using `/usr/bin/osascript` to uninstall the app. We're doing this because the app hosts a System Extension which requires user authentication to approve. By "moving the application bundle" to the trash with AppleScript the user is able to authenticate and remove the System Extension.

2023-04-28 03:24 UTC, razvanazamfirei commented
@Brandon7CC, thank you for submitting this! 
This is not directly relevant to the cask, but issues relating to managing system extensions/ `systemextensionsctl uninstall` not working with SIP came up before. 

We've briefly talked about using `/usr/bin/osascript` as a potential strategy, but I figured I would check whether or not this has been a reliable uninstall strategy for you and if you had any issues dealing with orphaned extensions.

2023-04-28 03:25 UTC, razvanazamfirei commented
/rebase

2023-04-28 04:00 UTC, Brandon7CC commented
@razvanazamfirei Thank you for asking about this! The OSA method works well -- given that the user accepts the uninstall request. If they don't macOS blocks the operation and the System Extension (SE) will be left installed unfortunately. Using `systemextensionsctl` like you said isn't helpful with SIP enabled, but the other option would be to use the `SystemExtensions` API directly with a "privileged helper binary" -- the user can again deny this operation though and the SE will be left installed. I found the OSA implementation to be the most "elegant" to help with this research tool case.

2023-04-28 09:47 UTC, razvanazamfirei requested changes
Added a few more things to the zap stanza and a comment. Besides this, I think it looks good!

Note: Locally, it uninstalls cleanly, but does require additional user input. It will always time-out during CI.

2023-04-28 09:47 UTC, razvanazamfirei commented on Casks/red-canary-mac-monitor.rb
> +  ]
```suggestion
  zap trash: [
    "~/Library/Application Support/Red Canary Mac Monitor",
    "~/Library/Preferences/com.redcanary.agent.plist",
    "~/Library/Saved Application State/com.redcanary.agent.savedState",
  ]
```

2023-04-28 09:47 UTC, razvanazamfirei commented on Casks/red-canary-mac-monitor.rb
> +  name "rc-mac-monitor"
I'm not sure this is necessary unless these are commonly-used names for the app.

2023-04-28 11:38 UTC, razvanazamfirei commented
Thank you, @Brandon7CC! This is very helpful.

2023-04-28 16:07 UTC, Brandon7CC commented on Casks/red-canary-mac-monitor.rb
> +  name "rc-mac-monitor"
👍  Took these out

2023-04-28 16:10 UTC, Brandon7CC commented
One more question... when we submit PRs for updates and the CI fails due to user interaction should we specify that at the next update?

2023-04-28 16:39 UTC, razvanazamfirei commented on Casks/red-canary-mac-monitor.rb
> +
```suggestion

  # The uninstall script requires user input to remove an installed system
  # extension. It is expected that the uninstall CI will time out and fail.
```

2023-04-28 16:41 UTC, razvanazamfirei commented
Adding the comment in the cask should streamline version bumps. It will fail initially, but hopefully pass once the install test is skipped. We don't want to do this by default in case install problems show up.

2023-04-28 17:42 UTC, razvanazamfirei approved these changes, later dismissed

2023-04-28 17:45 UTC, razvanazamfirei commented
/rebase

2023-04-28 18:16 UTC, razvanazamfirei commented
@Brandon7CC, since we don't have write access to the fork, can you rebase this? Thank you

2023-04-28 18:50 UTC, Brandon7CC commented
@razvanazamfirei should be good to go! Let me know if there's anything else funky going on

2023-04-29 01:44 UTC, razvanazamfirei approved these changes

2023-04-29 05:45 UTC, bevanjkay commented
Is there no way for this to pass CI without an exception. Ideally we shouldn't be using exceptions except in very rare circumstances.

2023-04-29 10:48 UTC, Brandon7CC commented
@bevanjkay  the app hosts a System Extension (https://developer.apple.com/system-extensions/) to communicate with the Endpoint Security subsystem. System Extensions are the replacement for Kexts and are protected by SIP (and in turn from the `root` user — “rootless”). To remove a System Extension theres a few different options (the ones relevant here are):

- User interaction and authentication deleting the app from the Finder (i.e. in the OSA case here with: `/usr/bin/osascript`).
- Using the System Extensions API directly which also requires user authentication and must be done from a “privileged app/binary”.

I’ve gone ahead and implemented the first option here and have found it to be the most elegant / helpful in this context. There are **no** unprivileged / entitled binaries on macOS to “remove a System Extension” without SIP disabled — to be expected as this is a security relevant operation. The CI job is failing due to the AppleEvent timeout waiting for the user to accept the System Extension uninstall request. Please let me know if I can provide any additional details!


<img width="831" alt="System Extension Removal Methods" src="https://user-images.githubusercontent.com/22716543/235298742-a43f27ba-1e15-4d6c-9b1d-14c93315d638.png">

2023-04-29 11:15 UTC, razvanazamfirei commented
We had a similar discussion in #145132 with respect to `ftdi-vcp-driver`. It is possible to have this pass CI at the expense of orphaning the system extension which would then require disabling SIP to remove. Turning this into a method is on my to-do list as it seems to be relevant to other casks as well.

2023-05-01 03:23 UTC, bevanjkay commented
@Brandon7CC My concern is that `homebrew-cask` users expect not to be presented with GUI inputs, and can be used successfully using a remote shell.
We have tested adding a `must_succeed: false` argument in #146256 which allows CI to pass, with the downside that Homebrew will consider the uninstall complete even if the script fails.

Without further digging as for the reason, the script did error out for me when I tested the install/uninstall process.

<details><summary>Error</summary>
<p>
```
29:125: execution error: Finder got an error: The operation can't be completed right now because another operation is in progress, such as moving or copying an item or emptying the Bin. (-8065)
Error: Failure while executing; `/usr/bin/env /Applications/Red\ Canary\ Mac\ Monitor.app/Contents/SharedSupport/uninstall.sh` exited with 1. Here's the output:
29:125: execution error: Finder got an error: The operation can't be completed right now because another operation is in progress, such as moving or copying an item or emptying the Bin. (-8065)
```
</p>
</details>

2023-05-01 23:46 UTC, closed without merging