volta: new cask
Homebrew/homebrew-cask pull request #146448
Opened 2023-05-03 23:46 UTC by danielbayley

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

2023-05-04 00:12 UTC, bevanjkay requested changes, later dismissed

2023-05-04 00:12 UTC, bevanjkay commented on Casks/volta-net.rb
> +    strategy :page_match
This line can be omitted as it is the default strategy.

2023-05-04 00:12 UTC, bevanjkay commented on Casks/volta-net.rb
> +cask "volta-net" do
We do have some casks that share a token with a formula

2023-05-04 00:16 UTC, danielbayley commented on Casks/volta-net.rb
> +cask "volta-net" do
> We do have some casks that share a token with a formula

So how to avoid the error?

2023-05-04 00:18 UTC, bevanjkay commented on Casks/volta-net.rb
> +cask "volta-net" do
It can be skipped on maintainer review, and is only checked on initial submission.

2023-05-04 03:54 UTC, miccal approved these changes, later dismissed

2023-05-04 04:05 UTC, miccal approved these changes

2023-05-07 13:02 UTC, razvanazamfirei commented
I feel like cask/formula token conflicts should be skippable. Alternatively, we could rename this to `nuxtlabs-volta`.

2023-05-07 14:51 UTC, p-linnane approved these changes

2023-05-07 22:05 UTC, bevanjkay commented
I am happy to merge as-is

2023-05-07 22:29 UTC, merged