Add Engine DJ.app v3.0.1 cask engine-dj.rb
Homebrew/homebrew-cask pull request #148096
Opened 2023-05-29 22:18 UTC by djasonic

Application formerly known as Engine Prime cask engine-prime.rb

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

2023-05-29 22:56 UTC, bevanjkay requested changes, later dismissed
From CI audit:
```
Some packages are still installed, add them to uninstall pkgutil: com.airmusictechnology.engineprime.application
```

2023-05-29 22:56 UTC, bevanjkay commented on Casks/engine-dj.rb
> +  desc "World's premier DJ software suite"
Please update the `desc` to fit the [desc stanza guidelines in the Cask Cookbook](https://docs.brew.sh/Cask-Cookbook#stanza-desc).

> Do not use empty marketing jargon.

2023-05-30 00:30 UTC, razvanazamfirei commented
> Application formerly known as Engine Prime cask engine-prime.rb

At this point I wonder if `engine-prime` should be removed
```
engine-prime
30 days: n/a
90 days: n/a
365 days: 13 (#5499)
Age: 1354 days (added 2019, September 13)
```

2023-05-30 00:33 UTC, bevanjkay commented on Casks/engine-dj.rb
> +    "~/Library/Caches/AIR Music Technology",
@razvanazamfirei I wonder if these folders are specific to this application or if they are used as common folders between the vendor's applications. This is always a tricky one with `zap` stanzas.

2023-05-30 00:42 UTC, razvanazamfirei commented on Casks/engine-dj.rb
> +    "~/Library/Caches/AIR Music Technology",
Good point! Maybe something like my last change?

```
zap trash: [
        "~/Library/Application Support/AIR Music Technology/EnginePrime",
        "~/Library/Caches/AIR Music Technology/EnginePrime",
        "~/Library/Preferences/com.air-music-technology.EnginePrime.plist",
        "~/Library/Saved Application State/com.air-music-technology.EnginePrime.savedState",
        "~/Music/Engine Library",
      ],
      rmdir: [
        "~/Library/Application Support/AIR Music Technology",
        "~/Library/Caches/AIR Music Technology",
      ]
```

2023-05-30 01:09 UTC, miccal commented
Thank you @djasonic.

2023-05-30 01:10 UTC, miccal approved these changes

2023-05-30 01:10 UTC, merged