Added "PicoScope 7 T&M.app" v7.1.2
Homebrew/homebrew-cask pull request #149980
Opened 2023-06-27 14:50 UTC by HendrikLamar

So far, only the PicoScope Beta software was available. Now, I added the stable version of the software in it's most recent version.

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).  
  - In my opinion this is misleading in since nobody knows what the "T & M" stands for and might confuse people.
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

2023-06-27 18:51 UTC, razvanazamfirei requested changes, later dismissed
Hi @HendrikLamar, thanks so much for opening this! Some comments below!

2023-06-27 18:51 UTC, razvanazamfirei commented on Casks/picoscope.rb
> +  desc "Test & Measurement Software for Picotech Oscilloscopes"
```suggestion
  desc "Oscilloscope test and measurement software"
```

2023-06-27 18:51 UTC, razvanazamfirei commented on Casks/picoscope.rb
> +    regex(%r{href=.*?/PicoScope_(\d+(?:.\d+)*).*\.pkg}i)
```suggestion
    regex(%r{href=.*?/PicoScope_(\d+(?:.\d+)+).*?Stable\.pkg}i)
```

2023-06-27 18:51 UTC, razvanazamfirei commented on Casks/picoscope.rb
> +  #  /opt/homebrew/Casksroom/..."
Would you mind clarifying what this means?

2023-06-28 00:35 UTC, miccal commented
Thank you @HendrikLamar.

2023-06-28 00:35 UTC, miccal approved these changes

2023-06-28 00:35 UTC, merged

2023-06-28 04:33 UTC, HendrikLamar commented on Casks/picoscope.rb
> +  #  /opt/homebrew/Casksroom/..."
Sure.
According to the docs the `app` stanza is kind of needed. However, the given stanza ends up in the error message

``` bash
Error: It seems the App source '/opt/homebrew/Caskroom/picoscope/7.1.2.15463/PicoScope 7 T&M.app' is not there.
```

when `brew install picoscope` is exectued.

However, if you are all fine without the `app` stanza then we can delete the lines 15 & 16.