[add] Akai MPC Software
Homebrew/homebrew-cask pull request #150346
Opened 2023-07-04 08:35 UTC by roolo

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask --online mpc-software` is error-free.
  - Audit reported error, which I wasn't able to fix / debug / understand. Pls throw a link at me which explains this
    ```
       $ brew audit --cask --online mpc-software
      ==> Downloading https://cdn.inmusicbrands.com/akai/MPC2/2121_sufbchdj/Install-MPC-v2.12-2.12.1.35-release-Mac.zip
      Already downloaded: /Users/mailo/Library/Caches/Homebrew/downloads/5383e709546f93c1b5442669070fb55fc4d770f460142b566d6f0e01aae83ff0--Install-MPC-v2.12-2.12.1.35-release-Mac.zip
      homebrew/core
        * audit_exceptions/versioned_dependencies_conflicts_allowlist.json references
          formulae or casks that are not found in the homebrew/core tap.
          Invalid formulae or casks: predictionio
        * pypi_formula_mappings.json references
          formulae or casks that are not found in the homebrew/core tap.
          Invalid formulae or casks: rtv
      Error: 2 problems in 1 tap detected.
    ```
- [x] `brew style --fix mpc-software` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask mpc-software` worked successfully.
- [ ] `brew install --cask mpc-software` worked successfully.
- [ ] `brew uninstall --cask mpc-software` worked successfully.

2023-07-04 11:51 UTC, razvanazamfirei commented on Casks/mpc-software.rb
> +  url "https://cdn.inmusicbrands.com/akai/MPC2/2121_sufbchdj/Install-MPC-v2.12-#{version}-release-Mac.zip",
Is there a difference between this url and
`https://cdn.inmusicbrands.com/akai/MPC/2121_kdhebxog/MPC%202.12.1%20Updater.app.zip`?

2023-07-04 12:16 UTC, bevanjkay commented on Casks/mpc.rb
> +        "/usr/local/bin/iloktool",
I'm not sure about including the `ilok` related items, even in zap. As it is likely that they are relevant to other applications, unless the bundle ID change between ilok-locked software. I'm familiar with ilok, but not how it installs.

2023-07-04 12:19 UTC, bevanjkay commented on Casks/mpc.rb
> +        "/usr/local/bin/iloktool",
Further to this, is [`ilok-license-manager`](https://github.com/homebrew/homebrew-cask/tree/master/Casks/ilok-license-manager.rb) bundled with this software, or is it separate?

Even if it's bundled I don't think we should zap anything anyway (you can see that the files are relevant to the `ilok` package independently from it's own cask) - as it would break other software that uses `ilok` for licensing.

2023-07-04 12:19 UTC, razvanazamfirei requested changes

2023-07-04 12:19 UTC, razvanazamfirei commented on Casks/mpc.rb
> +  url "https://cdn.inmusicbrands.com/akai/MPC2/#{version.major_minor_patch.no_dots}_sufbchdj/Install-MPC-v#{version.major_minor}-#{version}-release-Mac.zip",
Is there a difference between this url and
`https://cdn.inmusicbrands.com/akai/MPC/2121_kdhebxog/MPC%202.12.1%20Updater.app.zip`?

2023-07-04 12:19 UTC, razvanazamfirei commented on Casks/mpc.rb
> +cask "mpc" do
The app installed is called MPC. I think this should be the cask name.

2023-07-04 12:19 UTC, razvanazamfirei commented on Casks/mpc.rb
> +  url "https://cdn.inmusicbrands.com/akai/MPC2/#{version.major_minor_patch.no_dots}_sufbchdj/Install-MPC-v#{version.major_minor}-#{version}-release-Mac.zip",
Slightly concerned that `#{version.major_minor_patch.no_dots}_sufbchdj` is not stable. If that becomes a problem, we could capture it in the regex (what is now non-capturing group 1.

```
regex(%r{href=.*?/MPC2/\d+[._-](?:\w+)/Install[._-]MPC[._-]v?[\d.]+[_-](\d+(?:\.\d+)+)[_-]release[_-]Mac\.zip"}i)`
```

2023-07-04 12:19 UTC, razvanazamfirei commented on Casks/mpc.rb
> +  zap delete:    [
There are probably more things that should be included in the zap that I can't find since it requires a license. 

Of note, the cask also installs `ilok`, which is why all relevant files are included in zap.

2023-07-04 12:21 UTC, bevanjkay commented on Casks/mpc.rb
> +        "/usr/local/bin/iloktool",
These also shouldn't be included in the `uninstall` stanza to satisfy CI, as they will break other applcation.

2023-07-04 12:26 UTC, razvanazamfirei commented on Casks/mpc.rb
> +        "/usr/local/bin/iloktool",
Didn't realize you already commented! :) 

It's bundled with the software and I see the concerns. Ideally, we could notify users in the caveates that they may have to run 'brew uninstall ilok-license-manager --zap --force`. I don't think caveats show up on uninstall, though. Perhaps in a postflight block?

2023-07-04 12:35 UTC, bevanjkay commented on Casks/mpc.rb
> +        "/usr/local/bin/iloktool",
Yeah, that could be a good workaround, can we use `ohai` or similar in a `postflight_uninstall`?
It's a fairly unprecedented case. But in terms of CI we do use `ci-skip-install` at the moment for `google-drive` because it installs common software.

2023-07-04 22:12 UTC, bevanjkay commented on Casks/mpc.rb
> +      Please note that other casks may depend on it and it will not be
@razvanazamfirei I think it might be better to say other "applications" or similar as it could affect more than just casks.

2023-07-06 15:14 UTC, razvanazamfirei commented on Casks/mpc.rb
> +      Please note that other casks may depend on it and it will not be
Done.

2023-07-06 15:14 UTC, razvanazamfirei commented on Casks/mpc.rb
> +  url "https://cdn.inmusicbrands.com/akai/MPC2/#{version.major_minor_patch.no_dots}_sufbchdj/Install-MPC-v#{version.major_minor}-#{version}-release-Mac.zip",
@roolo, could you address this?

2023-08-04 00:11 UTC, closed without merging