Add Viso
Homebrew/homebrew-cask pull request #153774
Opened 2023-08-27 16:52 UTC by Ninzero

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask <cask>` worked successfully.
- [ ] `brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

-------

I have two questions about this pull request:

1. I am not sure what is the right format of `version` stanza. This app have different short version and version, It's version is "8.9.1" but short version is "6". The about page of this app says "Viso v6 (8.9.1)". I chose "8.9.1" to be the version, but I am not sure if this is the right decision.
2. When I am testing this cask with `brew install --cask viso`. It tells me that cask viso does not exist. I suspect this is because Homebrew only use the .json file to seach for casks. How to tell Homebrew to check local repository so I can install this cask for testing?

2023-08-27 23:53 UTC, bevanjkay requested changes

2023-08-27 23:53 UTC, bevanjkay commented on Casks/v/viso.rb
> +    "/Library/Preferences/com.apple.P2PSupervisor.plist",
This doesn't look correct

2023-08-28 05:03 UTC, Ninzero commented on Casks/v/viso.rb
> +    "/Library/Preferences/com.apple.P2PSupervisor.plist",
You are right. The zap part is generated by createzap, forgot to check it.

2023-08-28 05:52 UTC, bevanjkay approved these changes

2023-08-28 05:52 UTC, merged