Rename "Mouse Fix" to "Mac Mouse Fix"
Homebrew/homebrew-cask pull request #154230
Opened 2023-09-01 19:58 UTC by noah-nuebling

I made the app Mac Mouse Fix. The naming for the app used to be  inconsistent. In some places it used to be called "Mouse Fix" and in others "Mac Mouse Fix". Now I want to move toward consistently calling the app "Mac Mouse Fix" everywhere and deprecating any use of "Mouse Fix" in official material. The current version of the app bundle is "Mac Mouse Fix.app". This is why I would also like the homebrew formula name to be updated from 'mouse-fix' to 'mac-mouse-fix'.

---

Verified:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions)
- [x] `brew audit --cask --online --strict <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.
- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).

---

A side note: 

The `zap trash` section of this formula only contains the paths:

- "~/Library/Application Support/com.nuebling.mac-mouse-fix"
 - "~/Library/LaunchAgents/com.nuebling.mac-mouse-fix.helper.plist"

However, AppCleaner by FreeMacSoft finds more files that the system creates for Mac Mouse Fix:

![CleanShot 2023-09-01 at 20 49 14](https://github.com/Homebrew/homebrew-cask/assets/40808343/75780dbc-2e7a-4840-ad25-f66323830d47)

Should these also be added to the `zap trash` section?

2023-09-01 23:15 UTC, bevanjkay requested changes
@noah-nuebling Thanks for the update. Can you please sort the cask_renames file alphabetically?

2023-09-01 23:22 UTC, noah-nuebling commented
@bevanjkay I sorted the cask_renames file alphabetically

2023-09-02 00:05 UTC, bevanjkay approved these changes

2023-09-02 00:05 UTC, merged

2023-09-02 00:07 UTC, noah-nuebling commented
Great thanks for the quick replies!