Add "To Audio Converter" by Amvidia
Homebrew/homebrew-cask pull request #156297
Opened 2023-09-27 10:36 UTC by SoCuul

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online toaudioconverter` is error-free.
- [x] `brew style --fix toaudioconverter` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask toaudioconverter` worked successfully.
- [x] `brew install --cask toaudioconverter` worked successfully.
- [x] `brew uninstall --cask toaudioconverter` worked successfully.

2023-09-27 11:18 UTC, bevanjkay requested changes, later dismissed

2023-09-27 11:18 UTC, bevanjkay commented on Casks/t/toaudioconverter.rb
> +cask "toaudioconverter" do
@SoCuul The cask `token` and filename should be `to-audio-converter`.

2023-09-27 11:18 UTC, bevanjkay commented on Casks/t/toaudioconverter.rb
> +  desc "Convert over 200 audio formats with a simplified interface"
```suggestion
  desc "Audio converter"
```

2023-09-29 00:54 UTC, miccal commented
Thank you @SoCuul.

2023-09-29 00:54 UTC, miccal approved these changes

2023-09-29 00:54 UTC, merged