Adds fossa v3.8.18
Homebrew/homebrew-cask pull request #158367
Opened 2023-10-23 16:35 UTC by meghfossa

This PR, 

- Adds new cask: `fossa` with `v3.8.18`

_In the following questions `<cask>` is the token of the cask you're submitting._
After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

2023-10-23 16:42 UTC, SMillerDev commented
Is this not an [open source CLI tool](https://docs.brew.sh/Acceptable-Casks#rejected-casks)?

2023-10-23 16:50 UTC, meghfossa commented
> Is this not an [open source CLI tool](https://docs.brew.sh/Acceptable-Casks#rejected-casks)?

Source code of `fossa-cli` is MPL, but the built and distributed binary (via github releases) also includes propriety executables as embedded in fossa-executable (which are not open source) - so it simply is not possible to make this into formulae. Let me know if there are alternatives. I was recommended to make this into cask - since the reproducible build process is closed-source.

2023-10-23 22:13 UTC, bevanjkay requested changes
@meghfossa Thanks for your contribution to `homebrew-cask`. Based on the closed-source build it looks like `fossa` should be suitable to include in `homebrew-cask`.

Please see my review comments above.

2023-10-23 22:13 UTC, bevanjkay commented on Casks/f/fossa.rb
> +    EOS
@meghfossa Caveats are reserved for Homebrew specific installation caveats, and we try to use them sparingly. Can you please remove this? It is expected that a user would know about the product before installing it through Homebrew, as `homebrew-cask` is not a [discovery service](https://docs.brew.sh/Acceptable-Casks#homebrew-cask-is-not-a-discoverability-service).

2023-10-23 22:13 UTC, bevanjkay commented on Casks/f/fossa.rb
> +  end
@meghfossa This block should be removed, as there are internal checks to ensure that the binary is moved to the correct location.

2023-10-23 22:13 UTC, bevanjkay commented on Casks/f/fossa.rb
> +  end
@meghfossa If you do not use GitHub prereleases or tag releases without binaries, then the livecheck block can be omitted and Homebrew will automatically defer to the default `:git` strategy as inferred from the `url`.

2023-10-23 22:13 UTC, bevanjkay commented on Casks/f/fossa.rb
> +  auto_updates false
@meghfossa This can be omitted as it is the default.

2023-10-24 13:54 UTC, meghfossa commented on Casks/f/fossa.rb
> +  auto_updates false
Addressed in https://github.com/Homebrew/homebrew-cask/pull/158367/commits/5decac22d91909ad6bb191a02a8c9f3dfeb607c4

2023-10-24 13:54 UTC, meghfossa commented on Casks/f/fossa.rb
> +  end
Addressed in https://github.com/Homebrew/homebrew-cask/pull/158367/commits/5decac22d91909ad6bb191a02a8c9f3dfeb607c4

2023-10-24 13:54 UTC, meghfossa commented on Casks/f/fossa.rb
> +  end
Addressed in https://github.com/Homebrew/homebrew-cask/pull/158367/commits/5decac22d91909ad6bb191a02a8c9f3dfeb607c4

2023-10-24 13:54 UTC, meghfossa commented on Casks/f/fossa.rb
> +    EOS
Addressed in https://github.com/Homebrew/homebrew-cask/pull/158367/commits/5decac22d91909ad6bb191a02a8c9f3dfeb607c4

2023-10-24 22:16 UTC, miccal commented on Casks/f/fossa.rb
> +    # fossa-cli requires Rosetta 2 for it to run on Apple Silicon.
Please remove this line, then this PR can be merged.

2023-10-24 22:18 UTC, bevanjkay requested changes
Please try to add a [zap stanza](https://docs.brew.sh/Cask-Cookbook#stanza-zap). The linked documentation provides some recommended methods to create it.

If there is no zap stanza required a line
`# No zap stanza required`
can be added instead.

Example: https://github.com/razvanazamfirei/homebrew-cask/blob/66e0d9f9f38a4b1a79fd747fec556d7438678381/Casks/codeql.rb#L12

2023-10-25 00:34 UTC, bevanjkay approved these changes

2023-10-25 00:36 UTC, bevanjkay requested changes
One last question and then I think we're good to go, if you mark the PR as ready for review.

2023-10-25 00:36 UTC, bevanjkay commented on Casks/f/fossa.rb
> +  name "fossa"
@meghfossa Should this be stylised as below?

```suggestion
  name "FOSSA"
```

2023-10-25 00:45 UTC, krehel commented on Casks/f/fossa.rb
> +  # No zap stanza required
No zap should go before `caveats` (where it would go if there was a zap)

```suggestion
  binary "fossa"

  # No zap stanza required

   caveats do
     requires_rosetta
   end
```

2023-10-26 23:37 UTC, jssblck commented on Casks/f/fossa.rb
> +  url "https://github.com/fossas/fossa-cli/releases/download/v#{version}/fossa_#{version}_darwin_amd64.zip",
Homebrew can run on Linux as well, right? Should we be doing anything different here to handle that case (or at least provide a nicer error)?

2023-10-26 23:50 UTC, krehel commented on Casks/f/fossa.rb
> +  url "https://github.com/fossas/fossa-cli/releases/download/v#{version}/fossa_#{version}_darwin_amd64.zip",
Casks are macOS only

2023-10-27 22:32 UTC, meghfossa commented on Casks/f/fossa.rb
> +  name "fossa"
I would prefer it to be `fossa` for now (same as our previous custom tap).

2023-10-27 22:40 UTC, bevanjkay approved these changes

2023-10-27 22:40 UTC, merged

2023-10-27 22:40 UTC, bevanjkay commented
Thank you @meghfossa

2023-10-27 22:42 UTC, meghfossa commented
@bevanjkay, what do we need to do to have this cask in this official auto-bump: https://github.com/Homebrew/homebrew-cask/blob/master/.github/workflows/autobump.yml#L14. Is it matter of submitting a PR?

2023-10-27 22:45 UTC, bevanjkay commented
@meghfossa Yes a PR can be opened to add it to autobump. Otherwise Casks are often bumped by contributors and maintainers using the `brew bump` command.