Adding cask for TikTok Effect House
Homebrew/homebrew-cask pull request #160543
Opened 2023-11-19 22:57 UTC by matthewhuie

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x ] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x ] `brew audit --cask --online <cask>` is error-free.
- [x ] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x ] `brew audit --new-cask <cask>` worked successfully.
- [x ] `brew install --cask <cask>` worked successfully.
- [ x] `brew uninstall --cask <cask>` worked successfully.

2023-11-19 23:47 UTC, bevanjkay commented on Casks/t/tiktok-effecthouse.rb
> +  url "https://sf16-va.tiktokcdn.com/obj/eden-va2/olaa_ajlmml_zlp/ljhwZthlaukjlkulzlp/341_ExternalRelease_1107/Effect_House_#{version}.dmg",
@matthewhuie This url looks like it is not likely to be stable between releases. Is the `version` the only thing that changes?

2023-11-19 23:47 UTC, bevanjkay commented on Casks/t/tiktok-effecthouse.rb
> +cask "tiktok-effecthouse" do
The `token` here should be `effect-house` (and filename to match).

2023-11-20 00:04 UTC, matthewhuie commented on Casks/t/tiktok-effecthouse.rb
> +cask "tiktok-effecthouse" do
Corrected, thanks!

2023-11-20 00:04 UTC, matthewhuie commented on Casks/t/tiktok-effecthouse.rb
> +  url "https://sf16-va.tiktokcdn.com/obj/eden-va2/olaa_ajlmml_zlp/ljhwZthlaukjlkulzlp/341_ExternalRelease_1107/Effect_House_#{version}.dmg",
Corrected, thanks!

2023-11-20 00:17 UTC, razvanazamfirei requested changes, later dismissed

2023-11-20 00:17 UTC, razvanazamfirei commented on Casks/e/effect-house.rb
> +  url "https://sf16-va.tiktokcdn.com/obj/eden-va2/olaa_ajlmml_zlp/ljhwZthlaukjlkulzlp/#{version.csv.first.no_dots}_ExternalRelease_#{version.csv.third}/Effect_House_v#{version.csv.first}.#{version.cs
This url looks stable, but the versioning for this may be difficult to extract.

2023-11-20 00:17 UTC, razvanazamfirei commented on Casks/e/effect-house.rb
> +  end
We would need a way to extract all version components.

2023-11-20 00:17 UTC, razvanazamfirei commented on Casks/e/effect-house.rb
> +  zap trash: "~/Library/Application Support/EffectHouse"
More files should be added to the zap based on the bundle ID: `com.ies.orion`

2023-11-20 00:21 UTC, bevanjkay commented
Alternatively we could use the `:post` download strategy, 

```ruby
  url "https://effecthouse.tiktok.com/api/web/download",
      using: :post,
      data:  {
        "osType" => "macOS",
        "arch"   => arch.to_s,
      }
```

But this won't allow us to have a `version`.

In future this could be used for `livecheck` however we can't use `post` requests until they are implemented in `livecheck`.

2023-11-24 03:58 UTC, miccal commented
Thank you @matthewhuie, but please note that if we find the `url`'s are unstable then this Cask may be removed in the future.

2023-11-24 03:58 UTC, miccal approved these changes

2023-11-24 03:59 UTC, merged