Add cask `timemachinestatus`
Homebrew/homebrew-cask pull request #160646
Opened 2023-11-21 05:32 UTC by lukepistrol

Adds `timemachinestatus` cask for [TimeMachineStatus](https://github.com/lukepistrol/TimeMachineStatus) project.

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

2023-11-21 05:36 UTC, bevanjkay commented
/rebase

2023-11-21 05:43 UTC, bevanjkay requested changes, later dismissed

2023-11-21 05:43 UTC, bevanjkay commented on Casks/t/timemachinestatus.rb
> +
I assume based on the `appcast` in the url that the app has an auto-update mechanism.
If so, please add `auto_updates true`

2023-11-21 05:43 UTC, bevanjkay commented on Casks/t/timemachinestatus.rb
> +      ]
This should also be in the `trash` array unless you have a specific reason to include it here?

2023-11-21 05:43 UTC, bevanjkay commented on Casks/t/timemachinestatus.rb
> +  desc "Little menu bar app to show more info about Time Machine than the system default"
```suggestion
  desc "Menu bar app to show Time Machine information"

2023-11-21 05:58 UTC, lukepistrol commented on Casks/t/timemachinestatus.rb
> +      ]
Right! added :-)

2023-11-21 05:58 UTC, lukepistrol commented on Casks/t/timemachinestatus.rb
> +
Added :-)

2023-11-21 06:04 UTC, bevanjkay commented on Casks/t/timemachinestatus.rb
> +      ]
Sorry, my comment wasn't very clear. What I meant was that it should only be in the `trash` array and not the `delete` array.

2023-11-21 06:12 UTC, lukepistrol commented on Casks/t/timemachinestatus.rb
> +      ]
Oh sorry I misunderstood… fixed!

2023-11-24 03:48 UTC, miccal commented
/rebase

2023-11-24 03:55 UTC, miccal commented
Thank you @lukepistrol.

2023-11-24 03:55 UTC, miccal approved these changes

2023-11-24 03:55 UTC, merged