Add new cask `mindmac`
Homebrew/homebrew-cask pull request #160891
Opened 2023-11-23 20:39 UTC by singularitti

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

2023-11-23 20:40 UTC, singularitti commented
`brew audit` was not successful but this cask has an official webpage. So not a GitHub repo.

2023-11-23 23:00 UTC, bevanjkay requested changes, later dismissed

2023-11-23 23:00 UTC, bevanjkay commented on Casks/m/mindmac.rb
> +  homepage "https://mindmac.app/index.html"
```suggestion
  homepage "https://mindmac.app"
```

2023-11-23 23:39 UTC, miccal commented on Casks/m/mindmac.rb
> +
```suggestion
depends_on macos: ">= :Ventura"

```

2023-11-24 03:27 UTC, miccal approved these changes

2023-11-24 03:27 UTC, merged

2023-11-24 03:27 UTC, miccal commented
Thank you @singularitti.

2023-11-24 04:03 UTC, singularitti commented
Thank you guys!