adds codewhisperer 0.12.0 cask
Homebrew/homebrew-cask pull request #161105
Opened 2023-11-27 20:21 UTC by ajzeigert

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

2023-11-27 23:17 UTC, bevanjkay commented on Casks/c/codewhisperer.rb
> +  homepage "https://docs.aws.amazon.com/codewhisperer/latest/userguide/command-line-getting-started-installing.html"
```suggestion
  homepage "https://aws.amazon.com/codewhisperer/"
```

2023-11-27 23:26 UTC, bevanjkay commented on Casks/c/codewhisperer.rb
> +  desc "IDE-style autocomplete for 500+ CLIs. Translate natural language-to-bash"
```suggestion
  desc "AI-powered productivity tool for the IDE and command line"
```

2023-11-27 23:32 UTC, bevanjkay requested changes
@ajzeigert I have added a `livecheck` stanza and updated the `url` to be versioned to match. Please see additional review comments.

2023-11-28 18:31 UTC, ajzeigert commented on Casks/c/codewhisperer.rb
> +  desc "IDE-style autocomplete for 500+ CLIs. Translate natural language-to-bash"
This cask is specifically for the command line tool, which is separate from the IDE plugins. The description I provided was taken directly from how the app describes itself, but I understand if that is too long.

![Screenshot 2023-11-28 at 10 24 57 AM](https://github.com/Homebrew/homebrew-cask/assets/7832935/3bacf051-cfa9-4e1e-bd9f-f14d26117834)

![Screenshot 2023-11-28 at 10 25 02 AM](https://github.com/Homebrew/homebrew-cask/assets/7832935/958b7405-0ab4-4de0-96a2-5dbb7bd953cb)

Maybe just "AI-powered productivity tool for the command line"?

2023-11-28 20:29 UTC, bevanjkay approved these changes

2023-11-28 20:29 UTC, merged