salt: 3006.5
Homebrew/homebrew-cask pull request #162371
Opened 2023-12-12 23:35 UTC by cdalvaro

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --cask --new <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

2023-12-12 23:36 UTC, cdalvaro commented
This cask is a replacement for the deprecated `salt` formula.

2023-12-13 09:17 UTC, cdalvaro commented
> This cask is a replacement for the deprecated and disabled `salt` formula. Maybe it's time to remove the `salt` formula from the _core_ repository?

I would like to know @SMillerDev's opinion about this.

2023-12-13 09:23 UTC, SMillerDev commented
Sounds fine to me, it's been deprecated and disabled for a while already.

2023-12-13 12:30 UTC, bevanjkay commented on Casks/s/salt.rb
> +  end
Can you provide some commentary on why this `postflight` block is necessary, and perhaps add a comment to code explaining it succinctly?

2023-12-13 12:31 UTC, bevanjkay commented on Casks/s/salt.rb
> +              "com.saltstack.salt.*",
I don't believe that globs are supported for `launchctl`.

2023-12-14 08:22 UTC, SMillerDev commented on Casks/s/salt.rb
> +  end
I don't think we should use a post block to fix the deficiencies in salt.

2023-12-14 08:44 UTC, cdalvaro commented on Casks/s/salt.rb
> +  end
So, as an alternative, could this be handled as an optional step, disabled by default?

2023-12-14 08:49 UTC, SMillerDev commented on Casks/s/salt.rb
> +  end
No, it should be fixed upstream

2023-12-14 09:54 UTC, SMillerDev commented on Casks/s/salt.rb
> +  end
Maybe make an issue/PR upstream and link there with a caveat?

2023-12-14 10:05 UTC, cdalvaro commented on Casks/s/salt.rb
> +  end
I'll try to improve this PR: https://github.com/saltstack/salt/pull/64924

So, I think neither the modification of the plist files, nor the caveats documentation will be necessary.

2023-12-14 16:59 UTC, cdalvaro commented on Casks/s/salt.rb
> +  end
`postflight` removed

2023-12-15 10:33 UTC, SMillerDev commented on Casks/s/salt.rb
> +      sudo launchctl load -w /Library/LaunchDaemons/com.saltstack.salt.api
Shouldn't this be a `.plist`?

2023-12-15 10:33 UTC, SMillerDev commented on Casks/s/salt.rb
> +      https://docs.saltproject.io/salt/install-guide/en/latest/topics/configure-master-minion.html
Since this is not a homebrew specific instruction I don't think it should be a caveat

2023-12-15 20:02 UTC, cdalvaro commented on Casks/s/salt.rb
> +      sudo launchctl load -w /Library/LaunchDaemons/com.saltstack.salt.api
Done!

2023-12-15 20:02 UTC, cdalvaro commented on Casks/s/salt.rb
> +      https://docs.saltproject.io/salt/install-guide/en/latest/topics/configure-master-minion.html
Done!

2023-12-18 01:33 UTC, bevanjkay commented on Casks/s/salt.rb
> +  conflicts_with formula: "salt"
Now that `salt` has been removed from `homebrew-core`, this line needs to be removed here too.

2023-12-18 06:51 UTC, SMillerDev commented on Casks/s/salt.rb
> +
Since this is not specific to the Homebrew install.
```suggestion
```

2023-12-18 06:51 UTC, SMillerDev commented on Casks/s/salt.rb
> +      Load services you need:
```suggestion
      Included services:
```

2023-12-18 22:11 UTC, cdalvaro commented on Casks/s/salt.rb
> +      Load services you need:
Done!

2023-12-18 22:11 UTC, cdalvaro commented on Casks/s/salt.rb
> +
Done!

2023-12-18 22:11 UTC, cdalvaro commented on Casks/s/salt.rb
> +  conflicts_with formula: "salt"
Done!

2023-12-18 22:18 UTC, bevanjkay requested changes

2023-12-18 22:18 UTC, bevanjkay commented on Casks/s/salt.rb
> +  desc "World's fastest, most intelligent and scalable automation engine"
```suggestion
  desc "Automation and infastructure management engine"
```

2023-12-18 22:22 UTC, bevanjkay commented on Casks/s/salt.rb
> +    regex(/salt-(\d+(?:\.\d+)?(?:-\d+)?)-py3-#{arch}\.pkg/)
```suggestion
    regex(/salt[._-]v?(\d+(?:\.\d+)+)-py3-#{arch}\.pkg/)
```

2023-12-19 07:42 UTC, cdalvaro commented on Casks/s/salt.rb
> +  desc "World's fastest, most intelligent and scalable automation engine"
Done!

2023-12-19 07:42 UTC, cdalvaro commented on Casks/s/salt.rb
> +  ]
Done!

2023-12-19 07:42 UTC, cdalvaro commented on Casks/s/salt.rb
> +    regex(/salt-(\d+(?:\.\d+)?(?:-\d+)?)-py3-#{arch}\.pkg/)
Done!

2023-12-19 08:13 UTC, bevanjkay commented
Thanks @cdalvaro 

Using `ci-syntax-only` to skip the token conflict check.

2023-12-19 08:13 UTC, bevanjkay approved these changes

2023-12-19 08:17 UTC, merged