wordpresscom: fix livecheck and add arm64
Homebrew/homebrew-cask pull request #162804
Opened 2023-12-18 23:18 UTC by toobuntu

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --cask --new <cask>` worked successfully.
- [ ] `brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

---

Cask wordpresscom has the following out-of-date:

- The livecheck seems to not work correctly.
- It lacks support for Apple Silicon, although there is a download for it from [wordpress.com](https://apps.wordpress.com/d/osx-silicon/).
- Upstream defined :high_sierra as the minimum OS version and the cask defined no minimum OS version.
- It is missing `auto_updates true`.
- A `find` revealed additional lines to add to the zap stanza, as well as one path which was no longer present. That path (`~/Library/Preferences/com.automattic.wordpress.helper.plist`) was incorporated into a similar path (`~/Library/Preferences/com.automattic.wordpress.plist`) with a wildcard * in this commit, so it is not lost for those who do have it from an older version.

See https://github.com/orgs/Homebrew/discussions/4988#discussioncomment-7879360 for more detail about some of the decisions made, regarding changing the livecheck url and strategy and the download url and type (dmg instead of zip).

Thank you for maintaining this great project. Regards.

2023-12-18 23:29 UTC, bevanjkay requested changes

2023-12-18 23:29 UTC, bevanjkay commented on Casks/w/wordpresscom.rb
> +    end
This requires a regex to be passed. I think we should be able to try using the below instead, unless upstream have releases without MacOS related binaries.

```suggestion
    url :url
    strategy :github_latest
```

2023-12-18 23:30 UTC, bevanjkay commented on Casks/w/wordpresscom.rb
> +  url "https://github.com/Automattic/wp-desktop/releases/download/v#{version}/wordpress.com-macOS-dmg-#{version}-#{arch}.dmg", verified: "github.com/Automattic/wp-desktop/"
```suggestion
  url "https://github.com/Automattic/wp-desktop/releases/download/v#{version}/wordpress.com-macOS-dmg-#{version}-#{arch}.dmg",
       verified: "github.com/Automattic/wp-desktop/"
```

2023-12-18 23:33 UTC, bevanjkay commented
@toobuntu Thanks for this, I have made a couple of comments above.

2023-12-19 02:20 UTC, toobuntu commented on Casks/w/wordpresscom.rb
> +    end
Good catch with `url :url`. Thanks!

Does `:github_latest` skip betas/pre-releases? This is unclear to me from the [livecheck docs](https://docs.brew.sh/Brew-Livecheck#githublatest-strategy-block).

Upstream does publish betas, as well as packages for Linux and Windows, at that [GitHub Releases url](https://github.com/Automattic/wp-desktop/releases).

I was under the impression that

1. `:github_latest` does not skip betas, and the only way to do that is as in my initial commit, and
3. that, absent a specified regex, livecheck will resort to a fallback regex.

2023-12-19 02:32 UTC, bevanjkay commented on Casks/w/wordpresscom.rb
> +    end
`:github_latest` will use the release that is marked as "latest" in the repository.
If upstream mark pre-releases/betas as "latest" then it will not work.

2023-12-19 02:39 UTC, toobuntu commented on Casks/w/wordpresscom.rb
> +    end
Is there any way to find out if they have done that, historically, after-the-fact? Otherwise, it seems this PR could languish until upstream decides to release another beta.

2023-12-19 02:56 UTC, toobuntu commented
Thank you for the review feedback. Updated and force pushed.

2023-12-19 02:57 UTC, bevanjkay approved these changes

2023-12-19 03:02 UTC, merged