laverna: deprecate
Homebrew/homebrew-cask pull request #163592
Opened 2024-01-01 19:37 UTC by chenrui333

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [ ] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask --online <cask>` is error-free.
- [ ] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --cask --new <cask>` worked successfully.
- [ ] `brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

---

depends on #163591

2024-01-01 19:50 UTC, SMillerDev requested changes, later dismissed

2024-01-01 19:50 UTC, SMillerDev commented on Casks/l/laverna.rb
> +  deprecate! date: "2024-01-01", because: "use `encryptic` instead"
We can make recommendations in caveats, but it's the wrong deprecation reason.

2024-01-01 22:40 UTC, chenrui333 commented on Casks/l/laverna.rb
> +  deprecate! date: "2024-01-01", because: "use `encryptic` instead"
maybe `encryptic` is not a good alternative as there is no new release for it either, I will just seek for the deprecation for this PR then.

2024-01-01 22:53 UTC, bevanjkay commented on Casks/l/laverna.rb
> +  deprecate! date: "2024-01-01", because: unmaintained
```suggestion
  deprecate! date: "2024-01-01", because: :unmaintained
```

2024-01-02 00:40 UTC, bevanjkay approved these changes

2024-01-02 00:57 UTC, merged