hancock: deprecate
Homebrew/homebrew-cask pull request #163590
Opened 2024-01-01 19:15 UTC by chenrui333

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --cask --new <cask>` worked successfully.
- [ ] `brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

---

- https://github.com/JeremyAgost/Hancock/issues/8
- https://github.com/JeremyAgost/Hancock/issues/7
- https://github.com/JeremyAgost/Hancock/issues/6

2024-01-01 19:17 UTC, krehel commented
If the app no longer works it should be removed imho

2024-01-01 19:19 UTC, SMillerDev commented
We can disable it then, which would make for a much nicer experience for users.

2024-01-01 19:39 UTC, chenrui333 commented
> If the app no longer works it should be removed imho

I think it just does not work for the newer systems (that is my guess)

2024-01-01 19:46 UTC, krehel commented
That's fair.  I tend to err on not keeping broken things, especially if non functional for a relatively long time.  `disable` is a good option.

2024-01-01 19:54 UTC, SMillerDev commented
Not letting people install broken things is good, but if you remove the cask existing users will never know they should look for a replacement.

2024-01-01 19:56 UTC, krehel commented
Great point @SMillerDev.  Always appreciate your insights.  I am probably too aggressive with my thought process, the mediation is good. 👍

2024-01-01 22:07 UTC, bevanjkay approved these changes

2024-01-01 22:09 UTC, bevanjkay requested changes

2024-01-01 22:09 UTC, bevanjkay commented on Casks/h/hancock.rb
> +  disable! date: "2024-08-01", because: :unmaintained
@chenrui333 How is the date determined for disabling?

2024-01-02 01:12 UTC, p-linnane commented on Casks/h/hancock.rb
> +  disable! date: "2024-08-01", because: :unmaintained
This would be a good AGM topic, as we are planning to discuss how we do it for formulae then.

2024-01-02 03:58 UTC, chenrui333 commented on Casks/h/hancock.rb
> +  disable! date: "2024-08-01", because: :unmaintained
that is a typo, should be 2024-01-01 😆

2024-01-02 04:09 UTC, bevanjkay approved these changes

2024-01-04 05:13 UTC, merged