coteditor: update uninstall and livecheck
Homebrew/homebrew-cask pull request #163945
Opened 2024-01-07 04:23 UTC by toobuntu

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --cask --new <cask>` worked successfully.
- [ ] `brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

2024-01-07 05:29 UTC, bevanjkay requested changes

2024-01-07 05:29 UTC, bevanjkay commented on Casks/c/coteditor.rb
> +  uninstall quit: [
Can you make this a string instead of a single length array?

2024-01-07 19:58 UTC, toobuntu commented on Casks/c/coteditor.rb
> +  uninstall quit: [
Done!

2024-01-07 22:34 UTC, bevanjkay commented
There is a CI issue, ref: https://github.com/Homebrew/brew/pull/16438

2024-01-08 00:08 UTC, bevanjkay commented
/rebase

2024-01-08 00:08 UTC, bevanjkay approved these changes

2024-01-08 00:15 UTC, merged