Use path for audit.
Homebrew/homebrew-cask pull request #163917
Opened 2024-01-06 11:14 UTC by reitermarkus

Make `audit` step consistent with other steps. All other steps use the token for the `name` and path for the actual `run` command.

2024-01-06 11:50 UTC, SMillerDev requested changes
Aren't we discouraging everyone from using paths for commands? I'd be surprised if this actually worked as expected

2024-01-06 12:09 UTC, reitermarkus commented
Right, I only checked `install`, it doesn't work for `audit`:

```
Error: Calling brew audit [path ...] is disabled! Use brew audit [name ...] instead.
```

It's kinda weird we only do this for `audit` though. Shouldn't this be disabled for all commands?

2024-01-18 20:55 UTC, p-linnane commented
Do we still need this PR based off the above?

2024-01-22 16:54 UTC, p-linnane commented
Closing for now. We can reopen if it's determined me need this.

2024-01-22 16:54 UTC, closed without merging