Add iA Presenter
Homebrew/homebrew-cask pull request #163918
Opened 2024-01-06 12:22 UTC by andre4ik3

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --cask --new <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

2024-01-06 12:29 UTC, SMillerDev commented on Casks/i/ia-presenter.rb
> +  depends_on macos: ">= :monterey"
Upstream defines it as:
```suggestion
  depends_on macos: ">= : big_sur"
```

2024-01-06 12:31 UTC, andre4ik3 commented on Casks/i/ia-presenter.rb
> +  depends_on macos: ">= :monterey"
Yup, already changed it. Not sure if it defines the correct version tho? It needs 11.3, not 11.0, I didn't see a way to put 11.3 in the cask cookbook so I just put monterey.

![CleanShot 2024-01-06 at 16 30 09@2x](https://github.com/Homebrew/homebrew-cask/assets/62390580/6c70c4db-d1b9-406f-8f24-c48c0209aed9)

2024-01-07 04:28 UTC, bevanjkay requested changes

2024-01-07 04:28 UTC, bevanjkay commented on Casks/i/ia-presenter.rb
> +  name "ia-presenter"
```suggestion
  name "iA Presenter"
```

2024-01-07 04:30 UTC, bevanjkay requested changes

2024-01-07 04:30 UTC, bevanjkay commented on Casks/i/ia-presenter.rb
> +    end
Should use the default sparkle here that returns the versions separated by a comma. 

Then update the url using `#{version.csv.first}-#{version.csv.second}`

2024-01-07 22:47 UTC, bevanjkay approved these changes

2024-01-07 22:47 UTC, merged

2024-01-07 22:48 UTC, bevanjkay commented
Thank you @andre4ik3