shadow-bot 1.4.1 (new cask)
Homebrew/homebrew-cask pull request #164418
Opened 2024-01-14 08:08 UTC by moonfruit

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --cask --new <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

2024-01-14 11:36 UTC, bevanjkay requested changes
Please see review comments above.
Does the app have an in-app updating mechanism?

2024-01-14 11:36 UTC, bevanjkay commented on Casks/s/shadow-bot.rb
> +  arch arm: "-arm64", intel: ""
```suggestion
  arch arm: "-arm64"
  livecheck_query = on_arch_conditional arm: "arm64", intel: "intel"
```

Accompanied by changes to `livecheck` below.

2024-01-14 11:36 UTC, bevanjkay commented on Casks/s/shadow-bot.rb
> +    url "https://api.yingdao.com/api/v1/sys/download/client?os=mac&arch=intel"
```suggestion
  url "https://api.yingdao.com/api/v1/sys/download/client?os=mac&arch=#{livecheck_query}"
  regex(/ShadowBot[._-]v?(\d+(?:\.\d+)+)#{arch}\.dmg/i)
```

2024-01-15 01:33 UTC, moonfruit commented
I'm not aware of any in-app updating mechanism for now.

2024-01-15 01:44 UTC, bevanjkay approved these changes

2024-01-15 01:50 UTC, merged