Base 20.00.05.00
Homebrew/homebrew-cask pull request #164757
Opened 2024-01-18 15:09 UTC by tdclienttools

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --cask --new <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

Re: Closing this as there is not an easily discoverable public download. 
Our first submission failed for the above reason. The above issue is now fixed.

2024-01-18 18:41 UTC, p-linnane approved these changes

2024-01-18 19:28 UTC, krehel requested changes, later dismissed

2024-01-18 19:28 UTC, krehel commented on Casks/t/ttu-base-suite.rb
> +  url "https://downloads.teradata.com/sites/default/files/2024-01/TeradataToolsAndUtilities-macosx-brew-#{version}.tar"
the `2024-01` I assume is a yyyy-mm date, which will cause problems in the future if changed for versions.  This should be a variable as part of `version`

2024-01-18 19:29 UTC, p-linnane commented on Casks/t/ttu-base-suite.rb
> +  url "https://downloads.teradata.com/sites/default/files/2024-01/TeradataToolsAndUtilities-macosx-brew-#{version}.tar"
Yeah we can grab that with livecheck and append it to the version like `20.00.05.00,2024-01`.

2024-01-18 20:07 UTC, tdclienttools commented on Casks/t/ttu-base-suite.rb
> +  url "https://downloads.teradata.com/sites/default/files/2024-01/TeradataToolsAndUtilities-macosx-brew-#{version}.tar"
Re: the 2024-01 in the url I assume is a yyyy-mm date, which will cause problems in the future if changed for versions.

The URL will be different for each version. It is not clear to me why you think this is an issue? We plan on only providing the latest release in homebrew so for each release we will update the URL in the cask file and re-submitted it. I haven't seen anywhere in the homebrew documentation that implies that this cannot be done.

2024-01-18 20:40 UTC, bevanjkay commented on Casks/t/ttu-base-suite.rb
> +  url "https://downloads.teradata.com/sites/default/files/2024-01/TeradataToolsAndUtilities-macosx-brew-#{version}.tar"
Because `livecheck` should always return the most recent release. So any part of the url that changes needs to be interpolated as part of the version, and also detectable by `livecheck`. 

Homebrew is not a place for vendors to solely release their software and maintain a cask. Any contributor should be able to make trivial changes like version bumps without having any inside knowledge. Otherwise, you would be better hosting the cask in your own tap.

2024-01-18 20:48 UTC, krehel commented on Casks/t/ttu-base-suite.rb
> +  url "https://downloads.teradata.com/sites/default/files/2024-01/TeradataToolsAndUtilities-macosx-brew-#{version}.tar"
> The URL will be different for each version. It is not clear to me why you think this is an issue? We plan on only providing the latest release in homebrew since we release each month. So, for each release we will update the URL in the cask file and re-submitted it.

Here's an example: if the URL is hard coded to contain `2024-01` as this is right now, then your version is updated and the new download URL is `2024-02`, how would this be updated short of only you as a vendor?  It has to be parameterized or the download link will break when the version itself is updated.

A Cask should be updatable by anyone with the automated tools that have been developed for this purpose.

2024-01-18 20:54 UTC, p-linnane commented on Casks/t/ttu-base-suite.rb
> +  url "https://downloads.teradata.com/sites/default/files/2024-01/TeradataToolsAndUtilities-macosx-brew-#{version}.tar"
I've pushed a change that will resolve this issue. I'd just like @samford to weigh in on the livecheck before this is merged.

2024-01-18 20:55 UTC, tdclienttools commented on Casks/t/ttu-base-suite.rb
> +  url "https://downloads.teradata.com/sites/default/files/2024-01/TeradataToolsAndUtilities-macosx-brew-#{version}.tar"
Thank you so much for your help.

2024-01-19 02:20 UTC, samford commented on Casks/t/ttu-base-suite.rb
> +      end
```suggestion
    url :homepage
    regex(%r{href=.*?/(\d+(?:-\d+)+)/TeradataToolsAndUtilities-macosx-brew[._-]v?(\d+(?:\.\d+)+)\.t}i)
    strategy :page_match do |page, regex|
      page.scan(regex).map { |match| "#{match[1]},#{match[0]}" }
```

I'm good with this approach after some small tweaks.

2024-01-19 02:24 UTC, p-linnane approved these changes

2024-01-19 12:18 UTC, bevanjkay approved these changes

2024-01-19 15:05 UTC, krehel commented
I am fine with this I think.

@tdclienttools, I don't usually comment on vendor software but I _highly_ recommend running your scripts through Shellcheck and reworking some of the internals.  There are some unnecessarily complicated constructs just for removal / deletion of packages and the quoting done for variables and commands does not work as intended.

2024-01-19 16:09 UTC, p-linnane approved these changes

2024-01-19 16:09 UTC, merged