nightshade 1.0 (new cask, based on the glaze cask)
Homebrew/homebrew-cask pull request #164906
Opened 2024-01-20 12:35 UTC by maia-s

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --cask --new <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

2024-01-20 12:43 UTC, maia-s commented
The arm test failed because it timed out. Downloads from their site are currently slow.

I don't know why it tried to run an intel test. The cask only defines the arm arch. Nightshade is only available for M1+.

2024-01-21 04:32 UTC, bevanjkay commented
You can add `depends_on arch: :arm64`.

**Maintainer note:** CI will not be able to try to install this, so we will need to manually verify this to make sure that it works.

2024-01-21 09:39 UTC, maia-s commented
> You can add `depends_on arch: :arm64`.
Thanks, added.

2024-01-21 09:46 UTC, maia-s commented
Fixed the description

2024-01-21 10:24 UTC, bevanjkay commented on Casks/n/nightshade.rb
> +  desc "Tool for \"poisoning\" images so that AI models training on them will mislearn"
```suggestion
  desc "Tool that makes images unsuitable for model training"
```

2024-01-21 10:54 UTC, bevanjkay requested changes

2024-01-21 10:54 UTC, bevanjkay commented on Casks/n/nightshade.rb
> +
```suggestion
```

Because there is only an arm version, we don't need to include the `arch` variable.

2024-01-21 10:54 UTC, bevanjkay commented on Casks/n/nightshade.rb
> +  sha256 arm: "8d015e1f736a7873a81b50dc52dc8e2bd8babffd8026410e5ce9d0e45ef89669"
```suggestion
  sha256 "8d015e1f736a7873a81b50dc52dc8e2bd8babffd8026410e5ce9d0e45ef89669"
```

2024-01-21 10:54 UTC, bevanjkay commented on Casks/n/nightshade.rb
> +  url "https://mirror.cs.uchicago.edu/fawkes/files/nightshade/Nightshade-#{version}-#{arch}.dmg"
```suggestion
  url "https://mirror.cs.uchicago.edu/fawkes/files/nightshade/Nightshade-#{version}-m1.dmg"
```

2024-01-21 14:18 UTC, maia-s commented
I implemented all the requested changes, but I put "AI model training" instead of just "model training" in the description because I think the latter is too vague.

2024-01-21 14:20 UTC, maia-s commented on Casks/n/nightshade.rb
> +  desc "Tool for \"poisoning\" images so that AI models training on them will mislearn"
I changed it to "Tool that makes images unsuitable for AI model training" because I think just "model training" is too vague.

2024-01-21 20:47 UTC, bevanjkay approved these changes

2024-01-22 17:00 UTC, p-linnane commented on Casks/n/nightshade.rb
> +  zap trash: "~/.glaze"
Can this be installed with glaze at the same time? Or do they conflict? I'm wondering because if this is a case where glaze can be installed at the same time, we shouldn't be zapping this.

2024-01-22 18:45 UTC, maia-s commented on Casks/n/nightshade.rb
> +  zap trash: "~/.glaze"
Yes, they're often used together. Both this and glaze downloads several GB on first launch. They have a shared state so as to not download and store all of that twice.

I don't know what's the right thing to do here. Even if we remove the zap from this cask, if the zap of the glaze cask is executed it'll clear the state of nightshade.

2024-01-22 19:04 UTC, maia-s commented on Casks/n/nightshade.rb
> +  zap trash: "~/.glaze"
Is there a way for nightshade to skip zap if glaze is installed, and for glaze to skip zap if nightshade is installed?

2024-01-22 19:44 UTC, p-linnane commented on Casks/n/nightshade.rb
> +  zap trash: "~/.glaze"
I don't believe there is a good way for us to do this right now, but I think it's a good idea. Would you mind opening an issue in https://github.com/Homebrew/brew so people can take a look?

2024-01-22 19:44 UTC, p-linnane commented on Casks/n/nightshade.rb
> +  zap trash: "~/.glaze"
cc @Homebrew/cask

2024-01-22 20:03 UTC, bevanjkay commented on Casks/n/nightshade.rb
> +  zap trash: "~/.glaze"
It's currently expected behaviour of `zap` to sometimes remove preferences shared with other applications. Keep in mind zap is opt-in on uninstall.

2024-01-23 15:45 UTC, p-linnane commented on Casks/n/nightshade.rb
> +  zap trash: "~/.glaze"
Merging based off of the above.

2024-01-23 15:45 UTC, merged