ia-markdown-dictionary 1.0 (new cask)
Homebrew/homebrew-cask pull request #165470
Opened 2024-01-28 19:07 UTC by HuaDeity

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --cask --new <cask>` worked successfully.
- [x] `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

2024-01-29 01:42 UTC, bevanjkay commented
/rebase

2024-01-29 01:52 UTC, bevanjkay requested changes

2024-01-29 01:52 UTC, bevanjkay commented on Casks/i/ia-markdown-dictionary.rb
> +  end
We cannot use `extract_plist` here for `livecheck` because the download is already versioned. This strategy downloads the file and checks the contents, so when the `url` is versioned it will always return the same version as the current cask file.

Can you try to find another source for `livecheck`?

2024-01-29 02:02 UTC, bevanjkay commented
Please try to add a [zap stanza](https://docs.brew.sh/Cask-Cookbook#stanza-zap). The linked documentation provides some recommended methods to create it.

2024-01-29 06:46 UTC, HuaDeity commented
Hello, this is a dictionary for the macOS Dictionary.app. I was unable to locate any livecheck or zap options and do not think they are available.

2024-02-02 09:39 UTC, HuaDeity commented
I believe that, similar to [Emojipedia](https://raw.githubusercontent.com/Homebrew/homebrew-cask/master/Casks/e/emojipedia.rb), it is enough.

2024-02-02 16:35 UTC, bevanjkay commented
We would really like to see a livecheck here if at all possible. `emojipedia` is not a good example because it was added prior to `livecheck`'s existence.

2024-02-06 01:28 UTC, miccal approved these changes

2024-02-11 17:18 UTC, HuaDeity commented
I apologize, but I have searched thoroughly and could not find any available livecheck. However, you may visit the [download page](https://ia.net/tips/download#fcecdb10d0c1e54722) to see if there is anything that can be of help.

2024-02-12 00:47 UTC, samford reviewed
The download page asynchronously fetches the download URL by making a POST request to the site's WordPress API ( https://ia.net/wp-admin/admin-ajax.php?action=file_download&type=tips&code=fcecdb10d0c1e54722&file=markdown-dictionary). livecheck doesn't support POST requests (yet) and I don't see any alternative source of version information, so this appears to be uncheckable for now.

2024-02-12 02:42 UTC, HuaDeity commented
Thank you. Perhaps we could merge temporarily and check for any new version updates or available livecheck later on.

2024-02-12 08:48 UTC, SMillerDev commented on Casks/i/ia-markdown-dictionary.rb
> +  end
Is there absolutely no way to ever know if this was updated?

2024-02-12 08:59 UTC, HuaDeity commented on Casks/i/ia-markdown-dictionary.rb
> +  end
I'm sorry, I can't find any.

2024-02-14 17:24 UTC, bevanjkay approved these changes
Im really not a fan of casks that don't have a working livecheck, but it seems like in this case we will have to move ahead with manual version checking/updating.

2024-02-15 03:16 UTC, merged