Add Cask: mumu-player-pro (WIP)
Homebrew/homebrew-cask pull request #165471
Opened 2024-01-28 19:17 UTC by HuaDeity

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --cask --new <cask>` worked successfully.
- [ ] `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

Hi there, 

I am having trouble installing `<cask>` using the command `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --cask <cask>`. The error message I receive is "It seems the App source '/opt/homebrew/Caskroom/mumu-player-pro/1.2.142/MuMu模拟器Pro.app' is not there." I'm unsure why this is happening and would appreciate your assistance in resolving this issue.

2024-01-29 01:42 UTC, bevanjkay commented
/rebase

2024-01-29 01:55 UTC, bevanjkay requested changes

2024-01-29 01:55 UTC, bevanjkay commented on Casks/m/mumu-player-pro.rb
> +
There should be a way to find the latest version systematically.
Because we have `auto_updates true` the developer likely has an API or appcast available for finding the latest version (although sometimes these require authentication).

2024-01-29 07:48 UTC, HuaDeity commented
I added the livecheck stanza, but it still can't be installed through `brew install`.

2024-01-29 10:44 UTC, bevanjkay commented
@HuaDeity Try changing the `app` stanza to `app "MuMuPlayer.app"`

2024-01-29 11:07 UTC, HuaDeity commented
> @HuaDeity Try changing the `app` stanza to `app "MuMuPlayer.app"`

Thank you very much, this solves the problem.

2024-01-29 11:10 UTC, bevanjkay commented
@HuaDeity Sometimes the pathname in console is different to what is shown when opening the `.dmg`. This is one of those rare occasions.

2024-01-29 11:16 UTC, HuaDeity commented
> @HuaDeity Sometimes the pathname in console is different to what is shown when opening the `.dmg`. This is one of those rare occasions.

Thank you for informing me. Your response has been greatly beneficial.

2024-01-29 11:18 UTC, bevanjkay commented on Casks/m/mumu-player-pro.rb
> +  app "MuMuPlayer.app"
Now that the `app` stanza has changed, the `token` should be updated to just be `mumu-player` instead of `mumu-player-pro`. (filename also).

2024-01-29 11:34 UTC, HuaDeity commented
Great suggestion! I have updated the name of the cask.

2024-01-29 16:17 UTC, bevanjkay approved these changes

2024-01-31 22:17 UTC, samford reviewed
The `livecheck` block looks good to me but I'll leave final review of the overall cask to the cask maintainers.

2024-02-01 00:47 UTC, miccal approved these changes

2024-02-01 00:47 UTC, merged

2024-02-01 00:48 UTC, miccal commented
Thank you @HuaDeity.