hancom-office 12.30.0.5542 (new cask)
Homebrew/homebrew-cask pull request #165951
Opened 2024-02-03 15:43 UTC by leejongyoung

Created with `brew bump-cask-pr`.

2024-02-03 16:06 UTC, bevanjkay requested changes

2024-02-03 16:06 UTC, bevanjkay commented on Casks/h/hancom-office.rb
> +  sha256 :no_check
The `url` is versioned, so there should be a `sha256`.

2024-02-03 16:06 UTC, bevanjkay commented on Casks/h/hancom-office.rb
> +  end
Please try to find a working `livecheck`

2024-02-03 16:06 UTC, bevanjkay commented on Casks/h/hancom-office.rb
> +    "/private/var/db/receipts/com.hancom.office.hwp#{version.major}.mac.general.plist",
These items can be removed as they are temporary files.

2024-02-03 17:11 UTC, bevanjkay commented
Unfortunately we can't use the extract plist strategy here because it checks the contents of the downloaded files. So in this case it will always return the current cask version because the download is versioned.

2024-02-10 03:21 UTC, samford commented
Do you know of any public pages that list version information for this software? I don't see any version information, download links, etc. on https://office.hancom.com/. The only version information I saw when looking around was https://www.hancom.com/cs_center/csDownload.do and those versions don't correspond to the version used in the cask.

How did you find this pkg file?

2024-02-20 00:10 UTC, closed without merging