Add SideServer.app v1.0.6
Homebrew/homebrew-cask pull request #165909
Opened 2024-02-03 06:32 UTC by def324

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
  - With the exception of the following, with reasoning below:
    - Upstream defined :mojave as the minimum OS version and the cask defined :catalina
      - The [SideStore website](https://sidestore.io/) states MacOS 10.15 (Catalina) as the minimum version
    - GitHub fork (not canonical repository)
      - SideStore is a fork of AltStore (there is already a cask for it called altserver), however with significant improvements. Therefore it is valuable to have a separate cask for it.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --cask --new <cask>` worked successfully.
  - Exceptions listed above.
- [x] `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

2024-02-03 06:40 UTC, def324 commented
The tests failed due to the following reasons, as also described in the original pull request.

- Upstream defined :mojave as the minimum OS version and the cask defined :catalina
  - The [SideStore website](https://sidestore.io/) states MacOS 10.15 (Catalina) as the minimum version
- GitHub fork (not canonical repository)
  - SideStore is a fork of AltStore (there is already a cask for it called altserver), however with significant improvements. Therefore it is valuable to have a separate cask for it.

I would appreciate any feedback on how to best resolve these and I'll be happy to make the needed changes.

2024-02-03 10:36 UTC, bevanjkay requested changes
Regarding the fork audit, you can ask upstream to unfork the repository.

The minimum os audit checks the app's `info.plist` file, which supersedes whatever documentation is provided upstream.

2024-02-03 10:36 UTC, bevanjkay commented on Casks/s/sideserver.rb
> +
```suggestion
```
The `livecheck` block can be omitted, as the `git` strategy will be inferred from the `url`.

2024-02-03 10:36 UTC, bevanjkay commented on Casks/s/sideserver.rb
> +  url "https://github.com/SideStore/SideServer-macOS/releases/download/v1.0.6/SideServer.dmg",
```suggestion
  url "https://github.com/SideStore/SideServer-macOS/releases/download/v#{version}/SideServer.dmg",
```

2024-02-03 10:36 UTC, bevanjkay commented on Casks/s/sideserver.rb
> +  sha256 :no_check
The checksum will need to be added, as the `url` is versioned.

2024-02-16 19:10 UTC, def324 commented
I've asked upstream to unfork. I'll finish the cask once this has been done. Thanks for all your suggestions, I really appreciate them.

2024-03-17 00:12 UTC, closed without merging