youlean-loudness-meter 2.2.4 (new cask)
Homebrew/homebrew-cask pull request #166563
Opened 2024-02-12 22:06 UTC by rlpvin

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --cask --new <cask>` worked successfully.
- [x] `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

2024-02-14 04:10 UTC, razvanazamfirei requested changes

2024-02-14 04:10 UTC, razvanazamfirei commented on Casks/y/youlean-loudness-meter-2.rb
> +    regex(%r{href=.*?/Youlean-Loudness-Meter-2-V(\d+(?:\.\d+)+)-macOS.zip}i)
```suggestion
    regex(%r{href=.*?/(\w+)/(\w+)/youlean[_.-]loudness[_.-]meter-#{version.major}-v?(\d+(?:\.\d+)+)[_.-]macOS\.zip}i)
    strategy :page_match do |page, regex|
      page.scan(regex).map { |match| "#{match[2]},#{match[0]},#{match[1]}" }
    end
```

2024-02-14 04:10 UTC, razvanazamfirei commented on Casks/y/youlean-loudness-meter-2.rb
> +  zap trash: "~/Library/Application Support/Youlean/Youlean Loudness Meter 2/*"
```suggestion
  zap trash: "~/Library/Application Support/Youlean/Youlean Loudness Meter #{version.major}"
```

2024-02-14 04:10 UTC, razvanazamfirei commented on Casks/y/youlean-loudness-meter-2.rb
> +  zap trash: "~/Library/Application Support/Youlean/Youlean Loudness Meter 2/*"
Is this the only zap needed?

2024-02-14 04:10 UTC, razvanazamfirei commented on Casks/y/youlean-loudness-meter-2.rb
> +  url "https://cdn.youlean.co/wp-content/uploads/2023/03/Youlean-Loudness-Meter-2-V#{version}-macOS.zip"
```suggestion
  url "https://cdn.youlean.co/wp-content/uploads/#{version.csv.second}/#{version.csv.third}/Youlean-Loudness-Meter-#{version.major}-V#{version.csv.first}-macOS.zip"
```

2024-02-14 04:10 UTC, razvanazamfirei commented on Casks/y/youlean-loudness-meter-2.rb
> +  version "2.4.4"
```suggestion
  version "2.4.4,2023,03"
```

2024-02-15 00:17 UTC, razvanazamfirei commented on Casks/y/youlean-loudness-meter-2.rb
> +  version "2.4.4"
@rlpvin, no worries! I made the changes and committed them! Thanks so much for your first contribution!

2024-02-15 00:22 UTC, razvanazamfirei approved these changes

2024-02-15 08:16 UTC, bevanjkay requested changes, later dismissed

2024-02-15 08:16 UTC, bevanjkay commented on Casks/y/youlean-loudness-meter.rb
> +  depends_on macos: ">= :mavericks"
CI doesn't know mavericks anymore so this can and should be removed.

2024-02-15 13:16 UTC, krehel commented on Casks/y/youlean-loudness-meter.rb
> +    regex(%r{href=.*?/(\w+)/(\w+)/youlean[._-]loudness[._-]meter[._-]#{version.major}[._-]v?(\d+(?:\.\d+)+)[._-]macOS\.zip}i)
Won't this break when #{version.major} is incremented to 3 on the download site but the Cask will be at version 2?

2024-02-27 02:24 UTC, miccal approved these changes

2024-02-27 02:24 UTC, merged

2024-02-27 02:24 UTC, miccal commented
Thank you @rlpvin.