various: change spelling to international english
Homebrew/homebrew-cask pull request #166723
Opened 2024-02-14 12:19 UTC by razvanazamfirei

- [X] `brew style --fix <cask>` reports no offenses.

The PR changes descriptions to use British/Commonwealth/International English spelling variants.

List taken from [here](https://github.com/hyperreality/American-British-English-Translator).

2024-02-14 12:23 UTC, SMillerDev commented
Afaik our standard is British English.

Cc @MikeMcQuaid

2024-02-14 12:28 UTC, razvanazamfirei commented
@SMillerDev I used British and International interchangeably, but changes were made to use British/Commonwealth English spelling conventions.

2024-02-14 13:27 UTC, reitermarkus commented on Casks/c/camera-live.rb
> +  desc "Live Siphon Camera"
This is a bad description with either spelling. 😀

2024-02-14 13:29 UTC, reitermarkus commented on Casks/c/color-studio.rb
> +  desc "Coherent colourscheme creator"
```suggestion
  desc "Coherent colour scheme creator"
```

2024-02-14 13:29 UTC, reitermarkus commented on Casks/c/colorsnapper.rb
> +  desc "Colour picking application"
```suggestion
  desc "Colour picker"
```

2024-02-14 13:30 UTC, reitermarkus commented on Casks/c/crunch.rb
> +  desc "Insane(ly slow but wicked good) PNG image optimisation"
Too many marketing terms in this one.

2024-02-14 13:31 UTC, reitermarkus commented on Casks/c/crunch.rb
> +  desc "Insane(ly slow but wicked good) PNG image optimisation"
```suggestion
  desc "PNG image optimiser"
```

2024-02-14 13:31 UTC, reitermarkus commented on Casks/c/curio.rb
> +  desc "Note-taking and organising app"
```suggestion
  desc "Note-taking and organisation tool"
```

2024-02-14 13:34 UTC, reitermarkus commented on Casks/d/dcp-o-matic-batch-converter.rb
> +  desc "Convert video, audio and subtitles into DCP (Digital Cinema Democratised)"
```suggestion
  desc "Convert video, audio and subtitles into DCP (Digital Cinema Package)"
```

2024-02-14 13:35 UTC, reitermarkus commented on Casks/d/dcp-o-matic-combiner.rb
> +  desc "Convert video, audio and subtitles into DCP (Digital Cinema Democratised)"
```suggestion
  desc "Convert video, audio and subtitles into DCP (Digital Cinema Package)"
```

2024-02-14 13:35 UTC, reitermarkus commented on Casks/d/dcp-o-matic-disk-writer.rb
> +  desc "Convert video, audio and subtitles into DCP (Digital Cinema Democratised)"
```suggestion
  desc "Convert video, audio and subtitles into DCP (Digital Cinema Package)"
```

2024-02-14 13:35 UTC, reitermarkus commented on Casks/d/dcp-o-matic-editor.rb
> +  desc "Convert video, audio and subtitles into DCP (Digital Cinema Democratised)"
```suggestion
  desc "Convert video, audio and subtitles into DCP (Digital Cinema Package)"
```

2024-02-14 13:35 UTC, reitermarkus commented on Casks/d/dcp-o-matic-encode-server.rb
> +  desc "Convert video, audio and subtitles into DCP (Digital Cinema Democratised)"
```suggestion
  desc "Convert video, audio and subtitles into DCP (Digital Cinema Package)"
```

2024-02-14 13:36 UTC, reitermarkus commented on Casks/d/dcp-o-matic-kdm-creator.rb
> +  desc "Convert video, audio and subtitles into DCP (Digital Cinema Democratised)"
```suggestion
  desc "Convert video, audio and subtitles into DCP (Digital Cinema Package)"
```

2024-02-14 13:36 UTC, reitermarkus commented on Casks/d/dcp-o-matic-playlist-editor.rb
> +  desc "Convert video, audio and subtitles into DCP (Digital Cinema Democratised)"
```suggestion
  desc "Convert video, audio and subtitles into DCP (Digital Cinema Package)"
```

2024-02-14 13:36 UTC, reitermarkus commented on Casks/d/dcp-o-matic.rb
> +  desc "Convert video, audio and subtitles into DCP (Digital Cinema Democratised)"
```suggestion
  desc "Convert video, audio and subtitles into DCP (Digital Cinema Package)"
```

2024-02-14 13:39 UTC, reitermarkus commented on Casks/k/kigb.rb
> +  desc "Nintendo Game Boy/Game Boy Colour emulator"
```suggestion
  desc "Nintendo Game Boy/Game Boy Color emulator"
```

Product name.

2024-02-14 13:39 UTC, bevanjkay commented on Casks/c/camera-live.rb
> +  desc "Live Siphon Camera"
This may refer to "Syphon" the video transport protocol

2024-02-14 13:40 UTC, reitermarkus commented on Casks/s/sameboy.rb
> +  desc "Game Boy and Game Boy Colour emulator written in C"
```suggestion
  desc "Game Boy and Game Boy Color emulator written in C"
```

Product name.

2024-02-14 13:42 UTC, reitermarkus commented on Casks/s/spaceradar.rb
> +  desc "Disk And Memory Space Visualisation App built with Electron & d3.js"
```suggestion
  desc "Disk space and memory visualiser"
```

2024-02-14 13:44 UTC, reitermarkus commented on Casks/t/toshiba-color-mfp.rb
> +  desc "Drivers for Toshiba ColourMFP devices"
```suggestion
  desc "Drivers for Toshiba ColorMFP devices"
```

Product name.

2024-02-14 13:45 UTC, reitermarkus commented on Casks/v/visual-paradigm-ce.rb
> +  desc "All-in-one UML, SysML, BPMN Modelling Platform for Agile"
```suggestion
  desc "All-in-one UML, SysML, BPMN modelling platform"
```

2024-02-14 13:46 UTC, reitermarkus commented on Casks/v/visual-paradigm.rb
> +  desc "UML CASE Tool supporting UML 2, SysML and Business Process Modelling Notation"
```suggestion
  desc "UML, SysML, BPMN modelling platform"
```

2024-02-14 17:28 UTC, p-linnane commented
👍 with all of @reitermarkus's suggestions

2024-02-14 18:38 UTC, bevanjkay requested changes

2024-02-14 18:38 UTC, bevanjkay commented on Casks/c/camera-live.rb
> +  desc "Live Siphon Camera"
@razvanazamfirei this one needs to be left as "Syphon" because it refers to the protocol "Syphon".

2024-02-14 18:39 UTC, krehel commented on Casks/c/camera-live.rb
> +  desc "Live Siphon Camera"
Agreed.  Spelling of Syphon should not be changed, but desc could probably use an update.

Perhaps `Syphon server for connected Canon DSLR cameras`

Can drop the Canon DSLR portion - app readme states this is the only cameras that work so it may be a detail worth including.

2024-02-14 18:40 UTC, p-linnane commented on Casks/c/camera-live.rb
> +  desc "Live Siphon Camera"
:shipit:

2024-02-14 22:49 UTC, bevanjkay approved these changes

2024-02-15 00:32 UTC, p-linnane approved these changes

2024-02-15 02:21 UTC, krehel approved these changes

2024-02-15 03:16 UTC, merged