Add jamie 4.0.0 (new cask)
Homebrew/homebrew-cask pull request #166848
Opened 2024-02-15 22:22 UTC by antonengelhardt

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --cask --new <cask>` worked successfully.
   *GitHub repository not notable enough (<30 forks, <30 watchers and <75 stars)* : This is just a release repository as the source code is not public.
- [x] `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

2024-02-15 22:25 UTC, antonengelhardt commented
cc: @louismorgner

2024-02-16 15:39 UTC, bevanjkay requested changes

2024-02-16 15:39 UTC, bevanjkay commented on Casks/j/jamie.rb
> +  desc "Best AI-powered meeting notes. Across all tools. 15+ languages. Privacy-first"
Please update the zap to fit within the description guidelines - https://docs.brew.sh/Cask-Cookbook#stanza-desc

2024-02-16 15:39 UTC, bevanjkay commented on Casks/j/jamie.rb
> +    strategy :github_latest
Does the project use GitHub prereleases or have tags without releases? Otherwise the livecheck block should be omitted and the default (and preferred) `git` strategy will be inferred from the url.

2024-02-16 15:42 UTC, antonengelhardt commented on Casks/j/jamie.rb
> +  desc "Best AI-powered meeting notes. Across all tools. 15+ languages. Privacy-first"
What part of the description do you want changed? @bevanjkay

2024-02-16 15:42 UTC, antonengelhardt commented on Casks/j/jamie.rb
> +    strategy :github_latest
No, i will remove the livecheck block.

2024-02-16 15:45 UTC, bevanjkay commented on Casks/j/jamie.rb
> +  desc "Best AI-powered meeting notes. Across all tools. 15+ languages. Privacy-first"
If you read the docs you'll see that most of it needs to be removed. I would be okay with something like 

```suggestion
  desc "AI-powered meeting notes"
```

2024-02-16 15:55 UTC, antonengelhardt commented on Casks/j/jamie.rb
> +  desc "Best AI-powered meeting notes. Across all tools. 15+ languages. Privacy-first"
Done.

2024-02-16 15:58 UTC, bevanjkay approved these changes

2024-02-16 18:10 UTC, p-linnane approved these changes
Thanks!

2024-02-16 18:10 UTC, merged