Add Amnezia VPN client cask
Homebrew/homebrew-cask pull request #167034
Opened 2024-02-18 13:23 UTC by yslpn

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [ ] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask --online <cask>` is error-free.
- [ ] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --cask --new <cask>` worked successfully.
- [ ] `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

2024-02-18 22:05 UTC, bevanjkay requested changes
Thanks for contributing to `homebrew-cask` @yslpn - just one small change, otherwise looks good to me.

2024-02-18 22:05 UTC, bevanjkay commented on Casks/a/amnezia-client.rb
> +  desc "Amnezia is an open-source VPN client"
```suggestion
  desc "VPN client"
```

2024-02-19 06:46 UTC, yslpn commented on Casks/a/amnezia-client.rb
> +  desc "Amnezia is an open-source VPN client"
Okay, thank you)

2024-02-19 06:52 UTC, bevanjkay commented
@yslpn sorry for an additional change, but the token and file name for the cask should be `azeliavpn`

2024-02-19 06:54 UTC, yslpn commented
> @yslpn sorry for an additional change, but the token and file name for the cask should be `amneziavpn `

No problem) I'll rename

2024-02-19 07:05 UTC, bevanjkay approved these changes
Thank you @yslpn

2024-02-19 07:05 UTC, merged