update visual-studio-code cask
Homebrew/homebrew-cask pull request #167006
Opened 2024-02-17 16:37 UTC by gnought

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --cask --new <cask>` worked successfully.
- [ ] `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

2024-02-17 23:06 UTC, krehel commented
Hi @gnought - sorry but the only change that could be considered here is the minimum macOS requirement.  You can open a separate PR just for that change, or force push this PR for only that update.

2024-02-17 23:16 UTC, krehel requested changes

2024-02-17 23:16 UTC, krehel commented on Casks/v/visual-studio-code.rb
> +    end
We should keep the arch specific livecheck in case the versions diverge for some reason. 

That said, if the json strategy works, we can employ that over a regex.  Happy to consider this.

2024-02-17 23:16 UTC, krehel commented on Casks/v/visual-studio-code.rb
> +  url "https://update.code.visualstudio.com/#{version}/darwin-universal/stable"
This makes users download much more data. Architecture specific binaries should stay.

2024-02-17 23:16 UTC, krehel commented on Casks/v/visual-studio-code.rb
> +
This will cause the application to force quit on upgrade.  We had this before and reverted it.

2024-02-17 23:16 UTC, krehel commented on Casks/v/visual-studio-code.rb
> +  depends_on macos: ">= :catalina"
This should stay.  Thanks for finding this.

2024-02-17 23:16 UTC, krehel commented on Casks/v/visual-studio-code.rb
> +
```suggestion
```

Adding a suggestion so this isn't merged accidentally.

2024-02-18 01:34 UTC, bevanjkay commented on Casks/v/visual-studio-code.rb
> +
@krehel The logic has been changed so that `quit` doesn't run on upgrade/reinstall, only when specifically calling `uninstall`.

2024-02-18 01:39 UTC, krehel commented on Casks/v/visual-studio-code.rb
> +
Got it. Thanks @bevanjkay!

2024-02-20 15:11 UTC, krehel approved these changes

2024-02-20 15:11 UTC, merged