double-commander 1.1.10
Homebrew/homebrew-cask pull request #167023
Opened 2024-02-18 07:25 UTC by rich2014

double-commander 1.1.10 and livecheck updated.

2024-02-18 07:45 UTC, bevanjkay requested changes

2024-02-18 07:45 UTC, bevanjkay commented on Casks/d/double-commander.rb
>      strategy :page_match do |page, regex|
The whole strategy argument and block can be removed with this change

2024-02-19 00:25 UTC, rich2014 commented on Casks/d/double-commander.rb
>      strategy :page_match do |page, regex|
done, thx.

2024-02-19 01:36 UTC, samford commented on Casks/d/double-commander.rb
> +    regex(%r{url=["']?.*?/doublecmd[._-](\d+(?:\.\d+)+)[._-][^"']*?.dmg}i)
```suggestion
    regex(%r{url=.*?/doublecmd[._-](\d+(?:[.-]\d+)+)[^"' ]*?\.dmg}i)
    strategy :sourceforge do |page, regex|
      page.scan(regex).map { |match| match[0].tr("-", ",") }
    end
```

The newest two versions (1.1.9, 1.1.10) don't include a numeric suffix like the previous versions (e.g., 1.1.8-247) but versions as recent as 2023-12-16 include a numeric suffix. The current regex in this PR would omit any numeric suffix from the from the version and it would return a version like 1.1.8 even if the full version in the filename is 1.1.8-247, which would make this harder to version bump.

There's something to be said for supporting both formats in the `livecheck` block, so it will surface versions like 1.1.10 and 1.1.8-247.

2024-02-19 01:36 UTC, samford commented on Casks/d/double-commander.rb
> +  url "https://downloads.sourceforge.net/doublecmd/doublecmd-#{version}.cocoa.#{arch}.dmg",
```suggestion
  url "https://downloads.sourceforge.net/doublecmd/doublecmd-#{version.tr(",", "-")}.cocoa.#{arch}.dmg",
```

As with the `livecheck` block, this approach would readily support both versions like 1.1.10 and 1.1.8-247.

That said, I'm not sure if this is the preferred way of handling this within homebrew/cask compared to something like `https://downloads.sourceforge.net/doublecmd/doublecmd-#{version.csv.first}#{"-#{version.csv.second}" if version.csv.second}.cocoa.#{arch}.dmg`. The `#tr` approach is a bit cleaner but I'll defer to the cask maintainers on this particular change.

2024-02-19 05:03 UTC, rich2014 commented on Casks/d/double-commander.rb
> +    regex(%r{url=["']?.*?/doublecmd[._-](\d+(?:\.\d+)+)[._-][^"']*?.dmg}i)
done, thx

2024-02-24 13:14 UTC, rich2014 commented
@bevanjkay , could you please check the PR？

2024-02-25 08:34 UTC, bevanjkay approved these changes

2024-02-25 08:34 UTC, merged