Add Motion
Homebrew/homebrew-cask pull request #167112
Opened 2024-02-19 21:55 UTC by nihaals

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --cask --new <cask>` worked successfully.
- [x] `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

2024-02-19 21:57 UTC, nihaals commented
I thought `:github_releases` already checked for the release marked latest but it seems it's picking up on the release created later instead. I tried searching the repo for examples but all the examples I could find were for skipping pre-releases so I'm not sure what the neatest way of finding the release is. See [the release](https://github.com/usemotion/desktopapp/releases/tag/v0.99.0) for more context.

2024-02-20 03:10 UTC, bevanjkay requested changes

2024-02-20 03:10 UTC, bevanjkay commented on Casks/m/motion.rb
> +    strategy :github_releases
```suggestion
    strategy :github_latest
```

2024-02-20 05:10 UTC, reitermarkus requested changes, later dismissed

2024-02-20 05:10 UTC, reitermarkus commented on Casks/m/motion.rb
> +    "~/Library/HTTPStorages/com.electron.motion*",
```suggestion
    "~/Library/HTTPStorages/com.electron.motion",
```

2024-02-20 05:19 UTC, nihaals commented on Casks/m/motion.rb
> +    "~/Library/HTTPStorages/com.electron.motion*",
Both `~/Library/HTTPStorages/com.electron.motion` and `~/Library/HTTPStorages/com.electron.motion.binarycookies` exist

2024-02-20 10:48 UTC, SMillerDev commented
> I thought :github_releases already checked for [the release](https://github.com/usemotion/desktopapp/releases/tag/v0.99.0) marked latest but it seems it's picking up on the release created later instead. I tried searching the repo for examples but all the examples I could find were for skipping pre-releases so I'm not sure what the neatest way of finding the release is. See the release for more context.

That's `:github_latest`, releases just checks for the most recent release.

2024-02-20 22:50 UTC, miccal commented
/rebase

2024-02-25 08:46 UTC, bevanjkay approved these changes

2024-02-25 08:47 UTC, bevanjkay commented
Thank you @nihaals

2024-02-27 02:21 UTC, miccal approved these changes

2024-02-27 02:21 UTC, merged