webex: Update zap
Homebrew/homebrew-cask pull request #167520
Opened 2024-02-24 07:09 UTC by muneebmahmed

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --cask --new <cask>` worked successfully.
- [ ] `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

----------------
Updating the zap stanza for `webex` with some more directories found by AppCleaner and on my machine

2024-02-24 07:22 UTC, bevanjkay requested changes

2024-02-24 07:22 UTC, bevanjkay commented on Casks/w/webex.rb
> +    "~/Library/Logs/Webex Meetings",
Isn't Webex Meetings a different application?

2024-02-24 08:03 UTC, muneebmahmed commented on Casks/w/webex.rb
> +    "~/Library/Logs/Webex Meetings",
Nope, I tested this by zapping and reinstalling the `webex` cask, and joining a test meeting. Not only did it recreate the `Webex Meetings` directories, but I was also able to locate the "Cisco Webex Meetings" app in Finder under the directory `~/Library/Application\ Support/WebEx\ Folder/T33_64UMC_44.2.0.76/Meeting\ Center.app`. While doing this, I also happened to find even more files to add under various `com.cisco.webex*` directories.

2024-02-25 08:40 UTC, bevanjkay approved these changes

2024-02-25 08:40 UTC, merged

2024-02-25 08:40 UTC, bevanjkay commented
Thank you @muneebmahmed