feat: Change cinc-workstation URL to HTTPS
Homebrew/homebrew-cask pull request #168049
Opened 2024-03-02 08:10 UTC by aleksandrs-ledovskis

Change "cinc-workstation" cask to use HTTPS location.

---

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

---

2024-03-02 13:26 UTC, razvanazamfirei requested changes

2024-03-02 13:26 UTC, razvanazamfirei commented on Casks/c/cinc-workstation.rb
>    desc "Free-as-in-Beer all-in-one installer for Chef infrastructure management tools"
```suggestion
  desc "Installer for Chef infrastructure management tools"
```

2024-03-02 14:15 UTC, aleksandrs-ledovskis commented on Casks/c/cinc-workstation.rb
>    desc "Free-as-in-Beer all-in-one installer for Chef infrastructure management tools"
@razvanazamfirei Is your suggestion mandatory?

I wouldn't like changing/extending the scope of this PR buy making any additional changes other than URL.

Also the "Free-as-in-Beer" is exactly how the project describes itself (check https://cinc.sh/).

2024-03-02 17:45 UTC, p-linnane commented on Casks/c/cinc-workstation.rb
>    desc "Free-as-in-Beer all-in-one installer for Chef infrastructure management tools"
Yes, we need to make these changes. Per the [Cask Cookbook](https://docs.brew.sh/Cask-Cookbook#stanza-desc):
>desc is not for app slogans! Vendors’ descriptions tend to be filled with generic adjectives such as “modern” and “lightweight”. Those are meaningless marketing fluff (do you ever see apps proudly describing themselves as outdated and bulky?) which must be deleted. It’s fine to use the information on the software’s website as a starting point, but it will require editing in almost all cases.

2024-03-02 19:34 UTC, aleksandrs-ledovskis commented on Casks/c/cinc-workstation.rb
>    desc "Free-as-in-Beer all-in-one installer for Chef infrastructure management tools"
Ok, changed per your request. Though IMO `desc` clarification should have been done in original [PR](https://github.com/Homebrew/homebrew-cask/pull/107860) or any subsequent cask change 🤷

2024-03-03 06:18 UTC, razvanazamfirei commented on Casks/c/cinc-workstation.rb
>    desc "Free-as-in-Beer all-in-one installer for Chef infrastructure management tools"
Thank you for working with us, @aleksandrs-ledovskis! We address issues like this when they are noticed, as was the case with this PR! We're always very appreciative when people contribute and improve our project--thank you! ❤️

2024-03-03 06:18 UTC, razvanazamfirei approved these changes

2024-03-03 06:18 UTC, merged