jan 0.4.7 (new cask)
Homebrew/homebrew-cask pull request #168215
Opened 2024-03-04 20:40 UTC by chenrui333

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --cask --new <cask>` worked successfully.
- [x] `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

---

2024-03-04 20:58 UTC, bevanjkay requested changes

2024-03-04 20:58 UTC, bevanjkay commented on Casks/j/jan.rb
> +  desc "Open source alternative to ChatGPT that runs 100% offline on your computer"
Should succinctly describe what this actually does

2024-03-04 21:22 UTC, chenrui333 commented on Casks/j/jan.rb
> +  desc "Open source alternative to ChatGPT that runs 100% offline on your computer"
that is actually on the project site. What do you prefer?

2024-03-04 21:23 UTC, chenrui333 commented on Casks/j/jan.rb
> +  desc "Open source alternative to ChatGPT that runs 100% offline on your computer"
also on the homepage as well

<img width="632" alt="image" src="https://github.com/Homebrew/homebrew-cask/assets/1580956/da84ec0d-a23f-4a00-b7bf-c06653b6619a">

2024-03-04 21:35 UTC, chenrui333 commented on Casks/j/jan.rb
> +  desc "Open source alternative to ChatGPT that runs 100% offline on your computer"
@bevanjkay I wonder if we can just call it another `local LLM chat tool`?

2024-03-04 22:29 UTC, bevanjkay commented on Casks/j/jan.rb
> +  desc "Open source alternative to ChatGPT that runs 100% offline on your computer"
`Offline AI chat tool` ?

2024-03-05 04:11 UTC, chenrui333 commented on Casks/j/jan.rb
> +  desc "Open source alternative to ChatGPT that runs 100% offline on your computer"
Works for me.

2024-03-05 04:17 UTC, bevanjkay commented on Casks/j/jan.rb
> +  end
@chenrui333 Is there a reason for using `github_latest`?

2024-03-05 04:29 UTC, chenrui333 commented on Casks/j/jan.rb
> +  end
I did not find any good appcast to do the livecheck, so just go ahead of using github latest release, any concerns?

2024-03-05 04:45 UTC, bevanjkay commented on Casks/j/jan.rb
> +  end
When the `url` points to GitHub `livecheck` automatically uses the `:git` strategy which is preferred because it doesn't use the API.
So it's like the `livecheck` block can be removed entirely here.

2024-03-05 05:08 UTC, chenrui333 commented on Casks/j/jan.rb
> +  end
it works for me?

```
$ brew livecheck --debug jan
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::NullLoader): loading jan
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromDefaultNameLoader): loading jan

Cask:             jan
Livecheckable?:   Yes

URL (url):        https://github.com/janhq/jan/releases/download/v0.4.7/jan-mac-arm64-0.4.7.dmg
Strategy:         GithubLatest
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.2.11-21-gcf7c093\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 14.2.1\)\ curl/8.4.0 --header Accept-Language:\ en --retry 3 --location https://api.github.com/repos/janhq/jan/releases/latest --header Accept:\ application/vnd.github+json --write-out '
'\%\{http_code\} --header Authorization:\ token\ ****** --header X-GitHub-Api-Version:2022-11-28 --dump-header /private/tmp/github_api_headers20240305-46647-4tesa4
URL (strategy):   https://api.github.com/repos/janhq/jan/releases/latest
Regex (strategy): /v?(\d+(?:\.\d+)+)/i

Matched Versions:
0.4.7

jan: 0.4.7 ==> 0.4.7
```

2024-03-05 05:09 UTC, chenrui333 commented on Casks/j/jan.rb
> +  end
this is the one with the default livecheck

```
$ brew livecheck --debug jan
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::NullLoader): loading jan
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromDefaultNameLoader): loading jan

Cask:             jan
Livecheckable?:   No

URL:              https://github.com/janhq/jan/releases/download/v0.4.7/jan-mac-arm64-0.4.7.dmg
URL (processed):  https://github.com/janhq/jan.git
Strategy:         Git

Matched Versions:
0.1.1, 0.1.2, 0.1.3, 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.3.0, 0.3.1, 0.3.2, 0.3.3, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.4.4, 0.4.5, 0.4.6, 0.4.7, 0.5.0

jan: 0.4.7 ==> 0.5.0
```

2024-03-05 05:51 UTC, bevanjkay approved these changes

2024-03-05 05:51 UTC, merged