sonarr: update version, url and livecheck
Homebrew/homebrew-cask pull request #168632
Opened 2024-03-09 00:33 UTC by raikesy

Sonarr download url format changed with latest update and so this should bring it up to date, updating livecheck accordingly. Also adds postflight for the manual signing steps required to run sonarr after installation.

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --cask --new <cask>` worked successfully.
- [ ] `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

---

2024-03-09 02:30 UTC, bevanjkay requested changes, later dismissed

2024-03-09 02:30 UTC, bevanjkay commented on Casks/s/sonarr.rb
> +                   args: ["-rd", "com.apple.quarantine", "/Applications/Sonarr.app"]
We do not allow the systematic removal of quarantine attributes.
This is a security feature that we should not be automatically circumventing for users.

2024-03-09 15:36 UTC, raikesy commented on Casks/s/sonarr.rb
> +                   args: ["-rd", "com.apple.quarantine", "/Applications/Sonarr.app"]
Very reasonable. I have removed the offending lines and replaced them with a caveat that the user can choose to follow manually.

2024-03-10 13:31 UTC, razvanazamfirei commented
Thank you for opening this, @raikesy!

Sorry to rehash this, but see https://github.com/Homebrew/homebrew-cask/pull/160619. I think the language of the caveat should not instruct users on how to remove the quarantine attributes.

2024-03-10 13:46 UTC, raikesy commented
> Thank you for opening this, @raikesy!
> 
> Sorry to rehash this, but see #160619. I think the language of the caveat should not instruct users on how to remove the quarantine attributes.

I completely see your point, but the fact is (as far as I know) the app will not run unless those commands are executed, so removing all reference to them will leave us with a cask that installs a non-functional app, which seems to be a very poor UX and surely can’t be the right answer. 

What about replacing the caveat text with a hyperlink to the [official installation guidance page](https://wiki.servarr.com/sonarr/installation/macos) that contains the commands in their full context?

If there’s no appetite to point users to remove quarantine attributes I completely understand but then does it still make sense to include apps in homebrew-cask that require this in order to run?

2024-03-10 15:57 UTC, krehel commented
Appreciate the fair responses here @raikesy on what has been an off and on discussion over the last few years regarding this Cask.  There isn't an appetite to remove quarantine attributes or to advise doing so.

Some history below also -

https://github.com/orgs/Homebrew/discussions/3088#discussioncomment-7623916
https://github.com/Homebrew/homebrew-cask/pull/160619

Upstream signing the binaries is the correct course to address this issue.  Upstream have mentioned previously they don't want to do so and that is a choice they are free to make.

2024-03-10 16:07 UTC, raikesy commented
@krehel Ah that’s my fault for not checking for previous discussions thoroughly enough - thanks for providing that link. I’ll amend shortly.

2024-03-11 10:55 UTC, bevanjkay commented on Casks/s/sonarr.rb
> +  url "https://services.sonarr.tv/v1/download/main/latest?version=#{version.major}&os=macos&arch=#{arch}&installer=true"
Is there a reason for changing the `url`?
This will stop working whenever this is an update, because the checksum will begin to mismatch.

2024-03-11 15:46 UTC, raikesy commented on Casks/s/sonarr.rb
> +  url "https://services.sonarr.tv/v1/download/main/latest?version=#{version.major}&os=macos&arch=#{arch}&installer=true"
Yes. The reason is that Sonarr have changed the url they serve their latest version from. I probably should have changed sha256 to :no_check since their new url is not versioned.

Having said that I now think it might be better to follow the lead of the other *arrs and just download versioned from github. I'll amend it shortly.

2024-03-12 13:44 UTC, krehel commented on Casks/s/sonarr.rb
> +  url "https://services.sonarr.tv/v1/download/main/latest?version=#{version.major}&os=macos&arch=#{arch}&installer=true"
Thanks @raikesy - agree this is probably the nest option

2024-03-12 13:45 UTC, krehel commented
I think I'm ok with these updates.  If anything, it reduces complexity imho.

2024-03-13 03:17 UTC, bevanjkay commented
We have previously used the GitHub releases but changed it because some releases weren't available on the repo.
Maybe this has changed in 3 years, so we can give it a go.
https://github.com/Homebrew/homebrew-cask/pull/107522

2024-03-13 04:21 UTC, miccal commented
Thank you @raikesy.

2024-03-13 04:21 UTC, miccal approved these changes

2024-03-13 04:21 UTC, merged