jprofiler 14.0.2
Homebrew/homebrew-cask pull request #168826
Opened 2024-03-12 11:40 UTC by adithyasunil26

Created with `brew bump-cask-pr`.

2024-03-12 13:33 UTC, chenrui333 approved these changes

2024-03-13 00:12 UTC, razvanazamfirei commented on Casks/j/jprofiler.rb
> +  zap trash: [
Any reason not to use `#{version.major}` here instead?

2024-03-13 00:13 UTC, razvanazamfirei requested changes, later dismissed

2024-03-13 00:13 UTC, razvanazamfirei commented on Casks/j/jprofiler.rb
> +    "~/Library/Preferences/jprofiler.vmoptions",
```suggestion
    "~/.jprofiler#{version.major}",
    "~/Library/Preferences/com.jprofiler.history.plist",
    "~/Library/Preferences/com.jprofiler.v#{version.major}.plist",
    "~/Library/Preferences/jprofiler.vmoptions",
```

2024-03-13 00:13 UTC, bevanjkay commented on Casks/j/jprofiler.rb
> +  zap trash: [
I'm usually more in favour of using a glob `*` in these scenarios.

2024-03-13 00:28 UTC, razvanazamfirei approved these changes

2024-03-13 03:15 UTC, chenrui333 approved these changes

2024-03-13 03:15 UTC, merged