Add quickapp-ide 6.6.1 (new cask)
Homebrew/homebrew-cask pull request #169191
Opened 2024-03-15 15:33 UTC by GaoJuqian

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --cask --new <cask>` worked successfully.
- [x] `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

---

2024-03-15 16:05 UTC, chenrui333 commented
@GaoJuqian can you amend your commit msg as `quickapp-ide 6.6.1 (new cask)`

2024-03-17 07:00 UTC, bevanjkay requested changes

2024-03-17 07:00 UTC, bevanjkay commented on Casks/q/quickapp-ide.rb
> +  end
We need a different `livecheck`. This will always return the same version as the caskfile, because its a versioned download, and the `extract_plist` strategy checks the downloaded files' `info.plist`

2024-03-18 03:55 UTC, GaoJuqian commented on Casks/q/quickapp-ide.rb
> +  end
I modified it and run 'brew bump'.
```
==> quickapp-ide is up to date!
Current cask version:     6.6.1
Latest livecheck version: 6.6.1
Latest Repology version:  present only in Homebrew

```

2024-03-18 14:02 UTC, krehel commented
Let's get a livecheck from upstream somewhere.  Placing a 3rd party artifact into a personal GitHub repository probably isn't an appropriate solution.

2024-03-19 02:20 UTC, GaoJuqian commented
I got it. I changed it to this.
```
 homebrew-cask % brew livecheck --debug quickapp-ide
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::NullLoader): loading quickapp-ide
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromNameLoader): loading quickapp-ide

Cask:             quickapp-ide
Livecheckable?:   Yes

URL:              https://www.quickapp.cn/api/ide/rpk/getPackage
Strategy:         PageMatch
Regex:            /quickapp-ide-(\d+(?:\.\d+)*)\.pkg/i

Matched Versions:
6.6.1

quickapp-ide: 6.6.0 ==> 6.6.1
```

2024-03-19 02:23 UTC, bevanjkay requested changes

2024-03-19 02:23 UTC, bevanjkay commented on Casks/q/quickapp-ide.rb
> +    strategy :page_match
```suggestion
```

The `strategy` can be removed as `page_match` is the default.

2024-03-19 02:23 UTC, bevanjkay commented on Casks/q/quickapp-ide.rb
> +    regex(/quickapp-ide-(\d+(?:\.\d+)*)\.pkg/i)
```suggestion
    regex(/quickapp[._-]ide[._-]v?(\d+(?:\.\d+)+)\.pkg/i)
```
Minor regex tweaks to align with prevailing standards.

2024-03-19 02:24 UTC, bevanjkay commented
Can you also confirm whether the name of the `.app` file that is installed is "quickapp-ide" or just "quickapp"?

2024-03-19 02:37 UTC, GaoJuqian commented
The pkg files of download pages in version history are all "quickapp-ide". The name of the app after installation is "快应用开发工具.app"

2024-04-07 08:23 UTC, bevanjkay commented on Casks/q/quickapp-ide.rb
> +
Is this required, shouldn't this be handled by the pkg installer?

2024-04-26 00:04 UTC, closed without merging

2024-05-20 15:45 UTC, GaoJuqian commented on Casks/q/quickapp-ide.rb
> +
Yes, I deleted it.