Update tuxguitar to 1.6.1 and change source repository
Homebrew/homebrew-cask pull request #169109
Opened 2024-03-14 21:49 UTC by G-eos

A new team take the lead to maintain tuxguitar which was orphan since a long time.

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

Sorry I was unable to do it with brew command. I edit the file by hand in GitHub web interface ... :-( and submit a patched version. sha256 has been computed using shasum -a 256 ...
If you can share a pointer to perform the test I would love.
I try  brew bump-cask-pr  which fails with Error: This cask's tap is not a Git repository!

After making any changes to a cask, existing or new, verify:

- [X] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask --online <cask>` is error-free.
- [ ] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --cask --new <cask>` worked successfully.
- [ ] `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

---

2024-03-14 23:33 UTC, daeho-ro commented on Casks/t/tuxguitar.rb
> +  url "https://github.com/helge17/tuxguitar/releases/download/#{version}/tuxguitar-#{version}-macosx-swt-cocoa-x86_64.app.tar.gz"
```suggestion
  url "https://github.com/helge17/tuxguitar/releases/download/#{version}/tuxguitar-#{version}-macosx-swt-cocoa-x86_64.app.tar.gz"
      verified: "github.com/helge17/tuxguitar/"
```

2024-03-14 23:34 UTC, daeho-ro commented on Casks/t/tuxguitar.rb
> +  url "https://github.com/helge17/tuxguitar/releases/download/#{version}/tuxguitar-#{version}-macosx-swt-cocoa-x86_64.app.tar.gz"
And you can easily add the livecheck stanza when you use github repository, so please consider to add it.

2024-03-15 00:23 UTC, razvanazamfirei commented
It seems like we're in the situation described [here](https://docs.brew.sh/Acceptable-Casks#forks-and-apps-with-conflicting-names). Can you give us more detail on the maintainer switch?

2024-03-15 00:25 UTC, razvanazamfirei commented on Casks/t/tuxguitar.rb
> +  url "https://github.com/helge17/tuxguitar/releases/download/#{version}/tuxguitar-#{version}-macosx-swt-cocoa-x86_64.app.tar.gz"
@daeho-ro, thank you for the review. There's no need for a livecheck stanza when using github, unless we need to restrict ourselves to tags explicitly marked as "latest". Otherwise, this is implied by default:
```ruby
livecheck do
	url :url
	strategy :git
end
```

2024-03-15 00:26 UTC, razvanazamfirei requested changes

2024-03-15 00:26 UTC, razvanazamfirei commented on Casks/t/tuxguitar.rb
> +  url "https://github.com/helge17/tuxguitar/releases/download/#{version}/tuxguitar-#{version}-macosx-swt-cocoa-x86_64.app.tar.gz"
See my previous comment regarding information on the new maintainers.

2024-03-15 00:27 UTC, razvanazamfirei commented on Casks/t/tuxguitar.rb
> +  url "https://github.com/helge17/tuxguitar/releases/download/#{version}/tuxguitar-#{version}-macosx-swt-cocoa-x86_64.app.tar.gz"
Also, please try to add a [zap stanza](https://docs.brew.sh/Cask-Cookbook#stanza-zap) for this cask.

2024-03-15 06:35 UTC, G-eos commented
> It seems like we're in the situation described [here](https://docs.brew.sh/Acceptable-Casks#forks-and-apps-with-conflicting-names). Can you give us more detail on the maintainer switch?


TuxGuitar was written by Julián Gabriel Casadesús and maintained by him for a very long time. At the end of 2022, the former TuxGuitar websites disappeared and the development in the SourceForge repository stalled. After unsuccessful attempts to contact Julián, some TuxGuitar enthusiasts initiated a new TuxGuitar repository on Github.

The original maintainer seems to stop its works. This new development continue the work. This is why I think it shall replace without a new name. Please tell us what you think is the good direction to take.

2024-03-15 08:45 UTC, SMillerDev commented
I'd say it should get a new name then, since it is not related to the original project. We can deprecate the old one and refer here though.

2024-03-15 11:03 UTC, G-eos commented
So let proceed, how can I contribute ?

2024-03-15 18:25 UTC, guiv42 commented
Just for information: the question of a new name was already identified in the upstream repo.
It is now [explicitly open](https://github.com/helge17/tuxguitar/discussions/286).

2024-03-15 23:01 UTC, p-linnane requested changes
At a minimum, the `tuxguitar` cask should be deprecated and a new cask called `tuxguitar-helge17` should be created using the fork.

2024-03-18 21:02 UTC, closed without merging