Fix/foldit url details
Homebrew/homebrew-cask pull request #169276
Opened 2024-03-17 18:35 UTC by jhed9

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --cask --new <cask>` worked successfully.
- [x] `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

---
The existing cask installs an old version of Foldit. The URL needs to be updated.

I also fixed the livecheck, added a little to the description, and added the auto_updates tag.

2024-03-19 11:51 UTC, bevanjkay commented on Casks/f/foldit.rb
> +  auto_updates true
Does this actually update to the latest version, or just update some of the contents of the application? it seems to update some internal files, but not the whole application.

2024-03-20 01:36 UTC, jhed9 commented on Casks/f/foldit.rb
> +  auto_updates true
You are correct, it doesn't replace the whole app bundle, it only modifies/adds files inside of the app bundle when an update comes out. It is kind of unusual in that way. Nonetheless, after it updates the files inside the bundle, the app reports the new version as installed. It also does the updates automatically when they are released.

2024-03-20 01:38 UTC, bevanjkay requested changes

2024-03-20 01:38 UTC, bevanjkay commented on Casks/f/foldit.rb
> +    end
```suggestion
```

The strategy block can be removed, as this is the default behaviour.

2024-03-20 01:45 UTC, razvanazamfirei commented on Casks/f/foldit.rb
> +  desc "Crowdsourcing, protein folding computer game"
```suggestion
  desc "Protein folding computer game"
```

2024-03-20 01:46 UTC, razvanazamfirei approved these changes

2024-03-20 01:56 UTC, bevanjkay approved these changes

2024-03-20 01:56 UTC, merged

2024-03-20 01:56 UTC, bevanjkay commented
Thank you @jhed9