initial commit zc 0.14.0
Homebrew/homebrew-cask pull request #169269
Opened 2024-03-17 15:39 UTC by zectdev

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [X] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [X] `brew audit --cask --online <cask>` is error-free.
- [X] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [X] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [X] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [X] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [X] `brew audit --cask --new <cask>` worked successfully.
- [X] `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --cask <cask>` worked successfully.
- [X] `brew uninstall --cask <cask>` worked successfully.

---

2024-03-17 23:30 UTC, daeho-ro commented
It seems that the binary should go to the homebrew core first.

2024-03-18 00:02 UTC, bevanjkay commented
If the binary is built from a closed-source then `homebrew-cask` is the appropriate place for this to be submitted.

Aside to this, I am not convinced that the app carries enough notability to be included at this stage. Self-submission (by the vendor) is often an initial sign that there is not demand for the cask to be included in `homebrew-cask`. Additionally, a lack of SSL certificate on the homepage and download links points to the project not having a required level of maturity to be included as is.

It may be better to begin by offering this in  your [own tap](https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap).

2024-03-18 01:38 UTC, zectdev commented
This is indeed built closed-source.  We use a wildcard SSL cert https://releases.zectonal.com/ and https://www.zectonal.com/

2024-03-18 01:40 UTC, bevanjkay commented
Why not use those links in the cask file?

2024-03-18 01:43 UTC, zectdev commented
I didn't think of it since this is the first attempt, but I could easily do that...what is the process to handle this PR if I go back and use an HTTPS URL?  Should I resubmit a new PR?

2024-03-18 01:44 UTC, bevanjkay commented
You can push additional commits to this PR. We don't currently require commits to be squashed in `homebrew-cask` either.

2024-03-18 01:47 UTC, zectdev commented
Great news...I will update and push the new commits to this PR - thank you for the feedback.

2024-03-18 02:39 UTC, zectdev commented
I updated with https that uses our SSL cert

2024-03-19 11:50 UTC, bevanjkay requested changes

2024-03-19 11:50 UTC, bevanjkay commented on Casks/z/zc.rb
>      strategy :page_match
```suggestion
```
The `strategy` can be removed as `page_match` is the default.

2024-03-19 11:50 UTC, bevanjkay commented on Casks/z/zc.rb
> +    regex(/href=.*v(\d+(?:\.\d+)*).*/i)
```suggestion
    regex(%r{href=.*?download/v?(\d+(?:\.\d+)+)/index.html}i)
```

2024-03-19 12:16 UTC, zectdev commented on Casks/z/zc.rb
> +    regex(/href=.*v(\d+(?:\.\d+)*).*/i)
thank you for this feedback.  I incorporated into the latest commit below.

2024-03-24 02:53 UTC, razvanazamfirei commented
If no zap is needed for this cask, we should add `  # No zap stanza required`. 

Regardless, I agree with @bevanjkay that this does not meet our notability [requirements](https://docs.brew.sh/Acceptable-Casks#rejected-casks). 


Thank you for the PR, @zectdev and we really appreciate your contribution! Unfortunately, we're going to pass on this for now.

2024-03-24 02:53 UTC, closed without merging