add dbeaver-community binary from the app
Homebrew/homebrew-cask pull request #169367
Opened 2024-03-19 02:48 UTC by daeho-ro

Requested from https://github.com/orgs/Homebrew/discussions/5188.

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [v] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [v] `brew audit --cask --online <cask>` is error-free.
- [v] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --cask --new <cask>` worked successfully.
- [ ] `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

---

2024-03-19 11:45 UTC, bevanjkay requested changes

2024-03-19 11:45 UTC, bevanjkay commented on Casks/d/dbeaver-community.rb
> +  binary "#{appdir}/DBeaver.app/Contents/MacOS/dbeaver", target: "dbeaver-ce"
Why rename the binary?

2024-03-19 11:54 UTC, daeho-ro commented on Casks/d/dbeaver-community.rb
> +  binary "#{appdir}/DBeaver.app/Contents/MacOS/dbeaver", target: "dbeaver-ce"
The enterprise edition and the others can be installed at the same time and if I add the binary them later, then the binary name will be same which can cause the conflict and so I changed. Do you think is that safe to remain the original?

2024-03-19 11:56 UTC, bevanjkay commented on Casks/d/dbeaver-community.rb
> +  binary "#{appdir}/DBeaver.app/Contents/MacOS/dbeaver", target: "dbeaver-ce"
Is the binary inside of those also called `dbeaver`? As the app names themselves differ (or they would already be set to conflict).

2024-03-19 12:05 UTC, daeho-ro commented on Casks/d/dbeaver-community.rb
> +  binary "#{appdir}/DBeaver.app/Contents/MacOS/dbeaver", target: "dbeaver-ce"
I have downloaded `dbeaver-enterprise` and found the binary with name `dbeaver`. Since I have the community version already, I can install both and so the binary could be conflict.

2024-03-20 05:00 UTC, daeho-ro commented on Casks/d/dbeaver-community.rb
> +  binary "#{appdir}/DBeaver.app/Contents/MacOS/dbeaver", target: "dbeaver-ce"
Maybe, it is better to keep the binary for this community edition because of the app name is DBeaver.app. The app name for the enterprise edition is DBeaverEE.app and so I might add the enterprise binary with the name `dbeaver-ee` later. Any suggestions?

2024-03-20 19:18 UTC, reitermarkus commented on Casks/d/dbeaver-community.rb
> +  binary "#{appdir}/DBeaver.app/Contents/MacOS/dbeaver", target: "dbeaver-ce"
Why would someone install the community edition and enterprise edition at the same time? Is there any benefit to using the community edition if you also have the enterprise edition?

Seems like `conflicts_with` would be the best option if there isn't one.

2024-03-21 02:16 UTC, daeho-ro commented on Casks/d/dbeaver-community.rb
> +  binary "#{appdir}/DBeaver.app/Contents/MacOS/dbeaver", target: "dbeaver-ce"
I don't know why they allow this, but they actually not conflict in the package level.
https://github.com/dbeaver/dbeaver/issues/2856
So, I planned to do it as binary, too.

Anyway, I will not going to add the `conflicts_with` in this time, because I did't add the binary for the enterprise edition (ee) yet. We can discuss more on later when I or someone add the binary for the ee.

2024-03-21 02:17 UTC, daeho-ro commented on Casks/d/dbeaver-community.rb
> +  binary "#{appdir}/DBeaver.app/Contents/MacOS/dbeaver", target: "dbeaver-ce"
I'v changed the binary as the original, `dbeaver` and so this may resolve the conversation. If you need more discussion, please tell me again :)

2024-03-21 02:20 UTC, bevanjkay approved these changes

2024-03-21 02:20 UTC, merged