prompt-local-terminal 3.0.3 (new cask)
Homebrew/homebrew-cask pull request #169495
Opened 2024-03-20 06:14 UTC by HuaDeity

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --cask --new <cask>` worked successfully.
- [x] `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

---

2024-03-20 13:46 UTC, krehel commented
I'm afraid I don't understand what this is for.  This doesn't look like an application, and any application mentions for Prompt look to point to the App Store.

2024-03-20 14:55 UTC, HuaDeity commented
@krehel 

This is a helper program that is necessary to open the local terminal in prompt3. In my case, it would be beneficial to use Homebrew for installation and upgrades.

2024-03-21 02:22 UTC, bevanjkay requested changes

2024-03-21 02:22 UTC, bevanjkay commented on Casks/p/prompt-local-terminal.rb
> +    regex(%r{href="/prompt/Install%20Prompt%20Local%20Terminal%20(\d+\.\d+\.\d+)\.zip"}i)
```suggestion
    regex(/href=.*?Install%20Prompt%20Local%20Terminal%20v?(\d+(?:\.\d+)+)\.zip/i)

2024-03-21 03:31 UTC, HuaDeity commented
@bevanjkay 

I used the "createzap" command, but it only displayed "~/Library/LaunchAgents/com.panic.LocalTerminal.plist", which has already been added in launchctl.

2024-03-24 02:42 UTC, razvanazamfirei commented
I'm sorry, @HuaDeity, but I agree with @krehel on this one! Thank you for submitting this and all your hard work, but we're going to pass at this point. 

Thank you!

2024-03-24 02:42 UTC, closed without merging