Create ireal-pro.rb
Homebrew/homebrew-cask pull request #169683
Opened 2024-03-22 04:19 UTC by ShredderWalnut

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask --online <cask>` is error-free.
- [ ] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --cask --new <cask>` worked successfully.
- [ ] `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

---

2024-03-22 05:33 UTC, bevanjkay requested changes

2024-03-22 05:33 UTC, bevanjkay commented on ireal-pro
> +      strategy :sparkle, &:shortVersionString
```suggestion
      strategy :sparkle
```

If we also capture the version, then we can use the versioned url https://ireal-pro.s3.amazonaws.com/iRealPro20240213.zip which would allow the proper use of the `sha256` value.

2024-03-22 05:33 UTC, bevanjkay commented on ireal-pro
> +      regex(/\d+\.\d+/i)
```suggestion
```

We shouldn't need the regex here.

2024-03-22 05:33 UTC, bevanjkay commented on ireal-pro
> +  ]
```suggestion
  zap trash: "~/Library/Containers/iReal Pro"
```

2024-03-22 05:47 UTC, ShredderWalnut commented
Thank you for the tips and stylistic adjustments @bevanjkay , much appreciated! :)

2024-03-22 05:53 UTC, bevanjkay submitted a review, later dismissed
Another round of changes

2024-03-22 05:53 UTC, bevanjkay commented on ireal-pro
> +    url "https://ireal-pro.s3.amazonaws.com/iReal+Pro+2023.11.2.dmg"
```suggestion
    url "https://ireal-pro.s3.amazonaws.com/iReal+Pro+#{version}.dmg"

2024-03-22 05:53 UTC, bevanjkay commented on ireal-pro
> +    url "https://ireal-pro.s3.amazonaws.com/iReal+Pro.dmg",
```suggestion
    url "https://ireal-pro.s3.amazonaws.com/iRealPro#{version.csv.second}.zip"

2024-03-22 05:53 UTC, bevanjkay commented on ireal-pro
> +    version "2024.2"
```suggestion
    version "2024.2,20240213"
```

2024-03-22 05:58 UTC, bevanjkay commented
There will likely be some more style / audit failures, because the file was missing the extension and was in the wrong directory.

2024-03-24 02:34 UTC, razvanazamfirei commented
Thank you for submitting this! Looks great! 👍

2024-03-24 02:34 UTC, razvanazamfirei approved these changes

2024-03-24 02:43 UTC, razvanazamfirei approved these changes

2024-03-24 02:43 UTC, merged