Adding Irpf2024 v1.1
Homebrew/homebrew-cask pull request #169801
Opened 2024-03-24 15:47 UTC by ffeu

App for income declaration and tax calculation made for Brazilian tax payers.

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --cask --new <cask>` worked successfully.
- [x] `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

---

2024-03-24 22:30 UTC, bevanjkay requested changes

2024-03-24 22:30 UTC, bevanjkay commented on Casks/i/irpf2024.rb
> +  EOS
```suggestion
```

I know this has been included previously, however caveats are for Homebrew specific installation notes, which this is not.

2024-03-25 06:53 UTC, bevanjkay approved these changes

2024-03-25 14:18 UTC, p-linnane approved these changes

2024-03-25 14:18 UTC, merged