loungy 0.1.2
Homebrew/homebrew-cask pull request #169916
Opened 2024-03-26 13:26 UTC by MatthiasGrandl

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --cask --new <cask>` worked successfully.
- [x] `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

---
 
[Loungy](https://github.com/MatthiasGrandl/loungy) is an open-source GPU-accelerated application launcher in the vein of Raycast and Alfred.

2024-03-26 20:41 UTC, bevanjkay requested changes
I have left a couple of comments below.

My additional concern is the wording on your repository sounds to me like the product is not mature enough to be included in `homebrew-cask`. Is this statement still true?

> It isn't (yet) intended to be used outside of experimentation.

2024-03-26 20:41 UTC, bevanjkay commented on Casks/l/loungy.rb
> +
The `github_latest` strategy is only required if you have pre-releases or tags with no corresponding release. In this case it looks like it ok to remove the `livecheck` block and to use the default `git` livecheck strategy that will be inferred automatically from the `url`.

```suggestion
```

2024-03-26 20:41 UTC, bevanjkay commented on Casks/l/loungy.rb
> +  desc "GPU accelerated application launcher in the vein of Raycast and Alfred"
```suggestion
  desc "Application launcher"
```

Feel free to suggest an alternative to this, but make sure it meets the [`desc guidelines`](https://docs.brew.sh/Cask-Cookbook#stanza-desc).

2024-03-27 12:03 UTC, MatthiasGrandl commented
> I have left a couple of comments below.
> 
> My additional concern is the wording on your repository sounds to me like the product is not mature enough to be included in `homebrew-cask`. Is this statement still true?
> 
> > It isn't (yet) intended to be used outside of experimentation.

I updated the README.md. Loungy has matured a lot since then and quite a few people are using it already.

2024-03-27 20:42 UTC, bevanjkay approved these changes

2024-03-27 20:46 UTC, merged

2024-03-27 21:12 UTC, bevanjkay commented
Thank you @MatthiasGrandl