lookaway 1.4.1 (new cask)
Homebrew/homebrew-cask pull request #170014
Opened 2024-03-27 11:56 UTC by kushsolitary

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --cask --new <cask>` worked successfully.
- [x] `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

---

2024-03-27 12:13 UTC, kushsolitary commented
Hello, we use github only to host the binaries but the audit is failing because the repository is not notable enough. The app has its own website: https://lookaway.app and is getting quite popular.

2024-03-27 14:56 UTC, kushsolitary commented
Hello, we use github only to host the binaries but the audit is failing because the repository is not notable enough. The app has its [own website](https://lookaway.app/) and is getting quite popular.

2024-03-27 15:59 UTC, krehel commented
Congrats on opening you first PR in Homebrew.

Seems like we aren't allowed to edit this PR.  Any particular reason why?  Helpful if you allow maintainer edits, if needed.

2024-03-27 16:00 UTC, krehel commented on Casks/l/lookaway.rb
> +  end
Not needed if you don't use pre-releases, and preferred not to have it.

```suggestion
```

2024-03-27 16:01 UTC, krehel commented on Casks/l/lookaway.rb
> +  zap trash: "~/Library/Application Support/LookAway"
Found other files

```suggestion
  zap trash: [
    "~/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.mysticalbits.lookaway.sfl*",
    "~/Library/Application Support/LookAway",
    "~/Library/Caches/SentryCrash/LookAway",
    "~/Library/Preferences/com.mysticalbits.lookaway.plist",
  ]
```

2024-03-27 16:02 UTC, kushsolitary commented on Casks/l/lookaway.rb
> +  end
fixed!

2024-03-27 16:04 UTC, kushsolitary commented
> Congrats on opening your first PR in Homebrew!
> 
> Seems like we aren't allowed to edit this PR. Any particular reason why? Helpful if you allow maintainer edits, if needed.

hmm.. I am actually not sure how/where to enable that. Could you please point me to the right direction?

2024-03-27 16:05 UTC, kushsolitary commented on Casks/l/lookaway.rb
> +  zap trash: "~/Library/Application Support/LookAway"
thank you, added these as well.

2024-03-27 17:01 UTC, krehel commented on Casks/l/lookaway.rb
> +  auto_updates true
Thanks for adding `auto_updates`, I was going to ask about this.

2024-03-27 17:20 UTC, krehel commented on Casks/l/lookaway.rb
> +  desc "Reduce dry eyes and digital strain"
Maybe something like the first option?  I was working on the second option below but doesn't really tell what the application is for.  Thoughts? @kushsolitary?
```suggestion
  desc "Break time reminder app"
```
```suggestion
  desc "Reduce digital eye strain"
```

2024-03-27 17:41 UTC, kushsolitary commented on Casks/l/lookaway.rb
> +  desc "Reduce dry eyes and digital strain"
The first options sounds good to me @krehel

2024-03-27 21:14 UTC, bevanjkay commented
> Edit: I don't have the option "Allow edits from maintainers" which is supposed to be here

For future reference, this is because the PR is opened from an org fork.

2024-03-27 21:15 UTC, bevanjkay requested changes

2024-03-27 21:15 UTC, bevanjkay commented on Casks/l/lookaway.rb
> +
```suggestion
```

This should be removed.

2024-03-28 03:33 UTC, bevanjkay approved these changes

2024-03-28 03:42 UTC, merged

2024-03-28 03:42 UTC, miccal commented
Thank you @kushsolitary.