Add ClearVPN cask
Homebrew/homebrew-cask pull request #170255
Opened 2024-03-29 23:51 UTC by rternavskyi

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [ ] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask --online <cask>` is error-free.
- [ ] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --cask --new <cask>` worked successfully.
- [ ] `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

---

2024-03-31 01:41 UTC, razvanazamfirei commented
Thank you for opening this! I made some changes. The livecheck strategy is a bit awkward, but we prefer versioned urls when feasible.

2024-03-31 03:39 UTC, krehel commented
Could we go simpler on this?  Not sure if we need the `shortVersionString` - this strips out pretty much any excess in the regex, but I don't want to be so simple it causes issues down the line.

```
  livecheck do
    url "https://updates.devmate.com/com.macpaw.clearvpn.macos-site-ver.xml"
    regex(%r{/(\d+)/ClearVPN}i)
    strategy :sparkle do |item, regex|
      match = item.url.match(regex)
      next if match.blank?

      "#{item.title},#{match[1]}"
    end
  end
 ```

Alternate regex that also works with using the `.zip` to help maybe reduce any false positives -

```
regex(%r{/(\d+)/ClearVPN[._-](?:\d+\.+\d+)+\.zip}i)
```

2024-03-31 10:58 UTC, rternavskyi commented
@razvanazamfirei Why is there such a complication of livecheck? Here is a script for another program from the same publisher.
https://github.com/Homebrew/homebrew-cask/blob/master/Casks/c/cleanmymac.rb

2024-04-01 01:15 UTC, bevanjkay commented
@rternavskyi We need to collect additional version parts to assemble the `url` dynamically. The cask you linked has a simpler version format upstream.

2024-04-01 23:36 UTC, razvanazamfirei commented
@krehel, that looks good to me. I wanted to keep the canonical version, but am fine with us dropping it.

2024-04-02 08:51 UTC, bevanjkay requested changes
Looks good to me, just a minor nit on the `desc`.

2024-04-02 08:51 UTC, bevanjkay commented on Casks/c/clearvpn.rb
> +  desc "One-tap VPN for secure online journeys"
```suggestion
  desc "VPN client"
```

2024-04-03 05:26 UTC, bevanjkay approved these changes

2024-04-03 10:28 UTC, merged