CapCut
Homebrew/homebrew-cask pull request #170254
Opened 2024-03-29 23:51 UTC by rternavskyi

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [ ] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask --online <cask>` is error-free.
- [ ] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --cask --new <cask>` worked successfully.
- [ ] `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

---

2024-03-31 01:24 UTC, razvanazamfirei reviewed
This looks generally good, but I'm not sure how stable the livecheck will be given the `device_id` in it.

2024-03-31 02:33 UTC, samford reviewed
> I'm not sure how stable the livecheck will be given the `device_id` in it.

It looks like the relevant part of the JSON remains the same if we remove the `device_id` parameter. The same is true if we remove `arch_info=arm64`.

If these parameters were simply what the application was using when checking for new versions, then we should adapt them to what's appropriate for the cask and minimize them as much as possible. Removing any of the other parameters causes the check to fail, so I think we just want to remove `device_id` and maybe `arch_info` (unless there's a reason for us to restrict this to `arm64` only).

2024-03-31 20:31 UTC, bevanjkay commented
I out in considerable work to get the livecheck block working last time, but never heard back from @rternavskyi about whether the corresponding installation changes had any side effects. 

Ref: https://github.com/Homebrew/homebrew-cask/pull/162456

2024-03-31 20:35 UTC, bevanjkay requested changes

2024-03-31 20:35 UTC, bevanjkay commented on Casks/c/capcut.rb
> +  desc "Creative platform powered by AI that enables video editing and image design"
```
  desc "Video editing and image design platform"

2024-04-01 02:04 UTC, rternavskyi commented
@bevanjkay I'm sorry, last time I didn't have the opportunity to go to github and check the pull request update. So now I'm planning to close it.
I checked that the application is installed correctly. But after logging into the app, it offered me to update the version. It looks like there is another source of the update.

2024-04-01 02:05 UTC, bevanjkay commented
@rternavskyi Sometimes apps provide partial updates, that aren't offered as a full reinstall, so it could be expected behaviour

2024-04-01 02:31 UTC, rternavskyi commented
> Sometimes apps provide partial updates, that aren't offered as a full reinstall, so it could be expected behaviour

Then everything works perfectly

2024-04-01 02:32 UTC, rternavskyi commented
But I don't know if I should delete arch_info and device_id?

2024-04-01 02:54 UTC, bevanjkay commented
> But I don't know if I should delete arch_info and device_id?

Yes let's remove them. Thanks.

2024-04-01 23:27 UTC, bevanjkay approved these changes

2024-04-01 23:27 UTC, merged