arm-performance-libraries 24.04 (new cask)
Homebrew/homebrew-cask pull request #170762
Opened 2024-04-05 22:34 UTC by pthariensflame

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=pullrequests).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --cask --new <cask>` worked successfully.
- [x] `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

2024-04-06 01:49 UTC, razvanazamfirei requested changes
Hi @pthariensflame, is there any reason why the simplified version scheme would not work?

2024-04-06 01:49 UTC, razvanazamfirei commented on Casks/a/arm-performance-libraries.rb
> +  url "https://developer.arm.com/-/media/Files/downloads/hpc/arm-performance-libraries/#{version.csv.first.major}-#{version.csv.first.minor}/macos/arm-performance-libraries_#{version.csv.first}_macOS
```suggestion
  url "https://developer.arm.com/-/media/Files/downloads/hpc/arm-performance-libraries/#{version.dots_to_hyphens}/macos/arm-performance-libraries_#{version}_macOS.tgz"
```

2024-04-06 01:49 UTC, razvanazamfirei commented on Casks/a/arm-performance-libraries.rb
> +  version "24.04,17145f380ea64fe6b26de596182561bc,17145f38-0ea6-4fe6-b26d-e596182561bc"
```suggestion
  version "24.04"
```

2024-04-06 01:49 UTC, razvanazamfirei commented on Casks/a/arm-performance-libraries.rb
> +  install_suffix="#{version.csv.first}_flang-new_clang_18"
```suggestion
  install_suffix="#{version}_flang-new_clang_18"
```

2024-04-06 01:53 UTC, pthariensflame commented
> Hi @pthariensflame, is there any reason why the simplified version scheme would not work?

No specific reason, no!  It just makes autobump from livecheck harder, but I guess that was out of the question anyways given the install suffix issue.  I'll make that change when I can next touch my dev machine!

2024-04-06 18:37 UTC, pthariensflame commented
@razvanazamfirei As it turns out, the revision info is not needed for the download URL, so I got rid of it entirely!  Thank you for making me look at it more closely!

2024-04-12 22:03 UTC, pthariensflame commented
@razvanazamfirei Any news?

2024-04-12 22:33 UTC, pthariensflame commented on Casks/a/arm-performance-libraries.rb
> +  caveats "You may need to source /opt/arm/armpl_#{install_suffix}/armpl_env_vars.sh in order to use these libraries."
Applies across-the-board.  The script just sets some environment variables, so in principle a user could do that just as well manually, but running it is vender-recommended practice on all installations.

2024-04-15 00:39 UTC, bevanjkay commented on Casks/a/arm-performance-libraries.rb
> +  name "arm-performance-libraries"
```suggestion
  name "Arm Performance Libraries"
```

2024-04-15 02:47 UTC, bevanjkay commented on Casks/a/arm-performance-libraries.rb
> +    args:       ["-y"],
I'm on the fence on whether we should explicitly accept the license systematically. Waiting for some other maintainers to chime in their thoughts.

2024-04-15 17:54 UTC, razvanazamfirei commented on Casks/a/arm-performance-libraries.rb
> +    args:       ["-y"],
We should be able to use the license caveat, I think. See my last commit.

2024-04-16 20:27 UTC, razvanazamfirei approved these changes

2024-04-16 20:37 UTC, krehel approved these changes

2024-04-16 21:54 UTC, chenrui333 approved these changes

2024-04-16 21:54 UTC, merged