Add Flox as new Cask
Homebrew/homebrew-cask pull request #170971
Opened 2024-04-09 18:12 UTC by stahnma

See https://flox.dev for more information.

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=pullrequests).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --cask --new <cask>` worked successfully.
- [x] `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

---

2024-04-09 18:40 UTC, stahnma commented
The uninstall happening nearly immediately after the installation is case that we hadn't worked through yet. Will fix. (After install it kicks off an indexing thing so that can fail if you uninstall immediately)

2024-04-09 23:23 UTC, bevanjkay requested changes
Thank you for submitting this @stahnma 
I have left a few queries and suggested changes in my review.

2024-04-09 23:23 UTC, bevanjkay commented on Casks/f/flox.rb
> +    end
```suggestion
    regex(/^v?(\d+(?:\.\d+)+)$\.zip/i)
```

Update to align with standard pattern for `livecheck` blocks.

2024-04-09 23:23 UTC, bevanjkay commented on Casks/f/flox.rb
> +            },
Can you explain why the `early_script` stanza is required?

2024-04-09 23:23 UTC, bevanjkay commented on Casks/f/flox.rb
> +              "/opt/homebrew/Caskroom/flox",
The caskroom path should be removed from here.

2024-04-09 23:23 UTC, bevanjkay commented on Casks/f/flox.rb
> +    "/opt/homebrew/Caskroom/flox",
The caskroom path should be removed from here.

2024-04-09 23:23 UTC, bevanjkay commented on Casks/f/flox.rb
> +              "~/.cache/flox",
The cache should likely only be included in the `zap` stanza.

2024-04-09 23:23 UTC, bevanjkay commented on Casks/f/flox.rb
> +            },
Do we need to call the uninstall script directly? Or does the pkg uninstaller handle this already?

2024-04-10 16:37 UTC, stahnma commented on Casks/f/flox.rb
> +    end
I don't think that regex would match? There's no `.zip` anywhere. The file we're pulling for is literally a bare version string and that's it. In this example it says "1.0.3" that's the whole file.

2024-04-10 16:38 UTC, stahnma commented on Casks/f/flox.rb
> +            },
If you install flox it kicks off a background indexing job. If that's still running when you uninstall, it needs to be killed prior to the uninstall items running. This wasn't caught until this GHA because I never installed and then uninstalled in < 10 seconds before :)

2024-04-10 16:39 UTC, stahnma commented on Casks/f/flox.rb
> +            },
We do. The uninstall script does some additional cleanup and defense in addition to the items in the cask.

2024-04-10 16:41 UTC, stahnma commented on Casks/f/flox.rb
> +              "~/.cache/flox",
Changed.

2024-04-10 16:42 UTC, stahnma commented on Casks/f/flox.rb
> +    end
FWIW, I assumed would be really to just read a string, but it was remarkably obtuse in trying to figure out how to get it to work. If there's a shorter/more straightforward way of doing it -- happy to change.

2024-04-10 20:34 UTC, stahnma commented
Ready for another review pass. I've resolved the comments that were straightforward and answered questions on the remainder.

2024-04-10 21:35 UTC, bevanjkay commented on Casks/f/flox.rb
> +    end
Sorry yes that was a mistake on my part. I will update the suggestion

2024-04-10 21:37 UTC, bevanjkay commented on Casks/f/flox.rb
> +            },
Does it remove any user preferences, or related?
Noting that the uninstall stanza is also used for `brew upgrade` (runs uninstall, and then install).

2024-04-10 23:48 UTC, bevanjkay commented on Casks/f/flox.rb
> +            },
Can we use the `quit` stanza instead? https://docs.brew.sh/Cask-Cookbook#uninstall-quit
Or if that doesn't work use the `signal` stanza?

2024-04-11 02:22 UTC, stahnma commented on Casks/f/flox.rb
> +            },
I don't _think_ so. If I am comprehending this properly (and apologies if I am not, I am not super familiar with the macOS ecosystem, at least compared to my linux knowledge) `quit` looks like it will stop things that are running and spawned via launchd and not just processes that run/forked by a user. For example there is no `com.floxdev.pkgdb`, as it's normally only called by user using `flox` on the CLI. It's just this one case where it backgrounds itself to do the initial index. 

Am I understanding that correctly that the `quit` directive only uses things registered with launchd?

2024-04-11 02:24 UTC, stahnma commented on Casks/f/flox.rb
> +            },
Good to know on upgrade running uninstall then install. That may change the behavior I want here. I have an inquiry out to the dev team to ask more about the best way to handle this.

2024-04-11 03:20 UTC, tomberek commented on Casks/f/flox.rb
> +            },
It will remove any Nix-specific profiles and the contents of the Store. But those are not exposed and can be recreated so there is no degradation. This does mean that upgrade will be slower than it should be.

2024-04-12 16:11 UTC, stahnma commented on Casks/f/flox.rb
> +            },
@bevanjkay is there another approach I should take here?

2024-04-14 11:28 UTC, bevanjkay commented on Casks/f/flox.rb
> +            },
Can we try with `quit` or `signal` and see if it passes CI?

2024-04-15 22:58 UTC, stahnma commented on Casks/f/flox.rb
> +            },
@bevanjkay Yeah, switching to `signal` doesn't work. See https://github.com/Homebrew/homebrew-cask/actions/runs/8697133201/job/23851802679?pr=170971   I'll try `quit` and see if that can work without being a registered launchd service.

2024-04-15 23:00 UTC, bevanjkay commented on Casks/f/flox.rb
> +            },
Sorry, just pushed the same now. Otherwise we could try `signal` passing in `-9` as the signal, but it may fail because it is ran from the user, not sudo.

2024-04-15 23:03 UTC, bevanjkay commented on Casks/f/flox.rb
> +            },
If it doesn't work this time, feel free to drop the commits and we can revert to using `early_script`, thanks for trying the alternatives 👍

2024-04-15 23:04 UTC, stahnma commented on Casks/f/flox.rb
> +            },
Oh sorry, we're stepping on each other. :) I'll get this run through.

2024-04-15 23:10 UTC, bevanjkay commented on Casks/f/flox.rb
> +            },
Still no good @stahnma, all good to go back to `early_script`, and thank you for your patience.

2024-04-15 23:13 UTC, stahnma commented
@bevanjkay it does look like this also fails. Is going back to `early_script` an ok option if we've exhausted the others?

2024-04-15 23:14 UTC, bevanjkay approved these changes

2024-04-15 23:19 UTC, merged

2024-04-15 23:19 UTC, stahnma commented
Thank you, @bevanjkay

2026-02-11 21:30 UTC, chenrui333 commented on Casks/f/flox.rb
> +  auto_updates true
- https://github.com/Homebrew/homebrew-cask/pull/248967