Add cask `simpletex` v0.2.6
Homebrew/homebrew-cask pull request #171841
Opened 2024-04-20 22:34 UTC by singularitti

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=pullrequests).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --cask --new <cask>` worked successfully.
- [x] `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

---

2024-04-20 22:42 UTC, razvanazamfirei requested changes, later dismissed

2024-04-20 22:42 UTC, razvanazamfirei commented on Casks/s/simpletex.rb
> +  url "https://simpletex.cn/download_mac_#{arch}_url"
The link redirects to: `https://gitee.com/simpletex/simple-tex-download/releases/download/v0.2.5/SimpleTex-0.2.6-arm64.dmg`

2024-04-20 22:42 UTC, razvanazamfirei commented on Casks/s/simpletex.rb
> +
Since it uses Electron, can we use `https://update.simpletex.cn/publish/electron/latest-mac.yml` for the livecheck?

2024-04-20 22:42 UTC, razvanazamfirei commented on Casks/s/simpletex.rb
> +
Does this need auto_updates true?

2024-04-20 22:47 UTC, singularitti commented on Casks/s/simpletex.rb
> +  url "https://simpletex.cn/download_mac_#{arch}_url"
I am aware of this. However, I think they have messed up the release numbers, since `v0.2.6` is released under a `v0.2.5` tag.

2024-04-20 22:48 UTC, singularitti commented on Casks/s/simpletex.rb
> +
Sure. I did not add this link since I cannot have access to this link. Could you please verify that this link is valid?

2024-04-20 22:48 UTC, singularitti commented on Casks/s/simpletex.rb
> +
Probably not?

2024-04-21 23:51 UTC, bevanjkay commented on Casks/s/simpletex.rb
> +
I would assume based on the presence of Electron Builder that this has an in-app auto-updating mechanism?

2024-04-21 23:52 UTC, bevanjkay commented on Casks/s/simpletex.rb
> +  url "https://simpletex.cn/download_mac_#{arch}_url"
Let's wait for the issue to be resolved then.
We should use the versioned `url` wherever possible as it provides the additional security of having checksum.

2024-04-22 00:03 UTC, singularitti commented on Casks/s/simpletex.rb
> +
Yes, it is self-updatable.
<img width="890" alt="image" src="https://github.com/Homebrew/homebrew-cask/assets/25192197/7001ed7f-33dc-4aeb-8044-0e81710b019d">

2024-04-22 00:03 UTC, singularitti commented on Casks/s/simpletex.rb
> +  url "https://simpletex.cn/download_mac_#{arch}_url"
I'll contact them to fix this.

2024-04-22 00:21 UTC, bevanjkay commented on Casks/s/simpletex.rb
> +
Thanks, it should definitely have `auto_updates true` then.

2024-05-16 01:44 UTC, miccal commented
The `url`'s in the Cask are very slow, so adding the `ci-retry` label.

2024-05-16 01:47 UTC, miccal commented
/rebase

2024-05-16 01:49 UTC, miccal commented
/rebase

2024-05-16 01:53 UTC, miccal commented
Closing in favour of https://github.com/Homebrew/homebrew-cask/pull/173943.

2024-05-16 01:53 UTC, closed without merging

2024-05-16 03:33 UTC, singularitti commented
Thanks!