universal-control 4.2.0.96206 (new cask)
Homebrew/homebrew-cask pull request #172358
Opened 2024-04-28 00:22 UTC by Shane-CS

Add new cask Universal Control by PreSonus for controlling PreSonus hardware.

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=pullrequests).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --cask --new <cask>` worked successfully.
- [x] `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

---

2024-04-28 17:14 UTC, razvanazamfirei requested changes, later dismissed

2024-04-28 17:14 UTC, razvanazamfirei commented on Casks/u/universal-control.rb
> +cask "universal-control" do
I think we should call this `presonus-universal-control`
```suggestion
cask "presonus-universal-control" do
```

2024-04-28 17:14 UTC, razvanazamfirei commented on Casks/u/universal-control.rb
> +  desc "Control your PreSonus hardware"
```suggestion
  desc "PreSonus software control interface"
```

2024-04-28 17:14 UTC, razvanazamfirei commented on Casks/u/universal-control.rb
> +  end
```suggestion
  livecheck do
    url "https://legacy.presonus.com/products/Universal-Control/downloads"
    regex(/Universal\s?Control\sv?(\d+(?:\.\d+)*)/i)
  end
```

2024-04-28 17:14 UTC, razvanazamfirei commented on Casks/u/universal-control.rb
> +  uninstall launchctl: "asp.com.presonus.pae-quantum-audio-plug-in"
```suggestion
  uninstall launchctl: [
              "asp.com.presonus.pae-quantum-audio-plug-in",
              "com.presonus.ucdaemon",
            ],
            pkgutil:   [
              "presonus.pkg.Universal.Control.controlpanel",
              "presonus.pkg.Universal.Control.daemon",
              "presonus.pkg.Universal.Control.presets",
              "presonus.pkg.Universal.Control.tb_driver",
            ]
```

2024-04-28 17:14 UTC, razvanazamfirei commented on Casks/u/universal-control.rb
> +end
Please try to add a [zap stanza](https://docs.brew.sh/Cask-Cookbook#stanza-zap) for this cask.

2024-04-28 21:09 UTC, Shane-CS commented on Casks/u/universal-control.rb
> +end
Sure, I'll look into adding one.

2024-04-28 21:28 UTC, Shane-CS commented on Casks/u/universal-control.rb
> +end
Added the stanza.

2024-04-28 22:31 UTC, bevanjkay approved these changes

2024-04-28 22:33 UTC, bevanjkay approved these changes

2024-04-28 22:33 UTC, bevanjkay commented on Casks/p/presonus-universal-control.rb
> +    regex(/Universal\s?Control\sv?(\d+(?:\.\d+)*)/i)
The asterisk in the regex should be another `+`

2024-04-28 23:39 UTC, Shane-CS commented on Casks/p/presonus-universal-control.rb
> +    regex(/Universal\s?Control\sv?(\d+(?:\.\d+)*)/i)
You're right, totally missed that.

2024-04-29 00:08 UTC, bevanjkay approved these changes
Thank you @Shane-CS

2024-04-29 00:09 UTC, merged