Add VirtualDJ cask
Homebrew/homebrew-cask pull request #173053
Opened 2024-05-06 19:50 UTC by zotanmew

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=pullrequests).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --cask --new <cask>` worked successfully.
- [x] `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

---

2024-05-06 22:51 UTC, bevanjkay requested changes
Thanks @zotanmew for submitting this.
I have made some changes in my review.

2024-05-06 22:51 UTC, bevanjkay commented on Casks/v/virtualdj.rb
> +  desc "#1 Most Popular DJ Software"
```suggestion
  desc "DJ Software"
```

2024-05-06 22:51 UTC, bevanjkay commented on Casks/v/virtualdj.rb
> +  version "2024.b8124"
```suggestion
  version "2024,8124"
```

Split the version number with a comma between the version and then the build number.

2024-05-06 22:51 UTC, bevanjkay commented on Casks/v/virtualdj.rb
> +  url "https://download.virtualdj.com/install_virtualdj_#{version.dots_to_underscores}_mac.pkg"
```suggestion
  url "https://download.virtualdj.com/install_virtualdj_#{version.csv.first}_b#{version.csv.second}_mac.pkg"
```

Update url to match new `version` format.

2024-05-06 22:51 UTC, bevanjkay commented on Casks/v/virtualdj.rb
> +  end
```suggestion
  livecheck do
    url "https://virtualdj.com/download/mac"
    regex(/install[._-]virtualdj[._-]?(\d+(?:\.\d+)*)[._-]b(\d+)[._-]mac\.pkg/i)
    strategy :header_match do |headers, regex|
      match = headers["location"].match(regex)
      next if match.blank?

      "#{match[1]},#{match[2]}"
    end
  end
```

2024-05-06 22:51 UTC, bevanjkay commented on Casks/v/virtualdj.rb
> +  pkg "install_virtualdj_#{version.dots_to_underscores}_mac.pkg"
```suggestion
  pkg "install_virtualdj_#{version.csv.first}_b#{version.csv.second}_mac.pkg"
```

Update to match new `version` format.

2024-05-06 22:55 UTC, zotanmew commented
Thank you, should be all done.

2024-05-06 22:57 UTC, bevanjkay commented on Casks/v/virtualdj.rb
> +      next if match.blank?
Thanks @zotanmew, just need to add a new line underneath the `next if` guard clause.

2024-05-06 22:58 UTC, zotanmew commented
Apologies, I'm not that familiar with ruby syntax.

2024-05-06 23:08 UTC, bevanjkay approved these changes

2024-05-07 01:25 UTC, miccal approved these changes

2024-05-07 08:51 UTC, bevanjkay approved these changes

2024-05-07 08:51 UTC, merged