wd-security (new cask)
Homebrew/homebrew-cask pull request #174386
Opened 2024-05-20 21:38 UTC by unitof

Reattempt of https://github.com/Homebrew/homebrew-cask/pull/173945: may have found a fix for the failing workflow, borrowed from `anydesk.rb`

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [-] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=pullrequests).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --cask --new <cask>` worked successfully.
- [x] `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

---

2024-05-20 22:01 UTC, unitof commented
It passes! See https://github.com/Homebrew/homebrew-cask/pull/173945 for context.

Let me know if this is cheating! But seems to handle the plist that was tripping up the workflow, which is left behind by the uninstall script.

I may have overestimated by calling this "obscure"—it's needed by anyone with a number of Western Digital drives, and is a pain to find and install from WD, thus the desire for a Cask.

Also allows us to much better handle clean uninstallation, as evidenced by our reverse engineering struggles here.

2024-05-20 22:24 UTC, krehel commented on Casks/w/wd-security.rb
> +  }
For record purposes - what is the reasoning to not use installer.sh and instead directly call the installer?

2024-05-20 22:44 UTC, unitof commented on Casks/w/wd-security.rb
> +  }
`installer.sh` relies on being run from within the DMG to locate the `WD Security Installer.app`, so within Homebrew it errors with file not found.

Unless there's a preferred way to set the CWD for `executable`?

`WD Security Installer.dmg/installer.sh`:
```
#!/bin/sh

#  installer.sh
#  WD Security Installer
#
#  Created by Mike Webster on 5/31/16.
#  Copyright © 2016 Western Digital. All rights reserved.

SECURITY_INSTALLER="WD Security Installer.app"

# run installer.  Supported arguments are:
# -silent     Suppress user interface for operation
# -install    Force an install operation
# -uninstall  Force an uninstall operation
open -W "exec/$SECURITY_INSTALLER/"
```

2024-05-21 01:24 UTC, miccal commented on Casks/w/wd-security.rb
> +end
```suggestion

  caveats do
    requires_rosetta
  end
end
```

![Screenshot 2024-05-21 at 09 22 27](https://github.com/Homebrew/homebrew-cask/assets/6127163/3bb71eb1-a47e-44c4-98d3-263b5cdead6c)

2024-05-21 02:23 UTC, miccal approved these changes

2024-05-21 02:42 UTC, krehel commented on Casks/w/wd-security.rb
> +  }
This is fine @unitof - I just wanted something for documentation purposes in the PR in case we wonder sometime later why this was done.  Thank you!

2024-05-21 02:42 UTC, krehel approved these changes

2024-05-21 02:44 UTC, bevanjkay requested changes
Can we confirm that it doesn't require user-intervention on install? When I installed it locally it required an additional password outside of terminal before continuing.

It is definitely still hanging definitely for me.

![Screenshot 2024-05-21 at 12 46 51 pm](https://github.com/Homebrew/homebrew-cask/assets/40621599/3d5b1c22-b92a-4802-9bce-fc713fd7ed08)

2024-05-21 03:54 UTC, unitof commented
It seems to prompt for that if Gatekeeper is enabled and it's been more that X minutes since the last time it was installs.

The prompt asks for biometrics with `sudo: true`, but prompts for full password when the formula doesn't call for sudo. Does that provide any clues how I might go about scripting around it?

As @bevanjkay noticed in the last PR, it seems the install .app is calling yet some other executable.

Understood if this is just a hard wall requiring interactivity—happy to bring this back to a personal tap and keep tinkering. Very happy with where it's gotten to.

2024-05-30 17:43 UTC, krehel commented
@unitof are you using a machine with Apple Silicon?  Also for @bevanjkay.  I'm going to test this locally but thoughts below ⬇️ 

I worked on a strange issue with the [mplab-xc16](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/m/mplab-xc16.rb) cask that blocked an update for almost a year.

After a lot of tinkering on that cask, I found on Intel hardware behavior was normal, but installing on Apple Silicon produced an authentication UI similar to what is shown here, intermittently, which I assume was related to some auth caching.  It also used an installer that was called directly with parameters, bypassing a `.sh` script.

Wondering if -

1. It's the same installer family (not directly important)
2. We don't use `requires_rosetta` and instead lock it down to Intel hardware with `depends_on arch: :x86_64` (which solved the issue for `mplab-xc16`) that this issue goes away.

2024-06-03 04:15 UTC, unitof commented
I am on Apple Silicon! Very interesting. Certainly worth a try. Do the test runners have any macOS security systems disabled or with non-default settings?

2024-06-03 04:15 UTC, unitof commented
I am on Apple Silicon! Very interesting. Certainly worth a try. Do the test runners have any macOS security systems disabled or with non-default settings?

2024-06-03 04:16 UTC, unitof commented
I am on Apple Silicon! Very interesting. Certainly worth a try. Do the test runners have any macOS security systems disabled or with non-default settings?

2024-06-10 05:06 UTC, unitof commented
For some reason I had in my head that Homebrew ran its own Mac Mini runners.

It might be that that extra authentication window only appears on machines with TouchID sensors, similar to Safari's password fill prompts. That would explain "caching" (if you biometrically authenticate it lasts systemwide for the same action for a few minutes), and would also explain why it's working headlessly on the runners.

Defer to you @bevanjkay. Would love for it to be in homebrew-cask and will keep tinkering if I find improvements, but understand if it needs to be a private tap.

2024-06-12 00:43 UTC, krehel commented
I do have an Intel laptop with a TouchID I can test on.  I have no ARM machines without TouchID sensors though.  Will try to get to in the next day.

2024-06-14 05:05 UTC, unitof commented
Well we know it works on headless M1 Macs without biometric sensors from the runners, I think.

I just tested installing over SSH on my headless M1 Mac mini running Seqoia beta and the installer script failed while Homebrew thought it was a success, so I'm going to look into that separately.

However it did properly prompt for sudo password and did not hang on biometric, so it seems likely to me that's what's going on: macOS prompts for an additional biometric authentication (over sudo or other authentication) for certain filesystem actions, on machines with biometric sensors like Touch ID or Face ID. This authentication is cached for some period of time (5 or 10 minutes?) and is—as far as we can tell—indefinitely blocking an invisible to CLI scripts which trigger it.

2024-07-03 02:04 UTC, bevanjkay approved these changes

2024-07-03 02:19 UTC, merged