feat: cask for outline desktop app (arm64/x64)
Homebrew/homebrew-cask pull request #176888
Opened 2024-06-16 07:40 UTC by fschlegelone

I made a new cask for the outline desktop app (built from the .dmg installer). 
I verified everything is brew-conform and neither errors nor warnings do show-up. 
https://getoutline.com
https://github.com/outline/outline

- [*] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [*] `brew audit --cask --online <cask>` is error-free.
- [*] `brew style --fix <cask>` reports no offenses.
- [*] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [*] Checked the cask was not [already refused](https://github.com/search?q=repo%3AHomebrew%2Fhomebrew-cask+is%3Aclosed+is%3Aunmerged+&type=pullrequests) (add your cask's name to the end of the search field).
- [*] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [*] `brew audit --cask --new <cask>` worked successfully.
- [*] `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --cask <cask>` worked successfully.
- [*] `brew uninstall --cask <cask>` worked successfully.

---

2024-06-16 13:03 UTC, daeho-ro commented on Casks/g/getoutline.rb
> +
You can merge those blocks into one,
```suggestion
    url "https://desktop.getoutline.com/mac/dmg/#{arch}"
```

2024-06-16 13:51 UTC, razvanazamfirei requested changes
Hi! Thanks so much for your first contribution! A couple of comments

2024-06-16 13:51 UTC, razvanazamfirei commented on Casks/g/getoutline.rb
> +cask "getoutline" do
The token doesn't follow our naming guidelines.

2024-06-16 13:51 UTC, razvanazamfirei commented on Casks/g/getoutline.rb
> +  url "https://desktop.getoutline.com/mac/dmg/#{arch}"
Is there a way to get a versioned download?

2024-06-16 14:07 UTC, bevanjkay commented on Casks/g/getoutline.rb
> +cask "getoutline" do
This one's tricky because `outline` is taken, and there's not really a vendor name I could see to prefix. So following the url may be the best option? Will require some discussion as it's an exception.

2024-06-16 14:33 UTC, krehel commented on Casks/g/getoutline.rb
> +cask "getoutline" do
Maybe this should be `general-outline`?  Sort of in line with `thorium` and `alex313031-thorium`, but understanding this isn't a fork scenario. And that does seem to be the incorporated company name.

I agree that getoutline doesn't seem right.  Neither option is particularly elegant, but `general-outline` feels better if I had to pick one.

2024-06-16 16:43 UTC, razvanazamfirei commented on Casks/g/getoutline.rb
> +cask "getoutline" do
The vendor name on Github is https://github.com/outline. I think `general-outline` should be fine?

2024-06-16 19:15 UTC, tommoor commented on Casks/g/getoutline.rb
> +cask "getoutline" do
👋 Hi as owner I'd rather not use `general-outline`, while it is the Corp name it's not used anywhere else that a customer would see. Instacart's company name is "Maplebear Inc" but you wouldn't use that.

`outlinewiki` is probably second preference, although it really is frustrating that a long dead project gets to sit on the `outline` namespace forever.

2024-06-17 00:06 UTC, bevanjkay commented on Casks/g/getoutline.rb
> +cask "getoutline" do
> although it really is frustrating that a long dead project gets to sit on the outline namespace forever.

Hi @tommoor, thanks for your input here. But the existing `outline` project is not "long dead', and received an update as recently as March 2024. Using an existing `token` can be a nuanced issue, as the existing users of the cask would be forced to update to the completely different app when running `brew upgrade`. In this case, `outline` has had 827 installs in the last year, so it isn't an insignificant number.

2024-06-17 00:11 UTC, tommoor commented on Casks/g/getoutline.rb
> +cask "getoutline" do
> Using an existing token can be a nuanced issue

Absolutely. I guess I"m just surprised there isn't a pattern for this yet given the maturity of Homebrew – perhaps a way to reuse the token of a dead app but "version" it to prevent auto upgrades. Either way, lets not use `general-outline` please 🙏

2024-06-17 00:14 UTC, bevanjkay commented on Casks/g/getoutline.rb
> +cask "getoutline" do
There's no documented policy, but if a `token` was to go through the `deprecation/disable/removal` process, the token may then become available for use again.
In this case, `outline` (www.outline.app) is still being actively developed, so this won't be possible for the foreseeable future.

2024-06-17 00:17 UTC, tommoor commented on Casks/g/getoutline.rb
> +cask "getoutline" do
I would like to correct myself – as the links in the cask mostly do not resolve I thought it was another dead project that also went by the same name (https://outline.ws) (https://outline.app) https://github.com/Homebrew/homebrew-cask/blob/master/Casks/o/outline.rb 

I see now that it's still active and perhaps that cask needs fixing 👍

2024-06-17 00:19 UTC, bevanjkay commented on Casks/g/getoutline.rb
> +cask "getoutline" do
Thanks Tom, I have opened a PR to fix the existing cask.

2024-06-17 13:40 UTC, bevanjkay commented on Casks/g/getoutline.rb
> +  end
```suggestion
  livecheck do
    url "https://download.todesktop.com/2211128hgkdcltv/latest-mac.yml"
    regex(/Build[ ._-]([^-]+)[._-]/i)
    strategy :electron_builder do |item, regex|
      build = item["files"].first["url"][regex, 1]
      next if build.blank?

      "#{item["version"]},#{build}"
    end
  end
```

2024-06-17 13:40 UTC, bevanjkay commented on Casks/g/getoutline.rb
> +  url "https://desktop.getoutline.com/mac/dmg/#{arch}"
```suggestion
  url "https://download.todesktop.com/2211128hgkdcltv/Outline%20#{version.csv.first}%20-%20Build%20#{version.csv.second}-#{arch}.dmg",
      verified: "download.todesktop.com/2211128hgkdcltv/"

2024-06-17 13:40 UTC, bevanjkay commented on Casks/g/getoutline.rb
> +  sha256 :no_check
After updating to the versioned `url` would need to add the checksum values here in the format...

```ruby
  sha256 arm:  "1234",
         intel: "12345"

2024-06-17 22:08 UTC, bevanjkay commented
This is looking good. It just needs `auto_updates true` to be added and then it should be ready.

2024-06-18 23:32 UTC, bevanjkay commented
/rebase

2024-06-19 04:59 UTC, razvanazamfirei approved these changes
This looks good pending clarification of token

2024-06-19 05:11 UTC, bevanjkay approved these changes

2024-06-19 14:08 UTC, krehel approved these changes

2024-06-19 14:08 UTC, merged