magicquit 1.4 (new cask)
Homebrew/homebrew-cask pull request #187899
Opened 2024-10-09 03:45 UTC by aaditkamat

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/search?q=repo%3AHomebrew%2Fhomebrew-cask+is%3Aclosed+is%3Aunmerged+&type=pullrequests) (add your cask's name to the end of the search field).
- [x] `brew audit --cask --new <cask>` worked successfully.
- [x] `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

---

2024-10-09 03:50 UTC, bevanjkay commented on Casks/m/magicquit.rb
> +  end
```suggestion
  livecheck do
    url :homepage
    regex(/href=.*?MagicQuit[._-]v?(\d+(?:\.\d+)+)\.dmg/i)

2024-10-09 03:51 UTC, bevanjkay reviewed
Please try to add a [zap stanza](https://docs.brew.sh/Cask-Cookbook#stanza-zap). The linked documentation provides some recommended methods to create it.

2024-10-09 08:09 UTC, bevanjkay commented on Casks/m/magicquit.rb
> +  zap trash: "~/Desktop/MagicQuit_1.4.dmg"
This doesn't look right. Did you run the app before trying to find the paths to zap?

If you did this can be replaced with

```suggestion
  # No zap stanza required
```

2024-10-09 12:09 UTC, aaditkamat commented on Casks/m/magicquit.rb
> +  zap trash: "~/Desktop/MagicQuit_1.4.dmg"
I ran `brew createzap magicquit` to generate this line and tested the cask using all the commands mentioned in the checklist. There were no issues.

2024-10-09 12:11 UTC, aaditkamat commented on Casks/m/magicquit.rb
> +  zap trash: "~/Desktop/MagicQuit_1.4.dmg"
You are right though, it was stupid of me. I am downloading the application to my Desktop as a Disk Image file and hence that location is showing up. Your suggestion would be better.

2024-10-09 12:58 UTC, aaditkamat commented on Casks/m/magicquit.rb
> +  zap trash: "~/Desktop/MagicQuit_1.4.dmg"
Also, I checked what locations data is stored within the app using the [Uninstall Apps tool within Parallels Toolbox](https://youtu.be/JEelGTBpVYw) and found no other locations than the Applications folder.

2024-10-09 21:05 UTC, aaditkamat commented
How can I fix the commit style check?

2024-10-09 23:44 UTC, bevanjkay commented
It is not a required check, but I will rebase to fix it anyone. Thank you.

2024-10-10 05:36 UTC, p-linnane approved these changes

2024-10-10 05:37 UTC, p-linnane requested changes, later dismissed

2024-10-10 05:37 UTC, p-linnane commented on Casks/m/magicquit.rb
> +
```suggestion

```

2024-10-10 05:40 UTC, bevanjkay approved these changes

2024-10-10 05:41 UTC, p-linnane approved these changes

2024-10-10 05:46 UTC, merged