[WIP] Add Adobe After Effects
Homebrew/homebrew-cask pull request #23900
Opened 2016-08-19 01:27 UTC by danielbayley

2016-08-23 23:35 UTC, adidalal commented
Some of the other Adobe casks may have useful tidbits if you're running into issues, FYI

2016-09-05 07:06 UTC, fanquake commented
@danielbayley Are you still working on this?

2016-09-05 18:56 UTC, danielbayley commented
@fanquake If by working on this you mean gradually working down a long todo list back towards it then yes 😆 Iv’e been on holiday…

I haven’t quite got it working yet; see questions on #19746

2016-09-05 19:16 UTC, vitorgalvao commented
@danielbayley If you need help, @winkelsdorf might be the person.

2016-09-05 21:53 UTC, danielbayley commented
As it stands this cask downloads AE successfully, and then runs the installer, but nothing after that point actually happens… nothing actually gets installed despite the `0` exit code. I based this off @lukeadams’ [adobe-animate-cc](https://github.com/caskroom/homebrew-cask/pull/19776/files) cask, and the [adobe-illustrator-cc](https://github.com/caskroom/homebrew-cask/blob/42437e5fcd93b1a3c95376794e6d5eee2b096160/Casks/adobe-illustrator-cc.rb)

Here is the Terminal output…
~~~ sh
$ brew cask install adobe-after-effects-cc
Warning: A Cask for adobe-after-effects-cc is already installed. Add the "--force" option to force re-install.
brew cask install --force adobe-after-effects-cc
==> Downloading http://prodesigntools.com/trials3/AdobeProducts/AEFT/13_5/osx10-
######################################################################## 100.0%
==> Verifying checksum for Cask adobe-after-effects-cc
==> Running installer script /usr/local/opt/Caskroom/adobe-after-effects-cc/2015
Password:
==> Starting Installer... In Silent mode.
==> Installation successful.
==> Exiting Installer with Code: 0
🍺  adobe-after-effects-cc was successfully installed!
~~~

2016-09-06 07:09 UTC, vitorgalvao commented
@danielbayley It’s unlikely you’ll get help from the core team on this. Adobe un/installations are a pain as casks and complex to make, and I’m somewhat vocal against Adobe (even being a designer and having used their software in the past, they are an incredibly user-hostile company).

If you can get help from the other users who successfully built casks for them (or can do it yourself) and make the cask work, we can merge it, but otherwise I don’t think (I may very well be wrong) any maintainer is interested in wasting (and I do mean “waste”, in this case) time on these.

2016-09-06 12:40 UTC, danielbayley commented
> Adobe un/installations are a pain as casks and complex to make, and I’m somewhat vocal against Adobe (even being a designer and having used their software in the past, they are an incredibly user-hostile company).

You’re preaching to the choir on that note! I _really_ can’t stand them as a company… the result of a virtual monopoly. The UX around their software absolutely _sucks_. But what else is a professional going to seriously use?

That said, I don’t think Cask itself should be opinionated against certain software…

2016-09-06 13:48 UTC, vitorgalvao commented
> But what else is a professional going to seriously use?

The [Affinity Suite of apps](https://affinity.serif.com/). They’re the only thing that ever came close to me *and* they’re actually superior in some regards. They’re lacking in some aspects and I’m also vocal with them about what those are, but they are young (the apps, not the people working on them) and know they have a lot to improve. They have equivalents to Illustrator, Photoshop, and (coming) InDesign.

For After Effects the competition is less direct, but I did find some that looked seriously capable, a few months ago. Unlike with the Affinity apps, I can’t attest to AE alternatives since I don’t use it.

On that regard, the mentality of “I won’t use anything else because nothing else comes close” is *exactly why* Adobe has such a monopoly. If you don’t make the effort to use something else, even it does not yet satisfy all your needs, that company has one less user, which means less feedback, less money, less resources, less interest, less people hearing about it, less reason to keep it up.

Adobe will lose its throne when people actually stop using them, not by wishing another company magically appears and immediately does everything they can and more. That is not going to happen.

> I don’t think Cask itself should be opinionated against certain software

And we are not. If we were, no Adobe apps would have been allowed. But not being opinionated does not mean maintainers will plunge their volunteer time equally into each app equally. Never have we discriminated against the inclusion of any Adobe app and if you search this repo and [caskroom/versions](https://github.com/caskroom/homebrew-versions) you’ll find me always commenting and trying to make the Adobe apps work. That is exactly why I know they are a pain and (for me) not worth the time they require.

My commitment to homebrew-cask means I’ll guide you in the right direction, it does not mean I’ll spend my weekend researching and running tests on a VM to make sure a cask I want nothing to do with works. Most casks are volunteer-contributed; it’s up to the contributors to make sure they work according to our requirements (that try to be as lenient as possible).

Like I said, in this case if you can get it to work (alone or with help, hence why I suggested someone that worked extensively to make the existing Adobe apps work at all) we will accept it, but I have already wasted too much time on the apps of that rotten company. Ethically, I can no longer justify that to myself.

2016-09-11 15:06 UTC, vitorgalvao commented
Any progress on this cask, @danielbayley?

2016-09-11 15:11 UTC, danielbayley commented
@vitorgalvao Nope; I’m waiting on the outcome of #24388, which is currently labelled “on hold”…

2016-09-11 15:52 UTC, danielbayley commented
> They’re lacking in some aspects

I do keep a hopeful eye on competitors, and have briefly tried some of the Affinity apps out in the past, but those areas that are lacking to me are _vast_, not to mention the integration _between_ the applications (the workflow between Illustrator and After Effects in particular is key for me, or Ai and Photoshop for example…) and yet to me even those aren't nearly integrated enough; I would like to see some of them merged into a single app in fact, given the huge crossover between them.

The ability to seamlessly work with existing Adobe formats (`.ai`,`.psd`,`.indd`,`.aep` etc…) given the massive backlog of projects/assets in these formats is also a big factor unfortunately.

For casual users, or more niche pros who tend to stick mostly to a single app, current alternatives might be almost there, but when we are talking about the whole suite I just can't see anything viable.

I feel like the real Adobe killer would be a Photoshop/Illustrator/InDesign hybrid app all rolled into one with different layer _types_ (typography layer, pixel layer, vector layer, adjustment layer etc…) as opposed to different formats managed by very similar yet just-slightly-different-enough-to-be-annoying apps, and possibly based on web technologies. I would love to see such a thing realised but have no idea where one would even start to climb the absolute mountain that would be to actually build! But yeah like you say… sadly that isn’t going to magically appear.

I don’t blame you for not working on Adobe casks if you don’t even use them; I wouldn’t either… just looking for some help based on the existing casks that _do_ work.

2016-09-16 20:11 UTC, danielbayley commented
@vitorgalvao This is working now. 👍

2016-09-17 10:38 UTC, vitorgalvao commented on Casks/adobe-after-effects-cc.rb
> +  app = name[0]
Don’t do this. `name` is fickle and should never be depended on. Make this explicit.

2016-09-17 10:42 UTC, vitorgalvao requested changes

2016-09-17 10:42 UTC, vitorgalvao commented
Pinging @winkelsdorf and @reitermarkus since they have dealt more with Adobe casks.

2016-09-17 15:27 UTC, danielbayley commented on Casks/adobe-after-effects-cc.rb
> +  app = name[0]
Fixed.

2016-09-17 15:55 UTC, vitorgalvao approved these changes

2016-10-11 22:00 UTC, danielbayley commented
@reitermarkus https://travis-ci.org/caskroom/homebrew-cask/jobs/166820114#L522

> download not possible: Download failed on Cask 'adobe-after-effects-cc' with message: No space left on device

¯\_(ツ)_/¯

2016-10-11 22:28 UTC, reitermarkus commented
> ¯\_(ツ)_/¯

Yep, most of the Adobe casks are too huge for Travis.

One of them passed though, so merging this.

2016-10-11 22:28 UTC, merged