Add TSPrintClient.app v1.6.2 Purpose is to add to cask.
Homebrew/homebrew-cask pull request #24484
Opened 2016-09-14 14:25 UTC by markthetech

### Instructions

Delete the parts of this template that are not relevant (including these `Instructions`) and fill out the rest.  
If there’s a checkbox you can’t complete for any reason, that’s OK. Just explain in detail why you weren’t able to do so.  
*Note:* `{{cask_file}}` represents the cask file you’re submitting/editing.

### Checklist

- [ ] The commit message includes the cask’s name and version.
- [ ] `brew cask audit --download {{cask_file}}` is error-free.
- [ ] `brew cask style --fix {{cask_file}}` left no offenses.

Additionally, when **adding a new cask**:

- [ ] Checked there are no open [pull requests](https://github.com/caskroom/homebrew-cask/pulls) for the same cask.
- [ ] Checked there are no closed [issues](https://github.com/caskroom/homebrew-cask/issues) where that cask was already refused.
- [ ] When naming the cask, followed the [token reference](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.

2016-09-14 19:06 UTC, vitorgalvao commented on Casks/tsprint.rb
> +  version '1.6.2'
Seeing as `url` doesn’t point to a specific version, this cask should use `version :latest` and `sha256 :no_check`. [See an example](https://github.com/caskroom/homebrew-cask/blob/f25b6babcd398abf48e33af3d887b2d00de1d661/Casks/kibako.rb).

2016-09-14 19:07 UTC, vitorgalvao commented on Casks/tsprint.rb
> +  uninstall quit: 'com.terminalworks.TSPrintClient', trash: '/Applications/TSPrintClient.app'
Separate `trash` into another line.

2016-09-14 19:07 UTC, vitorgalvao requested changes

2016-09-14 20:29 UTC, markthetech commented on Casks/tsprint.rb
> +  version '1.6.2'
changed version to :latest and sha256 to :nocheck

2016-09-14 20:29 UTC, markthetech commented on Casks/tsprint.rb
> +  uninstall quit: 'com.terminalworks.TSPrintClient', trash: '/Applications/TSPrintClient.app'
I put trash onto a new line.

2016-09-14 21:25 UTC, vitorgalvao commented on Casks/tsprint.rb
> +  uninstall trash: '/Applications/TSPrintClient.app'
It should be just one `uninstall`. See other casks. What I meant was

```ruby
uninstall quit: 'com.terminalworks.TSPrintClient',
          trash: '/Applications/TSPrintClient.app'
```

2016-09-15 03:00 UTC, reitermarkus commented on Casks/tsprint.rb
> +  uninstall trash: '/Applications/TSPrintClient.app'
Why isn't his using `uninstall pkgutil:` when a `pkg` installer was used?

2016-09-15 07:05 UTC, vitorgalvao commented on Casks/tsprint.rb
> +  uninstall trash: '/Applications/TSPrintClient.app'
@reitermarkus Good point. I didn’t even read `quit` correctly, just outright assumed it was `pkgutil` (too many reviews of similar things, I guess).

2016-09-15 13:30 UTC, markthetech commented on Casks/tsprint.rb
> +  uninstall trash: '/Applications/TSPrintClient.app'
I'm not using pkgutil: because in my testing it didn't successfully uninstall it.

2016-09-15 16:00 UTC, vitorgalvao commented on Casks/tsprint.rb
> +  uninstall trash: '/Applications/TSPrintClient.app'
@markthetech Even if it did not uninstall everything (not unusual), it’s highly unlikely the only thing the `pkg` does is put `.app` in `Applications`. It’s very likely it’s installing other things, and `pkgutil` might take care of those.

2016-09-15 16:01 UTC, vitorgalvao commented
You need to rerun the commands every time you update the cask. There are now errors that can be fixed by `brew cask style --fix`.

2016-09-15 18:28 UTC, markthetech commented on Casks/tsprint.rb
> +  uninstall trash: '/Applications/TSPrintClient.app'
Alright that makes sense. I'll add it.

2016-09-15 18:29 UTC, markthetech commented
@vitorgalvao I'll do the style fix. I didn't understand how so thanks for letting me know. This is my first time so I'm a bit new at this.

2016-09-19 19:04 UTC, markthetech commented
Fixed the style problems. Added pkgutil as well. I left trash because without it it will not successfully delete the .app from the applications folder.

2016-09-19 19:06 UTC, merged