Update facebook-ios-sdk to 4.15.1
Homebrew/homebrew-cask pull request #24541
Opened 2016-09-16 12:41 UTC by pvtmert

#### Checklist

- [x] The commit message includes the cask’s name and version.
- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.

2016-09-16 13:03 UTC, vitorgalvao commented
Polluting a user’s `Documents` directory seems wrong. Is there any details about this installation and why it changed?

2016-09-16 13:03 UTC, vitorgalvao commented on Casks/facebook-ios-sdk.rb
> +  url 'https://origincache.facebook.com/developers/resources/?id=facebook-ios-sdk-current.zip'
Is there no versioned URL anymore?

2016-09-16 13:24 UTC, pvtmert commented on Casks/facebook-ios-sdk.rb
> +  url 'https://origincache.facebook.com/developers/resources/?id=facebook-ios-sdk-current.zip'
it seems no, also facebook recommends to put it there, i am updating cask because of yesterdays' discussion on gitter

2016-09-16 13:26 UTC, pvtmert commented on Casks/facebook-ios-sdk.rb
> +  url 'https://origincache.facebook.com/developers/resources/?id=facebook-ios-sdk-current.zip'
btw, if i say `#{ENV['HOME']}/Documents/FacebookSDK` will it create that dir or fails,
according to that i can update

2016-09-16 13:44 UTC, vitorgalvao commented on Casks/facebook-ios-sdk.rb
> +  url 'https://origincache.facebook.com/developers/resources/?id=facebook-ios-sdk-current.zip'
It should fail. Use [`kicad`](https://github.com/caskroom/homebrew-cask/blob/7b96fd2831f381b8e9ec07b980a32788c269b2d2/Casks/kicad.rb) as an example  to deal with that.

2016-09-16 13:44 UTC, vitorgalvao commented on Casks/facebook-ios-sdk.rb
> +  version '4.15.1'
Seeing as `url` doesn’t point to a specific version, this cask should use `version :latest` and `sha256 :no_check`. [See an example](https://github.com/caskroom/homebrew-cask/blob/f25b6babcd398abf48e33af3d887b2d00de1d661/Casks/kibako.rb).

2016-09-17 03:27 UTC, fanquake commented
```
==> 1 modified cask: facebook-ios-sdk
audit for facebook-ios-sdk: passed
>>> brew cask style Casks/facebook-ios-sdk.rb
== Casks/facebook-ios-sdk.rb ==
C: 22:  1: stanza groups should be separated by a single empty line
C: 22:  1: Trailing whitespace detected.
1 file inspected, 2 offenses detected
Error: style check failed
```

2016-09-17 10:48 UTC, vitorgalvao commented on Casks/facebook-ios-sdk.rb
> +  artifact 'AccountKit.framework', target: "#{ENV['HOME']}/Documents/FacebookSDK"
You need to add the artifact’s name at the end, as well (`#{ENV['HOME']}/Documents/FacebookSDK/AccountKit.framework`).

Also test `brew cask install`, to make sure we’re not forgetting anything else.

2016-09-17 10:48 UTC, vitorgalvao requested changes

2016-09-17 12:32 UTC, vitorgalvao commented on Casks/facebook-ios-sdk.rb
> +  preflight do
Stanza order does not affect execution order, but it is [important for style](https://github.com/caskroom/homebrew-cask/tree/c069add7bf974d958416e6bcc364769b378baad1/doc/cask_language_reference#stanza-order)).

2016-09-17 15:56 UTC, vitorgalvao commented on Casks/facebook-ios-sdk.rb
> +  preflight do
You should have left it where it was. It was correct. My point was simply that it had no bearing to execution order, as your commit message suggested.

2016-09-17 15:56 UTC, vitorgalvao approved these changes

2016-09-17 15:57 UTC, merged

2016-09-17 15:57 UTC, vitorgalvao commented
Thank you.