add pibakery (new formula)
Homebrew/homebrew-cask pull request #24551
Opened 2016-09-16 15:20 UTC by kai5263499

### Checklist

- [X] The commit message includes the cask’s name and version.
- [X] `brew cask audit --download {{cask_file}}` is error-free.
- [X] `brew cask style --fix {{cask_file}}` left no offenses.

Additionally, when **adding a new cask**:

- [X] Checked there are no open [pull requests](https://github.com/caskroom/homebrew-cask/pulls) for the same cask.
- [X] Checked there are no closed [issues](https://github.com/caskroom/homebrew-cask/issues) where that cask was already refused.
- [X] When naming the cask, followed the [token reference](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [X] `brew cask install {{cask_file}}` worked successfully.
- [X] `brew cask uninstall {{cask_file}}` worked successfully.

2016-09-16 19:31 UTC, reitermarkus commented on Casks/pibakery.rb
> +  url 'https://github.com/davidferguson/pibakery/releases/download/v0.2.3/PiBakery.pkg'
This needs an [`appcast`](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/appcast.md).

2016-09-16 19:32 UTC, reitermarkus commented on Casks/pibakery.rb
> +  pkg 'PiBakery.pkg'
`pkg` installers should have a corresponding [`uninstall pkgutil`](https://github.com/caskroom/homebrew-cask/blob/15171687a14436e6bde53c3a1111c8602f30e9ae/doc/cask_language_reference/stanzas/uninstall.md#uninstall-pkgutil-is-the-easiest-and-most-useful).

2016-09-16 19:33 UTC, reitermarkus requested changes

2016-09-16 21:46 UTC, kai5263499 commented
I've completed both requests

2016-09-17 03:28 UTC, fanquake commented on Casks/pibakery.rb
> +  url 'https://github.com/davidferguson/pibakery/releases/download/v0.2.3/PiBakery.pkg'
You can also use #{version} in the URL stanza

2016-09-17 12:42 UTC, kai5263499 commented
I've updated the PR to include #{version} in the url stanza

2016-09-17 13:24 UTC, adidalal approved these changes

2016-09-17 13:24 UTC, merged