Added TeamDrive v 4.2.1
Homebrew/homebrew-cask pull request #24649
Opened 2016-09-20 09:14 UTC by franklouwers

### Checklist

- [x] The commit message includes the cask’s name and version.
- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.

Additionally, when **adding a new cask**:

- [x] Checked there are no open [pull requests](https://github.com/caskroom/homebrew-cask/pulls) for the same cask.
- [x] Checked there are no closed [issues](https://github.com/caskroom/homebrew-cask/issues) where that cask was already refused.
- [x] When naming the cask, followed the [token reference](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.

2016-09-20 09:30 UTC, franklouwers commented on Casks/teamdrive.rb
> +            signal: [
this is ugly, but the processes don't stop after running the uninstall script or sending regular term/quit signals

2016-09-20 11:27 UTC, vitorgalvao commented on Casks/teamdrive.rb
> +  version '4.2.1'
`version '4.2.1547'`

2016-09-20 11:28 UTC, vitorgalvao commented on Casks/teamdrive.rb
> +  url 'http://s3download.teamdrive.net.s3.amazonaws.com/4.2.1547/TMDR/mac-10.10.5/Install-TeamDrive-4.2.1.1547_TMDR.dmg'
`url "http://s3download.teamdrive.net.s3.amazonaws.com/#{version}/TMDR/mac-10.10.5/Install-TeamDrive-#{version}_TMDR.dmg"`

2016-09-20 11:29 UTC, vitorgalvao commented on Casks/teamdrive.rb
> +  installer script: 'Install-TeamDrive-4.2.1.1547_TMDR.app/Contents/MacOS/osx-intel',
`installer script: "Install-TeamDrive-#{version}_TMDR.app/Contents/MacOS/osx-intel",`

2016-09-20 11:29 UTC, vitorgalvao requested changes

2016-09-21 15:30 UTC, franklouwers commented
changed to as per @vitorgalvao 's request.

2016-09-21 15:32 UTC, vitorgalvao commented on Casks/teamdrive.rb
> +  # s3download.teamdrive.net.s3.amazonaws.com/4.2.1547/TMDR/mac-10.10.5/Install-TeamDrive-4.2.1.1547_TMDR.dmg was verified as official when first introduced to the cask
This is also too detailed. As it is, it would need to be redone every time, which defeats the purpose of interpolation.

2016-09-21 15:33 UTC, vitorgalvao commented
Thank you for the contribution. It needed some fixes, so they were made in 9f4fdf2166f390db44a56c74374e4cd4f3393a78. Your contribution is still included (and still credited to you), with the appropriate modifications. Please feel free to ask about any of the changes.

2016-09-21 15:33 UTC, closed without merging

2016-09-21 15:34 UTC, franklouwers commented on Casks/teamdrive.rb
> +  # s3download.teamdrive.net.s3.amazonaws.com/4.2.1547/TMDR/mac-10.10.5/Install-TeamDrive-4.2.1.1547_TMDR.dmg was verified as official when first introduced to the cask
"brew cask style" forced me to do that. If I just wrote the s3 hostname, it complained. I had to write the entire url to make cask style happy. Is that a bug?

2016-09-21 15:47 UTC, vitorgalvao commented on Casks/teamdrive.rb
> +  # s3download.teamdrive.net.s3.amazonaws.com/4.2.1547/TMDR/mac-10.10.5/Install-TeamDrive-4.2.1.1547_TMDR.dmg was verified as official when first introduced to the cask
What did you write, exactly? Becuase [this](https://github.com/caskroom/homebrew-cask/blob/0de180ec6df10ad306a10c9494580998d8a2a8b7/Casks/teamdrive.rb#L5) passes fine.