Add FannyWidget 1.0.1 as cask
Homebrew/homebrew-cask pull request #24665
Opened 2016-09-20 22:12 UTC by hwine

### Checklist

- [X] The commit message includes the cask’s name and version.
- [X] `brew cask audit --download {{cask_file}}` is error-free.
- [X] `brew cask style --fix {{cask_file}}` left no offenses.

Additionally, when **adding a new cask**:

- [X] Checked there are no open [pull requests](https://github.com/caskroom/homebrew-cask/pulls) for the same cask.
- [X] Checked there are no closed [issues](https://github.com/caskroom/homebrew-cask/issues) where that cask was already refused.
- [X] When naming the cask, followed the [token reference](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [X] `brew cask install {{cask_file}}` worked successfully.
- [X] `brew cask uninstall {{cask_file}}` worked successfully.

2016-09-20 23:25 UTC, vitorgalvao commented on Casks/fanny.rb
> +  version '1.0.1'
Seeing as `url` doesn’t point to a specific version, this cask should use `version :latest` and `sha256 :no_check`. [See an example](https://github.com/caskroom/homebrew-cask/blob/f25b6babcd398abf48e33af3d887b2d00de1d661/Casks/kibako.rb).

2016-09-20 23:25 UTC, vitorgalvao requested changes

2016-09-23 16:50 UTC, hwine commented on Casks/fanny.rb
> +  version '1.0.1'
However, the 'app' stanza does have to reference the specific version. I'm not familiar enough with ruby to know how to either reference the version in the app stanza, or put a wildcard there.

2016-09-23 17:21 UTC, vitorgalvao commented on Casks/fanny.rb
> +  app 'Fanny 1.0.1/fanny.app'
But here, make it `app "Fanny #{version}/fanny.app"`.

2016-09-23 17:22 UTC, vitorgalvao requested changes

2016-09-23 17:34 UTC, hwine commented on Casks/fanny.rb
> +  app 'Fanny 1.0.1/fanny.app'
Ah, double quotes AND '#' -- thanks!

2016-09-23 18:27 UTC, vitorgalvao commented on Casks/fanny.rb
> +  app 'Fanny 1.0.1/fanny.app'
And we also have [other niceties](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/version.md#version-methods).

2016-09-23 18:27 UTC, vitorgalvao approved these changes

2016-09-23 18:37 UTC, merged