Upgrade Julia to 0.5.0
Homebrew/homebrew-cask pull request #24666
Opened 2016-09-20 22:30 UTC by abcsds

Updated julia cask to version 0.5.0 which came out sep 19

2016-09-20 23:23 UTC, vitorgalvao commented on Casks/julia.rb
> +  # Version 0.5.0 has removed the last 0, for next versions it might be added
Please remove the comment.

2016-09-20 23:24 UTC, vitorgalvao commented on Casks/julia.rb
> +  # Version 0.5.0 has removed the last 0, for next versions it might be added
Please remove the comment.

2016-09-20 23:25 UTC, vitorgalvao commented on Casks/julia.rb
> +  app "Julia-#{version.sub(%r{\.\d+$}, '')}.app"
Use `#{version.major_minor}` instead.

2016-09-20 23:25 UTC, vitorgalvao commented on Casks/julia.rb
> +  binary "#{appdir}/Julia-#{version.sub(%r{\.\d+$}, '')}.app/Contents/Resources/julia/bin/julia"
Use `#{version.major_minor}` instead.

2016-09-20 23:25 UTC, vitorgalvao requested changes

2016-09-21 00:01 UTC, abcsds commented
Ready,
Thanks for the tips :)

2016-09-21 08:56 UTC, vitorgalvao commented
There are now conflicts with the branch.

2016-09-21 08:57 UTC, vitorgalvao approved these changes

2016-09-22 00:14 UTC, adidalal commented
Thank you for the contribution. It needed some fixes, so they were made in caf836e0934f98a22970b2a00df93dff7fff911f. Your contribution is still included (and still credited to you), with the appropriate modifications. Please feel free to ask about any of the changes.

2016-09-22 00:14 UTC, closed without merging