Add Logos Bible Software 6.14.0.65
Homebrew/homebrew-cask pull request #24705
Opened 2016-09-21 20:04 UTC by ickc

- [x] The commit message includes the cask’s name and version.
- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] Checked there are no open [pull requests](https://github.com/caskroom/homebrew-cask/pulls) for the same cask.
- [x] Checked there are no closed [issues](https://github.com/caskroom/homebrew-cask/issues) where that cask was already refused.
- [x] When naming the cask, followed the [token reference](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.

2016-09-21 21:51 UTC, vitorgalvao commented on Casks/logos-bible-software.rb
> +cask 'logos-bible-software' do
The token reference was not followed. This needs to be `logos`.

2016-09-21 21:51 UTC, vitorgalvao requested changes

2016-09-21 21:51 UTC, vitorgalvao commented on Casks/logos-bible-software.rb
> +  version '6.14.0.65'
Seeing as `url` doesn’t point to a specific version, this cask should use `version :latest` and `sha256 :no_check`. [See an example](https://github.com/caskroom/homebrew-cask/blob/f25b6babcd398abf48e33af3d887b2d00de1d661/Casks/kibako.rb).

2016-09-21 21:51 UTC, vitorgalvao requested changes

2016-09-21 22:47 UTC, ickc commented on Casks/logos-bible-software.rb
> +cask 'logos-bible-software' do
Sorry I misunderstand it.

The one in the dmg is `Logos.app`, but the installed app is called `Logos Bible Software 6.app`. And I thought "logos" is too generic and people would thought it is the plural form of the English word logo, where there's another software named as logo which design logo. Rather, "logos" is a transliteration of "λόγος".

Anyway, I'm changing it to logos if you think that's right.

2016-09-21 22:50 UTC, ickc commented on Casks/logos-bible-software.rb
> +  version '6.14.0.65'
Done and thanks

2016-09-22 08:03 UTC, vitorgalvao approved these changes

2016-09-22 08:03 UTC, merged