Add maxiang.app Latest
Homebrew/homebrew-cask pull request #24734
Opened 2016-09-22 17:47 UTC by filosfino

### Checklist

- [x] The commit message includes the cask’s name and version.
- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.

- [x] Checked there are no open [pull requests](https://github.com/caskroom/homebrew-cask/pulls) for the same cask.
- [x] Checked there are no closed [issues](https://github.com/caskroom/homebrew-cask/issues) where that cask was already refused.
- [x] When naming the cask, followed the [token reference](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.

2016-09-22 18:37 UTC, vitorgalvao commented on Casks/maxiang.rb
> +  version ':latest'
`version :latest` (no quotes).

2016-09-22 18:38 UTC, vitorgalvao commented on Casks/maxiang.rb
> +  sha256 'ba9f2f32bc6c68ac732d0131d1e2a74aae2125a44012a0f6c1e975f7a4676419'
`sha256 :no_check` (always accompanies `version :latest`).

2016-09-22 18:39 UTC, vitorgalvao commented on Casks/maxiang.rb
> +  url 'https://github.com/filosfino/apps/raw/master/Maxiang.dmg'
Can you point me to this link on the homepage?

2016-09-22 18:40 UTC, vitorgalvao commented on Casks/maxiang.rb
> +  name 'maxiang'
Also needs the original name. See [docs](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/name.md).

2016-09-22 18:40 UTC, vitorgalvao requested changes

2016-09-23 05:31 UTC, filosfino commented on Casks/maxiang.rb
> +  url 'https://github.com/filosfino/apps/raw/master/Maxiang.dmg'
u mean the repo url on github? that is https://github.com/filosfino/apps

2016-09-23 05:34 UTC, filosfino commented on Casks/maxiang.rb
> +  name 'maxiang'
Does it has to be in utf-8? Can chinese characters be in here?

2016-09-23 08:36 UTC, vitorgalvao commented on Casks/maxiang.rb
> +  name 'maxiang'
Yes, just like you have in `app`. Make it one “english” and one original.

2016-09-23 08:36 UTC, vitorgalvao commented on Casks/maxiang.rb
> +  url 'https://github.com/filosfino/apps/raw/master/Maxiang.dmg'
I still need this, to verify the link

2016-09-23 09:17 UTC, filosfino commented on Casks/maxiang.rb
> +  url 'https://github.com/filosfino/apps/raw/master/Maxiang.dmg'
> Can you point me to this link on the homepage?

What do you mean by that?

2016-09-23 09:19 UTC, filosfino commented on Casks/maxiang.rb
> +  name 'maxiang'
How about this?
```
  name '马克飞象'
  name 'marxico'
  name 'maxiang'
```

2016-09-23 09:22 UTC, filosfino commented on Casks/maxiang.rb
> +  url 'https://github.com/filosfino/apps/raw/master/Maxiang.dmg'
If you mean the repo home page, that is:
https://github.com/filosfino/apps

2016-09-23 09:30 UTC, vitorgalvao commented on Casks/maxiang.rb
> +  url 'https://github.com/filosfino/apps/raw/master/Maxiang.dmg'
No, I mean that from the homepage I can’t see any proof this download link or that repo are in any way official. I need some detail on the page that makes it clear.

2016-09-23 09:31 UTC, vitorgalvao commented on Casks/maxiang.rb
> +  name 'maxiang'
Make it just

```ruby
name 'maxiang'
name '马克飞象'
```

2016-09-23 09:39 UTC, filosfino commented on Casks/maxiang.rb
> +  url 'https://github.com/filosfino/apps/raw/master/Maxiang.dmg'
I see. Here's the senario, I'm just a user of the app.
Guess what I can do is asking the author to provide an official link?

2016-09-23 09:44 UTC, vitorgalvao commented on Casks/maxiang.rb
> +  homepage 'https://github.com/filosfino/apps/raw/master/Maxiang.dmg'
This is not a homepage.

2016-09-23 09:44 UTC, vitorgalvao requested changes

2016-09-23 09:45 UTC, vitorgalvao commented on Casks/maxiang.rb
> +  url 'https://github.com/filosfino/apps/raw/master/Maxiang.dmg'
We can’t accept non-official links. It’s a security risk for users, and they need to trust the source. We need the homepage to provide and official link.

2016-09-23 09:45 UTC, closed without merging