Add iTeleport Connect.app v6.0.0.2 Cask
Homebrew/homebrew-cask pull request #24796
Opened 2016-09-23 23:38 UTC by Saklad5

### Instructions

Delete the parts of this template that are not relevant (including these `Instructions`) and fill out the rest.  
If there’s a checkbox you can’t complete for any reason, that’s OK. Just explain in detail why you weren’t able to do so.  
*Note:* `{{cask_file}}` represents the cask file you’re submitting/editing.

### Checklist

- [x] The commit message includes the cask’s name and version.
- [x] `brew cask audit —download {{cask_file}}` is error-free.
- [x] `brew cask style —fix {{cask_file}}` left no offenses.

Additionally, when **adding a new cask**:

- [x] Checked there are no open [pull requests](https://github.com/caskroom/homebrew-cask/pulls) for the same cask.
- [x] Checked there are no closed [issues](https://github.com/caskroom/homebrew-cask/issues) where that cask was already refused.
- [x] When naming the cask, followed the [token reference](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.

2016-09-24 07:32 UTC, vitorgalvao commented on Casks/iteleport-connect.rb
> +  name 'iTeleport Connect For Mac'
Keep this one. Remove the other two. See [docs](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/name.md) as to why.

2016-09-24 07:33 UTC, vitorgalvao requested changes

2016-09-24 12:37 UTC, vitorgalvao approved these changes

2016-09-24 12:37 UTC, vitorgalvao approved these changes
Can be merged as is if Travis passes, if there are no changes after this approval.

2016-09-24 12:38 UTC, vitorgalvao commented on Casks/iteleport-connect.rb
> +  auto_updates 'true'
This should be a boolean, not a string (`auto_updates true`).

2016-09-24 12:38 UTC, vitorgalvao requested changes

2016-09-24 12:39 UTC, vitorgalvao commented
Thank you for the contribution. It needed some fixes, so they were made in 4b310793dd093d537699352bb6d3742fabb9579f. Your contribution is still included (and still credited to you), with the appropriate modifications. Please feel free to ask about any of the changes.

2016-09-24 12:39 UTC, closed without merging

2016-09-24 12:39 UTC, Saklad5 commented on Casks/iteleport-connect.rb
> +  auto_updates 'true'
“brew style” and the rest didn’t change it.

2016-09-24 12:40 UTC, vitorgalvao commented on Casks/iteleport-connect.rb
> +  auto_updates 'true'
> “brew style” and the rest didn’t change it.

Doesn’t mean it shouldn’t be changed. That’s why we have manual reviews.

2016-09-24 13:04 UTC, vitorgalvao commented on Casks/iteleport-connect.rb
> +  auto_updates 'true'
Added a [report](https://github.com/caskroom/rubocop-cask/issues/34) on this.

2016-10-30 18:11 UTC, Saklad5 commented
Could we remove the “awaiting user reply” tag from this?

2016-10-30 18:13 UTC, vitorgalvao commented
@Saklad5 Sure, if you want, but once an issue is closed, we don’t really care and usually leave the tags.