Update mucommander.rb
Homebrew/homebrew-cask pull request #24806
Opened 2016-09-24 06:53 UTC by citydweller1985

Changed to new download URL

2016-09-24 07:25 UTC, vitorgalvao commented
There was a [pull request template](https://github.com/blog/2111-issue-and-pull-request-templates) when you submitted. It must be filled.

If you were not presented a template, you may have submitted via a CLI tool (likely [`hub`](https://hub.github.com/)). It that was the case, you may wish to see if the tool has a way to let you use the template (`hub` [is working on it](https://github.com/github/hub/issues/1118)).

In either case, please [refer to the template](https://raw.githubusercontent.com/caskroom/homebrew-cask/master/.github/PULL_REQUEST_TEMPLATE.md) and update your comment.

2016-09-24 07:25 UTC, vitorgalvao commented on Casks/mucommander.rb
> +  url "https://github.com/mucommander/mucommander/releases/download/{version}/mucommander-#{version.dots_to_underscores}.dmg"
Please add an [`appcast`](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/appcast.md).

2016-09-24 07:25 UTC, vitorgalvao commented on Casks/mucommander.rb
> +  url "https://github.com/mucommander/mucommander/releases/download/{version}/mucommander-#{version.dots_to_underscores}.dmg"
The cause of the failing build you’ll see after you run the commands in the template.

2016-09-24 07:25 UTC, vitorgalvao requested changes

2016-09-25 18:09 UTC, adidalal commented
Thank you for the contribution. It needed some fixes, so they were made in c82db7893d08e93a5d89cb06eceace3d9532e3e0. Your contribution is still included (and still credited to you), with the appropriate modifications. Please feel free to ask about any of the changes.

2016-09-25 18:09 UTC, closed without merging