Update URL of TuneInstructor v3.6
Homebrew/homebrew-cask pull request #24838
Opened 2016-09-25 12:24 UTC by spookey

### Checklist

- [x] The commit message includes the cask’s name and version.
- [x] `brew cask audit --download tuneinstructor` is error-free.
- [x] `brew cask style --fix tuneinstructor` left no offenses.

I decided to open a new request instead of appending to #24836 
The real issue here was a change in the download URL.

2016-09-25 14:34 UTC, vitorgalvao commented on Casks/tuneinstructor.rb
>    version '3.6'
Seeing as `url` doesn’t point to a specific version, this cask should use `version :latest` and `sha256 :no_check`. [See an example](https://github.com/caskroom/homebrew-cask/blob/f25b6babcd398abf48e33af3d887b2d00de1d661/Casks/kibako.rb).

2016-09-25 14:34 UTC, vitorgalvao requested changes

2016-09-25 18:15 UTC, adidalal commented
Got the versioned URL - `https://www.tune-instructor.de/resources/downloads/TuneInstructor3.6.dmg`

2016-09-26 00:57 UTC, closed without merging

2016-09-26 09:06 UTC, spookey commented
@adidalal the versioned url you mentioned has thrown me some "This Version only supports OS X 10.10 (Yosemite)." error yesterday.
Very strange.

I am very sorry about the mess, I created here, and very happy to see, the problem is fixed already (in #24865).