Create cask for 'ungoogled-chromium'
Homebrew/homebrew-cask pull request #24969
Opened 2016-09-28 19:31 UTC by Git-Jiro

### Instructions

Delete the parts of this template that are not relevant (including these `Instructions`) and fill out the rest.  
If there’s a checkbox you can’t complete for any reason, that’s OK. Just explain in detail why you weren’t able to do so.  
*Note:* `{{cask_file}}` represents the cask file you’re submitting/editing.

### Checklist

- [ ] The commit message includes the cask’s name and version.
- [ ] `brew cask audit --download {{cask_file}}` is error-free.
- [ ] `brew cask style --fix {{cask_file}}` left no offenses.

Additionally, when **adding a new cask**:

- [ ] Checked there are no open [pull requests](https://github.com/caskroom/homebrew-cask/pulls) for the same cask.
- [ ] Checked there are no closed [issues](https://github.com/caskroom/homebrew-cask/issues) where that cask was already refused.
- [ ] When naming the cask, followed the [token reference](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.

2016-09-28 21:28 UTC, reitermarkus requested changes

2016-09-28 21:28 UTC, reitermarkus commented on Casks/ungoogled-chromium.rb
> +  url 'https://github.com/Eloston/ungoogled-chromium/releases/download/53.0.2785.116-1.2/ungoogled-chromium_53.0.2785.116-1.2_macos.dmg'
This needs an [`appcast`](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/appcast.md).

2016-09-30 20:49 UTC, vitorgalvao commented
As per the token reference, this should be `eloston-chromium`.

> Details of software names and brands will inevitably be lost in the conversion to a minimal token. To capture the vendor’s full name for a distribution, use the [`name`](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/name.md) within a Cask. `name` accepts an unrestricted UTF-8 string.

Though on this particular case, I was a bit ambivalente if it wasn’t worthy of an exception. I leaned towards “no”, though. This had a (somewhat) meteoric rise, but I wonder for its future. As I’ve seen pointed out, trading known evil (Google) for binaries made by an unknown third party is a dubious move. It’s not a bad idea, though, and it’s conceivable other projects like this might pop up in the future. Rather than treat “Ungoogled Chromium” as something special due to a catchy name (not saying this in a bad way), we should treat this as just another fork, just like [`freesmug-chromium`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/freesmug-chromium.rb), because in the end, that’s what it is.

2016-10-01 08:14 UTC, vitorgalvao requested changes

2016-10-01 08:14 UTC, vitorgalvao commented on Casks/eloston-chromium.rb
> +  name 'Ungoogled Chromium by Eloston'
No need for the `by Eloston`. This is a place for the name the developer gives to the app, however they choose to name it.

2016-10-01 14:49 UTC, adidalal approved these changes

2016-10-01 14:50 UTC, merged

2016-10-02 06:40 UTC, chovy commented
Not sure what I'm doing wrong.

```
$ brew search ungoogled-chromium
No formula found for "ungoogled-chromium".
==> Searching pull requests...
```

2016-10-02 06:54 UTC, reitermarkus commented
> Rather than treat “Ungoogled Chromium” as something special due to a catchy name (not saying this in a bad way), we should treat this as just another fork, just like freesmug-chromium, because in the end, that’s what it is.

It was added as `eloston-chromium`.