Update usb-overdrive to 3.3
Homebrew/homebrew-cask pull request #24973
Opened 2016-09-28 22:10 UTC by AlexandreBouffard

### Checklist

- [x] The commit message includes the cask’s name and version.
- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.

2016-09-28 23:38 UTC, reitermarkus commented on Casks/usb-overdrive.rb
> +  url "http://www.usboverdrive.com/download/USB-Overdrive-#{version.no_dots}.dmg"
Do the old versions still work with this URL?

2016-09-29 00:14 UTC, vitorgalvao requested changes

2016-09-29 00:14 UTC, vitorgalvao commented on Casks/usb-overdrive.rb
> +  elsif MacOS.version < :mavericks
Make it `<= :mountain_lion`. We prefer these to be inclusive.

2016-09-29 00:38 UTC, AlexandreBouffard commented on Casks/usb-overdrive.rb
> +  url "http://www.usboverdrive.com/download/USB-Overdrive-#{version.no_dots}.dmg"
Yes tested all 3 URLs.

2016-09-29 00:38 UTC, AlexandreBouffard commented on Casks/usb-overdrive.rb
> +  elsif MacOS.version < :mavericks
Done.

2016-09-29 02:29 UTC, merged

2016-09-29 02:29 UTC, reitermarkus commented
Thanks!