Added Exponent XDE.app v2.8.0
Homebrew/homebrew-cask pull request #24981
Opened 2016-09-29 03:04 UTC by adamo57

*Note:* `{{cask_file}}` represents the cask file you’re submitting/editing.

### Checklist

- [x] The commit message includes the cask’s name and version.
- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.

Additionally, when **adding a new cask**:

- [x] Checked there are no open [pull requests](https://github.com/caskroom/homebrew-cask/pulls) for the same cask.
- [x] Checked there are no closed [issues](https://github.com/caskroom/homebrew-cask/issues) where that cask was already refused.
- [x] When naming the cask, followed the [token reference](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.

2016-09-29 03:51 UTC, reitermarkus requested changes

2016-09-29 03:51 UTC, reitermarkus commented on Casks/exponent-xde.rb
> +  url 'xde-updates.exponentjs.com/download/mac'
Leave the URL scheme here in place.

2016-09-29 03:51 UTC, reitermarkus commented on Casks/exponent-xde.rb
> +  # xde-updates.exponentjs.com/download/mac was verified as official when first introduced to the cask
`xde-updates.exponentjs.com` is enough here, maybe even `exponentjs.com`, as it seems to belong to the same vendor.

2016-09-29 14:40 UTC, reitermarkus requested changes

2016-09-29 14:40 UTC, reitermarkus commented on Casks/exponent-xde.rb
> +  # exponentjs.com/download/mac was verified as official when first introduced to the cask
Only the [identifying part of the URL](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/url.md#when-url-and-homepage-hostnames-differ-add-a-comment) is needed for this comment, so you can strip `/download/mac`.

2016-10-01 00:55 UTC, reitermarkus requested changes

2016-10-01 00:55 UTC, reitermarkus commented on Casks/exponent-xde.rb
> +  sha256 'a9eb36f75a9f971afc923e0866b7359e33d7409bbfdfa9e5715d0213d7749ff8'
Since the URL is unversioned, use:

```ruby
version :latest
sha256 :no_check
```

2016-10-01 05:41 UTC, reitermarkus approved these changes

2016-10-01 05:41 UTC, merged

2016-10-01 05:41 UTC, reitermarkus commented
Thanks!

2018-01-29 17:29 UTC, radixhound commented
If anyone stumbles upon this issue and tries to use the info here, the cask is now called `expo-xde`