Android Studio 2.2 no longer depends on Java
Homebrew/homebrew-cask pull request #24982
Opened 2016-09-29 03:34 UTC by paramaggarwal

> As of Android Studio 2.2, the IDE comes bundled with a custom OpenJDK build which contains a bunch of additional fixes to make the IDE work better (such as improved font rendering).

(from http://tools.android.com/tech-docs/configuration/osx-jdk)

2016-09-29 04:25 UTC, reitermarkus requested changes

2016-09-29 04:25 UTC, reitermarkus commented on Casks/android-studio.rb
You need to remove this empty line, too.

2016-09-29 10:08 UTC, vitorgalvao commented
There was a [pull request template](https://github.com/blog/2111-issue-and-pull-request-templates) when you submitted. It must be filled.

If you were not presented a template, you may have submitted via a CLI tool (likely [`hub`](https://hub.github.com/)). It that was the case, you may wish to see if the tool has a way to let you use the template (`hub` [is working on it](https://github.com/github/hub/issues/1118)).

The template has useful and necessary for you to run for the build not to fail (in this case, it’s the empty line @reitermarkus mentioned).

2016-09-30 03:56 UTC, paramaggarwal commented on Casks/android-studio.rb
👍

2016-09-30 03:57 UTC, paramaggarwal commented
Thanks for the review @reitermarkus and thanks for the note about PR template @vitorgalvao. I'll take care of this. I have updated the current PR as per the template. Please check. Thanks again.

2016-09-30 04:13 UTC, reitermarkus approved these changes

2016-09-30 04:13 UTC, merged