update wechat-web-devtools to 0.9.092300
Homebrew/homebrew-cask pull request #25017
Opened 2016-09-29 15:59 UTC by RobberPhex

- [x] Commit message includes cask’s name and new version
- [x] `brew cask audit --download Casks/wechat-web-devtools.rb` is error-free.
- [x] `brew cask style --fix Casks/wechat-web-devtools.rb` left no offenses.

2016-09-29 23:57 UTC, reitermarkus requested changes

2016-09-29 23:57 UTC, reitermarkus commented on Casks/wechat-web-devtools.rb
> +  url "http://dldir1.qq.com/WechatWebDev/mina/20160923/wechat_web_devtools_#{version}.dmg"
Use `version '0.9.092300,20160923'` above, and `version.before_comma` and `version.after_comma` here instead of hard-coding the date.

2016-09-30 00:35 UTC, RobberPhex commented
@reitermarkus done

2016-09-30 00:43 UTC, reitermarkus approved these changes

2016-09-30 15:20 UTC, merged