Update rawtherapee to 4.2.1025
Homebrew/homebrew-cask pull request #25020
Opened 2016-09-29 16:53 UTC by frhgit

#### Checklist

- [x] The commit message includes the cask’s name and version.
- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.

2016-09-29 17:02 UTC, vitorgalvao commented
Thank you.

2016-09-29 17:02 UTC, vitorgalvao approved these changes

2016-09-29 17:19 UTC, reitermarkus requested changes

2016-09-29 17:19 UTC, reitermarkus commented on Casks/rawtherapee.rb
> +    container nested: "RawTherapee_OSX_10.11_64_#{version}.dmg"
This should be `"RawTherapee_OSX_10.11_64_#{version}/RawTherapee_OSX_10.11_64__.dmg"`.

2016-09-29 17:21 UTC, reitermarkus commented on Casks/rawtherapee.rb
> +    container nested: "RawTherapee_OSX_10.11_64_#{version}.dmg"
Also, could you move the `container` stanzas to the `if` statement above?

2016-09-29 17:43 UTC, frhgit commented on Casks/rawtherapee.rb
> +    container nested: "RawTherapee_OSX_10.11_64_#{version}.dmg"
I would to those changes with pleasure, but I have no clue how to that. In short I have never used github :/

2016-09-29 20:24 UTC, frhgit commented on Casks/rawtherapee.rb
> +    container nested: "RawTherapee_OSX_10.11_64_#{version}.dmg"
Thank you.
Tell me if you are ok with the last change

2016-09-29 20:55 UTC, reitermarkus requested changes

2016-09-29 20:55 UTC, reitermarkus commented on Casks/rawtherapee.rb
> -  else
You accidentally deleted the else clause here. Either add this back or move all of the `container nested` lines in the respective branches of the existing `if` statement above.

2016-09-30 18:52 UTC, reitermarkus approved these changes

2016-09-30 18:52 UTC, merged