Add lightkey 1.6.2.
Homebrew/homebrew-cask pull request #25077
Opened 2016-10-01 05:17 UTC by knpwrs

http://lightkeyapp.com/en/

Please note that the package also installs `com.FTDI.ftdiusbserialdriverinstaller.FTDIUSBSerialDriver.pkg`, however, this is used by other lighting software so I didn't want to add it to the uninstall clause. Maybe a comment in `lightkey.rb` would be appropriate?

### Checklist

- [x] The commit message includes the cask’s name and version.
- [x] `brew cask audit --download lightkey` is error-free.
- [x] `brew cask style --fix lightkey` left no offenses.

Additionally, when **adding a new cask**:

- [x] Checked there are no open [pull requests](https://github.com/caskroom/homebrew-cask/pulls) for the same cask.
- [x] Checked there are no closed [issues](https://github.com/caskroom/homebrew-cask/issues) where that cask was already refused.
- [x] When naming the cask, followed the [token reference](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] `brew cask install lightkey` worked successfully.
- [x] `brew cask uninstall lightkey` worked successfully.

2016-10-01 05:45 UTC, reitermarkus requested changes

2016-10-01 05:45 UTC, reitermarkus commented on Casks/lightkey.rb
> +  url "http://lightkeyapp.com/content/06-download/Lightkey-#{version.major}-#{version.minor}-#{version.patch}/LightkeyInstaller.zip"
You can use `version.dots_to_hyphens` here.

2016-10-01 05:49 UTC, knpwrs commented on Casks/lightkey.rb
> +  url "http://lightkeyapp.com/content/06-download/Lightkey-#{version.major}-#{version.minor}-#{version.patch}/LightkeyInstaller.zip"
All set.

2016-10-01 14:25 UTC, merged

2016-10-01 15:00 UTC, knpwrs commented
Would we like to add a note about not uninstalling `com.FTDI.ftdiusbserialdriverinstaller.FTDIUSBSerialDriver.pkg`? That's the standard driver used by most (all?) lighting software.

2016-10-01 15:08 UTC, adidalal commented
Not sure what the right place for that would be, maybe @vitorgalvao has an opinion?

I'd be fine with it in the uninstall section, as another entry in the uninstall: pkgutil....

`# com.FTDI.ftdiusbserialdriverinstaller.FTDIUSBSerialDriver is used by other lighting software`

2016-10-01 23:28 UTC, knpwrs commented
Looks like that package is actually available standalone as a cask: https://github.com/caskroom/homebrew-cask/blob/6759c4427a303631c52bd401364e93d15f17db31/Casks/ftdi-vcp-driver.rb

2016-10-02 08:20 UTC, vitorgalvao commented
[The place for it is the `zap` stanza](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/zap.md):

> `zap` stanzas may remove:
> (…)
> Shared resources such as application updaters. Since shared resources may be removed, other applications may be affected by `brew cask zap`. Understanding that is the responsibility of the end user.

2016-10-02 20:00 UTC, knpwrs commented
Side note, when I first saw the `zap` command I thought it was just a regular uninstall. Probably because I was an [App Zapper](https://www.appzapper.com/) user prior to installing most software with Cask.

I'll open a PR to get that package in the zap stanza.