Repair provided apps and scripts for launching j 804
Homebrew/homebrew-cask pull request #25084
Opened 2016-10-01 14:26 UTC by 00dani

According to the readme.txt shipped with the J release, a J installation should add to PATH four commands: `jbrk`, `jcon`, `jhs`, and `jqt`. However none of these were being added to PATH previously, although `jcon` was available under the alternative name `jconsole`. This pull req adds the four specified binaries, preserving the original `jconsole` symlink for compatibility reasons.

Additionally, J provides four .app bundles which launch the four commands mentioned above. These all worked using relative paths, which means that when homebrew-cask moved them into /Applications they all broke. I have added a postflight section which updates the .app bundles on the fly, so that they use an absolute path and therefore work correctly again.

Finally I have added an installer stanza which invokes the `updatejqt.sh` script provided in the J distribution. This is required for jqt to work and indeed for homebrew-cask to generate a symlink to it properly. As this step takes a substantial amount of additional installation time, and jqt is far from required for working in J, I'd suggest we consider making jqt optional if possible. (If jqt is not required, then the script needn't run and neither the jqt command nor jqt.app need be installed.)

### Checklist

- [x] The commit message includes the cask’s name and version. (Note that these issues were *not* caused by the upgrade to J804; the J802 cask had all the same problems.)
- [x] `brew cask audit --download j` is error-free.
- [x] `brew cask style --fix j` left no offenses.

2016-10-01 14:39 UTC, adidalal commented
First off, thanks for submitting this detailed PR - I personally don't have experience with (or a use case for) J, so you're really helping out other J users.

Unfortunately, Homebrew Cask doesn't have option flags, so having `jqt` be optional is not possible.

However, it looks like J distributes a `jqt` included `.dmg`, as I posted on gitter, so that might be a better starting point rather than shelling out to `updatejqt.sh`

Will leave this unmerged for other maintainers to also take a look

2016-10-01 16:51 UTC, reitermarkus requested changes

2016-10-01 16:51 UTC, reitermarkus commented on Casks/j.rb
> +    FileUtils.ln_sf "#{@cask.appdir}/jqt.app/Contents/MacOS/apprun", "#{Hbc.binarydir}/jqt"
You can put this to the binaries above like:
```ruby
binary "#{appdir}/jqt.app/Contents/MacOS/apprun", target: 'jqt'`
```

2016-10-01 16:51 UTC, reitermarkus commented on Casks/j.rb
> +  installer sudo: false, script: "j64-#{version}/updatejqt.sh"
```ruby
installer script: "j64-#{version}/updatejqt.sh",
          sudo:   false
```

2016-10-01 16:51 UTC, reitermarkus commented on Casks/j.rb
> +      File.write "#{@cask.appdir}/#{a}.app/Contents/MacOS/apprun", <<-EOF.gsub(%r{^ +}, '')
Use only `appdir`, not `@cask.appdir`.

2016-10-01 16:51 UTC, reitermarkus commented on Casks/j.rb
> +          #{'open' if cli} "#{@cask.staged_path}/j64-#{version}/bin/#{command}"
Use only `staged_path `, not `@cask.staged_path` and `#{cli ? 'open ' : ''}`.

2016-10-01 16:53 UTC, reitermarkus requested changes

2016-10-01 16:53 UTC, reitermarkus commented on Casks/j.rb
> +      command = a == 'jcon' ? 'jconsole' : a + '.command'
Not sure if this should be

```ruby
a == 'jcon' ? 'jconsole' : (a + '.command')
```

or 

```ruby
(a == 'jcon' ? 'jconsole' : a) + '.command'
```

2016-10-02 01:28 UTC, 00dani commented on Casks/j.rb
> +          #{'open' if cli} "#{@cask.staged_path}/j64-#{version}/bin/#{command}"
You want to `open` the CLI ones so that MacOS opens a terminal to show them in. Remember, all of these are .app bundles - they'll be launched from the GUI and there won't be a terminal available.

2016-10-02 02:06 UTC, 00dani commented
Just pushed a commit addressing @reitermarkus's change requests. I'm… not sure how to tell GitHub that I've done that?

2016-10-02 02:32 UTC, reitermarkus commented
> I'm… not sure how to tell GitHub that I've done that?

You can't yourself, maintainers have an “Approve changes” button for that.

2016-10-02 03:57 UTC, reitermarkus requested changes

2016-10-02 03:57 UTC, reitermarkus commented on Casks/j.rb
> +  postflight do
Ok, I tinkered a bit with this. Replace the whole `postflight` block with:

```ruby
  postflight do
    # use `readlink` to get full path of symlinked commands
    commands.each do |c|
      command = "#{staged_path}/j64-#{version}/bin/#{c}.command"
      IO.write command, IO.read(command).gsub('$0', '$(readlink "$0")')
    end

    # fix relative paths inside App bundles
    apps.each do |a|
      apprun = "#{appdir}/#{a}.app/Contents/MacOS/apprun"
      IO.write apprun, IO.read(apprun).gsub(%r{`dirname "\$0"`.*?/bin}, "#{staged_path}/j64-#{version}/bin")
    end
  end
```

2016-10-02 03:57 UTC, reitermarkus requested changes

2016-10-02 03:57 UTC, reitermarkus commented on Casks/j.rb
> +  binary "#{appdir}/jqt.app/Contents/MacOS/apprun", target: 'jqt'
You can also get rid of this line if you replace the `postflight` block.

2016-10-02 04:30 UTC, 00dani commented on Casks/j.rb
> +  postflight do
`readlink` prints nothing if its argument is *not* a symbolic link, which means the app bundles don't work since they don't point to the symlink. Using `$(readlink "$0" || echo "$0")` appears to work however, so I'm gonna do that.

2016-10-02 04:34 UTC, reitermarkus commented on Casks/j.rb
> +  postflight do
> readlink prints nothing if its argument is not a symbolic link.

Didn't know that, good to know. It seems like `realpath` does what we need, though.

2016-10-02 04:36 UTC, 00dani commented on Casks/j.rb
> +  postflight do
`realpath` does what we need, yes, but `realpath` is a GNU coreutils command so it might not be available on the system. `readlink` however is available on standard MacOS.

2016-10-02 04:37 UTC, 00dani commented on Casks/j.rb
> +  postflight do
I'd be surprised if anyone using Homebrew *hasn't* installed GNU coreutils, but it's possible!

2016-10-02 04:38 UTC, reitermarkus commented on Casks/j.rb
> +  # that jconsole is available under the name jcon. Just provide both names.
You could probably use a single `# target names according to readme.txt` comment for all the `binary` stanzas.

2016-10-02 04:42 UTC, reitermarkus commented on Casks/j.rb
> +  postflight do
Hah, right!

```
/usr/local/opt/coreutils/libexec/gnubin/realpath
```

We'll leave it at `$(readlink "$0" || echo "$0")` then.

2016-10-02 04:44 UTC, reitermarkus commented on Casks/j.rb
> +  postflight do
Although let's hard-code `/usr/bin/readlink` to always use the system one.

2016-10-02 04:50 UTC, 00dani commented on Casks/j.rb
> +  # that jconsole is available under the name jcon. Just provide both names.
Sure thing. We do still need two loops though, since `jconsole` doesn't have a `.command` suffix like the others do.

2016-10-02 05:36 UTC, reitermarkus approved these changes

2016-10-02 05:37 UTC, merged

2016-10-02 05:37 UTC, reitermarkus commented
Thanks!