Add cmd-eikana 1.1.1
Homebrew/homebrew-cask pull request #25097
Opened 2016-10-02 04:32 UTC by holidayworking

### Checklist

- [x] The commit message includes the cask’s name and version.
- [x] `brew cask audit --download cmd-eikana` is error-free.
- [x] `brew cask style --fix cmd-eikana` left no offenses.
- [x] Checked there are no open [pull requests](https://github.com/caskroom/homebrew-cask/pulls) for the same cask.
- [x] Checked there are no closed [issues](https://github.com/caskroom/homebrew-cask/issues) where that cask was already refused.
- [x] When naming the cask, followed the [token reference](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] `brew cask install cmd-eikana` worked successfully.
- [x] `brew cask uninstall cmd-eikana` worked successfully.

2016-10-02 08:03 UTC, vitorgalvao requested changes

2016-10-02 08:03 UTC, vitorgalvao commented on Casks/cmd-eikana.rb
> +  name 'cmd-eikana'
[The original name also needs to be included](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/name.md).

2016-10-02 09:23 UTC, holidayworking commented on Casks/cmd-eikana.rb
> +  name 'cmd-eikana'
fixed.

2016-10-02 09:44 UTC, vitorgalvao commented on Casks/cmd-eikana.rb
> +  name 'cmd-eikana'
It **also** needs to be included, **both**. See the linked documentation.

2016-10-04 01:04 UTC, holidayworking commented on Casks/cmd-eikana.rb
> +  name 'cmd-eikana'
Sorry, I added latin alphabet name.

2016-10-04 09:56 UTC, merged