Devonagent pro
Homebrew/homebrew-cask pull request #25122
Opened 2016-10-03 00:37 UTC by nbsantos

### Checklist

- [x] The commit message includes the cask’s name and version.
- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.

Additionally, when **adding a new cask**:

- [x] Checked there are no open [pull requests](https://github.com/caskroom/homebrew-cask/pulls) for the same cask.
- [x] Checked there are no closed [issues](https://github.com/caskroom/homebrew-cask/issues) where that cask was already refused.
- [x] When naming the cask, followed the [token reference](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.

2016-10-03 02:20 UTC, adidalal commented on Casks/devonagent-pro.rb
> +  # amazonaws.com/DTWebsiteSupport was verified as official when first introduced to the cask
Should be `s3.amazonaws.com/DTWebsiteSupport`

2016-10-03 02:20 UTC, adidalal commented on Casks/devonagent-pro.rb
> +  app 'DEVONagent.app', target: 'DEVONagent Pro.app'
Why the rename - is it possible to have multiple versions installed at the same time?

2016-10-03 09:45 UTC, vitorgalvao requested changes

2016-10-03 09:45 UTC, vitorgalvao commented on Casks/devonagent-pro.rb
> +  app 'DEVONagent.app', target: 'DEVONagent Pro.app'
Every rename **must** have [a commented reason using a standardised comment](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/app.md#target-should-only-be-used-in-select-cases).

[`devonthink-pro-office`](https://github.com/caskroom/homebrew-cask/blob/801219f8a3457ec1fba46038270fcf4b5712f31c/Casks/devonthink-pro-office.rb#L15L16) is a good example.

2016-10-08 13:46 UTC, nbsantos commented on Casks/devonagent-pro.rb
> +  app 'DEVONagent.app', target: 'DEVONagent Pro.app'
This is similar to the devonthink-pro-office.rb formula. For some reason the vendor messed-up the naming on the zip file.

2016-10-08 14:21 UTC, vitorgalvao commented on Casks/devonagent-pro.rb
> +  app 'DEVONagent.app', target: 'DEVONagent Pro.app'
@nbsantos The comment is still needed. See the linked documentarion.

2016-10-10 15:24 UTC, fanquake commented
@nbsantos Can you make the requested changes?

2016-10-14 17:29 UTC, vitorgalvao commented
Closing for lack of reply. If you still wish to include this, please resubmit with the requested fixes.

2016-10-14 17:29 UTC, closed without merging