Add Metasploit nightly
Homebrew/homebrew-cask pull request #25128
Opened 2016-10-03 03:08 UTC by nbsantos

### Checklist

- [x] The commit message includes the cask’s name and version.
- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.

Additionally, when **adding a new cask**:

- [x] Checked there are no open [pull requests](https://github.com/caskroom/homebrew-cask/pulls) for the same cask.
- [x] Checked there are no closed [issues](https://github.com/caskroom/homebrew-cask/issues) where that cask was already refused.
- [x] When naming the cask, followed the [token reference](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.

2016-10-03 09:52 UTC, vitorgalvao requested changes

2016-10-03 09:52 UTC, vitorgalvao commented on Casks/metasploit.rb
> +  version :latest
Give it a version and a shasum. Since it has an appcast, it can have those.

2016-10-08 13:41 UTC, nbsantos commented on Casks/metasploit.rb
> +  version :latest
Added the version and shasum as requested. I also updated the app cast checkpoint to reflect the latest one as of today.

2016-10-08 14:34 UTC, vitorgalvao requested changes

2016-10-08 14:34 UTC, vitorgalvao commented on Casks/metasploit.rb
> +  uninstall script:  { executable: 'uninstall.tool', input: %w[Yes] },
Split this into lines (see other casks for examples, I’m currently on a phone).

2016-10-14 17:28 UTC, vitorgalvao commented
Closing for lack of reply. If you still wish to include this, please resubmit with the requested fixes.

2016-10-14 17:28 UTC, closed without merging