Add Cask for 'anonymous-vpn'
Homebrew/homebrew-cask pull request #25131
Opened 2016-10-03 06:49 UTC by aren55555

### Instructions

Delete the parts of this template that are not relevant (including these `Instructions`) and fill out the rest.  
If there’s a checkbox you can’t complete for any reason, that’s OK. Just explain in detail why you weren’t able to do so.  
*Note:* `{{cask_file}}` represents the cask file you’re submitting/editing.

### Checklist

- [ ] The commit message includes the cask’s name and version.
- [ ] `brew cask audit --download {{cask_file}}` is error-free.
- [ ] `brew cask style --fix {{cask_file}}` left no offenses.

Additionally, when **adding a new cask**:

- [ ] Checked there are no open [pull requests](https://github.com/caskroom/homebrew-cask/pulls) for the same cask.
- [ ] Checked there are no closed [issues](https://github.com/caskroom/homebrew-cask/issues) where that cask was already refused.
- [ ] When naming the cask, followed the [token reference](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.

2016-10-03 09:54 UTC, vitorgalvao requested changes

2016-10-03 09:54 UTC, vitorgalvao commented on Casks/anonymous-vpn.rb
> +cask 'anonymous-vpn' do
`anonymousvpn` (no hyphen).

2016-10-04 00:23 UTC, aren55555 commented
@vitorgalvao so I know for the future should I be using the app name contained in the pkg `AnonymousVPN` or the sevice's name `Anonymous VPN` (w/ space, as used on their website & social media) to seed the token generation?

2016-10-04 00:26 UTC, aren55555 commented
@vitorgalvao should I also change the filename?

2016-10-04 09:55 UTC, vitorgalvao commented
You should use the closest to the package itself, unless it’s a nonsensical name.

2016-10-04 09:55 UTC, vitorgalvao approved these changes

2016-10-04 09:55 UTC, merged