Add Cask for 'SafeSign Driver'
Homebrew/homebrew-cask pull request #25147
Opened 2016-10-03 14:09 UTC by berniechiu

### Instructions

Delete the parts of this template that are not relevant (including these `Instructions`) and fill out the rest.  
If there’s a checkbox you can’t complete for any reason, that’s OK. Just explain in detail why you weren’t able to do so.  
*Note:* `{{cask_file}}` represents the cask file you’re submitting/editing.

### Checklist

- [ ] The commit message includes the cask’s name and version.
- [ ] `brew cask audit --download {{cask_file}}` is error-free.
- [ ] `brew cask style --fix {{cask_file}}` left no offenses.

Additionally, when **adding a new cask**:

- [ ] Checked there are no open [pull requests](https://github.com/caskroom/homebrew-cask/pulls) for the same cask.
- [ ] Checked there are no closed [issues](https://github.com/caskroom/homebrew-cask/issues) where that cask was already refused.
- [ ] When naming the cask, followed the [token reference](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.

2016-10-03 15:51 UTC, vitorgalvao commented
Before discussing inclusion of this further, I’d like @rogeriopradoj’s input here, since he knows the app/cask well.

2016-10-04 00:05 UTC, berniechiu commented
alright I'll close this one first

2016-10-04 10:10 UTC, vitorgalvao requested changes

2016-10-04 10:10 UTC, vitorgalvao commented on Casks/safesign-driver.rb
> +cask 'safesign-driver' do
Call it `safesign-identity-client` instead.

2016-10-04 10:10 UTC, vitorgalvao commented on Casks/safesign-driver.rb
> +  name 'SafeSign Driver'
Make it `SafeSign Identity Client`.

2016-10-04 10:10 UTC, vitorgalvao commented on Casks/safesign-driver.rb
> +  uninstall pkgutil: [
See https://github.com/caskroom/homebrew-cask/pull/25158/files. Did you miss `'SafeSign3.0'`?

2016-10-05 00:27 UTC, berniechiu commented on Casks/safesign-driver.rb
> +cask 'safesign-driver' do
Sure~

2016-10-05 00:31 UTC, berniechiu commented on Casks/safesign-driver.rb
> +  name 'SafeSign Driver'
No problem

2016-10-05 02:03 UTC, rogeriopradoj commented
@berniechiu @vitorgalvao 😃

2016-10-05 08:28 UTC, vitorgalvao approved these changes

2016-10-05 08:28 UTC, vitorgalvao commented
Thank you. Merging.

2016-10-05 08:28 UTC, merged