Update Hyperterm to Hyper
Homebrew/homebrew-cask pull request #25259
Opened 2016-10-06 16:16 UTC by thibmaek

See https://github.com/zeit/hyper/releases/tag/0.8.1

2016-10-06 17:11 UTC, vitorgalvao requested changes

2016-10-06 17:11 UTC, vitorgalvao commented on Casks/hyperterm.rb
>  cask 'hyperterm' do
This also needs to change (and the name of the file).

2016-10-06 19:43 UTC, vitorgalvao approved these changes

2016-10-07 07:45 UTC, stovmascript commented on Casks/hyper.rb
> +          checkpoint: '5ccfd2a1a40f2a2c2ea39a554f122fc165a2815de4c2d864c11c2153981088e6'
Seems like the releases.atom file sha256 checksum also needs to be updated:

```shell
$ wget https://github.com/zeit/hyper/releases.atom
$ shasum -a 256 releases.atom 
9cb83c950deb477b1d9c95ebecbdaba3637db29007b2ff279ec4301147426b49  releases.atom
```

2016-10-07 09:33 UTC, vitorgalvao commented on Casks/hyper.rb
> +          checkpoint: '5ccfd2a1a40f2a2c2ea39a554f122fc165a2815de4c2d864c11c2153981088e6'
@stovmascript Even though in this case it’s the same, that not how you calculate [`appcast`](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/appcast.md).

2016-10-07 10:14 UTC, vitorgalvao commented
Thank you for the contribution. It needed some fixes, so they were made in 9e5b3db2d122990b81e9686903577379e769f963. Your contribution is still included (and still credited to you), with the appropriate modifications. Please feel free to ask about any of the changes.

2016-10-07 10:14 UTC, closed without merging