Add JProfiler.app v9.2
Homebrew/homebrew-cask pull request #25265
Opened 2016-10-06 17:57 UTC by onlynone

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked that the cask was not already refused in [closed issues].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed

2016-10-06 18:14 UTC, vitorgalvao requested changes

2016-10-06 18:14 UTC, vitorgalvao commented on Casks/jprofiler.rb
> +  url 'http://download-keycdn.ej-technologies.com/jprofiler/jprofiler_macos_9_2.dmg'
`url "http://download-keycdn.ej-technologies.com/jprofiler/jprofiler_macos_#{version.dots_to_underscores}.dmg"`

2016-10-06 21:02 UTC, onlynone commented on Casks/jprofiler.rb
> +  url 'http://download-keycdn.ej-technologies.com/jprofiler/jprofiler_macos_9_2.dmg'
Done

2016-10-06 21:04 UTC, vitorgalvao approved these changes

2016-10-07 03:44 UTC, victorpopkov commented
Thank you for the changes and your contribution!

2016-10-07 03:44 UTC, merged