Add Statusfy v1.4.0
Homebrew/homebrew-cask pull request #25276
Opened 2016-10-06 22:00 UTC by andreis

*If there’s a checkbox you can’t complete for any reason, that's okay, just explain in detail why you weren’t able to do so.*

After making all changes to the cask:

- [ ✔️ ] `brew cask audit --download {{cask_file}}` is error-free.
- [ ✔️ ] `brew cask style --fix {{cask_file}}` reports no offenses.
- [ ✔️ ] The commit message includes the cask’s name and version.

Additionally, **if adding a new cask**:

- [ ✔️ ] Named the cask according to the [token reference].
- [ ✔️ ] `brew cask install {{cask_file}}` worked successfully.
- [ ✔️ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ✔️ ] Checked there are no [open pull requests] for the same cask.
- [ ✔️ ] Checked that the cask was not already refused in [closed issues].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed

2016-10-06 22:07 UTC, vitorgalvao requested changes

2016-10-06 22:07 UTC, vitorgalvao commented on Casks/statusfy.rb
> +  url 'https://github.com/paulyoung/Statusfy/releases/download/1.4.0/Statusfy.zip'
`url "https://github.com/paulyoung/Statusfy/releases/download/#{version}/Statusfy.zip"`

2016-10-06 22:15 UTC, andreis commented on Casks/statusfy.rb
> +  url 'https://github.com/paulyoung/Statusfy/releases/download/1.4.0/Statusfy.zip'
That's what I did initially, but `brew cask style` complained. Will change

2016-10-06 23:38 UTC, vitorgalvao approved these changes

2016-10-06 23:38 UTC, vitorgalvao requested changes

2016-10-06 23:38 UTC, vitorgalvao commented on Casks/statusfy.rb
> +  appcast 'https://github.com/fitztrev/shuttle/releases.atom',
Wrong appcast.

2016-10-06 23:42 UTC, vitorgalvao approved these changes

2016-10-07 03:48 UTC, victorpopkov requested changes

2016-10-07 03:48 UTC, victorpopkov commented on Casks/statusfy.rb
> +  name 'Shuttle'
Wrong name.

2016-10-07 11:23 UTC, victorpopkov approved these changes

2016-10-07 11:24 UTC, victorpopkov commented
Thank you for all the changes and your contribution!

2016-10-07 11:26 UTC, merged