Add moira 4.0.0.3.
Homebrew/homebrew-cask pull request #25282
Opened 2016-10-07 05:52 UTC by leee

*If there’s a checkbox you can’t complete for any reason, that's okay, just explain in detail why you weren’t able to do so.*

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked that the cask was not already refused in [closed issues].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed

Signed-off-by: Eugene Lee <leee@mit.edu>

2016-10-08 08:52 UTC, reitermarkus requested changes

2016-10-08 08:52 UTC, reitermarkus commented on Casks/moira.rb
> +  url "https://github.com/macathena/moira/archive/#{version}.zip"
This needs an [`appcast`](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/appcast.md).

2016-10-08 08:52 UTC, reitermarkus commented on Casks/moira.rb
> +  depends_on formula: ['homebrew/dupes/krb5']
You don't need an array here.

2016-10-08 08:52 UTC, reitermarkus commented on Casks/moira.rb
> +  caveats 'You MUST use MIT Kerberos as opposed to Apple-provided Heimdal Kerberos.'
Use only one `caveats` stanza with `<<-EOS.undent`.

2016-10-10 15:25 UTC, fanquake commented
@leee Can you make the requested changes?

2016-10-10 19:05 UTC, leee reviewed
@fanquake - apologies for the delay. There were updates that had to be made upstream as well as a package provided for in `homebrew-core`.

2016-10-10 19:05 UTC, leee commented on Casks/moira.rb
> +  caveats 'You MUST use MIT Kerberos as opposed to Apple-provided Heimdal Kerberos.'
Done.

2016-10-10 19:05 UTC, leee commented on Casks/moira.rb
> +  depends_on formula: ['homebrew/dupes/krb5']
Modified - this was blocked until `hesiod` was added and updated in `homebrew-core`.

2016-10-10 19:05 UTC, leee commented on Casks/moira.rb
> +  url "https://github.com/macathena/moira/archive/#{version}.zip"
Done - didn't know about appcast - thank you!

2016-10-13 16:07 UTC, leee commented
The [macathena](https://github.com/macathena) team has been provided a public source from upstream and therefore find this PR moot/no longer necessary, and intend on writing a Formula for use in [homebrew-core](https://github.com/homebrew/homebrew-core).

Thank you for the initial code review and consideration for inclusion!

2016-10-13 16:07 UTC, closed without merging