Update qtpass to 1.1.4
Homebrew/homebrew-cask pull request #25358
Opened 2016-10-10 09:57 UTC by annejan

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

2016-10-10 10:02 UTC, vitorgalvao requested changes

2016-10-10 10:02 UTC, vitorgalvao commented on Casks/qtpass.rb
> +
Remove this line and `license` (it will be deprecated in a new release today).

2016-10-11 00:34 UTC, Numbermaniac commented on Casks/qtpass.rb
> +          checkpoint: '96b00beb82f888bbee5f39f9251b59a3fda77de19cc5adfc52caa43711a97f46'
Seems the appcast checkpoint should be `ff499dc0c1c79de926d52e62cfb7e2f4a8c07a27d69b1c15df140bec9b0cf52f`.

2016-10-11 09:03 UTC, vitorgalvao approved these changes

2016-10-11 09:04 UTC, merged