Add mediaconch-gui 16.09
Homebrew/homebrew-cask pull request #25357
Opened 2016-10-10 08:32 UTC by g-maxime

*If there’s a checkbox you can’t complete for any reason, that's okay, just explain in detail why you weren’t able to do so.*

After making all changes to the cask:

- [X] `brew cask audit --download {{cask_file}}` is error-free.
- [X] `brew cask style --fix {{cask_file}}` reports no offenses.
- [X] The commit message includes the cask’s name and version.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference].
-->  mediaconch name usually refers to the CLI package.

- [X] `brew cask install {{cask_file}}` worked successfully.
- [X] `brew cask uninstall {{cask_file}}` worked successfully.
- [X] Checked there are no [open pull requests] for the same cask.
- [X] Checked that the cask was not already refused in [closed issues].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed

2016-10-11 12:09 UTC, vitorgalvao requested changes

2016-10-11 12:09 UTC, vitorgalvao commented on Casks/mediaconch-gui.rb
> +cask 'mediaconch-gui' do
Make it `mediaconch-app`. It’ll either be that or have no suffix. We’re still deciding.

2016-10-11 12:09 UTC, vitorgalvao commented on Casks/mediaconch-gui.rb
> +  license :gpl
Remove `license`, it has been deprecated and is no longer in use.

2016-10-11 16:47 UTC, vitorgalvao commented on Casks/mediaconch-gui.rb
> +  license :gpl
> if a CLI application is acceptable in you project it will take the name.

Yes, they are very much acceptable. Is that a `pkg` just with the CLI, or a `pkg` with both the CLI and the `app`? That would be very much acceptable, yes, and preferred over this one.

> We also have

Does that mean you’re one of the developers?

2016-10-11 16:50 UTC, g-maxime commented on Casks/mediaconch-gui.rb
> +  license :gpl
The dmg with the pkg contains only the CLI.

I work for the editor.

2016-10-11 18:45 UTC, g-maxime commented on Casks/mediaconch-gui.rb
> +  license :gpl
This app do not need the CLI.

2016-10-11 20:44 UTC, vitorgalvao commented on Casks/mediaconch-gui.rb
> +  license :gpl
Let me clarify. Does this app have basically the same set of features as the CLI, but as a GUI, or do the GUI and CLI do basically different things, and they complement each other (meaning there’re things you can do with one but not with the other, and vice-versa).

And is there a “main” one between the two, one that drives the development of the other?

2016-10-11 22:24 UTC, g-maxime commented on Casks/mediaconch-gui.rb
> +  license :gpl
Basically the same functionalities, a little more options in the CLI but nothing concerning the main features.

2016-10-11 23:26 UTC, adidalal commented on Casks/mediaconch-gui.rb
> +  license :gpl
This should be fine as -app, if you plan on putting the cli into Homebrew

2016-10-12 08:09 UTC, vitorgalvao approved these changes

2016-10-12 08:09 UTC, merged