add RapidMiner Studio 7.2.3 (with link to rapidminer site)
Homebrew/homebrew-cask pull request #25374
Opened 2016-10-10 20:54 UTC by longstone

*If there’s a checkbox you can’t complete for any reason, that's okay, just explain in detail why you weren’t able to do so.*

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked that the cask was not already refused in [closed issues]*.

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed

* There are 2 closed issues, one which is a older version, and one which is walled. this version uses the link to the rapidminer site.

2016-10-10 21:04 UTC, reitermarkus requested changes

2016-10-10 21:04 UTC, reitermarkus commented on Casks/rapidminer-studio.rb
> +  sha256 'b04cc77028bac7822d5aeead687a4cf1cca146cebc220cb4d55803aa86489d61'
Use `:no_check` when there's no versioned download.

2016-10-10 21:28 UTC, vitorgalvao requested changes

2016-10-10 21:28 UTC, vitorgalvao commented on Casks/rapidminer-studio.rb
> +  version ':latest'
It’s `version :latest` (no quotes).

2016-10-11 09:03 UTC, vitorgalvao requested changes

2016-10-11 09:03 UTC, vitorgalvao commented on Casks/rapidminer-studio.rb
> +  license :unknown
Remove `license`. We no longer use it (since yesterday).

2016-10-11 12:08 UTC, vitorgalvao approved these changes

2016-10-11 12:08 UTC, merged