add Secure Pipes.app version 0.9.88 as secure-pipes
Homebrew/homebrew-cask pull request #25470
Opened 2016-10-13 20:56 UTC by zsprackett

*If there’s a checkbox you can’t complete for any reason, that's okay, just explain in detail why you weren’t able to do so.*

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked that the cask was not already refused in [closed issues].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed

2016-10-13 23:53 UTC, vitorgalvao approved these changes

2016-10-13 23:55 UTC, vitorgalvao requested changes

2016-10-13 23:55 UTC, vitorgalvao commented on Casks/secure-pipes.rb
> +  version '0.99.8'
Make it `version '0.99.8,15e8a5ef38260ea'`.

2016-10-13 23:55 UTC, vitorgalvao commented on Casks/secure-pipes.rb
> +  url 'https://www.opoet.com/pyro/index.php/files/download/15e8a5ef38260ea'
Make it `url "https://www.opoet.com/pyro/index.php/files/download/#{version.after_comma}"`.

2016-10-16 05:43 UTC, adidalal commented
Thank you for the contribution. It needed some fixes, so they were made in f47da9ed84f48d5e727d2bf7c524dcbc1ad2b83a. Your contribution is still included (and still credited to you), with the appropriate modifications. Please feel free to ask about any of the changes.

2016-10-16 05:43 UTC, closed without merging