Change token from 3mcloudlibrary to cloudlibrary
Homebrew/homebrew-cask pull request #25497
Opened 2016-10-14 19:16 UTC by Saklad5

*If there’s a checkbox you can’t complete for any reason, that's okay, just explain in detail why you weren’t able to do so.*

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference].
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked there are no [open pull requests] for the same cask.
- [ ] Checked that the cask was not already refused in [closed issues].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed

Add cloudLibrary.app v2.0.1610051750
Fix macOS dependencies

2016-10-14 19:20 UTC, Saklad5 commented
Why aren't we running build tests on macOS Sierra yet?

2016-10-14 19:37 UTC, reitermarkus commented
> Why aren't we running build tests on macOS Sierra yet?

Travis doesn't have a Sierra image yet.

2016-10-14 19:42 UTC, vitorgalvao requested changes

2016-10-14 19:42 UTC, vitorgalvao commented on Casks/cloudlibrary.rb
> +  appcast 'http://www.yourcloudlibrary.com/index.php/en-us/downloads/software?format=rss',
Move `appcast` inside the `else`.

2016-10-14 19:42 UTC, vitorgalvao commented on Casks/cloudlibrary.rb
> +  name 'cloudLibrary'
Remove this name, as it adds nothing.

2016-10-14 19:42 UTC, vitorgalvao commented on Casks/cloudlibrary.rb
> +    app '3MCloudLibrary.app'
Put an empty line above this one.

2016-10-14 19:42 UTC, vitorgalvao commented on Casks/cloudlibrary.rb
> +    pkg "cloudLibrary-#{version}.pkg"
And another above this one.

2016-10-14 19:43 UTC, vitorgalvao commented
Made the requested changed myself, since your branch allowed for it.

2016-10-14 19:43 UTC, vitorgalvao approved these changes

2016-10-14 20:32 UTC, Saklad5 commented
The appcast applies to both the old version and the new version. And the style check arranged the stanzas like that, not me.

2016-10-14 20:33 UTC, Saklad5 commented
Is it really that hard to wait a few hours for a reply?

2016-10-14 20:35 UTC, Saklad5 commented
Furthermore, even the source website is inconsistent about whether the name is "3MCloudLibrary" or "cloudLibrary". It took me ages to confirm that the former had been changed to the latter officially. Anyone looking for this Cask might use either name.

2016-10-14 20:49 UTC, jawshooah commented
> And the style check arranged the stanzas like that, not me.

The style check isn't smart enough yet to rearrange stanzas inside `if...else` blocks, sorry about that.

> Is it really that hard to wait a few hours for a reply?

Let's keep the tone civil, eh? We deal with a pretty high volume of PRs, so fixing and closing them out takes priority over waiting for a user to implement requested changes if a maintainer has time to do it themselves.

2016-10-14 20:54 UTC, Saklad5 commented
Sorry, I just was annoyed that he changed information about the cask without waiting a few minutes for a reply. If it was just syntax that he changed, I wouldn’t be so irritated.

2016-10-15 15:54 UTC, reitermarkus commented
> he changed information about the cask

Is the information as it is now correct?

2016-10-15 17:27 UTC, Saklad5 commented
The appcast stanza applies to both versions, not just the newly named one.

On Oct 15, 2016, at 10:54 AM, Markus Reiter <notifications@github.com> wrote:

he changed information about the cask

Is the information as it is now correct?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.

2016-10-16 01:48 UTC, vitorgalvao commented
> The appcast stanza applies to both versions, not just the newly named one.

From the point there is an older version of the app for an older version of the OS, the appcast starts to apply only to the newest one, according to our system. Unless there’s a version for Lion and earlier being developed at the same time as this new one, which does not seem to be the case at all, it only applies to the newest case. Simply because the older version is still present in the appcast, it does not mean it still applies. It’s present as an old version and nothing more.

In addition, I made the changes to save you work, I don’t really see why you chose to take that as an insult. My comments served to inform you of the changes.

Thank you for the contribution.

2016-10-16 01:48 UTC, merged

2016-10-16 01:49 UTC, Saklad5 commented
Who said I took it as an insult?

On 15 October 2016, at 8:48 PM, Vítor Galvão <notifications@github.com> wrote:

—