Add OverSight Releases v1.0.0
Homebrew/homebrew-cask pull request #25506
Opened 2016-10-15 01:02 UTC by tennisonchan

*If there’s a checkbox you can’t complete for any reason, that's okay, just explain in detail why you weren’t able to do so.*

After making all changes to the cask:

- [ ] `brew cask audit --download {{cask_file}}` is error-free.
- [ ] `brew cask style --fix {{cask_file}}` reports no offenses.
- [ ] The commit message includes the cask’s name and version.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference].
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked there are no [open pull requests] for the same cask.
- [ ] Checked that the cask was not already refused in [closed issues].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed

2016-10-15 03:21 UTC, fanquake commented on Casks/oversight.rb
> +  url 'https://bitbucket.org/objective-see/deploy/downloads/OverSight_1.0.0.zip'
Use #{version} in the URL stanza

2016-10-15 09:19 UTC, vitorgalvao requested changes

2016-10-15 09:19 UTC, vitorgalvao commented on Casks/oversight.rb
> +  uninstall delete: '/Applications/OverSight.app'
Are you sure this is the only thing the installer does? That’s unlikely. Doesn’t objective-see usually tell exactly how to uninstall their apps?

2016-10-16 05:51 UTC, adidalal requested changes

2016-10-16 05:51 UTC, adidalal commented on Casks/oversight.rb
> +  uninstall delete: '/Applications/OverSight.app'
Needs to be something like:

```
uninstall quit: {{package_id_here}}
          delete: '/Applications/OverSight.app'
          login_item: 'Oversight'
```

2016-10-16 05:51 UTC, adidalal commented on Casks/oversight.rb
> +  url 'https://bitbucket.org/objective-see/deploy/downloads/OverSight_#{version}.zip'
Mind adding an [appcast](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/appcast.md)?

URL is: https://objective-see.com/products/versions/oversight.json

2016-10-16 19:51 UTC, tennisonchan commented on Casks/oversight.rb
> +  uninstall delete: '/Applications/OverSight.app'
Not sure how to get the `{{package_id}}`.

2016-10-16 22:02 UTC, adidalal commented on Casks/oversight.rb
> +  uninstall delete: '/Applications/OverSight.app'
Updated comment.
For future reference: http://superuser.com/questions/346369/getting-the-bundle-identifier-of-an-os-x-application-in-a-shell-script

2016-10-16 22:49 UTC, vitorgalvao requested changes

2016-10-16 22:49 UTC, vitorgalvao commented on Casks/oversight.rb
> +  app 'OverSight.app'
This is to be used only when the app comes in the zip (not the case here).

2016-10-16 22:49 UTC, vitorgalvao commented on Casks/oversight.rb
> +  appcast 'https://objective-see.com/products/versions/oversight.json'
It needs a checkpoint. See the [docs](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/appcast.md).

2016-10-16 22:56 UTC, tennisonchan commented
The file `usr/local/Caskroom/oversight/1.0.0/OverSight_Installer.app` is not found. How can I modify the path of the installer? 

![screen shot 2016-10-16 at 6 47 01 pm](https://cloud.githubusercontent.com/assets/719938/19421511/f8913724-93d0-11e6-9733-32fb13bc7d4b.png)

2016-10-16 23:02 UTC, vitorgalvao commented
> The file `usr/local/Caskroom/oversight/1.0.0/OverSight_Installer.app` is not found. How can I modify the path of the installer?

Reread the message. It’s the other (wrong) stanza that is not being found.

2016-10-16 23:03 UTC, vitorgalvao approved these changes

2016-10-16 23:27 UTC, adidalal approved these changes

2016-10-16 23:28 UTC, adidalal commented
Just needs a `brew cask style --fix {{cask_file}}`, looks like

2016-10-17 01:01 UTC, adidalal commented
Thank you for the contribution. It needed some fixes, so they were made in 1910a740986bf8a0e62e9ca03502067c87221f63. Your contribution is still included (and still credited to you), with the appropriate modifications. Please feel free to ask about any of the changes.

2016-10-17 01:01 UTC, closed without merging

2016-10-17 01:07 UTC, tennisonchan commented
Thank you so much for the modifications!