Automatically fix a few RuboCop warnings
Homebrew/homebrew-cask pull request #25503
Opened 2016-10-14 22:25 UTC by maxnordlund

I'm currently deep diving into audit/RuboCop and figured I should see if there were any warnings. And sure enough, `4615 files inspected, 805 offenses detected, 14 offenses corrected`. I'll tackle the easy ones that causes a lot of noise next (google fonts) so that the real ones show up.

*If there’s a checkbox you can’t complete for any reason, that's okay, just explain in detail why you weren’t able to do so.*

After making all changes to the cask:

- [ ] `brew cask audit --download {{cask_file}}` is error-free.
- [ ] `brew cask style --fix {{cask_file}}` reports no offenses.
- [ ] The commit message includes the cask’s name and version.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference].
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked there are no [open pull requests] for the same cask.
- [ ] Checked that the cask was not already refused in [closed issues].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed

2016-10-14 23:52 UTC, reitermarkus requested changes

2016-10-14 23:52 UTC, reitermarkus commented on Casks/adobe-after-effects-cc.rb
>    license :commercial
Remove `license`, it has been deprecated.

2016-10-14 23:52 UTC, reitermarkus commented on Casks/adobe-premiere-pro-cc.rb
>    license :commercial
Same here.

2016-10-15 03:24 UTC, fanquake commented
Looks like this should be ok to merge now?

2016-10-15 04:13 UTC, jawshooah approved these changes

2016-10-15 04:13 UTC, merged