Add fork steveschow-gfxcardstatus (v2.4.3i)
Homebrew/homebrew-cask pull request #25525
Opened 2016-10-15 15:59 UTC by Tclv

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked that the cask was not already refused in [closed issues].

macOS Sierra broke the old version of gfxcardstatus. This fork fixes
the issues in the original.

There doesn't seem to be any indication of time or whether the original repo is going to be fixed at all.  There's no PR open either.

If there's anything wrong with the formatting of the cask/commit messages let me know and I will do my best to correct them!

2016-10-15 16:49 UTC, adidalal requested changes

2016-10-15 16:49 UTC, adidalal commented on Casks/steveschow-gfxcardstatus.rb
> +  url "https://github.com/steveschow/gfxCardStatus/releases/download/v#{version}/gfxCardStatus.app.zip"
Also, mind adding an [appcast](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/appcast.md)?

2016-10-15 16:49 UTC, adidalal commented on Casks/steveschow-gfxcardstatus.rb
> +  name 'steveschow-gfxCardStatus'
This can be just `gfxCardStatus`

2016-10-15 18:13 UTC, adidalal commented
Thank you for the contribution. It needed some fixes, so they were made in 3461e6433282dcbd7a78feb27aacd87b0663feb8. Your contribution is still included (and still credited to you), with the appropriate modifications. Please feel free to ask about any of the changes.

2016-10-15 18:13 UTC, closed without merging

2016-10-16 08:20 UTC, Tclv commented
@adidalal Thanks for going ahead and making the changes, just happy to see it get to master!