Update vimr to v0.9.0-SNAPSHOT-20161017.2152-107
Homebrew/homebrew-cask pull request #25599
Opened 2016-10-17 20:57 UTC by pbdeuchler

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

2016-10-17 22:08 UTC, vitorgalvao requested changes

2016-10-17 22:08 UTC, vitorgalvao commented on Casks/vimr.rb
> +  version 'v0.9.0-SNAPSHOT-20161017.2152-107'
Leave the `v` in the `url`.

2016-10-17 22:08 UTC, vitorgalvao commented on Casks/vimr.rb
> +  auto_updates true
This is in the wrong place. `brew cask style --fix` should fix that. Did you run that?

2016-10-17 22:14 UTC, pbdeuchler commented
@vitorgalvao first time contributor, sorry about that! should be all fixed

2016-10-17 22:17 UTC, vitorgalvao requested changes

2016-10-17 22:17 UTC, vitorgalvao commented on Casks/vimr.rb
> +  appcast 'https://raw.githubusercontent.com/qvacua/vimr/master/appcast.xml',
Why change this? We prefer the other one.

2016-10-17 22:44 UTC, pbdeuchler commented on Casks/vimr.rb
> +  appcast 'https://raw.githubusercontent.com/qvacua/vimr/master/appcast.xml',
Works for me, updated

2016-10-17 22:55 UTC, vitorgalvao approved these changes

2016-10-17 22:55 UTC, vitorgalvao commented
Thank you for the contribution and quick fixes! As soon as Travis passes, we can merge this.

2016-10-17 22:55 UTC, pbdeuchler commented
Happy to help!

2016-10-18 00:59 UTC, jawshooah commented
Wait, why are we upgrading to a snapshot release in the first place? It seems like there are [multiple snapshots every day](https://github.com/qvacua/vimr/releases), and they are all labeled "Pre-release". I feel like this belongs in the versions repo as `vimr-snapshot`.

2016-10-18 02:31 UTC, pbdeuchler commented
I wouldn't say every day, but no denying there are frequent releases. However this cask update fetches the latest version that includes Sparkle (plus a minor bugfix), so now anyone who installs will be on a better upgrade path for the future. However installing the snapshot doesn't force you into the nightly channel, so there will still be a stable experience (as stable as pre 1.0 gets at least). 

Most importantly though, anyone who would be installing vimr for the first time would use this release (as of today) if they followed the project README, while the current cask still installs a version that's almost a year old.

2016-10-18 23:07 UTC, jawshooah commented
@pbdeuchler The appcast checksum is now inaccurate because there has been another snapshot release since this PR was created. Which touches on my concern: which such frequent snapshot releases, how will this cask be kept up-to-date? Is there not a series of stable releases? You say that installing a snapshot release doesn't force you into a nightly channel, but what other channel is there?

2016-10-21 00:51 UTC, fanquake commented
@pbdeuchler Can you follow up here?

2016-10-21 03:08 UTC, pbdeuchler commented
Apologies, I must have accidentally inbox zeroed the previous notification email.

I wouldn't say the latest release changes my opinion at all, I'd like to re-iterate that the only releases for over the past year have been snapshot releases, and given that the official README of the project recommends downloading the latest bleeding edge release I don't necessarily agree that a separate cask is needed. 

As far as separate update channels are concerned, I am not on the nightly Sparkle channel and have yet to have an update come down the wire. I am assuming the next push down the default channel would be a major version however I think the maintainer would probably be the best person to ask about that.

Just to expedite this conversation, is the sticking point that this PR moves the version to a non-major release, or that the app is updated too frequently to warrant a cask not named with some sort of warning (`snapshot`, `nightly`, etc)?

2016-10-21 03:28 UTC, jawshooah commented
@pbdeuchler Thanks for getting back. Looking at the description of the [most recent snapshot release](https://github.com/qvacua/vimr/releases/tag/snapshot%2Fv0.9.0-SNAPSHOT-20161020.2036-111), it seems this discussion might be moot:

> Probably the last snapshot before the 0.9.0 release

Since a new stable release is coming soon, I think I'd rather wait. In the meantime, this can be added to [homebrew-versions](https://github.com/caskroom/homebrew-versions) as `vimr-snapshot`.

2016-10-21 03:37 UTC, closed without merging

2016-10-21 04:49 UTC, pbdeuchler commented
Works for me, I'll just wait and submit the stable version

2016-10-21 22:29 UTC, jawshooah commented
@pbdeuchler https://github.com/qvacua/vimr/releases/tag/v0.9.0-112

2016-10-21 22:58 UTC, pbdeuchler commented
Woohoo! You're on top of it @jawshooah... submitted here: https://github.com/caskroom/homebrew-cask/pull/26016