add pdftoolkit
Homebrew/homebrew-cask pull request #25600
Opened 2016-10-17 21:15 UTC by markthetech

*If there’s a checkbox you can’t complete for any reason, that's okay, just explain in detail why you weren’t able to do so.*

After making all changes to the cask:

- [ ] `brew cask audit --download {{cask_file}}` is error-free.
- [ ] `brew cask style --fix {{cask_file}}` reports no offenses.
- [ ] The commit message includes the cask’s name and version.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference].
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked there are no [open pull requests] for the same cask.
- [ ] Checked that the cask was not already refused in [closed issues].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed

2016-10-17 22:08 UTC, vitorgalvao requested changes

2016-10-17 22:08 UTC, vitorgalvao commented on Casks/pdftoolkit.rb
> +cask 'pdftoolkit' do
Needs to be `cisdem-pdftoolkit` according to the token reference.

2016-10-18 02:18 UTC, jawshooah requested changes

2016-10-18 02:18 UTC, jawshooah commented on Casks/pdftoolkit.rb
> +cask 'cisdem-pdftoolkit' do
You also need to rename the file.

2016-10-18 02:40 UTC, jawshooah approved these changes

2016-10-18 02:40 UTC, merged