Updated Droplr to 4.6.4 (Build 91)
Homebrew/homebrew-cask pull request #26079
Opened 2016-10-24 15:29 UTC by sbibauw

*If there’s a checkbox you can’t complete for any reason, that's okay, just explain in detail why you weren’t able to do so.*

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed

Previous link (http://droplr.com/homebrew) links currently to an error

2016-10-24 15:44 UTC, vitorgalvao requested changes

2016-10-24 15:44 UTC, vitorgalvao commented on Casks/droplr.rb
> +  url 'https://s3.amazonaws.com/files.droplr.com/apps/mac/Droplr+91.zip'
This will not pass `style`. It will need a comment.

2016-10-24 15:50 UTC, vitorgalvao requested changes

2016-10-24 15:50 UTC, vitorgalvao commented on Casks/droplr.rb
> +  url 'https://s3.amazonaws.com/files.droplr.com/apps/mac/Droplr+91.zip'
Where did you get this exact URL? I’m getting a different one (that also fails, like the previous one).

2016-10-24 19:09 UTC, vitorgalvao commented on Casks/droplr.rb
> +  url 'https://s3.amazonaws.com/files.droplr.com/apps/mac/Droplr+91.zip'
Run the `style` command, and you’ll see the problem. You need to add a `# s3.amazonaws.com/files.droplr.com was verified as official when first introduced to the cask` comment above `url`.

2016-10-24 19:09 UTC, vitorgalvao commented on Casks/droplr.rb
> +  version '4.6.4'
Make it `4.6.4,91`.

2016-10-24 19:10 UTC, vitorgalvao commented on Casks/droplr.rb
> +  url 'https://s3.amazonaws.com/files.droplr.com/apps/mac/Droplr+91.zip'
And here use `url "https://s3.amazonaws.com/files.droplr.com/apps/mac/Droplr+#{version.after_comma}.zip"`

2016-10-25 00:11 UTC, sbibauw commented
I have applied all the recommendations:
```
version "4.6.4,91"
sha256 "41064cec1922fa76b15e940a747e3d12e720588fa3ab9a527b38ba3a683c531b"

# files.droplr.com.s3.amazonaws.com was verified as official when first introduced to the cask
url "http://files.droplr.com.s3.amazonaws.com/apps/mac/Droplr+#{version.after_comma}.zip"
```
but still get a `[BUG] Segmentation fault` error on `brew cask style --fix`

Anyway, I have contacted Droplr to have them correct the `https://droplr.com/homebrew` link. 

What I couldn't find is Guidelines about whether `version :latest` + `sha256 :no_check` are preferred to a specific version number (better for updating, but needs more maintenance), or a specific version number (with/without a flexible URL scheme) are preferred...

2016-10-25 09:43 UTC, vitorgalvao requested changes

2016-10-25 09:43 UTC, vitorgalvao commented on Casks/droplr.rb
> +  version '4.6.4'
There is somewhere where we mention we prefer versions over `:latest` (users overwhelmingly voiced this preference).

Did you push your changes? It still looks the same.

2016-10-25 11:26 UTC, sbibauw commented
`brew cask style --fix` still fails ("[BUG] Segmentation fault")

2016-10-25 11:31 UTC, vitorgalvao commented
> `brew cask style --fix` still fails ("[BUG] Segmentation fault")

That’s an issue to report [on the core](https://github.com/Homebrew/brew). There was a similar issue a while ago, so please search for that first.

2016-10-26 01:12 UTC, merged