add an easy way to get the checksums
Homebrew/homebrew-cask pull request #26084
Opened 2016-10-25 01:11 UTC by muescha

*If there’s a checkbox you can’t complete for any reason, that's okay, just explain in detail why you weren’t able to do so.*

After making all changes to the cask:

- [ ] `brew cask audit --download {{cask_file}}` is error-free.
- [ ] `brew cask style --fix {{cask_file}}` reports no offenses.
- [ ] The commit message includes the cask’s name and version.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference].
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked there are no [open pull requests] for the same cask.
- [ ] Checked that the cask was not already refused in [closed issues].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed

2016-10-25 09:41 UTC, vitorgalvao requested changes

2016-10-25 09:41 UTC, vitorgalvao commented on doc/development/adding_a_cask.md
> +You can leave the checksum for `sha256` and `checkpoint` empty.
This gives the impression they’ll never have to be filled, which is incorrect.

Please *first* say how to correctly get them (for the appcast, link them to the document), and only then suggest `audit` as an alternative.

2016-10-28 03:38 UTC, schlueter commented on doc/development/adding_a_cask.md
> +You can leave the checksum for `sha256` and `checkpoint` empty.
I believe the shasum cli utility is available by default (or at least once XCode cli tools are installed). It's a one liner for anything: `shasum -a 256 <path/to/file>`.

2016-10-28 03:40 UTC, schlueter commented on doc/development/adding_a_cask.md
> +brew cask audit my-new-cask --download
I believe the shasum cli utility is available by default (or at least once XCode cli tools are installed), so audit would be overkill. It's a one liner for anything: `shasum -a 256 <path/to/file>`.

2016-11-01 14:07 UTC, vitorgalvao commented
Closing for lack of interest.

2016-11-01 14:07 UTC, closed without merging