Add zap to tunnelblick.rb
Homebrew/homebrew-cask pull request #26131
Opened 2016-10-26 17:23 UTC by chuanxd

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

2016-10-26 20:36 UTC, vitorgalvao requested changes

2016-10-26 20:36 UTC, vitorgalvao commented on Casks/tunnelblick.rb
> +                '~/Library/Preferences/net.tunnelblick.tunnelblick.plist'
This flunks `style` (missing a comma).

2016-10-27 01:51 UTC, adidalal commented
Thank you for the contribution. It needed some fixes, so they were made in efe3225dc7d3f6e2042f1d298bbf0e830f84db95. Your contribution is still included (and still credited to you), with the appropriate modifications. Please feel free to ask about any of the changes.

2016-10-27 01:51 UTC, closed without merging

2016-10-27 02:15 UTC, chuanxd commented
@adidalal Thank you for all your assistance.