Add 'Origami Studio' App
Homebrew/homebrew-cask pull request #26171
Opened 2016-10-28 06:51 UTC by olivererxleben

*If there’s a checkbox you can’t complete for any reason, that's okay, just explain in detail why you weren’t able to do so.*

After making all changes to the cask:

- [ ] `brew cask audit --download {{cask_file}}` is error-free.
- [ ] `brew cask style --fix {{cask_file}}` reports no offenses.
- [ ] The commit message includes the cask’s name and version.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference].
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked there are no [open pull requests] for the same cask.
- [ ] Checked that the cask was not already refused in [closed issues].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed

added the latest and officially first release of Origami Studio to the homebrew cask list

2016-10-28 08:46 UTC, miccal commented
You need to adda [comment](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/url.md#when-url-and-homepage-hostnames-differ-add-a-comment) above the url stanza.

2016-10-28 10:34 UTC, vitorgalvao requested changes

2016-10-28 10:34 UTC, vitorgalvao commented on Casks/origami-studio.rb
> +  url 'https://scontent-sea1-1.xx.fbcdn.net/t39.2270-6/10000000_930050417126110_4686042515185336320_n.dmg/Origami-Studio-External-Mac_42534415.dmg'
`42534415` looks like a version.

2016-10-29 02:08 UTC, adidalal commented on Casks/origami-studio.rb
> +  url 'https://scontent-sea1-1.xx.fbcdn.net/t39.2270-6/10000000_930050417126110_4686042515185336320_n.dmg/Origami-Studio-External-Mac_42534415.dmg'
In this case, I actually recommend the un versioned url - https://fb.me/getorigamistudio
It's a facebook cdn url, those break after some time, I believe.

2016-10-29 02:12 UTC, adidalal commented
Thank you for the contribution. It needed some fixes, so they were made in ec8e47baf775fe383fa64df5e2e3bae24312cf9c. Your contribution is still included (and still credited to you), with the appropriate modifications. Please feel free to ask about any of the changes.

2016-10-29 02:12 UTC, closed without merging