Add Electrum-DASH.app 2.4.1.
Homebrew/homebrew-cask pull request #26246
Opened 2016-10-31 00:10 UTC by neilbartley

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked that the cask was not already refused in [closed issues].

2016-10-31 11:00 UTC, vitorgalvao requested changes

2016-10-31 11:00 UTC, vitorgalvao commented on Casks/electrum-dash.rb
> +  uninstall delete: '/Applications/Electrum-DASH.app'
It’s unlikely this is the only thing the `pkg` installs. Check the [scripts](https://github.com/caskroom/homebrew-cask/tree/master/developer/bin) and [documentation](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/uninstall.md) geared for finding what more there is.

2016-11-01 22:16 UTC, neilbartley commented on Casks/electrum-dash.rb
> +  uninstall delete: '/Applications/Electrum-DASH.app'
No problem, I've updated the uninstall section to use pkgutil.

2016-11-01 22:51 UTC, vitorgalvao approved these changes

2016-11-02 02:08 UTC, merged