Add Aware.app v1.0.3
Homebrew/homebrew-cask pull request #26296
Opened 2016-11-01 16:37 UTC by ttaylorr

*If there’s a checkbox you can’t complete for any reason, that's okay, just explain in detail why you weren’t able to do so.*

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked that the cask was not already refused in [closed issues].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed

--

/cc @josh

2016-11-01 16:50 UTC, miccal commented
You need a [comment](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/url.md#when-url-and-homepage-hostnames-differ-add-a-comment) above the `url` stanza.

Use the `version` in their like so:
```
url 'https://github.com/josh/Aware/releases/download/v#{version}/Aware.zip'
```

Finally, could you please add an [appcast](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/appcast.md)?

2016-11-01 16:52 UTC, josh commented
Cool, but what's wrong with downloading from the Mac App Store? Its free.

2016-11-01 17:07 UTC, vitorgalvao requested changes

2016-11-01 17:07 UTC, vitorgalvao commented on Casks/aware.rb
> +  url 'https://github.com/josh/Aware/releases/download/v1.0.3/Aware.zip'
This needs the comment, like @miccal. It’s unlikely this has passed `style`.

2016-11-01 17:07 UTC, vitorgalvao commented on Casks/aware.rb
> +  url 'https://github.com/josh/Aware/releases/download/v1.0.3/Aware.zip'
Please add an [`appcast`](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/appcast.md).

2016-11-01 17:07 UTC, vitorgalvao commented on Casks/aware.rb
> +  url 'https://github.com/josh/Aware/releases/download/v1.0.3/Aware.zip'
`url "https://github.com/josh/Aware/releases/download/v#{version}/Aware.zip"`

2016-11-01 17:08 UTC, vitorgalvao commented
@josh Many people avoid the MAS like the plague and prefer to download it directly. Also, if you already manage all your apps via Homebrew-Cask, you want as many of them to be installable in this manner.

2016-11-01 17:14 UTC, ttaylorr commented on Casks/aware.rb
> +  url 'https://github.com/josh/Aware/releases/download/v1.0.3/Aware.zip'
Ah, I changed the URL and squashed it into the initial commit I made, without re-running `style`. It did indeed catch it, and is fixed as of https://github.com/caskroom/homebrew-cask/pull/26296/commits/95dbde348e0c9cdc3337c583d7bd2a99f99f7df9.

2016-11-01 17:15 UTC, ttaylorr commented on Casks/aware.rb
> +  url 'https://github.com/josh/Aware/releases/download/v1.0.3/Aware.zip'
https://github.com/caskroom/homebrew-cask/pull/26296/commits/e5ac0df1435cfa374c0c6f7942f3d859ca805de7.

2016-11-01 17:15 UTC, vitorgalvao requested changes

2016-11-01 17:15 UTC, vitorgalvao commented on Casks/aware.rb
> +  # github.com was verified as official when first introduced to the cask
Needs to be more specific: `github.com/josh/Aware`.

2016-11-01 17:16 UTC, vitorgalvao requested changes

2016-11-01 17:16 UTC, vitorgalvao commented on Casks/aware.rb
> +  url 'https://github.com/josh/Aware/releases/download/v1.0.3/Aware.zip'
Please make the change requested by @miccal.

2016-11-01 17:17 UTC, ttaylorr commented on Casks/aware.rb
> +  url 'https://github.com/josh/Aware/releases/download/v1.0.3/Aware.zip'
Nice. 1482ba602742652dffd263fad28b58c0f05fac09.

2016-11-01 17:17 UTC, ttaylorr commented on Casks/aware.rb
> +  # github.com was verified as official when first introduced to the cask
Was referencing Atom's [cask](https://github.com/caskroom/homebrew-cask/blob/161f85b605e160ff96e7dd11732d85609e13dc51/Casks/atom.rb#L5). See: bbc3b99c88a43d699848047f0fdb90993b2eff53.

2016-11-01 17:18 UTC, vitorgalvao approved these changes

2016-11-01 17:18 UTC, vitorgalvao commented
Thank you for the contribution and fast changes.

2016-11-01 22:32 UTC, ttaylorr commented
The test failure appears unrelated.

2016-11-02 02:11 UTC, vitorgalvao commented on Casks/aware.rb
> +  appcast 'https://github.com/jos/Aware/releases.atom',
This is wrong (`jos` instead of `josh`). I’ll fix it.

2016-11-02 02:13 UTC, vitorgalvao commented
Thank you for the contribution. It needed some fixes, so they were made in 187cc3046eb7acbf5363218692519d98e607d199. Your contribution is still included (and still credited to you), with the appropriate modifications. Please feel free to ask about any of the changes.

2016-11-02 02:13 UTC, closed without merging