Update rstudio to 1.0.44
Homebrew/homebrew-cask pull request #26340
Opened 2016-11-02 14:57 UTC by BenjaminHCCarr

After making all changes to the cask:
- [X] `brew cask audit --download rstudio.rb` is error-free.
- [X] `brew cask style --fix rstudio.rb` reports no offenses.
- [X] The commit message includes the cask’s name and version.

Rev rstudio from: `version '0.99.903'` to `version '1.0.44'` with brewed `r` dependancy.

```
tyr:~/Code/Homebrew benc$ brew cask audit --download ./rstudio.rb 
==> Downloading https://download1.rstudio.org/RStudio-1.0.44.dmg
######################################################################## 100.0%
==> Verifying checksum for Cask rstudio
audit for rstudio: passed
tyr:~/Code/Homebrew benc$ brew cask style --fix ./rstudio.rb 
==> Installing or updating 'rubocop-cask' gem
Fetching: rubocop-0.43.0.gem (100%)
Successfully installed rubocop-0.43.0
Fetching: rubocop-cask-0.10.4.gem (100%)
Successfully installed rubocop-cask-0.10.4
2 gems installed
== rstudio.rb ==
C:  4:  1: [Corrected] stanza groups should be separated by a single empty line

1 file inspected, 1 offense detected, 1 offense corrected
benc$ brew cask reinstall ./rstudio.rb 
==> Removing App: '/Applications/RStudio.app'
==> Satisfying dependencies
==> Installing Formula dependencies from Homebrew
homebrew/science/r ... ==> Warning: homebrew/science/r-3.3.2 already installed
done
complete
==> Downloading https://download1.rstudio.org/RStudio-1.0.44.dmg
Already downloaded: /Users/benc/Library/Caches/Homebrew/Cask/rstudio--1.0.44.dmg
==> Verifying checksum for Cask rstudio
==> Moving App 'RStudio.app' to '/Applications/RStudio.app'
🍺  rstudio was successfully installed!
```

This also closes #26308; I see all license files were nuked. Missed that discussion, but just for completeness rstudio is out under the `AGPL v3`

2016-11-02 15:03 UTC, vitorgalvao requested changes

2016-11-02 15:03 UTC, vitorgalvao commented on Casks/rstudio.rb
> +  #requires an `r` package
Remove comment.

2016-11-02 16:24 UTC, vitorgalvao approved these changes

2016-11-02 16:24 UTC, vitorgalvao commented
Thank you.

2016-11-02 16:24 UTC, merged

2016-11-02 16:25 UTC, BenjaminHCCarr commented
welcome took longer that is should have as I was testing a bunch of depends_on stanzas rather than just removing the line.

2016-11-22 19:33 UTC, rsrock commented on Casks/rstudio.rb
> +  depends_on formula: 'homebrew/science/r'
Is this dependency necessary?  I have the `r-app` cask installed instead, but this cask doesn't detect that.

2016-11-23 01:51 UTC, BenjaminHCCarr commented
That's part of the problem being explored in #26345.

The problem is there are multiple ways to get R. With the move toward bottles there is less need for R-app. If you want r and the gui you can unlink R-app; and try:

brew install r r-gui

I bet you get the same results as you will pull the bottle which should be the same as the cask. R-Gui will give you the gui interface. Possibly r-app should be deprecated.

2016-11-23 17:32 UTC, rsrock commented
That works.  Thanks!

2017-01-07 02:23 UTC, vitorgalvao commented on Casks/rstudio.rb
> +  depends_on formula: 'homebrew/science/r'
https://github.com/caskroom/homebrew-cask/pull/28717