Move Veertu Desktop to non-versioned download URL
Homebrew/homebrew-cask pull request #26375
Opened 2016-11-03 17:50 UTC by dwaite

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x ] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x ] The commit message includes the cask’s name and version.

2016-11-03 20:32 UTC, vitorgalvao commented
Thank you, but we prefer versioned downloads. Our users overwhelmingly chose it that way.

2016-11-03 20:41 UTC, miccal commented
The current download link `ttps://d2sje6b9huarvp.cloudfront.net/VeertuDesktop-#{version}.dmg` no longer works though.

2016-11-03 20:44 UTC, vitorgalvao commented
> The current download link `ttps://d2sje6b9huarvp.cloudfront.net/VeertuDesktop-#{version}.dmg` no longer works though.

Ah, that’s a different matter, then.

2016-11-03 20:45 UTC, vitorgalvao approved these changes

2016-11-03 21:12 UTC, jawshooah commented
Alternatively, we could keep the version number and add an appcast: https://d2sje6b9huarvp.cloudfront.net/vdoaupd.rss

2016-11-03 21:33 UTC, vitorgalvao commented
> Alternatively, we could keep the version number and add an appcast: https://d2sje6b9huarvp.cloudfront.net/vdoaupd.rss

Yes, best solution.

@dwaite Mind adding the [`appcast`](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/appcast.md)?

2016-11-03 21:36 UTC, dwaite commented
will do.

> On Nov 3, 2016, at 3:33 PM, Vítor Galvão <notifications@github.com> wrote:
> 
> Alternatively, we could keep the version number and add an appcast: https://d2sje6b9huarvp.cloudfront.net/vdoaupd.rss <https://d2sje6b9huarvp.cloudfront.net/vdoaupd.rss>
> Yes, best solution.
> 
> @dwaite <https://github.com/dwaite> Mind adding the appcast <https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/appcast.md>?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub <https://github.com/caskroom/homebrew-cask/pull/26375#issuecomment-258280896>, or mute the thread <https://github.com/notifications/unsubscribe-auth/AAARpcqCHXbBec9Bf-J4QRrYdWmvhRywks5q6lM_gaJpZM4Kote_>.
>

2016-11-03 21:49 UTC, vitorgalvao requested changes

2016-11-03 21:49 UTC, vitorgalvao commented on Casks/veertu-desktop.rb
> +  version '1.2.83'
Wait, why did we drop a version? According to the appcast we can even go higher than before, to `1.2.90`.

2016-11-05 03:08 UTC, adidalal commented
Versioned download seems to work, actually.
https://github.com/caskroom/homebrew-cask/pull/26443

2016-11-05 03:08 UTC, closed without merging