Add Nuimo.app v1.7.0
Homebrew/homebrew-cask pull request #26546
Opened 2016-11-07 13:46 UTC by anthonyangel

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked that the cask was not already refused in [closed issues].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed

2016-11-07 14:22 UTC, vitorgalvao commented on Casks/nuimo.rb
> +  url 'https://files.senic.com/nuimo-app-osx-1-7-0.zip'
Changed this for interpolation

2016-11-07 14:23 UTC, vitorgalvao commented on Casks/nuimo.rb
> +  url "https://files.senic.com/nuimo-app-osx-#{version.dots_to_dashes}.zip"
Changed this for interpolation.

2016-11-07 14:24 UTC, vitorgalvao requested changes

2016-11-07 14:24 UTC, vitorgalvao commented on Casks/nuimo.rb
> +  url "https://files.senic.com/nuimo-app-osx-#{version.dots_to_dashes}.zip"
Please add an [`appcast`](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/appcast.md). Address is `https://files.senic.com/nuimo-app-osx-appcast.xml`.

2016-11-08 04:16 UTC, fanquake commented
Travis failure:
```
>>> brew cask style Casks/nuimo.rb
== Casks/nuimo.rb ==
C:  5: 77: Trailing whitespace detected.
1 file inspected, 1 offense detected
```

2016-11-09 10:46 UTC, vitorgalvao approved these changes

2016-11-09 10:53 UTC, merged