Adding new jtool Cask
Homebrew/homebrew-cask pull request #26555
Opened 2016-11-07 16:21 UTC by timsutton

*If there’s a checkbox you can’t complete for any reason, that's okay, just explain in detail why you weren’t able to do so.*

After making all changes to the cask:

- [ ] `brew cask audit --download {{cask_file}}` is error-free.
- [ ] `brew cask style --fix {{cask_file}}` reports no offenses.
- [ ] The commit message includes the cask’s name and version.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference].
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked there are no [open pull requests] for the same cask.
- [ ] Checked that the cask was not already refused in [closed issues].

Submitting a new cask for [jtool](http://newosxbook.com/tools/jtool.html). I wasn't sure if there was a better way to handle linking a manpage. I opted to link it manually using `artifact` and `HOMEBREW_PREFIX`, similar to what [cargo does](https://github.com/caskroom/homebrew-cask/blob/master/Casks/cargo.rb).

2016-11-07 16:52 UTC, vitorgalvao requested changes

2016-11-07 16:52 UTC, vitorgalvao commented on Casks/jtool.rb
> +  license :gratis
Remove `license`, it has been deprecated and is no longer in use.

2016-11-07 16:54 UTC, timsutton commented on Casks/jtool.rb
> +  license :gratis
Done, thanks!

2016-11-08 00:58 UTC, vitorgalvao approved these changes

2016-11-08 01:45 UTC, merged