Add speedify latest
Homebrew/homebrew-cask pull request #26641
Opened 2016-11-10 06:15 UTC by Numbermaniac

After making all changes to the cask:

- [ ] `brew cask audit --download {{cask_file}}` is error-free.
- [ ] `brew cask style --fix {{cask_file}}` reports no offenses.
- [ ] The commit message includes the cask’s name and version.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference].
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked there are no [open pull requests] for the same cask.
- [ ] Checked that the cask was not already refused in [closed issues].

2016-11-10 09:44 UTC, vitorgalvao commented
From the contents of the dmg, it seems like uninstallation might be a little more complex. The app bundle even has a `uninstall-speedify-service.sh` script that has:

```shell
#!/bin/sh

launchctl unload /Library/LaunchDaemons/me.connectify.SMJobBlessHelper.plist
rm -f /Library/LaunchDaemons/me.connectify.SMJobBlessHelper.plist
#rm /var/run/SpeedifyService.socket
rm -f /Library/PrivilegedHelperTools/me.connectify.SMJobBlessHelper

launchctl unload /Library/LaunchDaemons/SwitchboardService.plist
rm -f /Library/LaunchDaemons/SwitchboardService.plist
rm -f /var/run/SwitchboardService.socket
rm -f /Library/PrivilegedHelperTools/SwitchboardService
rm -rf /tmp/tuntaposx-*.kext

launchctl unload /Library/LaunchDaemons/SpeedifyService.plist
rm -f /Library/LaunchDaemons/SpeedifyService.plist
rm -f /var/run/SpeedifyService.socket
rm -f /Library/PrivilegedHelperTools/SpeedifyService
```

2016-11-10 23:45 UTC, Numbermaniac commented
Neat. Should I change the `uninstall` stanza to just run that script?

2016-11-11 00:03 UTC, vitorgalvao commented
Scripts should be done as an extra, not as the only way (when possible).

Add the script, yes, but also extend your `launchctl:`.

2016-11-11 03:30 UTC, Numbermaniac commented
I think it's done, please check if it's right.

2016-11-11 12:03 UTC, vitorgalvao requested changes

2016-11-11 12:03 UTC, vitorgalvao commented on Casks/speedify.rb
> +            script:    '/Applications/Speedify.app/Contents/Resources/uninstall-speedify-service.sh'
`script:    "#{appdir}/Speedify.app/Contents/Resources/uninstall-speedify-service.sh"`

2016-11-11 12:23 UTC, Numbermaniac commented
Well, looks like you've just done that for me! Anything else need to be done?

2016-11-11 12:24 UTC, vitorgalvao approved these changes

2016-11-11 12:24 UTC, vitorgalvao commented
> Well, looks like you've just done that for me!

I did.

> Anything else need to be done?

No. I was just waiting for Travis.

2016-11-11 12:24 UTC, merged