Add cask for EurKEY v1.1
Homebrew/homebrew-cask pull request #26662
Opened 2016-11-10 22:33 UTC by saesh

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked that the cask was not already refused in [closed issues].

2016-11-11 00:07 UTC, vitorgalvao approved these changes

2016-11-11 20:55 UTC, reitermarkus requested changes

2016-11-11 20:55 UTC, reitermarkus commented on Casks/eurkey.rb
> +  version '1.1'
This should be `:latest`, since the download URL is unversioned.

2016-11-11 22:05 UTC, miccal commented on Casks/eurkey.rb
> +  sha256 'ef965dcb405378fb78cff8b89e69190d15b0e699ae773056e6c2cb9c66b9511d'
Should also be `sha256 :no_check`.

2016-11-12 00:18 UTC, Numbermaniac commented on Casks/eurkey.rb
> +  sha256 :no_check
You accidentally left a space at the end of this line.

2016-11-13 18:11 UTC, merged