Update vmware-appcatalyst (June 2016)
Homebrew/homebrew-cask pull request #26753
Opened 2016-11-14 15:46 UTC by displague

*If there’s a checkbox you can’t complete for any reason, that's okay, just explain in detail why you weren’t able to do so.*

After making all changes to the cask:

- [ ] `brew cask audit --download {{cask_file}}` is error-free.
- [ ] `brew cask style --fix {{cask_file}}` reports no offenses.
- [ ] The commit message includes the cask’s name and version.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference].
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked there are no [open pull requests] for the same cask.
- [ ] Checked that the cask was not already refused in [closed issues].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed

The license included in the previous version of VMware Appcatalyst has expired. http://blogs.vmware.com/cloudnative/appcatalyst-update/

The updated version includes a license that will expire in December 2016.

2016-11-14 16:00 UTC, vitorgalvao commented
There was a [pull request template](https://github.com/blog/2111-issue-and-pull-request-templates) when you submitted. It must be filled.

If you were not presented a template, you may have submitted via a CLI tool (likely [`hub`](https://hub.github.com/)). It that was the case, you may wish to see if the tool has a way to let you use the template (`hub` [is working on it](https://github.com/github/hub/issues/1118)).

In either case, please [refer to the template](https://raw.githubusercontent.com/caskroom/homebrew-cask/master/.github/PULL_REQUEST_TEMPLATE.md) and update your comment.

2016-11-14 16:02 UTC, vitorgalvao requested changes

2016-11-14 16:02 UTC, vitorgalvao commented on Casks/vmware-appcatalyst.rb
> +  sha256 '6ed3d6d6fc2ff54105eccf3435c316b728fa5da8'
This is not a `sha256` (too short).

2016-11-14 16:02 UTC, vitorgalvao commented on Casks/vmware-appcatalyst.rb
> +  version 'Update' # June-2016
Remove the comment. This makes no sense anymore, `Update` says nothing.

Seeing as `url` doesn’t point to a specific version, this cask should use `version :latest` and `sha256 :no_check`. [See an example](https://github.com/caskroom/homebrew-cask/blob/f25b6babcd398abf48e33af3d887b2d00de1d661/Casks/kibako.rb).

2016-11-14 16:02 UTC, vitorgalvao commented on Casks/vmware-appcatalyst.rb
>    url "http://getappcatalyst.com/downloads/VMware-AppCatalyst-Technical-Preview-#{version}.dmg"
Change to `url 'http://getappcatalyst.com/downloads/VMware-AppCatalyst-Technical-Preview-Update.dmg'`

2016-11-14 17:23 UTC, displague commented
Revised - thanks.

2016-11-14 17:51 UTC, vitorgalvao requested changes

2016-11-14 17:51 UTC, vitorgalvao commented on Casks/vmware-appcatalyst.rb
> +  sha256 'b8b99200e849079bbce4f8760950d6c4807d51a8c78ccccaca2bc3e04f467ddc'
Needs to be `:no_check`.

2016-11-17 01:53 UTC, adidalal commented
Thank you for the contribution. It needed some fixes, so they were made in 025ea7d9a2aa23411b522b7b42e6da130a38bec9. Your contribution is still included (and still credited to you), with the appropriate modifications. Please feel free to ask about any of the changes.

2016-11-17 01:53 UTC, closed without merging