Add "What's Your Sign?" 1.2.1
Homebrew/homebrew-cask pull request #26785
Opened 2016-11-15 14:26 UTC by listochkin

*If there’s a checkbox you can’t complete for any reason, that's okay, just explain in detail why you weren’t able to do so.*

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked that the cask was not already refused in [closed issues].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed

App uses same installer technique as all other Objective-See apps: zip contains an '*_Installer.app' that has to be manually run to install a helper for Finder.

2016-11-15 14:45 UTC, vitorgalvao requested changes

2016-11-15 14:45 UTC, vitorgalvao commented on Casks/whatsyoursign.rb
> +cask 'whatsyoursign' do
Corrected this.

2016-11-15 14:45 UTC, vitorgalvao commented on Casks/whatsyoursign.rb
> +  uninstall delete: '/Applications/WhatsYourSign.app'
It’s unlikely moving an app is the only thing the installer does. Please search their website or contact the developer for a thorough uninstall procedure.

2016-11-15 14:47 UTC, listochkin commented on Casks/whatsyoursign.rb
> +cask 'whatsyoursign' do
`"$(brew --repository)/Library/Taps/caskroom/homebrew-cask/developer/bin/generate_cask_token" "What's Your Sign?"` gave me `whats-your-sign`

2016-11-15 15:00 UTC, listochkin commented on Casks/whatsyoursign.rb
> +  uninstall delete: '/Applications/WhatsYourSign.app'
Yep, you're right. Turned out one has to run the `WhatsYourSign_Installer.app` again. How can I express in in Cask-file?

2016-11-15 23:39 UTC, Numbermaniac commented
According to their website:

Install:
a) copies WhatsYourSign.app into the /Applications directory
b) registers the Finder extension WhatsYourSign.appex
(found within WhatsYourSign.app/Contents/Plugins) 

Uninstall:
a) unregisters the Finder extension, WhatsYourSign.appex
b) removes the /Applications/WhatsYourSign.app directory (which also removes WhatsYourSign.appex)

2016-12-04 16:28 UTC, vitorgalvao commented
Closing for lack of reply.

2016-12-04 16:28 UTC, closed without merging