Add cask: Visual Studio for Mac preview-1
Homebrew/homebrew-cask pull request #26837
Opened 2016-11-16 22:53 UTC by joshka

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked that the cask was not already refused in [closed issues].

Note, this is distinct from Visual Studio Code. They can be installed
concurrently. I was unable to find any info on the installer arguments
for unattended installation, so this will show the user a UI.

See https://www.visualstudio.com/vs/visual-studio-mac/ to confirm download link.

2016-11-16 23:07 UTC, jawshooah commented
> I was unable to find any info on the installer arguments for unattended installation, so this will show the user a UI.

In that case, this needs `installer :manual`, not `:script`.

2016-11-17 22:55 UTC, joshka commented
> In that case, this needs installer :manual, not :script.
Done

2016-11-17 23:00 UTC, jawshooah commented
Looks like it's still using `script`. Are you sure you pushed the right branch?

2016-11-17 23:02 UTC, joshka commented
Heh, nope ;) Fixed it now.

Is changing to manual all that's required there, or does the path change as well?

2016-11-17 23:02 UTC, jawshooah commented on Casks/visual-studio.rb
> +  uninstall delete: '/Applications/Visual Studio.app'
Seems unlikely that the installer just unpacks an app bundle and drops it in `/Applications`. Are you sure there's nothing else to do here?

2016-11-17 23:03 UTC, jawshooah requested changes

2016-11-17 23:03 UTC, jawshooah commented on Casks/visual-studio.rb
> +  installer manual: 'Install Visual Studio for Mac Preview.app/Contents/MacOS/Install_Xamarin'
Just `installer manual: 'Install Visual Studio for Mac Preview.app'`

2016-11-17 23:12 UTC, joshka commented on Casks/visual-studio.rb
> +  uninstall delete: '/Applications/Visual Studio.app'
The installer downloads and installs a bunch of SDKs etc.
With that said, Visual Studio for Mac is Xamarin Studio rebadged which has the same problem, and it looks like some parts it installed are shared between the two making it not really possible to uninstall those parts sensibly on one or the other. What would you suggest here?

2016-11-17 23:15 UTC, joshka commented on Casks/visual-studio.rb
> +  installer manual: 'Install Visual Studio for Mac Preview.app/Contents/MacOS/Install_Xamarin'
Done

2016-11-19 12:58 UTC, vitorgalvao commented on Casks/visual-studio.rb
> +  uninstall delete: '/Applications/Visual Studio.app'
@joshka Is there any reason why you’d have both? If not, just add the rest of the uninstall.

2016-11-19 18:01 UTC, adidalal commented
Thank you for the contribution. It needed some fixes, so they were made in 721d04dc8304ff9215d8274797465b6fcd7baa89. Your contribution is still included (and still credited to you), with the appropriate modifications. Please feel free to ask about any of the changes.

2016-11-19 18:01 UTC, closed without merging

2016-11-19 18:26 UTC, vitorgalvao commented on Casks/visual-studio.rb
> +  uninstall delete: '/Applications/Visual Studio.app'
@adidalal Then we need to put said components in `zap`. As it is, `uninstall` is woefully incomplete, and there is no way to remove it correctly.