Add Upwork Desktop Latest Version
Homebrew/homebrew-cask pull request #26848
Opened 2016-11-17 07:51 UTC by bashu

*If there’s a checkbox you can’t complete for any reason, that's okay, just explain in detail why you weren’t able to do so.*

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked that the cask was not already refused in [closed issues].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed

replacement of oDesk Team, ref #26539

2016-11-17 08:17 UTC, miccal commented
I cannot see a link to this app from the homepage, I can only see a link to the [mobile app](https://www.upwork.com/i/mobile/)? Their [download page](https://www.upwork.com/downloads) appears to require a login?

2016-11-17 08:23 UTC, bashu commented
@miccal suddenly yes! but you can download / install desktop app using this formula and no login required

2016-11-17 08:26 UTC, miccal commented
Yes, but this may be classified as a [walled build](https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#unofficial-vendorless-and-walled-builds) which are not accepted for security reasons.

2016-11-17 08:35 UTC, bashu commented
@miccal should I PR to https://github.com/alehouse/homebrew-unofficial instead?

2016-11-17 08:37 UTC, miccal commented
Ping @vitorgalvao.

2016-11-17 08:46 UTC, bashu commented
@miccal @vitorgalvao Upwork Desktop is a successor of oDesk Team which was a part of homebrew-cask in a past, ref #26539

2016-11-17 14:31 UTC, vitorgalvao requested changes

2016-11-17 14:31 UTC, vitorgalvao commented on Casks/upwork.rb
> +~
This definitely is not right.

2016-11-17 14:31 UTC, vitorgalvao commented on Casks/upwork.rb
> +  version :latest
`version '4_2_88_0_zjqu5h1eh5fvxz5t'`

2016-11-17 14:31 UTC, vitorgalvao commented on Casks/upwork.rb
> +  sha256 :no_check
`sha256` also needs to be set. You can find what it is by running `shasum -a 256` on the downloaded file.

2016-11-17 14:31 UTC, vitorgalvao commented on Casks/upwork.rb
> +  url 'https://updates-desktopapp.upwork.com/binaries/v4_2_88_0_zjqu5h1eh5fvxz5t/Upwork.dmg'
`url "https://updates-desktopapp.upwork.com/binaries/v#{version}/Upwork.dmg"`

2016-11-17 14:34 UTC, vitorgalvao commented
Clarification regarding walled builds — see [the glossary](https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) (emphasis added):

> **Walled:** When the download URL is both behind a login/registration form **and from a host that differs from the homepage**.

That’s not the case, here. Issue is if you submit a casks with homepage `http://one.com` and the URL points to `http://two.com`. If the download URL is behind a registration/login wall, a user will have no easy way to know the download URL is trustworthy. If the download URL is from the same domain as the homepage, though, then you can be pretty sure the download is official (unless the website was hacked, but that would be an issue in every case).

2016-11-17 21:09 UTC, miccal commented
Thanks for the clarification @vitorgalvao.

2016-11-18 02:46 UTC, bashu commented on Casks/upwork.rb
> +  version :latest
@vitorgalvao fixed

2016-11-18 02:46 UTC, bashu commented on Casks/upwork.rb
> +~
@vitorgalvao what an ugly copy-paste! fixed

2016-11-18 02:49 UTC, bashu commented
@miccal @vitorgalvao thanks for feedback!

2016-11-18 05:41 UTC, miccal commented on Casks/upwork.rb
> +  url 'https://updates-desktopapp.upwork.com/binaries/v#{version}/Upwork.dmg'
You need double quotes around the URL for the interpolation to work, like so:
```
url "https://updates-desktopapp.upwork.com/binaries/v#{version}/Upwork.dmg"
```

2016-11-18 07:19 UTC, bashu commented
@miccal thank you

2016-11-18 10:45 UTC, merged