Update parallels-desktop to 12.1.1-41491
Homebrew/homebrew-cask pull request #26871
Opened 2016-11-17 22:58 UTC by ArtemMedvedev

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

---

Closes #.

2016-11-17 23:33 UTC, Numbermaniac commented
(Looks like you forgot the number after the # symbol)

2016-11-17 23:45 UTC, ArtemMedvedev commented
honestly, I don't know where it came from. I use [cask-repair](https://github.com/vitorgalvao/tiny-scripts/blob/master/cask-repair) to update the formulas, seems I accidentally add -c option

2016-11-18 00:23 UTC, jawshooah requested changes

2016-11-18 00:23 UTC, jawshooah commented on Casks/parallels-desktop.rb
>    url "https://download.parallels.com/desktop/v#{version[%r{^\w+}]}/#{version}/ParallelsDesktop-#{version}.dmg"
Use `version.major` instead of the regex capture.

2016-11-18 04:31 UTC, merged