Add PokerTH v1.1.1
Homebrew/homebrew-cask pull request #26904
Opened 2016-11-18 15:12 UTC by bashu

*If there’s a checkbox you can’t complete for any reason, that's okay, just explain in detail why you weren’t able to do so.*

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked that the cask was not already refused in [closed issues].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed

PokerTH is a poker game written in C++/Qt

2016-11-18 17:43 UTC, vitorgalvao requested changes

2016-11-18 17:43 UTC, vitorgalvao commented on Casks/pokerth.rb
> +  url "https://downloads.sourceforge.net/pokerth/PokerTH-#{version}.dmg"
`style` did not pass.

2016-11-19 01:53 UTC, bashu commented on Casks/pokerth.rb
> +  url "https://downloads.sourceforge.net/pokerth/PokerTH-#{version}.dmg"
@vitorgalvao fixed

2016-11-19 01:57 UTC, vitorgalvao approved these changes

2016-11-19 12:54 UTC, merged