Add The Ur-Quam Masters 0.7
Homebrew/homebrew-cask pull request #26903
Opened 2016-11-18 14:55 UTC by bashu

*If there’s a checkbox you can’t complete for any reason, that's okay, just explain in detail why you weren’t able to do so.*

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked that the cask was not already refused in [closed issues].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed

The Ur-Quan Masters is a science fiction video game

2016-11-18 17:43 UTC, vitorgalvao requested changes

2016-11-18 17:43 UTC, vitorgalvao commented on Casks/uqm.rb
> +cask 'uqm' do
Token reference was not followed.

2016-11-19 01:49 UTC, bashu commented on Casks/uqm.rb
> +cask 'uqm' do
@vitorgalvao fixed

2016-11-19 01:56 UTC, vitorgalvao approved these changes

2016-11-19 02:05 UTC, bashu commented on Casks/the-ur-quan-masters.rb
> +cask 'the-ur-quan-masters' do
@vitorgalvao but why "The Battle for Wesnoth" has cask named "wesnoth"

2016-11-19 12:44 UTC, vitorgalvao commented on Casks/the-ur-quan-masters.rb
> +cask 'the-ur-quan-masters' do
You’ve made cask submissions before. Have you never read the token reference, despite ticking that box?

This token is dependent on the name of the app bundle.

2016-11-19 12:45 UTC, merged