WIP: Add documentation for new option `pkg choices:`
Homebrew/homebrew-cask pull request #26964
Opened 2016-11-20 19:28 UTC by umireon

Related to Homebrew/brew#1535
I will work on this after I create an example (osxfuse).

2016-11-20 22:17 UTC, reitermarkus commented on doc/cask_language_reference/stanzas/pkg.md
> +## `pkg choices`:
The colon should probably also be inside the `.

2016-12-01 07:41 UTC, reitermarkus requested changes

2016-12-01 07:41 UTC, reitermarkus commented on doc/cask_language_reference/stanzas/pkg.md
> +See [this pull request of wireshark-chmodbpf](https://github.com/caskroom/homebrew-cask/pull/26997) for an example of the proceduce to extract the choices value, as well as their equivalents to the G
* procedure

2016-12-06 02:12 UTC, umireon commented
I added the real-world example and I think this document was complete.

2016-12-06 14:11 UTC, merged