Macfusion 2.1.1 dev.3
Homebrew/homebrew-cask pull request #26986
Opened 2016-11-21 11:01 UTC by umireon

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
---
MacFusion at 2.1-dev or under does not launch on Sierra.

2016-11-21 11:02 UTC, umireon commented on Casks/macfusion.rb
> +  appcast 'https://github.com/ElDeveloper/macfusion2/releases.atom',
I think the repository name will not necessary change when the major version is bumped.

2016-11-21 11:03 UTC, umireon commented on Casks/macfusion.rb
> +  homepage 'https://github.com/ElDeveloper/macfusion2/'
It seems that the former homepage is abandoned as well as the original repository.

2016-11-21 11:04 UTC, umireon commented on Casks/macfusion.rb
> +      File.symlink("#{Formula['sshfs'].bin}/sshfs", 'sshfs-static')
Since sshfs is now a Formula.

2016-11-21 18:53 UTC, vitorgalvao requested changes

2016-11-21 18:53 UTC, vitorgalvao commented on Casks/macfusion.rb
> +  appcast 'https://github.com/ElDeveloper/macfusion2/releases.atom',
> I think the repository name will not necessary change when the major version is bumped.

Perhaps not. But then again, perhaps it will. It’s best to leave it as it was and change back only if needed.

2016-11-21 18:55 UTC, vitorgalvao commented
Just noticed how wrong this cask is. It needs a prefix.

[See why](https://github.com/caskroom/homebrew-cask/pull/26945#issuecomment-261774577).

2016-11-21 19:02 UTC, umireon commented
Something like
cask 'eldeveloper-macfusion'
name 'ELDeveloper MacFusion'
?

2016-11-21 19:21 UTC, umireon commented
@vitorgalvao I changed this PR to be adding a new Cask eldeveloper-macfusion.

2016-11-21 22:03 UTC, vitorgalvao approved these changes

2016-11-22 01:57 UTC, miccal commented on Casks/eldeveloper-macfusion.rb
> +  homepage "https://github.com/ElDeveloper/macfusion2#{version.major}/"
This should be just `homepage "https://github.com/ElDeveloper/macfusion#{version.major}/"`.

2016-11-22 01:58 UTC, vitorgalvao commented on Casks/eldeveloper-macfusion.rb
> +  homepage "https://github.com/ElDeveloper/macfusion2#{version.major}/"
Nice catch. I can fix that.

2016-11-22 01:59 UTC, merged