Update tabula to 1.1.0
Homebrew/homebrew-cask pull request #26995
Opened 2016-11-21 15:02 UTC by dmofot

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

2016-11-21 18:21 UTC, vitorgalvao requested changes

2016-11-21 18:21 UTC, vitorgalvao commented on Casks/tabula.rb
> +  url "https://github.com/tabulapdf/tabula/releases/download/v#{version}/tabula-mac-#{version}c.zip"
`c` should be part of `version` above.

2016-11-21 19:53 UTC, dmofot commented
Ok, figured out that it should be `{{version.major_minor_patch}}` and added another commit.  Anything else I need to do?

2016-11-21 22:05 UTC, vitorgalvao commented
> Ok, figured out that it should be `{{version.major_minor_patch}}`

No, it should’ve been left as `version`. Your change is doing the same with more work.

2016-11-21 22:06 UTC, vitorgalvao approved these changes

2016-11-22 00:45 UTC, victorpopkov commented
Thank you for the changes and your contribution!

2016-11-22 00:45 UTC, merged