Update plantronics-hub to latest
Homebrew/homebrew-cask pull request #27011
Opened 2016-11-21 22:14 UTC by colindunn

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

2016-11-21 22:15 UTC, colindunn commented
Unfortunately they have removed individual links for the latest version and only supply version based links to older versions. The link to the latest version is now a constant, so changed to latest.

Also added auto_updates true and depends_on macos to complete the current version specifics.

2016-11-21 23:57 UTC, vitorgalvao requested changes

2016-11-21 23:57 UTC, vitorgalvao commented on Casks/plantronics-hub.rb
> +  auto_updates true
When an app auto-updates it has an [`appcast`](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/appcast.md). Can you figure out what it is?

2016-11-22 00:57 UTC, colindunn commented on Casks/plantronics-hub.rb
> +  auto_updates true
Spent some time trying to figure this out by doing a packet capture I can see that it goes to plantronicsmanager.com but not the actual address it's going to because it's HTTPS. Also tried to use a proxy to figure it out but no joy.

Should I remove the auto_updates flag?

2016-11-22 01:08 UTC, vitorgalvao approved these changes

2016-11-22 01:24 UTC, colindunn commented on Casks/plantronics-hub.rb
> +  auto_updates true
Thanks Vítor

2016-11-22 20:55 UTC, victorpopkov commented
Thank you for all the changes and your contribution!

2016-11-22 20:55 UTC, merged