Update homepage of 16 Casks
Homebrew/homebrew-cask pull request #27027
Opened 2016-11-22 15:05 UTC by miccal

Update homepage of 16 Casks.

Ping @victorpopkov

2016-11-22 21:18 UTC, victorpopkov requested changes

2016-11-22 21:18 UTC, victorpopkov commented on Casks/apm-planner.rb
>    appcast 'http://firmware.diydrones.com/Tools/APMPlanner/apm_planner_version.json',
There is also a domain changed in download and appcast URLs:
```ruby
  url "http://firmware.ardupilot.org/Tools/APMPlanner/apm_planner_#{version}_osx.dmg"
  appcast 'http://firmware.ardupilot.org/Tools/APMPlanner/apm_planner_version.json',
          checkpoint: 'c05e845dcfbcd54d6aaa3a597495483a526c5550cd06f6631ecee0cdfd68ab08'
```
The latest version is `2.0.24` so it also can be updated.

2016-11-23 00:30 UTC, victorpopkov requested changes

2016-11-23 00:30 UTC, victorpopkov commented on Casks/apm-planner.rb
> +          checkpoint: 'c05e845dcfbcd54d6aaa3a597495483a526c5550cd06f6631ecee0cdfd68ab08'  name 'APM Planner'
There is new line missing before `name`.

2016-11-23 00:31 UTC, miccal commented on Casks/apm-planner.rb
> +          checkpoint: 'c05e845dcfbcd54d6aaa3a597495483a526c5550cd06f6631ecee0cdfd68ab08'  name 'APM Planner'
Crap!

2016-11-23 02:20 UTC, victorpopkov approved these changes

2016-11-23 05:28 UTC, merged