Update homepage of 18 Casks
Homebrew/homebrew-cask pull request #27033
Opened 2016-11-22 16:26 UTC by miccal

Update homepage of 18 Casks.

Ping @victorpopkov

2016-11-22 21:45 UTC, victorpopkov requested changes

2016-11-22 21:45 UTC, victorpopkov commented on Casks/frizzix.rb
> +  homepage 'http://mac.frizzix.de/de/'
This should be left as is since is's used for localization purposes.

2016-11-22 21:45 UTC, victorpopkov commented on Casks/freeplane.rb
> +  homepage 'http://freeplane.sourceforge.net/wiki/index.php/Main_Page'
I would suggest to not change this and leave all the SourceForge links as they are.

2016-11-22 21:45 UTC, victorpopkov commented on Casks/eye-one-profiler.rb
> +  homepage 'http://www.xrite.com/categories/formulation-and-quality-assurance-software/i1Profiler'
This cask should be considered for removal. The download URL is dead.

2016-11-23 00:31 UTC, miccal commented
Thanks @victorpopkov - I will just revert the changes to those Casks that should be removed, and I will submit a separate PR later to remove them.

2016-11-23 02:21 UTC, victorpopkov approved these changes

2016-11-23 05:27 UTC, merged