Updated VisTrails to v2.2.4-1519abc0ae2b
Homebrew/homebrew-cask pull request #27068
Opened 2016-11-23 15:13 UTC by scottsideleau

- [ x ] `brew cask audit --download {{cask_file}}` is error-free.

One warning observed WRT SourceForge URL format, but review of reference reveals that URL format follows recommendation for MacOS-exclusive distributions.

- [ x ] `brew cask style --fix {{cask_file}}` reports no offenses.

One warning observed WRT the comment.  I am updating a pre-existing comment to be more relevant.

The 'rubocop' appears to incorrectly indent the 'checkpoint' parameter of appcast, which -- according to the documentation -- should be indented by 2-spaces and not "aligned with the method call" as it attempts to autofix.

- [ x ] The commit message includes the cask’s name and version.

Please let me know if you have any questions or concerns.

Cheers,
Scott

2016-11-23 21:38 UTC, vitorgalvao commented
All the warnings you encountered need to be fixed. `style` is correct. If the documentation contradicts it, then the documentation is wrong and we need to fix it. Please point me to the location so I can take care of it.

2016-11-23 21:38 UTC, vitorgalvao requested changes

2016-11-23 21:38 UTC, vitorgalvao commented on Casks/vistrails.rb
> +  # sourceforge.net/project/vistrails has been verified as official
Don’t change the comment. It’s standard and needs to be left as is.

2016-11-23 21:39 UTC, vitorgalvao requested changes

2016-11-23 21:39 UTC, vitorgalvao commented on Casks/vistrails.rb
> -  homepage 'https://www.vistrails.org/index.php/Main_Page'
This was also correct. The page redirects here.

2016-11-23 21:46 UTC, vitorgalvao commented
> but review of reference reveals that URL format follows recommendation for MacOS-exclusive distributions.

That is *only* if none of the other formats work, which is not the case.

Thank you for the submission, but it has several disparate issues it was easier to fix in a different PR: https://github.com/caskroom/homebrew-cask/pull/27081.

Please feel free to ask about any detail of the update. Thank you for the report of the outdated cask.

2016-11-23 21:46 UTC, closed without merging

2016-11-23 21:58 UTC, vitorgalvao commented
Found the 2-space rule. Making it cleaerer in https://github.com/caskroom/homebrew-cask/pull/27083/commits/b0e571c58ac61a10d081f38a13989e3322f35d2d.

2016-11-24 04:29 UTC, scottsideleau commented
Thank you for updating the documentation.