Update little-snitch to 3.7
Homebrew/homebrew-cask pull request #27185
Opened 2016-11-27 14:00 UTC by miccal

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

2016-11-27 14:03 UTC, vitorgalvao requested changes

2016-11-27 14:03 UTC, vitorgalvao commented on Casks/little-snitch.rb
> +  uninstall script: '/Library/Little Snitch/Little Snitch Uninstaller.app/Contents/MacOS/Little Snitch Uninstaller'
This will call a GUI, so it’s no good.

2016-11-27 14:04 UTC, closed without merging

2016-11-27 14:09 UTC, miccal commented on Casks/little-snitch.rb
> +  uninstall script: '/Library/Little Snitch/Little Snitch Uninstaller.app/Contents/MacOS/Little Snitch Uninstaller'
Of course, apologies. Any idea how we can add this then? The Little Snitch documentation says to run the app /Library/Little Snitch/Little Snitch Uninstaller.app.

2016-11-27 14:15 UTC, vitorgalvao commented on Casks/little-snitch.rb
> +  uninstall script: '/Library/Little Snitch/Little Snitch Uninstaller.app/Contents/MacOS/Little Snitch Uninstaller'
A possible solution would be to contact the developer and ask if it would be possible to have a CLI script to perform the same steps the GUI does.

2016-11-27 14:22 UTC, miccal commented on Casks/little-snitch.rb
> +  uninstall script: '/Library/Little Snitch/Little Snitch Uninstaller.app/Contents/MacOS/Little Snitch Uninstaller'
Should we instead add a caveat to the Cask, something like "To uninstall Little Snitch run the .app located at  /Library/Little Snitch/Little Snitch Uninstaller.app" or similar?

2016-11-27 15:02 UTC, vitorgalvao commented on Casks/little-snitch.rb
> +  uninstall script: '/Library/Little Snitch/Little Snitch Uninstaller.app/Contents/MacOS/Little Snitch Uninstaller'
No, we need to properly fix it.

2016-11-27 15:15 UTC, miccal commented on Casks/little-snitch.rb
> +  uninstall script: '/Library/Little Snitch/Little Snitch Uninstaller.app/Contents/MacOS/Little Snitch Uninstaller'
Here is a screenshot of the relevant documentation:

<img width="1268" alt="screen shot 2016-11-27 at 23 10 54" src="https://cloud.githubusercontent.com/assets/6127163/20649291/0f6d20d8-b4f7-11e6-9452-adc48ef1001e.png">

The only thing I can think of at the moment is to move the files in the attached image from the `zap` stanza to an `uninstall` stanza.

I know that is not perfect, but I cannot see how to properly fix this.

2016-11-27 15:57 UTC, vitorgalvao commented on Casks/little-snitch.rb
> +  uninstall script: '/Library/Little Snitch/Little Snitch Uninstaller.app/Contents/MacOS/Little Snitch Uninstaller'
> but I cannot see how to properly fix this.

Like I said, contacting the developer is a good first step. If they don’t reply or say “no”, then it’s time to think of another thing.

2016-11-27 16:00 UTC, miccal commented on Casks/little-snitch.rb
> +  uninstall script: '/Library/Little Snitch/Little Snitch Uninstaller.app/Contents/MacOS/Little Snitch Uninstaller'
It's worth a try, I will send them an email (I actually use this program and this have a valid licence).

Sorry I could not be of more help.

2016-12-05 09:30 UTC, miccal commented on Casks/little-snitch.rb
> +  uninstall script: '/Library/Little Snitch/Little Snitch Uninstaller.app/Contents/MacOS/Little Snitch Uninstaller'
@vitorgalvao I received a reply from the developers of Little Snitch - their response was that running the Little Snitch Uninstaller.app is the only way to completely remove the program and they claimed that a `.sh` script would not be as thorough and therefore saw no need to develop one.

Although my comment above about an `uninstaller manual:` was in jest, in all seriousness could it be a possibility as a last resort for an edge case like this one?