Create libreoffice-language-pack.rb
Homebrew/homebrew-cask pull request #27193
Opened 2016-11-27 22:45 UTC by bunam

*If there’s a checkbox you can’t complete for any reason, that's okay, just explain in detail why you weren’t able to do so.*

After making all changes to the cask:

- [ ] `brew cask audit --download {{cask_file}}` is error-free.
- [ ] `brew cask style --fix {{cask_file}}` reports no offenses.
- [ ] The commit message includes the cask’s name and version.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference].
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked there are no [open pull requests] for the same cask.
- [ ] Checked that the cask was not already refused in [closed issues].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed

2016-11-27 22:49 UTC, vitorgalvao commented
You need to complete the template in your top post.

Also, as I mentioned in the other issue, there are multiple issues here. I’ll fix some and discuss the others.

2016-11-27 22:49 UTC, miccal commented on Casks/libreoffice-language-pack.rb
> +
Please remove one of these two new lines.

2016-11-27 22:49 UTC, miccal commented on Casks/libreoffice-language-pack.rb
> +
Please remove one of these two new lines.

2016-11-27 22:49 UTC, miccal commented on Casks/libreoffice-language-pack.rb
> +    key_id: 'c2839ecad9408fbe9531c3e9f434a1efafeeaea3'
Please combine these two lines into a single line, like so:
```
gpg "#{url}.asc", key_id: 'c2839ecad9408fbe9531c3e9f434a1efafeeaea3'
```

2016-11-27 22:52 UTC, vitorgalvao requested changes

2016-11-27 22:52 UTC, vitorgalvao commented on Casks/libreoffice-language-pack.rb
> +    system '/usr/bin/sudo', '-E', '--', '/usr/bin/tar', '-C', '/Applications/LibreOffice.app/', '-xjf', "#{staged_path}/LibreOffice Language Pack.app/Contents/tarball.tar.bz2"
Don’t use `/Applications`, use `#{appdir}`.

2016-11-27 22:52 UTC, vitorgalvao commented on Casks/libreoffice-language-pack.rb
> +    system '/usr/bin/sudo', '-E', '--', '/usr/bin/tar', '-C', '/Applications/LibreOffice.app/', '-xjf', "#{staged_path}/LibreOffice Language Pack.app/Contents/tarball.tar.bz2"
Why is this needed? And why does it use `sudo`?

2016-11-27 22:52 UTC, vitorgalvao commented on Casks/libreoffice-language-pack.rb
> +    system '/usr/bin/sudo', '-E', '--', '/usr/bin/tar', '-C', '/Applications/LibreOffice.app/', '-xjf', "#{staged_path}/LibreOffice Language Pack.app/Contents/tarball.tar.bz2"
This cask is missing an artifact.

2016-11-27 23:06 UTC, miccal commented on Casks/libreoffice-language-pack.rb
> +#  end
Please remove these commented lines.

2016-11-27 23:06 UTC, miccal commented on Casks/libreoffice-language-pack.rb
> +  language 'en-GB' , default: true do
Please remove the space between `en-GB` and the comma.

2016-11-27 23:06 UTC, miccal commented on Casks/libreoffice-language-pack.rb
> +  url "http://download.documentfoundation.org/libreoffice/stable/#{version}/mac/x86_64/LibreOffice_#{version}_MacOS_x86-64_langpack_#{language}.dmg"
A comment in needed above the `url` stanza, like so:
```
# documentfoundation.org was verified as official when first introduced to the cask
```

2016-11-27 23:06 UTC, miccal commented on Casks/libreoffice-language-pack.rb
> +
Please remove this empty line.

2016-11-27 23:09 UTC, miccal commented on Casks/libreoffice-language-pack.rb
> +
Please add an `artifact`, like so:
```
app 'LibreOffice Language Pack.app'
```

2016-11-27 23:12 UTC, bunam commented on Casks/libreoffice-language-pack.rb
> +#  end
did you have any cue why it generate error like : 
`Error: 'ca-valencia' cannot be parsed to a Locale while loading 'libreoffice-language-pack' from '/opt/homebrew/Library/Taps/caskroom/homebrew-cask/Casks/libreoffice-language-pack.rb'`

2016-11-27 23:19 UTC, miccal commented on Casks/libreoffice-language-pack.rb
> +#  end
I assume because the language Catalan (Valencian) does not have a recognised language code.

2016-11-27 23:20 UTC, miccal commented on Casks/libreoffice-language-pack.rb
> +
Why is it unnecessary?

2016-11-27 23:29 UTC, bunam commented on Casks/libreoffice-language-pack.rb
> +
i'm using directly the archive inside the installer to do the job LibreOffice Language Pack.app/Contents/tarball.tar.bz2 , after this step the content is dispatched in the LibreOffice app, there is no "desktop action" to do
you can install all the 109 languages ;)
you just have to select the good on one the LibreOffice settings

2016-11-27 23:35 UTC, miccal commented on Casks/libreoffice-language-pack.rb
> +
I'll leave @vitorgalvao to discuss this.

2016-11-27 23:43 UTC, bunam commented on Casks/libreoffice-language-pack.rb
> +    system '/usr/bin/sudo', '-E', '--', '/usr/bin/tar', '-C', '/Applications/LibreOffice.app/', '-xjf', "#{staged_path}/LibreOffice Language Pack.app/Contents/tarball.tar.bz2"
I have read the applescript provided in any Libreoffice language pack but with a new test it's no necessary with full brew install.

i have updated WIP http://pastebin.com/W5LsvG2e

2016-11-27 23:54 UTC, adidalal commented on Casks/libreoffice-language-pack.rb
> +
An app needs at least one artifact stanza, if I remember correctly. Though maybe we could use 'artifact :none` or something like that.

2016-11-27 23:55 UTC, adidalal commented on Casks/libreoffice-language-pack.rb
> +    system '/usr/bin/sudo', '-E', '--', '/usr/bin/tar', '-C', '/Applications/LibreOffice.app/', '-xjf', "#{staged_path}/LibreOffice Language Pack.app/Contents/tarball.tar.bz2"
This technically doesn't require sudo, unless LibeOffice is installed outside of HBC (then permissions may be denied)

2016-11-28 00:50 UTC, miccal commented on Casks/libreoffice-language-pack.rb
> +  language 'kmr-Latn' do
Please change this to just `language 'kmr' do`.

2016-11-28 00:51 UTC, miccal commented on Casks/libreoffice-language-pack.rb
> +  language 'pa-IN' do
Please change this to just `language 'pa' do`.

2016-11-28 00:51 UTC, miccal commented on Casks/libreoffice-language-pack.rb
> +  language 'sa-IN' do
Please change this to just `language 'sa' do`.

2016-11-28 00:52 UTC, miccal commented on Casks/libreoffice-language-pack.rb
> +  language 'sw-TZ' do
Please change this to just `language 'sw' do`.

2016-11-28 00:52 UTC, miccal commented on Casks/libreoffice-language-pack.rb
> +  language 'zh-CN' do
Please change this to just `language 'zh' do`.

2016-11-28 12:29 UTC, reitermarkus commented on Casks/libreoffice-language-pack.rb
> +  language 'kmr-Latn' do
This is actually supported. See https://github.com/Homebrew/brew/blob/c521ff4a94328d02d345b13d65f3c5942cf613e9/Library/Homebrew/locale.rb#L7.

2016-11-28 12:30 UTC, reitermarkus commented on Casks/libreoffice-language-pack.rb
> +  language 'pa-IN' do
This is also supported, so no need to change this.

2016-11-28 12:30 UTC, reitermarkus commented on Casks/libreoffice-language-pack.rb
> +  language 'sa-IN' do
Same with this, and the others with the same format.

2016-11-29 22:46 UTC, miccal commented on Casks/libreoffice-language-pack.rb
> +
@vitorgalvao so what are your thoughts on this? Should we use the `preflight` as suggested by @bunam and add `stage_only true`?

2016-11-29 23:03 UTC, bunam commented on Casks/libreoffice-language-pack.rb
> +
i planned to put 
`  stage_only true`
2 lines below
`  depends_on cask: 'libreoffice'` 

i probably have time to correct all this file this week end

2016-12-07 12:34 UTC, vitorgalvao commented
Closing in favour of https://github.com/caskroom/homebrew-cask/pull/27465.

2016-12-07 12:34 UTC, closed without merging

2016-12-07 12:53 UTC, bunam commented
it's better like that ;)