Add Pale Moon version 26.5.0
Homebrew/homebrew-cask pull request #27191
Opened 2016-11-27 22:30 UTC by ibrokemypie

After making all changes to the cask:

- [ ] `brew cask audit --download {{cask_file}}` is error-free.
- [ ] `brew cask style --fix {{cask_file}}` reports no offenses.
- [ ] The commit message includes the cask’s name and version.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference].
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked there are no [open pull requests] for the same cask.
- [ ] Checked that the cask was not already refused in [closed issues].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed

Adds the app Pale Moon (Newmoon.app) for MacOS. Would like to add version 27 seperately as it is a major rebase that breaks some features.

2016-11-27 22:53 UTC, miccal commented on Casks/palemoon.rb
> +  version '26.5.0'
Please change the `version` to `6.5.0-131`.

2016-11-27 22:53 UTC, miccal commented on Casks/palemoon.rb
> +  url 'https://mac.palemoon.org/dist/palemoon-26.5.0-131-gstreamer.en-US.mac64.dmg'
Please change this to
```
url "https://mac.palemoon.org/dist/palemoon-#{version}-gstreamer.en-US.mac64.dmg"
```

2016-11-28 00:09 UTC, miccal commented on Casks/palemoon.rb
> +  version '26.5.0'
Yes, that is what I meant.

2016-11-28 01:25 UTC, vitorgalvao requested changes

2016-11-28 01:25 UTC, vitorgalvao commented on Casks/palemoon.rb
> +cask 'palemoon' do
Token reference was not followed.

2016-11-28 01:51 UTC, ibrokemypie commented on Casks/palemoon.rb
> +cask 'palemoon' do
token reference says to use newmoon as the file is called NewMoon.app, however the application is official named Pale Moon, so went with that

2016-11-28 02:24 UTC, vitorgalvao commented on Casks/palemoon.rb
> +cask 'palemoon' do
And the token reference also explains why that doesn’t matter and why it must be followed.

2016-11-28 03:55 UTC, ibrokemypie commented on Casks/palemoon.rb
> +cask 'palemoon' do
have updated to follow token reference

2016-11-28 11:23 UTC, vitorgalvao approved these changes

2016-11-29 02:00 UTC, merged