FileBot 4.7.5
Homebrew/homebrew-cask pull request #27220
Opened 2016-11-28 21:29 UTC by rednoah

2016-11-28 22:52 UTC, vitorgalvao commented
There was a [pull request template](https://github.com/blog/2111-issue-and-pull-request-templates) when you submitted. It contains [steps that must be followed](https://raw.githubusercontent.com/caskroom/homebrew-cask/master/.github/PULL_REQUEST_TEMPLATE.md).

If you were not presented a template, you may have submitted via a CLI tool (likely [`hub`](https://hub.github.com/)). It that was the case, you may wish to see if the tool has a way to let you use the template (`hub` [is working on it](https://github.com/github/hub/issues/1118)).

2016-11-28 22:52 UTC, vitorgalvao requested changes

2016-11-28 22:52 UTC, vitorgalvao commented on Casks/filebot.rb
> +  # The darwin package only includes the CLI tools. Launching the app merely redirects to the Mac App Store.
Could you explain this?

2016-11-29 17:45 UTC, rednoah commented
I deleted the template after checking all the requirements. I thought it's just a reminder for people submitting pull requests.

2016-11-30 12:11 UTC, merged