Create QOwnNotes Cask with v16.11.16
Homebrew/homebrew-cask pull request #27248
Opened 2016-11-29 18:39 UTC by cornercase

*If there’s a checkbox you can’t complete for any reason, that's okay, just explain in detail why you weren’t able to do so.*

After making all changes to the cask:

- [ x ] `brew cask audit --download {{cask_file}}` is error-free.
- [ x ] `brew cask style --fix {{cask_file}}` reports no offenses.
- [ x ] The commit message includes the cask’s name and version.

Additionally, **if adding a new cask**:

- [ x ] Named the cask according to the [token reference].
- [ x ] `brew cask install {{cask_file}}` worked successfully.
- [ x ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ x ] Checked there are no [open pull requests] for the same cask.
- [ x ] Checked that the cask was not already refused in [closed issues].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed

2016-11-29 19:44 UTC, vitorgalvao requested changes

2016-11-29 19:44 UTC, vitorgalvao commented on Casks/qownnotes.rb
> +  url "https://github.com/pbek/QOwnNotes/releases/download/macosx-#{version.after_comma}/QOwnNotes-#{version.after_comma}.dmg"
Please add an [`appcast`](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/appcast.md).

2016-11-29 20:44 UTC, cornercase commented
Accepted all changes, but corrected second instance of version.after_comma to version.before_comma to create correct download URL.  Appcast included.

2016-11-29 20:44 UTC, vitorgalvao approved these changes

2016-11-30 23:31 UTC, miccal requested changes

2016-11-30 23:31 UTC, miccal commented on Casks/qownnotes.rb
> +          checkpoint: '8428e3522fe51de301d61cf8e98fbe42b1ddab9a07e3c4ba03508086b683d6c6'
```
- appcast checkpoint mismatch
Expected: 8428e3522fe51de301d61cf8e98fbe42b1ddab9a07e3c4ba03508086b683d6c6
Actual: b50fae2bbdc57ad400b02198baec98eccef6731ee1343f6042129ffab3be441b
```

2016-12-03 15:13 UTC, merged

2016-12-03 15:17 UTC, adidalal commented
Merged and updated to latest version in https://github.com/caskroom/homebrew-cask/pull/27347


Check out `cask-repair`, it makes Cask updates like this quite easy (details in [CONTRIBUTING](https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md))

ie. `cask-repair -v 16.12.0,b2568-113120 qownnotes`