Add DarwiinRemoteOSC 0.6
Homebrew/homebrew-cask pull request #27272
Opened 2016-11-30 20:18 UTC by leafac

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked that the cask was not already refused in [closed issues].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed

2016-11-30 20:56 UTC, miccal commented on Casks/darwiin-remote-osc.rb
> +  sha256 'f98c6c982182ae899af0e1f729120242544e5b3231002802aaef8d565068fcb9'
Seeing as `url` doesn’t point to a specific version, this cask should use `version :latest` and `sha256 :no_check`.

2016-11-30 21:58 UTC, vitorgalvao requested changes

2016-11-30 21:58 UTC, vitorgalvao commented on Casks/darwiin-remote-osc.rb
> +cask 'darwiin-remote-osc' do
Token reference was not followed.

2016-11-30 21:58 UTC, vitorgalvao requested changes

2016-11-30 21:58 UTC, vitorgalvao commented on Casks/darwiinremoteosc.rb
> +  version '0.6'
Seeing as `url` doesn’t point to a specific version, this cask should use `version :latest` and `sha256 :no_check`. [See an example](https://github.com/caskroom/homebrew-cask/blob/f25b6babcd398abf48e33af3d887b2d00de1d661/Casks/kibako.rb).

2016-11-30 22:00 UTC, vitorgalvao approved these changes

2016-12-01 00:12 UTC, merged

2016-12-01 11:42 UTC, leafac commented
Thank you all for the fixes and for merging my contribution! 👍