Update omnipresence to 1.5.1
Homebrew/homebrew-cask pull request #27772
Opened 2016-12-14 11:03 UTC by colindunn

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

2016-12-14 11:06 UTC, colindunn commented
Hoping my definition of versioning in the path makes sense. Could just use MacOS.version except that both 10.11 and 10.12 are usable on the latest version which doesn't match the others. Anyway, let me know if there is a better way here

2016-12-14 13:15 UTC, vitorgalvao requested changes

2016-12-14 13:15 UTC, vitorgalvao commented on Casks/omnipresence.rb
> +  else # MacOS.version >= :el_capitan
Remove the comment.

2016-12-14 13:15 UTC, vitorgalvao commented on Casks/omnipresence.rb
> +  url "https://downloads.omnigroup.com/software/MacOSX/#{osx_version_path}/OmniPresence-#{version}.dmg"
Yes, use `MacOS.version` instead.

2016-12-14 13:15 UTC, vitorgalvao commented on Casks/omnipresence.rb
> +    osx_version_path = '10.11'
If `10.12` also works, no point in freezing this one, then.

2016-12-14 21:01 UTC, colindunn commented
The links are as follows:

mavericks: https://downloads.omnigroup.com/software/MacOSX/10.9/OmniPresence-1.2-r220586.dmg
yosemite: https://downloads.omnigroup.com/software/MacOSX/10.10/OmniPresence-1.4.1.dmg
el_capitan: https://downloads.omnigroup.com/software/MacOSX/10.11/OmniPresence-1.5.1.dmg
sierra: https://downloads.omnigroup.com/software/MacOSX/10.11/OmniPresence-1.5.1.dmg

Sierra doesn't use 10.12, which was why I didn't use MacOS.version but used a variable instead, trying to avoid using url in each if block.

Would you prefer me to just use url in each instead of doing it this way?

2016-12-14 21:01 UTC, colindunn commented on Casks/omnipresence.rb
> +  url "https://downloads.omnigroup.com/software/MacOSX/#{osx_version_path}/OmniPresence-#{version}.dmg"
See below

2016-12-14 21:01 UTC, colindunn commented on Casks/omnipresence.rb
> +    osx_version_path = '10.11'
See below

2016-12-14 21:01 UTC, colindunn commented on Casks/omnipresence.rb
> +  else # MacOS.version >= :el_capitan
Will do

2016-12-14 22:33 UTC, vitorgalvao commented
Using the variable in some and setting one of them to a fixed value seems inelegant. We don’t really gain anything by using `MacOS.version` in the early versions (which will not receive more updates and hence not change) if for the later versions we need a fixed value.

I’d rather use the `*_comma` methods. So we’d have `version '1.2-r220586,10.9'` and so forth. The URL would use `"https://downloads.omnigroup.com/software/MacOSX/#{version.after_comma}/OmniPresence-#{version.before_comma}.dmg"`.

2016-12-14 23:10 UTC, colindunn commented
Done

2016-12-15 00:46 UTC, vitorgalvao approved these changes

2016-12-15 05:41 UTC, merged