Update royal-tsx to 3.0.0.1000
Homebrew/homebrew-cask pull request #28008
Opened 2016-12-19 18:03 UTC by artdevjs

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

2016-12-19 19:17 UTC, vitorgalvao requested changes

2016-12-19 19:17 UTC, vitorgalvao commented on Casks/royal-tsx.rb
> +  url "https://royaltsx-v3.royalapplications.com/updates/royaltsx_#{version}.dmg"
`url "https://royaltsx-v#{version.major}.royalapplications.com/updates/royaltsx_#{version}.dmg"`

2016-12-20 10:12 UTC, miccal commented
`brew cask style` is failing as the comment above the `url` stanza does not match due to the interpolation, but otherwise everything else is fine.

2016-12-20 10:12 UTC, miccal approved these changes

2016-12-20 13:42 UTC, vitorgalvao commented
@miccal You’re right, hadn’t noticed. Apologies, @artdevjs, mind changing it back? Since the major number changes only sporadically, it’s preferable to have the cask not break on checks.

I remember we had similar cases when introducing this cop. Did we have a better solution, @reitermarkus?

2016-12-20 15:50 UTC, vitorgalvao commented
Closed by mistake.

2016-12-21 04:54 UTC, adidalal commented
https://github.com/caskroom/homebrew-cask/pull/28069

2016-12-21 04:54 UTC, closed without merging