Add BRL-CAD / MGED.app v7.24.0
Homebrew/homebrew-cask pull request #28263
Opened 2016-12-26 09:01 UTC by kaine119

*If there’s a checkbox you can’t complete for any reason, that's okay, just explain in detail why you weren’t able to do so.*

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked that the cask was not already refused in [closed issues].

`generate_cask_token` suggests "brl-cad-mged"; I've removed "mged" from the cask. From what I've experienced most people just refer to the software as brl-cad; mged is just a component of it. I'm not entirely sure, though.

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed

2016-12-26 09:12 UTC, miccal requested changes

2016-12-26 09:12 UTC, miccal commented on Casks/brl-cad.rb
> +  url 'https://downloads.sourceforge.net/brlcad/BRL-CAD%20for%20Mac%20OS%20X/7.24.0/BRL-CAD%207.24.0.dmg'
Please change this to `url "https://downloads.sourceforge.net/brlcad/BRL-CAD%20for%20Mac%20OS%20X/#{version}/BRL-CAD%20{version}.dmg"`.

2016-12-26 09:18 UTC, kaine119 commented on Casks/brl-cad.rb
> +  url 'https://downloads.sourceforge.net/brlcad/BRL-CAD%20for%20Mac%20OS%20X/7.24.0/BRL-CAD%207.24.0.dmg'
Alright, done.

2016-12-26 09:22 UTC, miccal approved these changes

2016-12-26 14:10 UTC, vitorgalvao requested changes

2016-12-26 14:10 UTC, vitorgalvao commented on Casks/brl-cad-mged.rb
> +  url "https://downloads.sourceforge.net/brlcad/BRL-CAD%20for%20Mac%20OS%20X/#{version}/BRL-CAD%20#{version}.dmg"
Please add an [`appcast`](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/appcast.md).

2016-12-26 14:27 UTC, miccal commented on Casks/brl-cad-mged.rb
> +  url "https://downloads.sourceforge.net/brlcad/BRL-CAD%20for%20Mac%20OS%20X/#{version}/BRL-CAD%20#{version}.dmg"
Thanks @vitorgalvao, I missed that.

2016-12-26 23:43 UTC, kaine119 commented on Casks/brl-cad-mged.rb
> +  url "https://downloads.sourceforge.net/brlcad/BRL-CAD%20for%20Mac%20OS%20X/#{version}/BRL-CAD%20#{version}.dmg"
Alright, done. Sorry for the wait; I was asleep

2016-12-27 00:35 UTC, vitorgalvao approved these changes

2016-12-27 00:35 UTC, merged