Add MySQL Shell v1.0.5
Homebrew/homebrew-cask pull request #28293
Opened 2016-12-27 07:20 UTC by SNakano

*If there’s a checkbox you can’t complete for any reason, that's okay, just explain in detail why you weren’t able to do so.*

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked that the cask was not already refused in [closed issues].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed

2016-12-27 07:33 UTC, miccal requested changes

2016-12-27 07:33 UTC, miccal commented on Casks/mysql-shell.rb
> +  homepage 'https://dev.mysql.com/doc/refman/5.7/en/mysql-shell.html'
Please change this to `homepage 'http://dev.mysql.com/downloads/shell/'`.

2016-12-27 08:43 UTC, SNakano commented on Casks/mysql-shell.rb
> +  homepage 'https://dev.mysql.com/doc/refman/5.7/en/mysql-shell.html'
Thanks review. I changed it.

2016-12-27 08:52 UTC, miccal approved these changes

2016-12-30 02:13 UTC, merged

2016-12-30 02:13 UTC, miccal commented
Thank you for your contribution.