Add F-Secure Anti-Virus v16.4
Homebrew/homebrew-cask pull request #28476
Opened 2017-01-02 12:52 UTC by dcondrey

Note that the install is very slow.  It takes several minutes to complete but it does complete successfully.  I do not know why it takes so long.

*If there’s a checkbox you can’t complete for any reason, that's okay, just explain in detail why you weren’t able to do so.*

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked that the cask was not already refused in [closed issues].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed

2017-01-02 16:58 UTC, vitorgalvao requested changes

2017-01-02 16:58 UTC, vitorgalvao commented on Casks/f-secure-anti-virus.rb
> +  version ':latest'
`':latest'` is invalid. You mean `:latest` (no quotes).

2017-01-02 16:58 UTC, vitorgalvao commented on Casks/f-secure-anti-virus.rb
> +  sha256 'bd22b8841b8ebbc178936afbf9a6c6668750e1cfc313500419fe4d7b5960542c'
Seeing as `url` doesn’t point to a specific version, this cask should use `version :latest` and `sha256 :no_check`. [See an example](https://github.com/caskroom/homebrew-cask/blob/f25b6babcd398abf48e33af3d887b2d00de1d661/Casks/kibako.rb).

2017-01-02 16:58 UTC, vitorgalvao commented on Casks/f-secure-anti-virus.rb
> +  uninstall script: '/usr/local/f-secure/bin/uninstall_MacProtection'
Add a `pkgutil` in addition to the script.

2017-01-02 21:25 UTC, miccal commented on Casks/f-secure-anti-virus.rb
> +  uninstall script: '/usr/local/f-secure/bin/uninstall_MacProtection'
Using the commands listed [here](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/uninstall.md#working-with-a-pkg-file-manually), you need to add the following to the `pkgutil:`:
```
com.f-secure.agents-and-daemons
com.f-secure.aua
com.f-secure.fsmac
com.f-secure.fsmac.bin
com.f-secure.fsmac.customization
com.f-secure.fsmac.fsauth
com.f-secure.fsmac.gui
com.f-secure.fsmac.gui.customization
com.f-secure.fsmac.lib
com.f-secure.fsmac.tools
com.f-secure.fssp
com.f-secure.orspclient
```

2017-01-03 00:42 UTC, miccal commented on Casks/f-secure-anti-virus.rb
> +  uninstall script: '/usr/local/f-secure/bin/uninstall_MacProtection'
Investigating the `.mpkg`, I think the `uninstall script:` also requires `sudo` - see an example [here](https://github.com/caskroom/homebrew-cask/blob/master/Casks/drobo-dashboard.rb).

@dcondrey please confirm that `brew cask uninstall f-secure-anti-virus` does indeed work.

2017-01-08 23:56 UTC, dcondrey commented
Updated based on feedback and uninstall does complete successfully.

2017-01-09 00:11 UTC, miccal approved these changes

2017-01-09 00:42 UTC, merged

2017-01-09 00:42 UTC, vitorgalvao commented
Thank you.

2017-01-09 02:09 UTC, dcondrey commented
Thank you.