Add ExNihilo.app v1.5.1
Homebrew/homebrew-cask pull request #28479
Opened 2017-01-02 17:17 UTC by Vayn

*If there’s a checkbox you can’t complete for any reason, that's okay, just explain in detail why you weren’t able to do so.*

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked that the cask was not already refused in [closed issues].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed

2017-01-02 17:21 UTC, vitorgalvao approved these changes

2017-01-02 17:53 UTC, vitorgalvao requested changes

2017-01-02 17:53 UTC, vitorgalvao commented on Casks/exnihilo.rb
> +  appcast 'https://vayn.github.io/ex-nihilo/release/appcast.xml',
Use `https://github.com/Vayn/ex-nihilo/releases.atom` instead.

2017-01-02 18:10 UTC, Vayn commented on Casks/exnihilo.rb
> +  appcast 'https://vayn.github.io/ex-nihilo/release/appcast.xml',
I used `find_sparkle_appcast` to generate appcast line. I think releases.atom is duplicated.

2017-01-02 20:13 UTC, vitorgalvao commented on Casks/exnihilo.rb
> +  appcast 'https://vayn.github.io/ex-nihilo/release/appcast.xml',
Because sparkle appcasts tend to be forgotten and become outdated. A github releases appcast is automatically generated, and will always be up to date with the current `url` scheme.

2017-01-03 01:59 UTC, vitorgalvao approved these changes

2017-01-03 02:00 UTC, Vayn commented on Casks/exnihilo.rb
> +  appcast 'https://vayn.github.io/ex-nihilo/release/appcast.xml',
Thank you for your clear and helpful explanation.

2017-01-03 02:01 UTC, merged

2017-01-03 02:02 UTC, miccal commented
Thank you for your contribution.