Add loslesscut 1.3.0
Homebrew/homebrew-cask pull request #28522
Opened 2017-01-03 20:52 UTC by andrev68

*If there’s a checkbox you can’t complete for any reason, that's okay, just explain in detail why you weren’t able to do so.*

After making all changes to the cask:

- [ ] `brew cask audit --download {{cask_file}}` is error-free.
- [ ] `brew cask style --fix {{cask_file}}` reports no offenses.
- [ ] The commit message includes the cask’s name and version.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference].
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked there are no [open pull requests] for the same cask.
- [ ] Checked that the cask was not already refused in [closed issues].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed

2017-01-03 20:59 UTC, vitorgalvao requested changes

2017-01-03 20:59 UTC, vitorgalvao commented on Casks/loslesscut.rb
> +  url "https://github.com/mifi/lossless-cut/releases/download/v#{version}/LosslessCut-darwin-x64.zip"
Please add an [`appcast`](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/appcast.md).

2017-01-03 21:15 UTC, vitorgalvao commented
Please fill the template in your top post. I’ve already done some for you.

2017-01-03 21:29 UTC, andrev68 commented on Casks/loslesscut.rb
> +  url "https://github.com/mifi/lossless-cut/releases/download/v#{version}/LosslessCut-darwin-x64.zip"
thanks, done

2017-01-03 21:30 UTC, andrev68 commented
thank you again, I checked both and filled out

2017-01-03 23:11 UTC, vitorgalvao commented
Did you run the commands? Because `brew cask style --fix` would’ve caught the trailing whitespace.

2017-01-04 18:10 UTC, merged

2017-01-04 18:16 UTC, vitorgalvao commented on Casks/loslesscut.rb
> +cask 'loslesscut' do
This was wrong. Fixed in a different commit.