Add Oxygen XML Editor.app v18.1
Homebrew/homebrew-cask pull request #28632
Opened 2017-01-05 16:02 UTC by joewiz

*If there’s a checkbox you can’t complete for any reason, that's okay, just explain in detail why you weren’t able to do so.*

After making all changes to the cask:

- [X] `brew cask audit --download {{cask_file}}` is error-free.
- [X] `brew cask style --fix {{cask_file}}` reports no offenses.
- [X] The commit message includes the cask’s name and version.

Additionally, **if adding a new cask**:

- [X] Named the cask according to the [token reference].
- [X] `brew cask install {{cask_file}}` worked successfully.
- [X] `brew cask uninstall {{cask_file}}` worked successfully.
- [X] Checked there are no [open pull requests] for the same cask.
- [X] Checked that the cask was not already refused in [closed issues].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed

2017-01-05 19:22 UTC, vitorgalvao requested changes

2017-01-05 19:22 UTC, vitorgalvao commented on Casks/oxygen-xml-editor.rb
> +  version '18.1'
Seeing as `url` doesn’t point to a specific version, this cask should use `version :latest` and `sha256 :no_check`. [See an example](https://github.com/caskroom/homebrew-cask/blob/f25b6babcd398abf48e33af3d887b2d00de1d661/Casks/kibako.rb).

2017-01-05 19:51 UTC, joewiz commented on Casks/oxygen-xml-editor.rb
> +  version '18.1'
@vitorgalvao Thank you, I've made the change. Still learning!

2017-01-05 19:53 UTC, vitorgalvao approved these changes

2017-01-05 20:03 UTC, joewiz commented on Casks/oxygen-xml-editor.rb
> +  version '18.1'
@vitorgalvao Sorry about the bad version clause, I'd made the change but neglected to add it before my 2nd commit. Thank you for catching it. I noticed the kibako example included a license clause, so I've added one for this software.

2017-01-05 21:52 UTC, vitorgalvao commented on Casks/oxygen-xml-editor.rb
> +  version '18.1'
> I noticed the kibako example included a license clause

Where’s the example, so we can fix it?

2017-01-05 23:26 UTC, vitorgalvao commented on Casks/oxygen-xml-editor.rb
> +  version '18.1'
Ah, that’s because I have that message in an automated snippet. I’ll update that.

2017-01-06 00:18 UTC, merged

2017-01-06 00:28 UTC, joewiz commented
@miccal @vitorgalvao Thanks so much, as always, for your guidance and support!

2017-01-06 00:30 UTC, miccal commented
Your welcome @joewiz, but @vitorgalvao did most of the work here, I just merged it.