Create binary.md
Homebrew/homebrew-cask pull request #28822
Opened 2017-01-10 09:45 UTC by miccal

Closes https://github.com/caskroom/homebrew-cask/issues/25423.

2017-01-10 15:42 UTC, vitorgalvao requested changes

2017-01-10 15:42 UTC, vitorgalvao commented on doc/cask_language_reference/stanzas/binary.md
> +In the simple case of a string argument to `binary`, the source file is linked into the `/usr/local/bin` folder on installation. For example (from [operadriver.rb](https://github.com/caskroom/homebre
I think we usually call them “directories” not “folders”. Or maybe we’re inconsistent on that. I prefer the former.

2017-01-10 15:42 UTC, vitorgalvao commented on doc/cask_language_reference/stanzas/binary.md
> +/usr/local/bin/operadriver
This isn’t strictly true. In practice we use `$(brew --prefix)/bin`. Most of the time that will translate to `/user/local/bin`, but not always. See https://github.com/caskroom/homebrew-cask/issues/21372.

This also needs to be fixed in https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/all_stanzas.md.

2017-01-10 15:42 UTC, vitorgalvao commented on doc/cask_language_reference/stanzas/binary.md
> +from a source file such as:
I don’t think this section is necessary. It’s not that useful to know where it’s linked from, that’s a more advanced detail.

2017-01-10 15:42 UTC, vitorgalvao commented on doc/cask_language_reference/stanzas/binary.md
> +You can rename the target which appears in your `/usr/local/bin` directory by adding a `target:` key to `binary`, for example to be to be consistent with other command-line tools like [changing case]
We can name it “binaries directory” or something, here, instead of `/usr/local/bin`, since as previously noted, it might not be that location.

2017-01-10 15:42 UTC, vitorgalvao commented on doc/cask_language_reference/stanzas/binary.md
> +You can rename the target which appears in your `/usr/local/bin` directory by adding a `target:` key to `binary`, for example to be to be consistent with other command-line tools like [changing case]
The examples could be taken directly from https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/app.md#target-should-only-be-used-in-select-cases, for consistency.

2017-01-10 15:42 UTC, vitorgalvao commented on doc/cask_language_reference/stanzas/binary.md
> +## target: May Contain an Absolute Path
While useful, this part is referring to `artifact`, not `binary`. We don’t want to encourage absolute paths in `binary, target:`. The section should be removed or made clearer that it is referring to `artifact` as a companion to `binary`.

2017-01-10 15:56 UTC, miccal commented on doc/cask_language_reference/stanzas/binary.md
> +/usr/local/bin/operadriver
Fixed.

2017-01-10 15:58 UTC, miccal commented on doc/cask_language_reference/stanzas/binary.md
> +from a source file such as:
I followed the same language as used in [app.md](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/app.md) which says the same thing.

Happy to remove it, though.

2017-01-10 15:58 UTC, miccal commented on doc/cask_language_reference/stanzas/binary.md
> +In the simple case of a string argument to `binary`, the source file is linked into the `/usr/local/bin` folder on installation. For example (from [operadriver.rb](https://github.com/caskroom/homebre
Fixed.

2017-01-10 15:59 UTC, miccal commented on doc/cask_language_reference/stanzas/binary.md
> +You can rename the target which appears in your `/usr/local/bin` directory by adding a `target:` key to `binary`, for example to be to be consistent with other command-line tools like [changing case]
> We can name it “binaries directory” or something, here, instead of /usr/local/bin, since as previously noted, it might not be that location.

Fixed.

> The examples could be taken directly from https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/app.md#target-should-only-be-used-in-select-cases, for consistency.

That is where I got them from.

2017-01-10 15:59 UTC, miccal commented on doc/cask_language_reference/stanzas/binary.md
> +## target: May Contain an Absolute Path
Again, I followed the same language as used in [app.md](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/app.md) which says the same thing.

Happy to remove it, though.

2017-01-10 16:00 UTC, vitorgalvao commented on doc/cask_language_reference/stanzas/binary.md
> +from a source file such as:
I think we can remove it from `app.md` as well. As long as it’s consistent, I’ll leave it to what you find is clearer.

2017-01-10 16:02 UTC, miccal commented on doc/cask_language_reference/stanzas/binary.md
> +from a source file such as:
I thing that it is better in the binary because it actually _is_ a symlink, and users would like to know _where_ the symlink points to.

2017-01-10 16:09 UTC, vitorgalvao commented on doc/cask_language_reference/stanzas/binary.md
> +## target: May Contain an Absolute Path
Lets do one better. I think that I was the one to originally write these, and that I put `target` in `app.md` for lack of a better place. We could either:

+ Split the documentation of `target:` to a new document and link there from both `app.md` and `binary.md`
+ Remove all `target:` documentation from `binary.md` and link to the section in `app.md`.

I’m partial to the second one (seems to be as clear, and requires less files.

2017-01-10 16:15 UTC, miccal commented on doc/cask_language_reference/stanzas/binary.md
> +## target: May Contain an Absolute Path
Sounds good to me.

2017-01-10 16:34 UTC, miccal commented on doc/cask_language_reference/stanzas/binary.md
> +## target: May Contain an Absolute Path
I'm offline for a while - please fell free to edit the file.

2017-01-10 16:53 UTC, vitorgalvao commented on doc/cask_language_reference/stanzas/binary.md
> +## target: May Contain an Absolute Path
I’m instead [removing mentions of `binary`](https://github.com/caskroom/homebrew-cask/pull/28840).

In this document, we can say that for `target:`, the `app.md` document should be followed, but that the select cases don’t apply as rigidly and it’s fine to take some extra liberties with `target:` to be consistent with other command-line tools, like [changing case](https://github.com/caskroom/homebrew-cask/blob/6e4eb6ba58ca0d9e6d42a1d78856cc8a35cf5fce/Casks/diffmerge.rb#L11), [removing an extension](https://github.com/caskroom/homebrew-cask/blob/312ae841f1f1b2ec07f4d88b7dfdd7fbdf8d4f94/Casks/filebot.rb#L12), or [cleaning up the name](https://github.com/caskroom/homebrew-cask/blob/146917cbcc679648de6b0bccff4e9b43fce0e6c8/Casks/minishift.rb#L13).

This way it’ll be more consistent with what we do with the other repos (we tell users to check the rules in this one, and point out the differences there.

2017-01-10 19:32 UTC, vitorgalvao approved these changes

2017-01-10 19:33 UTC, vitorgalvao commented on doc/cask_language_reference/stanzas/binary.md
> +from a source file such as:
> I think that it is better in the binary because it actually _is_ a symlink, and users would like to know _where_ the symlink points to.

> It can be removed from `app.md` though, I think.

Agreed.

2017-01-10 23:51 UTC, miccal commented on doc/cask_language_reference/stanzas/binary.md
> +## target: May Contain an Absolute Path
I Agree.

2017-01-10 23:53 UTC, merged

2017-01-11 01:48 UTC, miccal commented
Thanks for all the help @vitorgalvao.

2017-01-11 02:59 UTC, vitorgalvao commented
@miccal Thank you for starting it in the first place.