Update gpgtools.rb
Homebrew/homebrew-cask pull request #28939
Opened 2017-01-12 06:58 UTC by miccal

For reference: https://github.com/caskroom/homebrew-cask/issues/28911.

2017-01-12 16:08 UTC, vitorgalvao requested changes

2017-01-12 16:09 UTC, vitorgalvao commented
The `uninstall.sh` should be added as well.

2017-01-12 16:29 UTC, miccal commented on Casks/gpgtools.rb
> +    system_command '/bin/bash', args: ['-c', '[[ "$(/usr/bin/readlink /usr/local/bin/gpg2)"      =~ MacGPG2 ]] && /bin/rm -f /usr/local/bin/gpg2']
Done.

2017-01-12 16:29 UTC, miccal commented
> The uninstall.sh should be added as well.

Done.

2017-01-12 16:31 UTC, vitorgalvao commented on Casks/gpgtools.rb
> +    %w(gpg gpg2 gpg-agent).map { |exec_name| "/usr/local/bin/#{exec_name}" }.each do |exec|
No idea why this wasn’t done in pure ruby before. I see no reason not to. Fixed.

2017-01-12 16:32 UTC, miccal commented on Casks/gpgtools.rb
> +    system_command '/usr/bin/killall', args: ['-kill', 'gpg-agent']
But `quit:` required the bundle ids of running applications to quit, which I do not know how to kind without installing?

I was following the example in [adobe-photoshop-lightroom.rb](https://github.com/caskroom/homebrew-cask/blob/master/Casks/adobe-photoshop-lightroom.rb#L19)

2017-01-12 16:36 UTC, miccal commented on Casks/gpgtools.rb
> +    %w(gpg gpg2 gpg-agent).map { |exec_name| "/usr/local/bin/#{exec_name}" }.each do |exec|
Very nice solution!

2017-01-12 16:37 UTC, vitorgalvao commented on Casks/gpgtools.rb
> +    system_command '/usr/bin/killall', args: ['-kill', 'gpg-agent']
> But `quit:` required the bundle ids of running applications to quit

Ah, right.

> I was following the example in [adobe-photoshop-lightroom.rb](https://github.com/caskroom/homebrew-cask/blob/master/Casks/adobe-photoshop-lightroom.rb#L19) for this; is that not a better way?

That one is out of necessity. Notice it is being done in `preflight`, i.e. *before* the **installation**.

2017-01-12 16:37 UTC, vitorgalvao approved these changes

2017-01-12 16:38 UTC, miccal commented on Casks/gpgtools.rb
> +    system_command '/usr/bin/killall', args: ['-kill', 'gpg-agent']
Ah, good point - I should have noticed that.

2017-01-12 16:48 UTC, miccal commented on Casks/gpgtools.rb
> +    system_command '/usr/bin/killall', args: ['-kill', 'gpg-agent']
Maybe leave to as-is and add a `#TODO:` comment, like on lines 17 and 79?

2017-01-13 05:52 UTC, miccal commented
@vitorgalvao not sure about this:
```
>>> brew cask style Casks/gpgtools.rb
== Casks/gpgtools.rb ==
C: 31:  5: %w-literals should be delimited by [ and ].
C: 32: 24: Don't use parentheses around the condition of an if.
```

2017-01-13 18:18 UTC, miccal commented
Crap, that's what I though it meant! Thanks @vitorgalvao.

2017-01-13 18:18 UTC, merged