Add Dext.app v0.7.1
Homebrew/homebrew-cask pull request #28965
Opened 2017-01-12 16:14 UTC by akz92

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked that the cask was not already refused in [closed issues].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed

2017-01-12 16:33 UTC, vitorgalvao requested changes

2017-01-12 16:33 UTC, vitorgalvao commented on Casks/dext.rb
> +  url "https://github.com/vutran/dext/releases/download/v#{version}/Dext-darwin-x64.zip"
Please add an [`appcast`](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/appcast.md).

2017-01-12 16:45 UTC, akz92 commented on Casks/dext.rb
> +  url "https://github.com/vutran/dext/releases/download/v#{version}/Dext-darwin-x64.zip"
Added the `appcast`.

2017-01-12 20:10 UTC, vitorgalvao approved these changes

2017-01-13 05:53 UTC, miccal commented
Thank you for your contribution.

2017-01-13 05:53 UTC, merged