Add Standard Notes v0.1.1
Homebrew/homebrew-cask pull request #29146
Opened 2017-01-18 14:26 UTC by gwerbin

*If there’s a checkbox you can’t complete for any reason, that's okay, just explain in detail why you weren’t able to do so.*

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked that the cask was not already refused in [closed issues].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed

2017-01-18 14:50 UTC, miccal requested changes

2017-01-18 14:50 UTC, miccal commented on Casks/standard-notes.rb
> +  url 'https://github.com/standardnotes/desktop/releases/download/v0.1.1/Standard.Notes-Mac-0.1.1.dmg'
Can you please add an [`appcast`](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/appcast.md).

2017-01-19 01:52 UTC, gwerbin commented on Casks/standard-notes.rb
> +  url 'https://github.com/standardnotes/desktop/releases/download/v0.1.1/Standard.Notes-Mac-0.1.1.dmg'
@miccal done, I think. Does the `checkpoint` need to be updated on every release along with the version and URL?

2017-01-19 02:00 UTC, miccal commented on Casks/standard-notes.rb
> +  url 'https://github.com/standardnotes/desktop/releases/download/v0.1.1/Standard.Notes-Mac-0.1.1.dmg'
Yes, but `cask-repair` will do that automatically.

2017-01-19 12:22 UTC, merged