Starleaf breeze
Homebrew/homebrew-cask pull request #29259
Opened 2017-01-21 04:29 UTC by majidfn

*If there’s a checkbox you can’t complete for any reason, that's okay, just explain in detail why you weren’t able to do so.*

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked that the cask was not already refused in [closed issues].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed

2017-01-21 05:04 UTC, miccal requested changes

2017-01-21 05:04 UTC, miccal commented on Casks/starleaf-breeze.rb
> +  pkg 'StarLeaf-Breeze-Installer-Mac-OS.pkg'
A [`pkg`](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/pkg.md) stanza must always be accompanied by an [`uninstall`](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/uninstall.md) stanza.

Please add the following:
```
uninstall pkgutil: 'com.starleaf.breeze.mac'
```

See an example [here](https://github.com/caskroom/homebrew-cask/blob/f4c3fd06721fa9ee58506de1235aaa52dc75ff37/Casks/asepsis.rb#L9#L11).

2017-01-21 05:16 UTC, majidfn commented
Thanks for pointing that out. I just fixed the uninstall and tried it as well.

2017-01-21 05:16 UTC, majidfn commented on Casks/starleaf-breeze.rb
> +  pkg 'StarLeaf-Breeze-Installer-Mac-OS.pkg'
Thanks for pointing that out. I just fixed the uninstall and tried it as well.

2017-01-21 05:17 UTC, miccal commented on Casks/starleaf-breeze.rb
> +  pkg 'StarLeaf-Breeze-Installer-Mac-OS.pkg'
No problem - can you also remove the empty line before the final `end` statement, otherwise it will fail `brew cask style`.

2017-01-21 05:20 UTC, majidfn commented on Casks/starleaf-breeze.rb
> +  pkg 'StarLeaf-Breeze-Installer-Mac-OS.pkg'
Just did. Thanks.

2017-01-21 05:24 UTC, miccal commented on Casks/starleaf-breeze.rb
> +  pkg 'StarLeaf-Breeze-Installer-Mac-OS.pkg'
Thank you.

2017-01-21 05:37 UTC, miccal approved these changes

2017-01-22 20:42 UTC, merged

2017-01-22 20:43 UTC, miccal commented
Thank you for your contribution.