Add Quickhash v2.7.0
Homebrew/homebrew-cask pull request #29284
Opened 2017-01-22 09:33 UTC by henrymuppet

*If there’s a checkbox you can’t complete for any reason, that's okay, just explain in detail why you weren’t able to do so.*

After making all changes to the cask:

- [X] `brew cask audit --download {{cask_file}}` is error-free.
- [X] `brew cask style --fix {{cask_file}}` reports no offenses.
- [X] The commit message includes the cask’s name and version.

Additionally, **if adding a new cask**:

- [X] Named the cask according to the [token reference].
- [X] `brew cask install {{cask_file}}` worked successfully.
- [X] `brew cask uninstall {{cask_file}}` worked successfully.
- [X] Checked there are no [open pull requests] for the same cask.
- [X] Checked that the cask was not already refused in [closed issues].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed

2017-01-22 10:23 UTC, miccal requested changes

2017-01-22 10:23 UTC, miccal commented on Casks/quickhash.rb
> +  url 'http://quickhash-gui.org/download/quickhash-v2-7-0-for-apple-mac-osx/?wpdmdl=206'
Please change this to `url "http://quickhash-gui.org/download/quickhash-v#{version.dots_to_hyphens}-for-apple-mac-osx/?wpdmdl=206"`.

2017-01-22 10:23 UTC, miccal commented on Casks/quickhash.rb
> +  app 'QuickHash.app'
Please change this to `app "QuickHash-AppleMacOSX-v#{version}/QuickHash.app"`.

2017-01-22 17:26 UTC, nuomi1 commented
> This is the latest v2.7.0 of QuickHash-GUI for Apple Mac OSX systems. It was compiled using Yosemite but should work on El Capitan and Sierra as well.
>
> I only have one (old) Apple Mac PC so if this does not work on your system, let me know. You need to ensure it is executable (chmod +x NameofBinary) and that your Mac is set to allow programs to run "from anywhere" in the Security settings.

`chmod +x QuickHash-AppleMacOSX-v2.7.0/QuickHash.app/Contents/MacOS/QuickHash`

2017-01-27 01:40 UTC, vitorgalvao approved these changes

2017-01-27 08:55 UTC, merged