Add TeamPaper Latest
Homebrew/homebrew-cask pull request #29427
Opened 2017-01-26 09:46 UTC by cema-sp

Add TeamPaper Snap screen capturing tool

2017-01-26 09:54 UTC, miccal requested changes

2017-01-26 09:54 UTC, miccal commented on Casks/teampaper.rb
> +  url 'https://teampaper.me/snap/download/teampapersnap.dmg'
Please add an [`appcast`](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/appcast.md).You will also need to update the `version` and `sha256` accordingly.

2017-01-26 10:16 UTC, cema-sp commented on Casks/teampaper.rb
> +  url 'https://teampaper.me/snap/download/teampapersnap.dmg'
I could add `version` and `sha256`, but the project doesn't have any appcast 😞

2017-01-26 10:47 UTC, miccal commented on Casks/teampaper.rb
> +  url 'https://teampaper.me/snap/download/teampapersnap.dmg'
Please run the command suggested in the [`appcast` documentation](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/appcast.md) - you will find this app _does_ have an `appcast`.

2017-01-26 11:40 UTC, cema-sp commented on Casks/teampaper.rb
> +  url 'https://teampaper.me/snap/download/teampapersnap.dmg'
@miccal thank you! It is the first time I heart of Sparkle

2017-01-27 01:41 UTC, vitorgalvao commented on Casks/teampaper.rb
> +  url 'https://teampaper.me/snap/download/teampapersnap.dmg'
> @miccal thank you! It is the first time I heart of Sparkle

You know when you’re using a native macOS app and it prompts you for an update? Notice how most of the time the update process looks exactly the same for different apps? That’s [sparkle](https://sparkle-project.org/).

2017-01-27 01:42 UTC, vitorgalvao approved these changes

2017-01-27 06:37 UTC, cema-sp commented on Casks/teampaper.rb
> +  url 'https://teampaper.me/snap/download/teampapersnap.dmg'
@vitorgalvao Yes, I've already seen that update window in various apps

2017-01-27 08:55 UTC, merged