Update hacking.md
Homebrew/homebrew-cask pull request #29421
Opened 2017-01-26 05:00 UTC by miccal

Closes https://github.com/caskroom/homebrew-cask/issues/28964 and https://github.com/caskroom/homebrew-cask/issues/17007.

Ping @caskroom/maintainers for suggestions and feedback - please feel free to edit my commit directly.

2017-01-26 06:36 UTC, reitermarkus commented on doc/development/hacking.md
> +* Join us (and [caskbot](https://github.com/passcod/caskbot)) on IRC at `#homebrew-cask` on Freenode
Is anyone even using IRC? I only know I never used it.

2017-01-26 06:36 UTC, reitermarkus commented on doc/development/hacking.md
> -Homebrew-Cask is still young, and should be considered in alpha.
I think we should still keep this until we have `upgrade`.

2017-01-26 06:38 UTC, miccal commented on doc/development/hacking.md
> -Homebrew-Cask is still young, and should be considered in alpha.
Agreed.

2017-01-26 06:38 UTC, miccal commented on doc/development/hacking.md
> +* Join us (and [caskbot](https://github.com/passcod/caskbot)) on IRC at `#homebrew-cask` on Freenode
Copied from README.md.

2017-01-26 16:06 UTC, vitorgalvao requested changes

2017-01-26 16:06 UTC, vitorgalvao commented on doc/development/hacking.md
> +The setup is similar to that for contibuting to the core code of Homebrew - consult Homebrew's [documentation for maintainers]( https://github.com/Homebrew/brew/tree/master/docs#maintainers) for more
Replace `- consult Homebrew's` with `— consult Homebrew’s` (correct typographic characters, I’ve changed them in all docs a while back).

2017-01-26 16:06 UTC, vitorgalvao commented on doc/development/hacking.md
> +The setup is similar to that for contibuting to the core code of Homebrew - consult Homebrew's [documentation for maintainers]( https://github.com/Homebrew/brew/tree/master/docs#maintainers) for more
There’s an extraneous space after `](`.

2017-01-26 16:06 UTC, vitorgalvao commented on doc/development/hacking.md
> +For example, `brew cask _stanza appcast atom` outputs the `appcast` for the Cask [atom.rb](https://github.com/caskroom/homebrew-cask/blob/43ad9d8ddbad71fbeee42710d567861f080fedf8/Casks/atom.rb#L7), n
Should be instead “outputs the [`appcast` for the Cask atom.rb](https://github.com/caskroom/homebrew-cask/blob/43ad9d8ddbad71fbeee42710d567861f080fedf8/Casks/atom.rb#L7)” (notice how the link encompasses from the word `appcast`. That makes clearer we’re linking to that exact line.

2017-01-26 16:06 UTC, vitorgalvao commented on doc/development/hacking.md
> +If no `<cask_token>`'s are given, then data for all Casks is returned. On failure, a blank line is returned on the standard output.
`<cask_token>`'s → `<cask_token>`’s (typography again).

2017-01-26 16:06 UTC, vitorgalvao commented on doc/development/hacking.md
> +The command `brew cask _stanza app --table --yaml alfred google-chrome adium voicemac logisim` outputs a human-readable data table of the `app` stanzas for the given Casks:
I think we can remove this. `_stanza` is an internal advanced command anyway. It’s good to show it exists, but functionality should be studied by the interested.

2017-01-26 16:06 UTC, vitorgalvao commented on doc/development/hacking.md
> +As a final example, the command `brew cask _stanza homepage > homepage_list.txt` will output the `homepage` of every Cask into the text file `homepage_list.txt`.
[Same](https://github.com/caskroom/homebrew-cask/pull/29421/files#r98026358).

2017-01-26 16:06 UTC, vitorgalvao commented on doc/development/hacking.md
> +* Join us (and [caskbot](https://github.com/passcod/caskbot)) on IRC at `#homebrew-cask` on Freenode
I think this whole section can go away. We already mention it in the README, anyway.

2017-01-26 16:06 UTC, vitorgalvao commented on doc/development/hacking.md
> +* Join us (and [caskbot](https://github.com/passcod/caskbot)) on IRC at `#homebrew-cask` on Freenode
Last time I checked (a long time ago), there were still people on our IRC channel.

2017-01-26 16:08 UTC, vitorgalvao commented
Ideally, to close https://github.com/caskroom/homebrew-cask/issues/17007 we should also add `_stanza` do the `man` page. @reitermarkus already [made a section](https://github.com/Homebrew/brew/pull/1894/commits/2076b494a6233630025acd45d9a5766bd6bb785d), anyway, so it’d be a nice fit.

2017-01-26 23:02 UTC, miccal commented
@vitorgalvao so would I update _both_ of these files:

https://github.com/Homebrew/brew/blob/master/manpages/brew-cask.1 
https://github.com/Homebrew/brew/blob/master/Library/Homebrew/manpages/brew-cask.1.md

or just one and the other is automatically updated? I remember updating a `man` file in the past, and I _think_ I updated the wrong one?

PS: Thank you for the careful review and your updates.

2017-01-26 23:05 UTC, miccal commented on doc/development/hacking.md
> +The setup is similar to that for contibuting to the core code of Homebrew - consult Homebrew's [documentation for maintainers]( https://github.com/Homebrew/brew/tree/master/docs#maintainers) for more
> Replace “- consult Homebrew's” with “— consult Homebrew’s” (correct typographic characters, I’ve changed them in all docs a while back).

How do you do that in Markdown?

2017-01-26 23:06 UTC, miccal commented on doc/development/hacking.md
> +If no `<cask_token>`'s are given, then data for all Casks is returned. On failure, a blank line is returned on the standard output.
Same question - how do you do that? I always edit the .md files online, and I am not sure how to do this?

2017-01-26 23:15 UTC, vitorgalvao commented
@miccal The `md` one is the one to update. The other is generated with `brew man`.

2017-01-26 23:21 UTC, vitorgalvao commented on doc/development/hacking.md
> +The setup is similar to that for contibuting to the core code of Homebrew - consult Homebrew's [documentation for maintainers]( https://github.com/Homebrew/brew/tree/master/docs#maintainers) for more
Not a markdown feature, you have to actually type (or copy) the characters. On my (Portuguese) keyboard, <kbd>⌥</kbd><kbd>-</kbd> → — (em dash); <kbd>⇧</kbd><kbd>⌥</kbd><kbd>L</kbd> → ’ (apostrophe). I also have others committed to memory.

I think [this cheatsheet](https://www.typewolf.com/cheatsheet) has the US shortcuts.

I don’t mind making those changes, though. I like having the correct typographic characters.

2017-01-27 00:42 UTC, miccal commented on doc/development/hacking.md
> +The setup is similar to that for contibuting to the core code of Homebrew - consult Homebrew's [documentation for maintainers]( https://github.com/Homebrew/brew/tree/master/docs#maintainers) for more
> I like having the correct typographic characters.

Me too, thanks for explaining how to do it.

2017-01-27 01:29 UTC, miccal commented
@vitorgalvao done in https://github.com/Homebrew/brew/pull/1919.

I was not sure how much information to add to the `man` entry?

2017-01-27 01:38 UTC, vitorgalvao approved these changes

2017-01-27 02:52 UTC, adidalal approved these changes

2017-01-27 11:43 UTC, merged