Add Timer App.app v1.1.0
Homebrew/homebrew-cask pull request #29436
Opened 2017-01-26 17:16 UTC by pasqualesalza

*If there’s a checkbox you can’t complete for any reason, that's okay, just explain in detail why you weren’t able to do so.*

After making all changes to the cask:

- [ ] `brew cask audit --download {{cask_file}}` is error-free.
- [ ] `brew cask style --fix {{cask_file}}` reports no offenses.
- [ ] The commit message includes the cask’s name and version.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference].
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked there are no [open pull requests] for the same cask.
- [ ] Checked the cask was not already refused in [closed issues].
- [ ] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask

2017-01-26 17:28 UTC, vitorgalvao requested changes

2017-01-26 17:28 UTC, vitorgalvao commented on Casks/michaelvillar-timer.rb
> +  url "https://github.com/michaelvillar/timer-app/releases/download/#{version}/Timer.app.zip"
Please add an [`appcast`](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/appcast.md).

2017-01-26 18:12 UTC, pasqualesalza commented on Casks/michaelvillar-timer.rb
> +  url "https://github.com/michaelvillar/timer-app/releases/download/#{version}/Timer.app.zip"
Done, thanks!

2017-01-26 18:29 UTC, vitorgalvao approved these changes

2017-01-27 05:20 UTC, miccal commented
Thank you for your contribution.

2017-01-27 05:20 UTC, merged