Add KodeLife.app v0.4.0
Homebrew/homebrew-cask pull request #29583
Opened 2017-01-30 02:37 UTC by jzgdev

*If there’s a checkbox you can’t complete for any reason, that's okay, just explain in detail why you weren’t able to do so.*

After making all changes to the cask:

- [*] `brew cask audit --download {{cask_file}}` is error-free.
- [*] `brew cask style --fix {{cask_file}}` reports no offenses.
- [*] The commit message includes the cask’s name and version.

Additionally, **if adding a new cask**:

- [*] Named the cask according to the [token reference].
- [*] `brew cask install {{cask_file}}` worked successfully.
- [*] `brew cask uninstall {{cask_file}}` worked successfully.
- [*] Checked there are no [open pull requests] for the same cask.
- [*] Checked the cask was not already refused in [closed issues].
- [*] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask

2017-01-30 03:25 UTC, miccal requested changes

2017-01-30 03:25 UTC, miccal commented on Casks/kodelife.rb
> +  url 'http://hexler.net/mint/pepper/orderedlist/downloads/download.php?file=http%3A//hexler.net/pub/kodelife/kodelife-0.4.0-osx.zip'
Please change this to `url "http://hexler.net/pub/kodelife/kodelife-#{version}-osx.zip"`.

Also, please add an [appcast](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/appcast.md).

2017-01-31 09:22 UTC, jzgdev reviewed
Requested changes made

2017-01-31 10:22 UTC, miccal commented
I am not sure what you have done, but you have added a bunch of other commits to your PR and have not updated `kodelife.rb` as requested.

2017-01-31 14:55 UTC, vitorgalvao commented
@jzgdev Please try again in a new PR. That’ll be easier for everyone.

2017-01-31 14:55 UTC, closed without merging