Update tomtom-mysports-connect to 3.1.6
Homebrew/homebrew-cask pull request #29632
Opened 2017-01-31 07:03 UTC by HobbinHood

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

2017-01-31 10:19 UTC, miccal requested changes

2017-01-31 10:19 UTC, miccal commented on Casks/tomtom-mysports-connect.rb
> +  sha256 '677d4d5a870e113d8b226c6760a0c4f9b6406718ae665c490ce43a219bdbf428'
Since the `url` is un-versioned and there is no `appcast`, this should be left as `version :latest` and `sha256 :no_check` - please change these back to what they were.

2017-01-31 11:16 UTC, HobbinHood commented on Casks/tomtom-mysports-connect.rb
> +  sha256 '677d4d5a870e113d8b226c6760a0c4f9b6406718ae665c490ce43a219bdbf428'
Understood.
Can I use cask-repair for that to follow up on that. Or directly via git?

2017-01-31 11:17 UTC, miccal commented on Casks/tomtom-mysports-connect.rb
> +  sha256 '677d4d5a870e113d8b226c6760a0c4f9b6406718ae665c490ce43a219bdbf428'
I can do it of you, no problem.

2017-01-31 12:12 UTC, HobbinHood commented on Casks/tomtom-mysports-connect.rb
> +  sha256 '677d4d5a870e113d8b226c6760a0c4f9b6406718ae665c490ce43a219bdbf428'
Pushed it according to

> To make changes based on feedback:
> 
> 1. Checkout your branch again with `git checkout YOUR_BRANCH_NAME`
> 2. Make any requested changes and commit them with `git add` and `git commit`
> 3. Squash new commits into one commit per formula with `git rebase --interactive origin/master`
> 4. Push to the fork's remote branch and the pull request with `git push --force`

as per [How To Open a Homebrew Pull Request (and get it merged)](https://github.com/wting/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md)

2017-02-01 20:05 UTC, vitorgalvao commented on Casks/tomtom-mysports-connect.rb
> +  url 'https://sports.tomtom-static.com/downloads/desktop/mysportsconnect/latest/TomTomMySportsConnectInstaller.pkg'
What’s the download page for this? Also, the old URL is still live. Why the change?

2017-02-01 21:07 UTC, HobbinHood commented on Casks/tomtom-mysports-connect.rb
> +  url 'https://sports.tomtom-static.com/downloads/desktop/mysportsconnect/latest/TomTomMySportsConnectInstaller.pkg'
If you visit https://www.tomtom.com/mysports/getstarted you can select the device you own. You're then forwarded to a site with instructions for your device (mostly the same across the product range) and download of the TomTom MySports Connect software.

I don't know why the old URL ist still live, but they released a major update to their software and apparently made it available through a new URL.
When I downloaded and installed the (old) client through brew, the first thing it did was, presenting a message popup that an update is needed and after accepting, it downloaded the new version from the new URL and initiated installation of the pkg.

Afaik there is no reason to keep the old download URL in there, since the new one directly provides the most current client (that still works with the old TomTom hardware).

Let me know if there's anything else.

2017-02-01 21:37 UTC, vitorgalvao commented on Casks/tomtom-mysports-connect.rb
> +  url 'https://sports.tomtom-static.com/downloads/desktop/mysportsconnect/latest/TomTomMySportsConnectInstaller.pkg'
And the one for this is https://uk.support.tomtom.com/app/getstarted/p/2997, correct?

2017-02-01 21:38 UTC, vitorgalvao commented
@miccal After update we should move this one to caskroom/drivers, I’d say.

2017-02-01 21:52 UTC, HobbinHood commented on Casks/tomtom-mysports-connect.rb
> +  url 'https://sports.tomtom-static.com/downloads/desktop/mysportsconnect/latest/TomTomMySportsConnectInstaller.pkg'
Well it doesn't really matter. The URL I stated above redirects to country  specific TomTom pages and after that it's just different landing pages for each product with different images and text to sooth the customer. But they all download the same software.

I think https://www.tomtom.com/mysports/getstarted should be the download page. This URL is more generic and (might) stay in place a lot longer. You never know if they retire a product and remove it's site.

But if a specific URL with direct download on the page is really needed, then: Yes, any of the currently ten product landing pages will suffice.

2017-02-01 21:58 UTC, vitorgalvao commented on Casks/tomtom-mysports-connect.rb
> +  url 'https://sports.tomtom-static.com/downloads/desktop/mysportsconnect/latest/TomTomMySportsConnectInstaller.pkg'
That’s OK. I though each had different software. In that case, it makes sense as it is. Thank you for clarifying.

2017-02-01 21:59 UTC, vitorgalvao approved these changes

2017-02-02 00:54 UTC, vitorgalvao commented
Travis is taking too long. Verified locally.

2017-02-02 00:54 UTC, merged