Add Jriver Media Center 22.0.54
Homebrew/homebrew-cask pull request #29666
Opened 2017-01-31 20:58 UTC by nrlquaker

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

- [x] Named the cask according to the [token reference]. (not sure if I used the correct name according to your token reference. Jriver Media Center is full name mentioned at homepage. But appname is Media Center. But its very generic.)
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not already refused in [closed issues].
- [x] Checked the cask is submitted to [the correct repo].

2017-01-31 22:48 UTC, miccal requested changes

2017-01-31 22:48 UTC, miccal commented on Casks/jriver-media-center.rb
> +  url 'http://files.jriver.com/mediacenter/channels/v22/stable/MediaCenter220054.dmg'
Please change this to `url "http://files.jriver.com/mediacenter/channels/v#{version.major}/stable/MediaCenter#{version.no_dots}.dmg"`.

2017-01-31 22:48 UTC, miccal commented on Casks/jriver-media-center.rb
> +  app 'Media Center 22.app'
Please change this to `app "Media Center #{version.major}.app"`.

2017-01-31 22:48 UTC, miccal commented on Casks/jriver-media-center.rb
> +  name 'Media Center'
Please remove the last two `name`'s; as they are included in the first `name`.

2017-02-02 09:46 UTC, nrlquaker commented
Does someone know why build is failing?

> Error: undefined method `major' for nil:NilClass

2017-02-02 10:03 UTC, miccal commented
Just a spelling mistake - I have fixed it.

2017-02-02 18:52 UTC, vitorgalvao commented
Verified locally due to Travis delays.

2017-02-02 18:52 UTC, merged