Add Web Archive Extractor v0.2
Homebrew/homebrew-cask pull request #29884
Opened 2017-02-06 19:09 UTC by MattiSG

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not already refused in [closed issues].
- [ ] Checked the cask is submitted to [the correct repo]. **→ Not sure of that one. The version is 0.2, which should point to not stable, but this has not been changed for years and is surely stable in terms of usage.**

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask

2017-02-06 19:31 UTC, neutric requested changes
Thanks for your contribution! A few minor things need fixing...

2017-02-06 19:31 UTC, neutric commented on Casks/webarchiveextractor.rb
> +  # The homepage subdomain is provided by SourceForge, and the download domain is the shared SourceForge one.
Please stick to the [template](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/url.md#when-url-and-homepage-hostnames-differ-add-a-comment): `# downloads.sourceforge.net/webarchivext was verified as official when first introduced to the cask`.

2017-02-06 19:31 UTC, neutric commented on Casks/webarchiveextractor.rb
> +  url "https://downloads.sourceforge.net/webarchivext/WebArchiveExtractor.#{version}.zip"
Please add an [appcast](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/appcast.md).

2017-02-06 19:31 UTC, neutric commented on Casks/webarchiveextractor.rb
> +cask 'webarchiveextractor' do
This should be web-archive-extractor since the name is "Web Archive Extractor". The file would have to be renamed accordingly.

2017-02-06 19:31 UTC, neutric commented on Casks/webarchiveextractor.rb
> +  name 'WebArchiveExtractor'
This should be "Web Archive Extractor".

2017-02-06 19:48 UTC, vitorgalvao commented
> Not sure of that one. The version is 0.2, which should point to not stable, but this has not been changed for years and is surely stable in terms of usage.

The docs [inform there as well](https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version):

> But There Is No Stable Version!
>
> When an App is only available as beta, development, or unstable versions, or in cases where such a version is the general standard, then said version can go into the main repo.

2017-02-06 19:50 UTC, vitorgalvao commented on Casks/webarchiveextractor.rb
> +cask 'webarchiveextractor' do
This is correct as it. As per the [token reference](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md), the name of the app bundle determines the token, not whatever name the developers give it (that is often inconsistent).

2017-02-06 19:53 UTC, vitorgalvao commented on Casks/webarchiveextractor.rb
> +  # The homepage subdomain is provided by SourceForge, and the download domain is the shared SourceForge one.
The comment in this case is unnecessary. It needs to be removed altogether. In other cases yes, it must follow the pattern. `style` even warns you of that, if I recall correctly.

2017-02-06 19:58 UTC, vitorgalvao approved these changes

2017-02-06 20:18 UTC, neutric commented on Casks/webarchiveextractor.rb
> +cask 'webarchiveextractor' do
Ah, didn't know that yet! Thanks for the correction. :)

2017-02-06 20:20 UTC, neutric commented on Casks/webarchiveextractor.rb
> +  # The homepage subdomain is provided by SourceForge, and the download domain is the shared SourceForge one.
True. I glanced at one of the most recently updated casks that have a sf URL but overlooked that the project has their own domain... -.-

2017-02-06 22:55 UTC, MattiSG commented on Casks/webarchiveextractor.rb
> +  # The homepage subdomain is provided by SourceForge, and the download domain is the shared SourceForge one.
> style even warns you of that, if I recall correctly.

At least in that case, it didn't.

I did not get from reading `CONTRIBUTING.md` that the format was mandatory. I found it only after reading the [`url.md`](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/url.md#when-url-and-homepage-hostnames-differ-add-a-comment) file, which I went to only after getting the comment here.

> As a side note, I find it slightly weird to use a comment to affirm authenticity when the review process should be enough to prove a verification was made.

2017-02-06 22:58 UTC, MattiSG commented on Casks/webarchiveextractor.rb
> +  name 'WebArchiveExtractor'
I don't know: the developer seems to use indifferently “Web Archive Extractor”, “WebArchiveExtractor”, and “WebArchive Extractor”. The latter would actually make the most sense, “WebArchive” being a file format.

2017-02-06 22:59 UTC, MattiSG commented on Casks/webarchiveextractor.rb
> +cask 'webarchiveextractor' do
I actually wrote the cask a first time naming it `web-archive-extractor`, then re-read the token reference once again after finding discrepancies between app name, doc, and HTML presentation file  ;)

2017-02-06 23:21 UTC, merged

2017-02-07 00:15 UTC, vitorgalvao commented on Casks/webarchiveextractor.rb
> +cask 'webarchiveextractor' do
> finding discrepancies between app name, doc, and HTML presentation file ;)

Those discrepancies led to a huge duplicates problem (since each person would interpret it differently), hence why we had to make the token reference.

2017-02-07 00:17 UTC, vitorgalvao commented on Casks/webarchiveextractor.rb
> +  # The homepage subdomain is provided by SourceForge, and the download domain is the shared SourceForge one.
> As a side note, I find it slightly weird to use a comment to affirm authenticity when the review process should be enough to prove a verification was made.

We’re only human, and as such can make mistakes. The comment serves to inform users we did our due diligence but that they should still be careful (hence why we say “when first introduced to the cask”). It also helps with the review, since the absence of a comment when it is needed will indeed trigger and error in `style`.

2017-02-07 07:36 UTC, neutric commented on Casks/webarchiveextractor.rb
> +cask 'webarchiveextractor' do
Again, sorry for the confusion! Vitor and Miccal and the other guys are putting in so much effort here that I thought I'll help out here and there. Unfortunately, being corrected like this in my case seems to help memorize "the rules" much better than reading the docs and memorizing intricacies dozens of times.

2017-02-07 07:50 UTC, miccal commented on Casks/webarchiveextractor.rb
> +cask 'webarchiveextractor' do
No problem @neutric, @vitorgalvao has corrected my stuff-ups more times than I can remember, but that is how we learn.