Add Captain.app v6.0.0
Homebrew/homebrew-cask pull request #29886
Opened 2017-02-06 20:53 UTC by ggarnier

*If there’s a checkbox you can’t complete for any reason, that's okay, just explain in detail why you weren’t able to do so.*

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not already refused in [closed issues].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask

2017-02-06 20:59 UTC, victorpopkov approved these changes

2017-02-06 21:31 UTC, miccal requested changes

2017-02-06 21:31 UTC, miccal commented on Casks/captain.rb
> +  sha256 '0d077781163d4a759d428218f6028829ee50e97f1d40303bb42020145a10be2b'
Since the `url` is un-versioned and there is no `appcast`, this Cask should use `version :latest` and `sha256 :no_check`.

2017-02-06 22:00 UTC, neutric commented on Casks/captain.rb
> +  # dropbox.com was verified as official when first introduced to the cask
And the URL in the comment should be `dropbox.com/s/pkayzy14unr4r0a` to [uniquely identify app/vendor](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/url.md#when-url-and-homepage-hostnames-differ-add-a-comment).

2017-02-06 23:22 UTC, miccal approved these changes

2017-02-07 06:12 UTC, miccal commented
Thank you for your contribution.

2017-02-07 06:12 UTC, merged