Add Devdogs v0.2.1
Homebrew/homebrew-cask pull request #29981
Opened 2017-02-09 21:06 UTC by mendelk

*If there’s a checkbox you can’t complete for any reason, that's okay, just explain in detail why you weren’t able to do so.*

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not already refused in [closed issues].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask

resolves ragingwind/devdogs#4

2017-02-09 21:08 UTC, vitorgalvao requested changes

2017-02-09 21:08 UTC, vitorgalvao commented on Casks/devdogs.rb
> +  url "https://github.com/ragingwind/devdogs/releases/download/v#{version}/Devdogs-#{version}.zip"
Please add an [`appcast`](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/appcast.md).

2017-02-09 21:13 UTC, mendelk commented on Casks/devdogs.rb
> +  url "https://github.com/ragingwind/devdogs/releases/download/v#{version}/Devdogs-#{version}.zip"
Done!

2017-02-09 21:52 UTC, vitorgalvao requested changes

2017-02-09 21:52 UTC, vitorgalvao commented on Casks/devdogs.rb
> +  appcast 'https://github.com/ragingwind/devdogs/releases.atom'
You also need the `checkpoint`.

2017-02-09 21:55 UTC, mendelk commented on Casks/devdogs.rb
> +  appcast 'https://github.com/ragingwind/devdogs/releases.atom'
It should be there. Refresh maybe?

2017-02-09 22:59 UTC, vitorgalvao approved these changes

2017-02-10 07:44 UTC, miccal commented
Thank you for your contribution.

2017-02-10 07:44 UTC, merged