Add LG OnScreenControl
Homebrew/homebrew-cask pull request #30020
Opened 2017-02-10 21:50 UTC by bwilczynski

*If there’s a checkbox you can’t complete for any reason, that's okay, just explain in detail why you weren’t able to do so.*

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not already refused in [closed issues].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask

2017-02-10 22:31 UTC, vitorgalvao requested changes

2017-02-10 22:31 UTC, vitorgalvao commented on Casks/onscreen-control.rb
> +  homepage 'http://www.lg.com/'
This is really generic. It needs to be more specific.

What’s this app? What does it do?

2017-02-11 10:18 UTC, bwilczynski commented on Casks/onscreen-control.rb
> +  homepage 'http://www.lg.com/'
This app allows you to do a screen split on LG displays, but also changes display settings (like brightness, constrast etc.) If you think this needs to go to drivers I will move it there.

Unfortunatelly there is no homepage for this app, even clicking on a "home" button inside the app redirects you to LG homepage.

2017-02-11 14:27 UTC, vitorgalvao commented on Casks/onscreen-control.rb
> +  homepage 'http://www.lg.com/'
Definitely belongs in drivers, yes, since it’s useless without and LG display. Please resubmit there.

2017-02-11 14:27 UTC, closed without merging

2017-02-11 16:44 UTC, bwilczynski commented on Casks/onscreen-control.rb
> +  homepage 'http://www.lg.com/'
https://github.com/caskroom/homebrew-drivers/pull/6