Tanki x
Homebrew/homebrew-cask pull request #30090
Opened 2017-02-13 23:47 UTC by giannitm

*If there’s a checkbox you can’t complete for any reason, that's okay, just explain in detail why you weren’t able to do so.*

After making all changes to the cask:

- [*] `brew cask audit --download {{cask_file}}` is error-free.
- [*] `brew cask style --fix {{cask_file}}` reports no offenses.
- [*] The commit message includes the cask’s name and version.

Additionally, **if adding a new cask**:

- [*] Named the cask according to the [token reference].
- [*] `brew cask install {{cask_file}}` worked successfully.
- [*] `brew cask uninstall {{cask_file}}` worked successfully.
- [*] Checked there are no [open pull requests] for the same cask.
- [*] Checked the cask was not already refused in [closed issues].
- [*] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask

2017-02-13 23:50 UTC, giannitm commented
I apologise if I've done anything incorrectly – I'm pretty new to this, but I tried my best to follow the guides provided by you for creating new Casks.

2017-02-13 23:55 UTC, vitorgalvao requested changes

2017-02-13 23:55 UTC, vitorgalvao commented on Casks/tankix.rb
> +  url 'http://static.tankix.com/app/StandaloneOSXIntel64/prod_523/TankiX.dmg'
Isn’t `523` a version?

2017-02-14 00:00 UTC, OranShuster commented
shouldn't this be under homebrew-games?

2017-02-14 00:23 UTC, giannitm commented on Casks/tankix.rb
> +  url 'http://static.tankix.com/app/StandaloneOSXIntel64/prod_523/TankiX.dmg'
I am unsure (but I do not believe so), because the application often applies updates internally, and on a regular basis. In addition, no version number is displayed on the download webpage, and the version number embedded in the app's metadata relates to the version of Unity the game is using, not the version of the game itself.

2017-02-14 01:14 UTC, miccal approved these changes

2017-02-14 17:48 UTC, merged