Add AppGate-Client 11.2.3
Homebrew/homebrew-cask pull request #30335
Opened 2017-02-23 21:33 UTC by xavador

*If there’s a checkbox you can’t complete for any reason, that's okay, just explain in detail why you weren’t able to do so.*

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference].
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked there are no [open pull requests] for the same cask.
- [ ] Checked the cask was not already refused in [closed issues].
- [ ] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask

2017-02-23 22:58 UTC, vitorgalvao requested changes

2017-02-23 22:58 UTC, vitorgalvao commented on Casks/AppGate-Client.rb
> +  app 'AppGate Client 11.2.3.app'
There is no such app inside the `dmg`. You need to interact with the `pkg` (documentation).

Also, it’s missing `uninstall`. There are [scripts](https://github.com/caskroom/homebrew-cask/tree/master/developer/bin) and [documentation](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/uninstall.md) geared for that.

2017-02-23 22:58 UTC, vitorgalvao commented on Casks/AppGate-Client.rb
> +  sha256 :no_check
`sha256` also needs to be set. You can find what it is by running `shasum -a 256` on the downloaded file.

2017-02-23 22:58 UTC, vitorgalvao commented on Casks/AppGate-Client.rb
> +    depends_on_java('6')
Does it depend on this specific version, or is this the minimum?

2017-02-23 22:58 UTC, vitorgalvao commented on Casks/AppGate-Client.rb
> +  name 'AppGate-Client'
`AppGate (classic)`.

2017-02-23 23:26 UTC, xavador commented on Casks/AppGate-Client.rb
> +    depends_on_java('6')
it is the minimum, should i change them? when yes, to what?

2017-02-23 23:31 UTC, xavador commented on Casks/AppGate-Client.rb
> +  sha256 :no_check
thanks, i will change it with the next commit

2017-02-23 23:33 UTC, xavador commented on Casks/AppGate-Client.rb
> +  name 'AppGate-Client'
Should the name 'AppGate (classic)' and/or the complete cask?

2017-02-23 23:48 UTC, vitorgalvao commented on Casks/AppGate-Client.rb
> +    depends_on_java('6')
To `6+`.

2017-02-23 23:50 UTC, vitorgalvao approved these changes

2017-02-24 00:47 UTC, vitorgalvao commented
Verifying locally, since Travis is taking too long.

2017-02-24 00:47 UTC, merged