Add avg-antivirus :latest
Homebrew/homebrew-cask pull request #30536
Opened 2017-03-03 12:57 UTC by ninotoshi

This will install the latest AVG Antivirus for Mac.
The application offers “Uninstall AVG Antivirus…” in the menu, but I couldn’t figure out how to put an uninstall stanza :sweat:

*If there’s a checkbox you can’t complete for any reason, that's okay, just explain in detail why you weren’t able to do so.*

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not already refused in [closed issues].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask

2017-03-03 12:59 UTC, vitorgalvao commented
It’s missing `uninstall`. There are [scripts](https://github.com/caskroom/homebrew-cask/tree/master/developer/bin) and [documentation](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/uninstall.md) geared for that.

2017-03-03 13:00 UTC, vitorgalvao requested changes

2017-03-03 13:00 UTC, vitorgalvao commented on Casks/avg-antivirus.rb
> +  url 'http://avg.mac.avcdn.net/macosx/avg/avg_antivirus_for_mac_online.dmg'
Where did you get this URL?

2017-03-03 13:01 UTC, ninotoshi commented on Casks/avg-antivirus.rb
> +  url 'http://avg.mac.avcdn.net/macosx/avg/avg_antivirus_for_mac_online.dmg'
The green button on http://www.avg.co.jp/avg-antivirus-for-mac redirects there.

2017-03-03 13:03 UTC, vitorgalvao commented on Casks/avg-antivirus.rb
> +  url 'http://avg.mac.avcdn.net/macosx/avg/avg_antivirus_for_mac_online.dmg'
> The green button on http://www.avg.co.jp/avg-antivirus-for-mac redirects there.

But not the one on the homepage you linked to. That one redirects to cnet.

2017-03-03 13:05 UTC, ninotoshi commented on Casks/avg-antivirus.rb
> +  url 'http://avg.mac.avcdn.net/macosx/avg/avg_antivirus_for_mac_online.dmg'
I assume there is one universal binary, and `homepage` is only a reference.

2017-03-03 17:42 UTC, vitorgalvao commented on Casks/avg-antivirus.rb
> +  url 'http://avg.mac.avcdn.net/macosx/avg/avg_antivirus_for_mac_online.dmg'
Confirmed they are the same. Still needs `uninstall` before it can be accepted, though.

2017-03-03 22:45 UTC, miccal commented on Casks/avg-antivirus.rb
> +  url 'http://avg.mac.avcdn.net/macosx/avg/avg_antivirus_for_mac_online.dmg'
`uninstall` added.

2017-03-04 04:20 UTC, miccal commented
Thank you for your contribution.

2017-03-04 04:20 UTC, merged