add YoudaoNote.app V2.5.1
Homebrew/homebrew-cask pull request #30571
Opened 2017-03-04 15:03 UTC by magicsky

*If there’s a checkbox you can’t complete for any reason, that's okay, just explain in detail why you weren’t able to do so.*

After making all changes to the cask:

- [ ] `brew cask audit --download {{cask_file}}` is error-free.
- [ ] `brew cask style --fix {{cask_file}}` reports no offenses.
- [ ] The commit message includes the cask’s name and version.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference].
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked there are no [open pull requests] for the same cask.
- [ ] Checked the cask was not already refused in [closed issues].
- [ ] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask

2017-03-04 15:44 UTC, miccal approved these changes

2017-03-04 17:12 UTC, vitorgalvao requested changes

2017-03-04 17:12 UTC, vitorgalvao commented on Casks/youdao-note.rb
> +  version '2.5.1'
Seeing as `url` doesn’t point to a specific version, this cask should use `version :latest` and `sha256 :no_check`. [See an example](https://github.com/caskroom/homebrew-cask/blob/37f8d181d1789cbb06c6e73625587fdbe77ca225/Casks/kibako.rb#L2L3).

2017-03-04 17:12 UTC, vitorgalvao commented on Casks/youdao-note.rb
> +  name '有道云笔记'
This also need an english name above. See [docs](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/name.md).

2017-03-05 14:19 UTC, magicsky commented
OK, I added english name; and the app name should be 'YoudaoNote.app', becasuse it will be a error if app name is 'Youdao Note.app':
<img width="1210" alt="screen_shot__2017-03-05_22 18 37" src="https://cloud.githubusercontent.com/assets/93135/23588027/bf16ad96-01f1-11e7-8063-75c0f58420e1.png">

2017-03-05 14:20 UTC, magicsky commented on Casks/youdao-note.rb
> +  version '2.5.1'
OK, thank you

2017-03-05 14:26 UTC, wuliang142857 reviewed
OK, that's right

2017-03-05 14:33 UTC, magicsky commented on Casks/youdao-note.rb
> +  name '有道云笔记'
ok. thank you, add english name now

2017-03-05 15:48 UTC, vitorgalvao approved these changes

2017-03-05 16:10 UTC, merged