Adding explorer v1.104
Homebrew/homebrew-cask pull request #30678
Opened 2017-03-07 17:41 UTC by gobinathm

- Including Explorer v1.104

*If there’s a checkbox you can’t complete for any reason, that's okay, just explain in detail why you weren’t able to do so.*

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not already refused in [closed issues].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask

2017-03-07 17:46 UTC, vitorgalvao requested changes

2017-03-07 17:46 UTC, vitorgalvao commented on Casks/explorer.rb
> +  app 'explorer'
`Explorer-darwin-x64.app`.

2017-03-07 17:47 UTC, gobinathm commented on Casks/explorer.rb
> +  app 'explorer'
style check / audit / installation did not fail with that name :( hence i ended up leaving that.  Pushing an update..

2017-03-07 17:48 UTC, gobinathm commented on Casks/explorer.rb
> +  app 'explorer'
@vitorgalvao pushed an update

2017-03-07 17:50 UTC, reitermarkus commented on Casks/explorer.rb
> +  app 'explorer'
> installation did not fail with that name

But did it actually install what you expected?

2017-03-07 18:40 UTC, gobinathm commented on Casks/explorer.rb
> +  app 'explorer'
@reitermarkus , actually i was wrong, in my machine it did not fail due to a problem in my local. Tried in another machine it did fail.

2017-03-08 02:22 UTC, miccal requested changes

2017-03-08 02:22 UTC, miccal commented on Casks/explorer.rb
> +  name 'explorer'
Please change this to `Explorer`.

2017-03-08 02:27 UTC, gobinathm commented on Casks/explorer.rb
> +  name 'explorer'
@miccal Its updated.

2017-03-08 11:51 UTC, vitorgalvao approved these changes

2017-03-09 04:58 UTC, merged