Update TOPCAT 4.4
Homebrew/homebrew-cask pull request #30744
Opened 2017-03-08 23:11 UTC by hebl

*If there’s a checkbox you can’t complete for any reason, that's okay, just explain in detail why you weren’t able to do so.*

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference].
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked there are no [open pull requests] for the same cask.
- [ ] Checked the cask was not already refused in [closed issues].
- [ ] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask

2017-03-08 23:42 UTC, vitorgalvao requested changes

2017-03-08 23:42 UTC, vitorgalvao commented on Casks/topcat.rb
>    version '4.3-5'
Didn’t you forget to update this?

2017-03-09 01:15 UTC, hebl commented on Casks/topcat.rb
>    version '4.3-5'
Has fixed!

2017-03-09 01:16 UTC, vitorgalvao approved these changes

2017-03-09 10:44 UTC, merged