USAGE.md: Add --language option to Options section
Homebrew/homebrew-cask pull request #31106
Opened 2017-03-19 06:14 UTC by Numbermaniac

Fixes issue C in #31094.

2017-03-19 13:36 UTC, vitorgalvao requested changes

2017-03-19 13:36 UTC, vitorgalvao commented on USAGE.md
> +Default is the language of your system.
The default is based on the cask, usually the American English version.

2017-03-19 16:41 UTC, muescha commented on USAGE.md
> +Default is the language of your system.
not exactly: as @vitorgalvao write here https://github.com/caskroom/homebrew-cask/issues/27181#issuecomment-263144132 :

> No, that would be ridiculous. It will just get either the language of your system, or the one you specifically ask for.

i assume this order:
1. language of your system, 
2. default on the cask
3. or the one you specifically ask for.

2017-03-19 18:02 UTC, muescha commented on USAGE.md
> +Default is the language of your system.
you should change to `<iso-language>[,<iso-language> ... ]` (see my updated issue #31094 )

2017-03-20 12:55 UTC, vitorgalvao approved these changes

2017-03-20 13:03 UTC, merged