Add Scansion.app v1.12
Homebrew/homebrew-cask pull request #31555
Opened 2017-03-29 10:00 UTC by gigaflw

vcd (Value Change Dump) file viewer

This app is handy when processing signal output, and is recommended for verilog development in this  [tutorial](https://www.swarthmore.edu/NatSci/mzucker1/e15_f2014/iverilog.html) 

*If there’s a checkbox you can’t complete for any reason, that's okay, just explain in detail why you weren’t able to do so.*

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not already refused in [closed issues].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask

2017-03-29 19:18 UTC, victorpopkov requested changes

2017-03-29 19:18 UTC, victorpopkov commented on Casks/scansion.rb
> +  url 'http://www.logicpoet.com/releases/scansion/Scansion_1.12.dmg'
You can use string interpolation here to reuse the version in the download URL. Also, there is an appcast available for this app which will make future updates easier:
```ruby
  url "http://www.logicpoet.com/releases/scansion/Scansion_#{version}.dmg"
  appcast 'http://www.logicpoet.com/feeds/Scansion.xml',
          checkpoint: 'c9012b984959235fae42c1eb9655a91852874d9600218378988da313217b6494'
```

2017-03-29 19:20 UTC, gobinathm requested changes

2017-03-30 03:02 UTC, miccal commented
Thank you for your contribution.

2017-03-30 03:02 UTC, merged