Update android-sdk
Homebrew/homebrew-cask pull request #31568
Opened 2017-03-29 12:02 UTC by plastiv

Correct the emulator binaries, which are moved from /tools to /emulator folder.
See announcement here: https://developer.android.com/studio/releases/emulator.html

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [ ] The commit message includes the cask’s name and version.

👋  Hello! My first MR here, please let me know if I missed anything from the contributing guideline I'll fix it ASAP.

2017-03-29 15:03 UTC, thevery commented
Can we fix adb binary path as well? I've done this in original brew long time ago, see https://github.com/Homebrew/legacy-homebrew/pull/27600

2017-03-29 15:29 UTC, plastiv commented
@thevery do you mean ` binary "#{staged_path}/platform-tools/adb"`?

2017-03-29 15:36 UTC, thevery commented
@plastiv yes. Plus `build-tools/LATEST_VERSION/` binaries (aapt, aapt2, zipalign, dx, etc)

2017-03-29 17:02 UTC, victorpopkov approved these changes

2017-03-29 17:31 UTC, plastiv commented
@thevery pushed an update with changes. please, check if I get implementation correctly

2017-03-29 18:05 UTC, thevery commented on Casks/android-sdk.rb
> +  build_tools_version = '25.0.2'
this version is 'unstable' and even not known at the install :(

2017-03-29 18:07 UTC, thevery commented on Casks/android-sdk.rb
> +  binary "#{staged_path}/platform-tools/fastboot"
Add `sqlite3`, too.
And probably `dmtracedump`, `etc1tool`, `hprof-conv`.

2017-03-29 18:19 UTC, victorpopkov requested changes

2017-03-29 18:19 UTC, victorpopkov commented on Casks/android-sdk.rb
>    postflight do
The `preflight` should be used here instead. This will run the `sdkmanager` command before linking the binaries. At the moment, the changes in your PR include binaries that are only available after running the `sdkmanager`.

2017-03-29 18:21 UTC, victorpopkov commented on Casks/android-sdk.rb
>    postflight do
And btw, thank you for your contribution! We really appreciate it.

You are awesome!

2017-03-29 18:25 UTC, plastiv commented on Casks/android-sdk.rb
> +  build_tools_version = '25.0.2'
What do you mean by unstable? Its current release uploaded last December https://developer.android.com/studio/releases/build-tools.html

2017-03-29 21:25 UTC, plastiv commented on Casks/android-sdk.rb
> +  binary "#{staged_path}/platform-tools/fastboot"
@thevery Thanks for the review, added.

2017-03-29 21:26 UTC, plastiv commented on Casks/android-sdk.rb
>    postflight do
@victorpopkov changed.

I'm new to cask development, so feedback like this is much appreciated 👍

2017-03-29 21:39 UTC, thevery commented on Casks/android-sdk.rb
> +  build_tools_version = '25.0.2'
I mean build tools are available in different versions (25.0.2, 25.0.1, etc) and not connected to sdk version, so user might not have most recent version installed. But since we force build tools installation on cask install hardcoding version is ok.

2017-03-30 05:43 UTC, julienschmidt commented
This conflicts with PR #31598

Issue regarding missing binaries: #31468

2017-03-30 07:13 UTC, plastiv commented
@julienschmidt 
> This conflicts with PR #31598

That merge request was created after this one. Do you suggest to wait for merge that first and rebase this one on top?

2017-03-30 07:18 UTC, julienschmidt commented
@plastiv not necessarily. Those two PRs seem to use different approaches. This one seems to create softlinks for the binaries, while #31598 links the containing dir to a "stable path" and requests the user to manually add it to the`$PATH`.

We have to pick one approach. Personally, I prefer the approach in this PR, but  #31550 might be a reason to pick the other approach.

2017-03-30 07:22 UTC, julienschmidt commented
Forget what I've said. #31598 is just a solution for #31550. It does not make the binaries available anywhere in `$PATH`.
These two PRs are thus not blocking each other, I guess. But building upon each other might still make sense.

2017-03-30 07:25 UTC, victorpopkov approved these changes

2017-03-30 07:43 UTC, victorpopkov commented
I will merge this since I'm not sure about the better solution for https://github.com/caskroom/homebrew-cask/issues/31550. The https://github.com/caskroom/homebrew-cask/pull/31598 will need attention and most likely won't be merged in quickly.

The solution proposed in this PR doesn't seem to break anything. It just links additional binaries in the first place and changes paths to emulator binaries. So it would be better to rebase https://github.com/caskroom/homebrew-cask/pull/31598 instead.

Thank you for your contribution and congratulation with your first PR in this project! 🎉

2017-03-30 07:47 UTC, merged