add new Cask for ManicTime 1.3.3
Homebrew/homebrew-cask pull request #31591
Opened 2017-03-29 15:02 UTC by waldyrious

*If there’s a checkbox you can’t complete for any reason, that's okay, just explain in detail why you weren’t able to do so.*

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not already refused in [closed issues].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask

2017-03-29 15:03 UTC, waldyrious commented
Uninstalling failed with the following output:

```
$ brew cask uninstall manictime
Warning: Unexpected method 'pkgutil' called on Cask manictime.
Follow the instructions here:
  https://github.com/caskroom/homebrew-cask/blob/master/doc/reporting_bugs/pre_bug_report.md

If this doesn’t fix the problem, please report this bug:
  https://github.com/caskroom/homebrew-cask#reporting-bugs

Warning: Unexpected method 'pkgutil' called on Cask manictime.
Follow the instructions here:
  https://github.com/caskroom/homebrew-cask/blob/master/doc/reporting_bugs/pre_bug_report.md

If this doesn’t fix the problem, please report this bug:
  https://github.com/caskroom/homebrew-cask#reporting-bugs
```

Any help appreciated.

2017-03-29 15:12 UTC, Moisan commented
You need `pkgutil:` instead of `pkgutil` to fix the uninstall.

2017-03-29 15:14 UTC, waldyrious commented
Thanks @Moisan. Shouldn't the audit or the style checker have caught this issue?

2017-03-29 15:18 UTC, Moisan commented
I am not deeply familiar with Homebrew audit and style checker but my feeling is that those will only make sure that the formula is properly formatted (e.g. correct indentation, all attributes needed are present), not that it will necessarily work at runtime.

2017-03-29 15:35 UTC, waldyrious commented
Yes, that makes sense, but since "pkgutil:" is a known keyword, I don't think it would be out of scope to check for the necessary punctuation. At the very least (IMHO), one of these checkers (or the uninstall command) should print out an informative error message that would lead cask authors towards the solution.

2017-03-29 16:43 UTC, gobinathm requested changes
While uninstalling there are some residues left in Application Support folder. Hence that needs to be deleted as well

> > ~/Library/Application\ Support/ManicTime/

May be include

```
zap delete: '~/Library/Application Support/ManicTime'
```

2017-03-29 16:43 UTC, gobinathm commented on Casks/manictime.rb
> +  caveats 'This is not a full ManicTime Windows port to Mac. '\
Not sure if we need this caveat here.

When visited the software homepage there is clear indication of this message on the webpage. Also this message has nothing to do with how homebrew-cask is installing this software.

> >Sometimes there are particularities with the installation of a piece of software that cannot or should not be handled programmatically by Homebrew-Cask


Ref: [Caveat Doc](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/caveats.md)

2017-03-29 16:43 UTC, gobinathm commented on Casks/manictime.rb
> +cask 'manictime' do
Since it's only a Client App, it might be good idea to use the token like ```manictime-client```

2017-03-29 17:55 UTC, waldyrious commented on Casks/manictime.rb
> +  caveats 'This is not a full ManicTime Windows port to Mac. '\
I'd rather keep it since people might then be confused that the app is not working as they expect (considering that the Windows client is fully-featured), but I understand the reasoning on the caveat guidelines.

Note, however, that the warning is quite visible in http://www.manictime.com/Mac, but not as much on http://www.manictime.com/mac/download, which is the page you get to by following the download links from the homepage.

That said, if you still think the caveat does more harm than good, let me know and I'll remove it.

2017-03-29 23:30 UTC, gobinathm commented on Casks/manictime.rb
> +  caveats 'This is not a full ManicTime Windows port to Mac. '\
@waldyrious personally i feel its not required, but i will defer the decision to Maintainers

2017-03-30 02:57 UTC, miccal commented on Casks/manictime.rb
> +cask 'manictime' do
The token reference goes by the `name` stanza, so this is fine.

2017-03-30 03:02 UTC, miccal commented
Thank you for your contribution.

2017-03-30 03:02 UTC, merged

2017-03-30 09:27 UTC, waldyrious commented
@gobinathm I'm sorry, I missed some of your review comments. I agree with you about the token, but the one I used was generated according to the instructions in [adding_a_cask.md](https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md), which is why I didn't think of changing it.

As for the `zap delete`, that makes sense. Should I send a new PR adding that, @miccal?

2017-03-30 12:24 UTC, gobinathm commented
@waldyrious i guess new PR is not need for the token change, that can be ignored.

2017-03-30 12:26 UTC, miccal commented
@waldyrious you are welcome to open a new PR to add the `zap` stanza.