android-ndk: latest
Homebrew/homebrew-cask pull request #31610
Opened 2017-03-29 20:27 UTC by yurikoles

*If there’s a checkbox you can’t complete for any reason, that's okay, just explain in detail why you weren’t able to do so.*

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference].
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not already refused in [closed issues].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask

2017-03-29 21:00 UTC, yurikoles commented
I can't create a workaround for cask requiring url stanza.

```sheell
cask install android-ndk
==> Downloading https://developer.android.com/ndk/
######################################################################## 100,0%
==> No checksum defined for Cask android-ndk, skipping verification
Error: Uh oh, could not figure out how to unpack '/Users/yurikoles/Library/Caches/Homebrew/Cask/android-ndk--latest'
Error: nothing to install
```

2017-03-30 02:48 UTC, miccal requested changes

2017-03-30 02:48 UTC, miccal commented on Casks/android-ndk.rb
> +
This is missing an [`artifact`](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/all_stanzas.md#at-least-one-artifact-stanza-is-also-required) stanza.

2017-03-30 08:14 UTC, yurikoles commented on Casks/android-ndk.rb
> +  version 'latest'
done

2017-03-30 08:45 UTC, yurikoles commented
There is still an open issue #31234

2017-03-30 11:23 UTC, yurikoles commented
@miccal this package is supposed to be meta/fake one that uses `android-sdk`'s `sdkmanager` to install itself.

2017-04-07 00:35 UTC, victorpopkov commented
@yurikoles You can try experimenting with the solution below. It will use the shared path provided with `android-sdk.rb` cask to install the `ndk-bundle` as you mentioned earlier:

```ruby
cask 'android-ndk' do
  version '14b'
  sha256 'f5373dcb8ddc1ba8a4ccee864cba2cbdf500b2a32d6497378dfd32b375a8e6fa'

  # google.com/android/repository was verified as official when first introduced to the cask
  url "https://dl.google.com/android/repository/android-ndk-r#{version}-darwin-x86_64.zip"
  name 'android-sdk'
  homepage 'https://developer.android.com/ndk/index.html'

  conflicts_with cask: 'android-platform-tools'
  depends_on cask: 'android-sdk'

  installer script: "#{HOMEBREW_PREFIX}/share/android-sdk/tools/bin/sdkmanager",
            args:   ['ndk-bundle'],
            input:  'y'

  postflight do
    FileUtils.ln_sf("#{HOMEBREW_PREFIX}/share/android-sdk", "#{HOMEBREW_PREFIX}/share/android-ndk")
  end

  uninstall_postflight do
    FileUtils.rm("#{HOMEBREW_PREFIX}/share/android-ndk")
  end

  caveats <<-EOS.undent
    We will install ndk-bundle for you in existing android-sdk directory provided
    by the android-sdk cask.

    You may want to add to your profile:
      'export ANDROID_NDK_HOME=#{HOMEBREW_PREFIX}/share/android-ndk'

    This operation may take up to 10 minutes depending on your internet connection.
    Please, be patient.
  EOS
end
```

Maybe there is a better solution, but at least it should work.

2017-04-13 11:03 UTC, yurikoles commented
@victorpopkov the problem with your code is that it makes unwanted download of `android-ndk-r14b-darwin-x86_64.zip` by cask which is later being downloaded by `sdkmanager`.

2017-04-13 11:05 UTC, yurikoles commented
@miccal how can we avoid any downloads by cask? I want this cask to not download anything since download will be handled by `sdkmanager`

2017-04-13 11:52 UTC, miccal commented
@yurikoles you cannot - Cask by design _must_ download something.

2017-04-13 11:53 UTC, yurikoles commented
@miccal could we download some fake data for this cask?

2017-04-13 11:55 UTC, miccal commented
Ping @victorpopkov and @vitorgalvao.

2017-04-13 11:57 UTC, miccal commented
If it doesn't download anything, then what is the point of adding this to Cask at all?

2017-04-13 12:16 UTC, yurikoles commented
@miccal I had tried to download it and make symlinks with no luck in this PR #31614. It looks like we need to write custom wrappers for every binary.

2017-04-13 13:38 UTC, closed without merging