android-ndk: 14b
Homebrew/homebrew-cask pull request #31614
Opened 2017-03-29 20:53 UTC by yurikoles

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not already refused in [closed issues].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask

2017-03-29 21:36 UTC, plastiv commented on Casks/android-ndk.rb
> +      'export ANDROID_HOME=#{HOMEBREW_PREFIX}/opt/android-sdk'
is path correct? `brew cask info android-sdk` gives me `/usr/local/Caskroom/android-sdk/25.2.3`

maybe it should be `ANDROID_NDK_HOME` instead?

2017-03-30 02:46 UTC, miccal requested changes

2017-03-30 02:46 UTC, miccal commented on Casks/android-ndk.rb
> +
This is missing an [`artifact`](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/all_stanzas.md#at-least-one-artifact-stanza-is-also-required) stanza.

2017-03-30 08:44 UTC, yurikoles commented
There is steal an open issue #31234

2017-04-08 13:53 UTC, adi1133 commented
The [android-sdk](android-sdk) automatically installs the ndk when required by a project. 
If that fails, the ndk can also be installed manually by running `$ANDROID_HOME/tools/bin/sdkmanager ndk-bundle`.

2017-04-13 12:02 UTC, yurikoles commented
@miccal how to port following code from homebrew to cask DSL?
```ruby
ndk_exec = prefix+"ndk-exec.sh"
    ndk_exec.write <<-EOS.undent
      #!/bin/sh
      BASENAME=`basename $0`
      EXEC="#{prefix}/$BASENAME"
      test -f "$EXEC" && exec "$EXEC" "$@"
    EOS
    ndk_exec.chmod 0755
    %w[ndk-build ndk-depends ndk-gdb ndk-stack ndk-which].each { |app| bin.install_symlink ndk_exec => app }
```

2017-04-13 12:05 UTC, yurikoles commented
>Do you have a usecase where you run the ndk without the sdk installed ?
I don't have any, but I want this cask to exist for those users who prefer keep their software in managed manner.

2017-04-13 12:40 UTC, miccal commented
> @miccal how to port following code from homebrew to cask DSL?

No idea, sorry.

2017-04-13 13:05 UTC, vitorgalvao commented
@yurikoles The `chmod` can be accomplished with `set_permissions`. Everything above it [just a shim script](https://github.com/caskroom/homebrew-cask/search?utf8=✓&q=shim+script), and the last line is something [like this](https://github.com/caskroom/homebrew-cask/blob/1527cf9abd0350cf5cb9c8b641e7bad4d772f764/Casks/macvim.rb#L16L23).

But I haven’t been following this whole android situation closely, so as for the validity of the cask itself, I’ll leave it to the other maintainers that have been managing the case.

2017-04-13 13:53 UTC, yurikoles commented
@vitorgalvao thank you for your help, it looks like working.

2017-04-13 13:56 UTC, yurikoles commented on Casks/android-ndk.rb
> +
done

2017-04-14 13:19 UTC, yurikoles commented
@miccal please trigger test

2017-04-14 14:34 UTC, vitorgalvao commented on Casks/android-ndk.rb
> +    FileUtils.rm_rf "#{HOMEBREW_PREFIX}/opt/android-ndk"
Are you sure `HOMEBREW_PREFIX` is available?

2017-04-14 14:42 UTC, vitorgalvao requested changes

2017-04-14 14:42 UTC, vitorgalvao commented on Casks/android-ndk.rb
> +    FileUtils.rm_rf "#{HOMEBREW_PREFIX}/opt/android-ndk"
Why are you deleting the directory?

2017-04-14 14:52 UTC, yurikoles commented on Casks/android-ndk.rb
> +    FileUtils.rm_rf "#{HOMEBREW_PREFIX}/opt/android-ndk"
Because this formulae is versioned an we need to put new symlink there after new release.
Is it possible to pass `-f` to `ln`?

2017-04-17 00:52 UTC, numbermaniac commented on Casks/android-ndk.rb
> +     ndk-which
Travis CI is saying that each of these should be indented two spaces from the bracket, instead of one.

2017-04-18 15:28 UTC, ilovezfs commented
What's the status here?

2017-04-18 15:31 UTC, yurikoles commented
@vitorgalvao are you ready to merge it?

2017-04-18 19:36 UTC, vitorgalvao commented
I see Travis finally passed. Had to restart it for this cask a bunch of times.

Merging.

2017-04-18 19:36 UTC, merged

2017-04-19 04:08 UTC, ilovezfs commented
@vitorgalvao great thanks!

@yurikoles do you mind opening a PR updating the `tap_migrations` file in homebrew/core accordingly? Thanks!

2017-04-19 04:29 UTC, yurikoles commented
@ilovezfs https://github.com/Homebrew/homebrew-core/pull/12612

2017-04-19 04:30 UTC, ilovezfs commented
@yurikoles perfect! thank you