Update ncar-ncl to 6.4.0
Homebrew/homebrew-cask pull request #31917
Opened 2017-04-05 15:57 UTC by gobinathm

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

2017-04-05 18:47 UTC, vitorgalvao requested changes

2017-04-05 18:47 UTC, vitorgalvao commented on Casks/ncar-ncl.rb
> +    sha256 ''
This cannot be empty.

2017-04-05 18:47 UTC, vitorgalvao commented on Casks/ncar-ncl.rb
> +  if MacOS.version == :sierra
The latest release (`sierra` in this case) is always the one in `else`, never at the top.

2017-04-06 03:20 UTC, gobinathm commented on Casks/ncar-ncl.rb
> +  if MacOS.version == :sierra
@vitorgalvao Updated this

2017-04-06 03:21 UTC, gobinathm commented on Casks/ncar-ncl.rb
> +    sha256 ''
@vitorgalvao Updated this

2017-04-06 03:21 UTC, gobinathm commented
@vitorgalvao all requested change is complete.

2017-04-06 04:52 UTC, miccal approved these changes

2017-04-06 06:39 UTC, merged