Update xpra to latest
Homebrew/homebrew-cask pull request #32214
Opened 2017-04-11 16:28 UTC by gobinathm

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

2017-04-11 19:22 UTC, victorpopkov requested changes

2017-04-11 19:22 UTC, victorpopkov commented on Casks/xpra.rb
> +  url 'https://www.xpra.org/dists/osx/x86_64/Xpra-x86_64.pkg'
Since now it uses `pkg` instead of `dmg`, the installer should be changed to `pkg` ([pkg.md](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/pkg.md)) and be accompanied with the `uninstall` ([uninstall.md](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/uninstall.md)).

2017-04-11 19:23 UTC, gobinathm commented on Casks/xpra.rb
> +  url 'https://www.xpra.org/dists/osx/x86_64/Xpra-x86_64.pkg'
mm, that so bad of me to miss it. Will update.

2017-04-12 05:04 UTC, gobinathm commented on Casks/xpra.rb
> +  url 'https://www.xpra.org/dists/osx/x86_64/Xpra-x86_64.pkg'
@victorpopkov Its updated now.

2017-04-12 06:41 UTC, merged