Add LRTimelapse cask
Homebrew/homebrew-cask pull request #33273
Opened 2017-05-01 06:27 UTC by bai

Add LRTimelapse cask.

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not already refused in [closed issues].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask

2017-05-01 10:57 UTC, vitorgalvao requested changes

2017-05-01 10:57 UTC, vitorgalvao commented on Casks/lrtimelapse.rb
> +  uninstall script: { executable: 'Uninstall LRTimelapse.command' }
This is incomplete. Where is this located?

2017-05-01 12:09 UTC, bai commented on Casks/lrtimelapse.rb
> +  uninstall script: { executable: 'Uninstall LRTimelapse.command' }
Thanks for your review! This script is located in `.pkg` file in the app dmg image. Uninstall seem to have worked when I tested it with `brew cask uninstall`.
If calling that `command` is not an option, should I use `zap` instead?

2017-05-02 00:06 UTC, merged

2017-05-02 00:06 UTC, miccal commented
Thank you for your contribution.