Adding Scrabble3D
Homebrew/homebrew-cask pull request #33344
Opened 2017-05-03 01:55 UTC by DrStrangepork

*If there’s a checkbox you can’t complete for any reason, that's okay, just explain in detail why you weren’t able to do so.*

After making all changes to the cask:

- [ ] `brew cask audit --download {{cask_file}}` is error-free.
- [ ] `brew cask style --fix {{cask_file}}` reports no offenses.
- [ ] The commit message includes the cask’s name and version.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference].
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked there are no [open pull requests] for the same cask.
- [ ] Checked the cask was not already refused in [closed issues].
- [ ] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask

2017-05-03 02:02 UTC, DrStrangepork commented
The SourceForge URL format as suggested by the documentation link does not work for this download.

2017-05-03 03:08 UTC, miccal approved these changes

2017-05-03 08:20 UTC, vitorgalvao commented on Casks/scrabble3d.rb
> +  url 'https://sourceforge.net/projects/scrabble/files/latest/download'
Please add an [`appcast`](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/appcast.md), and with that a `version` and `sha256`.

2017-05-03 08:25 UTC, vitorgalvao requested changes

2017-05-03 08:25 UTC, vitorgalvao commented on Casks/scrabble3d.rb
> +  name 'Scrabble3D'
Please add an [`appcast`](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/appcast.md), and with that a `version` and `sha256`.

2017-05-04 00:42 UTC, miccal commented on Casks/scrabble3d.rb
> +  name 'Scrabble3D'
@vitorgalvao I cannot seem to find a valid `version` for this?

2017-05-04 06:41 UTC, miccal commented on Casks/scrabble3d.rb
> +  name 'Scrabble3D'
@vitorgalvao found the version in by expanding the `pkg` and viewing the file `PackageInfo`.

2017-05-04 06:57 UTC, miccal approved these changes

2017-05-04 08:09 UTC, vitorgalvao commented on Casks/scrabble3d.rb
> +  name 'Scrabble3D'
@miccal Nice one!

2017-05-04 08:09 UTC, merged