Add cask Persepolis 2.4.2
Homebrew/homebrew-cask pull request #33444
Opened 2017-05-05 09:07 UTC by ibrokemypie

*If there’s a checkbox you can’t complete for any reason, that's okay, just explain in detail why you weren’t able to do so.*

After making all changes to the cask:

- [ ] `brew cask audit --download {{cask_file}}` is error-free.
- [ ] `brew cask style --fix {{cask_file}}` reports no offenses.
- [ ] The commit message includes the cask’s name and version.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference].
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked there are no [open pull requests] for the same cask.
- [ ] Checked the cask was not already refused in [closed issues].
- [ ] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask

2017-05-05 09:34 UTC, vitorgalvao requested changes

2017-05-05 09:34 UTC, vitorgalvao commented on Casks/persepolis-download-manager.rb
> +  name 'Persepolis'
Please add an [`appcast`](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/appcast.md).

2017-05-05 09:47 UTC, commitay commented
@ibrokemypie Use `#{version.dots_to_underscores}` instead of `#{version.major_minor_patch}`

2017-05-05 09:59 UTC, vitorgalvao commented
> @ibrokemypie Use `#{version.dots_to_underscores}` instead of `#{version.major_minor_patch}`

As a note, @ibrokemypie, that’s what you wanted from the start. `major_minor_patch` does not output underscores.

2017-05-05 10:22 UTC, ibrokemypie commented
is there anywhere where all of these variables are listed? Would be very helpful :P

2017-05-05 10:24 UTC, vitorgalvao commented
[Yes](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/version.md#version-methods).

2017-05-05 10:24 UTC, vitorgalvao commented on Casks/persepolis-download-manager.rb
> +cask 'persepolis-download-manager' do
Don’t change this back. I corrected it in accordance with the [token reference](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).

2017-05-06 00:16 UTC, miccal commented
Thank you @ibrokemypie.

2017-05-06 00:16 UTC, merged