Add policy to better prevent malware.
Homebrew/homebrew-cask pull request #33538
Opened 2017-05-07 03:45 UTC by reitermarkus

*If there’s a checkbox you can’t complete for any reason, that's okay, just explain in detail why you weren’t able to do so.*

After making all changes to the cask:

- [ ] `brew cask audit --download {{cask_file}}` is error-free.
- [ ] `brew cask style --fix {{cask_file}}` reports no offenses.
- [ ] The commit message includes the cask’s name and version.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference].
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked there are no [open pull requests] for the same cask.
- [ ] Checked the cask was not already refused in [closed issues].
- [ ] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask

2017-05-07 04:34 UTC, mholt commented
This is a great first step and I definitely approve (for what it's worth). :+1:

However, this is just someone ticking a box. Now might be a good time to start talking about a technical method for enforcing version+hash immutability. I don't have a good answer for Homebrew off-hand, at least, not through the pull request system...

2017-05-07 08:39 UTC, vitorgalvao commented
Yes, the thing we also need to add is a requirement for the person ticking the box to link to a public discussion where they can show they confirmed with the developer that the shasum changed.

@mholt You can’t enforce version+sha immutability. This problem did not occur due to human error and cannot be fixed by software. It was a correctly enforced bad policy, which is why the policy needs to change.

It’s **common**, especially for closed-source (but not only) software developers to update the upstream package in place without changing its version. So the vast majority of times the shasum changes but not the version are legitimate. There are cases where we do check with upstream, but not always (like in Handbrake’s case) due to it being so common. Making the version and the shasum immutable would mean you break multiple casks with no way of fixing them.

2017-05-07 09:18 UTC, vitorgalvao requested changes

2017-05-07 09:18 UTC, vitorgalvao commented on doc/development/updating_a_cask.md
> +# Updating a Cask
This document is mostly a repeat of the PR_TEMPLATE, so I feel it’ll be ignored. I assume most documents are unread unless shoved in the user’s face (i.e. the templates).

So just like the [comment security measure](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/url.md#when-url-and-homepage-hostnames-differ-add-a-comment) is in [`url.md`](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/url.md), I feel like the shasum warning can be in [`sha256.md`](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md) and linked to from the PR_TEMPLATE.

2017-05-07 09:18 UTC, vitorgalvao commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [ ] [If the checksum changed, the version also has to have changed.][version-checksum]
Should have a note asking for a link to a public proof.

2017-05-07 09:30 UTC, vitorgalvao commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [ ] [If the checksum changed, the version also has to have changed.][version-checksum]
Even better, in the longer rules we should mention that if it is asked on Twitter they should @mention [@homebrewcask](twitter.com/homebrewcask), and if on Github they should @mention one of us.

2017-05-08 18:50 UTC, reitermarkus commented on doc/cask_language_reference/stanzas/sha256.md
> + - If confirmed on Twitter, @mention [@homebrewcask](https://twitter.com/homebrewcask),
These should probably end with a dot now, since each point is a complete sentence.

2017-05-08 18:50 UTC, vitorgalvao approved these changes
Fine by me as it is @reitermarkus, but feel free to tweak some more.

2017-05-08 18:50 UTC, reitermarkus commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [ ] `sha256` was update, but `version` remained the same.
*update**d**

2017-05-08 19:00 UTC, merged