Update moom to 3.2.6
Homebrew/homebrew-cask pull request #34088
Opened 2017-05-14 09:32 UTC by giannitm

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

2017-05-14 21:58 UTC, vitorgalvao requested changes

2017-05-14 21:58 UTC, vitorgalvao commented on Casks/moom.rb
> +  url "https://manytricks.com/download/_do_not_hotlink_/moom#{version.no_dots}.dmg"
I think that maybe they might not want this in HBC. We should ask.

2017-05-15 16:54 UTC, giannitm commented
@vitorgalvao I was wondering if that would be an issue, but I'm not sure if that will apply for HBC. I interpreted the message to be targeting sites which offer file downloads, but direct the download request to the Manytricks server, while still earning money themselves from advertising revenue. That is the true spirit of "hotlinking".

2017-05-15 16:57 UTC, gobinathm commented
many appcast have different download URL's compare to the once that's found on their website.  They might be doing it specifically to track downloads (or) something for analytics purpose. As @vitorgalvao it worth checking that, instead of we deciding it

2017-05-15 17:01 UTC, giannitm commented
@gobinathm Good point, didn't think of that.

2017-05-15 17:36 UTC, giannitm commented
New version of Moom has just been released – I'm making another pull request. @vitorgalvao

2017-05-15 17:36 UTC, closed without merging