Add Keypad Layout 1.1
Homebrew/homebrew-cask pull request #34135
Opened 2017-05-14 15:26 UTC by janten

*If there’s a checkbox you can’t complete for any reason, that's okay, just explain in detail why you weren’t able to do so.*

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, if **updating a cask**:

- [ ] [If the `sha256` changed but the `version` didn’t][version-checksum],  
      provide public confirmation by the developer: {{link}}

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not already refused in [closed issues].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

2017-05-14 21:53 UTC, vitorgalvao requested changes

2017-05-14 21:53 UTC, vitorgalvao commented on Casks/keypad-layout.rb
> +  name 'Keypad Layout'
Please add an [`appcast`](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/appcast.md).

2017-05-14 22:31 UTC, janten commented on Casks/keypad-layout.rb
> +  name 'Keypad Layout'
Appcast has been added.

2017-05-14 22:34 UTC, janten commented
@vitorgalvao I have added the requested appcast and amended the original commit.

2017-05-14 22:36 UTC, janten reviewed
Suggested changes have been incorporated into the commit.

2017-05-15 00:29 UTC, miccal commented
Thank you for your contribution.

2017-05-15 00:29 UTC, merged