Update sha256.md - add virustotal
Homebrew/homebrew-cask pull request #34786
Opened 2017-05-23 11:32 UTC by commitay

Add VirusTotal codesigning information.

/CC @vitorgalvao

2017-05-23 14:20 UTC, vitorgalvao commented
Pinging @caskroom/maintainers for comments.

Note that we still need to pay attention to the signer. After all, a malicious actor could sign their malicious change (as happened to Transmission, a while back).

2017-05-23 14:20 UTC, vitorgalvao approved these changes

2017-05-23 14:50 UTC, victorpopkov approved these changes

2017-05-23 18:00 UTC, giannitm commented on doc/cask_language_reference/stanzas/sha256.md
> +Maintainers will confirm the VirusTotal submission is legitimate by comparing it’s `sha256` with the one on the updated cask.
Should be "its" not "it's".

2017-05-23 18:01 UTC, gtmgianni requested changes

2017-05-23 18:01 UTC, giannitm commented on doc/cask_language_reference/stanzas/sha256.md
> +Maintainers will confirm the VirusTotal submission is legitimate by comparing it’s `sha256` with the one on the updated cask.
Should be "its" not "it's".

2017-05-23 23:31 UTC, miccal approved these changes

2017-05-25 12:07 UTC, commitay commented on doc/cask_language_reference/stanzas/sha256.md
> +Maintainers will confirm the VirusTotal submission is legitimate by comparing its `sha256` with the one on the updated cask.
Should this be moved above the example?

2017-05-25 23:38 UTC, miccal commented on doc/cask_language_reference/stanzas/sha256.md
> +Maintainers will confirm the VirusTotal submission is legitimate by comparing its `sha256` with the one on the updated cask.
I think it is fine where it is.

2017-05-26 13:09 UTC, merged