Added cask to install Rider EAP from Jetbrains, at version EAP Build 22
Homebrew/homebrew-cask pull request #34865
Opened 2017-05-25 02:06 UTC by sgleadow

Moved existing PR here from homebrew-versions caskroom/homebrew-versions#3897

After making all changes to the cask:

- [ ] `brew cask audit --download {{cask_file}}` is error-free.
- [ ] `brew cask style --fix {{cask_file}}` reports no offenses.
- [ ] The commit message includes the cask’s name and version.

Additionally, if **adding a new cask**:

- [ ] Named the cask according to the [token reference].
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked there are no [open pull requests] for the same cask.
- [ ] Checked the cask was not already refused in [closed issues].
- [ ] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

2017-05-25 02:41 UTC, vitorgalvao commented
Pinging @leipert for a quick review.

2017-05-25 04:13 UTC, reitermarkus requested changes

2017-05-25 04:13 UTC, reitermarkus commented on Casks/rider-eap.rb
> +    ENV['PATH'].split(File::PATH_SEPARATOR).map { |path| File.join(path, 'river') }.each { |path| File.delete(path) if File.exist?(path) }
Shouldn't this be `rider` here?

Also, you could use:

```ruby
uninstall delete: ENV['PATH'].split(File::PATH_SEPARATOR).map { |p| "#{p}/rider" }
```

2017-05-25 04:14 UTC, reitermarkus commented on Casks/rider-eap.rb
> +    ENV['PATH'].split(File::PATH_SEPARATOR).map { |path| File.join(path, 'river') }.each { |path| File.delete(path) if File.exist?(path) }
Also, isn't this always in `/usr/local/bin`?

2017-05-25 05:30 UTC, sgleadow commented on Casks/rider-eap.rb
> +    ENV['PATH'].split(File::PATH_SEPARATOR).map { |path| File.join(path, 'river') }.each { |path| File.delete(path) if File.exist?(path) }
Thanks for the feedback, and catching my typo. I've corrected to `river` and used the `uninstall delete: ` format, and pushed it.

In terms of the location, it defaults to `/usr/local/bin` but the user can override, so it could be anywhere on their path.

I've just based the format on the intellij-idea cask, and editing from there (new to this cask business).

2017-05-25 08:15 UTC, miccal commented on Casks/rider-eap.rb
> +    ENV['PATH'].split(File::PATH_SEPARATOR).map { |path| File.join(path, 'river') }.each { |path| File.delete(path) if File.exist?(path) }
```
>>> brew cask style Casks/rider-eap.rb
== Casks/rider-eap.rb ==
W: 13: 68: Unused block argument - p. You can omit the argument if you don't care about it.
C: 13: 71: Prefer single-quoted strings when you don't need string interpolation or special symbols.
```

Ping @reitermarkus for advice here.

2017-05-25 17:46 UTC, reitermarkus commented on Casks/rider-eap.rb
> +  uninstall delete: ENV['PATH'].split(File::PATH_SEPARATOR).map { |p| "{p}/rider" }.each { |path| File.delete(path) if File.exist?(path) }
Should be `#{p}`, not `{p}`.

2017-05-25 22:25 UTC, sgleadow commented on Casks/rider-eap.rb
> +  uninstall delete: ENV['PATH'].split(File::PATH_SEPARATOR).map { |p| "{p}/rider" }.each { |path| File.delete(path) if File.exist?(path) }
Ah sorry about that... I tested it, but it must have picked up my original cask in "homebrew-versions" and used that. I've updated the code. I changed the `each` to a `select` so it only returns the paths that actually exist (I'm assuming only 1 in practice).

Style should be ok now:

```
$ brew cask style Casks/rider-eap.rb 

1 file inspected, no offenses detected
```

Checked uninstall detects and removes the command line binary:

```
$ brew cask uninstall rider-eap
==> Uninstalling Cask rider-eap
==> Running uninstall process for rider-eap; your password may be necessary
==> Removing files:
/usr/local/bin/rider
Password:
==> Removing App '/Applications/Rider EAP.app'.
```

2017-05-25 23:39 UTC, miccal commented
Thank you @sgleadow.

2017-05-25 23:39 UTC, merged

2017-05-26 07:28 UTC, leipert commented
Sorry. There was a public holiday yesterday in 🇩🇪 .
LAGTM.
I made some adjustments in #34917