Add transmit-disk 4.4.12
Homebrew/homebrew-cask pull request #34948
Opened 2017-05-26 18:35 UTC by phatblat

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not already refused in [closed issues].
- [x] Checked the cask is submitted to [the correct repo].

## Notes 

Transmit Disk is a helper app for Transmit which is separate due to Mac App Store sandboxing restrictions. The helper app is necessary to mount a remote server as a disk in the Finder. I believe it uses [FUSE](https://osxfuse.github.io) to do this as it installs a 2nd bundle to `/Library/Filesystems/transmitdisk.fs`.

The `com.panic.TransmitDisk.pkg` package installs `Transmit Disk.app` into `/tmp/` which doesn't seem like a good permanent home.

I tried setting `customLocation` in choices, which worked to put the .app in `/Applications`, but the installer validation failed. So, instead this uses a `postflight` move, paired with an `uninstall`/`trash`.

2017-05-27 22:17 UTC, vitorgalvao requested changes

2017-05-27 22:17 UTC, vitorgalvao commented on Casks/transmit-disk.rb
> +    system_command 'mv',
Don’t use `mv` (also, always use the full path). Instead, use ruby itself (`FileUtils`).

2017-05-27 22:17 UTC, vitorgalvao commented on Casks/transmit-disk.rb
> +                           '/Applications/',
Use `appdir` so it uses the user’s choice. Also, don’t end directory paths in `/`.

2017-05-27 22:17 UTC, vitorgalvao commented on Casks/transmit-disk.rb
> +            trash:   '/Applications/Transmit Disk.app'
`appdir` here as well. Also, use `delete`, `trash` does not work yet.

2017-05-27 22:17 UTC, vitorgalvao commented on Casks/transmit-disk.rb
> +                '/Applications/Transmit Disk.app',
`zap` always runs `uninstall` first. Remove this line.

2017-05-27 22:17 UTC, vitorgalvao commented on Casks/transmit-disk.rb
> +  depends_on cask: 'transmit'
If `transmit` can be installed from the App Store, don’t force it being installed by us.

2017-05-28 00:48 UTC, phatblat commented on Casks/transmit-disk.rb
> +    system_command 'mv',
I don't know if `FileUtils` will work. Is there a way to run it through `sudo`?

```
Error: Permission denied - (/tmp/Transmit/Transmit Disk.app, /Applications/Transmit Disk.app)
```

Installer packages get ran [through `sudo`](https://github.com/Homebrew/brew/blob/d1f599f1ed51976fc76ad19803de04864d12ef2b/Library/Homebrew/cask/lib/hbc/artifact/pkg.rb#L55), so the installed files are owned by root.

```
ls -ld /Applications /tmp /tmp/Transmit /tmp/Transmit/Transmit\ Disk.app                                                                                                                                                                                                          5  18:41:42
drwxrwxr-x+ 163 root        admin        5542 May 27 18:05 /Applications/
lrwxr-xr-x@   1 root        wheel          11 Sep 26  2016 /tmp -> private/tmp
drwxr-xr-x    3 root        wheel         102 May 27 18:40 /tmp/Transmit/
drwxr-xr-x    3 root        wheel         102 May 27 18:40 /tmp/Transmit/Transmit Disk.app/
```

2017-05-28 00:52 UTC, phatblat commented on Casks/transmit-disk.rb
> +    system_command 'mv',
nvm, I found [set_ownership](https://github.com/Homebrew/brew/blob/b6f3399cb3facababf4f6b1e6f7821edc2db554a/Library/Homebrew/cask/lib/hbc/staged.rb#L33)

2017-05-28 02:51 UTC, vitorgalvao approved these changes

2017-05-28 04:19 UTC, merged