Add Syncthing BrewBar.app beta2
Homebrew/homebrew-cask pull request #35530
Opened 2017-06-14 14:48 UTC by jonashoechst

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not already refused in [closed issues].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

2017-06-14 16:22 UTC, vitorgalvao requested changes

2017-06-14 16:22 UTC, vitorgalvao commented on Casks/syncthing-brewbar.rb
> +  name 'Syncthing BrewBar'
Please add an [`appcast`](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/appcast.md).

2017-06-15 09:48 UTC, miccal commented
[Unfortunately we cannot accept this in Cask.](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/rejected_casks.md)

2017-06-15 09:48 UTC, closed without merging

2017-06-15 09:55 UTC, vitorgalvao commented
Nice catch, @miccal. Could swear I had checked the repo.

@jonashoechst Reason is the second from the bottom in the first least (“the Cask is too obscure”).