Adding the latest version of deepstream.io to cask
Homebrew/homebrew-cask pull request #36067
Opened 2017-07-01 19:13 UTC by yasserf

This change allows users to use cask to download the deepstream.io
pkg. A small limitations are the fact that it currently
uses 777 settings for log directories.

*If there’s a checkbox you can’t complete for any reason, that's okay, just explain in detail why you weren’t able to do so.*

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, if **updating a cask**:

- [ ] [If the `sha256` changed but the `version` didn’t][version-checksum],  
      provide public confirmation by the developer: {{link}}

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not already refused in [closed issues].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

2017-07-01 19:35 UTC, vitorgalvao requested changes

2017-07-01 19:35 UTC, vitorgalvao commented on Casks/deepstream.rb
> +  version '2.4.0'
[This is a pre-release](https://github.com/deepstreamIO/deepstream.io/releases). Use `2.3.7` instead.

2017-07-01 19:35 UTC, vitorgalvao commented on Casks/deepstream.rb
> +  url 'https://s3.amazonaws.com/ds-server-artifacts/deepstreamIO/deepstream.io/2.4.0/deepstream.io-mac-2.4.0-5bca621.pkg'
Use the link from the Github instead.

2017-07-01 19:35 UTC, vitorgalvao commented on Casks/deepstream.rb
> +  url 'https://s3.amazonaws.com/ds-server-artifacts/deepstreamIO/deepstream.io/2.4.0/deepstream.io-mac-2.4.0-5bca621.pkg'
Add an [`appcast`](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/appcast.md).

2017-07-01 19:35 UTC, vitorgalvao commented on Casks/deepstream.rb
> +  # s3.amazonaws.com was verified as official when first introduced to the cask
Comment needs to be more specific.

2017-07-01 19:35 UTC, vitorgalvao commented on Casks/deepstream.rb
> +  url 'https://s3.amazonaws.com/ds-server-artifacts/deepstreamIO/deepstream.io/2.4.0/deepstream.io-mac-2.4.0-5bca621.pkg'
Use interpolation ([example](https://github.com/caskroom/homebrew-cask/blob/fae58b599ea95a6c251d20aab4caf2dc044fb112/Casks/alfred.rb#L5)).

2017-07-01 19:35 UTC, vitorgalvao commented on Casks/deepstream.rb
> +  pkg 'deepstream.io-mac-2.4.0-5bca621.pkg'
Use interpolation ([example](https://github.com/caskroom/homebrew-cask/blob/fae58b599ea95a6c251d20aab4caf2dc044fb112/Casks/alfred.rb#L5)).

2017-07-01 19:35 UTC, vitorgalvao commented on Casks/deepstream.rb
> +  homepage 'https://deepstreamhub.com/'
Why not `https://deepstream.io/`?

2017-07-01 19:35 UTC, vitorgalvao commented on Casks/deepstream.rb
> +cask 'deepstream' do
`deepstreamio`.

2017-07-01 19:37 UTC, yasserf commented on Casks/deepstream.rb
> +  version '2.4.0'
Just removed pre-release tag

2017-07-01 19:38 UTC, yasserf commented on Casks/deepstream.rb
> +cask 'deepstream' do
the executable itself is deepstream, I was told cask names should try match the binary

2017-07-01 19:38 UTC, yasserf commented on Casks/deepstream.rb
> +  url 'https://s3.amazonaws.com/ds-server-artifacts/deepstreamIO/deepstream.io/2.4.0/deepstream.io-mac-2.4.0-5bca621.pkg'
will do, thanks!

2017-07-01 19:39 UTC, yasserf commented on Casks/deepstream.rb
> +  homepage 'https://deepstreamhub.com/'
We will be merging the two websites pretty soon since they are quite defragmented. I can change it to deepstream.io and move it once the move is done

2017-07-01 19:41 UTC, vitorgalvao commented on Casks/deepstream.rb
> +  homepage 'https://deepstreamhub.com/'
> I can change it to deepstream.io and move it once the move is done

That is preferable. Thank you.

2017-07-01 19:42 UTC, yasserf commented on Casks/deepstream.rb
> +cask 'deepstream' do
changed the name of the cask inside to match

2017-07-01 19:42 UTC, vitorgalvao commented on Casks/deepstream.rb
> +cask 'deepstream' do
> the executable itself is deepstream, I was told cask names should try match the binary

That is fine, then.

2017-07-01 19:53 UTC, yasserf commented
Applied recommended changes, thanks for quick feedback!

2017-07-01 20:08 UTC, yasserf commented
Odd with CI, just ran same change locally and got this

```
brew cask _audit_modified_casks 983124cfe24e29a2a7b47ca08402b328d9de38ad...402a11c2a5fa36b2a964602d4082d0d9408fa50e
==> 1 modified cask: deepstream
==> Downloading https://github.com/deepstreamIO/deepstream.io/releases/download/v2.4.0/deepstream.io-mac-2.4.0.pkg
Already downloaded: /Users/yasserf/Library/Caches/Homebrew/Cask/deepstream--2.4.0.pkg
==> Verifying checksum for Cask deepstream
audit for deepstream: passed
```

2017-07-02 01:36 UTC, commitay commented
> Odd with CI, just ran same change locally and got this

> Already downloaded: /Users/yasserf/Library/Caches/Homebrew/Cask/deepstream--2.4.0.pkg

The `pkg` is still cached.

> Also, does mac get stripped out intentionally from the file name?

Yes, Cask saves the downloads as `name--version`

> A small limitations are the fact that it currently uses 777 settings for log directories.

Where are the logs located?

2017-07-02 09:05 UTC, yasserf commented
> Where are the logs located?

logs are located at `/usr/var/logs/deepstream/`

2017-07-02 09:48 UTC, commitay commented
Thanks @yasserf

2017-07-02 09:48 UTC, commitay approved these changes

2017-07-02 09:50 UTC, merged

2017-07-02 09:54 UTC, yasserf commented
Awesome, thanks!