Certificate issue on installation
Homebrew/homebrew-cask pull request #36725
Opened 2017-07-18 18:00 UTC by suxxes

Certificate used to sign package is not trusted. Use -allowUntrusted to override.

*If there’s a checkbox you can’t complete for any reason, that's okay, just explain in detail why you weren’t able to do so.*

After making all changes to the cask:

- [ ] `brew cask audit --download {{cask_file}}` is error-free.
- [ ] `brew cask style --fix {{cask_file}}` reports no offenses.
- [ ] The commit message includes the cask’s name and version.

Additionally, if **updating a cask**:

- [ ] [If the `sha256` changed but the `version` didn’t][version-checksum],  
      provide public confirmation by the developer: {{link}}

Additionally, if **adding a new cask**:

- [ ] Named the cask according to the [token reference].
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked there are no [open pull requests] for the same cask.
- [ ] Checked the cask was not already refused in [closed issues].
- [ ] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

2017-07-18 18:29 UTC, vitorgalvao commented
Thank you for the contribution. Next time, please fill the template.

I’m going to refuse this. There’s a significant difference between an unsigned packaged and one with an invalid signature. This is the latter. By adding `allow_untrusted`, you’re making so that when the certificate is fixed, we won’t notice and then be vulnerable.

The correct fix here is to contact upstream about the issue. Care to do so?

2017-07-18 18:31 UTC, vitorgalvao requested changes
There’s a significant difference between an unsigned packaged and one with an invalid signature. This is the latter (expired certificate).

2017-07-26 15:16 UTC, vitorgalvao commented
Closing for lack of reply.

If someone else stubs against this problem before upstream fixes it, we’ll deal with it then.

2017-07-26 15:16 UTC, closed without merging

2017-08-14 21:03 UTC, BM5k commented
Hitting this for ksdiff today. Manual installation worked without a certificate error. Not sure what needs to be changed to remove the error from cask-based install.

2017-08-14 23:08 UTC, vitorgalvao commented
> Not sure what needs to be changed to remove the error from cask-based install.

You need to contact the developers of the app and tell them the certificate they used to sign the package has expired.

2017-08-15 04:37 UTC, BM5k commented
@vitorgalvao the cask points to this [package][0] with this sha256 checksum `9570f53dcbeb558c53f4808ba58e8c9f394a3026e8bdd122277200a1cdf11e52`

That's the same package linked to [here][1] (same download URL).
Manually downloading the file results in the same checksum:

```
openssl dgst -sha256 ~/Downloads/ksdiff-122.zip
SHA256(/Users/bm5k/Downloads/ksdiff-122.zip)= 9570f53dcbeb558c53f4808ba58e8c9f394a3026e8bdd122277200a1cdf11e52
```

Installing from the manual download doesn't complain about the certificate warning.
Installing from the cask does.

So, it seems like there is a problem with the cask _not_ the certificate or the package (unless cask is more strictly checking the cert than installer, which would be a lame decision on apple's part).

[0]: https://cdn.kaleidoscopeapp.com/releases/ksdiff-122.zip
[1]: https://www.kaleidoscopeapp.com/ksdiff2

2017-08-15 05:01 UTC, commitay commented
```
pkgutil --check-signature Install\ ksdiff.pkg
Package "Install ksdiff.pkg":
   Status: signed by a certificate that has since expired
   Certificate Chain:
    1. Developer ID Installer: Black Pixel
       SHA1 fingerprint: B2 0D D5 48 F4 61 57 48 92 F2 2F 3F 7F A3 82 3A 3D 25 1C F5
       -----------------------------------------------------------------------------
    2. Developer ID Certification Authority
       SHA1 fingerprint: 3B 16 6C 3B 7D C4 B7 51 C9 FE 2A FA B9 13 56 41 E3 88 E1 86
       -----------------------------------------------------------------------------
    3. Apple Root CA
       SHA1 fingerprint: 61 1E 5B 66 2C 59 3A 08 FF 58 D1 4A E2 24 52 D1 98 DF 6C 60

```

2017-08-15 05:04 UTC, BM5k commented
@commitay OK, I verified that the manual download also fails that check.

Does installer not display those errors when installing? I received no warning in the GUI when installing _this package_ today.

2017-08-15 05:14 UTC, commitay commented
> Does installer not display those errors when installing?

`/usr/sbin/installer` seems to have stricter cert checks.