Add Kactus.app v0.1.14
Homebrew/homebrew-cask pull request #36975
Opened 2017-07-25 18:12 UTC by imasaru

*If there’s a checkbox you can’t complete for any reason, that's okay, just explain in detail why you weren’t able to do so.*

After making all changes to the cask:

- [X] `brew cask audit --download {{cask_file}}` is error-free.
- [X] `brew cask style --fix {{cask_file}}` reports no offenses.
- [X] The commit message includes the cask’s name and version.

Additionally, if **updating a cask**:

- [ ] [If the `sha256` changed but the `version` didn’t][version-checksum],  
      provide public confirmation by the developer: {{link}}

Additionally, if **adding a new cask**:

- [X] Named the cask according to the [token reference].
- [X] `brew cask install {{cask_file}}` worked successfully.
- [X] `brew cask uninstall {{cask_file}}` worked successfully.
- [X] Checked there are no [open pull requests] for the same cask.
- [X] Checked the cask was not already refused in [closed issues].
- [X] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

I wasn't sure how to implement the checkpoint, so I'll leave it to @commitay or someone else :)

2017-07-25 19:25 UTC, vitorgalvao requested changes

2017-07-25 19:25 UTC, vitorgalvao commented on Casks/kactus.rb
> +  name 'Kactus'
Please add an [`appcast`](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/appcast.md).

2017-07-25 19:41 UTC, imasaru commented
I'm guessing you mean that it doesn't need Sketch to run on its own, which, of course, is true, but for the app to work at full functionality, Sketch is a requirement.

Looking at the application:
https://farm5.staticflickr.com/4303/36030060331_9d17097f17_o.png

2017-07-25 23:20 UTC, imasaru commented on Casks/kactus.rb
> +  name 'Kactus'
Done

2017-07-25 23:42 UTC, commitay commented
>  but for the app to work at full functionality, Sketch is a requirement.

Ping @vitorgalvao

2017-07-25 23:55 UTC, vitorgalvao commented
@imasaru Ah, alright. Especially since they mentioned planned support for other apps, I though they only needed the files, not the app itself.

2017-07-25 23:56 UTC, vitorgalvao approved these changes

2017-07-26 00:06 UTC, miccal commented
Thank you for your contribution.

2017-07-26 00:06 UTC, merged