soapui fix - program hangs on first launch
Homebrew/homebrew-cask pull request #37310
Opened 2017-08-02 18:59 UTC by TheLonelyGhost

Due diligence:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] If `sha256` changed but the version didn't, included public confirmation by developer.

See [StackOverflow answer](https://stackoverflow.com/a/44325050/1236035) about problem with running SOAP UI after installing. This automates that fix, with slightly future-proof checks in case it is fixed upstream.

Also includes some configuration file additions to zap, since there was a missing zap stanza.

2017-08-02 21:03 UTC, vitorgalvao requested changes

2017-08-02 21:03 UTC, vitorgalvao commented on Casks/soapui.rb
> +      system %Q{sed -i'' -e 's/#.*\\(JAVA_OPTS=".*-Dsoapui\\.browser\\.disabled=true".*\\)$/\\1/g' "#{file}" 1>/dev/null}
Use `system_command`.

2017-08-02 21:17 UTC, commitay commented
I can't reproduce any issues with launching `soapui`, is this something we should be fixing here if it isn't a consistent problem?

2017-08-03 05:36 UTC, reitermarkus requested changes

2017-08-03 05:36 UTC, reitermarkus commented on Casks/soapui.rb
> +      system %Q{sed -i'' -e 's/#.*\\(JAVA_OPTS=".*-Dsoapui\\.browser\\.disabled=true".*\\)$/\\1/g' "#{file}" 1>/dev/null}
This could be done in Ruby, so we don‘t have to duplicate the regex.

2017-08-10 06:24 UTC, commitay commented
Ping @TheLonelyGhost

2017-08-12 03:48 UTC, miccal commented
Closing in favour of https://github.com/caskroom/homebrew-cask/pull/37594.

2017-08-12 03:48 UTC, closed without merging