Add DotEditor.app v0.3.1
Homebrew/homebrew-cask pull request #37332
Opened 2017-08-03 17:40 UTC by shageman

This PR adds DotEditor, a graphviz dotfile editor.

After making all changes to the cask:

- [X] `brew cask audit --download {{cask_file}}` is error-free.
- [X] `brew cask style --fix {{cask_file}}` reports no offenses.
- [X] The commit message includes the cask’s name and version.

Additionally, if **adding a new cask**:

- [X] Named the cask according to the [token reference].
- [X] `brew cask install {{cask_file}}` worked successfully.
- [X] `brew cask uninstall {{cask_file}}` worked successfully.
- [X] Checked there are no [open pull requests] for the same cask.
- [X] Checked the cask was not already refused in [closed issues].
- [X] Checked the cask is submitted to [the correct repo].

2017-08-03 18:39 UTC, vitorgalvao requested changes

2017-08-03 18:39 UTC, vitorgalvao commented on Casks/doteditor.rb
> +  caveats "Graphviz needs to be installed for #{token} to work."
Use [`depends_on`](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/depends_on.md) instead.

2017-08-03 18:39 UTC, vitorgalvao commented on Casks/doteditor.rb
> +  sha256 :no_check
This needs to be set. Run `shasum -a 256` on the downloaded file.

2017-08-03 18:39 UTC, vitorgalvao commented on Casks/doteditor.rb
> +  url "https://github.com/vincenthEE/DotEditor/releases/download/v#{version}/DotEditor.#{version}.dmg"
This needs a comment above, that the `style` command will have warned about.

2017-08-03 22:12 UTC, vitorgalvao approved these changes

2017-08-04 08:53 UTC, merged

2017-08-04 08:54 UTC, victorpopkov commented
Thank you for your contribution!