update dotnet-sdk version to  2.0.0
Homebrew/homebrew-cask pull request #37661
Opened 2017-08-14 18:55 UTC by mathewpeterson

*If there’s a checkbox you can’t complete for any reason, that's okay, just explain in detail why you weren’t able to do so.*

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, if **updating a cask**:

- [ ] `sha256` changed but `version` stayed the same ([what is this?][version-checksum]).  
      I’m providing public confirmation below.

Additionally, if **adding a new cask**:

- [ ] Named the cask according to the [token reference].
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked there are no [open pull requests] for the same cask.
- [ ] Checked the cask was not already refused in [closed issues].
- [ ] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

2017-08-14 19:07 UTC, vitorgalvao requested changes

2017-08-14 19:07 UTC, vitorgalvao commented on Casks/dotnet-sdk.rb
> +    run_times = ['2.0.0']
If it’s only one, there’s no point in this variable and the loop, now.

2017-08-14 19:20 UTC, mathewpeterson commented on Casks/dotnet-sdk.rb
> +    run_times = ['2.0.0']
@vitorgalvao I didn't want to change functionality but I honestly don't know why loop exists.

2017-08-15 01:00 UTC, commitay commented
`openssl` dependancy is no longer needed as of `2.0.0`

2017-08-15 01:03 UTC, commitay approved these changes

2017-08-15 08:22 UTC, merged