New formula: ICC for Mac v1.0.r7564
Homebrew/homebrew-cask pull request #37749
Opened 2017-08-17 15:52 UTC by apetresc

ICC is the most popular chess server worldwide. This is their official Mac client.

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not already refused in [closed issues].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

2017-08-17 17:55 UTC, apetresc commented
Okay, yeah, I wasn't sure about the "for Mac" part of the name. I opted to keep it because it's definitely a part of the app's own branding; the .app file is called "ICC for Mac.app", etc. But either way :)

2017-08-17 19:24 UTC, apetresc commented
Apparently Travis is failing on `#{version.patch}` not resolving to anything. Does it not work with non-numerical patch numbers? (the 'r' in this case?)

2017-08-17 19:31 UTC, apetresc commented
Indeed, that does seem to be the problem. The [current `patch` regex](https://github.com/Homebrew/brew/blob/19347f3b87917368d7157fe5007d506a4db0c7db/Library/Homebrew/cask/lib/hbc/dsl/version.rb#L13) only works for purely-numerical patch numbers.

2017-08-17 19:37 UTC, vitorgalvao approved these changes

2017-08-18 10:49 UTC, vitorgalvao requested changes

2017-08-18 10:49 UTC, vitorgalvao commented on Casks/icc.rb
> +                '~/.cache/internet_chess_club',
Caches are for `delete`.

2017-08-18 22:11 UTC, merged