Update real-vnc.rb
Homebrew/homebrew-cask pull request #38155
Opened 2017-08-31 02:55 UTC by daylightbrightledlight

I've updated some little-snitch.rb zaps and uninstalls

2017-08-31 05:14 UTC, commitay requested changes

2017-08-31 05:14 UTC, commitay commented on Casks/real-vnc.rb
> +                '/Library/LaunchAgents/com.realvnc.vncserver.peruser.plist',
Remove this line, it is removed by `uninstall launchctl`

2017-08-31 05:27 UTC, commitay commented
https://github.com/caskroom/homebrew-cask/pull/38152#issuecomment-326192869

2017-09-01 03:57 UTC, daylightbrightledlight commented on Casks/real-vnc.rb
> +                '/Library/LaunchAgents/com.realvnc.vncserver.peruser.plist',
Okay.

2017-09-01 04:22 UTC, commitay approved these changes

2017-09-01 04:22 UTC, merged