Add duplicati.rb zaps
Homebrew/homebrew-cask pull request #38152
Opened 2017-08-31 02:49 UTC by daylightbrightledlight

After making all changes to the cask:

- [ ] `brew cask audit --download {{cask_file}}` is error-free.
- [ ] `brew cask style --fix {{cask_file}}` reports no offenses.
- [ ] The commit message includes the cask’s name and version.

Additionally, if **updating a cask**:

- [ ] `sha256` changed but `version` stayed the same ([what is this?][version-checksum]).  
      I’m providing public confirmation below.

Additionally, if **adding a new cask**:

- [ ] Named the cask according to the [token reference].
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked there are no [open pull requests] for the same cask.
- [ ] Checked the cask was not already refused in [closed issues].
- [ ] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

2017-08-31 03:05 UTC, daylightbrightledlight commented
For some reason, the CI build could not compete.

2017-08-31 05:16 UTC, commitay requested changes

2017-08-31 05:16 UTC, commitay commented on Casks/duplicati.rb
> +  zap delete: [
`zap trash`

2017-08-31 05:23 UTC, commitay commented
@daylightbrightledlight Please add PR templates and complete `style` and `audit` checks for all open PRs.

2017-09-01 02:36 UTC, daylightbrightledlight commented
@commitay Hi there. I've read the [documentation](https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#testing-your-new-cask), but I am having trouble trying to configure brew to use my patched casks. How do I edit the cask using my repository without messing up brew cask from being able to work normally?

2017-09-01 02:40 UTC, daylightbrightledlight commented
> Please add PR templates

I'll add the PR templates.

2017-09-01 02:50 UTC, commitay commented
> but I am having trouble trying to configure brew to use my patched casks. How do I edit the cask using my repository without messing up brew cask from being able to work normally?

You don't need to configure anything.

Run `brew cask style --fix /path/to/edited/cask.rb` and `brew cask audit --download /path/to/edited/cask.rb`

2017-09-01 02:59 UTC, daylightbrightledlight commented
@commitay Okay thanks. I used `brew cask style --fix`. After `Installing or updating 'rubocop-cask' gem` finished, I ended up with the following error:

```
E: 25:  1: unexpected token kEND
(Using Ruby 2.1 parser; configure using TargetRubyVersion parameter, under AllCops)

1 file inspected, 1 offense detected
Error: style check failed
```

I'll work on trying to fix this and keep you updated.

2017-09-01 03:35 UTC, commitay commented
> However the audit failed:

```
 - appcast checkpoint mismatch
Expected: a62964fa18b2896ce5de9ac6c7a2012457c1bfb4b36d9cf2ae4f336aca5e65fd
Actual: 1d9839044f40dd3ee88a76d1074c8c34b7162a0960512932deeaa1e2d94fe9ee
```

You need to replace the `appcast` checkpoint with its current value.

2017-09-01 03:36 UTC, commitay commented on Casks/duplicati.rb
> +  zap delete: [
`zap trash`

2017-09-01 03:43 UTC, daylightbrightledlight commented on Casks/duplicati.rb
> +  zap delete: [
Okay. I've changed it to `zap trash`

2017-09-01 03:45 UTC, daylightbrightledlight commented
I think I've completed the requirements. Please let me know if this patch is ready.

2017-09-01 04:10 UTC, commitay approved these changes

2017-09-01 04:10 UTC, merged