avimetaedit-app 1.0.1
Homebrew/homebrew-cask pull request #39080
Opened 2017-09-28 13:31 UTC by g-maxime

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not already refused in [closed issues].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

2017-09-28 14:31 UTC, miccal commented
https://github.com/Homebrew/homebrew-core/pull/18621

2017-09-28 20:16 UTC, commitay requested changes

2017-09-28 20:16 UTC, commitay commented on Casks/avimetaedit-app.rb
> +cask 'avimetaedit-app' do
Please change this to `avi-metaedit-app`

2017-09-28 22:18 UTC, commitay commented
https://github.com/caskroom/homebrew-cask/pull/39078#issuecomment-332979343

2017-09-29 15:46 UTC, g-maxime commented
Renamed, thanks to @commitay

2017-09-29 21:44 UTC, miccal commented
@g-maxime thank you for your contribution, but we cannot accept this Cask at this time.

2017-09-29 21:44 UTC, closed without merging