Update keepassxc to 2.2.1
Homebrew/homebrew-cask pull request #39278
Opened 2017-10-04 14:30 UTC by ckesc

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, if **updating a cask**:

- [ ] `sha256` changed but `version` stayed the same ([what is this?](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256)).
      I’m providing public confirmation below.

2017-10-04 22:16 UTC, commitay requested changes

2017-10-04 22:16 UTC, commitay commented on Casks/keepassxc.rb
> +      key_id: 'BF5A669F2272CF4324C1FDA8CFB4C2166397D0D2'
Please change this to a single line.
```
gpg "#{url}.sig", key_url: 'https://keepassxc.org/keepassxc_master_signing_key.asc'
```

2017-10-04 22:52 UTC, ckesc commented on Casks/keepassxc.rb
> +      key_id: 'BF5A669F2272CF4324C1FDA8CFB4C2166397D0D2'
Ok.
By the way, Is GPG verification already works? I found that it is still experimental feature.

2017-10-04 22:55 UTC, commitay commented on Casks/keepassxc.rb
> +      key_id: 'BF5A669F2272CF4324C1FDA8CFB4C2166397D0D2'
GPG verification is not yet implemented.

2017-10-05 01:11 UTC, commitay approved these changes

2017-10-05 09:56 UTC, merged