add Kapow v1.5.3
Homebrew/homebrew-cask pull request #39384
Opened 2017-10-06 21:26 UTC by alfiepates

Nice little time-tracking utility from the person who wrote [FocusWriter].

[FocusWriter]: https://github.com/caskroom/homebrew-cask/blob/master/Casks/focuswriter.rb

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

~~Additionally, if **updating a cask**:~~

- [ ] ~~`sha256` changed but `version` stayed the same ([what is this?][version-checksum]).  
      I’m providing public confirmation below.~~

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not already refused in [closed issues].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

2017-10-06 21:29 UTC, commitay requested changes

2017-10-06 21:29 UTC, commitay commented on Casks/kapow.rb
> +  url 'https://gottcode.org/kapow/Kapow_1.5.3.dmg'
`url "https://gottcode.org/kapow/Kapow_#{version}.dmg"`

2017-10-06 21:29 UTC, commitay commented on Casks/kapow.rb
> +  zap trash: '~/Library/Application Support/GottCode/Kapow/*'
`zap trash: '~/Library/Application Support/GottCode/Kapow'`

2017-10-06 21:33 UTC, alfiepates commented on Casks/kapow.rb
> +  zap trash: '~/Library/Application Support/GottCode/Kapow/*'
Noticed and fixed this one, and proceeded to slightly break my PR by squashing the commits together >.<

2017-10-06 23:44 UTC, commitay approved these changes

2017-10-07 01:12 UTC, merged

2017-10-07 01:12 UTC, miccal commented
Thank you for your contribution.