New Cask: gfortran 6.1
Homebrew/homebrew-cask pull request #40065
Opened 2017-10-26 15:07 UTC by jeroen

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not already refused in [closed issues].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

---

The following formula allows for installing gfortran. Technically, this is actually a dependency of the `r-app` Cask, but in practice it is only needed to install R packages with fortran code, which is only a few of them. 

The build gfortran that ships with homebrew `gcc` is incompatible with the gfortran runtime that ships with `r-app`. More details are given on the [r-project website](https://cran.r-project.org/bin/macosx/tools/) in particular this fragment:

> __Important note__: R 3.4.0 El Capitan binaries are using Clang 4.0.0 and GNU Fortran 6.1 to provide OpenMP parallelization support and C++17 standard features. If you want to compile R packages from sources, please download GNU Fortran binary from the official GNU Fortran Binaries page - in particular OS X 10.11 gfortran 6.1. 

Thanks for considering.

2017-10-26 16:18 UTC, vitorgalvao commented
Thank you for the submission.

This seems to be a CLI-only open-source tool. Please submit it first to [Homebrew/core](https://github.com/Homebrew/homebrew-core) and only if they don’t accept it, submit here (linking back to the pull request where it was refused).

This policy is documented in [faq/rejected_casks](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/rejected_casks.md):

> The app is both open-source and CLI-only (i.e. it only uses the `binary` artifact). In that case, and [in the spirit of deduplication](https://github.com/caskroom/homebrew-cask/issues/15603), submit it first to [Homebrew/core](https://github.com/Homebrew/homebrew-core). If it is rejected there, you may then try again in Homebrew-Cask (link us to the issue on Homebrew so we can see their reasoning for rejection).

2017-10-26 16:40 UTC, jeroen commented
I don't understand. Should I submit the cask to core? The problem is that `gfortran` is part of `gcc` which is already in homebrew, but we would like to provide the official binary build.

2017-10-26 19:52 UTC, commitay commented
@jeroen Is `6.1` needed specifically or should be be dependent on macOS version?

2017-10-26 20:07 UTC, jeroen commented
We specifically like use the 6.1 version. This build targets el-capitain so it works on all currently supported versions of MacOS (10.11, 10.12, 10.13).

2017-10-26 20:13 UTC, commitay commented
@vitorgalvao I think this would be better suited in a personal tap because the use case won't support the usual `if MacOS.version` and `6.1` is not the latest release.

2017-10-26 20:30 UTC, jeroen commented
The 6.1 build is the latest version that works on all currently supported MacOS versions. The latest build from [the website](https://gcc.gnu.org/wiki/GFortranBinaries#MacOS) is 6.3 for Sierra. We could conditionally install the 6.3 version on Sierra and up. For simplicity R just uses the 6.1 build so that we have a single toolchain across different MacOS users, but either way is fine by me.

Sure I can host it in my own tap, but I do think that the official Fortran for MacOS (that does not require the entire gcc) may be more useful to other users, not just me :)

2017-10-26 21:25 UTC, commitay commented
Can you add the Sierra version, `conflicts with formula: 'gcc'` and `pkgutil` to the uninstall please?

2017-10-27 02:48 UTC, miccal commented
<img width="1634" alt="screen shot 2017-10-27 at 10 47 29" src="https://user-images.githubusercontent.com/6127163/32085896-4923d754-bb04-11e7-8390-4fb105dc89d3.png">

> To install any of them, you need to have the Apple Developer Tools installed, as well as "command line developer tools".

So does this need the full Xcode, or are the CLT enough?

2017-10-27 02:51 UTC, miccal commented
<img width="1066" alt="screen shot 2017-10-27 at 10 50 20" src="https://user-images.githubusercontent.com/6127163/32085969-b8696174-bb04-11e7-83c2-b4884190bb18.png">

2017-10-27 12:05 UTC, jeroen commented
I'v been using it on a VM with only CLT and it works fine as far as I can tell.

2017-10-27 12:22 UTC, commitay commented
@vitorgalvao What do you think about adding this to `versions` as `gfortran61`?

2017-10-27 12:29 UTC, jeroen commented
I have conditioned the version on the MacOS version in the [last commit](https://github.com/caskroom/homebrew-cask/pull/40065/commits/c90cd8a6b4d2b7c542b6d4ffa9a29d9bb9722803). Not sure I like it but it seems to work.

2017-10-27 12:31 UTC, vitorgalvao requested changes

2017-10-27 12:31 UTC, vitorgalvao commented on Casks/gfortran.rb
> +  # coudert.name/software was verified as official when first introduced to the cask
This should be located directly above `url`, even if it means repeating it. Each URL is verified independently.

2017-10-27 12:34 UTC, jeroen commented on Casks/gfortran.rb
> +  # coudert.name/software was verified as official when first introduced to the cask
You sure? It seems to pass the audit. Anyway will update.

2017-10-27 12:34 UTC, vitorgalvao commented
> @vitorgalvao What do you think about adding this to `versions` as `gfortran61`?

If there’s a reason a Sierra (and up) user would want that version, yes. Otherwise, one this one should be enough. I’m doubting the usefulness (amount of people that’ll take advantage of) this cask already as it is; it’s harder to justify two casks across two repos.

2017-10-28 07:37 UTC, commitay approved these changes

2017-10-29 04:40 UTC, merged