Add iMouseTrick v1.1
Homebrew/homebrew-cask pull request #40161
Opened 2017-10-30 15:51 UTC by karbassi

iMouseTrick is a program designed to perform only one function: click
many times and as fast as you want. When this program is useful? For
example, when you are playing a game where you have to do a lot of
clicks and you're not fast enough or you don't want to lose your finger
clicking all the time. The limit is up to you.

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not already refused in [closed issues].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

2017-10-30 16:09 UTC, vitorgalvao approved these changes

2017-10-30 20:59 UTC, commitay requested changes

2017-10-30 20:59 UTC, commitay commented on Casks/imousetrick.rb
> +  zap quit:   'com.beecubu.iMouseTrick',
Please change this to `uninstall quit`

2017-10-31 01:54 UTC, merged

2017-10-31 03:10 UTC, karbassi commented
@vitorgalvao Question: Why not delete the `/private/var/folders/` data files?

2017-10-31 12:32 UTC, vitorgalvao commented
@karbassi Because those are temporary files that the system should handle. They’re not meant to be taken care of manually or by software that isn’t the one that created them.