Add Xfer Records OTT 1.21b
Homebrew/homebrew-cask pull request #40174
Opened 2017-10-30 21:41 UTC by danielbayley

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not already refused in [closed issues].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

2017-10-30 21:56 UTC, commitay requested changes

2017-10-30 21:56 UTC, commitay commented on Casks/ott.rb
> +  version '1.21b'
version latest and sha256 no_check

2017-10-31 01:58 UTC, commitay approved these changes

2017-11-02 14:42 UTC, vitorgalvao commented on Casks/xfer-ott.rb
> +  uninstall pkgutil: %r{com.xfer.OTT.*}
This works with wildcards, not regular expressions.

2017-11-02 16:27 UTC, danielbayley commented on Casks/xfer-ott.rb
> +  uninstall pkgutil: %r{com.xfer.OTT.*}
Ah ok, cool. I did think that would be more useful than regex in most cases, but it wasn't clear that was possible from reading [that section of the docs](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/uninstall.md#uninstall-key-pkgutil).

2017-11-02 21:37 UTC, merged