Updated Visual Paradigm CE to version 14.2,20171107
Homebrew/homebrew-cask pull request #41392
Opened 2017-11-28 10:00 UTC by byassine52

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not already refused in [closed issues].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

2017-11-28 10:07 UTC, commitay requested changes

2017-11-28 10:07 UTC, commitay commented on Casks/visual-paradigm-ce.rb
>            checkpoint: '0faa8a7e1b7d77130add1edd6d95a6795fc4a113d2583ef7d65578233309b945'
`checkpoint` needs to be updated as well.

2017-11-28 15:48 UTC, amyspark commented
homebrew/brew#3492 (once merged) will include a fix for the ENOENT issue that appeared in the Travis log. I'll need a Cask maintainer to trigger the build again after it is merged.

2017-11-30 05:22 UTC, commitay approved these changes

2017-11-30 05:22 UTC, merged