Add MollyGuard Latest Cask
Homebrew/homebrew-cask pull request #41405
Opened 2017-11-28 21:04 UTC by migmruiz

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not already refused in [closed issues].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

2017-11-28 21:07 UTC, commitay requested changes

2017-11-28 21:07 UTC, commitay commented on Casks/mollyguard.rb
> +  sha256 '1db2745811987d4dbb94aa586b91199eff3b5d715b684ab93c789231c0ca4f13'
`version :latest` and `sha256 :no_check`

2017-11-28 21:07 UTC, commitay commented on Casks/mollyguard.rb
> +  url 'https://dl.dropboxusercontent.com/s/e2l2dk2qz1u93cb/MollyGuard.dmg?dl=1'
`https://dl.dropboxusercontent.com/s/e2l2dk2qz1u93cb/MollyGuard.dmg`

2017-11-28 23:14 UTC, migmruiz commented
@commitay changes made

2017-11-29 07:31 UTC, commitay approved these changes

2017-11-29 08:20 UTC, merged