nordvpn.rb: use new download url (cdn), bump version to 3.3.10
Homebrew/homebrew-cask pull request #41533
Opened 2017-12-01 15:50 UTC by Iouns

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Tested on high sierra, it works fine. For now, there is no download link for 10.13, so I set it to 10.12.

2017-12-01 21:05 UTC, commitay requested changes
These all have the same `sha256` so the if / elsif block is unnecessary.

2017-12-01 21:23 UTC, vitorgalvao requested changes

2017-12-01 21:23 UTC, vitorgalvao commented on Casks/nordvpn.rb
> +  url "https://downloads.nordcdn.com/apps/macos/10.10/NordVPN-OpenVPN/#{version}/NordVPN.dmg"
You’re going to bump into [this](https://github.com/caskroom/homebrew-cask/blob/1002d41242216ce7c71597765dc0a86cabd1fcf7/doc/cask_language_reference/stanzas/url.md#when-url-and-homepage-hostnames-differ-add-a-comment).

2017-12-02 22:46 UTC, commitay commented
`3.3.10` is the current download from the homepage but it isn't listed on the appcast.

2017-12-02 22:46 UTC, commitay approved these changes

2017-12-05 13:21 UTC, merged