Update polyphone to 1.9
Homebrew/homebrew-cask pull request #41646
Opened 2017-12-04 20:58 UTC by gtmgianni

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

2017-12-05 06:01 UTC, commitay commented
Download URL 404s.

The download from the homepage is:

> https://polyphone-soundfonts.com/en/files/file/559-polyphone-1-9-dmg/latest/download?0fdc953d1ce17e5d6f055f0d6ef83577=1&return=aHR0cHMlM0ElMkYlMkZwb2x5cGhvbmUtc291bmRmb250cy5jb20lMkZlbiUyRmZpbGVzJTJGNi1wb2x5cGhvbmUlMkY0MTMtcG9seXBob25lLTEtOQ==

`referer`, etc don't work. Might have to remove this.

2017-12-06 12:54 UTC, claui requested changes

2017-12-06 12:54 UTC, claui commented on Casks/polyphone.rb
> +  url "https://polyphone-soundfonts.com/judownload/0_1512442550_rk9xVE/polyphone-#{version}.dmg"
Use this URL, which is more stable:

```
url "https://polyphone-soundfonts.com/en/download/file/559-polyphone-#{version.sub('.', '-')}-dmg/latest/download"
```

2017-12-06 13:37 UTC, commitay commented on Casks/polyphone.rb
> +  url "https://polyphone-soundfonts.com/judownload/0_1512442550_rk9xVE/polyphone-#{version}.dmg"
@claui Does that URL work reliably for you?
```
curl: (16) Error in the HTTP2 framing layer
audit for polyphone: failed
 - download not possible: Download failed on Cask 'polyphone' with message: Download failed: https://polyphone-soundfonts.com/en/download/file/559-polyphone-1-9-dmg/latest/download
```

2017-12-06 13:41 UTC, claui commented on Casks/polyphone.rb
> +  url "https://polyphone-soundfonts.com/judownload/0_1512442550_rk9xVE/polyphone-#{version}.dmg"
@commitay I double-checked one more time; both `install` and `audit --download` work for me.

![During installation](https://user-images.githubusercontent.com/1239874/33664298-61626c96-da93-11e7-8729-a5f51295bffd.png)

![After installation/audit](https://user-images.githubusercontent.com/1239874/33664303-66ba687e-da93-11e7-8bed-ca3c7fb5759d.png)

2017-12-06 13:45 UTC, commitay commented on Casks/polyphone.rb
> +  url "https://polyphone-soundfonts.com/judownload/0_1512442550_rk9xVE/polyphone-#{version}.dmg"
Thanks!

2017-12-06 13:51 UTC, claui commented on Casks/polyphone.rb
> +  url "https://polyphone-soundfonts.com/judownload/0_1512442550_rk9xVE/polyphone-#{version}.dmg"
@commitay Are you sure the `polyphone.app` artifact is supposed to be in lower-case?

2017-12-06 13:52 UTC, claui commented on Casks/polyphone.rb
> +  app 'polyphone.app'
@commitay Are you sure the `polyphone.app` artifact is supposed to be in lower-case?

2017-12-06 14:00 UTC, claui commented on Casks/polyphone.rb
> +  app 'polyphone.app'
Mind = blown :woman_shrugging:

Fair enough.

2017-12-06 14:00 UTC, claui approved these changes

2017-12-07 02:52 UTC, merged