Add ColdTurkey.app v3.1
Homebrew/homebrew-cask pull request #41827
Opened 2017-12-11 11:43 UTC by jinntrance

After making all changes to the cask:

- [ ] `brew cask audit --download {{cask_file}}` is error-free.
- [ ] `brew cask style --fix {{cask_file}}` reports no offenses.
- [ ] The commit message includes the cask’s name and version.

Additionally, if **adding a new cask**:

- [ ] Named the cask according to the [token reference].
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked there are no [open pull requests] for the same cask.
- [ ] Checked the cask was not already refused in [closed issues].
- [ ] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

2017-12-11 11:59 UTC, commitay commented on Casks/cold-turkey.rb
> +  pkg 'Cold_Turkey_Mac_Installer.pkg'
Add [`uninstall pkgutil`](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/uninstall.md#uninstall-key-pkgutil)

Example:
https://github.com/caskroom/homebrew-cask/blob/9c23c72d088ee016720d0409f686f229ad19b90f/Casks/vfuse.rb#L11-L13

2017-12-11 11:59 UTC, commitay requested changes

2017-12-11 11:59 UTC, commitay commented on Casks/cold-turkey.rb
> +  sha256 :no_check
Please add the `sha256`

2017-12-11 12:13 UTC, commitay requested changes
Please rename the Cask to `cold-turkey-blocker`

[Simplified Names of pkg-based Installers](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md#simplified-names-of-pkg-based-installers)

2017-12-12 00:39 UTC, jinntrance commented
@commitay Thank you for your comments.  I've changed what you requested.

2017-12-12 02:21 UTC, commitay approved these changes

2017-12-12 02:48 UTC, merged

2017-12-12 02:48 UTC, commitay commented
Thanks for the PR!