Update netron to 1.1.5
Homebrew/homebrew-cask pull request #42172
Opened 2017-12-21 11:39 UTC by lutzroeder

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

2017-12-21 14:56 UTC, vitorgalvao requested changes

2017-12-21 14:56 UTC, vitorgalvao commented on Casks/netron.rb
> +          checkpoint: '4b2477fb43c10031f0772cf347bf94797e9bbcd14047d75224e9f4534480885a'
`2a7d1adfdc69303749ab1de19341e1a2532f22beb1c386aed2a74db4a66d5e07`

2017-12-21 19:50 UTC, commitay commented
Same issue with https://github.com/caskroom/homebrew-cask/pull/42129

@lutzroeder You [deploy script](https://github.com/lutzroeder/Netron/blob/master/tools/deploy) seems to run `cask-repair` before the GitHub releases page is updated, hence the incorrect `checkpoint` on the last two PRs. Deleting the fork means we can't edit the PR.

2017-12-22 00:06 UTC, closed without merging

2017-12-22 00:33 UTC, commitay commented
https://github.com/caskroom/homebrew-cask/pull/42197