Add Homespun Instant Access v2.9.3
Homebrew/homebrew-cask pull request #42319
Opened 2017-12-27 19:00 UTC by laenzlinger

Homespun is a music instruction site.
Homespun Instant Access is the application to play Homespun lessons.

I am not sure if I implemented this cask correctly. The Application requires an installer script to be run. I was able to start this script, but It still requires manual input (clicks) from the user. (First a confirmation and then a screen to accept the license agreement)

![screen shot 2017-12-27 at 19 55 52](https://user-images.githubusercontent.com/6319634/34390487-50eb761a-eb40-11e7-805f-8e13330109fe.png)

![screen shot 2017-12-27 at 19 56 15](https://user-images.githubusercontent.com/6319634/34390490-57016906-eb40-11e7-9e22-62096f5cc492.png)

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not already refused in [closed issues].
- [x] Checked the cask is submitted to [the correct repo].

2017-12-27 19:46 UTC, vitorgalvao requested changes

2017-12-27 19:46 UTC, vitorgalvao commented on Casks/homespun-instant-access.rb
> +            delete: '/Applications/Homespun Instant Access.app'
Are you sure adding this app is the only thing the installer does? That is highly unlikely.

2017-12-27 19:46 UTC, vitorgalvao commented on Casks/homespun-instant-access.rb
> +  uninstall quit:   'com..mm_launcher',
Is this correct (`..`)?

2017-12-27 19:46 UTC, vitorgalvao commented on Casks/homespun-instant-access.rb
> +                      executable: "#{staged_path}/Homespun Instant Access Installer.app/Contents/MacOS/Homespun Instant Access Installer",
This isn’t a script, it’s simply the binary inside the app bundle.

This need to be [`installer manual:`](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/installer.md#installer-manual) on the `.app` instead.

2017-12-27 19:52 UTC, laenzlinger commented on Casks/homespun-instant-access.rb
> +                      executable: "#{staged_path}/Homespun Instant Access Installer.app/Contents/MacOS/Homespun Instant Access Installer",
Ok, I will change that. 

I have tried this as well. But I was not sure, how such situation is usually handled. I thought it was beneficial to the user would not have to locate the installer manually and click on it, instead, I thought it would be easier that the installer ist automatically started.

But I am new to this project and I have not seen many different casks how the work. 

If I get you correctly, a manual installation is the best for such situation, therefore I will change it.

2017-12-27 19:57 UTC, laenzlinger commented on Casks/homespun-instant-access.rb
> +  uninstall quit:   'com..mm_launcher',
Unfortunately this seems to be the id of this bundle. See the following output while the application is running:

```
/u/l/H/L/T/c/homebrew-cask ❯❯❯ developer/bin/list_running_app_ids                                                                   bundle_id	app_name
--------------------------------------
.... more stuff
com..mm_launcher	Homespun Instant Access
.... more stuff
```

2017-12-27 19:59 UTC, vitorgalvao commented on Casks/homespun-instant-access.rb
> +                      executable: "#{staged_path}/Homespun Instant Access Installer.app/Contents/MacOS/Homespun Instant Access Installer",
> I thought it was beneficial to the user would not have to locate the installer manually and click on it, instead, I thought it would be easier that the installer ist automatically started.

But that also means the installation blocks scripts (much like it did Travis), which is bad. This is standard procedure for us, and users already expect it.

We do have plans for it to be different in the future — see https://github.com/caskroom/homebrew-cask/issues/24377.

2017-12-27 19:59 UTC, vitorgalvao commented on Casks/homespun-instant-access.rb
> +  uninstall quit:   'com..mm_launcher',
It’s fine if it is, I was just checking if it wasn’t a copying mistake.

2017-12-27 20:03 UTC, laenzlinger commented on Casks/homespun-instant-access.rb
> +            delete: '/Applications/Homespun Instant Access.app'
I agree with you, that probably it does something very strange (since it requires password during the installation. 

How can I find out what the application is installing?

I am using app cleaner to remove applications: This reports the following:
![screen shot 2017-12-27 at 21 01 59](https://user-images.githubusercontent.com/6319634/34391938-4d1a1812-eb49-11e7-8c99-4cb398c192c9.png)

What out of this data should be removed? Something more?

2017-12-27 20:04 UTC, laenzlinger commented on Casks/homespun-instant-access.rb
> +                      executable: "#{staged_path}/Homespun Instant Access Installer.app/Contents/MacOS/Homespun Instant Access Installer",
Perfect, I will update this PR.

2017-12-27 20:12 UTC, vitorgalvao commented on Casks/homespun-instant-access.rb
> +            delete: '/Applications/Homespun Instant Access.app'
> How can I find out what the application is installing?

Ideally, the developer will have that information somewhere, like instructions on how to completely uninstall the app.

But you can also take a look at our other `developer/bin` scripts, namely `list_installed_launchjob_ids`, `list_loaded_kext_ids`. They might turn up something more.

2017-12-27 20:19 UTC, laenzlinger commented on Casks/homespun-instant-access.rb
> +            delete: '/Applications/Homespun Instant Access.app'
I have checked both `list_loaded_kext_ids` and `list_installed_launchjob_ids `. Both did not report anything related to this application.

Unfortunately I am not the developer of the Homespun application. (Just a user)

2017-12-27 20:24 UTC, vitorgalvao commented on Casks/homespun-instant-access.rb
> +            delete: '/Applications/Homespun Instant Access.app'
>  I am not the developer of the Homespun application.

I know, but the information may be posted somewhere on the website or there may be a forum where you can ask.

2017-12-27 20:27 UTC, laenzlinger commented on Casks/homespun-instant-access.rb
> +            delete: '/Applications/Homespun Instant Access.app'
Agreed, I was searching a bit on the webpage. But definitely a good Idea is the forum (although it's a bit music related, but maybe somebody is willing to help)

2017-12-27 20:51 UTC, laenzlinger commented on Casks/homespun-instant-access.rb
> +            delete: '/Applications/Homespun Instant Access.app'
Currently checking with the support.

2017-12-29 10:38 UTC, commitay approved these changes

2017-12-29 11:35 UTC, vitorgalvao commented on Casks/homespun-instant-access.rb
> +            delete: '/Applications/Homespun Instant Access.app'
Thank you for checking!

2017-12-29 11:35 UTC, merged