Update eagle to 8.5.1
Homebrew/homebrew-cask pull request #42431
Opened 2018-01-01 03:57 UTC by FlechaMaker

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, if **updating a cask**:

- [ ] [If the `sha256` changed but the `version` didn’t](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256),
      provide public confirmation by the developer: {{link}}

2018-01-01 04:15 UTC, commitay requested changes

2018-01-01 04:15 UTC, commitay commented on Casks/eagle.rb
> +  url "https://eagle-updates.circuits.io/downloads/#{version.split('.').join('_')}/Autodesk_EAGLE_#{version}_English_Mac_64bit.pkg"
Use `#{version.dots_to_underscores}`

This isn't the current download link on the homepage, we will have to wait until it is updated.

2018-01-01 04:17 UTC, commitay commented on Casks/eagle.rb
> +  appcast 'http://eagle.autodesk.com/eagle/release-notes',
Please remove the `appcast` and `checkpoint`.

2018-01-03 13:15 UTC, FlechaMaker commented on Casks/eagle.rb
> +  url "https://eagle-updates.circuits.io/downloads/#{version.split('.').join('_')}/Autodesk_EAGLE_#{version}_English_Mac_64bit.pkg"
Although the download link on autodesk.com haven't updated, update dialog of the EAGLE.app shows link to latest version on eagle-updates.circuits.io. Also, the link "autodesk.com/eagle" on the dialog is linked to https://eagle-updates.circuits.io/downloads/latest.html now.

<img width="800" alt="screen shot 2018-01-03 at 21 43 00" src="https://user-images.githubusercontent.com/6488324/34521725-a121419a-f0d2-11e7-8bb9-3a455264fbf9.png">

2018-01-10 21:51 UTC, commitay commented
Closing in favour of https://github.com/caskroom/homebrew-cask/pull/42688

2018-01-10 21:51 UTC, closed without merging