Add ResidualVM v0.3.0
Homebrew/homebrew-cask pull request #42536
Opened 2018-01-05 14:43 UTC by epistrephein

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not already refused in [closed issues].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

2018-01-05 15:48 UTC, vitorgalvao requested changes
Edit: made in error.

2018-01-05 15:49 UTC, vitorgalvao approved these changes

2018-01-06 02:33 UTC, commitay commented on Casks/residualvm.rb
> +  depends_on macos: '>= :high_sierra'
Why High Sierra?

2018-01-06 02:35 UTC, commitay commented
```
possible duplicate, cask token conflicts with Homebrew core formula: https://github.com/Homebrew/homebrew-core/blob/master/Formula/residualvm.rb
```

2018-01-06 03:31 UTC, vitorgalvao commented on Casks/residualvm.rb
> +  depends_on macos: '>= :high_sierra'
> The intel 64 dmg is for 10.7+

It says that on the website, but when I downloaded (to check for an appcast — it exists, but goes somewhere the server does not allow) it showed the icon with the prohibition icon on top, so this might be right (I’m on Sierra).

2018-01-06 03:44 UTC, commitay commented on Casks/residualvm.rb
> +  depends_on macos: '>= :high_sierra'
Doesn't seem to work on High Sierra, same message in VM and host.

![residualvm](https://user-images.githubusercontent.com/26216252/34636138-e291672a-f2e6-11e7-98c0-5dda3eb4022e.png)

2018-01-06 07:45 UTC, epistrephein commented
Definitely looks like the OSX build is broken.  
I wasn't sure about the 10.7+ system requirement on the website since on my Sierra didn't work, but I've tested on two High Sierra and I can confirm it doesn't work.
I'll open an issue on their repo and report back here it that's ok.

About duplication, I think `residualvm` would work just like `scummvm`: build from source (brew) or install the app (cask).

2018-01-06 07:51 UTC, commitay commented
> About duplication ...

The duplication is okay as they provide different things, I just added the comment as a note to show that it was known when it was merged. 

> I'll open an issue on their repo and report back here it that's ok.

Great, thanks!

2018-02-13 03:32 UTC, commitay commented
Closing for now as it's been over a month and upstream haven't responded.

Feel feel to open a new PR when upstream has the app is working.

2018-02-13 03:32 UTC, closed without merging