Add SimSim.app 1.3.3
Homebrew/homebrew-cask pull request #42557
Opened 2018-01-06 23:50 UTC by rtdaly

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not already refused in [closed issues].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

2018-01-06 23:53 UTC, commitay requested changes

2018-01-06 23:53 UTC, commitay commented on Casks/simsim.rb
> +  uninstall login_item: 'SimSim',
Does this need uninstall `quit:` or `signal:`?

2018-01-06 23:53 UTC, commitay commented on Casks/simsim.rb
> +               '~/Library/Preferences/com.dsmelov.SimSim.plist',
Make this a single line with `zap trash`.

2018-01-07 00:08 UTC, rtdaly commented on Casks/simsim.rb
> +  uninstall login_item: 'SimSim',
You're right I forgot the `quit:`

2018-01-07 00:26 UTC, rtdaly commented
@commitay Fixed!

2018-01-07 00:45 UTC, commitay approved these changes

2018-01-07 00:54 UTC, merged