Add Storyboarder.app v1.3.0
Homebrew/homebrew-cask pull request #42562
Opened 2018-01-07 02:18 UTC by ramsey

There is a [rejected pull request for the Storyboard Fountain app](https://github.com/caskroom/homebrew-cask/pull/36774) that is no longer maintained, but the author of that PR did not submit a new PR for the maintained Storyboarder app, which replaces Storyboard Fountain. This PR introduces a cask for the Storyboarder app, which is actively maintained.

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not already refused in [closed issues].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

2018-01-07 02:37 UTC, commitay requested changes

2018-01-07 02:37 UTC, commitay commented on Casks/storyboarder.rb
> +  name 'Storyboarder'
Remove this line

2018-01-07 02:37 UTC, commitay commented on Casks/storyboarder.rb
> +                '~/Library/Saved Application State/com.wonderunit.storyboarder.savedState',
Move this into ` zap trash`

2018-01-07 02:48 UTC, ramsey commented
Thanks for the review. I've fixed up my changes back into the same commit.

2018-01-07 02:51 UTC, commitay commented
> I've fixed up my changes back into the same commit.

Just for future reference, we prefer that contributors don't fixup/squash commits, it makes it easier to see what changes have been made.

2018-01-07 02:53 UTC, commitay approved these changes

2018-01-07 20:48 UTC, vitorgalvao commented
This looks walled, to me.

2018-01-07 20:52 UTC, commitay commented
Didn't notice that the download requires an email. They link to their GitHub next to another download link at the bottom of the homepage.

2018-01-07 20:58 UTC, ramsey commented
Their downloads are available on GitHub under tags/releases without needing to provide an email address. They don’t bundle an OSS license in the repo, but their website outlines their open philosphy and states that their terms are according to the MIT license (ish). https://wonderunit.com/thoughts-on-free-and-open-source/

2018-01-08 02:49 UTC, adidalal commented
Don't think it needs the caveat, personally.

2018-01-08 02:54 UTC, commitay commented
Do you mean set the homepage to the Github repo and remove the verified comment?

2018-01-09 18:24 UTC, vitorgalvao commented
> Their downloads are available on GitHub under tags/releases without needing to provide an email address.

Not the point. `url` origins need to be auditable, which means users need to be able to verify them from the homepage with low effort. Having to provide an email is high effort. If there were no links to github on the homepage (found it; thank you @commitay) then they also couldn’t trust that repo to be official.

> Don't think it needs the caveat, personally.

What do you mean? We always require the comment, and it’s not part of the style check, even. If the comment weren’t there, Travis would fail.

2018-01-09 18:24 UTC, merged