Update noejectdelay to 7.1.4
Homebrew/homebrew-cask pull request #43477
Opened 2018-02-01 20:25 UTC by brianmorton

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

2018-02-01 20:25 UTC, brianmorton commented
Website seems outdated as it redirects to https://pqrs.org/osx/karabiner/ now... version was found by URL sniffing.

Maybe this cask should just be removed?

2018-02-01 21:48 UTC, commitay commented
https://pqrs.org/osx/karabiner/noejectdelay.html only has `7.1.0`

Only works on el cap and older.

2018-02-01 21:56 UTC, brianmorton commented
@commitay ahh ok... The URL in the cask is wrong then - it has a `.en` after the `.html` which is causing the redirect.

2018-02-02 02:11 UTC, adidalal requested changes

2018-02-02 02:11 UTC, adidalal commented on Casks/noejectdelay.rb
>    homepage 'https://pqrs.org/osx/karabiner/noejectdelay.html.en'
`homepage 'https://pqrs.org/osx/karabiner/noejectdelay.html'`

2018-02-02 02:11 UTC, adidalal commented on Casks/noejectdelay.rb
Let's add a `depends_on macos: '<= :el_capitan'` and a `discontinued` caveat.

Example - https://github.com/caskroom/homebrew-cask/blob/f601dceb8d8a44d1aff6104daae3a2fcb0d6f32f/Casks/fraise.rb

2018-02-02 20:32 UTC, vitorgalvao commented
Since we officially only support the latest macOS and the version before and this is already discontinued, might as well remove it.

https://github.com/caskroom/homebrew-cask/pull/43580

2018-02-02 20:32 UTC, closed without merging