Add StarLeaf.app v2.11.32
Homebrew/homebrew-cask pull request #43945
Opened 2018-02-13 15:30 UTC by witsch

After making all changes to the cask:

- [ ] `brew cask audit --download {{cask_file}}` is error-free.
- [ ] `brew cask style --fix {{cask_file}}` reports no offenses.
- [ ] The commit message includes the cask’s name and version.

Additionally, if **adding a new cask**:

- [ ] Named the cask according to the [token reference].
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked there are no [open pull requests] for the same cask.
- [ ] Checked the cask was not already refused in [closed issues].
- [ ] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

2018-02-13 15:32 UTC, CryoTheRenegade requested changes
Add Uninstall pkgutil: stanza

2018-02-13 15:37 UTC, witsch commented
Thank you, will do... 🙂

2018-02-13 21:08 UTC, victorpopkov approved these changes

2018-02-14 02:03 UTC, merged

2018-02-14 07:47 UTC, witsch commented on Casks/starleaf.rb
> +            quit:       'Starleaf.breeze2'
Ah, thanks!  I was wondering about the `Starleaf.breeze2` (in `~/Library/Preferences/Starleaf.breeze2.plist`).  Is there any documentation/readme about the different keys to `uninstall`?

2018-02-14 08:13 UTC, commitay commented on Casks/starleaf.rb
> +            quit:       'Starleaf.breeze2'
https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/uninstall.md