Add OpenSC v.0.17.0
Homebrew/homebrew-cask pull request #44048
Opened 2018-02-15 20:55 UTC by mastahyeti

The [`opensc` formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/opensc.rb) seems to just download the source and run `./bootstrap && ./configure ${some_args} && make install`. The actual installer distributed by OpenSC does quite a bit more though (see [`build-package.in`](https://github.com/OpenSC/OpenSC/blob/master/MacOSX/build-package.in)).

More specifically, when installing OpenSC with hombrew `OpenSC.tokend` is not installed. This is a major component of OpenSC and is what allows it to interact with the macOS keychain.

I [asked in the forums](https://discourse.brew.sh/t/opensc-formula-is-missing-the-opensc-tokend-component/1683) if we should update the homebrew formula or add a new cask formula. @MikeMcQuaid said that a new cask formula would be better, so here we are.

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not already refused in [closed issues].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

2018-02-15 21:13 UTC, commitay requested changes

2018-02-15 21:13 UTC, commitay commented on Casks/opensc.rb
> +  appcast 'https://github.com/github/SoftU2F/releases.atom',
`OpenSC/OpenSC`

The checkpoint will need to be updated.

2018-02-15 21:13 UTC, commitay commented on Casks/opensc.rb
> +  homepage 'https://github.com/OpenSC/OpenSC'
`https://github.com/OpenSC/OpenSC/wiki`

2018-02-15 21:14 UTC, mastahyeti commented on Casks/opensc.rb
> +  appcast 'https://github.com/github/SoftU2F/releases.atom',
Whoops. I copied this from another formula.

2018-02-15 21:47 UTC, commitay commented
cc @ilovezfs

2018-02-15 21:49 UTC, commitay approved these changes

2018-02-16 05:20 UTC, ilovezfs commented
lgtm

2018-02-16 05:21 UTC, ilovezfs approved these changes

2018-02-16 05:47 UTC, commitay commented
@ilovezfs Do you want to keep the formula?

2018-02-16 05:51 UTC, merged

2018-02-16 05:51 UTC, ilovezfs commented
For now I think keeping it is fine. There were 622 installs in the last 90 days and this is the first we're hearing about any interest in the `OpenSC.tokend` bundle, so I'm quite dubious it's as important as suggested above. Also, MacPorts doesn't install that bit either: https://github.com/macports/macports-ports/blob/master/security/opensc/Portfile