Tripmode: update zap stanza
Homebrew/homebrew-cask pull request #45022
Opened 2018-03-20 22:48 UTC by ondrejfuhrer

I have updated the zap stanza for all the files that I found left after uninstalling.

After making all changes to the cask:

- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name

2018-03-20 22:49 UTC, commitay requested changes

2018-03-20 22:49 UTC, commitay commented on Casks/tripmode.rb
> +               '/Library/LaunchDaemons/ch.tripmode.TripMode.HelperTool.plist',
`uninstall launchctl` for the two `LaunchDaemons`

2018-03-20 22:49 UTC, commitay commented on Casks/tripmode.rb
> +               '/Library/PrivilegedHelperTools/ch.tripmode.TripMode.HelperTool',
`uninstall delete` for this

2018-03-20 23:08 UTC, commitay commented on Casks/tripmode.rb
> +                         '/Library/LaunchDaemons/ch.tripmode.TripMode.HelperTool.plist',
Don't use the full path to the plist.

See [here](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/uninstall.md#uninstall-key-launchctl) for how to find the launchjob id.

2018-03-21 09:45 UTC, ondrejfuhrer commented
I also added `uninstall signal:` stanza. I tested the `quit` for the app, but didn't work.

2018-03-21 10:00 UTC, commitay approved these changes

2018-03-21 10:00 UTC, merged