Add Solstice Client :latest
Homebrew/homebrew-cask pull request #46215
Opened 2018-04-22 22:55 UTC by iandrewt

Adds Solstice client, an app used for mirroring the display to a TV
in education/enterprise

2018-04-23 14:48 UTC, vitorgalvao requested changes
We need further documentation on this app’s un/install process. As it is, we cannot accept this cask.

2018-04-23 14:48 UTC, vitorgalvao commented on Casks/solstice.rb
> +  uninstall delete: '~/Desktop/Solstice Client.app'
It’s unlikely moving this app is the only thing the installer says. Furthermore, it’s unlikely users will keep the installed app in their Desktop.

2018-04-24 05:41 UTC, commitay commented on Casks/solstice.rb
> +  uninstall delete: '~/Desktop/Solstice Client.app'
> it’s unlikely users will keep the installed app in their Desktop

There isn't much we can do about this. It runs a GUI installer that doesn't seem to accept any flags so we can't move it ourselves.

2018-04-24 10:49 UTC, vitorgalvao commented on Casks/solstice.rb
> +  uninstall delete: '~/Desktop/Solstice Client.app'
> There isn't much we can do about this.

We can `postflight` to move it to `appdir`.

2018-04-24 10:52 UTC, commitay commented on Casks/solstice.rb
> +  uninstall delete: '~/Desktop/Solstice Client.app'
It's a GUI installer?

2018-04-24 15:06 UTC, vitorgalvao commented on Casks/solstice.rb
> +  uninstall delete: '~/Desktop/Solstice Client.app'
Ah, right. Still, deleting it from the Desktop is bound to be useless. This would be another good candidate for https://github.com/caskroom/homebrew-cask/issues/8211.

2018-04-24 22:38 UTC, commitay commented on Casks/solstice.rb
> +  uninstall delete: '~/Desktop/Solstice Client.app'
Should we refuse it then?

2018-04-25 12:37 UTC, vitorgalvao commented on Casks/solstice.rb
> +  uninstall delete: '~/Desktop/Solstice Client.app'
Yes, depending on what @iandrewt can gather, if anything. For all we know this might setup an uninstall script in a fixed location that would acceptably deal with the matter.

2018-04-25 12:48 UTC, iandrewt commented on Casks/solstice.rb
> +  uninstall delete: '~/Desktop/Solstice Client.app'
Hi, sorry I've been inactive since submitting this. Did some testing, moving the app from the desktop to Applications doesn't result in it being moved back when opening it again. Is this the kind of info you're after?

2018-04-25 12:52 UTC, vitorgalvao commented on Casks/solstice.rb
> +  uninstall delete: '~/Desktop/Solstice Client.app'
No, the issue is that since this has an installer (as opposed to just a .app bundle) it likely does some modifications to your system (like installing `launchd` jobs). For this to be accepted, we need to have an `uninstall` that undos those changes.

2018-04-25 13:01 UTC, iandrewt commented on Casks/solstice.rb
> +  uninstall delete: '~/Desktop/Solstice Client.app'
Ah, did some digging and it looks like the only other file system thing it does is create a couple files in `~/Library/Application Support` (the file `solsticeMRU_V2.dat` and the folder `Solstice`). Nothing at all in `/Library`, and no `launchd` jobs

2018-05-16 22:30 UTC, vitorgalvao commented
Going to refuse since we can’t build a proper uninstall. Still, thank you for the contribution and the fast responses.

2018-05-16 22:30 UTC, closed without merging