Add AirUnlock 0.4 (OSX/Android BT unlock pair)
Homebrew/homebrew-cask pull request #46447
Opened 2018-04-27 19:27 UTC by BenjaminHCCarr

Add AirUnlock cask, which creates a status bar icon that listens for BT LE hashes from an Android client to unlock the Mac using the biometrics on the Android phone:
AirUnlock for Android:
    https://github.com/pinetum/AirUnlock-for-Android
    https://f-droid.org/packages/tw.qtlin.mac.airunlocker/

After making all changes to the cask:

- [X] `brew cask audit --download {{cask_file}}` is error-free.
- [X] `brew cask style --fix {{cask_file}}` reports no offenses.
- [X] The commit message includes the cask’s name and version.

Additionally, if **adding a new cask**:

- [X] Named the cask according to the [token reference].
- [X] `brew cask install {{cask_file}}` worked successfully.
- [X] `brew cask uninstall {{cask_file}}` worked successfully.
- [X] Checked there are no [open pull requests] for the same cask.
- [X] Checked the cask was not already refused in [closed issues].
- [X] Checked the cask is submitted to [the correct repo].

2018-04-27 21:31 UTC, commitay requested changes

2018-04-27 21:31 UTC, commitay commented on Casks/airunlock.rb
> +  # homepage and URL verified at time of pull request
Verified comment needs to look like this:
https://github.com/caskroom/homebrew-cask/blob/0f07d216ece59954816d0f3c13baaf56a016025a/Casks/skype.rb#L5

2018-04-27 21:31 UTC, commitay commented on Casks/airunlock.rb
> +  caveats <<~EOS
Remove the caveat

2018-04-28 02:48 UTC, BenjaminHCCarr commented
Two commits as I think the caveat is useful, otherwise it's a useless `cask`, but two options for you, commit whichever you feel is more appropriate.

2018-04-28 12:42 UTC, commitay approved these changes

2018-05-01 09:20 UTC, merged