Update IDA free 7.0 SHA
Homebrew/homebrew-cask pull request #46749
Opened 2018-05-05 20:17 UTC by fletchto99

The sha provided is actually the SHA-1 and not SHA256 thus the checksum check fails. I've updated it to use the SHA256

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

2018-05-06 00:01 UTC, vitorgalvao commented
> The sha provided is actually the SHA-1 and not SHA256

That is incorrect. SHA-1 is shorter (40 characters long) and if the shasum were wrong at the moment of submission, Travis would have caught it.

This represents a file changed in place. Seeing as there isn’t a signed app we can check, the VirusTotal check does us no good. You need to follow the other procedure and contact the developer in a way they publicly confirm this shasum is correct.

2018-05-06 00:01 UTC, vitorgalvao requested changes
Awaiting shasum verification

2018-05-06 00:06 UTC, fletchto99 commented
Ahh true it makes sense that the SHA1 wouldn't have been used in the first place 😓. The file was changed in place hence the change in the shasum. 

The developer publishes the SHA1: https://www.hex-rays.com/products/ida/support/download_freeware.shtml

Is that enough to verify that the file is correct?

2018-06-02 21:02 UTC, fletchto99 commented
Sorry for the delayed response! I got busy and totally forgot to message the developer. Anyhow I've got confirmation now.

![screen shot 2018-06-02 at 4 56 45 pm](https://user-images.githubusercontent.com/718681/40880823-fd294716-6685-11e8-9391-4a966ba6705d.png)

![screen shot 2018-06-02 at 4 57 42 pm](https://user-images.githubusercontent.com/718681/40880850-b2712fda-6686-11e8-9891-a947b20c47d5.png)

2018-06-04 07:53 UTC, fletchto99 commented
Got an update as per why the SHA changed:

![capture](https://user-images.githubusercontent.com/718681/40905085-e09ce2e4-67aa-11e8-8721-67abb4257aad.PNG)

2018-06-17 03:16 UTC, fletchto99 commented
@vitorgalvao Is there anything else I must do before this PR is good to go?

2018-06-18 17:45 UTC, vitorgalvao commented
Thank you, @fletchto99. I see an inconsistency between the published version and their shasum on the page, so give me a bit to confirm that.

2018-06-18 17:46 UTC, merged