Remove winds
Homebrew/homebrew-cask pull request #46862
Opened 2018-05-08 19:29 UTC by gtmgianni

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

2018-05-08 20:38 UTC, vitorgalvao requested changes

2018-05-08 20:38 UTC, vitorgalvao commented on Casks/winds.rb
> +  url "https://s3.amazonaws.com/winds-#{version.major_minor}-releases/releases/Winds-#{version}-mac.zip"
We can’t use this link, because it’s walled.

2018-05-08 21:01 UTC, gtmgianni commented on Casks/winds.rb
> +  url "https://s3.amazonaws.com/winds-#{version.major_minor}-releases/releases/Winds-#{version}-mac.zip"
Does it count as walled if you don't need to register "fully" (you just need to enter an email address, and the download begins)? If so, we should probably just remove this cask.

2018-05-08 21:10 UTC, vitorgalvao commented on Casks/winds.rb
> +  url "https://s3.amazonaws.com/winds-#{version.major_minor}-releases/releases/Winds-#{version}-mac.zip"
> Does it count as walled if you don't need to register "fully"

Yes. Even if it works with a fake email, it still counts as walled.

The point is to make every cask easily auditable by anyone, without having to resort to “tricks”.

2018-05-09 09:35 UTC, commitay commented
Thanks!

2018-05-09 09:35 UTC, merged

2018-06-20 14:02 UTC, commitay commented
Re-added in https://github.com/Homebrew/homebrew-cask/pull/48699 with less wall.