Update deco
Homebrew/homebrew-cask pull request #46987
Opened 2018-05-12 01:58 UTC by 0xdevalias

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

2018-05-12 19:36 UTC, victorpopkov approved these changes

2018-05-12 20:27 UTC, vitorgalvao requested changes
Since `sha256` was updated but `version` stayed the same, this change needs to be verified. Please [follow the instructions to do so](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256).

2018-05-12 23:33 UTC, commitay commented
@vitorgalvao The `sha256` change is expected as we are switching from the zip to the pkg.

2018-05-13 00:15 UTC, vitorgalvao approved these changes

2018-05-13 04:29 UTC, merged

2018-05-13 04:29 UTC, commitay commented
Thanks @0xdevalias!