Update firestr to 0.11
Homebrew/homebrew-cask pull request #47299
Opened 2018-05-16 09:00 UTC by core-code

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

2018-05-16 22:07 UTC, vitorgalvao requested changes
Since `sha256` was updated but `version` stayed the same, this change needs to be verified. Please [follow the instructions to do so](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256).

2018-05-17 18:46 UTC, core-code commented
since the file is not code-signed i've asked the developer to confirm its authenticity

2018-06-22 17:33 UTC, core-code commented
i guess we can give up waiting for confirmation from the developer

2018-06-22 18:34 UTC, vitorgalvao commented
Closing for now, with a nod to https://github.com/Homebrew/homebrew-cask/issues/48862.

2018-06-22 18:34 UTC, closed without merging