Update 1password to 7.0
Homebrew/homebrew-cask pull request #47471
Opened 2018-05-22 16:28 UTC by core-code

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

2018-05-22 16:58 UTC, vitorgalvao commented on Casks/1password.rb
> +  elsif MacOS.version <= :sierra
This implies this version only works on Sierra and below, which I don’t think is the case.

2018-05-22 17:06 UTC, cpmsmith commented on Casks/1password.rb
> +  elsif MacOS.version <= :sierra
According to AgileBits, [v7 supports 10.12 onward](https://support.1password.com/upgrade-mac/#get-help), so this should say El Capitan.

2018-05-22 17:18 UTC, brianmorton commented
https://github.com/caskroom/homebrew-cask/pull/47470

2018-05-22 17:46 UTC, core-code commented on Casks/1password.rb
> +  elsif MacOS.version <= :sierra
> This implies this version only works on Sierra and below, which I don’t think is the case.
 
i think you mis-read the diff. version 7 of 1password only runs on 10.12+ so older systems still have to install the old version 6

> This needs to be part of only the conditional of version 7.

fixed thanks

2018-05-22 21:00 UTC, commitay requested changes
Version 7 is a paid upgrade, I think this Cask should contain version 7 only and 6 should be added to versions.

2018-05-22 21:02 UTC, commitay commented
Also, there is a zip for version 7.

https://cache.agilebits.com/dist/1P/mac7/1Password-7.0.zip

2018-05-22 21:55 UTC, core-code commented
the zip file wasn't there when i checked earlier today. 

i can change the cask to contain only version 7 if you want.

2018-05-22 22:10 UTC, commitay approved these changes

2018-05-22 22:11 UTC, commitay commented on Casks/1password.rb
> +  # 1password.com was verified as official when first introduced to the cask
The comment is required, same as https://github.com/caskroom/homebrew-versions/pull/5451

2018-05-22 23:28 UTC, commitay commented
PR for `1password6` https://github.com/caskroom/homebrew-versions/pull/5720

2018-05-23 02:49 UTC, karlbright approved these changes

2018-05-23 09:51 UTC, vitorgalvao commented
> the zip file wasn't there when i checked earlier today.

Can confirm. I also checked and thought they had given rid of it for good.

2018-05-23 09:53 UTC, merged