Update microsoft-teams to 1.1.00.11551
Homebrew/homebrew-cask pull request #47522
Opened 2018-05-23 23:05 UTC by jefftougas

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

2018-05-24 09:17 UTC, vitorgalvao requested changes
Since `sha256` was updated but `version` stayed the same, this change needs to be verified. Please [follow the instructions to do so](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256).

2018-05-25 06:38 UTC, jefftougas commented
@vitorgalvao here is the VirusTotal analysis for this cask's dmg: https://www.virustotal.com/#/file/5239931c11303c89c10646600b01a847581f6e5d21974c847e29d04475cbcd93/details

Here's a screenshot of the signatures section:

![image](https://user-images.githubusercontent.com/121735/40529859-9405bbb0-5fc4-11e8-9a3f-557b7a99cdf5.png)

Let me know if I missed anything.

2018-05-25 10:18 UTC, commitay approved these changes

2018-05-25 10:18 UTC, merged

2018-05-25 10:18 UTC, commitay commented
Thanks @jefftougas!