Update projectlibre to 1.8.0
Homebrew/homebrew-cask pull request #48232
Opened 2018-06-08 22:07 UTC by rmappleby

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

2018-06-08 22:20 UTC, vitorgalvao requested changes
Since `sha256` was updated but `version` stayed the same, this change needs to be verified. Please [follow the instructions to do so](https://github.com/homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256).

2018-06-08 23:13 UTC, commitay commented
We need confirmation from the developer if it isn't codesigned.

Another contributor has an open PR for this and they have contacted the developer via twitter.
https://github.com/Homebrew/homebrew-cask/pull/47841#issuecomment-392831559

2018-06-08 23:28 UTC, rmappleby commented
Want me to just close off this pull request then?

2018-06-25 20:08 UTC, vitorgalvao commented
Closing in favour of #47841.

Thank you anyway, @rmappleby.

2018-06-25 20:08 UTC, closed without merging