Update studio-3t to 2018.3.2
Homebrew/homebrew-cask pull request #48888
Opened 2018-06-25 02:31 UTC by RJHsiao

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

2018-06-25 02:36 UTC, RJHsiao commented
Fixed for checksum error

```
Error: Checksum for Cask 'studio-3t' does not match.

Expected: 9854e2ec74687a131fe7392dd9a4c0c4256d5ea5ffb4dc2370965dd211f08957
Actual: 9ea3a66fc952260eec335526ddb5f692064b919de4335446341cd64358c0d014
```

2018-06-25 14:37 UTC, vitorgalvao requested changes
Since `sha256` was updated but `version` stayed the same, this change needs to be verified. Please [follow the instructions to do so](https://github.com/homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256).

2018-06-25 17:08 UTC, RJHsiao commented
Hmm...

> Post a link to the developer's confirmation.

Not found...

> If the Cask is an .app that is codesigned (in a .dmg or .zip container) it can be uploaded and verified using VirusTotal by looking at the “Details” tab.

No signature info...
https://www.virustotal.com/#/file/9ea3a66fc952260eec335526ddb5f692064b919de4335446341cd64358c0d014/details

2018-07-05 15:51 UTC, MerlinDMC commented
@vitorgalvao https://github.com/Homebrew/homebrew-cask/pull/48861 broke the studio-3t cask which the current PR will fix again. Can we speed this up in any way or just revert the commit that breaks the cask please?

2018-07-05 18:19 UTC, vitorgalvao commented
@MerlinDMC The other PR didn’t break the cask, upstream did. The way to speed this up is to get public confirmation from the devs that the shasum is correct.

2018-07-06 10:16 UTC, MerlinDMC commented
@vitorgalvao from the Studio 3T support team:

> Hello Daniel,
> 
> Firstly thank you for letting us know. This is indeed intended, the previous artifact for MacOS had to be rebuild under the same version number.
> 
> We will consider adding sums starting with the next releases, thank you a lot for the suggestion!
> 
> Kind regards,
> Piotr Gwizdala
> 
> --
> Piotr Gwizdala (Studio 3T) 
> Part of the Team
> 

But I suspect this will not be enough to go forward from here as it's not a publicly available statement...
guess we'll wait for a new version number then.

2018-07-20 17:49 UTC, brianmorton commented
https://github.com/Homebrew/homebrew-cask/pull/49894

2018-07-20 20:21 UTC, RJHsiao commented
Cool!

2018-07-20 20:21 UTC, closed without merging