Update sha256 for cask rar 5.6.0
Homebrew/homebrew-cask pull request #49149
Opened 2018-07-01 13:45 UTC by g-bon

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, if **adding a new cask**:

- [ ] Named the cask according to the [token reference].
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked there are no [open pull requests] for the same cask.
- [ ] Checked the cask was not already refused in [closed issues].
- [ ] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[closed issues]: https://github.com/Homebrew/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

The sha256 for rar 5.6.0 https://www.rarlab.com/rar/rarosx-5.6.0.tar.gz was not correct and causan ing error. Fixed with correct sha256.

2018-07-01 14:14 UTC, vitorgalvao requested changes
Since `sha256` was updated but `version` stayed the same, this change needs to be verified. Please [follow the instructions to do so](https://github.com/homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256).

2018-07-01 17:21 UTC, g-bon commented
Thanks, VirusTotal link:

https://www.virustotal.com/#/file/381ca05ca2701cf72148da49d36a4dda4e8e29cd0c3879f697b2861326277d5d/details

2018-07-01 18:11 UTC, vitorgalvao commented
That is expected and not the root cause of the issue. The problem is the package was updated in place upstream. Since this is not codesigned the virustotal verification is not enough. We need public confirmation from the developer that they changed the shasum to that one.

2018-07-01 19:06 UTC, g-bon commented
Ok I don't fully understand why the Sha should be different, but happy to learn if someone has time to explain.

This said I don't think the file was ever changed, couldn't just be that it was just pushed with the wrong SHA255 in this pull request [48968](https://github.com/Homebrew/homebrew-cask/pull/48968) 4 days ago and for some reason the CI didn't catch the problem?Never worked for me since it was updated

2018-07-01 20:04 UTC, vitorgalvao commented
> Ok I don't fully understand why the Sha should be different, but happy to learn if someone has time to explain.

The result of a shasum is always the same when applied to the same file. So if it changed, it means the file also changed. That means the file was replaces in place on the server. That’s somewhat common, and developers usually do that for updates they deem too small to be worth bumping the version.

> couldn't just be that it was just pushed with the wrong SHA256 in this pull request 48968 4 days ago and for some reason the CI didn't catch the problem?

That is highly unlikely. The former case is happens quite a lot.

2018-07-01 20:07 UTC, g-bon commented
Thanks a lot for the explanation. Makes sense.

2018-07-12 12:10 UTC, Viktor45 commented
Hello,



This is a legitimate modification.

32 bit app support will be removed from OS X soon and latest OS X beta
already issues a warning when running 32 bit apps. We received user
complains about it, so we replaced 32 bit RAR for OS X version
with 64 bit version.

We plan to publish only 64 bit version in the future.

Eugene

2018-07-12 12:10 UTC, Viktor45 commented
from: roshal(at)rarlab.com

> Hello,
> 
> This is a legitimate modification.
> 
> 32 bit app support will be removed from OS X soon and latest OS X beta
> already issues a warning when running 32 bit apps. We received user
> complains about it, so we replaced 32 bit RAR for OS X version
> with 64 bit version.
> 
> We plan to publish only 64 bit version in the future.
> 
> Eugene

2018-07-12 14:37 UTC, vitorgalvao commented
Thank you @Viktor45, but we need *public* confirmation. For all we know you could’ve made up that email.

2018-07-12 16:20 UTC, Viktor45 commented
@vitorgalvao you can contact rar developer yourself

2018-07-12 21:43 UTC, vitorgalvao commented
@g-bon Any of those is fine. They can tweet at [@homebrewcask](https://twitter.com/homebrewcask) from an official account, or comment here (if the person can prove they work for them). Any method is fine, as long as a person who can prove they’re from the team says it’s OK in a way we can vet.

2018-07-13 07:00 UTC, euroshal commented
I've added info about this change to "News" section of top www.rarlab.com page. Search for "64 bit RAR for OS X". If it is still not convincing, you can write to developers email from "Feedback" section of same site and I'll confirm it by email.

2018-07-13 07:16 UTC, g-bon commented
Thanks a lot @euroshal. Let's wait @vitorgalvao for confirmation but I guess that should do it.

2018-07-13 11:55 UTC, vitorgalvao commented
That does it. Thank you, everyone!

2018-07-13 11:55 UTC, merged