Update freedome to 2.19.5374.0
Homebrew/homebrew-cask pull request #49583
Opened 2018-07-12 23:34 UTC by cstrangedk

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

2018-07-12 23:36 UTC, commitay requested changes

2018-07-12 23:36 UTC, commitay commented on Casks/freedome.rb
> +  url 'https://download.sp.f-secure.com/freedome/installer/2/Freedome.pkg'
As the URL is unversioned and there isn't an appcast this should stay as `:latest` and `:no_check`

2018-07-26 12:25 UTC, vitorgalvao approved these changes

2018-07-28 16:38 UTC, vitorgalvao commented
@reitermarkus From this and a few other PR’s, it seems the keys in `uninstall` are not correctly using the wildcards.

2018-07-28 23:40 UTC, commitay commented
`launchctl` doesn't accept wildcards.

2018-07-30 14:06 UTC, merged