Upgrade xiami to v7.0.2
Homebrew/homebrew-cask pull request #50076
Opened 2018-07-25 19:03 UTC by Ouyancheng

After making all changes to the cask:

- [ ] `brew cask audit --download {{cask_file}}` is error-free.
- [ ] `brew cask style --fix {{cask_file}}` reports no offenses.
- [ ] The commit message includes the cask’s name and version.
- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [ ] Named the cask according to the [token reference].
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked there are no [open pull requests] for the same cask.
- [ ] Checked the cask was not already refused in [closed issues].
- [ ] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[closed issues]: https://github.com/Homebrew/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

2018-07-26 10:36 UTC, vitorgalvao requested changes

2018-07-26 10:36 UTC, vitorgalvao commented on Casks/xiami.rb
> +               # '~/Library/Application Support/XIAMI-MUSIC',
Either keep it or don’t. Why are you commenting out this?

2018-07-26 13:55 UTC, Ouyancheng commented
Sorry, that's for the old versions. Now it's uncommented.

2018-07-26 16:41 UTC, Ouyancheng commented on Casks/xiami.rb
> +               # '~/Library/Application Support/XIAMI-MUSIC',
Sorry for this. It's for old versions. I have uncommented them.

2018-07-30 14:02 UTC, vitorgalvao approved these changes

2018-07-30 14:09 UTC, merged