Add rrshare v2.53
Homebrew/homebrew-cask pull request #50534
Opened 2018-08-07 14:38 UTC by Maecenas

[rrshare/人人影视/字幕组](http://www.zimuzu.io)
> rrshare is the subtitles distribution software of YYeTs that offers translation of movies, TV series and open courses since 2004

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [ ] `brew cask style --fix {{cask_file}}` reports no offenses.
>
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

```
# Error when executing $ brew cask style --fix rrshare
== Casks/rrshare.rb ==
C:  5:  3: Cask/HomepageMatchesUrl: http://appdown.rrys.tv/ does not match appdown.rrys.tv/YYetsShare.

1 file inspected, 1 offense detected
Error: style check failed
```

2018-08-08 15:55 UTC, vitorgalvao requested changes

2018-08-08 15:55 UTC, vitorgalvao commented on Casks/rrshare.rb
> +  name '人人影视'
Please add the english name on top ([like so](https://github.com/Homebrew/homebrew-cask/blob/0fe48607f5656e4f1de58c6884945378b7e6f960/Casks/cave-story.rb#L7#L9)).

2018-08-09 02:47 UTC, Maecenas commented on Casks/rrshare.rb
> +  name '人人影视'
Sure! Already added the English name. By the way, should I squash all the commits before merging or let GitHub do this for me?

2018-08-09 12:16 UTC, vitorgalvao commented
I’m confused. Is it called `yyets` or `rrshare`?

2018-08-10 07:42 UTC, Maecenas commented
It's also confusing to me. As when I followed the [Cask Token Reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md#converting-to-ascii) and found that this app was named after `rrshare` by developer. However, there is no other exposure to this name, and not even on its homepage. What's more, searching `rrsahre` with major search engines would only give unrelated messages. The organization `YYeTs` however, is the consistent name for referencing and searching.

I personally recommend using `yyets` or `YYeTs` to reference the task for searching/indexing purposes. It would be better if we add the Chinese annotation/cask name `人人影视` (`YYeTs`'s Chinese name) to it.  

```plist
<!-- Digest of 人人影视.app/Info.plist  -->

	<key>CFBundleExecutable</key>
	<string>rrshare</string>
        <key>CFBundleName</key>
        <string>人人影视</string>
	<key>CFBundleIdentifier</key>
	<string>com.yyets.rrshare</string>
```
@vitorgalvao

2018-08-10 13:01 UTC, vitorgalvao approved these changes

2018-08-11 03:26 UTC, Maecenas commented
Squash previous commits. However, if the related branch name were to change, this PR is set to track only the original one. Would it be better to close this PR and reference it from a new one?

2018-08-11 12:15 UTC, vitorgalvao commented
There’s no need to squash commits. Github’s web interface let’s us do it on merge.

2018-08-11 12:15 UTC, merged