Update resolume-arena to 6.0.11,61108
Homebrew/homebrew-cask pull request #50564
Opened 2018-08-07 18:01 UTC by brianmorton

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

2018-08-08 22:07 UTC, brianmorton commented
```
Error: Some launch jobs were not unloaded.
+ com.resolume.arena.15800
Error: Some packages were not uninstalled.
+ com.resolume.pkg.ResolumeDXV.plist
+ com.resolume.pkg.ResolumeQuickLook.plist
Error: Build failed.
```

The packages failing are expect as they are in a `zap`, but how do I do the launch job with that PID or whatever on the end?

2018-08-08 22:38 UTC, brianmorton commented
need help with this launch control job

2018-08-10 20:14 UTC, victorpopkov approved these changes

2018-08-11 17:44 UTC, reitermarkus commented
The ones listed on Travis should be added as `pkgutil`.

2018-08-13 17:20 UTC, brianmorton commented
Per travis, I added the `uninstall quit:` block. As discussed in the other resolume cask PR, the zap is there for shared entries.

2018-08-13 17:47 UTC, brianmorton commented
Unless somebody wants to continue working on these packages, I will probably just close this PR and give up on this cask.

2018-08-13 18:57 UTC, vitorgalvao requested changes

2018-08-13 18:57 UTC, vitorgalvao commented on Casks/resolume-arena.rb
> +  url "https://resolume.com/download/Resolume_Arena_#{version.major_minor_patch.dots_to_underscores}_rev_#{version.after_comma}_Inst$
Something went wrong here. Everything else looks fine.

2018-08-13 22:36 UTC, merged