Update resolume-avenue to 6.0.11,60828
Homebrew/homebrew-cask pull request #50565
Opened 2018-08-07 18:13 UTC by brianmorton

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

2018-08-08 22:38 UTC, brianmorton commented
should be good to merge i think, the `zap` stanza always fails IIRC.

2018-08-10 20:15 UTC, victorpopkov approved these changes

2018-08-12 02:04 UTC, reitermarkus requested changes

2018-08-12 02:04 UTC, reitermarkus commented on Casks/resolume-avenue.rb
>                 'com.resolume.pkg.ResolumeDXV',
This shouldn't be here.

2018-08-13 04:26 UTC, brianmorton commented on Casks/resolume-avenue.rb
>                 'com.resolume.pkg.ResolumeDXV',
Sorry I'm a bit thick sometimes - what shouldn't be where? The zap trash?

2018-08-13 04:58 UTC, reitermarkus commented on Casks/resolume-avenue.rb
>                 'com.resolume.pkg.ResolumeDXV',
This should be in `uninstall`, not in `zap`.

2018-08-13 11:13 UTC, vitorgalvao commented on Casks/resolume-avenue.rb
>                 'com.resolume.pkg.ResolumeDXV',
This is in `zap` because it’s shared with [`resolume-arena`](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/resolume-arena.rb). Though I’m not familiar with the software so I have no idea if you’d ever install both versions.

But at the very least it should be `zap pkgutil:`, not `zap trash:`.

2018-08-13 17:15 UTC, brianmorton commented
updated `zap` to `pkgutil`

2018-08-13 17:47 UTC, brianmorton commented
Unless somebody wants to continue working on these packages, I will probably just close this PR and give up on this cask.

2018-08-13 18:50 UTC, vitorgalvao approved these changes

2018-08-15 21:26 UTC, brianmorton commented
Pls merge or close ;)

2018-08-16 06:58 UTC, merged