Update onedrive to 18.131.0701.0008
Homebrew/homebrew-cask pull request #50661
Opened 2018-08-09 16:58 UTC by yuusharo

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

2018-08-09 18:18 UTC, vitorgalvao requested changes

2018-08-09 18:35 UTC, yuusharo commented on Casks/onedrive.rb
> +  version '18.131.0701.0008'
It's the latest version of the standalone client that gets pushed to me the moment I run OneDrive after a cask install. The OneDrive Updater forces an upgrade to this version in the background.

You should be able to recreate this by installing OneDrive from cask, then launch it. An update process will run in the background, and the client will restart and update to version 18.131.0701.0008 (Standalone).

As for why it's not showing up on Microsoft's documentation, I don't know.

Please see the attached screenshot.

![screen shot 2018-08-09 at 11 26 49 am](https://user-images.githubusercontent.com/36213375/43918414-da40db20-9bc7-11e8-95a3-3ee907a88f18.png)

2018-08-09 23:25 UTC, yuusharo commented on Casks/onedrive.rb
> +  version '18.131.0701.0008'
Update: After moving back to my personal MacBook Pro, the OneDrive client there updated to 18.111.0603.0007, as you mentioned before on Microsoft's website. I can't explain the version difference. I'm not part of the Insiders Program on that other machine. Perhaps some sort of A/B testing, or a staged rollout?

In any case, the current version on Cask is still out of date, and perhaps should be updated to at least 18.111.0603.0007 to match Microsoft's documentation. It doesn't technically matter, since the OneDrive client will almost always update to what it considers the latest version after launching it.

Sorry for the trouble. Take care!

2018-08-10 12:10 UTC, vitorgalvao approved these changes

2018-08-10 12:51 UTC, merged