world-of-tanks: add 'uk' and 'be' to cis region
Homebrew/homebrew-cask pull request #51209
Opened 2018-08-23 16:45 UTC by yurikoles

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

I'm not sure why other languages are spelled in capital letters, for me only 'uk' works.

2018-08-23 16:50 UTC, vitorgalvao requested changes

2018-08-23 16:50 UTC, vitorgalvao commented on Casks/world-of-tanks.rb
> +  language 'be', 'ru', 'uk' do
I’ll need some justification, here, this is a weird coupling.

And why would they have both `gb` and `uk`?

2018-08-23 17:31 UTC, yurikoles commented on Casks/world-of-tanks.rb
> +  language 'be', 'ru', 'uk' do
UK don't works for me, it installs us version. `gb` is for United Kingdom, `uk` is for Ukrainian.

2018-08-23 17:32 UTC, yurikoles commented on Casks/world-of-tanks.rb
> +  language 'be', 'ru', 'uk' do
@vitorgalvao this couple is for CIS region, users from this region are offered to install Russian version.

2018-08-23 17:33 UTC, yurikoles commented on Casks/world-of-tanks.rb
> +  language 'be', 'ru', 'uk' do
`be` is for Belarusian.

2018-08-23 19:55 UTC, vitorgalvao commented on Casks/world-of-tanks.rb
> +  language 'be', 'ru', 'uk' do
`be` is Belgium. Belarus is `by` and Ukraine is `ua`.

2018-08-24 12:32 UTC, yurikoles commented on Casks/world-of-tanks.rb
> +  language 'be', 'ru', 'uk' do
We talk about different things: countries vs. languages.

2018-08-24 14:19 UTC, vitorgalvao commented on Casks/world-of-tanks.rb
> +  language 'be', 'ru', 'uk' do
`BE` is already at the top. Why should `BE` and `UK` be here?

Also, change the capitalisation to uppercase, it works fine. You also need to capitalise when giving `--language`.

2018-08-24 19:35 UTC, reitermarkus commented
Regions should be uppercase.

2018-08-24 19:36 UTC, reitermarkus commented
And `uk` should be `GB`.

2018-09-14 12:34 UTC, yurikoles commented
bump?

2018-09-14 12:45 UTC, vitorgalvao requested changes

2018-09-14 12:45 UTC, vitorgalvao commented on Casks/world-of-tanks.rb
> +  language 'AZ', 'BE', 'HY', 'KK', 'KY', 'RU', 'UK', 'UZ', 'TG' do # CIS region
Please remove the comment.

2018-09-14 12:45 UTC, vitorgalvao requested changes
> Checksum for Cask 'world-of-tanks' does not match.
>
> Expected:133b3f3271eb957a4eea59cd59a6f79d2c4376a4297a980d8c9232ae9419a995
> Actual:23c2e97b89eeabd45aa5a6250e87b15c9f17757271f615e013453fea3949ac60

2018-09-14 12:46 UTC, vitorgalvao commented on Casks/world-of-tanks.rb
>    version '2.0.21'
It’s now at `2.0.28`.

2018-09-14 12:49 UTC, yurikoles commented
There is mention of version `2.0.28` in all appcasts, but only CIS binary has updated 😕.

2018-09-14 12:53 UTC, yurikoles commented on Casks/world-of-tanks.rb
>    version '2.0.21'
@vitorgalvao, thanks, I had already figured out. See my comment below.

2018-09-14 12:55 UTC, yurikoles commented
Oh, asian binary was also updated 😕.

2018-09-14 12:58 UTC, yurikoles commented
I had updated committed message to include all languages that I had added to CIS region.

2018-09-14 13:00 UTC, yurikoles commented on Casks/world-of-tanks.rb
> +  language 'AZ', 'BE', 'HY', 'KK', 'KY', 'RU', 'UK', 'UZ', 'TG' do # CIS region
@vitorgalvao, done.

2018-09-14 13:09 UTC, vitorgalvao commented
Travis passed. Merging. Thank you.

2018-09-14 13:09 UTC, merged