Update x2goclient to 4.1.2.1
Homebrew/homebrew-cask pull request #51442
Opened 2018-08-30 12:01 UTC by ytbmulder

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

2018-08-30 22:13 UTC, adidalal requested changes

2018-08-30 22:13 UTC, adidalal commented on Casks/x2goclient.rb
> +  version '4.1.2.1'
Please change it to `version '4.1.2.1, 20180717'` and use version methods, as version seems to be linked to date implicitly here.

Info [here][https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/version.md]

2018-09-02 09:02 UTC, ytbmulder commented on Casks/x2goclient.rb
> +  version '4.1.2.1'
I fixed the version as requested, added a cask for Snow Leopard, and added a caveats section.

2018-09-02 10:50 UTC, vitorgalvao requested changes

2018-09-02 10:50 UTC, vitorgalvao commented on Casks/x2goclient.rb
> +  caveats "The X2Go OS X client uses the OS X X11 server.
`caveats` are for instructions related to installation, not usage. Please remove it.

[This is documented](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/caveats.md#caveats).

2018-09-03 05:25 UTC, ytbmulder commented on Casks/x2goclient.rb
> +  caveats "The X2Go OS X client uses the OS X X11 server.
I removed the caveats section. Is there a place to inform the user about the cask's usage?

2018-09-03 12:00 UTC, vitorgalvao commented on Casks/x2goclient.rb
> +  caveats "The X2Go OS X client uses the OS X X11 server.
> Is there a place to inform the user about the cask's usage?

The software’s usage, not the cask’s usage, and therein lies the difference. As per the linked documentation, `caveats` are for installation-related matters (i.e. cask’s usage). For the software’s usage, the user has to consult the vendor page. [This is also documented](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/not_a_discoverability_service.md).

Ultimately we manage packages: we make it easier for you to install and uninstall things. It’s your responsibility to know how to use them.

2018-09-03 12:43 UTC, ytbmulder commented on Casks/x2goclient.rb
> +  caveats "The X2Go OS X client uses the OS X X11 server.
Thank you for the extensive reply. This makes sense now.

2018-09-05 05:43 UTC, ytbmulder commented on Casks/x2goclient.rb
> +  caveats "The X2Go OS X client uses the OS X X11 server.
@vitorgalvao I have made the requested changes.

2018-09-05 12:23 UTC, merged