Add geotag-photos-pro v1.0.8 cask
Homebrew/homebrew-cask pull request #51540
Opened 2018-09-01 16:02 UTC by dlackty

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

2018-09-08 19:58 UTC, victorpopkov approved these changes

2018-09-09 19:53 UTC, vitorgalvao requested changes

2018-09-09 19:53 UTC, vitorgalvao commented on Casks/geotag-photos-pro.rb
> +  url "https://github.com/tappytaps/geotag-desktop-app/releases/download/v#{version}/geotag-#{version}-mac.zip"
From the download URL on the page it’s not possible to verify this is the repo it takes from. Is there anything on the website that confirms it?

2018-09-10 04:09 UTC, dlackty commented on Casks/geotag-photos-pro.rb
> +  url "https://github.com/tappytaps/geotag-desktop-app/releases/download/v#{version}/geotag-#{version}-mac.zip"
This was found on the website's download link.
```
 % curl -I https://www.geotagphotos.net/download?type=mac
HTTP/1.1 302 Found
Date: Mon, 10 Sep 2018 04:08:50 GMT
Server: Apache/2.4.18 (Ubuntu) SVN/1.9.3 mod_fcgid/2.3.9 OpenSSL/1.0.2g mod_wsgi/4.3.0 Python/2.7.12
X-Powered-By: Nette Framework
X-Frame-Options: SAMEORIGIN
Location: https://github.com/tappytaps/geotag-desktop-app/releases/download/v1.0.8/geotag-1.0.8-mac.zip
Content-Type: text/html; charset=utf-8```

2018-09-10 08:13 UTC, merged