Update picat to 2.4#8
Homebrew/homebrew-cask pull request #51564
Opened 2018-09-03 02:00 UTC by boltomli

Release version 2.4#8, August 16, 2018.
audit for picat: passed

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [ ] `brew cask style --fix {{cask_file}}` reports no offenses. (Failed to install/update the 'rubocop-cask' gem.)
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [ ] Named the cask according to the [token reference].
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked there are no [open pull requests] for the same cask.
- [ ] Checked the cask was not [already refused].
- [ ] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

2018-09-03 12:20 UTC, vitorgalvao requested changes
Since `sha256` was updated but `version` stayed the same, this change needs to be verified. Please [follow the instructions to do so](https://github.com/homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256).

2018-09-04 06:43 UTC, boltomli commented
Thanks for the check. I updated version as well. Upstream updates trivia version after '#' without updating minor version nor download location, but just replaces the file when doing so.

2018-09-04 17:57 UTC, vitorgalvao approved these changes

2018-09-06 12:55 UTC, reitermarkus commented
Looking at http://picat-lang.org/download.html, this seems to be open-source and CLI only, so this should be a formula.

2018-09-10 00:16 UTC, vitorgalvao commented
@boltomli What @reitermarkus is referring to is policy documented in [faq/rejected_casks](https://github.com/homebrew/homebrew-cask/blob/master/doc/faq/rejected_casks.md):

> The app is both open-source and CLI-only (i.e. it only uses the `binary` artifact). In that case, and [in the spirit of deduplication](https://github.com/Homebrew/homebrew-cask/issues/15603), submit it first to [Homebrew/core](https://github.com/Homebrew/homebrew-core) as a formula that builds from source. If it is rejected, you may then try again as a cask (link us to the issue so we can see the discussion and reasoning for rejection).

This means we’ll have to remove the cask. Would you like to try to submit the formula?

2018-09-10 04:06 UTC, boltomli commented
Thanks for the comments. I may keep this as a tap then in my repo, because the source to build needs modifications from the official tarball and not easy to maintain. So far I can only rely on the binary from official site. Here's an unofficial mirror with fixes to build <https://github.com/rurban/picat-lang>

2018-09-11 17:24 UTC, closed without merging