Add Lynx Launcher v3.0.0
Homebrew/homebrew-cask pull request #51610
Opened 2018-09-04 15:14 UTC by PhilHannent

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

2018-09-05 12:44 UTC, vitorgalvao requested changes

2018-09-05 12:44 UTC, vitorgalvao commented on Casks/lynx-launcher.rb
> +  url 'http://download.saharasupport.com/lynxlauncher2/production/macx/LynxLauncher.pkg'
I only see DMGs to download on the page. Where are you getting this one from?

2018-09-09 05:33 UTC, adidalal requested changes
Similar comments as Lynx (versioning, appcast, dmg, etc) - please reply with specific concerns and I'd be happy to elaborate.

2018-10-11 21:44 UTC, vitorgalvao commented
No reply for over a month. Closing.

2018-10-11 21:44 UTC, closed without merging