Add VSCodium v1.27.1
Homebrew/homebrew-cask pull request #51727
Opened 2018-09-08 16:45 UTC by MatiasConTilde

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

2018-09-09 05:36 UTC, adidalal commented
@MatiasConTilde Does this conflict with `vscode`, or can they be installed in harmony? That would also determine what would be appropriate to put in `uninstall`

2018-09-09 11:43 UTC, vitorgalvao requested changes

2018-09-09 11:43 UTC, vitorgalvao commented on Casks/vscodium.rb
> +cask 'vscodium' do
Pinging @stripedpajamas as well.

This one is a problem, as it does not adhere to the [token reference](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md) (which it needs to, as it helps with duplicates). Two options:

1. Rename the cask `code-oss`.
2. Rename the app `VSCodium` *on your end*.

2018-09-09 14:54 UTC, adidalal commented
And do they use the same settings folder? (~/.vscode or something IIRC)

2018-09-09 16:44 UTC, MatiasConTilde commented
@adidalal No, everything is separte, even the extensions. The config folders are `~/.vscode/`and `~/.vscode-oss/`

@vitorgalvao I personally prefer the second option and opened https://github.com/VSCodium/vscodium/issues/11, but as I'm not a mantainer I can't change it myself. If VSCodium's devs don't agree, I will rename it to `code-oss`.

2018-09-10 21:45 UTC, stripedpajamas commented on Casks/vscodium.rb
> +cask 'vscodium' do
Changed the name of the app to VSCodium 😄thanks @vitorgalvao and @MatiasConTilde

2018-09-10 22:00 UTC, vitorgalvao commented on Casks/vscodium.rb
> +cask 'vscodium' do
Thank you @stripedpajamas. @MatiasConTilde Care to update the cask?

2018-09-12 19:21 UTC, vitorgalvao approved these changes

2018-09-12 20:31 UTC, stripedpajamas approved these changes

2018-09-13 07:44 UTC, merged