Update SpiderOakONE to 7.3.0
Homebrew/homebrew-cask pull request #51834
Opened 2018-09-11 19:33 UTC by g-a-c

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [ ] Named the cask according to the [token reference].
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked there are no [open pull requests] for the same cask.
- [ ] Checked the cask was not [already refused].
- [ ] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

2018-09-12 11:07 UTC, vitorgalvao commented on Casks/spideroakone.rb
> +  uninstall quit:    'com.spideroak.orange.client',
If Travis still fails, try [`signal`](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/uninstall.md#uninstall-key-signal) instead.

2018-09-14 12:30 UTC, vitorgalvao requested changes

2018-09-14 12:30 UTC, vitorgalvao commented on Casks/spideroakone.rb
> +  uninstall signal:  [
It should be just one (the lowest one that gets the job done).

2018-09-14 12:31 UTC, vitorgalvao commented on Casks/spideroakone.rb
> +            pkgutil: 'org.python.python'
Is this correct? Why is it uninstalling `python`?

2018-09-16 16:03 UTC, g-a-c commented on Casks/spideroakone.rb
> +            pkgutil: 'org.python.python'
That's the ID that's used in the SpiderOak installer:

```
gac@MBP /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/developer/bin ±master » ./list_ids_in_pkg /Volumes/SpiderOakONE/SpiderOakONE.pkg
org.python.python (+)
```

I'm sure it might be considered a bug in SpiderOak, but that's what it does, so if we want it in Homebrew then that's how it should be. Since Python isn't distributed as a Cask it seems like it should be safe from conflicting with an actual version of Python, which is (I assume) why it was allowed into Homebrew to begin with (I'm not the original committer).

2018-11-02 12:01 UTC, reitermarkus commented on Casks/spideroakone.rb
> +  if MacOS.version == :high_sierra
Use `<=`.

2018-11-02 12:02 UTC, reitermarkus commented on Casks/spideroakone.rb
> +  depends_on macos: '>= :mavericks'
This doesn't match `MacOS.version == :high_sierra` above.

2018-11-05 15:53 UTC, g-a-c commented on Casks/spideroakone.rb
> +  depends_on macos: '>= :mavericks'
It isn't supposed to match - the SpiderOak download offering is supported on Mavericks and above, but for some reason (which I don't know) they offer one package for 10.9, 10.10, 10.11, 10.12, and 10.14 and a separate package for 10.13 only.

2018-11-05 15:57 UTC, g-a-c commented on Casks/spideroakone.rb
> +  if MacOS.version == :high_sierra
Please see the other comment - for some reason 10.13 is the only version of macOS that needs this package, both older and newer versions of macOS use the alternative package.

Maybe this would be easier to read with multiple ifs for  "<= el_capitan", "== high_sierra", ">= mojave"?

2018-11-08 19:20 UTC, closed without merging