Fix coconutbattery 3.7 checksum
Homebrew/homebrew-cask pull request #52390
Opened 2018-09-24 14:40 UTC by vin047

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

2018-09-25 02:41 UTC, miccal commented
Closes https://github.com/Homebrew/homebrew-cask/issues/52377

2018-09-25 21:36 UTC, vitorgalvao requested changes
Since `sha256` was updated but `version` stayed the same, this change needs to be verified. Please [follow the instructions to do so](https://github.com/homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256).

2018-09-26 05:42 UTC, numbermaniac commented on Casks/coconutbattery.rb
> +    sha256 '66cdaec7f53f1e9d13c265f0c2e7418f304656a5a46fc9f940a79201006fde9d'
SHA256 appears to have changed again, downloading it from their website gives a `shasum` of `fe0338e808c76096d8fad8cd3ef2eb98f8f6860278abbb89a85507e9872bffe2`.

Another user also reported the same SHA256 at https://github.com/Homebrew/homebrew-cask/issues/52377#issuecomment-424414416

2018-09-26 05:46 UTC, numbermaniac commented
VirusTotal says the file is fine: https://www.virustotal.com/#/file/fe0338e808c76096d8fad8cd3ef2eb98f8f6860278abbb89a85507e9872bffe2/details

2018-09-26 11:01 UTC, merged