xdm: new cask, 7.2.7
Homebrew/homebrew-cask pull request #52433
Opened 2018-09-25 12:17 UTC by yurikoles

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

2018-09-25 21:45 UTC, vitorgalvao requested changes

2018-09-25 21:45 UTC, vitorgalvao commented on Casks/xdm.rb
> +  uninstall delete: [
It’s unlikely this is all the script does. Isn’t there an `uninstaller`?

Also, please pay attention to the corrections. You’ve been submitting for years, probably, and still make basic mistakes like not separating the array properly.

2018-09-26 18:35 UTC, yurikoles commented on Casks/xdm.rb
> +  uninstall delete: [
from [official ticket](https://sourceforge.net/p/xdman/discussion/xdmhelp/thread/701f5570/):

>* delete the xdm.app folder from applications
>* open terminal, and type rm -rf ~/.xdman

2018-09-26 18:36 UTC, yurikoles commented on Casks/xdm.rb
> +  uninstall delete: [
@vitorgalvao we have ticket about arrays: https://github.com/Homebrew/rubocop-cask/issues/64

2018-09-26 18:37 UTC, yurikoles commented on Casks/xdm.rb
> +  uninstall delete: [
And, no, I can't find any uninstaller in dmg or app dir.

2018-09-26 20:38 UTC, vitorgalvao commented on Casks/xdm.rb
> +  uninstall delete: [
> we have ticket about arrays: Homebrew/rubocop-cask#64

Yes, but that’s about `style` doing it automatically, nothing stops you from doing it manually, which is what everyone else does.

2018-09-26 20:40 UTC, vitorgalvao requested changes

2018-09-26 20:40 UTC, vitorgalvao commented on Casks/xdm.rb
> +                      '/Applications/xdm.app/',
Remove the trailing slash.

2018-09-26 20:40 UTC, vitorgalvao commented on Casks/xdm.rb
> +                      '~/Desktop/xdm.app',
It installs one app in `/Applications` *and* another one with the same name in the `Desktop`?

2018-09-26 21:17 UTC, yurikoles commented on Casks/xdm.rb
> +                      '~/Desktop/xdm.app',
I no longer see app on Desktop after fresh install, seems to be issue in my setup.

2018-10-06 15:43 UTC, victorpopkov approved these changes

2018-10-11 21:34 UTC, merged