Update sts to 4.0.0
Homebrew/homebrew-cask pull request #52458
Opened 2018-09-25 20:57 UTC by VonUniGE

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

2018-09-25 21:51 UTC, vitorgalvao requested changes

2018-09-25 21:51 UTC, vitorgalvao commented on Casks/sts.rb
> +  url 'http://download.springsource.com/release/STS4/4.0.0.RELEASE/dist/e4.9/spring-tool-suite-4-4.0.0.RELEASE-e4.9.0-macosx.cocoa.x86_64.dmg'
Please revert this to what it was. This change will make the cask harder to update.

2018-09-25 21:51 UTC, vitorgalvao commented on Casks/sts.rb
> +  app 'SpringToolSuite4.app'
`SpringToolSuite#{version.major}.app`

2018-10-07 17:32 UTC, reitermarkus commented
Closed in favour of https://github.com/Homebrew/homebrew-cask/pull/52972.

2018-10-07 17:32 UTC, closed without merging