Upgrade plug to 2.0.19
Homebrew/homebrew-cask pull request #52480
Opened 2018-09-26 05:33 UTC by jesse-c

- [x] `brew cask audit --download plug` is error-free.
- [x] `brew cask style --fix plug` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Corrected https://github.com/Homebrew/homebrew-cask/pull/52449.

2018-09-27 11:36 UTC, vitorgalvao requested changes

2018-09-27 11:36 UTC, vitorgalvao commented on Casks/plug.rb
> +    appcast 'https://www.plugformac.com/updates/plug#{version.major}/sparklecast.xml'
Don’t change the quotes. It breaks the interpolation.

2018-09-27 11:36 UTC, vitorgalvao commented on Casks/plug.rb
> +    url 'https://www.plugformac.com/updates/plug2/Plug-2067.dmg'
We can’t use a hidden link other users don’t have access to. Also, by removing the interpolation you’re making this harder to update.

Either make this the official link on the page or update the shasum.

2018-09-28 16:43 UTC, jesse-c commented
Thanks for the feedback. Will leave it as is for now.

2018-09-28 16:43 UTC, closed without merging