Add On1 Photo Raw 2018
Homebrew/homebrew-cask pull request #52569
Opened 2018-09-27 23:20 UTC by teran

Signed-off-by: Igor Shishkin <me@teran.ru>

After making all changes to the cask:

- [X] `brew cask audit --download {{cask_file}}` is error-free.
- [X] `brew cask style --fix {{cask_file}}` reports no offenses.
- [X] The commit message includes the cask’s name and version.
- [X] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [X] Named the cask according to the [token reference].
- [X] `brew cask install {{cask_file}}` worked successfully.
- [X] `brew cask uninstall {{cask_file}}` worked successfully.
- [X] Checked there are no [open pull requests] for the same cask.
- [X] Checked the cask was not [already refused].
- [X] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

2018-09-28 19:56 UTC, vitorgalvao requested changes

2018-09-28 19:56 UTC, vitorgalvao commented on Casks/on1-photo-raw.rb
> +  uninstall script: {
Please add `pkgutil` and the other methods that apply. `script` should be used *in addition to* the others.

2018-09-28 21:01 UTC, teran commented on Casks/on1-photo-raw.rb
> +  uninstall script: {
Done

2018-10-01 00:02 UTC, vitorgalvao requested changes

2018-10-01 00:02 UTC, vitorgalvao commented on Casks/on1-photo-raw.rb
> +  uninstall pkgutil: 'com.ononesoftware.pluginsuite1200.premium',
Keep the `script`.

2018-10-01 00:07 UTC, teran commented on Casks/on1-photo-raw.rb
> +  uninstall pkgutil: 'com.ononesoftware.pluginsuite1200.premium',
@vitorgalvao it makes no sense, since removing package com.ononesoftware.pluginsuite1200.premium will remove the script too and AFAICS in [documentation](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/uninstall.md#summary-of-keys) `pkgutil` runs before `script` so it have no chance to be run anyway.

2018-10-23 21:55 UTC, teran commented
@vitorgalvao @reitermarkus guys, it's almost a month passed, there's even new version of On1 Photo Raw released :) let's finally decide how to deal with it?:)

2018-12-11 15:32 UTC, vitorgalvao commented on Casks/on1-photo-raw.rb
> +  uninstall pkgutil: 'com.ononesoftware.pluginsuite1200.premium',
Please readd the `script`. It does (should) indeed [run first](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/cask/artifact/abstract_uninstall.rb#L16L17).

2019-01-08 11:49 UTC, reitermarkus commented
@teran, closing this for now due to no response. Feel free to resubmit this with the updated version and the added `script`.

2019-01-08 11:49 UTC, closed without merging