Upgrade Aria2D to Latest
Homebrew/homebrew-cask pull request #52667
Opened 2018-10-01 05:59 UTC by CaptainYukinoshitaHachiman

The author stopped offering download for previous versions, instead, now he provides a general url. So here I'm updating for this.

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

2018-10-01 08:08 UTC, vitorgalvao requested changes

2018-10-01 08:08 UTC, vitorgalvao commented on Casks/aria2d.rb
> +  version :latest
The cask has an `appcast`, so `version` and `sha256` should remain (`1.2.4`).

2018-10-01 15:11 UTC, CaptainYukinoshitaHachiman commented on Casks/aria2d.rb
> +  version :latest
but we don't have the link for different versions

2018-10-02 00:30 UTC, vitorgalvao commented on Casks/aria2d.rb
> +  version :latest
And set the `sha256`.

2018-10-02 02:19 UTC, CaptainYukinoshitaHachiman commented on Casks/aria2d.rb
> +  version :latest
But I don't have the version after comma

2018-10-02 13:40 UTC, merged