Add Clockify v2.1.6
Homebrew/homebrew-cask pull request #52756
Opened 2018-10-03 07:08 UTC by danyim

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

2018-10-03 09:39 UTC, danyim commented
I'm not sure why CI failed. Could someone shed some light?

2018-10-03 12:36 UTC, vitorgalvao commented on Casks/clockify.rb
> +  depends_on macos: '>= 10.8'
Unnecessary. Too far behind.

2018-10-03 12:36 UTC, vitorgalvao commented on Casks/clockify.rb
> +  container nested: 'Clockify Desktop.app'
You’re misunderstanding what this line does. What were you expecting it did?

2018-10-03 12:37 UTC, vitorgalvao commented on Casks/clockify.rb
> +  url 'https://drive.google.com/uc?export=download&id=1kPzQGOveprS_JFlQJG8wd0IYh-trmj1o'
Where are you getting this URL from?

2018-10-03 12:38 UTC, vitorgalvao requested changes
Before the merge, please clarify where the Google Drive URL came from.

2018-10-04 02:40 UTC, danyim commented
The link was from this helpdesk URL: https://clockify.me/help/apps/mac-desktop-app

But now that I navigated their site, it looks like they fixed their original app URL in this link: https://clockify.me/mac-time-tracking

which points to https://clockify.me/downloads/ClockifyDesktop_216_35.zip

2018-10-04 02:47 UTC, danyim commented on Casks/clockify.rb
> +  container nested: 'Clockify Desktop.app'
I assumed that this would extract this particular file from the compressed ZIP.

2018-10-04 02:47 UTC, danyim commented on Casks/clockify.rb
> +  url 'https://drive.google.com/uc?export=download&id=1kPzQGOveprS_JFlQJG8wd0IYh-trmj1o'
See PR comment for full context, but in short it was from their helpdesk page: https://clockify.me/help/apps/mac-desktop-app

2018-10-04 02:48 UTC, danyim commented
Thanks for making the changes for me! Is it good to merge now?

2018-10-04 02:49 UTC, danyim commented on Casks/clockify.rb
> +  depends_on macos: '>= 10.8'
I took this from another cask.

2018-10-04 11:51 UTC, vitorgalvao commented
> In retrospect, it was probably unsafe to be linking to a random Google Drive binary without any way to verify its owner, origin, or contents.

Yes, that was the the issue.

Thank you for the explanation.

2018-10-04 11:51 UTC, merged

2018-10-04 13:12 UTC, vitorgalvao commented on Casks/clockify.rb
> +  depends_on macos: '>= 10.8'
Which cask?