Archipelago v2.3.2 - New Cask
Homebrew/homebrew-cask pull request #52809
Opened 2018-10-04 03:16 UTC by andrewmcodes

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

2018-10-04 13:55 UTC, vitorgalvao requested changes

2018-10-04 13:55 UTC, vitorgalvao commented on Casks/archipelago.rb
> +  homepage 'https://archipelago-terminal.herokuapp.com/download/osx'
This is not a homepage, it’s a download link.

2018-10-05 01:11 UTC, andrewmcodes commented on Casks/archipelago.rb
> +  homepage 'https://archipelago-terminal.herokuapp.com/download/osx'
@vitorgalvao This application does not have a homepage and the linters really want one :unamused: Do you have any suggestions, other than submitting a PR to add a homepage of some sorts to the repo?

2018-10-05 01:12 UTC, commitay commented on Casks/archipelago.rb
> +  homepage 'https://archipelago-terminal.herokuapp.com/download/osx'
Where did you get the download URL from?

2018-10-05 02:08 UTC, andrewmcodes commented on Casks/archipelago.rb
> +  homepage 'https://archipelago-terminal.herokuapp.com/download/osx'
@commitay The [readme](https://github.com/npezza93/archipelago) of the repo.

2018-10-05 02:10 UTC, commitay commented on Casks/archipelago.rb
> +  homepage 'https://archipelago-terminal.herokuapp.com/download/osx'
https://github.com/npezza93/archipelago can be used as the homepage

2018-10-05 11:42 UTC, vitorgalvao requested changes

2018-10-05 11:42 UTC, vitorgalvao commented on Casks/archipelago.rb
> +  url 'https://archipelago-terminal.herokuapp.com/download/osx'
Make it a link from [the releases page](https://github.com/npezza93/archipelago/releases).

2018-10-05 11:42 UTC, vitorgalvao commented on Casks/archipelago.rb
> +  version :latest
Add a `version` and `sha256`.

2018-10-08 22:08 UTC, andrewmcodes commented on Casks/archipelago.rb
> +  version :latest
👍

2018-10-08 22:09 UTC, andrewmcodes commented on Casks/archipelago.rb
> +  url 'https://archipelago-terminal.herokuapp.com/download/osx'
👍

2018-10-08 23:57 UTC, vitorgalvao requested changes

2018-10-08 23:57 UTC, vitorgalvao commented on Casks/archipelago.rb
> +  url 'https://github.com/npezza93/archipelago/releases/tag/v2.3.2'
No. An actual dmg or zip. Something that actually downloads a package.

2018-10-08 23:57 UTC, vitorgalvao commented on Casks/archipelago.rb
> +  url 'https://github.com/npezza93/archipelago/releases/tag/v2.3.2'
Why did you remove the `appcast` line? Don’t.

2018-10-10 21:34 UTC, andrewmcodes commented on Casks/archipelago.rb
> +  url 'https://github.com/npezza93/archipelago/releases/tag/v2.3.2'
Sorry, I think everything should be good to go now.

2018-10-10 22:45 UTC, vitorgalvao approved these changes

2018-10-11 09:50 UTC, merged