Add AdoptOpenJDK 11,28
Homebrew/homebrew-cask pull request #52874
Opened 2018-10-05 08:29 UTC by gdams

This cask installs the AdoptOpenJDK build of OpenJDK11.

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [ ] Named the cask according to the [token reference].
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked there are no [open pull requests] for the same cask.
- [ ] Checked the cask was not [already refused].
- [ ] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

2018-10-05 08:37 UTC, commitay requested changes

2018-10-05 08:37 UTC, commitay commented on Casks/adoptopenjdk.rb
> +                          'https://raw.githubusercontent.com/AdoptOpenJDK/homebrew-openjdk/plist/Info.plist'],
Running `curl` in a cask isn't acceptable. If this is needed it should be included in the tarball.

2018-10-05 08:41 UTC, gdams commented on Casks/adoptopenjdk.rb
> +                          'https://raw.githubusercontent.com/AdoptOpenJDK/homebrew-openjdk/plist/Info.plist'],
@commitay thanks for the feedback. I'll have a play around and work how to to avoid this.

2018-10-05 08:43 UTC, commitay commented on Casks/adoptopenjdk.rb
> +    system_command '/usr/libexec/PlistBuddy',
Why are all of the plist commands needed?

2018-10-05 08:43 UTC, commitay commented on Casks/adoptopenjdk.rb
> +    system_command '/bin/rm',
Remove this.

2018-10-05 08:43 UTC, commitay commented on Casks/adoptopenjdk.rb
> +    system_command '/bin/rm',
Remove this.

2018-10-05 08:44 UTC, gdams commented on Casks/adoptopenjdk.rb
> +    system_command '/usr/libexec/PlistBuddy',
We essentially have a default Info.plist which we then configure with the correct values for the Java version

2018-10-05 08:46 UTC, commitay commented on Casks/adoptopenjdk.rb
> +    system_command '/usr/libexec/PlistBuddy',
It would be better if it was handled upstream rather than in the cask.

2018-10-05 08:47 UTC, gdams commented on Casks/adoptopenjdk.rb
> +    system_command '/bin/rm',
We have to have this because we move `/usr/local/Caskroom/adoptopenjdk/#{version}` to `/usr/local/Caskroom/adoptopenjdk/jdk-#{version.before_comma}+#{version.after_comma}`. Essentially it's a workaround so that we don't have to use the default structure generated by brew

2018-10-05 08:49 UTC, gdams commented on Casks/adoptopenjdk.rb
> +    system_command '/usr/libexec/PlistBuddy',
If we need to include the plist in the tarball then we might have to do that anyway.

2018-10-05 08:50 UTC, gdams commented on Casks/adoptopenjdk.rb
> +    system_command '/bin/rm',
I'll see if I can get things to work without it.

2018-10-05 08:51 UTC, commitay commented on Casks/adoptopenjdk.rb
> +    system_command '/bin/rm',
The [`java`](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/java.rb) cask is an example of how to handle moving/renaming.

2018-10-05 08:53 UTC, gdams commented on Casks/adoptopenjdk.rb
> +    system_command '/bin/rm',
yup removed that

2018-10-05 08:53 UTC, gdams commented on Casks/adoptopenjdk.rb
> +    system_command '/bin/rm',
removed

2018-10-05 08:55 UTC, commitay commented on Casks/adoptopenjdk.rb
> +                   args: ['-s', '--', "/usr/local/Caskroom/adoptopenjdk/#{version}/jdk-#{version.before_comma}+#{version.after_comma}",
`/usr/local/Caskroom/adoptopenjdk/#{version}` can be replaced with `staged_path`

2018-10-05 08:58 UTC, commitay commented
Is the intention to make casks for the formulae in https://github.com/AdoptOpenJDK/homebrew-openjdk and deprecate the tap?

2018-10-05 09:01 UTC, gdams commented
> Is the intention to make casks for the formulae in https://github.com/AdoptOpenJDK/homebrew-openjdk and deprecate the tap?

@commitay that is correct

2018-10-05 11:38 UTC, gibfahn commented
> > Is the intention to make casks for the formulae in [AdoptOpenJDK/homebrew-openjdk](https://github.com/AdoptOpenJDK/homebrew-openjdk) and deprecate the tap?
> 
> @commitay that is correct

Why the change from formula to cask? (https://github.com/AdoptOpenJDK/homebrew-openjdk/issues/4#issuecomment-376994448)

2018-10-05 11:41 UTC, commitay commented
@gibfahn Feel free to discuss that elsewhere, not in this PR.

2018-10-05 22:41 UTC, gdams commented
@commitay updated PTAL

2018-10-06 00:44 UTC, commitay commented on Casks/adoptopenjdk.rb
> +    system_command '/bin/mkdir',
Using `mkdir` and `ln` for a reason or can we just use `mv`?

We're trying to keep a consistent style for these types of casks.

2018-10-06 00:44 UTC, commitay commented on Casks/adoptopenjdk.rb
> +  # github.com was verified as official when first introduced to the cask
`# github.com/AdoptOpenJDK`

2018-10-06 00:44 UTC, commitay commented on Casks/adoptopenjdk.rb
> +    system_command '/usr/libexec/PlistBuddy',
Will these plist commands be fixed in future releases?

2018-10-06 10:28 UTC, gdams commented
@commitay updated PTAL, I've essentially copied the layout of the Java.rb cask and then added my plist commands. I've noticed that the Azul cask actually needs to use the plistbuddy commands as well.

2018-10-06 11:14 UTC, gdams commented
@commitay I'm just playing around with cutting a second release that might not need all of the plistbuddy commands. I'll let you know so please don't merge yet

2018-10-06 16:58 UTC, gdams commented
@commitay updated PTAL, I've managed to remove one of the plistbuddy commands but I'm afraid that the rest have to remain there to overwrite the Oracle defaults.

2018-10-06 19:05 UTC, breun commented
@gdams I'm not very familiar with brew casks, but I plan on adding AdoptOpenJDK to MacPorts and I see this cask installs into `/Library/Java/JavaVirtualMachines/adoptopenjdk-11.28.jdk`. Does Homebrew support having multiple versions of AdoptOpenJDK 11.y.z installed simultaneously? If not and the idea is that 11.0.1 updates 11, I would suggest installing into a directory that only contains the major version, like `/Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk`, so that when a new AdoptOpenJDK 11.y.z is released this will be installed into the same directory as the previous one and users don't need to update the JDK 11 location in their IDE. What do you think?

2018-10-06 19:27 UTC, breun commented
@gdams Ok great, I'll mirror that in MacPorts as well then.

I also see a few link and plist commands? Are those still necessary after https://blog.adoptopenjdk.net/2018/10/macos-binary-changes ?

2018-10-06 19:29 UTC, gdams commented
@breun yes they are. Let's continue to discuss this over at Adopt so that we don't clutter up this PR :)

2018-10-06 23:20 UTC, commitay approved these changes

2018-10-07 00:15 UTC, commitay commented on Casks/adoptopenjdk.rb
> +                   args: ['-c', "Set :JavaVM:JVMPlatformVersion #{version.before_comma}.#{version.after_comma}", "/Library/Java/JavaVirtualMachines/adoptopenjdk-#{version.before_comma}.jdk/Contents/I
Just double checking before merging, is `#{version.before_comma}.#{version.after_comma}` intended here?
```
		<key>JVMPlatformVersion</key>
		<string>11.28</string>
```

The next release would be displayed as, e.g. `11.0.1.35`?

2018-10-07 10:13 UTC, gdams commented on Casks/adoptopenjdk.rb
> +                   args: ['-c', "Set :JavaVM:JVMPlatformVersion #{version.before_comma}.#{version.after_comma}", "/Library/Java/JavaVirtualMachines/adoptopenjdk-#{version.before_comma}.jdk/Contents/I
yes this is intended, with a bit of luck I can remove these plist commands in the next release anyway

2018-10-07 10:18 UTC, merged

2018-10-07 10:18 UTC, commitay commented
🚢 Thanks again @gdams!

2018-10-08 22:45 UTC, rmartin7c commented
Any plans for support for OpenJDK 8/9/10?

2018-10-08 22:45 UTC, rmartin7c commented
@gdams Any plans for support for OpenJDK 8/9/10?

2018-10-09 07:45 UTC, gdams commented
@rmartin7c, I’ve got a PR in cask versions for 9 and will shortly be adding 10. JDK8 will be PR’d into this repo along with JDK11 as we still fully support it

2018-10-09 07:46 UTC, commitay commented
The JDK 8 should go in versions as well along with the other JDK 8 casks: `zulu8` and `java8`.

2018-10-09 14:10 UTC, rmartin7c commented
@gdams that's awesome, thanks. Trying to plot a path off of Oracle JDK 8 SE for my department's MacBooks, and this will be a huge help. Any idea on timeframe? Can I help test it?

2018-10-11 15:39 UTC, karianna commented
We will be releasing the next 8 probably tomorrow or on Monday

2018-10-16 18:59 UTC, gdams commented
@rmartin7c 8u PR [here](https://github.com/Homebrew/homebrew-cask-versions/pull/6415)