libreoffice-language-pack: open LibreOffice once
Homebrew/homebrew-cask pull request #52893
Opened 2018-10-05 15:07 UTC by amyspark

After making all changes to the cask:

- [X] `brew cask audit --download {{cask_file}}` is error-free.
- [X] `brew cask style --fix {{cask_file}}` reports no offenses.
- [X] The commit message includes the cask’s name and version.
- [X] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [ ] Named the cask according to the [token reference].
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked there are no [open pull requests] for the same cask.
- [ ] Checked the cask was not [already refused].
- [ ] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

--

LibreOffice Language Pack, when manually executed, runs LibreOffice at least once (using AppleScript) before inserting the language files. This is to trigger Gatekeeper and thus cheat the code signature assessment.

This pull request adds this step to the `preflight` block.

Fixes #52758 , fixes #52883 .

(source for the fix: `Contents/osx_install.applescript` inside the Cask's DMG)

2018-10-05 21:14 UTC, vitorgalvao requested changes
Lets just add the caveat. Adding the AppleScript is too much, and HBC should never trigger GUIs, especially one as taxing as LibreOffice.

2018-10-05 21:21 UTC, amyspark commented
I understand @vitorgalvao. But since this step is essential for LibreOffice to work out of the box (TDF even adds it in their own executable), I'd like to get a consensus on this. 
Pinging @Homebrew/cask.

2018-10-05 23:46 UTC, commitay commented
> Adding the AppleScript is too much

👍 

> and HBC should never trigger GUIs

👍 

> I’d rather remove the auto-installation (which is a non-standard hacky method anyway) and change the cask to `installer :manual`.

👍

2018-10-06 10:59 UTC, tiiiecherle commented
I know you guys come across a lot of issues and have standards to solve them, but just from a user and automation point of view adding the applescript seems the best way to implement. As using the homebrew-cask install one of the most things I love about it is the automation. And if there is a way to do the install automatically without breaking downsides I (and I guess other users) would love to see a most effortless install as possible. For me as an example I would have to explain to everyone in the office what to do and why instead of just installing the cask.

Would be nice to have see the most automated version possible. Thanks a lot for all your work. I really do like this project. Have a nice weekend together ;)

2018-10-06 12:11 UTC, vitorgalvao commented
> but just from a user and automation point of view adding the applescript seems the best way to implement.

Unfortunately, that doesn’t consider the users who don’t want a GUI to spring up when installing, especially one that’s slow like LibreOffice.

2018-10-06 12:46 UTC, tiiiecherle commented
I am pretty sure there is no "real" popup of a window when install the language pack manually. I will try and report back in a few minutes...

2018-10-06 12:59 UTC, tiiiecherle commented
I just downloaded the latest libreoffice and language pack from the offical website. Then I dragged the LibreOffice.app to /Applications/LibreOffice.app and unmounted the .dmg.
Afterwards I mounted the Language Pack installer and double clicked it. You are right, LibreOffice opens, but only for a very short time, not really noticable and is quit really fast before showing the startup gui. Then then langpack installs and reports success.

The only thing is that libreoffice asks for permission to open on first launch due to gatekeeper. This could be avoided by exporting the quarantine data, deleting the xattr, open Libreoffice and reimport the quarantine afterwards like this:
```
xattr -p com.apple.quarantine "/Applications/LibreOffice.app" > /tmp/quarantine_libreoffice.xattr
xattr -d com.apple.quarantine "/Applications/LibreOffice.app"
INSTALL LANGUAGE PACK HERE
xattr -w com.apple.quarantine `cat "/tmp/quarantine_libreoffice.xattr"` "/Applications/LibreOffice.app"

```

2018-10-06 13:28 UTC, tiiiecherle commented
I tried that, unfortunately restoring the com.apple.quarantine xattr does seem to break libreoffice again after the process completes. So it would still be possible with the applescriop, the only thing a user would have to do is hit one button to allow libreoffice to be opened, the rest could be automated.

2018-10-06 16:02 UTC, amyspark commented
> I tried that, unfortunately restoring the com.apple.quarantine xattr does seem to break libreoffice again after the process completes. So it would still be possible with the applescriop, the only thing a user would have to do is hit one button to allow libreoffice to be opened, the rest could be automated without long waiting and without seeing any libreoffice gui.

What you actually want is to toggle the "opened" bit in `com.apple.quarantine` - but doing that without updating the security policy database is... prone to errors 😉

2018-10-07 23:18 UTC, commitay commented on Casks/libreoffice-language-pack.rb
>      #{token} assumes LibreOffice is installed in '#{appdir}'. If it is not, you’ll need to run '#{staged_path}/LibreOffice Language Pack.app' manually.
The `caveat` isn't needed now with the switch to `installer manual`

2018-10-07 23:34 UTC, commitay commented
```
audit for libreoffice-language-pack: warning
 - installer and pkg stanzas require an uninstall stanza
```
Need to add a fake `uninstall` to make `audit` happy.
https://github.com/Homebrew/homebrew-cask/blob/959f4d949808c895fbc507e097936779b314a208/Casks/google-cloud-sdk.rb#L19

2018-10-09 17:49 UTC, vitorgalvao approved these changes

2018-10-09 17:49 UTC, merged