Update daylite to 6.5.5
Homebrew/homebrew-cask pull request #53064
Opened 2018-10-07 18:21 UTC by core-code

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

2018-10-07 18:35 UTC, reitermarkus requested changes

2018-10-07 18:35 UTC, reitermarkus commented on Casks/daylite.rb
> +  if MacOS.version <= :mojave
`<= :high_sierra`

2018-10-07 18:42 UTC, core-code commented on Casks/daylite.rb
> +  if MacOS.version <= :mojave
thanks ;)

2018-10-07 21:54 UTC, core-code commented
not sure about travis failure

2018-10-13 15:46 UTC, core-code commented on Casks/daylite.rb
> +  if MacOS.version <= :mojave
@reitermarkus i think i've addressed the changes you've requested. also, i don't understand the travis failure as those two are in uninstall launchctl. any ideas? thanks

2018-10-18 09:13 UTC, core-code commented
can someone have a look at this?

2018-11-02 12:02 UTC, core-code commented
@reitermarkus i've updated to 6.6.2. can you have a look?

2018-11-02 13:11 UTC, reitermarkus commented
This needs a rebase.

2018-11-02 17:28 UTC, closed without merging