Add ScreenTray.app v1.1.0
Homebrew/homebrew-cask pull request #53091
Opened 2018-10-08 20:38 UTC by mwean

https://screentray.com/

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

2018-10-09 14:03 UTC, vitorgalvao requested changes

2018-10-09 14:03 UTC, vitorgalvao commented on Casks/screentray.rb
> +  url 'https://screentray.com/download'
`https://github.com/DSnopov/screentray-distribution/releases/download/v1.1.0/screen-tray-1.1.0-mac.zip`

2018-10-15 00:37 UTC, mwean commented
@vitorgalvao I updated the url

2018-11-02 13:42 UTC, reitermarkus commented
Checksum has changed.

2018-11-02 17:09 UTC, mwean commented
I just downloaded it from the site, and the checksum is the same.

2018-11-06 03:18 UTC, reitermarkus commented
> Should I update the URL or the checksum?

Let's use the DMG URL then.

2018-11-06 06:15 UTC, mwean commented
Done

2018-11-14 20:52 UTC, merged