Fixes #39739 - document 'unofficial' app naming conventions.
Homebrew/homebrew-cask pull request #53222
Opened 2018-10-11 13:36 UTC by russtaylor

Documentation changes only. I'm hoping this description is clear enough to fix #39739. 

If it's not clear or this should be documented elsewhere, I'm happy to adjust it!

2018-10-11 19:56 UTC, vitorgalvao requested changes

2018-10-11 19:56 UTC, vitorgalvao commented on doc/cask_language_reference/token_reference.md
> +In most cases, the prefix should be the vendor's name. For example, `google-play-music-desktop-player` is unofficial, so [its cask was renamed to `marshallofsound-google-play-music-player`](https://g
This is already covered by the link above ([a prefix must be added](../development/adding_a_cask.md#forks-and-apps-with-conflicting-names)). It can be removed.

2018-10-11 19:56 UTC, vitorgalvao commented on doc/cask_language_reference/token_reference.md
> +In cases that the prefix is ambiguous and would make the app appear official, the `unofficial-` prefix may be used.
It’s supposed to be a suffix, not a prefix.

2018-10-11 19:57 UTC, vitorgalvao commented
Thank you for opening this.

2018-10-11 20:33 UTC, russtaylor commented
Thanks for the feedback! Changes made.

2018-10-11 20:53 UTC, vitorgalvao approved these changes

2018-10-12 08:51 UTC, commitay commented
Thanks @russtaylor!

2018-10-12 08:51 UTC, merged