Add Ondesoft AudioBook Converter.app v3.2.0
Homebrew/homebrew-cask pull request #53658
Opened 2018-10-15 21:01 UTC by alissa-huskey

Added Ondesoft AudioBook Converter, a paid app to convert Audible AA/AAX audiobooks to MP3/M4A

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

2018-11-02 13:45 UTC, reitermarkus requested changes

2018-11-02 13:45 UTC, reitermarkus commented on Casks/ondesoft-audiobook-converter.rb
> +  version '3.2.0'
The URL doesn't contain a version, so this should be `:latest`.

2018-11-09 09:03 UTC, tiiiecherle commented
The app was updated to 4.2.0 in the meantime. I would like to see the version included instead of latest, but I don`t know if this is going to work with homebrew guidelines. Would be nice to see this updated and merged. Thanks

2018-12-10 14:26 UTC, vitorgalvao approved these changes

2018-12-11 01:07 UTC, merged