Update itch to 25.0.0
Homebrew/homebrew-cask pull request #53685
Opened 2018-10-16 16:02 UTC by core-code

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

2018-10-18 09:48 UTC, core-code commented
i think the installer runs unattended anyway so maybe better use that

`
env: /usr/local/Caskroom/itch/25.0.0/Install itch.app: Permission denied
`

anyone know why this happens?

2018-10-20 17:04 UTC, vitorgalvao commented
> anyone know why this happens?

Because it’s not a script. You’re calling the `app` bundle, which is a directory.

2018-10-20 20:09 UTC, vitorgalvao commented on Casks/itch.rb
> +  installer script: 'Install itch.app/Contents/MacOS/itch-setup'
Does this open a GUI?

2018-10-20 20:30 UTC, core-code commented on Casks/itch.rb
> +  installer script: 'Install itch.app/Contents/MacOS/itch-setup'
yes it does but as far as i remember the installation does run unattended

2018-10-21 10:01 UTC, core-code commented on Casks/itch.rb
> +  installer script: 'Install itch.app/Contents/MacOS/itch-setup'
1.) the sha has changed 3 times since i first sent it, so i've changed to version latest
2.) i've verified the installation works locally

2018-10-21 16:43 UTC, vitorgalvao requested changes

2018-10-21 16:43 UTC, vitorgalvao commented on Casks/itch.rb
> +  version :latest
Needs to stay versioned and have a `sha256`, because it has an `appcast`.

2018-10-21 17:05 UTC, merged

2018-11-02 12:57 UTC, core-code commented
just some info so that it isn't lost
the installer checks version by retrieving 'https://broth.itch.ovh/itch/darwin-amd64/LATEST'

if we want to bypass the installer and install directly we could do so by retrieving
'https://broth.itch.ovh/itch/darwin-amd64/#{version}/archive-default'