Update gobdokumente to 1.3.1
Homebrew/homebrew-cask pull request #53935
Opened 2018-10-21 08:48 UTC by herrriehm

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

added alternative name, depends_on macos

2018-10-21 16:40 UTC, vitorgalvao requested changes

2018-10-21 16:40 UTC, vitorgalvao commented on Casks/gobdokumente.rb
> +  name 'GoBDocuments'
This is not a place for common misspellings. Is the app caslled this anywhere?

2018-10-22 07:07 UTC, herrriehm commented on Casks/gobdokumente.rb
> +  name 'GoBDocuments'
Thanks for asking. „GoBDocuments“ is not a spelling mistake, but merely the official English name of the program. You can find (German) „GoBDokumente“ on the [German website](https://gobdokumente.de/deutsch.html), and (English) „GoBDocuments“ on the [English website](https://gobdokumente.de/index.html).
Although obviously the English website is preferred, I propose to stay with the German name „GoBDokumente“ as appcast and url also say so.

2018-10-23 02:44 UTC, vitorgalvao commented on Casks/gobdokumente.rb
> +  depends_on macos: '>= :el_capitan'
Always release names, never numbers.

2018-10-23 02:44 UTC, vitorgalvao commented on Casks/gobdokumente.rb
> +  depends_on macos: '>= :el_capitan'
Always release names, never numbers.

2018-10-23 02:45 UTC, merged