Fix tableplus 1.0.146 SHA-256
Homebrew/homebrew-cask pull request #54214
Opened 2018-10-29 13:19 UTC by SeanSith

Per https://tableplus.io/blog/2017/02/changelogs.html the SHA-256 in
the existing cask is incorrect. Also fails to pass the check on download.

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

2018-10-29 17:01 UTC, peterjc-123 commented
Share side request about SHA-256

2018-10-29 18:34 UTC, SeanSith commented
I'm not sure what's being asked above, but just in case we're also looking for a VirusTotal scan: https://www.virustotal.com/#/file/956e92f651f93e2fa9a7cbdf36eec835bc55d887dacdfb6cf42fd009a7f68c00/detection

It does not contain a signature section, unfortunately.

2018-10-30 15:21 UTC, vitorgalvao commented
> I'm not sure what's being asked above

I’m not either. Not sure if that’s a spam account.

@peterjc-123 This is the second post of yours I’d had to delete. If there’s a third, you’ll be banned from Homebrew.

2018-10-30 15:21 UTC, vitorgalvao requested changes
The VirusTotal verification ins’t enough because there’s no signing info. We need developer confirmation, as per the instructions.

2018-10-30 17:30 UTC, SeanSith commented
@huyphams Any chance we could get you over here to verify that the SHA checksum mentioned in the commit I made above is correct based on your blog post?

2018-10-30 17:42 UTC, huyphams commented
Thanks @SeanSith I have accidentally updated the wrong version of TablePlus (which is for my partner Setapp), but I realize and re-upload it, sorry because the confusing :(
The changes log and the SHA can always be found here: 
https://tableplus.com/osx/changelog

2018-10-31 00:48 UTC, vitorgalvao commented
Thank you for the confirmation, @SeanSith.

2018-10-31 00:48 UTC, merged