Update Dozer V2.1
Homebrew/homebrew-cask pull request #54250
Opened 2018-10-30 20:56 UTC by Mortennn

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

2018-10-30 21:06 UTC, commitay requested changes

2018-10-30 21:06 UTC, commitay commented on Casks/dozer.rb
> +  appcast 'https://raw.githubusercontent.com/Mortennn/Dozer/master/appcast.xml'
Please use `https://github.com/Mortennn/Dozer/releases.atom`

2018-10-30 21:06 UTC, commitay commented on Casks/dozer.rb
> +  auto_updates :yes
`auto_updates :yes` isn't valid, please use `auto_updates true`

2018-10-30 21:17 UTC, commitay commented on Casks/dozer.rb
> +  appcast 'https://raw.githubusercontent.com/Mortennn/Dozer/master/appcast.xml'
We prefer to use the GitHub releases feed.

2018-10-31 07:08 UTC, merged

2018-10-31 15:37 UTC, Mortennn commented
I still can't install Dozer with `brew cask install dozer`.
When will it be available?