Add SimpleDiagrams4.app v4.0.28
Homebrew/homebrew-cask pull request #54545
Opened 2018-11-06 07:21 UTC by SangatsuUsagi

After making all changes to the cask:

- [X] `brew cask audit --download {{cask_file}}` is error-free.
- [X] `brew cask style --fix {{cask_file}}` reports no offenses.
- [X] The commit message includes the cask’s name and version.
- [X] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [X] Named the cask according to the [token reference].
- [X] `brew cask install {{cask_file}}` worked successfully.
- [X] `brew cask uninstall {{cask_file}}` worked successfully.
- [X] Checked there are no [open pull requests] for the same cask.
- [X] Checked the cask was not [already refused].
- [X] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

2018-11-07 20:51 UTC, reitermarkus requested changes

2018-11-07 20:51 UTC, reitermarkus commented on Casks/simplediagrams.rb
> +  url 'https://www.simplediagrams.com/download/simplediagrams_installer_4_0_28.dmg'
Interpolate the version here with `version.dots_to_underscores`.

2018-11-07 20:51 UTC, reitermarkus commented on Casks/simplediagrams.rb
> +  app 'SimpleDiagrams4.app'
Also interpolate the version here with `version.major`.

2018-11-08 04:57 UTC, SangatsuUsagi commented on Casks/simplediagrams.rb
> +  app 'SimpleDiagrams4.app'
I’ve fixed url and app and sent new pr.

2018-11-18 18:50 UTC, merged