Add SubEthaEdit.app v5
Homebrew/homebrew-cask pull request #55484
Opened 2018-11-28 19:15 UTC by mystygage

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

2018-11-28 19:19 UTC, mystygage commented
As SubEthaEdit is no longer MAS-only there should be a cask again

2018-12-03 18:30 UTC, vitorgalvao requested changes

2018-12-03 18:30 UTC, vitorgalvao commented on Casks/subethaedit.rb
> +  version :latest
Add a `version`.

2018-12-03 18:30 UTC, vitorgalvao commented on Casks/subethaedit.rb
> +  sha256 :no_check
Add a `sha256`.

2018-12-03 19:02 UTC, mystygage commented
Atm the developers don’t provide a versioned download URL, so I used the `advancedcolors` template from https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md for unversioned downloads.
Is it possible to use a `sha256` and no version?

2018-12-04 15:09 UTC, mystygage commented
Sorry, I didn't see yesterday that a commit with an appcast was added by @victorpopkov to my pull request.

I must admit that I'm not familiar with appcasts etc. I just read this comment by @monkeydom 
> I'm fine with it leaching the https://subethaedit.net/SubEthaEdit.zip which always will turn to the current version and have Sparkle in it for self updates.

in subethaedit/SubEthaEdit#22 and thought that's ok.

Should we ask @monkeydom if they can provide a versioned zip file?

2018-12-04 15:20 UTC, monkeydom commented
The AppCast with dsa signature is at https://subethaedit.net/appcast.xml - I can make sure old binaries will stick around and don't change.

2018-12-04 15:49 UTC, mystygage commented on Casks/subethaedit.rb
> +  version :latest
Version added 5fcc10f78b14a4832b480d8246b8bf6758369636

2018-12-04 15:49 UTC, mystygage commented on Casks/subethaedit.rb
> +  sha256 :no_check
sha256 added 5fcc10f78b14a4832b480d8246b8bf6758369636

2018-12-04 16:01 UTC, mystygage commented
I updated the pull request. By mistake I first squashed the commits and realized afterwards the contributing guidelines, but now everything should be ok again.

2018-12-04 16:02 UTC, victorpopkov requested changes

2018-12-04 16:02 UTC, victorpopkov commented on Casks/subethaedit.rb
> +  url 'https://subethaedit.net/Releases/SubEthaEdit-5.0rc1.zip'
You can use string interpolation here to reuse the version.

In this case, if you choose to stick with the `5.0rc1` as a `version` stanza value:

```suggestion
  url "https://subethaedit.net/Releases/SubEthaEdit-#{version}.zip"
```

2018-12-04 16:21 UTC, monkeydom commented on Casks/subethaedit.rb
> +  url 'https://subethaedit.net/Releases/SubEthaEdit-5.0rc1.zip'
updated the feed and binary so this can work now. (e.g. put SubEthaEdit-5.0.zip in the appcast, and made the binary accessible as such too. The app never showed the rc1 anyways, so it is a pre-release artifact that it was in there)

2018-12-04 22:51 UTC, mystygage commented on Casks/subethaedit.rb
> +  url 'https://subethaedit.net/Releases/SubEthaEdit-5.0rc1.zip'
Thanks for the hint. I updated the PR with `version` in url.

2018-12-05 11:48 UTC, victorpopkov approved these changes

2018-12-06 14:35 UTC, merged