Update cocktail.rb for v12.1
Homebrew/homebrew-cask pull request #55606
Opened 2018-12-01 22:16 UTC by drbyte

Cocktail 12.1 release by Maintain.se

Unchecked boxes below are because:
I haven't done a checkout of this project locally. 
However, I did test that the zip filename is correct and obtained the sha256 value from it. 

- [ ] `brew cask audit --download {{cask_file}}` is error-free.
- [ ] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

2018-12-02 23:59 UTC, ran-dall requested changes
```ruby
   elsif MacOS.version == :high_sierra
     version '11.6.3'
     sha256 '6a00bae70a5befa7fb9467c1320e8818939e5f074deadd70177021fbf4694b07'
 
    url "https://www.maintain.se/downloads/sparkle/highsierra/Cocktail_#{version}.zip"
    appcast 'https://www.maintain.se/downloads/sparkle/highsierra/highsierra.xml'
  else
```

@drbyte 👉 The High Sierra version needs to be updated.👇

```ruby
elsif MacOS.version == :high_sierra
     version '11.6.4'
     sha256 '1e606fd287fdb4adb7e64d345dfd007458b216ed06694abf54f1c799037986be'
 
    url "https://www.maintain.se/downloads/sparkle/highsierra/Cocktail_#{version}.zip"
    appcast 'https://www.maintain.se/downloads/sparkle/highsierra/highsierra.xml')
```

2018-12-03 00:03 UTC, ran-dall commented
@drbyte The Mojave cask seems to be correct. Updating the cask with my suggestion 👆 will fix the Travis issue.

2018-12-03 00:44 UTC, drbyte commented
@ran-dall Done. 
You're right, and I should have seen that Travis error. I know better!  :(

2018-12-03 01:09 UTC, ran-dall approved these changes

2018-12-03 15:45 UTC, merged