Update Miniconda3 to 4.5.11 from tag 'latest' and fix caveats
Homebrew/homebrew-cask pull request #56823
Opened 2018-12-31 17:09 UTC by niheaven

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).

- The latest Miniconda version is 4.5.11, and Homepage is moved to [here](https://conda.io/miniconda.html), download url's domain is moved from continuum.io to anaconda.com on Homepage.
- Since conda 4.4 (the latest version is 4.5.11), it is not recommanded to modify PATH, so the caveats are fixed accordingly.

2018-12-31 17:27 UTC, vitorgalvao requested changes
`caveats` are too long and have too much [non-installation-related instructions](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/caveats.md#caveats).

2019-01-01 05:36 UTC, niheaven commented
Fix `caveats`, only profile modification left. Delete instruction of modifying wrong PATH.

2019-01-02 17:59 UTC, vitorgalvao commented
Remaining caveats were not installation-related, but usage-related, so removed as well.

2019-01-02 18:01 UTC, vitorgalvao approved these changes

2019-01-02 19:16 UTC, merged