Update mathpix-snipping-tool to latest
Homebrew/homebrew-cask pull request #57124
Opened 2019-01-07 09:32 UTC by jinntrance

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

2019-01-08 11:08 UTC, reitermarkus requested changes

2019-01-08 11:08 UTC, reitermarkus commented on Casks/mathpix-snipping-tool.rb
> +  auto_updates false
Remove this line, `false` is the default.

2019-01-08 11:09 UTC, reitermarkus commented
1.3.1 still seems to be the latest release, so why remove the appcast?

2019-01-10 05:14 UTC, jinntrance commented
The download url from the official site has changed, and version is no longer included.

2019-01-10 14:46 UTC, vitorgalvao commented
1. The `appcast` is a Sparkle appcast, still present in the app. I doubt this no longer auto updates.
2. Maybe the URL on the website has changed, but the appcast (which is clearly official) still has versioned links, and the unversioned link downloads the same version.

Everything in this cask appears valid as is.

2019-01-20 20:12 UTC, zbeekman commented on Casks/mathpix-snipping-tool.rb
> +  auto_updates false
LGTM (now)

2019-01-20 20:13 UTC, zbeekman commented
I think this can ship, no?

2019-01-20 23:43 UTC, vitorgalvao commented
@zbeekman Not really, no. None of the concerns were addressed. As it is, this is closer to being closed than being merged.

2019-01-20 23:47 UTC, zbeekman commented
> Everything in this cask appears valid as is.

Sorry, I completely misunderstood your comment.

2019-01-20 23:58 UTC, closed without merging