Azure pipelines for CI instead of Travis #56815
Homebrew/homebrew-cask pull request #57156
Opened 2019-01-08 04:10 UTC by shikhar-scs

Since this is unrelated to any of the cask files, none of the checkboxes fit here.
Refer #56815

2019-01-08 04:10 UTC, shikhar-scs commented
@reitermarkus I ran a build today. It gave a green tick (a successful build) on the Azure portal.
<img width="1135" alt="screenshot 2019-01-08 at 9 35 16 am" src="https://user-images.githubusercontent.com/25258877/50809320-d2eedd80-1328-11e9-8acd-b8a7acfee19c.png">


However, there was also this error at the end of the build report 
<img width="765" alt="screenshot 2019-01-08 at 9 33 21 am" src="https://user-images.githubusercontent.com/25258877/50809331-e4d08080-1328-11e9-876e-8e787240f78f.png">

I then ran the `brew cask ci` command after getting in the `HOMEBREW_TAP_DIRECTORY` and then did the `rm -rf`. Didnt work.

Also, the changes I'm making in the brewcask-ci.rb file isnt reflecting in the build. I tried using some `puts` statements to debug, also tried removing a few lines of code and stuff, however it still makes the build as if no changes were made, throwing the same errors again and again.

2019-01-08 11:53 UTC, reitermarkus commented
What exactly do you mean with `HOMEBREW_TAP_DIRECTORY`? The command expects you to be in e.g. `/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask`.

2019-01-08 11:54 UTC, reitermarkus commented on azure-pipelines.yml
> +        HOMEBREW_TAP_DIR="/usr/local/Homebrew/Library/Taps/#{tap}"
`#{tap}` is neither set nor is it Bash syntax.

2019-01-08 12:57 UTC, reitermarkus commented on azure-pipelines.yml
> +        HOMEBREW_COVERALLS_REPO_TOKEN: $(coveralls.homebrewBrewApiToken)
We don't need this for casks.

2019-01-08 13:30 UTC, shikhar-scs commented on azure-pipelines.yml
> +        HOMEBREW_COVERALLS_REPO_TOKEN: $(coveralls.homebrewBrewApiToken)
Cool. I'll remove this.

2019-01-08 13:30 UTC, shikhar-scs commented on azure-pipelines.yml
> +        HOMEBREW_TAP_DIR="/usr/local/Homebrew/Library/Taps/#{tap}"
True. I noticed that now. I'll correct it too.

2019-01-08 14:00 UTC, shikhar-scs commented on azure-pipelines.yml
> +        HOMEBREW_COVERALLS_REPO_TOKEN: $(coveralls.homebrewBrewApiToken)
@reitermarkus I made the changes, and now I'm getting this. Can it be related to Travis ? 
<img width="1011" alt="screenshot 2019-01-08 at 7 25 26 pm" src="https://user-images.githubusercontent.com/25258877/50834900-3ace1400-137b-11e9-9270-a52662768b00.png">

I checked up https://github.com/Homebrew/homebrew-core/issues/31840 and it was mentioned that `.to_str` is an upstream issue. 

Also, how could I force the build to run the `brewcask-ci.rb` file that I'm pushing and not the one in the system. This is essential to allow me to debug.

2019-01-08 14:47 UTC, reitermarkus commented
@shikhar-scs, the next commit should actually run on our Azure pipeline, which will probably solve the issue of it not using the proper `brewcask-ci.rb`.

2019-01-09 16:11 UTC, vitorgalvao requested changes

2019-01-09 16:11 UTC, vitorgalvao commented on azure-pipelines.yml
> +      displayName: Run brew cask-test-bot
It has a “no newline at end of file” warning. Those are [actually meaningful](http://unix.stackexchange.com/a/18789).

2019-01-09 16:48 UTC, shikhar-scs commented on azure-pipelines.yml
> +      displayName: Run brew cask-test-bot
@vitorgalvao I had tried the same but still got the error
<img width="1011" alt="screenshot 2019-01-08 at 7 25 26 pm" src="https://user-images.githubusercontent.com/25258877/50834900-3ace1400-137b-11e9-9270-a52662768b00.png">

2019-01-10 00:00 UTC, reitermarkus commented
You need to do the same thing the Travis script does: `rsync` the current repo to the correct tap directory.

2019-01-10 03:08 UTC, shikhar-scs commented
@reitermarkus I did the changes. Thanks a lot for your help. Its working now. Please have a look at the azure build.

2019-01-10 14:33 UTC, vitorgalvao commented on azure-pipelines.yml
> +        rsync -az --delete "${HOMEBREW_TAP_DIR}/"
```suggestion
        rsync --archive --compress --delete "${HOMEBREW_TAP_DIR}"
```

Always use long flags, as they are clearer.

Also, is the trailing slash required?

2019-01-10 14:33 UTC, vitorgalvao commented on azure-pipelines.yml
> +        HOMEBREW_TAP_DIR="/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask"
```suggestion
        HOMEBREW_TAP_DIR='/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask'
```

Single quotes when interpolation isn’t needed.

2019-01-10 14:35 UTC, vitorgalvao commented on azure-pipelines.yml
> +        export TRAVIS_BUILD_DIR="${HOMEBREW_TAP_DIR}"
Since Travis is no longer the CI, this variable should be renamed.

2019-01-10 14:36 UTC, vitorgalvao commented on azure-pipelines.yml
> +        builtin cd "${TRAVIS_BUILD_DIR}"
Is `builtin` really necessary?

2019-01-10 14:37 UTC, shikhar-scs commented on azure-pipelines.yml
> +        builtin cd "${TRAVIS_BUILD_DIR}"
I tried to replicate the code written in the `travois.yml` file. That's it. I'll remove the Travis Specific Code.

2019-01-10 14:39 UTC, vitorgalvao commented on azure-pipelines.yml
> +      displayName: Run brew cask-test-bot
Shouldn’t this start with `-` as well? As in:

```suggestion
      - displayName: Run brew cask-test-bot
```

Also, it’s my understanding this is pretty much just a message. So shouldn’t we change this for something more descriptive and that looks less like an outright command?

2019-01-10 14:41 UTC, vitorgalvao commented on azure-pipelines.yml
> +        rsync -az --delete "${HOMEBREW_TAP_DIR}"
```suggestion
        rsync --archive --compress --delete "${HOMEBREW_TAP_DIR}"
```

Again, we should use long flags whenever they exist.

2019-01-10 14:41 UTC, vitorgalvao commented on azure-pipelines.yml
> +      displayName: Run brew cask-test-bot
Finally, having it at the top might be clear visually.

2019-01-10 14:42 UTC, shikhar-scs commented on azure-pipelines.yml
> +      displayName: Run brew cask-test-bot
> Shouldn’t this start with - as well?
[Not really](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=vsts&tabs=schema#tabpanel_8ugYiRH0yv-6_schema) it works like this too.

> Finally, having it at the top might be clear visually.

Sure.

2019-01-10 14:42 UTC, shikhar-scs commented on azure-pipelines.yml
> +        rsync -az --delete "${HOMEBREW_TAP_DIR}"
my fault sorry

2019-01-10 14:46 UTC, shikhar-scs commented on azure-pipelines.yml
> +        rsync -az --delete "${HOMEBREW_TAP_DIR}"
Its still bringing the same error :(

2019-01-10 14:49 UTC, vitorgalvao commented on azure-pipelines.yml
> +        rsync -az --delete "${HOMEBREW_TAP_DIR}"
> Its still bringing the same error :(

Note the changes I’m suggesting are not to fix the errors (that’s the area @reitermarkus), but to tidy everything up consistently.

2019-01-10 14:50 UTC, shikhar-scs commented on azure-pipelines.yml
> +        rsync -az --delete "${HOMEBREW_TAP_DIR}"
Oops. Sure. Thanks for the help. 👍

2019-01-10 15:41 UTC, reitermarkus requested changes

2019-01-10 15:41 UTC, reitermarkus commented on azure-pipelines.yml
> +    - bash: |
This also needs the other flags Travis uses, like `set -e`, so that any error results in a failure.

2019-01-10 15:41 UTC, reitermarkus commented on azure-pipelines.yml
> +        HOMEBREW_TAP_DIR='/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask'
This should be built from a variable. The current repo should be available from some environment variable provided by Azure.

2019-01-10 15:43 UTC, reitermarkus commented on azure-pipelines.yml
> +        export AZURE_BUILD_DIR="${HOMEBREW_TAP_DIR}"
Is this actually the variable name Azure uses initially? In the Travis case, this was only re-exported because it is actually a variable initially provided by Travis.

2019-01-10 19:51 UTC, shikhar-scs commented on azure-pipelines.yml
> +        HOMEBREW_TAP_DIR='/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask'
Oh. I'll look into that.

2019-01-10 19:52 UTC, shikhar-scs commented on azure-pipelines.yml
> +        export AZURE_BUILD_DIR="${HOMEBREW_TAP_DIR}"
I guess it does not.

2019-01-20 03:44 UTC, shikhar-scs commented
@reitermarkus . Sorry I was unavailable for a week, got back this weekend only. 😬 

> This should be built from a variable. The current repo should be available from some environment variable provided by Azure.

I looked this up and made them changes accordingly. Have a look at the current `azure-pipelines.yml` file.

However, I'm getting the same old error, that the command `brew cask ci` should be run from inside the tap directory. I double checked that we already were there using `ls` and everything but the error still persists. 
Here's the output of `ls`
<img width="848" alt="screenshot 2019-01-20 at 9 07 29 am" src="https://user-images.githubusercontent.com/25258877/51434995-657d6e00-1c93-11e9-822a-df94022d50dd.png">

2019-01-20 05:03 UTC, reitermarkus commented on azure-pipelines.yml
> +        rsync --archive --compress --delete $(Build.SourcesDirectory)
What is this supposed to do? It doesn't sync anywhere.

2019-01-20 07:57 UTC, shikhar-scs commented on azure-pipelines.yml
> +        rsync --archive --compress --delete $(Build.SourcesDirectory)
It was used in the `travis.yml` file, so I guess it does have some significance. Maybe, if not, we can remove it ?

2019-01-20 23:12 UTC, reitermarkus commented on azure-pipelines.yml
> +        rsync --archive --compress --delete $(Build.SourcesDirectory)
What I mean is, this is missing the target directory parameter, so it isn't doing anything.

2019-01-21 04:14 UTC, shikhar-scs commented on azure-pipelines.yml
> +        rsync --archive --compress --delete $(Build.SourcesDirectory)
Oh, Cool. But what about the `This command must be run from inside the Tap Directory` error ?

2019-01-21 08:51 UTC, reitermarkus commented on azure-pipelines.yml
> +        rsync --archive --compress --delete $(Build.SourcesDirectory)
What I mean to say is, this *should* be doing something, that is syncing the build directory into the tap directory, which is why the command is not running inside a tap directory.

2019-01-21 09:22 UTC, shikhar-scs commented on azure-pipelines.yml
> +        rsync --archive --compress --delete $(Build.SourcesDirectory)
Oh I get it. Correct. Let me look out for the same.

2019-01-21 09:38 UTC, reitermarkus commented on azure-pipelines.yml
> +        # Mirror the repo as a tap.
An advantage of syncing is that we can fix the CI script and it will be used when restarting failed builds.

2019-01-21 10:05 UTC, shikhar-scs commented on azure-pipelines.yml
> +        # Mirror the repo as a tap.
symlink isn't working. The error persists.
Also, a combo of rsync and symlink fails too.

2019-01-21 12:39 UTC, reitermarkus commented on azure-pipelines.yml
> +        # Mirror the repo as a tap.
You still aren't syncing into the tap directory.

2019-01-23 02:52 UTC, shikhar-scs commented on azure-pipelines.yml
> +        # Mirror the repo as a tap.
Then how do I fix that

2019-02-20 03:55 UTC, closed without merging