Add Trilium Notes.app v0.27.4
Homebrew/homebrew-cask pull request #57377
Opened 2019-01-12 03:55 UTC by Karunamon

After making all changes to the cask:

- [X] `brew cask audit --download {{cask_file}}` is error-free.
- [X] `brew cask style --fix {{cask_file}}` reports no offenses.
- [X] The commit message includes the cask’s name and version.
- [X] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [X] Named the cask according to the [token reference].
- [X] `brew cask install {{cask_file}}` worked successfully.
- [X] `brew cask uninstall {{cask_file}}` worked successfully.
- [X] Checked there are no [open pull requests] for the same cask.
- [X] Checked the cask was not [already refused].
- [X] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

----

Tasks done, first add to Brew Cask. Looks like all the boxes have been ticked, please be gentle :)

[Trilium Notes](https://github.com/zadam/trilium) is a hierarchical note taking application with focus on building large personal knowledge bases.

2019-01-12 16:13 UTC, vitorgalvao requested changes
In the future, please tick the box that allows maintainers to do edits directly, as it moves the process along faster.

2019-01-12 16:13 UTC, vitorgalvao commented on Casks/trilium-notes.rb
> +  app "trilium-mac-x64/Trilium\ Notes.app"
```ruby
app 'trilium-mac-x64/Trilium Notes.app'
```

2019-01-12 17:10 UTC, Karunamon commented on Casks/trilium-notes.rb
> +  app "trilium-mac-x64/Trilium\ Notes.app"
My bad. It appears both my ruby and github-fu has grown rusty. What's the preferred way to make that change, just add another commit to the PR?

2019-01-12 20:47 UTC, vitorgalvao commented on Casks/trilium-notes.rb
> +  app "trilium-mac-x64/Trilium\ Notes.app"
> just add another commit to the PR?

Yep.

2019-01-14 15:08 UTC, Karunamon commented on Casks/trilium-notes.rb
> +  app "trilium-mac-x64/Trilium\ Notes.app"
Alright, I've made a mess of this. I managed to blow away my source branch while trying to clean up some stuff, which means I can't add to this anymore. (Unless you're aware of a way to push directly into the PR without an associated branch).

Thinking it may be better to nuke this and I'll try again the right way.

2019-01-14 15:17 UTC, vitorgalvao commented on Casks/trilium-notes.rb
> +  app "trilium-mac-x64/Trilium\ Notes.app"
> Thinking it may be better to nuke this and I'll try again the right way.

Sure thing. Go ahead.

2019-01-14 15:17 UTC, closed without merging