Attempt to enable Azure Pipelines as a CI provider
Homebrew/homebrew-cask pull request #58044
Opened 2019-01-28 17:30 UTC by tommyang

I was following #57156 as I look forward to being able to use Azure Pipelines for Cask taps. 
I see that the activity on that PR has died down recently and thought I would give it a try. Apologies to @shikhar-scs if you are still working on it.

Here are the new changes:
- Updated `vmImage` version. 
- `set -o errexit` and `set -o pipefail` added to the bash script per comments from the previous PR. 
- `TAP_DIR` is set and serves as the rsync destination in the bash script. 
- Use `brew update-reset` on `Homebrew/brew` instead of doing `brew update` per suggestion from the previous PR. (Is this enough?)
- Created an Azure build pipeline _for my forked repo_ to test this. 
  - Note that in order to test with the modified `brewcask-ci.rb` in this PR on Azure, the bash script overwrites `Homebrew/homebrew-cask`'s shipping version. 

Here is where I am stuck:
I noticed that `brewcask-ci.rb` needs commit range info to work. On Travis, this info is provided by the `TRAVIS_COMMIT_RANGE` env variable. Since there is no Azure Pipelines equivalent, commit range info needs to be derived. 
I tried to copy [how homebrew-test-bot does it](https://github.com/Homebrew/homebrew-test-bot/blob/5cf61bcb03bb70ca657724a8d8db6571e5a25abb/cmd/brew-test-bot.rb#L413-L419) but it doesn't seem to work with my test PR tommyang/homebrew-cask#1. ~~[Azure Pipelines log](https://dev.azure.com/tommyang/homebrew-cask/_build/results?buildId=144) indicates that `SYSTEM_PULLREQUEST_TARGETBRANCH` and `BUILD_SOURCEVERSION` were not set.~~ Env variables are filtered. 

Not sure how far I can go from here as I am familiar with neither Ruby nor Azure Pipelines. But I thought I should share my findings.

2019-01-30 01:04 UTC, reitermarkus requested changes

2019-01-30 01:04 UTC, reitermarkus commented on cmd/brewcask-ci.rb
> +          @commit_range = @commit_range
`@commit_range = @commit_range` does nothing.

2019-01-30 01:04 UTC, reitermarkus commented on cmd/brewcask-ci.rb
> +          @commit_range = "#{current_commit_hash}...#{current_commit_hash}"
Move the `@commit_range =` in front of the `if` above.

```ruby
@commit_range = if
  ...
end
```

2019-01-30 01:06 UTC, reitermarkus commented on azure-pipelines.yml
> +        set -o pipefail
Also add `nounset`.

2019-01-30 01:09 UTC, reitermarkus commented on cmd/brewcask-ci.rb
> +        ).stdout.strip
Add a newline after this.

2019-02-07 16:49 UTC, reitermarkus requested changes

2019-02-07 16:49 UTC, reitermarkus commented on azure-pipelines.yml
> +        export HOMEBREW_NO_ENV_FILTERING=1
This should not be set, please revert to prefixing the variables with `HOMEBREW_`.

2019-02-07 16:49 UTC, reitermarkus commented on cmd/brewcask-ci.rb
> +        pr_url =
When would this be necessary if we already have `SYSTEM_PULLREQUEST_TARGETBRANCH`?

2019-02-07 16:49 UTC, reitermarkus commented on azure-pipelines.yml
> +        TAP_DIR="$(brew --repository)/Library/Taps/$(Build.Repository.Name)"
You can call `brew --repository "$(Build.Repository.Name)"` here instead.

2019-02-07 16:49 UTC, reitermarkus commented on cmd/brewcask-ci.rb
> +            "#{current_commit_hash}...#{current_commit_hash}"
Raise an error here instead.

2019-02-24 23:01 UTC, tommyang commented
I probably won't have time to work on this in the near future. Closing this for now.

2019-02-24 23:01 UTC, closed without merging