Add jMetrik 4.1.1
Homebrew/homebrew-cask pull request #58609
Opened 2019-02-08 10:50 UTC by sbibauw

jMetrik is a free psychometric measurement and statistics software
distributed by Psychomeasurement Systems, LLC.
It runs on Java (set as dependency) and is being installed by
install4j. I heavily copied the formula for SoapUI.rb and adapted
the parameters for the install4j install and uninstall scripts.

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

2019-02-08 13:53 UTC, vitorgalvao requested changes

2019-02-08 13:53 UTC, vitorgalvao commented on Casks/jmetrik.rb
> +  depends_on cask: 'java'
Needs to be a `caveat` instead.

https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/caveats.md#caveats-mini-dsl

2019-02-08 13:53 UTC, vitorgalvao commented on Casks/jmetrik.rb
> +  # installer :manual => "jMetrik Installer.app"
Remove this.

2019-02-08 13:53 UTC, vitorgalvao commented on Casks/jmetrik.rb
> +  # This Installer is copied and adapted from the formula for SoapUI.
Don’t mention where it’s copied from. If that one is changed, this will be outdated.

2019-02-09 00:29 UTC, sbibauw commented on Casks/jmetrik.rb
> +  depends_on cask: 'java'
OK, thank! All done!

2019-02-09 03:04 UTC, reitermarkus requested changes

2019-02-09 03:04 UTC, reitermarkus commented on Casks/jmetrik.rb
> +                                    '-Vsys.languageId=en',
I don't think this is needed.

2019-02-09 03:04 UTC, reitermarkus commented on Casks/jmetrik.rb
> +                                    '-Vsys.adminRights$Boolean=true',
I don't think this is needed.

2019-02-09 03:04 UTC, reitermarkus commented on Casks/jmetrik.rb
> +                      sudo:       true,
Does this actually require `sudo`?

2019-02-10 15:42 UTC, sbibauw commented on Casks/jmetrik.rb
> +                                    '-Vsys.installationDir=/Applications/jMetrik',
OK. Done.

2019-02-10 15:42 UTC, sbibauw commented on Casks/jmetrik.rb
> +                                    '-Vsys.languageId=en',
Indeed. It seems to be the default.

2019-02-10 15:48 UTC, sbibauw commented on Casks/jmetrik.rb
> +                                    '-Vsys.adminRights$Boolean=true',
Indeed. It seems to be the default.

2019-02-10 15:50 UTC, sbibauw commented on Casks/jmetrik.rb
> +                      sudo:       true,
Yes! The install4j Installer does require admin rights to both install and uninstall the app. If I do not mention "sudo: true" here, the Terminal will request admin rights via an external window during the installation.

2019-02-10 19:05 UTC, vitorgalvao commented
This looks good. Would you consider doing the same to the SoapUI cask?

2019-02-10 22:02 UTC, sbibauw commented
> This looks good. Would you consider doing the same to the SoapUI cask?

Done! (PR #58706)

2019-02-14 23:34 UTC, vitorgalvao approved these changes

2019-02-14 23:34 UTC, merged