abricotine 0.7.0
Homebrew/homebrew-cask pull request #59123
Opened 2019-02-19 01:18 UTC by dmlemos

After making all changes to the cask:

- [X] `brew cask audit --download {{cask_file}}` is error-free.
- [X] `brew cask style --fix {{cask_file}}` reports no offenses.
- [X] The commit message includes the cask’s name and version.
- [X] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

2019-02-19 16:41 UTC, vitorgalvao commented
> It seems the App source '/usr/local/Caskroom/abricotine/0.7.0/Abricotine.app' is not there.

[How to fix](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/source_is_not_there_error.md).

2019-02-19 16:41 UTC, vitorgalvao requested changes
> It seems the App source '/usr/local/Caskroom/abricotine/0.7.0/Abricotine.app' is not there.

[How to fix](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/source_is_not_there_error.md).

2019-02-20 00:16 UTC, dmlemos commented
@vitorgalvao Thanks for the tip. Fixed and also added zap contents.

2019-02-20 00:18 UTC, vitorgalvao commented on Casks/abricotine.rb
> +  app 'Abricotine-darwin-x64/Abricotine.app'
This in enough; we won’t copy the directory.

2019-02-20 00:18 UTC, vitorgalvao approved these changes

2019-02-20 03:36 UTC, merged