Update dynamic-dark-mode to 1.1.4
Homebrew/homebrew-cask pull request #59724
Opened 2019-03-03 11:30 UTC by suschizu

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

2019-03-03 15:05 UTC, vitorgalvao requested changes

2019-03-03 15:05 UTC, vitorgalvao commented on Casks/dynamic-dark-mode.rb
> +  url "https://github.com/ApolloZhu/Dynamic-Dark-Mode/releases/download/#{version}/Dynamic_Dark_Mode-#{version}.pkg"
If this is now a `pkg`, line `12` needs to change as well, and it’ll require `uninstall`.

2019-03-04 01:11 UTC, core-code requested changes
uninstall pkgutil: 'io.github.apollozhu.Dynamic.pkg'

2019-03-04 11:23 UTC, suschizu commented
just the Mojave-issue left …
the app depends on >=mojave

2019-03-04 14:30 UTC, merged