Add BetterAndBetter.app v1.6.25
Homebrew/homebrew-cask pull request #60342
Opened 2019-03-14 14:23 UTC by FereX98

After making all changes to the cask:

- [ ] `brew cask audit --download {{cask_file}}` is error-free.
- [ ] `brew cask style --fix {{cask_file}}` reports no offenses.
- [ ] The commit message includes the cask’s name and version.
- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [ ] Named the cask according to the [token reference].
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked there are no [open pull requests] for the same cask.
- [ ] Checked the cask was not [already refused].
- [ ] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

2019-03-15 02:18 UTC, vitorgalvao approved these changes

2019-03-15 17:03 UTC, vitorgalvao requested changes

2019-03-15 17:03 UTC, vitorgalvao commented on Casks/betterandbetter.rb
> +  url "http://13315641.s21d-13.faiusrd.com/0/1/ABUIABAAGAAg2aSO5AUowLyioAI?f=Better+And+Better+#{version}+Alpha%E7%89%88.dmg
This needs a closing quote at the end that was removed by mistake.

2019-03-16 02:20 UTC, FereX98 commented on Casks/betterandbetter.rb
> +  url "http://13315641.s21d-13.faiusrd.com/0/1/ABUIABAAGAAg2aSO5AUowLyioAI?f=Better+And+Better+#{version}+Alpha%E7%89%88.dmg
Yeah I've done that by mistake. I'll close this and make a new pull request.

2019-03-16 02:20 UTC, closed without merging