Updated URL and Version Number in Fing.app v5.3.3
Homebrew/homebrew-cask pull request #60449
Opened 2019-03-15 18:18 UTC by jpartain89

Fing changed how their URL's are formatted. 

After making all changes to the cask:

- [X] `brew cask audit --download {{cask_file}}` is error-free.
- [X] `brew cask style --fix {{cask_file}}` reports no offenses.
- [X] The commit message includes the cask’s name and version.
- [X] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

2019-03-19 01:57 UTC, reitermarkus commented on Casks/fing.rb
> +  version '5.3.3-osX'
Remove the `-osX` from the version.

2019-04-09 12:43 UTC, vitorgalvao requested changes

2019-04-09 12:43 UTC, vitorgalvao commented on Casks/fing.rb
> +  version '5.3.3'
Seeing as `url` doesn’t point to a specific version and there’s no [appcast](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/appcast.md), this cask should use `version :latest` and `sha256 :no_check`. [See an example](https://github.com/homebrew/homebrew-cask/blob/37f8d181d1789cbb06c6e73625587fdbe77ca225/Casks/kibako.rb#L2L3).

2019-04-28 11:42 UTC, vitorgalvao commented
This cask has since been updated by someone else and has conflicts. If you still wish to merge these changes, follow the requests and submit again. Thank you.

2019-04-28 11:42 UTC, closed without merging