Update adoptopenjdk from 11.0.2,9 to 12,33
Homebrew/homebrew-cask pull request #62201
Opened 2019-04-20 05:45 UTC by tiiiecherle

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

2019-04-20 10:57 UTC, vitorgalvao commented
Why change this from an `artifact` to a `pkgutil`? Assuming the end result is the same, that is a net loss.

2019-04-20 17:49 UTC, tiiiecherle commented
@vitorgalvao no specific reason for changing artifact to a pkgutil. I adopted the changes form [here](https://github.com/AdoptOpenJDK/homebrew-openjdk/blob/master/Casks/adoptopenjdk12.rb).

Feel free to change it back if you see any disadvantages. Thanks

2019-04-20 22:47 UTC, vitorgalvao commented
Please do change it back to using an `artifact`. A `pkg` can do anything, an `artifact` is just a moved file; way easier for the user to track.

2019-04-20 22:48 UTC, vitorgalvao requested changes
Please do change it back to using an `artifact`. A `pkg` can do anything, an `artifact` is just a moved file; way easier for the user to track.

2019-04-21 10:29 UTC, vitorgalvao requested changes

2019-04-21 10:29 UTC, vitorgalvao commented on Casks/adoptopenjdk.rb
> +  artifact "jdk-#{version.before_comma}+#{version.after_comma}", target: "/Library/Java/JavaVirtualMachines/adoptopenjdk-#{version.before_comma}.jdk"
Just this won’t work. You’ve made other changes. The download can’t be a `pkg`, for example, it needs to use their new `tar.gz` (or whatever) if available.

2019-04-21 15:20 UTC, tiiiecherle commented
I just installed the cask locally and it is working. 

How do we make sure all "old" versions are uninstalled correctly?
After the installation I have
/Library/Java/JavaVirtualMachines/adoptopenjdk-11.0.2.jdk
/Library/Java/JavaVirtualMachines/adoptopenjdk-12.jdk
both installed.
And the old unused one is 312,6 MB.

```
java --version
openjdk 12 2019-03-19
OpenJDK Runtime Environment AdoptOpenJDK (build 12+33)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 12+33, mixed mode, sharing)
```

2019-04-21 16:08 UTC, vitorgalvao requested changes

2019-04-21 16:08 UTC, vitorgalvao commented on Casks/adoptopenjdk.rb
> -  uninstall rmdir: '/Library/Java/JavaVirtualMachines'
This also has to be restored, and the `uninstall pkgutil` line removed.

2019-04-21 16:24 UTC, tiiiecherle commented on Casks/adoptopenjdk.rb
> -  uninstall rmdir: '/Library/Java/JavaVirtualMachines'
o.k., done, would be nice if you could take the time and have a look at my question regarding the old versions. thanks

2019-04-21 16:24 UTC, vitorgalvao approved these changes

2019-04-21 16:26 UTC, vitorgalvao commented
If you’ve installed from this cask (`homebrew/cask/adoptopenjdk`), then the previous version will upgrade to this one. If you installed from another tap, they should be considered different casks, and thus will not.

If there’s any install confusion, try uninstalling them all or installing again, or just removing the the file `artifact` points to (an advantage of doing it this way).

2019-04-21 16:31 UTC, tiiiecherle commented
o.k., thanks

2019-04-21 16:32 UTC, merged