Add Kotlin Native v1.3.31
Homebrew/homebrew-cask pull request #63560
Opened 2019-05-20 19:00 UTC by grlee

There's a formula that was submitted and rejected to homebrew-core.  I believe a cask makes more sense, given the nature of the project (e.g. native binaries are included in the release)

After making all changes to the cask:

- [X] `brew cask audit --download {{cask_file}}` is error-free.
- [X] `brew cask style --fix {{cask_file}}` reports no offenses.
- [X] The commit message includes the cask’s name and version.
- [X] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [X] Named the cask according to the [token reference].
- [X] `brew cask install {{cask_file}}` worked successfully.
- [X] `brew cask uninstall {{cask_file}}` worked successfully.
- [X] Checked there are no [open pull requests] for the same cask.
- [X] Checked the cask was not [already refused].
- [X] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

2019-05-20 22:42 UTC, vitorgalvao requested changes

2019-05-20 22:42 UTC, vitorgalvao commented on Casks/kotlin-native.rb
> +require 'fileutils'
Please don’t add stuff before the cask definition. No other official cask does it, and it is not necessary.

2019-05-20 22:42 UTC, vitorgalvao commented on Casks/kotlin-native.rb
> +  caveats depends_on_java '6+'
`caveats` need to be together in the same block.

2019-05-20 22:42 UTC, vitorgalvao commented on Casks/kotlin-native.rb
> +  caveats <<~EOS
But remove this `caveat`; it is not installation-related.

2019-05-20 22:42 UTC, vitorgalvao commented on Casks/kotlin-native.rb
> +  uninstall delete: "#{staged_path}/#{token}"
Unnecessary. Please remove it.

2019-05-20 22:42 UTC, vitorgalvao commented on Casks/kotlin-native.rb
> +  postflight do
Search for “shim script” in the repo. We have a way to do this.

2019-05-20 22:42 UTC, vitorgalvao commented
> There's a formula that was submitted and rejected to homebrew-core.

Please link me to it.

How is this different from the `kotlin` formula? How does this add value?

2019-05-21 01:39 UTC, grlee commented
Thank you for looking at this @vitorgalvao.

Here's the pull request for the formula:
https://github.com/Homebrew/homebrew-core/pull/37546

As far as value added - the kotlin formula only includes the kotlin compiler that outputs jvm and llvm compatible binaries.  kotlin-native is a side-project to add compiler support for native binaries.  It's primarily use case is building android/ios applications or java/net libraries with the same code base.
(Linux, Windows, and Mac OS binaries are also supported by the kotlin–native project.)

2019-05-21 01:43 UTC, vitorgalvao commented on Casks/kotlin-native.rb
> +  # github.com/JetBrains/kotlin/releases/download/v was verified as official when first introduced to the cask
Just `github.com/JetBrains/kotlin`

2019-05-21 01:44 UTC, vitorgalvao commented
Sounds acceptable. Please proceed with the requested fixes so we can merge.

2019-05-21 16:43 UTC, grlee commented on Casks/kotlin-native.rb
> +  postflight do
I'm going to drop this postflight clause.  It's testing that the install succeeds, but I'm not seeing any other casks testing their installations like this.

2019-05-21 16:53 UTC, grlee commented
Updated pull request with review suggestions.

2019-05-21 19:19 UTC, vitorgalvao commented
Looks great. Thank you.

2019-05-21 19:19 UTC, merged