GitKraken latest (switch from zip to DMG)
Homebrew/homebrew-cask pull request #63633
Opened 2019-05-21 20:28 UTC by crahan

After making all changes to the cask:

- [X] `brew cask audit --download {{cask_file}}` is error-free.
- [X] `brew cask style --fix {{cask_file}}` reports no offenses.
- [X] The commit message includes the cask’s name and version.
- [X] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

This is a pull request as requested at https://github.com/Homebrew/homebrew-cask/issues/63563. The original .zip file which is downloaded from https://release.gitkraken.com/darwin/GitKraken-v5.0.4.zip contains a GitKraken application which is over 500MB. The .dmg version downloaded from https://release.gitkraken.com/darwin/installGitKraken.dmg (which is the location used when directly downloading from the GitKraken website) contains an application that's only half the size. The .dmg version also does not trigger an unidentified developer warning when launched.

Unfortunately, I did have to change the versioning from an actual version number to `:latest` which does not check the SHA256 hash, doesn't support auto_update, and doesn't use appcast (per the `brew cask audit --download` output).

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

2019-05-21 22:35 UTC, vitorgalvao commented
> I did have to change the versioning from an actual version number to `:latest` which does not check the SHA256 hash, doesn't support auto_update, and doesn't use appcast

Those aren’t mutually exclusive. Revert everything except for the `url` change, and update the `sha256`. We’ll continue from there.

2019-05-22 18:37 UTC, crahan commented
Changes have been applied as requested.

Using this configuration, even though the installer package (DMG) does not indicate a particular version number, the SHA256-check will warn of any updates or changes to the installGitKraken.dmg disk image and require someone to update the version number and SHA256 in `Casks/gitkraken.rb`?

2019-05-22 19:16 UTC, vitorgalvao commented
> the SHA256-check will warn of any updates or changes to the installGitKraken.dmg disk image and require someone to update the version number and SHA256 in `Casks/gitkraken.rb`?

Yes. The `appcast` will help identify updates faster.

For anyone that lands here later on, quick recap of the reasons for the change:

* Zip version is double (185MB) the size of the DMG (91MB).
* Zip version is unsigned.

2019-05-22 19:16 UTC, vitorgalvao approved these changes

2019-05-22 20:48 UTC, vitorgalvao requested changes

2019-05-22 20:48 UTC, vitorgalvao commented on Casks/gitkraken.rb
> +  url "https://release.gitkraken.com/darwin/installGitKraken.dmg"
These need to be changed to single quotes.

2019-05-22 20:56 UTC, crahan commented on Casks/gitkraken.rb
> +  url "https://release.gitkraken.com/darwin/installGitKraken.dmg"
Fixed.

2019-05-23 11:55 UTC, vitorgalvao commented
Thank you, @crahan.

2019-05-23 11:56 UTC, merged