new cask: qt-design-studio
Homebrew/homebrew-cask pull request #64317
Opened 2019-06-03 15:34 UTC by yurikoles

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

2019-06-03 15:42 UTC, vitorgalvao requested changes

2019-06-03 15:42 UTC, vitorgalvao commented on Casks/qt-design-studio.rb
> +  uninstall delete: "~/Applications/QtDesignStudio-#{version}-community"
It’s unlikely this is everything the installer does. If it is, it must mean there’s an app somewhere we can grab instead of relying on the installer.

2019-06-03 15:44 UTC, yurikoles commented on Casks/qt-design-studio.rb
> +  uninstall delete: "~/Applications/QtDesignStudio-#{version}-community"
I just copy-pasted this from  qt3dstudio.

2019-06-03 15:47 UTC, vitorgalvao commented on Casks/qt-design-studio.rb
> +  uninstall delete: "~/Applications/QtDesignStudio-#{version}-community"
> I just copy-pasted this from qt3dstudio.

[Which you submitted in this same form](https://github.com/Homebrew/homebrew-cask/pull/52683). Had I noticed it then, I would have commented then.

2019-06-04 14:40 UTC, yurikoles commented
@vitorgalvao I'm unsure how to extract it.
```
$ file installer.dat 
installer.dat: Qt Binary Resource file
$ 7z x installer.dat 

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=utf8,Utf16=on,HugeFiles=on,64 bits,6 CPUs x64)

Scanning the drive for archives:
1 file, 180913742 bytes (173 MiB)

Extracting archive: installer.dat

WARNINGS:
There are data after the end of archive

--
Path = installer.dat
Type = 7z
WARNINGS:
There are data after the end of archive
Offset = 207155
Physical Size = 19714590
Tail Size = 160991997
Headers Size = 223
Method = LZMA2:24
Solid = -
Blocks = 1

Everything is Ok                               

Archives with Warnings: 1

Warnings: 1
Folders: 3
Files: 1
Size:       20403947
Compressed: 180913742

$ tree .     
.
├── installer.dat
└── qtlive
    └── android
        └── arm7
            └── qt_live_viewer.apk

3 directories, 2 files
```

2019-06-04 14:42 UTC, yurikoles commented
And I don't see any extract or install methods in help output.
```
$ ./qt-designstudio-mac-x86_64-1.2.0-community --help
Usage: ./qt-designstudio-mac-x86_64-1.2.0-community [options] Key=Value

Options:
  -h, --help                               Displays this help.
  --version                                Displays version information.
  --framework-version                      Displays the version of the Qt
                                           Installer Framework.
  -v, --verbose                            Verbose mode. Prints out more
                                           information.
  --proxy                                  Use system proxy on Windows and
                                           Linux. This option has no effect on
                                           OS X.
  --no-proxy                               Do not use system proxy.
  --script <file>                          Execute the script given as
                                           argument.
  --checkupdates                           Check for updates and return an XML
                                           description.
  --updater                                Start application in updater mode.
  --manage-packages                        Start application in package manager
                                           mode.
  --no-force-installations                 Allow deselecting components that
                                           are marked as forced.
  --show-virtual-components                Show virtual components in installer
                                           and package manager.
  --logging-rules <rules>                  Enables logging according to passed
                                           rules. Comma separated logging rules
                                           have the following syntax:
                                           loggingCategory=true/false. Passing
                                           empty logging rules enables all
                                           logging categories. The following
                                           rules enable a single category:
                                           ifw.*=false,ifw.category=true The
                                           following logging categories are
                                           available:
                                           ifw.componentChecker
                                           ifw.resources
                                           ifw.translations
                                           ifw.network
  --create-local-repository                Create a local repository inside the
                                           installation directory. This option
                                           has no effect on online installers.
  --addRepository <URI,...>                Add a local or remote repository to
                                           the list of user defined
                                           repositories.
  --addTempRepository <URI,...>            Add a local or remote repository to
                                           the list of temporary available
                                           repositories.
  --setTempRepository <URI,...>            Set a local or remote repository as
                                           temporary repository, it is the only
                                           one used during fetch.
                                           Note: URI must be prefixed with the
                                           protocol, i.e. file:///, https://,
                                           http:// or ftp://.
  --startserver <mode,socketname,key>      Starts the application as headless
                                           process waiting for commands to
                                           execute. Mode can be DEBUG or
                                           PRODUCTION. In DEBUG mode, the option
                                           values can be omitted.Note: The
                                           server will not shutdown on his own,
                                           you need to quit the process by hand.
  --startclient <socketname,key>           Starts the application to debug the
                                           client-server communication. If a
                                           value is omitted, the client will use
                                           a default instead. Note: The server
                                           process is not started by the client
                                           application in that case, you need to
                                           start it on your own.
  --installCompressedRepository <URI,...>  Installs QBSP or 7z file. The QBSP
                                           (Board Support Package) file must be
                                           a .7z file which contains a valid
                                           repository.
  --silentUpdate                           Updates all packages silently.
  --platform <plugin>                      Use the specified platform plugin.
  --squish-port <port number>              Give a port where Squish can connect
                                           to. If no port is given, default port
                                           11233 is used. Note: To enable Squish
                                           support you first need to build IFW
                                           with SQUISH_PATH parameter where
                                           SQUISH_PATH is pointing to your
                                           Squish installation folder:
                                           <path_to_qt>/bin/qmake -r
                                           SQUISH_PATH=<pat_to_squish>

Arguments:
  Key=Value                                Key Value pair to be set.

2019-06-04 14:49 UTC, yurikoles commented
As I see from installer log in GUI it basically extracts some 7z archives and writes config for updater/maintainance app. But I don't know a way how to grab those 7z's.

2019-06-04 14:50 UTC, yurikoles commented
I just had putted default install location in `uninstall` stanza, but user may install it anywhere.

2019-06-04 15:02 UTC, vitorgalvao commented
Alright, let’s leave as is for now. Thank you for trying!

2019-06-04 15:02 UTC, merged

2019-06-04 15:22 UTC, yurikoles commented
Ok, thanks. Uninstaller for default location is better than lack of uninstaller.

2019-06-04 15:23 UTC, vitorgalvao commented
> Uninstaller for default location is better than lack of uninstaller.

I’m more worried about things lacking in the uninstaller.

2019-06-04 15:33 UTC, yurikoles commented
It didn't prompted me for password, so I assume that all things are installed to this folder.

2019-06-04 15:39 UTC, vitorgalvao commented
> It didn't prompted me for password, so I assume that all things are installed to this folder.

It may still have installed login items or launchd jobs.