Added cask for CellDesigner
Homebrew/homebrew-cask pull request #64339
Opened 2019-06-04 00:02 UTC by achillesrasquinha

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

2019-06-04 00:43 UTC, vitorgalvao requested changes

2019-06-04 00:43 UTC, vitorgalvao commented on Casks/celldesigner.rb
> +  container type: :dmg
Have you tried without this line? It should not be needed.

2019-06-04 00:43 UTC, vitorgalvao commented on Casks/celldesigner.rb
> +  depends_on cask: 'java'
Should be a [`caveat`](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/caveats.md#caveats-mini-dsl) instead.

2019-06-04 03:07 UTC, achillesrasquinha commented on Casks/celldesigner.rb
> +  container type: :dmg
Yes. Alright.

2019-06-04 03:41 UTC, achillesrasquinha commented
@vitorgalvao fixed all changes.

2019-06-04 12:35 UTC, vitorgalvao requested changes

2019-06-04 12:35 UTC, vitorgalvao commented on Casks/celldesigner.rb
> +    depends_on_java
It needs a version as the argument. What versions does this require?

2019-06-05 03:40 UTC, achillesrasquinha commented on Casks/celldesigner.rb
> +    depends_on_java
'6+'

2019-06-05 15:22 UTC, vitorgalvao commented
Thank you, @achillesrasquinha.

By the way, [that’s a great last name](https://glosbe.com/pt/en/%C3%A0%20rasquinha).

2019-06-05 15:22 UTC, merged