Skip uninstall in ci if manual
Homebrew/homebrew-cask pull request #66436
Opened 2019-07-18 15:57 UTC by hyuraku

Closes https://github.com/Homebrew/homebrew-cask/issues/59835

2019-07-18 16:03 UTC, reitermarkus requested changes

2019-07-18 16:03 UTC, reitermarkus commented on cmd/brewcask-ci.rb
> +        cask.ancestors.include?(ManualInstaller)
```suggestion
        cask.artifacts.any? { |a| a.is_a?(Artifact::Installer::ManualInstaller) }
```

2019-07-18 16:03 UTC, reitermarkus commented on cmd/brewcask-ci.rb
> +      def check_manual
```suggestion
      def manual_installer?
```

2019-07-19 13:13 UTC, reitermarkus commented
Can you add a commit with a change to a cask this applies to, to see if this is working?

2019-07-20 08:57 UTC, hyuraku commented on Casks/blue-jeans.rb
> +  sha256 'e7a5f5faa69000906bb30da34edc415d297174b4c463dd186c00125be58140c9'
To check fixed ci, I changed one cask.
I will reset it after fixed ci is approved.

2019-07-20 15:49 UTC, vitorgalvao commented on Casks/blue-jeans.rb
>    appcast 'https://www.bluejeans.com/downloads'
Also remove this line on the test, or CI will fail because of it.

2019-07-20 16:15 UTC, reitermarkus commented on cmd/brewcask-ci.rb
> +              Installer.new(cask, verbose: true).uninstall unless manual_installer?(cask)
Also, let's add a message like `"Cask has a manual installer, skipping …"`.

2019-07-23 07:14 UTC, reitermarkus commented
Thanks, @hyuraku, working as expected! You can remove the change to the cask again.

2019-07-23 07:17 UTC, reitermarkus commented on cmd/brewcask-ci.rb
> +          puts 'Cask has a manual installer, skipping …'
Move the message to where `manual_installer?` is used, so this function can stay simple.

2019-07-23 14:44 UTC, vitorgalvao approved these changes

2019-07-23 14:51 UTC, merged

2019-07-23 14:51 UTC, reitermarkus commented
Great work, @hyuraku!