Add citra
Homebrew/homebrew-cask pull request #66668
Opened 2019-07-24 08:51 UTC by aaronliu0130

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

2019-07-24 12:33 UTC, vitorgalvao requested changes

2019-07-24 12:33 UTC, vitorgalvao commented on Casks/citra.rb
> +  url 'https://github.com/citra-emu/citra-web/releases/download/1.0/citra-setup-mac.dmg'
Needs an [`appcast`](https://github.com/homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/appcast.md).

2019-07-24 12:33 UTC, vitorgalvao commented on Casks/citra.rb
> +  version :latest
`version` and `shasum` need to be set.

2019-07-24 12:33 UTC, vitorgalvao commented on Casks/citra.rb
> +  url 'https://github.com/citra-emu/citra-web/releases/download/1.0/citra-setup-mac.dmg'
Version should be interpolated.

2019-07-24 12:33 UTC, vitorgalvao commented on Casks/citra.rb
> +  uninstall delete: [
It’s unlikely this is the only thing the installer does.

Still, if it is, it should not be an array.

2019-07-24 12:34 UTC, vitorgalvao commented
Welcome and thank you, but we’ll be rejecting this on account of [not being notable enough](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/rejected_casks.md):

> The Cask is too obscure (for example, a self-submitted app from a GitHub repository that is [not notable enough](https://github.com/Homebrew/homebrew-cask/pull/28103) (under 50 stars)).

I’ve still went and commented on what would need fixing, for future reference.

2019-07-25 03:21 UTC, aaronliu0130 commented
> Welcome and thank you, but we’ll be rejecting this on account of [not being notable enough](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/rejected_casks.md):
> 
> > The Cask is too obscure (for example, a self-submitted app from a GitHub repository that is [not notable enough](https://github.com/Homebrew/homebrew-cask/pull/28103) (under 50 stars)).
> 
> I’ve still went and commented on what would need fixing, for future reference.

@vitorgalvao Actually, it is notable enough. The citra-web repo just hosts the source code for the website and downloads, but the emulator's source code itself has a lot of stars.
![the actual emulator's repository](https://user-images.githubusercontent.com/11874211/61843377-f09f2100-aecd-11e9-9530-a5b234df58be.png)
I had to link to the download page in citra-web because there are two different distributions, canary and nightly, and it would be hard to download and update this cask because a new release is made every day. See citra-emu/citra-canary and citra-emu/citra-nightly

2019-07-25 03:21 UTC, aaronliu0130 commented
I'll be fixing those later.

2019-07-25 03:22 UTC, aaronliu0130 commented on Casks/citra.rb
> +  version :latest
If I set this for citra canary or nightly, it needs to be checked and changed every day because a new build is released on a daily basis.

2019-07-25 03:25 UTC, aaronliu0130 commented on Casks/citra.rb
> +  url 'https://github.com/citra-emu/citra-web/releases/download/1.0/citra-setup-mac.dmg'
Actually, there's no new version for the citra-setup. The version is only there because GitHub requires semantic versioning for each release.

2019-07-25 03:25 UTC, aaronliu0130 commented on Casks/citra.rb
> +  uninstall delete: [
So, I don't need the brackets or the comma?

2019-07-25 03:26 UTC, aaronliu0130 commented on Casks/citra.rb
> +  version :latest
The installer does not has a version. The installer only downloads the latest version.

2019-07-25 03:27 UTC, aaronliu0130 commented on Casks/citra.rb
> +  url 'https://github.com/citra-emu/citra-web/releases/download/1.0/citra-setup-mac.dmg'
Should I add the app cast for nightly or canary? The installer can install both versions.

2019-07-25 03:27 UTC, aaronliu0130 commented on Casks/citra.rb
> +  uninstall delete: [
I'm assuming that's what you're saying.

2019-07-25 03:37 UTC, aaronliu0130 commented on Casks/citra.rb
> +  uninstall delete: [
Now I pushed those changes to my branch, but somehow they're not showing up in this pull request...

2019-07-25 12:54 UTC, aaronliu0130 commented
@vitorgalvao Please reopen this.

2019-07-25 15:31 UTC, vitorgalvao commented
> @vitorgalvao Please reopen this.

Please be patient. I’ve got ten email notifications on this in the last few hours.

I’m human and a volunteer, I also have a life and things to do, like sleep. I’ll reopen this *if* it warrants being reopened, *after* I have the time to rereview. Since you’ve sent so many messages, that might take longer.

2019-07-26 00:49 UTC, aaronliu0130 commented
Ok.

2019-07-26 10:59 UTC, vitorgalvao commented on Casks/citra.rb
> +  url 'https://github.com/citra-emu/citra-web/releases/download/1.0/citra-setup-mac.dmg'
> The version is only there because GitHub requires semantic versioning for each release.

That’s incorrect. You can call a version anything.

2019-07-26 11:01 UTC, vitorgalvao requested changes

2019-07-26 11:01 UTC, vitorgalvao commented on Casks/citra.rb
> +  uninstall delete: '/Applications/Citra'
This is still incomplete. It’s unlikely moving an `app` is the only thing the installer does. You’ll need to find an official source that shows how to completely remove the app after it’s installed.

2019-07-27 03:48 UTC, aaronliu0130 commented on Casks/citra.rb
> +  uninstall delete: '/Applications/Citra'
Hmmm... There's an app included in `Applications/Citra` that can update, uninstall, and install. Should I tell the user to run that?

2019-07-27 12:20 UTC, vitorgalvao commented on Casks/citra.rb
> +  uninstall delete: '/Applications/Citra'
> There's an app included in `Applications/Citra` that can update, uninstall, and install. Should I tell the user to run that?

No, we need to be able to reproduce programatically what it does automatically. Usually there’s a FAQ or official forum post on how to completely remove the software.

2019-07-27 13:01 UTC, aaronliu0130 commented on Casks/citra.rb
> +  uninstall delete: '/Applications/Citra'
![image](https://user-images.githubusercontent.com/11874211/61994778-9959a600-b0b1-11e9-92bb-05566dcd3966.png)
Currently the only thing I can find that the installer installs is `Applications/Citra/` and that's about it.

2019-07-27 14:14 UTC, vitorgalvao commented on Casks/citra.rb
> +  uninstall delete: '/Applications/Citra'
**Again**:

> You’ll need to find an official source that shows how to completely remove the app after it’s installed.

> Usually there’s a FAQ or official forum post on how to completely remove the software.

2019-07-28 03:06 UTC, aaronliu0130 commented on Casks/citra.rb
> +  uninstall delete: '/Applications/Citra'
There's no official forum post or faq and there's a manual download on the site which basically downloads the `canary/` or `nightly/` folder. Probably the only thing that the installer does is write a log, get the maintenance tool, gather the liscense, and download the latest "manual download" folder. All in the `Applications/Citra/` folder.

2019-07-30 12:06 UTC, merged