Add triple-cheese 1.2.1.3898
Homebrew/homebrew-cask pull request #66679
Opened 2019-07-24 15:59 UTC by hannesbraun

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

2019-07-26 11:14 UTC, vitorgalvao requested changes
Please follow the same patter as https://github.com/Homebrew/homebrew-cask/pull/66765.

2019-07-26 11:15 UTC, vitorgalvao commented on Casks/triple-cheese.rb
> +  pkg "TripleCheese#{version.split('.')[3]}Mac/TripleCheese #{version} Installer.pkg"
Does the installed app have spaces in the name?

2019-07-26 22:46 UTC, hannesbraun commented on Casks/triple-cheese.rb
> +  pkg "TripleCheese#{version.split('.')[3]}Mac/TripleCheese #{version} Installer.pkg"
When installed, the Audio Unit is named "TripleCheese". But the homepage uses the version with a space in the name, that's why I chose that.

2019-07-26 23:15 UTC, vitorgalvao commented on Casks/triple-cheese.rb
> +  pkg "TripleCheese#{version.split('.')[3]}Mac/TripleCheese #{version} Installer.pkg"
> But the homepage uses the version with a space in the name, that's why I chose that.

The [token reference](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md) is explicit. What matters it the name of the installed software, not what they call it on the page.

2019-07-26 23:16 UTC, vitorgalvao approved these changes

2019-07-26 23:36 UTC, merged

2019-07-27 08:46 UTC, hannesbraun commented on Casks/triple-cheese.rb
> +  pkg "TripleCheese#{version.split('.')[3]}Mac/TripleCheese #{version} Installer.pkg"
Okay, thank you :)