Add microsoft-word 16.27.19071500
Homebrew/homebrew-cask pull request #66740
Opened 2019-07-25 16:11 UTC by joh-klein

After making all changes to the cask:

- [ ] `brew cask audit --download {{cask_file}}` is error-free.
- [ ] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

Cask was refused #41092 but I asked if it was okay to reopen: #66735 

Right now I get curl errors (416) so I am flying a little blind. But will check again later.

I am not sure about the whole `unistall` part, but maybe you can give me pointers?

Thx in advance!

2019-07-25 23:33 UTC, vitorgalvao requested changes

2019-07-25 23:33 UTC, vitorgalvao commented on Casks/microsoft-word.rb
> +  url "https://officecdn-microsoft-com.akamaized.net/pr/C1297A47-86C4-4C1F-97FA-950631F94777/MacAutoupdate/Microsoft_Word_#{version}_Installer.pkg"
This is not the URL on the page you mentioned in the other issue, and it’s missing the URL itself as the `appcast`, as requested.

2019-07-26 08:36 UTC, joh-klein commented on Casks/microsoft-word.rb
> +  url "https://officecdn-microsoft-com.akamaized.net/pr/C1297A47-86C4-4C1F-97FA-950631F94777/MacAutoupdate/Microsoft_Word_#{version}_Installer.pkg"
I went the same route the [microsoft-office.rb](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/microsoft-office.rb#L6) cask is going and took the URL to which "https://go.microsoft.com/fwlink/p/?linkid=525134" is forwarding (checked via `curl -I <URL>`) since it is an absolute URL and contains the version information as well.

2019-07-26 08:40 UTC, joh-klein commented on Casks/microsoft-word.rb
> +  url "https://officecdn-microsoft-com.akamaized.net/pr/C1297A47-86C4-4C1F-97FA-950631F94777/MacAutoupdate/Microsoft_Word_#{version}_Installer.pkg"
And as you can see in the that cask, the URL is largely the same.

2019-07-26 09:04 UTC, joh-klein commented
How can I check what a package ist actually installing on my system (besides the *.app)? I know about `pkgutil` but what about the other places? Looking at the [mirosoft-office](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/microsoft-office.rb#L33) cask I see a lot of other things beeing unistalled or deleted – how do find out about those?

2019-07-26 10:53 UTC, vitorgalvao requested changes

2019-07-26 10:53 UTC, vitorgalvao commented on Casks/microsoft-word.rb
> +  url "https://officecdn-microsoft-com.akamaized.net/pr/C1297A47-86C4-4C1F-97FA-950631F94777/MacAutoupdate/Microsoft_Word_#{version}_Installer.pkg"
Not if you use the URL in the page: `https://officecdn.microsoft.com/pr/C1297A47-86C4-4C1F-97FA-950631F94777/MacAutoupdate/Microsoft_Word_16.27.19071500_Updater.pkg`; `curl` doesn’t give a different location. The whole point of reallowing this cask is that we can have a `url` that is present on a page we deem official.

2019-07-26 10:54 UTC, vitorgalvao commented
> I know about `pkgutil` but what about the other places?

Read the [`uninstall`](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/uninstall.md) documentation I’ve pointed you to.

2019-07-26 12:11 UTC, joh-klein commented on Casks/microsoft-word.rb
> +  url "https://officecdn-microsoft-com.akamaized.net/pr/C1297A47-86C4-4C1F-97FA-950631F94777/MacAutoupdate/Microsoft_Word_#{version}_Installer.pkg"
I am sorry, but I am not sure I understand you correctly. As far as I understand [this site by Microsoft](https://docs.microsoft.com/en-us/officeupdates/update-history-office-for-mac) there are two different packages for most of the individual office products. For example Word:

Updater:
https://officecdn.microsoft.com/pr/C1297A47-86C4-4C1F-97FA-950631F94777/MacAutoupdate/Microsoft_Word_16.27.19071500_Updater.pkg

SHA-256: b989fc4d1f49f096ee5e1ebd043a36f2afd7551c23c7e6d51f8ff2aa5c325654

Installer:
https://go.microsoft.com/fwlink/p/?linkid=525134
or
`curl -I https://go.microsoft.com/fwlink/p/?linkid=525134`
->
https://officecdn-microsoft-com.akamaized.net/pr/C1297A47-86C4-4C1F-97FA-950631F94777/MacAutoupdate/Microsoft_Word_16.27.19071500_Installer.pkg

SHA-256: 6e6e87f28b5ff4b53d6fe3c021a5516f4b709bfb05e67ffab99751cc41ba5777

Do you want me to use the updater package? I don't think that would work (but I have to admit, I am not sure)

PS: If I might add: the situation, that the full URL is not on that page is the same for the microsoft-office cask. [And it looks like you accepted it, when it changed to this](https://github.com/Homebrew/homebrew-cask/pull/56068) and also the last time, [when that cask was updated](https://github.com/Homebrew/homebrew-cask/pull/66786) …
At least the SHA-256 sum is on that page, shouldn't that count for something?

2019-07-30 12:20 UTC, vitorgalvao requested changes

2019-07-30 12:20 UTC, vitorgalvao commented on Casks/microsoft-word.rb
> +  homepage 'https://products.office.com/mac/microsoft-office-for-mac/'
`https://products.office.com/en-US/word`

2019-07-30 12:21 UTC, vitorgalvao requested changes

2019-07-30 12:21 UTC, vitorgalvao commented on Casks/microsoft-word.rb
> +            launchctl: [
Single item. Make it a string instead of an array.

2019-07-30 12:21 UTC, vitorgalvao requested changes

2019-07-30 12:21 UTC, vitorgalvao commented on Casks/microsoft-word.rb
> +      pkgutil:   [
Single item. Make it a string instead of an array.

2019-07-30 12:29 UTC, joh-klein commented on Casks/microsoft-word.rb
> +  homepage 'https://products.office.com/mac/microsoft-office-for-mac/'
Yeah, I thought about that as well. Since the screenshots were for the PC version and the link was not for all languages I reconsidered. But I just found the global link: "https://products.office.com/word". It's still not macOS specific, but at least the page changes to the language of your system. What do you think?

2019-07-30 12:31 UTC, vitorgalvao commented on Casks/microsoft-word.rb
> +  homepage 'https://products.office.com/mac/microsoft-office-for-mac/'
> but at least the page changes to the language of your system.

It changes to your *location* (my system is in english, but it’s forcing me to read the page in Portuguese). Keep the language part.

2019-07-30 12:34 UTC, vitorgalvao approved these changes

2019-08-03 01:21 UTC, merged