Add XCTU Latest
Homebrew/homebrew-cask pull request #66957
Opened 2019-07-30 23:19 UTC by onesmallskipforman

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

2019-08-01 22:29 UTC, vitorgalvao requested changes

2019-08-01 22:29 UTC, vitorgalvao commented on Casks/xctu.rb
> +  uninstall trash: '/Applications/XCTU.app'
It’s unlikely the installer only does this. You’ll need to find the proper to way to completely remove the app from the system. There’s usually a FAQ or forum post you can reference. Contacting the author sometimes works, too.

2019-08-04 06:23 UTC, onesmallskipforman commented on Casks/xctu.rb
> +  uninstall trash: '/Applications/XCTU.app'
Thanks for the update. I found the other files/directories the installer creates, and added them to a new zap section in the cask.

2019-08-04 09:45 UTC, vitorgalvao commented on Casks/xctu.rb
> +  uninstall trash: '/Applications/XCTU.app'
Those are configuration files, not files added bu the installer.

2019-08-04 09:45 UTC, vitorgalvao commented on Casks/xctu.rb
> +               '/Applications/XCTU.app',
This is repeated.

2019-08-04 09:46 UTC, vitorgalvao commented on Casks/xctu.rb
> +               '~/Library/Saved\ Application\ State/XCTU.savedState',
Don’t escape spaces.

2019-08-04 22:00 UTC, onesmallskipforman commented on Casks/xctu.rb
> +  uninstall trash: '/Applications/XCTU.app'
@vitorgalvao Ah, you're right. Those files are created when I first run the app, rather than during installation. I did some extra pruning and could not find any extra files created during installation. Checking install logs, and using 3rd party install management apps, I could only find config files created.

2019-08-05 01:25 UTC, vitorgalvao commented on Casks/xctu.rb
> +  uninstall trash: '/Applications/XCTU.app'
Don’t try to guess what the installer does; look for an official source instead. We won’t be able to accept this otherwise.

2019-08-05 18:40 UTC, onesmallskipforman commented on Casks/xctu.rb
> +  uninstall trash: '/Applications/XCTU.app'
@vitorgalvao I contacted Digi Tech Support (the creators of XCTU). They told me deleting XCTU.app is sufficient for a complete uninstall. No other files are created by the installer.

2019-08-06 01:06 UTC, onesmallskipforman commented on Casks/xctu.rb
> +  uninstall trash: '/Applications/XCTU.app'
Here is the email conversation:
![Screen Shot 2019-08-05 at 9 02 42 PM](https://user-images.githubusercontent.com/45481075/62503946-6f486800-b7c4-11e9-8a4d-7ed29dba7968.png)

2019-08-06 16:06 UTC, vitorgalvao commented on Casks/xctu.rb
> +  uninstall trash: '/Applications/XCTU.app'
That’s an awful way to go about it, but from their website it seems like macOS might be an afterthought for them.

Thank you for asking.

2019-08-06 16:07 UTC, vitorgalvao commented
Welcome, and thank you for the contribution.

2019-08-06 16:07 UTC, merged