Update podman from 1.4.2 to 1.5.0
Homebrew/homebrew-cask pull request #67491
Opened 2019-08-12 14:49 UTC by ashley-cui

Update podman version and make manpages installable

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

After making all changes to the cask:

- [ ] `brew cask audit --download {{cask_file}}` is error-free.
- [ ] `brew cask style --fix {{cask_file}}` reports no offenses.
- [ ] The commit message includes the cask’s name and version.
- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [ ] Named the cask according to the [token reference].
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked there are no [open pull requests] for the same cask.
- [ ] Checked the cask was not [already refused].
- [ ] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

2019-08-12 15:06 UTC, vitorgalvao requested changes

2019-08-12 15:06 UTC, vitorgalvao commented on Casks/podman.rb
> +end
It has a “no newline at end of file” warning. Those [are meaningful](http://unix.stackexchange.com/a/18789).

2019-08-12 15:06 UTC, vitorgalvao commented on Casks/podman.rb
> +
Too many empty lines.

2019-08-12 15:06 UTC, vitorgalvao commented on Casks/podman.rb
> +  man1 = Dir["#{HOMEBREW_PREFIX}/Caskroom/podmand/#{version}/brew/docs/*.1"]
Please don’t do this. Don’t set variables at the top level

2019-08-12 15:06 UTC, vitorgalvao commented on Casks/podman.rb
> +  man1.each do |page|
Also don’t do this. Don’t have random blocks at the top level. look into the [`*flight` blocks](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/flight.md) (see other casks for how to use them).

2019-08-12 15:18 UTC, ashley-cui commented on Casks/podman.rb
> +  man1.each do |page|
Is the man1.each block not okay? Or just the docs variable?

2019-08-12 20:35 UTC, closed without merging

2019-08-19 18:26 UTC, ashley-cui commented on Casks/podman.rb
> +  man1.each do |page|
@vitorgalvao Hi, I still would like to get this working, but still do not understand the requirements. Can you link me to any resources that would be helpful in this case? Is the .each part not okay?

2019-08-20 13:03 UTC, vitorgalvao commented on Casks/podman.rb
> +  man1.each do |page|
Look into the `postflight` and `uninstall_postflight` blocks in casks, and in the link I posted earlier. Your new codes needs to be inside those.