Add Wally.app Latest
Homebrew/homebrew-cask pull request #67838
Opened 2019-08-19 12:55 UTC by fdidron

Wally is an open source application allowing users to flash new
firmwares to their ZSA keyboards.

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

2019-08-19 16:29 UTC, vitorgalvao requested changes

2019-08-19 16:29 UTC, vitorgalvao commented on Casks/wally.rb
> +  version :latest
Set this (`1.1.1`) and `sha256`.

2019-08-19 16:29 UTC, vitorgalvao commented on Casks/wally.rb
> +  url 'https://configure.ergodox-ez.com/wally/osx'
Use the download from https://github.com/zsa/wally/releases, don’t forget [the comment](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/url.md#when-url-and-homepage-hostnames-differ-add-a-comment) (`github.com/zsa/wally …`).

2019-08-19 16:29 UTC, vitorgalvao commented on Casks/wally.rb
> +  url 'https://configure.ergodox-ez.com/wally/osx'
Also add an [`appcast`](https://github.com/homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/appcast.md).

2019-08-19 16:29 UTC, vitorgalvao commented
Welcome. This just needs a few fixes, and we can merge it.

2019-08-20 00:14 UTC, fdidron commented
Thanks @vitorgalvao for the pointers, I fixed the issues you reported.

2019-08-20 10:55 UTC, vitorgalvao approved these changes

2019-08-20 11:30 UTC, vitorgalvao commented
Submit to [homebrew/cask-drivers](https://github.com/Homebrew/homebrew-cask-drivers) instead, please.

2019-08-20 11:30 UTC, closed without merging