Add Runway ML
Homebrew/homebrew-cask pull request #68156
Opened 2019-08-26 10:54 UTC by fepegar

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused].
- [x] Checked the cask is submitted to [the correct repo].

The Download button says "Download Beta". The downloaded version is 0.9.2. Please let me know if there's any missing information.

I called it `runway-ml` because there's already a `runway` cask. The website uses both Runway and Runway ML anyways.

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

2019-08-26 23:38 UTC, vitorgalvao requested changes

2019-08-26 23:38 UTC, vitorgalvao commented on Casks/runway-ml.rb
> +  url "https://api.runwayml.com/v1/download\?platform\=mac"
`https://runway-releases.s3.amazonaws.com/Runway-#{version}.dmg`

2019-08-26 23:38 UTC, vitorgalvao commented on Casks/runway-ml.rb
> +  version :latest
`0.9.2`

2019-08-26 23:38 UTC, vitorgalvao commented on Casks/runway-ml.rb
> +cask 'runway-ml' do
The [token reference](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md) is explicit about token conflicts. The way to do it is to prefix the vendor name.

The other `runway` is unpopular enough that it can be renamed instead, this one becoming `runway`.

```
runway (added 123 days ago)
30 days: 6 (#3079)
90 days: 8 (#3994)
365 days: 13 (#5022)
```

2019-08-26 23:38 UTC, vitorgalvao commented on Casks/runway-ml.rb
> +  url "https://api.runwayml.com/v1/download\?platform\=mac"
Add an [`appcast`](https://github.com/homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/appcast.md) (`https://macupdater.net/cgi-bin/check_urls/check_url_redirect.cgi?url=https://api.runwayml.com/v1/download?platform=mac`).

2019-08-26 23:54 UTC, fepegar commented on Casks/runway-ml.rb
> +  url "https://api.runwayml.com/v1/download\?platform\=mac"
Hi @vitorgalvao, thanks for reviewing.

How did you find those two URLs?

2019-08-26 23:59 UTC, fepegar commented on Casks/runway-ml.rb
> +cask 'runway-ml' do
Shall I rename the other one to `celestialteapot-runway`?

2019-08-27 00:04 UTC, fepegar commented on Casks/runway-ml.rb
> +  version :latest
Should I add the `sha256` too?

2019-08-27 00:22 UTC, vitorgalvao commented on Casks/runway-ml.rb
> +  url "https://api.runwayml.com/v1/download\?platform\=mac"
The download link they have on the website redirects to the first one. The second one is a script provided by @core-code that shows the result of the redirection.

2019-08-27 00:22 UTC, vitorgalvao commented on Casks/runway-ml.rb
> +  version :latest
> Should I add the `sha256` too?

Yes.

2019-08-27 00:23 UTC, vitorgalvao commented on Casks/runway-ml.rb
> +cask 'runway-ml' do
> Shall I rename the other one to `celestialteapot-runway`?

Yes.

2019-08-27 00:28 UTC, fepegar commented on Casks/runway-ml.rb
> +  url "https://api.runwayml.com/v1/download\?platform\=mac"
Thanks, I'll take that into account and try to find those out next time I add a cask.

2019-08-27 00:35 UTC, fepegar commented
It seems that Travis doesn't like that I modified two casks in the same PR.

2019-08-27 12:22 UTC, merged