MagicCap 2.0.0
Homebrew/homebrew-cask pull request #68717
Opened 2019-09-06 11:45 UTC by dxf

After making all changes to the cask:

- [ x] `brew cask audit --download {{cask_file}}` is error-free.
- [ x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [ x] The commit message includes the cask’s name and version.
- [ x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [ x] Named the cask according to the [token reference].
- [ x] `brew cask install {{cask_file}}` worked successfully.
- [ x] `brew cask uninstall {{cask_file}}` worked successfully.
- [ x] Checked there are no [open pull requests] for the same cask.
- [ x] Checked the cask was not [already refused].
- [ x] Checked the cask is submitted to [the correct repo].
- [ x] Attempted to find an [appcast].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256
[appcast]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/appcast.md

2019-09-06 12:12 UTC, reitermarkus requested changes

2019-09-06 12:12 UTC, reitermarkus commented on Casks/magiccap.rb
> +  sha256 :no_check
This needs to be set.

2019-09-06 12:12 UTC, reitermarkus commented on Casks/magiccap.rb
> +  url 'https://github.com/magiccap/MagicCap/releases/download/v2.0.0/magiccap-mac.dmg'
Interpolate the version here.

2019-09-06 12:18 UTC, dxf commented on Casks/magiccap.rb
> +  url 'https://github.com/magiccap/MagicCap/releases/download/v2.0.0/magiccap-mac.dmg'
Sorry?

2019-09-06 12:18 UTC, dxf commented on Casks/magiccap.rb
> +  url 'https://github.com/magiccap/MagicCap/releases/download/v2.0.0/magiccap-mac.dmg'
Do you mean as in calculate the sha256?

2019-09-06 12:26 UTC, reitermarkus commented on Casks/magiccap.rb
> +  url 'https://github.com/magiccap/MagicCap/releases/download/v2.0.0/magiccap-mac.dmg'
Look at some other casks. Calculate the checksum and use `#{version}` in the URL.

2019-09-06 17:04 UTC, vitorgalvao commented on Casks/magiccap.rb
> +  # github.com/magiccap was verified as official when first introduced to the cask
```suggestion
  # github.com/magiccap/MagicCap was verified as official when first introduced to the cask
```

2019-09-11 21:09 UTC, bxio commented on Casks/magiccap.rb
> +  sha256 :no_check
```suggestion
  sha256 '8cebb0061062e03e54a71ff120a6c658a41bbf8952aadfd2945fd76808dc2cb6'
```

brew cask audit output:
`
➜ brew cask audit --download magiccap
==> Downloading https://github.com/magiccap/MagicCap/releases/download/v2.0.0/magiccap-mac.dmg
==> Downloading from https://github-production-release-asset-2e65be.s3.amazonaws.com/142702658/f8bc2480-
######################################################################## 100.0%
==> Verifying SHA-256 checksum for Cask 'magiccap'.
audit for magiccap: passed
`

2019-09-11 21:16 UTC, bxio commented on Casks/magiccap.rb
> +  url 'https://github.com/magiccap/MagicCap/releases/download/v2.0.0/magiccap-mac.dmg'
```suggestion
  url "https://github.com/magiccap/MagicCap/releases/download/v#{version}/magiccap-mac.dmg"
```

2019-09-26 07:45 UTC, dxf commented
Hey, committed all of you guys' changes

2019-09-26 17:45 UTC, merged