Add Dendroscope 3.6.3
Homebrew/homebrew-cask pull request #68789
Opened 2019-09-08 12:06 UTC by romainstuder

After making all changes to the cask:

- [ ] `brew cask audit --download {{cask_file}}` is error-free.
- [ ] `brew cask style --fix {{cask_file}}` reports no offenses.
- [ ] The commit message includes the cask’s name and version.
- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [ ] Named the cask according to the [token reference].
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked there are no [open pull requests] for the same cask.
- [ ] Checked the cask was not [already refused].
- [ ] Checked the cask is submitted to [the correct repo].
- [ ] Attempted to find an [appcast].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256
[appcast]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/appcast.md

2019-09-09 07:43 UTC, romainstuder commented
The line `installer script: 'Dendroscope Installer.app/Contents/MacOS/JavaApplicationStub'` opens a GUI interface which guide user in the installation process. While it works on my laptop, it makes the travis-ci to stall, with the alert: `WARNING: GL pipe is running in software mode`. Any suggestions? Otherwise I could put `installer manual: 'Dendroscope Installer.app/Contents/MacOS/JavaApplicationStub'` and the user has to manually open the link. But I found this less clean.

2019-09-09 13:58 UTC, vitorgalvao commented on Casks/dendroscope.rb
> +  uninstall script: '/Applications/Dendroscope/Dendroscope Uninstaller.app/Contents/MacOS/JavaApplicationStub'
Does this one call a GUI as well?

2019-09-09 13:59 UTC, vitorgalvao commented on Casks/dendroscope.rb
> +  installer script: 'Dendroscope Installer.app/Contents/MacOS/JavaApplicationStub'
We have other casks with `JavaApplicationStub` that use arguments to make a GUI-less install. Reference them to see if the same works here.

2019-09-09 13:59 UTC, vitorgalvao commented on Casks/dendroscope.rb
> +  homepage 'https://ab.inf.uni-tuebingen.de/software/dendroscope/welcome.html'
```suggestion
  homepage 'https://ab.inf.uni-tuebingen.de/software/dendroscope/'
```

2019-09-09 15:49 UTC, romainstuder commented on Casks/dendroscope.rb
> +  homepage 'https://ab.inf.uni-tuebingen.de/software/dendroscope/welcome.html'
Thanks!

2019-09-09 15:49 UTC, romainstuder commented on Casks/dendroscope.rb
> +  installer script: 'Dendroscope Installer.app/Contents/MacOS/JavaApplicationStub'
Thanks for the suggestion! I followed your advice and managed to build a working formula.

2019-09-10 14:12 UTC, vitorgalvao requested changes

2019-09-10 14:12 UTC, vitorgalvao commented on Casks/dendroscope.rb
> +  preflight do
Don’t use `preflight`, but `installer script:`, [like so](https://github.com/Homebrew/homebrew-cask/blob/4184d50d2d7fa4afb62e6c7eb6761ae5ac417c88/Casks/thinkorswim.rb).

2019-09-10 14:55 UTC, vitorgalvao commented
Incorrect indentations. Run the `fix` line again.

2019-09-10 15:11 UTC, romainstuder commented on Casks/dendroscope.rb
> +  preflight do
Thansk, this is now fixed.

2019-09-10 15:16 UTC, vitorgalvao commented
File is formatted with tabs instead of spaces; indentation in the `installer` and `uninstall` scripts is wrong. `brew cask style --fix` should correct all of those.

2019-09-10 15:20 UTC, romainstuder commented
> File is formatted with tabs instead of spaces; indentation in the `installer` and `uninstall` scripts is wrong. `brew cask style --fix` should correct all of those.

For some reasons, `brew cask style --fix` is not working on my Mac:

In Gemfile:
  mechanize was resolved to 2.7.6, which depends on
    http-cookie was resolved to 1.0.3, which depends on
      domain_name was resolved to 0.5.20190701, which depends on
        unf was resolved to 0.1.4, which depends on
          unf_ext


In Gemfile:
  ronn was resolved to 0.7.3, which depends on
    hpricot

In Gemfile:
  rubocop-performance was resolved to 1.4.1, which depends on
    rubocop was resolved to 0.74.0, which depends on
      jaro_winkler

2019-09-10 19:18 UTC, merged