Add Feishu 3.6.3
Homebrew/homebrew-cask pull request #68811
Opened 2019-09-09 03:40 UTC by boltomli

Feishu (Lark) is a tool to create team collaboration experiences.

After making all changes to the cask:

- [X] `brew cask audit --download {{cask_file}}` is error-free.
- [X] `brew cask style --fix {{cask_file}}` reports no offenses.
- [X] The commit message includes the cask’s name and version.
- [X] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [X] Named the cask according to the [token reference].
- [X] `brew cask install {{cask_file}}` worked successfully.
- [X] `brew cask uninstall {{cask_file}}` worked successfully.
- [X] Checked there are no [open pull requests] for the same cask.
- [X] Checked the cask was not [already refused].
- [X] Checked the cask is submitted to [the correct repo].
- [X] Attempted to find an [appcast].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256
[appcast]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/appcast.md

2019-09-09 14:01 UTC, vitorgalvao requested changes

2019-09-09 14:01 UTC, vitorgalvao commented on Casks/feishu.rb
> +cask 'feishu' do
Does not follow the [token reference](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).

2019-09-09 14:01 UTC, vitorgalvao commented on Casks/feishu.rb
> +  url "https://sf3-ttcdn-tos.pstatp.com/obj/ee-appcenter/Feishu_#{version}.dmg"
What methods have you tried to find the `appcast`?

2019-09-10 00:49 UTC, boltomli commented on Casks/feishu.rb
> +  url "https://sf3-ttcdn-tos.pstatp.com/obj/ee-appcenter/Feishu_#{version}.dmg"
I browsed the website, which didn't advertise change log explicitly. There might be some URL but I would need to find in the app's Content or monitor requests over network. The result will not be quite stable in future anyway.

2019-09-10 01:07 UTC, boltomli commented on Casks/feishu.rb
> +cask 'feishu' do
Thanks for the comment. I should have raised the question. The name is displayed (and widely referenced by the developer and users) as 'Feishu' in the dmg and after installation. The folder and executable name is Lark, though.

2019-09-10 14:21 UTC, vitorgalvao commented on Casks/feishu.rb
> +  url "https://sf3-ttcdn-tos.pstatp.com/obj/ee-appcenter/Feishu_#{version}.dmg"
We’re going to need some kind of appcast. What’s the download page?

2019-09-11 01:55 UTC, boltomli commented on Casks/feishu.rb
> +  url "https://sf3-ttcdn-tos.pstatp.com/obj/ee-appcenter/Feishu_#{version}.dmg"
The page is <https://www.feishu.cn/download>. I managed to dump the API URL to get all downloads and updated the cask.

2019-09-11 13:25 UTC, vitorgalvao commented on Casks/feishu.rb
> +  url "https://sf3-ttcdn-tos.pstatp.com/obj/ee-appcenter/Feishu_#{version}.dmg"
Fantastic. That’s ideal. Thank you.

2019-09-11 13:25 UTC, merged