Add Natron v2.3.14
Homebrew/homebrew-cask pull request #69106
Opened 2019-09-14 14:13 UTC by luzpaz

After making all changes to the cask:

- [ ] `brew cask audit --download {{cask_file}}` is error-free.
- [ ] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [ ] Named the cask according to the [token reference].
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [ ] Checked the cask was not [already refused].
- [x] Checked the cask is submitted to [the correct repo].
- [x] Attempted to find an [appcast].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256
[appcast]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/appcast.md

2019-09-14 14:20 UTC, luzpaz commented
Cask was deleted because it was pointing to old website pre-fork.  
ref: https://github.com/Homebrew/homebrew-cask/pull/67251  
I'm also exploring adding this to cask-versions because the beta releases are more frequent then stable.

2019-09-14 14:53 UTC, vitorgalvao requested changes

2019-09-14 14:53 UTC, vitorgalvao commented on Casks/natron.rb
> +  version :latest
Needs to be set.

2019-09-14 14:53 UTC, vitorgalvao commented on Casks/natron.rb
> +  sha256 :no_check
Needs to be set.

2019-09-14 14:53 UTC, vitorgalvao commented on Casks/natron.rb
> +  url 'https://github.com/NatronGitHub/Natron/releases/latest/download/Natron-2.3.14.dmg'
```suggestion
  url "https://github.com/NatronGitHub/Natron/releases/latest/download/Natron-#{version}.dmg"
```

2019-09-14 14:53 UTC, vitorgalvao commented on Casks/natron.rb
> +  url 'https://github.com/NatronGitHub/Natron/releases/latest/download/Natron-2.3.14.dmg'
Needs a comment above (`style` or `audit` will point it out).

2019-09-15 06:00 UTC, luzpaz commented
Thanks. Should be good to go

2019-09-15 10:35 UTC, merged