Add Samsung DeX 1.0.0.54
Homebrew/homebrew-cask pull request #69650
Opened 2019-09-25 02:24 UTC by kirb

After making all changes to the cask:

- [X] `brew cask audit --download {{cask_file}}` is error-free.
- [X] `brew cask style --fix {{cask_file}}` reports no offenses.
- [X] The commit message includes the cask’s name and version.
- [X] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [X] Named the cask according to the [token reference].
- [X] `brew cask install {{cask_file}}` worked successfully.
- [X] `brew cask uninstall {{cask_file}}` worked successfully.
- [X] Checked there are no [open pull requests] for the same cask.
- [X] Checked the cask was not [already refused].
- [X] Checked the cask is submitted to [the correct repo].
- [X] Attempted to find an [appcast].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256
[appcast]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/appcast.md

----

This is the DeX on PC client that provides a VNC-like Samsung DeX session from the phone over USB.

Some notes:

* The pkg forces a reboot. I tried manually `kextload`ing `ssuddrv.kext` after allowing it in the Security preferences, but it still didn’t work till I rebooted. Manual `kextload` won’t work before the user manually allows the kext publisher anyway.
* The uninstaller app (requires user input to continue, and won’t exit with failure on error, so Homebrew will think it’s uninstalled when it isn’t) can very likely be replaced with Cask uninstall stanzas. Aside from uninstalling all the pkgs, killing the processes, and unloading the kext, I don’t think it does anything special.
* Plenty of references to DevMate, but no DevMate appcast that I can see. Closest I can see is from the Info.plist, a URL that returns an auth error:

```xml
<key>LiveUpdate_Mode</key>
<string>A</string>
<key>LiveUpdate_URL</key>
<string>https://dopc-api.linuxondex.com</string>
```

2019-09-25 02:32 UTC, kirb commented
Hah, I put the file in the root dir instead of in Casks/. Amended with that fixed.

2019-09-28 12:34 UTC, vitorgalvao requested changes

2019-09-28 12:34 UTC, vitorgalvao commented on Casks/samsung-dex.rb
> +                      executable: "#{staged_path}/Uninstall.app/Contents/MacOS/Uninstall",
This is not a script, it’s just calling the app through the command-line. Please use the other uninstall options (`uninstall pkgutil:` and whatever else is necessary).

2019-09-28 12:36 UTC, kirb commented on Casks/samsung-dex.rb
> +                      executable: "#{staged_path}/Uninstall.app/Contents/MacOS/Uninstall",
Yes, I mentioned this. I’ll work on it then.

2020-01-03 01:03 UTC, vitorgalvao commented
Closing for lack of progress.

2020-01-03 01:03 UTC, closed without merging

2020-01-03 01:13 UTC, kirb commented
After some time I realised the USB DeX client is awful to use, compared to attaching keyboard/mouse/monitor directly to the phone. Even using USB-C over a Thunderbolt cable, it uses H.264 fixed at 1920x1080 on the video with unusable latency, by contrast a directly attached monitor runs at native resolution with no compression. I don’t think it’s right to have this in Cask, it feels like just a proof of concept/padding out a feature list. So I agree with closing this.