Firecamp v0.6.7 cask ready
Homebrew/homebrew-cask pull request #69727
Opened 2019-09-26 12:04 UTC by Nishchit14

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused].
- [x] Checked the cask is submitted to [the correct repo].
- [x] Attempted to find an [appcast].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256
[appcast]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/appcast.md

2019-09-26 19:57 UTC, vitorgalvao requested changes
You have an extraneous cask in your submission.

2019-09-26 19:57 UTC, vitorgalvao commented on Casks/firecamp.rb
> +  sha256 :no_check
`sha256` also needs to be set. You can find what it is by running `shasum --algorithm 256` on the downloaded file.

2019-09-26 19:57 UTC, vitorgalvao commented on Casks/firecamp.rb
> +  url "https://firecamp.ams3.digitaloceanspaces.com/versions/mac/Firecamp-#{version}.dmg"
I don’t see a macOS download on the website.

2019-09-27 05:59 UTC, Nishchit14 commented on Casks/firecamp.rb
> +  url "https://firecamp.ams3.digitaloceanspaces.com/versions/mac/Firecamp-#{version}.dmg"
Do you mean to say on `https://firecamp.app`?  It's necessary? We're planning to launch it on cask and will update the doc here https://firecamp.app/docs/installation/#mac

2019-09-27 06:07 UTC, Nishchit14 commented on Casks/firecamp.rb
> +  sha256 :no_check
Added, Thank you.

2019-09-27 11:29 UTC, vitorgalvao commented on Casks/firecamp.rb
> +  url "https://firecamp.ams3.digitaloceanspaces.com/versions/mac/Firecamp-#{version}.dmg"
> Do you mean to say on `https://firecamp.app`? It's necessary?

Yes.

> We're planning to launch it on cask and will update the doc here

You don’t “launch” on HBC, because we’re not an advertisement platform. We’re not HackerNews or ProductHunt, [you won’t get any more visibility by having a cask](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/not_a_discoverability_service.md).

We provide an easier installation method, but we need to follow the website. How can we or our users know you’re a legitimate author of this tool unless an official source says so? If there’s no public link to download the software *outside* of HBC, we won’t allow it *inside*.

2019-09-27 11:30 UTC, vitorgalvao commented on Casks/firecamp.rb
> +  url "https://firecamp.ams3.digitaloceanspaces.com/versions/mac/Firecamp-#{version}.dmg"
You still have the extraneous cask in this PR.

2019-09-27 12:56 UTC, Nishchit14 commented on Casks/firecamp.rb
> +  url "https://firecamp.ams3.digitaloceanspaces.com/versions/mac/Firecamp-#{version}.dmg"
Thanks, @vitorgalvao,  It's live now here https://firecamp.app/docs/installation/#mac

2019-09-28 04:52 UTC, Nishchit14 commented
Thanks, @vitorgalvao for th review, 
Mac download like is here on the website,  https://firecamp.app/docs/installation/#mac

2019-09-28 11:56 UTC, vitorgalvao requested changes

2019-09-28 11:56 UTC, vitorgalvao commented on Casks/firecamp.rb
> +  url "https://firecamp.ams3.digitaloceanspaces.com/versions/mac/Firecamp-#{version}.dmg"
You still have an extraneous cask commit, to `datagrip`, in this PR. Until you remove that, this won’t be merged.

2019-09-28 19:00 UTC, vitorgalvao approved these changes

2019-09-28 19:08 UTC, Nishchit14 commented
Creating new fresh PR... and closing this one.

2019-09-28 19:08 UTC, closed without merging