Add "Mission Control Plus.app" v1.1
Homebrew/homebrew-cask pull request #69785
Opened 2019-09-27 05:31 UTC by ronyfadel

A user requested my app, Mission Control Plus to be added to cask.
The app's webpage can be found at: https://fadel.io/MissionControlPlus
It provides a 10 day trial with in-app activation.

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [ ] `brew cask style --fix {{cask_file}}` reports no offenses.
^ I was not able to run 'brew cask style':

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
An error occurred while installing json (2.2.0), and Bundler cannot continue.
Make sure that `gem install json -v '2.2.0' --source 'https://rubygems.org/'` succeeds before bundling.
An error occurred while installing unf_ext (0.0.7.6), and Bundler cannot continue.
Make sure that `gem install unf_ext -v '0.0.7.6' --source 'https://rubygems.org/'` succeeds before bundling.

- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused].
- [x] Checked the cask is submitted to [the correct repo].
- [x] Attempted to find an [appcast].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256
[appcast]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/appcast.md

2019-09-27 11:51 UTC, vitorgalvao requested changes

2019-09-27 11:51 UTC, vitorgalvao commented on Casks/mission-control-plus.rb
> +  url "https://github.com/ronyfadel/MissionControlPlusReleases/releases/download/v#{version}/Mission_Control_Plus.zip"
We’ll need a link from the homepage to the github repo, to verify this is accurate.

2019-09-27 13:55 UTC, ronyfadel commented on Casks/mission-control-plus.rb
> +  url "https://github.com/ronyfadel/MissionControlPlusReleases/releases/download/v#{version}/Mission_Control_Plus.zip"
A link is already available. Check the source of the web page at:

https://fadel.io/MissionControlPlus

The download button links to the url provided above

2019-09-28 12:38 UTC, vitorgalvao approved these changes

2019-09-28 13:03 UTC, merged