find_appcast: detect electron-builder appcasts
Homebrew/homebrew-cask pull request #69968
Opened 2019-10-01 11:24 UTC by amyspark

After making all changes to the cask:

- [ ] `brew cask audit --download {{cask_file}}` is error-free.
- [ ] `brew cask style --fix {{cask_file}}` reports no offenses.
- [ ] The commit message includes the cask’s name and version.
- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [ ] Named the cask according to the [token reference].
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked there are no [open pull requests] for the same cask.
- [ ] Checked the cask was not [already refused].
- [ ] Checked the cask is submitted to [the correct repo].
- [ ] Attempted to find an [appcast].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256
[appcast]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/appcast.md

---

Fixes Homebrew/homebrew-cask#69749.

2019-10-01 18:02 UTC, vitorgalvao requested changes

2019-10-01 18:03 UTC, vitorgalvao commented
I’d rather not have a separate script just for this. We can either convert everything to ruby or convert the new script to bash (since keys are pretty consistent `key: value`, it should work).

I haven’t had the chance to look yet, but did you see if there are other providers? Some other apps to check are in https://github.com/Homebrew/homebrew-cask/pull/69611#issuecomment-535681740.

2019-10-01 23:30 UTC, amyspark commented
@vitorgalvao I've made the changes you requested! As regards the Bash-vs-Ruby point: I know  Ruby can parse YAML with just two lines, that's why I stuck with it and called the helper from the main script.

2019-10-01 23:46 UTC, vitorgalvao commented on developer/bin/find_appcast
> +  electron_parser_script="$(brew --repo homebrew/cask)/developer/bin/parse_electron_builder_appcast"
Nice one! `brew --repo` is even better.

2019-10-01 23:48 UTC, merged

2019-10-25 13:56 UTC, core-code commented
i've found another one that eludes the find_appcast search for an electron appcast:

https://s3.amazonaws.com/sm-app-updates/public/Smartmockups-2.7.3.dmg

2019-10-25 14:27 UTC, vitorgalvao commented
@core-code Fixing in https://github.com/Homebrew/homebrew-cask/pull/71459.