Update mysqlworkbench from 8.0.18 to 6.3.10
Homebrew/homebrew-cask pull request #70877
Opened 2019-10-15 19:13 UTC by ottnorml

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

2019-10-15 19:18 UTC, ottnorml commented on Casks/mysqlworkbench.rb
> +    sha256 :no_check
The checksum should be `29857bf84bebb7c4442ce147e44602d00f8c001e3c09b3a6e3af356767e08d2c`, but `brew cask style --fix` replaced it. How can I fix that?

2019-10-15 20:01 UTC, vitorgalvao requested changes

2019-10-15 20:01 UTC, vitorgalvao commented on Casks/mysqlworkbench.rb
> +    sha256 :no_check
This still needs to be set.

2019-10-15 20:38 UTC, ottnorml commented on Casks/mysqlworkbench.rb
> +    sha256 :no_check
I added the checksum in 6836936.

2019-10-15 20:39 UTC, vitorgalvao commented
Looking good. Thank you.

2019-10-15 20:40 UTC, vitorgalvao approved these changes

2019-10-15 21:00 UTC, ottnorml commented
@vitorgalvao Do you have an idea, why the `xcode10.1` Travis build ([143135.1](https://travis-ci.com/Homebrew/homebrew-cask/jobs/245980573)) is failing?

2019-10-15 21:31 UTC, reitermarkus commented
The `appcast` doesn't apply for the High Sierra version.

2019-10-15 21:44 UTC, ottnorml commented
@reitermarkus Is this a problem? `find_appcast` did not find anything and I did not change it.

2019-10-15 21:48 UTC, vitorgalvao commented
> The `appcast` doesn't apply for the High Sierra version.

Technically it does, because it links back to the `6.3` versions. But presumably version 6 won’t get further updates, so it shouldn’t be a problem (if it is, we can just stick the `appcast` in the conditional).

2019-10-16 03:03 UTC, John-Dennert commented
Per https://dev.mysql.com/downloads/workbench/, MySQL Workbench 8.0.18 works with High Sierra. "Packages for Mojave (10.14) are compatible with High Sierra (10.13)"

2019-10-16 08:24 UTC, ottnorml commented
> Per https://dev.mysql.com/downloads/workbench/, MySQL Workbench 8.0.18 works with High Sierra. "Packages for Mojave (10.14) are compatible with High Sierra (10.13)"
In this case, it must be new in version 8.0.18, because the program in version 8.0.17 with High Sierra refused to run (see #69926).

2019-10-17 14:21 UTC, ottnorml commented
![Screenshot](https://user-images.githubusercontent.com/2350859/67017185-a78bf100-f0f9-11e9-9045-4fee3518bad3.png)
As you can see from the screenshot, version `8.0.18` is not compatible with High Sierra.

2019-10-17 15:06 UTC, ottnorml commented
@vitorgalvao  & @reitermarkus How do we continue?

2019-10-18 11:12 UTC, merged