Add platelet.app Latest
Homebrew/homebrew-cask pull request #71583
Opened 2019-10-28 08:50 UTC by amorist

After making all changes to the cask:

- [ ] `brew cask audit --download {{cask_file}}` is error-free.
- [ ] `brew cask style --fix {{cask_file}}` reports no offenses.
- [ ] The commit message includes the cask’s name and version.
- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [ ] Named the cask according to the [token reference].
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked there are no [open pull requests] for the same cask.
- [ ] Checked the cask was not [already refused].
- [ ] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

2019-10-28 12:09 UTC, vitorgalvao requested changes

2019-10-28 12:09 UTC, vitorgalvao commented on Casks/platelet.rb
> +  name 'platelet'
```suggestion
  name 'Platelet'
  name 'けっしょうばん'
```

2019-10-28 12:09 UTC, vitorgalvao commented on Casks/platelet.rb
> +  url "https://github.com/amorist/platelet/releases/download/v0.0.13/platelet-0.0.13.dmg"
```suggestion
  url "https://github.com/amorist/platelet/releases/download/v#{version}/platelet-#{version}.dmg"
```

2019-10-28 12:09 UTC, vitorgalvao commented on Casks/platelet.rb
> +  appcast 'https://github.com/amorist/platelet/releases.atom'
This is fixed by the `brew cask style --fix`. Please make sure to follow the commands *before* checking the boxes.

2019-10-29 01:20 UTC, amorist commented
Thanks.

2019-10-29 02:53 UTC, merged