Add Cisco Webex Meetings
Homebrew/homebrew-cask pull request #72713
Opened 2019-11-16 01:56 UTC by optix2000

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
Non versioned downloads. Webex also auto-updates itself.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

2019-11-16 01:58 UTC, optix2000 commented
Not sure how to clean up some of the App Support stuff, as Webex sometimes downloads stuff with version numbers appended (ie `T33_64UMC_39.9.5.164`).

I'm 80% sure the whole `WebEx Folder` is nukable on uninstall, but I put it under `zap` to be safe.

2019-11-16 02:08 UTC, optix2000 commented
Also on my local machine which is running OSX `10.15.1 (19B88)` it installs to `/Application/Cisco Webex Meetings.app`, but on Travis (OSX 10.13 and 10.14) it's installing to `/Application/Webex/` and it comes with an `Uninstall.app`.

Ideally I'd say uninstall should call the Uninstall app if it exists, but most (if not all) the uninstall steps should have been taken care of through the Cask itself. What's everyone else's thoughts on this?

2019-11-17 22:07 UTC, vitorgalvao requested changes

2019-11-17 22:07 UTC, vitorgalvao commented on Casks/webex-meetings.rb
> +                         '/Applications/Webex', # App gets installed to different places depending on OSX version
`macOS`, not `OSX`.

2019-11-17 22:07 UTC, vitorgalvao commented on Casks/webex-meetings.rb
> +                         '/Applications/Cisco\ Webex\ Meetings.app',
Don’t escape spaces. The string is in quotes, so the `\` are taken literally.

2019-11-18 18:33 UTC, optix2000 commented on Casks/webex-meetings.rb
> +                         '/Applications/Cisco\ Webex\ Meetings.app',
Bad copy paste, though it seems to work in testing.

2019-11-19 08:19 UTC, reitermarkus approved these changes

2019-11-19 16:32 UTC, merged