Backblaze
Homebrew/homebrew-cask pull request #72782
Opened 2019-11-18 21:02 UTC by danielbayley

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [ ] Named the cask according to the [token reference].
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked there are no [open pull requests] for the same cask.
- [ ] Checked the cask was not [already refused].
- [ ] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

2019-11-19 01:14 UTC, vitorgalvao commented on Casks/backblaze.rb
> +  if ARGV.include? 'upgrade'
Nice idea.

@reitermarkus Is there anything we can use here other than `ARGV`? Like `brew.arguments` or some array we can keep and reference, that would be more resilient?

2019-11-19 01:18 UTC, vitorgalvao commented on Casks/backblaze.rb
> +  if ARGV.include? 'upgrade'
On second thought, might not work since `upgrade` means `uninstall && install`.

2019-11-22 16:09 UTC, danielbayley commented
> On second thought, might not work since upgrade means uninstall && install

@vitorgalvao I can confirm this works nicely and avoids having to manually reinstall Backblaze every time there is an update…

2019-11-23 16:35 UTC, reitermarkus commented on Casks/backblaze.rb
> +  if ARGV.include? 'upgrade'
> might not work

Depends on what the script does. Anyways, this is a hacky workaround. I don't think the contents of a cask should depend on which command is called.

2019-11-29 00:00 UTC, vitorgalvao commented on Casks/backblaze.rb
> +  if ARGV.include? 'upgrade'
I agree the current implementation is hacky, but I also think the idea has merit. Other casks would benefit from something like this. An example is [`lulu`](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/lulu.rb) which gets rid (used to get rid?) of the user’s configuration on uninstall, making upgrades through us a pain.

2019-12-12 04:12 UTC, vitorgalvao requested changes

2019-12-12 04:12 UTC, vitorgalvao commented on Casks/backblaze.rb
> +  if ARGV.include? 'upgrade'
@danielbayley If you want, you can open an issue for the discussion of this method or alternatives. But as of right now, since we don’t have consensus, please remove this so we can merge the other changes.

2020-01-03 01:00 UTC, vitorgalvao commented
@danielbayley Still interested in getting this merged?

2020-01-03 16:09 UTC, danielbayley commented
> @danielbayley Still interested in getting this merged?

@vitorgalvao Hey, happy new year! Yeah, I've just been extremely busy… But sure, I will open another issue and address this when I get chance…

2020-01-03 16:11 UTC, vitorgalvao commented
> Hey, happy new year!

Thank you. Happy new year to you!

> I've just been extremely busy

Good things, I hope!

> I will open another issue and address this when I get chance

In that case I’ll close this one.

2020-01-03 16:18 UTC, danielbayley commented
> Good things, I hope!

Mostly! :)

> In that case I’ll close this one.

@vitorgalvao But I think some of the changes in this PR can still be merged after I amend it further, which I'll get around to shortly…

2020-01-03 23:41 UTC, danielbayley commented
> But I think some of the changes in this PR can still be merged after I amend it further, which I'll get around to shortly…

@vitorgalvao Done.

2020-01-04 02:39 UTC, vitorgalvao requested changes

2020-01-04 02:39 UTC, vitorgalvao commented on Casks/backblaze.rb
> +  uninstall launchctl: ['com.backblaze.bzserv', 'com.backblaze.bzbmenu'],
Have these in multiple lines, like other casks do.

2020-01-06 01:38 UTC, vitorgalvao approved these changes

2020-01-06 01:46 UTC, merged

2020-01-06 18:19 UTC, JamesChevalier commented
This is the first time that I've noticed a cask where the download link is not versioned, and the cask's `version` is not set to `:latest`.

I have a number of casks that show `(latest) != latest` in the output of `brew cask outdated --greedy`, so I'm wondering if those casks can be improved in the same manner that you've accomplished here.

Can you explain how you were able to do this?
It looks like it's a combination of the `version` and `sha256` line changes, but I'm unsure if the `appcast` line change is also playing a role here.

2020-01-06 18:23 UTC, vitorgalvao commented
> but I'm unsure if the `appcast` line change is also playing a role here.

It is *the* line playing a role. Find an [`appcast`](https://github.com/homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/appcast.md) and the cask shall be converted to a versioned cask, even if the `url` isn’t.

2020-01-06 23:36 UTC, JamesChevalier commented
hrm. I upgraded my installed cask to this version, and Backblaze would not open again. Manually downloading/installing got it working again.

After I did that, I noticed that the version on the website is now 7.0.0.402 so I tried doing a `cask-repair backblaze` to contribute an update. This attempt didn't change the `sha256` line, so I canceled the process. 🤷‍♂ 

🤔 I'm not sure I like this new approach (not that manually upgrading Backblaze was nice lol).

2020-01-06 23:46 UTC, vitorgalvao commented
> I'm not sure I like this new approach

The changes have nothing to do with your error.