Update calibre.rb
Homebrew/homebrew-cask pull request #73198
Opened 2019-11-26 19:40 UTC by waldemarKunkel

After making all changes to the cask:

- [ ] `brew cask audit --download {{cask_file}}` is error-free.
- [ ] `brew cask style --fix {{cask_file}}` reports no offenses.
- [ ] The commit message includes the cask’s name and version.
- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [ ] Named the cask according to the [token reference].
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked there are no [open pull requests] for the same cask.
- [ ] Checked the cask was not [already refused].
- [ ] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

2019-11-26 23:24 UTC, vitorgalvao requested changes

2019-11-26 23:24 UTC, vitorgalvao commented on Casks/calibre.rb
> +  if MacOS.version <= '10.8'
Too far back. Remove this conditional.

2019-11-26 23:24 UTC, vitorgalvao commented on Casks/calibre.rb
> +  elsif MacOS.version <= :high_sierra
Do *you* need this version?

2019-11-27 09:25 UTC, waldemarKunkel commented on Casks/calibre.rb
> +  elsif MacOS.version <= :high_sierra
I'm on high sierra so the newest version for me is 3.48.0

2019-11-27 18:21 UTC, merged