add sizzy: The browser for developers and designers
Homebrew/homebrew-cask pull request #73243
Opened 2019-11-27 06:55 UTC by bkbabydp

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

2019-11-27 14:28 UTC, vitorgalvao requested changes
Please be sure to run the commands in the template before submission. A few of the errors would have been caught beforehand.

2019-11-27 14:28 UTC, vitorgalvao commented on Casks/sizzy.rb
> +  name 'Sizzy'
Please add an [`appcast`](https://github.com/homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/appcast.md): `https://headway-widget.net/widgets/JAXRr7`.

2019-11-27 14:28 UTC, vitorgalvao commented on Casks/sizzy.rb
> +  version :latest
`0.11`

2019-11-27 14:28 UTC, vitorgalvao commented on Casks/sizzy.rb
> +  sha256 :no_check
Also needs to be set.

2019-11-29 03:00 UTC, dz85 reviewed
I've changed this one, but brew cask style sizzy still failed. why? Help me.

2019-11-29 13:19 UTC, vitorgalvao requested changes

2019-11-29 13:19 UTC, vitorgalvao commented on Casks/sizzy.rb
> +  url "https://sizzy.co/get-app"
Needs to use single quotes.

2019-11-29 13:21 UTC, vitorgalvao commented
> I've changed this one, but brew cask style sizzy still failed. why?

That’s why you need to follow the template. Those commands tell you what’s wrong, and in some cases auto-fix it.

2019-11-30 02:02 UTC, bkbabydp commented
> > I've changed this one, but brew cask style sizzy still failed. why?
> 
> That’s why you need to follow the template. Those commands tell you what’s wrong, and in some cases auto-fix it.

Sorry and thx, let me try the template :)

2019-11-30 05:18 UTC, bkbabydp commented
so bad!.. failed again

2019-11-30 05:30 UTC, bkbabydp commented
> > I've changed this one, but brew cask style sizzy still failed. why?
> 
> That’s why you need to follow the template. Those commands tell you what’s wrong, and in some cases auto-fix it.

so bad!.. failed again

and another one , `brew cask info wechat`, it's outdated too. and i try to use `cask-repair` and it failed with the same error - `brew cask style wechat`. why?

do u have more efficient communication methods with u. 'cos i feel that the github comment is too inefficient.

2019-11-30 06:38 UTC, ran-dall commented
https://github.com/Homebrew/homebrew-cask/pull/73391#issuecomment-559876422

2019-12-01 22:58 UTC, merged