Add AuroraHDR
Homebrew/homebrew-cask pull request #73576
Opened 2019-12-03 17:21 UTC by mofneko

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).
- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused].
- [x] Checked the cask is submitted to [the correct repo].

2019-12-03 17:40 UTC, core-code commented
here is a real sparkle appcast
`http://aurorahdr2019mac.update.skylum.com`

2019-12-03 22:01 UTC, vitorgalvao requested changes

2019-12-03 22:01 UTC, vitorgalvao commented on Casks/aurora-hdr.rb
> +                      '/Applications/Aurora\ HDR\ 2019.app',
Don’t escape spaces. Since these are between quotes, `\` is taken literally.

2019-12-03 22:01 UTC, vitorgalvao commented on Casks/aurora-hdr.rb
> +  name 'AuroraHDR'
```suggestion
  name 'Aurora HDR'
```

(with a space)

Also, please add the original Japanese name in a new `name` underneath.

2019-12-03 22:55 UTC, mofneko commented on Casks/aurora-hdr.rb
> +  app 'Aurora HDR 2019 Installer.app'
Do you need to automate the installation? The user originally needs to agree to the terms of service in the installer.

2019-12-03 22:57 UTC, mofneko commented on Casks/aurora-hdr.rb
> +  name 'AuroraHDR'
I think this product has the English name as described.

2019-12-03 22:59 UTC, mofneko commented
Thank you for the correction. If necessary, I rewind the commit and force push.

2019-12-03 22:59 UTC, vitorgalvao commented on Casks/aurora-hdr.rb
> +  name 'AuroraHDR'
Yes, but we’d like to have both.

2019-12-03 23:00 UTC, vitorgalvao commented on Casks/aurora-hdr.rb
> +  app 'Aurora HDR 2019 Installer.app'
`installer :manual` won’t automate the installation, it will tell the user that they still need to run the app to finish installing.

The uninstallation does have to be automated, though.

2019-12-03 23:05 UTC, mofneko commented on Casks/aurora-hdr.rb
> +  name 'AuroraHDR'
I'm sorry. There was a shortage in my explanation.
There is no Japanese name for this software.

2019-12-03 23:07 UTC, mofneko commented on Casks/aurora-hdr.rb
> +  app 'Aurora HDR 2019 Installer.app'
I understand and correct your indication. please confirm.

2019-12-03 23:23 UTC, mofneko commented
This software seems to have a special version numbering.
sparkle: version = "5825" sparkle: shortVersionString = "1.0.0"

2019-12-03 23:25 UTC, vitorgalvao commented
> This software seems to have a special version numbering.
> sparkle: version = "5825" sparkle: shortVersionString = "1.0.0"

That’s common, don’t worry about it.

2019-12-04 00:51 UTC, vitorgalvao commented on Casks/aurora-hdr.rb
> +  uninstall delete: [
Were you able to find official uninstall instructions?

2019-12-04 01:00 UTC, mofneko commented on Casks/aurora-hdr.rb
> +  uninstall delete: [
It conforms to the uninstallation path of the official Japanese reseller support site.
https://www.swtoo.com/support/skylum/aurorahdr/tech-aurorahdr/aurorahdr-uninstall/

2019-12-04 01:50 UTC, vitorgalvao commented on Casks/aurora-hdr.rb
> +  app 'Aurora HDR 2019.app'
The download from the appcast is not an installer.

2019-12-04 01:50 UTC, vitorgalvao approved these changes

2019-12-04 01:58 UTC, merged