Create knotes2.rb
Homebrew/homebrew-cask pull request #73754
Opened 2019-12-06 03:21 UTC by Chandler-Lu

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

2019-12-06 15:17 UTC, vitorgalvao requested changes

2019-12-06 15:17 UTC, vitorgalvao commented on Casks/knotes2.rb
> +  name '糯词笔记'
It need the english `name` above

2019-12-06 15:18 UTC, Chandler-Lu commented on Casks/knotes2.rb
> +  name '糯词笔记'
Knotes2

2019-12-06 15:21 UTC, vitorgalvao commented on Casks/knotes2.rb
> +  name '糯词笔记'
*Above*, not instead of.

2019-12-06 15:21 UTC, vitorgalvao submitted a review, later dismissed

2019-12-06 15:26 UTC, vitorgalvao requested changes

2019-12-06 15:26 UTC, vitorgalvao commented on Casks/knotes2.rb
> +cask 'knotes2' do
This does not conform to the [token reference](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md). Versions numbers are not to be included. Please follow that document and add the appropriate vendor prefix.

2019-12-06 15:29 UTC, Chandler-Lu commented on Casks/knotes2.rb
> +  name '糯词笔记'
tks~I update it

2019-12-06 16:25 UTC, vitorgalvao requested changes

2019-12-06 16:25 UTC, vitorgalvao commented on Casks/knotes2.rb
> +cask 'knotesapp' do
Please read the [token reference](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md) document, as requested. We don’t add `app` to names of apps, it has to be a **prefix** with the vendor’s name. So if this was made by Apple, for example, you’d call it `apple-knotes`.

2019-12-07 12:17 UTC, Chandler-Lu commented on Casks/knotes2.rb
> +cask 'knotesapp' do
Sorry, I change it~

2019-12-07 12:35 UTC, vitorgalvao commented on Casks/knotes2.rb
> +cask 'mhz-knotes' do
Could you explain how you arrived at `mhz`, so we’re clear on the rationale?

Also, don’t forget the file name, it needs to match this token.

2019-12-07 12:49 UTC, Chandler-Lu commented on Casks/knotes2.rb
> +cask 'mhz-knotes' do
The developer's company is called "一兆赫兹(Megahertz)"

2019-12-07 13:12 UTC, vitorgalvao commented on Casks/knotes2.rb
> +cask 'mhz-knotes' do
Then make it `megahertz`, not `mhz`.

2019-12-07 13:46 UTC, Chandler-Lu commented on Casks/knotes2.rb
> +cask 'mhz-knotes' do
OK

2019-12-07 14:59 UTC, merged