Fix Native Access Cask
Homebrew/homebrew-cask pull request #73867
Opened 2019-12-08 01:49 UTC by danielbayley

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x]  The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [ ] Named the cask according to the [token reference].
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked there are no [open pull requests] for the same cask.
- [ ] Checked the cask was not [already refused].
- [ ] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

2019-12-12 04:09 UTC, vitorgalvao commented on Casks/native-access.rb
> +  appcast "https://native-instruments.com/forum/threads/official-update-status-native-access-current-version-#{version.major_minor_patch.dots_to_hyphens}.313999",
Doesn’t the `.313999` change?

2019-12-12 04:10 UTC, vitorgalvao requested changes

2019-12-12 04:10 UTC, vitorgalvao commented on Casks/native-access.rb
> +            rmdir:     '/Library/Application Support{/Native Instruments{/*,},}'
These are getting confusing. It’s one thing to do them in huge casks, but on smaller casks this will only confuse other users. Please don’t use anything more complicated than `*`.

2019-12-12 04:10 UTC, vitorgalvao commented on Casks/native-access.rb
> +               '/Library/Application Support{/Native Instruments{/*,},}',
Same as the comment above

2020-01-03 00:59 UTC, vitorgalvao commented
@danielbayley Pinging to know if you’re still interested in doing this (with the changes).

2020-01-03 16:11 UTC, danielbayley commented
> @danielbayley Pinging to know if you’re still interested in doing this (with the changes).

@vitorgalvao Yeah sure, I'll get around to it soon…

2020-01-03 16:12 UTC, danielbayley commented on Casks/native-access.rb
> +  appcast "https://native-instruments.com/forum/threads/official-update-status-native-access-current-version-#{version.major_minor_patch.dots_to_hyphens}.313999",
Actually no, I don't think so, as it's a pinned forum post with official release notes.

2020-01-03 16:12 UTC, danielbayley commented on Casks/native-access.rb
> +            rmdir:     '/Library/Application Support{/Native Instruments{/*,},}'
@vitorgalvao I agree. But this is exactly why I raised issue #67806, which you closed… it's a recurring problem I come across all the time when adding `rmdir:`. This kind of brace expansion was the only solution suggested [here](https://github.com/Homebrew/homebrew-cask/issues/67806#issuecomment-522380747) by @reitermarkus.

As I stated [here](https://github.com/Homebrew/homebrew-cask/issues/67806#issuecomment-546115001):
> I still think `rmdir:` should work recursively on empty folders though… save using brace expansion.

But the point was never acknowledged…

2020-01-03 16:24 UTC, vitorgalvao commented on Casks/native-access.rb
> +            rmdir:     '/Library/Application Support{/Native Instruments{/*,},}'
> But the point was never acknowledged…

To clarify, I agree with having `rmdir:` be recursive. But I don’t see anyone with enough interest to *implement* the feature, hence the closing.

2020-01-03 16:25 UTC, vitorgalvao commented on Casks/native-access.rb
> +            rmdir:     '/Library/Application Support{/Native Instruments{/*,},}'
> But the point was never acknowledged…

To clarify, I agree with having rmdir: be recursive. But I don’t see anyone with enough interest to implement the feature, hence the closing.

2020-01-03 22:43 UTC, vitorgalvao commented
Thank you.

2020-01-03 22:43 UTC, merged

2020-01-05 21:20 UTC, ErikMinekus commented
1. This cask now fails to upgrade with the message:
```
Error: Directory not empty @ dir_s_rmdir - /Applications/Native Access.app
```

2. Native Access auto-updates, so I don't understand why the cask now has a `version`, `sha256` and `appcast`. It should just have the `auto_updates` stanza.

3.
```
rmdir:     [
                         '/Library/Application Support/Native Instruments/*',
                         '/Library/Application Support/Native Instruments',
                       ]
```
```
      rmdir: [
               '/Library/Application Support/Native Instruments/*',
               '/Library/Application Support/Native Instruments',
               '~/Library/Application Support/Native Instruments',
```
Other Native Instruments apps are installed in this directory. They will now break when you uninstall Native Access.

4.
```
  zap trash: [
               '/Library/Application Support/Native Instruments/Service Center/NativeAccess.xml',
...
               '~/Library/Application Support/Native Instruments/Service Center',
```
Service Center is a different app, it shouldn't be removed.

2020-01-06 00:32 UTC, danielbayley commented
> Native Access auto-updates, so I don't understand why the cask now has a version, sha256 and appcast. It should just have the auto_updates stanza.

I did forget to add `auto_updates true`… but other casks have all 4.

> Other Native Instruments apps are installed in this directory. They will now break when you uninstall Native Access.

Surely not, because `rmdir:` only removes empty folders… So if other NI apps remain installed and have data stored here, nothing would happen… or am I missing something @ErikMinekus?

> Service Center is a different app, it shouldn't be removed.

Is it not the precursor to Native Access? I could be wrong… but I seem to remember Service Centre replacing itself with Native Access (through it's own auto update)… apparently leaving behind some files. Also `NativeAccess.xml` clearly is related…

2020-01-06 01:40 UTC, vitorgalvao commented
> Native Access auto-updates, so I don't understand why the cask now has a `version`, `sha256` and `appcast`. It should just have the `auto_updates` stanza.

Those are not interdependent. Having `auto_updates` does not preclude the other three, and is the least important of the four.

2020-01-06 20:23 UTC, ErikMinekus commented
> Surely not, because `rmdir:` only removes empty folders… So if other NI apps remain installed and have data stored here, nothing would happen… or am I missing something @ErikMinekus?

I still wouldn't want a Cask to touch folders for other apps, even if they're empty. And what if the implementation for `rmdir` changes in the future and it does remove folders with files?

> Is it not the precursor to Native Access? I could be wrong… but I seem to remember Service Centre replacing itself with Native Access (through it's own auto update)… apparently leaving behind some files. Also `NativeAccess.xml` clearly is related…

Service Center has indeed been replaced by Native Access, but I still have both installed. I can still launch Service Center (on macOS Mojave at least) and it doesn't replace itself. And again, I don't think Casks should touch files and folders from other apps.

2020-01-06 20:30 UTC, vitorgalvao commented
> I still wouldn't want a Cask to touch folders for other apps

In a `zap`, that’s fair game and [covered by the documentation](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/zap.md). `uninstall` is more conservative. There’s a reason we have both.

> And what if the implementation for `rmdir` changes in the future and it does remove folders with files?

Then it would no longer be `rmdir`. The chance of that happening is essentially nil. We already have `delete`; `rmdir` only exists because it only removes empty directories.