Update openvanilla from 1.4.0 to 1.5.0
Homebrew/homebrew-cask pull request #74051
Opened 2019-12-11 17:53 UTC by CryoRenegade

After making all changes to the cask:

- [ ] `brew cask audit --download {{cask_file}}` is error-free.
- [ ] `brew cask style --fix {{cask_file}}` reports no offenses.
- [ ] The commit message includes the cask’s name and version.
- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

2019-12-11 18:10 UTC, CryoRenegade commented
Looks lie the .app is no longer available in the installer app and has been replaced with a terminal executable.

2019-12-11 19:01 UTC, CryoRenegade commented
Yea, i have no idea how to reformat the .rb to make the app, help is welcome!

2019-12-11 23:04 UTC, vitorgalvao commented
You’ll need to replace `input_method` with an [`installer :manual`](https://github.com/homebrew/homebrew-cask/blob/c129758c8086d86b3d33cc8c2045b4a26bee2a83/doc/cask_language_reference/stanzas/installer.md#installer-manual). It will also require [`uninstall`](https://github.com/homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/uninstall.md).

2019-12-13 17:17 UTC, vitorgalvao requested changes

2019-12-13 17:17 UTC, vitorgalvao commented on Casks/openvanilla.rb
> +  uninstall
This is not a valid `uninstall` stanza. Please see the linked documentation.

Also, as it is, the cask wouldn’t pass `style`.

2019-12-13 21:57 UTC, vitorgalvao commented
Found a better method: https://github.com/Homebrew/homebrew-cask/pull/74196.

Thank you anyway for your work here.

2019-12-13 21:57 UTC, closed without merging