Add tableau-log-viewer v1.2
Homebrew/homebrew-cask pull request #75255
Opened 2020-01-08 21:14 UTC by aogail

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

2020-01-08 21:22 UTC, schwedenmut commented on Casks/tableau-log-viewer.rb
> +  url 'https://github.com/tableau/tableau-log-viewer/releases/download/1.2/tlv-osx-1.2.zip'
What about using the defined version in the url. Would look like this:
url 'https://github.com/tableau/tableau-log-viewer/releases/download/#{version}/tlv-osx-#{version}.zip'

2020-01-08 21:23 UTC, vitorgalvao requested changes

2020-01-08 21:23 UTC, vitorgalvao commented on Casks/tableau-log-viewer.rb
> +cask 'tableau-log-viewer' do
Needs to follow the [token reference](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md), meaning it needs to be `tlv`.

2020-01-08 21:28 UTC, aogail commented on Casks/tableau-log-viewer.rb
> +cask 'tableau-log-viewer' do
Is there a preference for tokenizing the file name instead of the full name from docs?

2020-01-10 02:48 UTC, vitorgalvao commented on Casks/tableau-log-viewer.rb
> +cask 'tableau-log-viewer' do
It’s not a preference, it’s a requirement. The token reference goes into detail as to why.

2020-01-10 03:03 UTC, vitorgalvao commented on Casks/tableau-log-viewer.rb
> +cask 'tableau-log-viewer' do
It’s not a tokenization, it follows from the bundle’s name. The token reference explains this in detail, as well as the reasons. Have you not read the document? You have ticked the box:

> - [x] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).

2020-01-10 18:17 UTC, merged

2020-01-10 18:19 UTC, aogail commented on Casks/tableau-log-viewer.rb
> +cask 'tableau-log-viewer' do
Yes, I read that, I just missed that there was a discrepancy between examples I read and that doc as far as the string to start with when tokenizing. I think in this type of case, where the app file name is less descriptive than the real application name, starting with the file name results in a less useful token.

In any case, I've renamed the cask to `tlv`.

2020-01-10 18:41 UTC, vitorgalvao commented on Casks/tableau-log-viewer.rb
> +cask 'tableau-log-viewer' do
> I think in this type of case, where the app file name is less descriptive than the real application name, starting with the file name results in a less useful token.

Not doing so results in duplicates, which is a far greater problem.