Update lightproxy from 1.1.7 to 1.1.8
Homebrew/homebrew-cask pull request #76825
Opened 2020-02-09 04:01 UTC by MashiroWang

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

2020-02-10 18:06 UTC, vitorgalvao commented on Casks/lightproxy.rb
> +  homepage 'https://github.com/alibaba/lightproxy/'
Revert this. The previous homepage is still functional.

2020-02-10 18:07 UTC, vitorgalvao requested changes

2020-02-10 18:07 UTC, vitorgalvao commented on Casks/lightproxy.rb
> +  homepage 'https://github.com/alibaba/lightproxy/'
Revert this. The previous homepage is still functional.

2020-04-07 18:04 UTC, vkarampinis commented
@vitorgalvao this PR is outdated and can be close.

`master` has `1.1.11` already
https://github.com/Homebrew/homebrew-cask/blob/cd97efb47f05a9a4319d637e98e2f16455c81a0b/Casks/lightproxy.rb#L2

2020-04-08 03:33 UTC, closed without merging