Add Collabshot.app v1.2.3.985
Homebrew/homebrew-cask pull request #77405
Opened 2020-02-20 15:25 UTC by cmw

Collabshot is a collaborative screenshot app, developed by Toptal.
The download link is unversioned and will always provide the latest version,
so there is no check for the sha256.

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

2020-02-21 23:26 UTC, vitorgalvao requested changes

2020-02-21 23:26 UTC, vitorgalvao commented on Casks/collabshot.rb
> +  version :latest
`1.2.3.985`

2020-02-21 23:26 UTC, vitorgalvao commented on Casks/collabshot.rb
> +  sha256 :no_check
Add shasum.

2020-02-21 23:26 UTC, vitorgalvao commented on Casks/collabshot.rb
> +  url 'https://api.collabshot.com/desktop/latest/mac'
`https://collabshot.s3.amazonaws.com/desktop/builds/mac/Collabshot_#{version}.dmg`

2020-02-24 01:17 UTC, merged

2020-02-24 01:17 UTC, vitorgalvao commented
Merged. Thank you.

2020-02-24 08:56 UTC, cmw commented
Thank you!