Add affinity-designer
Homebrew/homebrew-cask pull request #78944
Opened 2020-03-20 05:49 UTC by Chandler-Lu

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask

2020-03-20 16:13 UTC, vitorgalvao commented on Casks/affinity-designer.rb
> +  name 'affinity-designer'
This is the name of the app, not a repeat of the token.

2020-03-20 16:15 UTC, vitorgalvao requested changes

2020-03-20 16:15 UTC, vitorgalvao commented on Casks/affinity-designer.rb
> +  url "https://s3-eu-west-1.amazonaws.com/affinity-update/mac/retail/Affinity%20Designer-#{version}.app.zip"
I don’t see a way to confirm this link without registering.

2020-03-20 16:15 UTC, vitorgalvao commented on Casks/affinity-designer.rb
> +  name 'affinity-designer'
This is the name of the app, not a repeat of the token.

2020-03-20 23:53 UTC, Chandler-Lu commented on Casks/affinity-designer.rb
> +  url "https://s3-eu-west-1.amazonaws.com/affinity-update/mac/retail/Affinity%20Designer-#{version}.app.zip"
I get it by packet analyzer. You can download the software in [https://store.serif.com/en-us/download/corporate/trial/](https://store.serif.com/en-us/download/corporate/trial/) and use packet analyzer to get the true url.
![截屏2020-03-2107 47 08](https://user-images.githubusercontent.com/18322610/77214205-03dfba80-6b49-11ea-9359-ec75b377741c.png)

2020-03-22 02:03 UTC, vitorgalvao commented on Casks/affinity-designer.rb
> +  url "https://s3-eu-west-1.amazonaws.com/affinity-update/mac/retail/Affinity%20Designer-#{version}.app.zip"
Thank you, but this makes it a [walled build](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) so [we will not accept it](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#unofficial-vendorless-and-walled-builds) for now (I’m thinking of revising that rule).

2020-03-22 02:03 UTC, closed without merging