GPlates 2.2.0
Homebrew/homebrew-cask pull request #79219
Opened 2020-03-24 21:15 UTC by peterdavidhamilton

After making all changes to the cask:

- [ ] `brew cask audit --download {{cask_file}}` is error-free.
- [ ] `brew cask style --fix {{cask_file}}` reports no offenses.
- [ ] The commit message includes the cask’s name and version.
- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [ ] Named the cask according to the [token reference].
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked there are no [open pull requests] for the same cask.
- [ ] Checked the cask was not [already refused].
- [ ] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask

2020-03-25 02:10 UTC, vitorgalvao commented on Casks/gplates.rb
> +  binary "#{appdir}/GPlates.app/Contents/MacOS/gplates"
For this to be accepted, it needs to be explicitly recommended by upstream. Is there a page you can point to?

2020-03-25 09:00 UTC, peterdavidhamilton commented on Casks/gplates.rb
> +  binary "#{appdir}/GPlates.app/Contents/MacOS/gplates"
Hi Vitor. The latest [GPlates](http://gplates.org/) is compatible with 10.6 and above; so I set the dependency to Mavericks. 
<http://gplates.org/download.html>.

2020-03-25 14:01 UTC, vitorgalvao commented on Casks/gplates.rb
> +  binary "#{appdir}/GPlates.app/Contents/MacOS/gplates"
I’m talking about this specific line. Linking the binary.

Unless upstream specifically recommends it, remove it.

2020-03-25 14:03 UTC, vitorgalvao requested changes

2020-03-25 14:03 UTC, vitorgalvao commented on Casks/gplates.rb
> +  depends_on macos: '>= :mavericks'
Remove this. Homebrew doesn’t work below this version, anyway.

2020-03-25 23:22 UTC, peterdavidhamilton commented on Casks/gplates.rb
> +  binary "#{appdir}/GPlates.app/Contents/MacOS/gplates"
I see. Older versions certainly had command-line only flags but I don't know if this latest version does anymore. I have removed it as suggested.

2020-03-26 02:58 UTC, vitorgalvao approved these changes

2020-03-26 03:09 UTC, vitorgalvao commented
Thank you, and welcome.

2020-03-26 03:09 UTC, merged