Add flanders ip util v1.8.2
Homebrew/homebrew-cask pull request #79690
Opened 2020-03-31 16:41 UTC by missionology

After making all changes to the cask:

- [Y] `brew cask audit --download {{cask_file}}` is error-free.
- [Y] `brew cask style --fix {{cask_file}}` reports no offenses.
- [Y] The commit message includes the cask’s name and version.
- [Y] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [Y] Named the cask according to the [token reference].
- [Y] `brew cask install {{cask_file}}` worked successfully.
- [Y] `brew cask uninstall {{cask_file}}` worked successfully.
- [Y] Checked there are no [open pull requests] for the same cask.
- [Y] Checked the cask was not [already refused].
- [Y] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask

2020-04-01 00:47 UTC, vitorgalvao requested changes

2020-04-01 00:47 UTC, vitorgalvao commented on Casks/flanders-ip-utility.rb
> +cask 'flanders-ip-utility' do
Does not follow the [token reference](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).

2020-04-01 00:47 UTC, vitorgalvao commented on Casks/flanders-ip-utility.rb
> +  url "https://www.flandersscientific.com/ip-remote/release/IPRemoteUtility-#{version}-macOSX.zip"
Use `https://flandersscientific.com/lut/mac.php` as an [`appcast`](https://github.com/homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/appcast.md).

2020-04-01 00:47 UTC, vitorgalvao commented
Tip: use `x` in checklists (no spaces inside the brackets) and [Github will make them clickable](https://github.com/blog/1375-task-lists-in-gfm-issues-pulls-comments).

2020-04-01 08:56 UTC, missionology commented
Hi thanks for the tip and help, I am new to contributing to open source.

I fixed the token reference, but I did not update the app-cast as the link you posted is for an unrelated app so if it needs an appcast I could add the same homepage link again? https://flandersscientific.com/ip-remote/

Thank you

2020-04-02 12:55 UTC, merged

2020-04-12 18:13 UTC, suschizu commented
@missionology  - this url doesn't seem to work - do you perhaps have another project-url? 
`curl: (7) Failed to connect to flandersscientific.com port 443: Operation timed out`

2020-04-12 18:38 UTC, missionology commented
Hi this works for me still,

Could it be geographical ? Where are you pulling from? Can you download it
directly from the site?

Https://flandersscientific.com/ip-remote


On Sun, 12 Apr 2020, 19:13 suschizu, <notifications@github.com> wrote:

> @missionology <https://github.com/missionology> - this url doesn't seem
> to work - do you perhaps have another project-url?
> curl: (7) Failed to connect to flandersscientific.com port 443: Operation
> timed out
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Homebrew/homebrew-cask/pull/79690#issuecomment-612655352>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/APAHPTSBTIQ4IXMD32JTZG3RMIAGHANCNFSM4LXXMXMA>
> .
>

2020-04-12 20:36 UTC, suschizu commented
hm that's strange - the website just works via VPN for me