Add GoldenDict.app v1.5.0-RC2
Homebrew/homebrew-cask pull request #80383
Opened 2020-04-10 14:35 UTC by terrywang

After making all changes to the cask:

- [ ] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused]. `--->` PR #65927 was closed due to `out-dated`
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask

GoldenDict [`macOS` Early Access](https://github.com/goldendict/goldendict/wiki/Early-Access-Builds-for-Mac-OS-X) (RC ONLY since April 2019, no GA) does **NOT** follow the typical SourceFourge URL schema...

2020-04-10 21:40 UTC, vladimyr commented on Casks/goldendict.rb
> +  url 'https://jaist.dl.sourceforge.net/project/goldendict/early%20access%20builds/MacOS/GoldenDict-1.5.0-RC2-372-gc3ff15f%28Qt_5121%29.dmg'
```suggestion
  url 'https://downloads.sourceforge.net/project/goldendict/early%20access%20builds/MacOS/GoldenDict-1.5.0-RC2-372-gc3ff15f%28Qt_5121%29.dmg'
```
The actual download server being used depends on your location and curl will follow this redirect.

2020-04-10 22:02 UTC, vladimyr commented
Additional changes proposed: https://github.com/terrywang/homebrew-cask/pull/1

2020-04-11 13:58 UTC, vladimyr approved these changes

2020-04-11 14:14 UTC, vitorgalvao requested changes

2020-04-11 14:14 UTC, vitorgalvao commented on Casks/goldendict.rb
> +  if MacOS.version <= :mavericks
Thank you, but this was better as the initial commit. Mavericks is the bottom of what Homebrew supports, and we don’t like to add support for random old versions. If someone needs an older version, they’re welcome to add to the conditional, but we don’t do it unprompted—extra maintenance for no gain.

2020-04-11 14:14 UTC, vitorgalvao commented on Casks/goldendict.rb
> +  appcast 'https://github.com/goldendict/goldendict/releases.atom'
If the download is hosted on sourceforge, use the sourceforge appcast.

2020-04-11 14:16 UTC, vitorgalvao requested changes

2020-04-11 14:16 UTC, vitorgalvao commented on Casks/goldendict.rb
> +  version '1.5.0-RC2'
```suggestion
  version '1.5.0-RC2,372-gc3ff15f%28Qt_5121%29'
```

2020-04-11 14:16 UTC, vitorgalvao commented on Casks/goldendict.rb
> +    url "https://download.sourceforge.net/project/goldendict/early%20access%20builds/MacOS/GoldenDict-#{version}-372-gc3ff15f%28Qt_5121%29.dmg"
```suggestion
    url "https://download.sourceforge.net/project/goldendict/early%20access%20builds/MacOS/GoldenDict-#{version.before_comma}-#{version.after_comma}.dmg"
```

2020-04-11 14:29 UTC, vladimyr commented on Casks/goldendict.rb
> +  if MacOS.version <= :mavericks
It should be `:sierra` instead of `:mavericks`, my bad:
https://github.com/goldendict/goldendict/wiki/Early-Access-Builds-for-Mac-OS-X#150-rc2-372-gc3ff15f
and I believe we both agree that sierra conditional is not something that should be avoided to minimize maintenance burden?

2020-04-11 14:43 UTC, vitorgalvao commented on Casks/goldendict.rb
> +  if MacOS.version <= :mavericks
> and I believe we both agree that sierra conditional is not something that should be avoided to minimize maintenance burden?

We don’t. The rule still applies—if someone needs it for Sierra, they can add it. Officially we only support the current macOS version and one behind.

Technically you can tell me right now that you need it for yourself or someone you know. I’ll believe you and let it in. But I expect people to not abuse that trust.

Having a conditional for a version that no one uses in one cask isn’t problematic. Having it in a lot of casks is (and has been). The way to avoid the latter is to be diligent in the former.

2020-04-11 14:46 UTC, vladimyr commented on Casks/goldendict.rb
> +  if MacOS.version <= :mavericks
```suggestion
  if MacOS.version <= :el_capitan
```

2020-04-11 14:46 UTC, vladimyr commented on Casks/goldendict.rb
> +  appcast 'https://github.com/goldendict/goldendict/releases.atom'
```suggestion
  appcast 'https://sourceforge.net/projects/goldendict/rss'
```

2020-04-11 15:51 UTC, vladimyr commented on Casks/goldendict.rb
> +  if MacOS.version <= :mavericks
As usual, I'm guilty of not RTFM https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions (this needs to be updated but it is pretty clear) 
Sorry!

With that being said @terrywang please revert my commit.

2020-04-14 14:42 UTC, vitorgalvao approved these changes

2020-04-14 14:49 UTC, vladimyr commented on Casks/goldendict.rb
> +  homepage 'https://github.com/goldendict/goldendict'
```suggestion
  homepage 'http://goldendict.org'
```

2020-04-14 15:02 UTC, vladimyr commented on Casks/goldendict.rb
> +  url "https://download.sourceforge.net/goldendict/GoldenDict-#{version.before_comma}-#{version.after_comma}.dmg"
```suggestion
  # downloads.sourceforge.net/goldendict was verified as official when first introduced to the cask
  url "https://downloads.sourceforge.net/goldendict/GoldenDict-#{version.before_comma}-#{version.after_comma}.dmg"
```

2020-04-14 15:05 UTC, vladimyr commented on Casks/goldendict.rb
> +  url "https://download.sourceforge.net/goldendict/GoldenDict-#{version.before_comma}-#{version.after_comma}.dmg"
This should fix both style check & https://github.com/Homebrew/homebrew-cask/pull/80383/checks?check_run_id=586018448#step:3:20

2020-04-14 18:00 UTC, merged