Fix alacritty un/install
Homebrew/homebrew-cask pull request #80597
Opened 2020-04-13 19:26 UTC by darwingr

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [ ] The commit message includes the cask’s name and version.
       **NO VERSION NUMBER. This isn't a version update.**
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [ ] Named the cask according to the [token reference].
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked there are no [open pull requests] for the same cask.
- [ ] Checked the cask was not [already refused].
- [ ] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask

2020-04-14 16:08 UTC, vitorgalvao requested changes

2020-04-14 16:08 UTC, vitorgalvao commented on Casks/alacritty.rb
> -                '~/.config/alacritty',
Why are you removing this?

2020-04-14 16:08 UTC, vitorgalvao commented on Casks/alacritty.rb
> +  binary "#{appdir}/Alacritty.app/Contents/MacOS/alacritty"
Unless there’s official documentation recommending this, we don’t do it.

2020-04-15 03:37 UTC, darwingr commented on Casks/alacritty.rb
> +  binary "#{appdir}/Alacritty.app/Contents/MacOS/alacritty"
The is okay to execute directly on MacOS and other platforms.
For example, here's the output you actually get with `-h`:
![image](https://user-images.githubusercontent.com/6166398/79296226-344d1700-7eb1-11ea-9b00-05d1bdac1392.png)


Here's the documentation on how to use alacritty on the command line to make it easier to configure your keyboard mappings: https://github.com/alacritty/alacritty/wiki/Keyboard-mappings

2020-04-15 03:50 UTC, darwingr commented on Casks/alacritty.rb
> -                '~/.config/alacritty',
Sorry, I put it in the commit message.
This file is never created by the app. The only way it is ever created is intentionally/deliberately by the user. If that's the case they likely would not want it deleted along with the other trash.

The same approach would go for MacVim, Wireshark, Emacs, GnuCash, etc,  to delete their respective user configs found in `~/.config/` and `~/`.

2020-04-15 16:14 UTC, merged