Add PyCharm with Anaconda plugin 2020.1
Homebrew/homebrew-cask pull request #80720
Opened 2020-04-15 14:38 UTC by sicruse

After making all changes to the cask:

- [ ] `brew cask audit --download {{cask_file}}` is error-free.
- [ ] `brew cask style --fix {{cask_file}}` reports no offenses.
- [ ] The commit message includes the cask’s name and version.
- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [ ] Named the cask according to the [token reference].
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked there are no [open pull requests] for the same cask.
- [ ] Checked the cask was not [already refused].
- [ ] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask

2020-04-15 16:41 UTC, vitorgalvao commented on Casks/pycharm-with-anaconda-plugin.rb
> +  app 'PyCharm with Anaconda plugin .app'
Is the space at the end correct?

2020-04-15 16:41 UTC, vitorgalvao requested changes

2020-04-15 16:41 UTC, vitorgalvao commented on Casks/pycharm-with-anaconda-plugin.rb
> +               "~/Library/Application Support/PyCharm#{version.major_minor}",
Use `*` instead of interpolating `version`.

2020-04-15 17:38 UTC, sicruse commented on Casks/pycharm-with-anaconda-plugin.rb
> +  app 'PyCharm with Anaconda plugin .app'
unfortunately, yes it is. Thanks for checking though!

2020-04-15 17:43 UTC, sicruse commented on Casks/pycharm-with-anaconda-plugin.rb
> +               "~/Library/Application Support/PyCharm#{version.major_minor}",
Thanks for the feedback @vitorgalvao - so you think:

```suggestion
  zap trash: [
               "~/Library/Application Support/PyCharm*",
```

correct?

2020-04-15 19:43 UTC, sicruse commented on Casks/pycharm-with-anaconda-plugin.rb
> +               "~/Library/Application Support/PyCharm#{version.major_minor}",
I have updated the zap stanza in the latest commit.

2020-04-16 16:39 UTC, vitorgalvao approved these changes

2020-04-16 16:54 UTC, merged