update Wireshark
Homebrew/homebrew-cask pull request #81081
Opened 2020-04-21 16:47 UTC by lulor

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

2020-04-21 16:56 UTC, lulor commented
This should solve #81060

2020-04-21 21:08 UTC, vitorgalvao requested changes

2020-04-21 21:08 UTC, vitorgalvao commented on Casks/wireshark.rb
> +    if system('/usr/bin/dscl . -read /Groups/access_bpf &> /dev/null')
Use `system_command`, as below.

2020-04-21 21:37 UTC, lulor commented on Casks/wireshark.rb
> +    if system('/usr/bin/dscl . -read /Groups/access_bpf &> /dev/null')
Sorry, I'm not much familiar with ruby nor homebrew files.
I've tried to use `system_command`, but if the group is not preset, the whole uninstall process fails with an error, instead of just skipping the command inside the `if` statement.
Probably it's just because of my inability, but how should I re-write the statement?

2020-04-21 23:04 UTC, miccal commented
Closes https://github.com/Homebrew/homebrew-cask/pull/81059

2020-04-22 02:57 UTC, vladimyr commented on Casks/wireshark.rb
>    end
First, there is no way to ignore command execution error inside a code block except wrapping it inside try-rescue. Instead, you should use something that is guaranteed to succeed:
```rb
  uninstall_preflight do
    set_ownership '/Library/Application Support/Wireshark'

    stdout, * = system_command '/usr/bin/dscl', args: ['.', '-list', '/Groups']
    next unless stdout.lines.map(&:strip).include? 'access_bpf'

    system_command '/usr/sbin/dseditgroup',
                   args: ['-q', '-o', 'delete', 'access_bpf'],
                   sudo: true
  end
```

2020-04-22 02:57 UTC, vladimyr commented on Casks/wireshark.rb
>              launchctl: 'org.wireshark.ChmodBPF'
Please list all pkgs explicitly because wildcards are not supported here:
```suggestion
  uninstall pkgutil:   [
                         'org.wireshark.ChmodBPF.pkg',
                         'org.wireshark.path_helper.pkg',
                       ],
            launchctl: 'org.wireshark.ChmodBPF'
```

2020-04-22 02:57 UTC, vladimyr commented on Casks/wireshark.rb
> +             ]
This is really a cosmetic thing but helps maintainers later on, sort those alphabetically: 
```suggestion
  zap trash: [
               '~/Library/Caches/org.wireshark.Wireshark',
               '~/Library/Cookies/org.wireshark.Wireshark.binarycookies',
               '~/Library/Preferences/org.wireshark.Wireshark.plist',
               '~/Library/Saved Application State/org.wireshark.Wireshark.savedState',
             ]
```

2020-04-22 03:17 UTC, vladimyr commented
@lulor Please change download URL to:
```rb
  url "https://www.wireshark.org/download/osx/Wireshark%20#{version}%20Intel%2064.dmg"
```

2020-04-22 03:31 UTC, miccal commented on Casks/wireshark.rb
>              launchctl: 'org.wireshark.ChmodBPF'
@vladimyr yes they are, as shown in the build log:
```
==> Uninstalling packages:
org.wireshark.ChmodBPF.pkg
org.wireshark.path_helper.pkg
```

2020-04-22 03:35 UTC, vladimyr commented on Casks/wireshark.rb
>              launchctl: 'org.wireshark.ChmodBPF'
You are right, I confused it with `launchctl`.
@lulor Ignore this one.

2020-04-22 06:04 UTC, vladimyr approved these changes

2020-04-22 06:04 UTC, vladimyr commented on Casks/wireshark.rb
>              launchctl: 'org.wireshark.ChmodBPF'
Actually @lulor was right! We shouldn't reinvent the wheel:
```rb
  uninstall_preflight do
    system_command '/usr/sbin/installer',
                   args: [
                           '-pkg', "#{staged_path}/Uninstall ChmodBPF.pkg",
                           '-target', '/'
                         ],
                   sudo: true
    system_command '/usr/sbin/installer',
                   args: [
                           '-pkg', "#{staged_path}/Remove Wireshark from the system path.pkg",
                           '-target', '/'
                         ],
                   sudo: true
  end

  uninstall pkgutil: 'org.wireshark.*'
```
It even makes `launchctl` unneeded.

2020-04-22 07:15 UTC, lulor commented on Casks/wireshark.rb
>              launchctl: 'org.wireshark.ChmodBPF'
@vladimyr thank you so much for all the suggestions!
I've committed all your changes, I think it should be fine now

2020-04-22 07:24 UTC, vladimyr commented on Casks/wireshark.rb
>              launchctl: 'org.wireshark.ChmodBPF'
You are welcome. I think we are good now but let's hear what others say. 🤞

2020-04-22 22:33 UTC, vitorgalvao commented
Fantastic! Thank you for trying and succeeding, @lulor. I really appreciate you making the effort.

And thank you for being always helpful, @vladimyr.

2020-04-22 22:33 UTC, merged