Add librepcb.app v0.1.3
Homebrew/homebrew-cask pull request #81129
Opened 2020-04-22 00:38 UTC by onesmallskipforman

Add librepcb.app, an open-source PCB design and schematic tool.

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask

2020-04-22 01:33 UTC, vitorgalvao commented
Please add an [`appcast`](https://github.com/homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/appcast.md).

2020-04-22 01:34 UTC, vitorgalvao requested changes

2020-04-22 01:34 UTC, vitorgalvao commented on Casks/librepcb.rb
> +  zap delete: [
If there’s only one file, make this a string instead of an array.

2020-04-22 01:55 UTC, onesmallskipforman commented on Casks/librepcb.rb
> +  zap delete: [
Sounds good. I added an appcast and changed the zap stanza to a single string.

2020-04-24 00:05 UTC, onesmallskipforman commented
@vitorgalvao I also switched the zap stanza to use trash instead of delete. Everything should be good now.

2020-04-24 04:01 UTC, merged