Update intel-power-gadget
Homebrew/homebrew-cask pull request #81205
Opened 2020-04-23 08:22 UTC by lulor

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.

Similarly to #81081, `intel-power-gadget` comes with an `Uninstaller.pkg` provided by Intel itself.
Maybe it could be preferable to use that instead of manually replicate its function?
Correct if I'm wrong, so that I can adjust the PR to just remove the config files in the `zap` stanza

2020-04-23 17:39 UTC, core-code commented
can you use this as an 'appcast'?

`https://software.intel.com/sites/landingpage/powergadget/?app=IntelPowerGadgetMac`

2020-04-23 19:40 UTC, lulor commented
> can you use this as an 'appcast'?
> 
> `https://software.intel.com/sites/landingpage/powergadget/?app=IntelPowerGadgetMac`

Sure! Should I leave the "configuration" field as it is? To be honest, it's not entirely clear to me what its purpose is

2020-04-23 20:30 UTC, core-code commented
the appcast is used to prevent beta versions being submitted and auto-merged. if the version number isn't contained in the appcast, travis will fail. the 'configuration' tells travis which part of the version number is expected to be contained in the appcast. 

you can delete the configuration since the full version number should be contained in the new appcast

2020-04-23 21:55 UTC, core-code commented
thanks!

2020-04-24 22:36 UTC, lulor commented
> thanks!

@core-code  Thank you for the explanation!

Anyway, the tests are not going to succeed because of some COU r

2020-04-24 22:36 UTC, lulor commented
We

2020-04-24 22:38 UTC, lulor commented
@core-code thank you for the explanation!

Anyway, the tests are not going to succeed because of some CPU requirements from Intel

2020-04-25 21:50 UTC, vitorgalvao requested changes

2020-04-25 21:50 UTC, vitorgalvao commented on Casks/intel-power-gadget.rb
> -  uninstall pkgutil: 'com.intel.pkg.PowerGadget.*',
We’d rather keep this like it is, if tests succeed.

2020-04-26 09:14 UTC, lulor commented on Casks/intel-power-gadget.rb
> -  uninstall pkgutil: 'com.intel.pkg.PowerGadget.*',
Thanks!
I don't think the tests are going to succeed, since the application fails to install because of some CPU requirements from Intel that are not satisfied (only 1 CPU package).

Should I revert to using the `kext` key anyway?

2020-04-27 14:13 UTC, vitorgalvao commented on Casks/intel-power-gadget.rb
> -  uninstall pkgutil: 'com.intel.pkg.PowerGadget.*',
I meant if they succeed in that area, if it still works.

If there’s a situation where they’ll fail either way, ignore that when evaluating.

2020-04-27 15:34 UTC, lulor commented on Casks/intel-power-gadget.rb
> -  uninstall pkgutil: 'com.intel.pkg.PowerGadget.*',
I understand. I went back to the previous approach, it should be good now

2020-04-27 15:35 UTC, merged