Add Fireworks.app
Homebrew/homebrew-cask pull request #82636
Opened 2020-05-14 23:23 UTC by byassine52

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask

2020-05-15 02:57 UTC, vitorgalvao requested changes

2020-05-15 02:57 UTC, vitorgalvao commented on Casks/fireworks.rb
> +  url 'https://www.fireworksapp.xyz/public/fireworks.zip'
Please add an [`appcast`](https://github.com/homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/appcast.md) (`https://www.fireworksapp.xyz`).

2020-05-15 02:57 UTC, vitorgalvao commented on Casks/fireworks.rb
> +  version :latest
Add a version and shasum.

2020-05-29 12:19 UTC, adidalal commented on Casks/fireworks.rb
> +  version :latest
```
version '1.2'
sha256 925774f32399c6b11e8e07cab5fb39f30c5bf7df6896540992065e5bac0327cd
```

2020-06-05 02:32 UTC, byassine52 commented on Casks/fireworks.rb
> +  url 'https://www.fireworksapp.xyz/public/fireworks.zip'
Sorry for the delay.
Done 👍

2020-06-05 02:33 UTC, byassine52 commented on Casks/fireworks.rb
> +  version :latest
Sorry for the delay.
Done 👍

2020-06-05 02:34 UTC, byassine52 commented
Applied requested changes.

2020-06-05 02:40 UTC, ran-dall requested changes
@byassine52 You're also missing the `zap` stanza.

2020-06-05 02:40 UTC, ran-dall commented on Casks/fireworks.rb
> +end
```suggestion

  zap trash: [
             '~/Library/Application Scripts/com.Besher-Al-Maleh.fireworks',
             '~/Library/Containers/com.Besher-Al-Maleh.fireworks',
           ]
end
```

2020-06-05 17:30 UTC, merged

2020-06-06 11:44 UTC, byassine52 commented on Casks/fireworks.rb
> +end
Great addition @ran-dall 😄 👏