Add MPLAB X IDE
Homebrew/homebrew-cask pull request #83151
Opened 2020-05-24 05:32 UTC by CyberCastle

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [X] `brew cask audit --download {{cask_file}}` is error-free.
- [X] `brew cask style --fix {{cask_file}}` reports no offenses.
- [X] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [X] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, **if adding a new cask**:

- [X] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [X] `brew cask install {{cask_file}}` worked successfully.
- [X] `brew cask uninstall {{cask_file}}` worked successfully.
- [X] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [X] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).

2020-05-24 13:43 UTC, vitorgalvao commented on Casks/mplabx-ide.rb
> +  app 'mplab_ide.app', target: 'microchip/mplab_ide.app'
Why the rename?

2020-05-24 15:59 UTC, CyberCastle commented on Casks/mplabx-ide.rb
> +  app 'mplab_ide.app', target: 'microchip/mplab_ide.app'
As such, it is not a rename, it is an ordering of the applications, just as the original installer does. I used [this](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/kicad.rb) barrel as a reference.

2020-05-24 19:47 UTC, vitorgalvao requested changes

2020-05-24 19:47 UTC, vitorgalvao commented on Casks/mplabx-ide.rb
> +  postflight do
Do you need this ownership change to use the software?

2020-05-24 19:47 UTC, vitorgalvao commented on Casks/mplabx-ide.rb
> +            delete: ['/Applications/microchip']
Use `#{appdir}`, not `/Applications`

2020-05-24 19:47 UTC, vitorgalvao commented on Casks/mplabx-ide.rb
> +  app 'mplab_ide.app', target: 'microchip/mplab_ide.app'
> just as the original installer does.

What exactly does this mean?

2020-05-24 19:57 UTC, CyberCastle commented on Casks/mplabx-ide.rb
> +  app 'mplab_ide.app', target: 'microchip/mplab_ide.app'
The installer adds other application in "/Applications/microchip" folder, by default, and this cannot be changed. So use that folder to install mplab_ide.app and mplab_ipe.app. That is why the configuration of this cask has been done in this way.

2020-05-24 19:59 UTC, CyberCastle commented on Casks/mplabx-ide.rb
> +  postflight do
Yes, especially if it is required to adjust some settings or to uninstall it.

2020-05-25 03:31 UTC, vitorgalvao commented on Casks/mplabx-ide.rb
> +  app 'mplab_ide.app', target: 'microchip/mplab_ide.app'
Thank you. That clarifies it.

2020-05-25 03:33 UTC, vitorgalvao commented on Casks/mplabx-ide.rb
> +    set_ownership "#{appdir}/microchip"
> The installer adds other application in "/Applications/microchip" folder, by default, and this cannot be changed.

That makes my request for changing this incorrect.

2020-05-25 03:33 UTC, vitorgalvao approved these changes

2020-05-25 04:11 UTC, merged

2020-05-25 04:15 UTC, CyberCastle commented
@vitorgalvao Thanks you for merge this cask. Can you check this other [cask](https://github.com/Homebrew/homebrew-cask/pull/83106) please?