Update miniconda from 4.7.12 to py37_4.8.2
Homebrew/homebrew-cask pull request #83359
Opened 2020-05-28 07:09 UTC by b0ttle

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [ ] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

2020-05-28 07:11 UTC, b0ttle commented
btw miniconda divided into version py37 and py38, i chose py37 here

2020-05-28 07:16 UTC, ran-dall commented
@b0ttle This might be a stupid question, but what's the difference?

2020-05-28 07:24 UTC, b0ttle commented
@ran-dall Sorry I didn't know the difference either, but in miniconda's download page [https://repo.anaconda.com/miniconda/](url), they are different files.

2020-05-28 07:49 UTC, ran-dall commented
@b0ttle It probably has something to do with `py_37` being based on `3.7.x` branch of Python and py_38` being based on `3.8.x` branch of Python. However, I don't know which would be better for HBC, or if we should now have two different casks.

@vitorgalvao Could I get your opinion on this situation?

2020-05-28 08:01 UTC, b0ttle commented
@ran-dall Actually there exists a file named 'latest', which is the same as 'py37'(Same MD5). Maybe we can change the download link to the 'latest' version. It also can let users to know when to send a update PR. In 3 month no one notices miniconda get updated.

2020-05-28 08:16 UTC, ran-dall commented
@b0ttle We'd like to use a version where we can, so I think it's better to keep it. It makes sense the `py37` is the `latest` because it's probably the most compatible (and probably has fewer bugs). With that considered, I think this update makes sense; but let's see what some of the other maintainers think.

> In 3 month no one notices miniconda get updated.

I can address with the ML. So it's not going to happen as often.

2020-05-28 11:34 UTC, vitorgalvao commented
This cask should be updated to use the `pkg` installer instead. It will allow us a better `uninstall`.

Is that something you want to pursue, @b0ttle?

2020-05-28 12:20 UTC, b0ttle commented
@vitorgalvao I always use `.sh` for conda's install, not sure if it will be better using `pkg`. Depends on your judgement :).

2020-05-28 12:39 UTC, vitorgalvao commented
> I always use `.sh` for conda's install, not sure if it will be better using `pkg`.

As a manual install, it’s a matter of personal preference. As a cask, the `pkg` is better.

2020-05-28 14:53 UTC, ran-dall commented
@b0ttle If you don't want to do or you need some help, I'll be happy to help / do it. Just let me know...

2020-05-28 15:46 UTC, b0ttle commented
@ran-dall It is difficult for me to communicate in English. Sometimes I can't get your ideas, sorry about that.
So help me do it, thank you very much.

2020-05-28 17:00 UTC, ran-dall commented
@b0ttle Completely understandable. I'll try to keep it as "simple" English as possible. 😉

Let me look over what needs to get done, and I'll post it here shortly. All you'd need to do is copy the changes over and submit to this PR.

2020-05-28 18:33 UTC, ran-dall requested changes

2020-05-28 18:33 UTC, ran-dall commented on Casks/miniconda.rb
>    installer script: {
```ruby
  installer script: {
                      executable: "Miniconda3-py37_#{version}-MacOSX-x86_64.sh",
                      args:       ['-b', '-p', "#{caskroom_path}/base"],
                    }
  binary "#{caskroom_path}/base/condabin/conda"

  uninstall delete: "#{caskroom_path}/base"
```

Replace with:

```ruby
  pkg 'Miniconda3-latest-MacOSX-x86_64.pkg'

  uninstall pkgutil: [
                       'io.continuum.pkg.apreinstall',
                       'io.continuum.pkg.conda.exe',
                       'io.continuum.pkg.pathupdate',
                       'io.continuum.pkg.postextract',
                       'io.continuum.pkg.preconda',
                     ]

```

2020-05-28 18:37 UTC, ran-dall commented on Casks/miniconda.rb
>    binary "#{caskroom_path}/base/condabin/conda"
```suggestion
  pkg 'Miniconda3-latest-MacOSX-x86_64.pkg'
```

2020-05-28 18:38 UTC, ran-dall reviewed
It wouldn't let me a the suggestion on line 19, but replace line 19 with:

```
  uninstall pkgutil: [
                       'io.continuum.pkg.apreinstall',
                       'io.continuum.pkg.conda.exe',
                       'io.continuum.pkg.pathupdate',
                       'io.continuum.pkg.postextract',
                       'io.continuum.pkg.preconda',
                     ]
```

The `zap` stanza and the rest of it should be left the same.

2020-05-28 18:42 UTC, vitorgalvao commented on Casks/miniconda.rb
> +  url "https://repo.anaconda.com/miniconda/Miniconda3-py37_#{version}-MacOSX-x86_64.sh"
You need to suggest the whole line, including `url` and the quotes. Is there no versioned link for the PKG?

2020-05-28 18:43 UTC, ran-dall commented
@vitorgalvao Does this still require `container type: :naked` now that we're using a `pkg`?

2020-05-28 18:44 UTC, vitorgalvao commented
> @vitorgalvao Does this still require `container type: :naked` now that we're using a `pkg`?

Nope.

2020-05-28 19:52 UTC, ran-dall commented on Casks/miniconda.rb
> +  url "https://repo.anaconda.com/miniconda/Miniconda3-py37_#{version}-MacOSX-x86_64.sh"
@vitorgalvao Thanks, I think this is my first time using suggestions. I like to try new things.

2020-05-28 19:54 UTC, ran-dall commented on Casks/miniconda.rb
>    container type: :naked
```suggestion

```

2020-05-28 19:56 UTC, ran-dall commented on Casks/miniconda.rb
>    container type: :naked
> > @vitorgalvao Does this still require `container type: :naked` now that we're using a `pkg`?
> 
> Nope.

@b0ttle So you can also remove line 11 completely.

2020-05-28 19:57 UTC, ran-dall commented
@b0ttle So the final should look something like this (you can just copy and paste as a whole, if you want)

```ruby
cask 'miniconda' do
  version '4.8.2'
  sha256 'f3ede3a58d82fb5dcbca52d291a9edb5cd962d84d823a20693dd4bb27506cdd0'

  # repo.anaconda.com/miniconda/ was verified as official when first introduced to the cask
  url "https://repo.anaconda.com/miniconda/Miniconda3-#{version}-MacOSX-x86_64.pkg"
  name 'Continuum Analytics Miniconda'
  homepage 'https://conda.io/miniconda.html'

  auto_updates true

  pkg 'Miniconda3-latest-MacOSX-x86_64.pkg'

  uninstall pkgutil: [
                       'io.continuum.pkg.apreinstall',
                       'io.continuum.pkg.conda.exe',
                       'io.continuum.pkg.pathupdate',
                       'io.continuum.pkg.postextract',
                       'io.continuum.pkg.preconda',
                     ]

  zap trash: [
               '~/.condarc',
               '~/.conda',
               '~/.continuum',
             ]

  caveats <<~EOS
    Please run the following to setup your shell:

      conda init "$(basename "${SHELL}")"
  EOS
end
```

2020-05-29 00:15 UTC, b0ttle commented
@ran-dall Already add your code in newest commit! Thank you for your kindly help and patients. Will try to contribute more in the future!

2020-05-29 00:25 UTC, ran-dall commented
@b0ttle Thank you for your effort and work. We'd be very happy to have another frequent contributor.

Also, I don't think the caveat is required anymore with the pkg.

2020-05-29 00:44 UTC, ran-dall approved these changes

2020-05-29 14:28 UTC, merged