Add PrivateVPN 2.11
Homebrew/homebrew-cask pull request #83501
Opened 2020-05-30 22:28 UTC by falmp

I noticed this was previously removed due to some download problems
related to cookies, but I recreated it, tested it and it works.

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).

2020-05-31 01:50 UTC, ran-dall requested changes
@falmp You're missing the `zap` stanza.

2020-05-31 01:50 UTC, ran-dall commented on Casks/privatevpn.rb
> +end
```suggestion

  zap trash: [
               '/Library/LaunchDaemons/com.privat.vpn.helper.plist',
               '/Library/PrivilegedHelperTools/com.privat.vpn.helper',
               '~/Library/Application Support/com.privat.vpn',
               '~/Library/Caches/com.privat.vpn',
               '~/Library/Cookies/com.privat.vpn.binarycookie',
               '~/Library/Preferences/com.privat.vpn.plist',
             ]
end
```

2020-05-31 21:24 UTC, falmp commented
> @falmp You're missing the `zap` stanza.

Thanks, I added it now.

2020-06-01 03:22 UTC, ran-dall approved these changes

2020-06-01 06:51 UTC, merged