Add SoundBlaster Command App
Homebrew/homebrew-cask pull request #83746
Opened 2020-06-04 09:23 UTC by iMonZ

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [ X] `brew cask audit --download {{cask_file}}` is error-free.
- [ ] `brew cask style --fix {{cask_file}}` reports no offenses.
- [ X] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [ X] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, **if adding a new cask**:

- [ X] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [ X] `brew cask install {{cask_file}}` worked successfully.
- [ X] `brew cask uninstall {{cask_file}}` worked successfully.
- [ X] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ X] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).

Maybe I need some help with the uninstaller script.
But this Script already included worked too but need User input

2020-06-04 09:35 UTC, iMonZ commented
Maybe I need some help with the uninstaller script.
But this Script already included worked too but need a User input
(This Software uses a tool with an UI for Uninstalling)

2020-06-04 09:38 UTC, iMonZ reviewed
Fixed an Empty Folder

2020-06-04 09:52 UTC, iMonZ reviewed
Sorry

2020-06-04 10:59 UTC, miccal commented
Please run `brew cask style --fix sb-command` as asked in the template:
```
==> brew cask style sb-command
== /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/sb-command.rb ==
C:  8:  1: stanza groups should be separated by a single empty line
C:  9:  1: stanza groups should be separated by a single empty line
C: 10:  1: Trailing whitespace detected.
C: 11: 29: Use 2 spaces for indentation in a hash, relative to the position of the opening brace.
C: 11: 29: Align the keys and values of a hash literal if they span more than one line.
C: 11: 39: Space missing after colon.
C: 14: 27: Indent the right brace the same as the left brace.
C: 15:  9: Align the keys and values of a hash literal if they span more than one line.
C: 16: 16: Use 2 spaces for indentation in an array, relative to the position of the opening bracket.
C: 17: 14: Indent the right bracket the same as the left bracket.
```

2020-06-04 11:28 UTC, iMonZ reviewed
Done!
I have used the Command: brew cask style Casks/sb-command.rb [--fix] from https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md

But this command doesn't fixed the offences

2020-06-04 11:52 UTC, iMonZ commented
It would be great if you would help me with the Uninstaller.
Travis cannot test it cause of the need of User Input

2020-06-04 23:26 UTC, ran-dall requested changes
@iMonZ Sometimes when you execute a `pkg` you don't need a `zap` stanza because `pkg` requires `uninstall`, however, I've made the `zap` stanza (just in case) which will ensure everything gets removed.

Also, if the `name` is `Sound Blaster Command`, then the `.rb` needs to be `sound-blaster-command.rb`

2020-06-04 23:26 UTC, ran-dall commented on Casks/sb-command.rb
>  end
```suggestion

  zap trash: [
             '~/Library/Application Support/Creative.SB-Command',
             '~/Library/Application Support/Creative.SB-Command.logs',
             '~/Library/Preferences/Creative.SB-Command.plist',
           ]
end
```

2020-06-04 23:42 UTC, iMonZ commented
Hey thank you!

The name of the app after installing and on the Official Website is SB command!
The tool from homebrew suggested the name for the .rb file as SB-command.
So I need really to change this or let this at SB-command what is also better for the user cause of the same name on the website

2020-06-05 02:42 UTC, ran-dall commented
@iMonZ The main reason I'd change it to `Sound Blaster Command` is also because when a user runs `brew search` they would have to enter `sb command` or `sb-command` to see the cask. IMO `sb-command` is a bit ambiguous, so I'd personally prefer `sound-blaster-command`. 

HOWEVER, I don't really have a problem with keeping it with `sb-command` if you want. If that's the cask though, I'd chagne the `name` staza to `SB Command`.

2020-06-05 08:24 UTC, iMonZ commented
Okay Right I’m changing it and run the style fix then you can merge

2020-06-05 10:07 UTC, iMonZ commented
Done!
It can be merged now.

2020-06-05 18:28 UTC, ran-dall approved these changes
@iMonZ LGTM. Good work!

2020-06-05 18:29 UTC, merged

2020-06-05 20:01 UTC, iMonZ commented
Good work from your side!
Thank you for your work

2020-08-30 16:45 UTC, vitorgalvao commented
Moving this to [homebrew/cask-drives](https://github.com/Homebrew/homebrew-cask-drivers).

2020-08-30 17:05 UTC, vitorgalvao commented
Moving this to [homebrew/cask-drivers](https://github.com/Homebrew/homebrew-cask-drivers). It definitely belongs there, as it’s useless without a peripheral:
<img src="https://user-images.githubusercontent.com/1699443/91665051-e6951c00-eaea-11ea-8d21-e7a27e560da6.png">

Because that repo requires the company’s name as a prefix, the correct name of the app `sb-command` is no longer ambiguous. Leaving `name` with `Sound Blaster` for searchability.

It has almost no users yet, so this won’t be too disruptive.

```
sound-blaster-command
30 days: 3 (#4258)
90 days: 3 (#5862)
365 days: 3 (#7143)
Age: 86 days (added 2020, June 05)
```

2020-08-31 01:03 UTC, vitorgalvao commented on Casks/sound-blaster-command.rb
> +                      executable:   '/Applications/Creative/Uninstaller.app/Contents/MacOS/Uninstaller',
@ran-dall For future reference, we don’t allow this an uninstall because it’s not a script, it invokes the uninstaller GUI, which holds up the terminal indefinitely.

We’d need https://github.com/Homebrew/homebrew-cask/issues/24377 to use this.