Add Workspaces 1.5.2
Homebrew/homebrew-cask pull request #83779
Opened 2020-06-04 20:06 UTC by guydebros

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).

2020-06-04 23:27 UTC, ran-dall approved these changes

2020-06-04 23:30 UTC, ran-dall commented
@guydebros Is there no `appcast` for the current version? If no, then I assume this would do because it would be assumed the newest version would be shown after they're done with beta.

2020-06-05 11:13 UTC, guydebros commented
Fixed, and it works fine. RTFM! 😛

2020-06-05 17:00 UTC, ran-dall commented
`The URL https://www.apptorium.com/updates/workspaces-1.5.2 is not reachable (HTTP status code 404)`

@guydebros This link isn't working. I'd suggest changing it back to the original one. As I said, I think we can assume that that link will be up-to-date when `2.0` comes out.

2020-06-05 17:00 UTC, ran-dall requested changes

2020-06-05 17:00 UTC, ran-dall commented on Casks/workspaces.rb
> +  appcast "https://www.apptorium.com/updates/workspaces-#{version}"
```suggestion
   appcast 'https://www.apptorium.com/updates/workspaces' 
```

2020-06-05 17:37 UTC, guydebros commented on Casks/workspaces.rb
> +  appcast "https://www.apptorium.com/updates/workspaces-#{version}"
Sorry, this is my first time creating a cask. I thought `audit --download` worked with the version number, but you're right, the link doesn't work. Doesn't make sense to me.

As for `2.0`, the author says it will be ready "--Late 2019 / Early 2020-- April/May 2020" so I'll keep an eye out.

2020-06-05 18:01 UTC, merged