wireshark: Add shim script
Homebrew/homebrew-cask pull request #84455
Opened 2020-06-16 20:04 UTC by gechr

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

---

Prompted by https://github.com/eldadru/ksniff/issues/63, it seems that the `wireshark` CLI script was removed somewhere along the line when the cask was upgraded from v2 to v3.

This adds a shim script in the same way it's done in other Casks to address the issue.

2020-06-17 04:28 UTC, miccal commented
@gechr would you know what exactly the `pkg 'Add Wireshark to the system path.pkg'` does? I assume the `shimscript` that you have added does not interfere?

2020-06-17 08:27 UTC, gechr commented
Hmm according to https://github.com/wireshark/wireshark/blob/77d94aea2/CMakeLists.txt#L2850-L2881, it seems that `Add Wireshark to the system path.pkg` adds https://github.com/wireshark/wireshark/blob/77d94aea2/packaging/macosx/path_helper/root/etc/paths.d/Wireshark to the system `PATH`:

```
$ cat /etc/paths.d/Wireshark
/Applications/Wireshark.app/Contents/MacOS

$ find /Applications/Wireshark.app/Contents/MacOS/ -maxdepth 1 -executable -type f
/Applications/Wireshark.app/Contents/MacOS/capinfos
/Applications/Wireshark.app/Contents/MacOS/captype
/Applications/Wireshark.app/Contents/MacOS/dftest
/Applications/Wireshark.app/Contents/MacOS/dumpcap
/Applications/Wireshark.app/Contents/MacOS/editcap
/Applications/Wireshark.app/Contents/MacOS/idl2wrs
/Applications/Wireshark.app/Contents/MacOS/mergecap
/Applications/Wireshark.app/Contents/MacOS/mmdbresolve
/Applications/Wireshark.app/Contents/MacOS/randpkt
/Applications/Wireshark.app/Contents/MacOS/rawshark
/Applications/Wireshark.app/Contents/MacOS/reordercap
/Applications/Wireshark.app/Contents/MacOS/sharkd
/Applications/Wireshark.app/Contents/MacOS/text2pcap
/Applications/Wireshark.app/Contents/MacOS/tshark
/Applications/Wireshark.app/Contents/MacOS/Wireshark
```

Not sure if something's wrong with my setup, but none of these are available to me when I `<tab>` complete. Also, the `wireshark` binary is not lowercase, as it was in v2.x, so I think this change is still valid (or an upstream patch).

2020-06-17 10:53 UTC, miccal commented
@gechr so the `pkg 'Add Wireshark to the system path.pkg'` seems to add `/Applications/Wireshark.app/Contents/MacOS` to the `PATH`, implying that calling `Wireshark` from the command line should already work, correct?

2020-06-17 11:54 UTC, gechr commented
@miccal Yep, `Wireshark` works after I sorted out `/usr/libexec/path_helper`. However, there is still the issue of case-(in)sensitivity.

It _happens_ to work for me regardless of case because my filesystem is case-insensitive, i.e. `WIRESHARK`, `Wireshark`, `wireshark` all work, but for other people who have a case-sensitive filesystem, it won't work, so I think this PR might still be valid for those folk.

2020-06-19 17:39 UTC, vitorgalvao requested changes

2020-06-19 17:39 UTC, vitorgalvao commented on Casks/wireshark.rb
> +      exec #{appdir}/Wireshark.app/Contents/MacOS/Wireshark "$@"
This probably could be a `binary` on its own. But to be considered at all, there needs to be an official source that recommends it, otherwise every cask would do it.

2020-06-19 22:50 UTC, gechr commented on Casks/wireshark.rb
> +      exec #{appdir}/Wireshark.app/Contents/MacOS/Wireshark "$@"
I don't think it can be a symlinked `binary` on its own. I tried that prior to raising this PR and got the following error:

```
$ ln -s /Applications/Wireshark.app/Contents/MacOS/Wireshark /usr/local/bin/wireshark

$ wireshark
qt.qpa.plugin: Could not find the Qt platform plugin "cocoa" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

fish: Job 1, 'wireshark' terminated by signal SIGABRT (Abort)
```

> _[...] there needs to be an official source that recommends it_

Not entirely sure what you mean by this – do you mean an official upstream Wireshark source that recommends creating a shim script? If so, I don't think there is one, I just borrowed the shim pattern from various other Casks:

- https://github.com/Homebrew/homebrew-cask/search?q=shim

2020-06-21 00:37 UTC, vitorgalvao commented on Casks/wireshark.rb
> +      exec #{appdir}/Wireshark.app/Contents/MacOS/Wireshark "$@"
> I just borrowed the shim pattern from various other Casks

Those casks have a reason for the shim script: upstream directly recommends doing that linking for using the application from the command line because they behave like CLI tools.

If there’s no such upstream recommendation, we don’t add those. The result of a cask installation should be as close to a manual installation as possible. Otherwise someone would add shim scripts to every cask (not an exaggeration, it’s been tried), complicating them and polluting users’ paths with a ton of garbage.

2020-06-21 00:37 UTC, closed without merging