Add ytmdesktop v1.11.0
Homebrew/homebrew-cask pull request #84606
Opened 2020-06-18 18:48 UTC by adlerluiz

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).

## note
For token reference the app have 'desktop' and 'app' on name.

2020-06-18 19:20 UTC, vitorgalvao requested changes

2020-06-18 19:20 UTC, vitorgalvao commented on Casks/ytmdesktop.rb
> +  appcast 'https://ytmdesktop.app/#download'
`https://github.com/ytmdesktop/ytmdesktop/releases.atom`

2020-06-18 19:20 UTC, vitorgalvao commented on Casks/ytmdesktop.rb
> +cask 'ytmdesktop' do
Either `adlerluiz-youtube-music` or `ytmdesktop-youtube-music`. `ytmdesktop` ignores the token reference and `youtube-music` looks deceptively official.

2020-06-18 19:39 UTC, adlerluiz commented on Casks/ytmdesktop.rb
> +cask 'ytmdesktop' do
maybe ```ytmdesktop-app``` or ```ytmd-app``` or ```ytmd-player```

2020-06-18 19:39 UTC, adlerluiz commented on Casks/ytmdesktop.rb
> +  appcast 'https://ytmdesktop.app/#download'
I will modify, thank you

2020-06-18 22:44 UTC, adlerluiz commented
The build has already finished successfully, but here's a bug
![image](https://user-images.githubusercontent.com/2112638/85078980-12fff400-b19c-11ea-8a59-311a74167a9c.png)

https://travis-ci.com/github/Homebrew/homebrew-cask/builds/172113020

2020-06-19 00:20 UTC, vitorgalvao commented on Casks/ytmdesktop.rb
> +cask 'ytmdesktop' do
> maybe `ytmdesktop-app` or `ytmd-app` or `ytmd-player`

No. Specifically one of the two I mentioned. Do not ignore the token reference. Cask naming has clear guidelines.

2020-06-23 17:59 UTC, adlerluiz reviewed
changed

2020-06-23 19:14 UTC, ran-dall requested changes
@adlerluiz You were also missing the `zap` staza.

2020-06-23 19:14 UTC, ran-dall commented on Casks/ytmdesktop.rb
> +end
```suggestion
  zap trash: [
               '~/Library/Preferences/app.ytmd.plist',
               '~/Library/Saved Application State/app.ytmd.savedState',
             ]
end
```

2020-06-24 02:43 UTC, ran-dall requested changes
@adlerluiz Your 'style' was a big off. You have some extra spaces.

2020-06-24 02:44 UTC, ran-dall requested changes

2020-06-24 02:44 UTC, ran-dall commented on Casks/ytmdesktop-youtube-music.rb
> +end
```suggestion

  zap trash: [
               '~/Library/Preferences/app.ytmd.plist',
               '~/Library/Saved Application State/app.ytmd.savedState',
             ]
end
```

2020-06-24 02:50 UTC, adlerluiz commented on Casks/ytmdesktop-youtube-music.rb
> +end
I hope that everything is now right =)

2020-06-24 02:52 UTC, ran-dall approved these changes

2020-06-24 02:53 UTC, ran-dall commented
@adlerluiz Everything LGTM

2020-06-24 02:56 UTC, adlerluiz commented
```Done. Your build exited with 0.```

thanks for the support

2020-06-24 03:07 UTC, adlerluiz commented
I believe that there is something wrong with the hook, because in travis it is like ok and here still queued.

https://travis-ci.com/github/Homebrew/homebrew-cask/jobs/352935240

2020-06-24 03:15 UTC, ran-dall commented
@adlerluiz It's all good. The CIs go bananas all the time. It's something I'm working on. I'll simply leaving this open overnight if @vitorgalvao want's to take a look and merge; otherwise, I'll merge it for you tomorrow morning.

2020-06-24 03:20 UTC, adlerluiz commented
great, thank you

2020-06-24 12:39 UTC, merged