Add `subsync.app`
Homebrew/homebrew-cask pull request #84745
Opened 2020-06-21 13:56 UTC by zx8

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).

---

Ref: https://github.com/sc0ty/subsync/issues/88

2020-06-21 18:52 UTC, vitorgalvao requested changes

2020-06-21 18:52 UTC, vitorgalvao commented on Casks/subsync.rb
> +  url "https://github.com/sc0ty/subsync/releases/download/0.15/subsync-#{version}-mac-x86_64.dmg"
The `0.15` needs to be `#{version.major_minor}`.

2020-06-21 18:52 UTC, vitorgalvao commented on Casks/subsync.rb
> +
It’s missing the `app` stanza.

2020-06-21 19:05 UTC, gechr commented on Casks/subsync.rb
> +
https://github.com/Homebrew/homebrew-cask/pull/84745/commits/2c9e060c674089bec997cf4aeb6251bd0610d71f

2020-06-21 19:06 UTC, zx8 commented on Casks/subsync.rb
> +
https://github.com/Homebrew/homebrew-cask/pull/84745/commits/2c9e060c674089bec997cf4aeb6251bd0610d71f

2020-06-21 19:06 UTC, zx8 commented on Casks/subsync.rb
> +  url "https://github.com/sc0ty/subsync/releases/download/0.15/subsync-#{version}-mac-x86_64.dmg"
https://github.com/Homebrew/homebrew-cask/pull/84745/commits/acf259304541810df9b12d314f54dfce67cabfec

2020-06-21 20:04 UTC, miccal commented on Casks/subsync.rb
> +      exec #{appdir}/subsync.app/Contents/MacOS/subsync --cli "$@"
I think this should be:
```
exec '#{appdir}/subsync.app/Contents/MacOS/subsync --cli' "$@"
```

2020-06-21 21:03 UTC, zx8 commented on Casks/subsync.rb
> +      exec #{appdir}/subsync.app/Contents/MacOS/subsync --cli "$@"
https://github.com/Homebrew/homebrew-cask/pull/84745/commits/e1b22c2c8dbec7bf73e84746f501aabe7d17a73b

2020-06-21 22:20 UTC, miccal commented on Casks/subsync.rb
> +      exec '#{appdir}/subsync.app/Contents/MacOS/subsync' --cli "$@"
Thanks @zx8, but the trailing `'` should be after the `--cli` part, not after the `subsync` part.

2020-06-22 08:44 UTC, zx8 commented on Casks/subsync.rb
> +      exec '#{appdir}/subsync.app/Contents/MacOS/subsync' --cli "$@"
`subsync --cli` is not a single binary containing a space. The `--cli` part is a parameter to the `subsync` binary which enables CLI-mode.

2020-06-22 11:32 UTC, miccal commented on Casks/subsync.rb
> +      exec '#{appdir}/subsync.app/Contents/MacOS/subsync' --cli "$@"
@zx8 you are correct, apologies.

2020-06-23 00:40 UTC, vitorgalvao commented
Still missing [`zap`](https://github.com/sc0ty/subsync/issues/88#issuecomment-647169572) and [`depends_on`](https://github.com/sc0ty/subsync/issues/88#issuecomment-647227138) entries.

2020-06-23 08:13 UTC, zx8 commented
@vitorgalvao I'm not sure what you mean by missing `zap` entries? My understanding based on @sc0ty's linked comment was that `~/Library/Preferences/subsync/` should cover everything – what am I missing?

@sc0ty Before I add the `depends_on` stanza, can you confirm that the dependencies you mentioned in the linked comment ("ffmpeg or libav and pocketsphinx") do not come bundled with the DMG file? Do they need to be installed separately?

2020-06-23 19:17 UTC, vitorgalvao commented
> My understanding based on @sc0ty's linked comment was that `~/Library/Preferences/subsync/` should cover everything – what am I missing?

Nothing. Seems I misread, as I thought there were more files.

2020-06-23 19:18 UTC, vitorgalvao requested changes

2020-06-23 19:18 UTC, vitorgalvao commented on Casks/subsync.rb
> +  zap trash: [
If it’s only one, make it a string.

2020-06-23 19:56 UTC, sc0ty commented
> @sc0ty Before I add the `depends_on` stanza, can you confirm that the dependencies you mentioned in the linked comment (_"ffmpeg or libav and pocketsphinx"_) do not come bundled with the DMG file? Do they need to be installed separately?

All dependencies are bundled in. I was thinking about eventual future builds made specifically for brew - with libraries installed also from brew. But that's to be consider in the future. This version should work out of the box.

2020-06-23 21:51 UTC, zx8 commented on Casks/subsync.rb
> +  zap trash: [
https://github.com/Homebrew/homebrew-cask/pull/84745/commits/067f184b3bf057a3416b769428d045e08d9e04dd

As a side note, would be cool if `brew cask style --fix` could detect and auto-fix this?

2020-06-24 02:55 UTC, ran-dall approved these changes

2020-06-24 12:40 UTC, merged