Add Unclutter Latest
Homebrew/homebrew-cask pull request #85037
Opened 2020-06-26 12:31 UTC by Yoshi2889

This cask has been submitted a few times before but rejected because it was unclear if the app could be purchased from within the app and not requiring a download.

I have bought the app and it is possible to activate it with an activation link from the e-mail you receive afterwards. The app also mentions activation using a license file. It does not require a re-download, clicking the link brings you back to Unclutter which then activates and removes the trial restrictions. Therefore I don't think it differs from apps like Little Snitch or Alfred which are included in the repo.

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).

2020-06-26 15:26 UTC, ran-dall requested changes

2020-06-26 15:26 UTC, ran-dall commented on Casks/unclutter.rb
> +  sha256 :no_check
Needs a `version` preferably.

2020-06-26 15:26 UTC, ran-dall commented on Casks/unclutter.rb
> +end
Missing a `zap` stanza.

2020-06-26 16:07 UTC, Yoshi2889 commented on Casks/unclutter.rb
> +  sha256 :no_check
The site only gives out an Unclutter.zip without version info. I could version and hash this but whenever they push out an update it’ll break this cask, I’m not sure that’s preferable. Maybe there’s a different endpoint it uses for updates, I’ll have to check.

2020-06-26 16:13 UTC, vitorgalvao requested changes

2020-06-26 16:13 UTC, vitorgalvao commented on Casks/unclutter.rb
> +  url 'https://unclutterapp.com/files/Unclutter.zip'
Please add an [`appcast`](https://github.com/homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/appcast.md): `https://unclutterapp.com/files/Unclutter.zip`

2020-06-26 16:13 UTC, vitorgalvao commented on Casks/unclutter.rb
> +  sha256 :no_check
Usually you’d be right. But because we can have an `appcast`, it can be versioned.

2020-06-26 16:15 UTC, vitorgalvao commented
> but rejected because it was unclear if the app could be purchased from within the app

No, it was rejected because *it was clear it couldn’t* be purchased from outside the MAS. It’s irrelevant if it can be done from inside the app.

Right now there’s a clear direct payment option, so it can be accepted.

2020-06-26 16:20 UTC, ran-dall commented
@Yoshi2889 All you're missing now is a `zap` stanza.

2020-06-26 16:21 UTC, Yoshi2889 commented
I’ll take a look at the zap stanza later tonight, thank you for the feedback and changes!

2020-06-27 08:30 UTC, Yoshi2889 commented
I've added a zap stanza as requested; I wasn't sure if the `/var/folders` entries should also be included, I remember reading that macOS cleans those up automatically on reboot.

I mainly used AppCleaner to scan for these as it seems to usually be fairly accurate, this is what it came up with:

![image](https://user-images.githubusercontent.com/1280380/85918238-63d4b400-b850-11ea-89a7-ffdd2fb0b757.png)

Please let me know if I missed anything.

2020-06-27 11:32 UTC, merged