Add PlayStatus
Homebrew/homebrew-cask pull request #85128
Opened 2020-06-28 22:38 UTC by okb1100

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).

2020-06-30 14:51 UTC, vitorgalvao requested changes

2020-06-30 14:51 UTC, vitorgalvao commented on Casks/playstatus.rb
> +  url 'https://github.com/nbolar/PlayStatus/releases/latest/download/PlayStatus.app.zip'
Missing [`appcast`](https://github.com/homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/appcast.md).

2020-06-30 14:51 UTC, vitorgalvao commented on Casks/playstatus.rb
> +  version :latest
Needs version.

2020-06-30 14:51 UTC, vitorgalvao commented on Casks/playstatus.rb
> +  sha256 :no_check
Needs checksum.

2020-06-30 14:51 UTC, vitorgalvao commented
Thank you, but we’ll be rejecting this on account of [not being notable enough](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/rejected_casks.md):

> + The Cask is too obscure. Examples:
>   + A self-submitted app from a GitHub repository that is [not notable enough](https://github.com/Homebrew/homebrew-cask/pull/28103) (under 30 forks, 30 watchers, and 75 stars).
>   + [Electronic Identification (eID) software](https://github.com/Homebrew/homebrew-cask/issues/59021).

2020-06-30 14:51 UTC, closed without merging

2020-06-30 14:52 UTC, vitorgalvao commented
@SMillerDev Isn’t the notability check for casks live yet? I was under the impression it was. It it is, something went wrong, as it didn’t fire here.

2020-06-30 14:53 UTC, SMillerDev commented
It is, I'll check what's happening.

2020-06-30 14:58 UTC, SMillerDev commented
I think CI needs to be adjusted to run `brew cask audit --new-cask <token>` on new casks. Otherwise the notability check isn't triggered.

2020-07-01 01:02 UTC, ran-dall commented
> I think CI needs to be adjusted to run brew cask audit --new-cask <token> on new casks. Otherwise the notability check isn't triggered.

@SMillerDev @vitorgalvao I'll see what I can do.