Add Nocturnal.app v1.1
Homebrew/homebrew-cask pull request #85488
Opened 2020-07-07 01:36 UTC by joshjon

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [ x There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] `brew cask audit --new-cask {{cask_file}}` worked successfully.
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).

2020-07-07 02:13 UTC, miccal commented on Casks/nocturnal-screen.rb
> +  url 'https://github.com/joshjon/nocturnal/releases/download/v1.1/Nocturnal-1.1.zip'
Please change this to:
```
url "https://github.com/joshjon/nocturnal/releases/download/v#{version}/Nocturnal-#{version}.zip"
```

2020-07-07 02:21 UTC, joshjon commented on Casks/nocturnal-screen.rb
> +  url 'https://github.com/joshjon/nocturnal/releases/download/v1.1/Nocturnal-1.1.zip'
Done

2020-07-07 14:15 UTC, vitorgalvao requested changes

2020-07-07 14:15 UTC, vitorgalvao commented on Casks/nocturnal-screen.rb
> +cask 'nocturnal-screen' do
This does not follow the [token reference](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md). Needs to be `joshjon-nocturnal`.

2020-07-08 04:02 UTC, ran-dall approved these changes

2020-07-08 05:14 UTC, joshjon commented on Casks/nocturnal-screen.rb
> +cask 'nocturnal-screen' do
The reason for this is mainly becuase I dont have an official vendor name and preferred to not include my personal name in the cask title. However, if this is cumpolsary then all good.

2020-07-09 17:13 UTC, merged