Add mumu emoji picker app
Homebrew/homebrew-cask pull request #85586
Opened 2020-07-08 21:04 UTC by bval

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [ ] `brew cask audit --download {{cask_file}}` is error-free.
- [ ] `brew cask style --fix {{cask_file}}` reports no offenses.
- [ ] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [ ] `brew cask audit --new-cask {{cask_file}}` worked successfully.
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).

2020-07-10 12:15 UTC, vitorgalvao requested changes

2020-07-10 12:15 UTC, vitorgalvao commented on Casks/mumu.rb
> +  # vendors.paddle.com was verified as official when first introduced to the cask
Insufficient to disambiguate.

2020-07-10 12:15 UTC, vitorgalvao commented on Casks/mumu.rb
> +  url 'https://vendors.paddle.com/download/product/597910'
Use the last redirect URL: `https://paddle.s3.amazonaws.com/fulfillment_downloads/116824/597910/3UjvmpBGSxuQuBAVlQm6_Mumu%201.0.1.dmg`

And use interpolation in the version.

2020-07-10 12:15 UTC, vitorgalvao commented on Casks/mumu.rb
> +  version :latest
Add a version.

2020-07-10 12:15 UTC, vitorgalvao commented on Casks/mumu.rb
> +  sha256 :no_check
Add a checksum

2020-07-10 12:15 UTC, vitorgalvao commented on Casks/mumu.rb
> +  url 'https://vendors.paddle.com/download/product/597910'
Add an [`appcast`](https://github.com/homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/appcast.md): `https://macupdater.net/cgi-bin/check_urls/check_url_redirect.cgi?url=https://vendors.paddle.com/download/product/597910`

2020-07-11 20:56 UTC, merged

2020-07-11 21:14 UTC, bval commented
🎉 Thanks, @ran-dall!