Developer
Homebrew/homebrew-cask pull request #85820
Opened 2020-07-12 18:07 UTC by danielbayley

- [x] `brew cask style --fix {{commands}}` reports no offenses.
- [x] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.

Add `list_associated_files` developer helper script to list all associated files of a given app name, Bundle ID, or Cask token.

2020-07-13 10:55 UTC, vitorgalvao requested changes

2020-07-13 10:55 UTC, vitorgalvao commented on cmd/brewcask-find-bundle-id.rb
> +def bundle_id_from(app)
Why three methods?

2020-07-13 10:55 UTC, vitorgalvao commented on developer/bin/list_associated_files
> +raise 'A cask-token, bundle.ID, or App Name argument is required' if ARGV.empty?
`cask token`, `bundle ID`, `app name` (no hyphen, no period, lowercase).

Also, it should mention that a combination of those can be used (or is encouraged).

2020-07-13 10:55 UTC, vitorgalvao commented on developer/bin/list_associated_files
> +if %r{^\w+\.\w+\.\w+$}.match? args
What’s this trying to match? If it’s looking for bundle IDs, it will fail a lot. Not all bundle IDs have three sections or dots.

2020-07-13 10:55 UTC, vitorgalvao commented on developer/bin/list_associated_files
> +  stdout, = Open3.capture3 'brew', 'cask', 'find-bundle-id', *args
Why not `capture2`?

2020-07-13 10:55 UTC, vitorgalvao commented on cmd/brewcask-find-bundle-id.rb
> +ARGV.shift
I don’t feel this file is warranted, and it shouldn’t be an external command. The code should be included in the other one.

2020-07-13 10:56 UTC, vitorgalvao commented
Pinging @ran-dall. I know you’re a fan of an external tool to do something similar, so you’ll be better able to compare results.

2020-07-14 03:09 UTC, ran-dall commented on developer/bin/list_associated_files
> +if %r{^\w+\.\w+\.\w+$}.match? args
This is one of my main concerns as well.

2020-07-14 03:13 UTC, ran-dall commented on developer/bin/list_associated_files
> +search = ['Library/*', 'Documents{,/*}', 'Users/Shared', 'private/var/**']
I also feel this is a bit heavy handed and would prefer not so much globbing.

2020-07-14 03:14 UTC, ran-dall requested changes
@danielbayley This is a pretty decent idea, however I feel there more that can be done. I agree with all the comments left by @vitorgalvao and I've left a few of my own. Let me know if you need any help or anything...

2020-08-05 13:51 UTC, vitorgalvao commented
@danielbayley Still interested in this, or should we close?

2020-08-05 22:36 UTC, danielbayley commented
> Still interested in this, or should we close?

@vitorgalvao Yes, I definitely want it to be a thing; I’ll take another pass at it soon…

2020-08-29 12:38 UTC, miccal commented
> @ran-dall What tool is that?

@danielbayley [this one I believe.](https://github.com/nrlquaker/homebrew-createzap)

2020-12-12 19:34 UTC, danielbayley commented
> This pull request has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs.

I'll get back to it soon!

2020-12-20 00:30 UTC, closed without merging