Add Mac Mouse Fix Latest
Homebrew/homebrew-cask pull request #85868
Opened 2020-07-13 19:42 UTC by gerlero

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
https://github.com/Homebrew/homebrew-cask/pull/70036 was closed without merging.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] `brew cask audit --new-cask {{cask_file}}` worked successfully.
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
https://github.com/Homebrew/homebrew-cask/pull/70036 was rejected due to low notability at the time. I understand that the notability criterion is now met as the software has over 200 stars [on GitHub](https://github.com/noah-nuebling/mac-mouse-fix).
- [x] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).

2020-07-13 19:56 UTC, vitorgalvao requested changes

2020-07-13 19:56 UTC, vitorgalvao commented on Casks/mouse-fix.rb
> +  url 'https://mousefix.org/maindownload/MacMouseFix.zip'
Use the download on https://github.com/noah-nuebling/mac-mouse-fix/releases. Do not forget to run `style`, as it will point out a comment you’ll need to add.

2020-07-13 19:56 UTC, vitorgalvao commented on Casks/mouse-fix.rb
> +  url 'https://mousefix.org/maindownload/MacMouseFix.zip'
Add an [`appcast`](https://github.com/homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/appcast.md).

2020-07-13 19:56 UTC, vitorgalvao commented on Casks/mouse-fix.rb
> +  version :latest
Add a version.

2020-07-13 19:56 UTC, vitorgalvao commented on Casks/mouse-fix.rb
> +  sha256 :no_check
Add a checksum.

2020-07-13 19:56 UTC, vitorgalvao commented on Casks/mouse-fix.rb
> +cask 'mouse-fix' do
Add `-prefpane` to the token and name.

2020-07-13 20:53 UTC, gerlero commented on Casks/mouse-fix.rb
> +  url 'https://mousefix.org/maindownload/MacMouseFix.zip'
While I agree that making a versioned cask would be better, the GitHub releases for this particular project seem to contain only pre-release versions, and do not contain the expected version (0.9.1 as of now) that is downloadable from the project's homepage (in fact, the "Pre-releases" link on the project's README on GitHub points to the GitHub releases page, while the "Download" link points to the URL I used in the cask).

2020-07-13 21:29 UTC, vitorgalvao commented on Casks/mouse-fix.rb
> +  url 'https://mousefix.org/maindownload/MacMouseFix.zip'
Considering this is a preference pane and thus (presumably):

1. Does not auto-update.
2. Will not be very popular.

Having it unversioned is a disadvantage to the point of refusal. If you can convince the author to provide stable versioned releases with an appcast (can be an HTML page), we can accept it.

2020-07-13 22:28 UTC, gerlero commented on Casks/mouse-fix.rb
> +  url 'https://mousefix.org/maindownload/MacMouseFix.zip'
Regarding your points:

1. The software actually does include a self-update feature, and is set to check for updates automatically by default (I did not include the auto-update flag in the file because it was understanding that such flag is only relevant to versioned casks).
2. I cannot say much on the expected popularity of this cask. For my part, I don't see why it would be less popular than many other utility casks. The software has seen a previous attempt at inclusion as a cask, it is mentioned on various forums when searching the web for the functionality it provides (noted, many of those mentions were made by the author of the software), and the project meets the notability criterion that was the reason for the previous refusal. However, this is your call ultimately.

I agree that having the cask (actually, any cask) unversioned is not optimal, but as a user I'd rather it not be rejected for this reason.

2020-07-13 23:55 UTC, ran-dall commented on Casks/mouse-fix.rb
> +  url 'https://mousefix.org/maindownload/MacMouseFix.zip'
Just to point out, being 'unversioned' was one of the reason we rejected in the past.

2020-07-14 00:01 UTC, ran-dall commented on Casks/mouse-fix.rb
> +  url 'https://mousefix.org/maindownload/MacMouseFix.zip'
@gerleno Another option is to contact @noah-nuebling and ask him to properly use the GitHub Release system. I've done this on several occasions (most recently with the folks from Obsidian) and I've had success.

2020-08-05 13:53 UTC, vitorgalvao commented
@gerlero Still interested in making the fixes, or should we close?

2020-08-05 15:26 UTC, gerlero commented
I won't pursue this further for now. I'll close it.

2020-08-05 15:26 UTC, closed without merging

2021-03-03 02:49 UTC, noah-nuebling commented
Hey guys, if you're still interested in adding Mac Mouse Fix to brew, it's using GitHub releases now. I think it would be cool if it was on HomeBrew! Let me know if I can help with anything.

2021-03-03 12:34 UTC, vitorgalvao commented
@noah-nuebling We don’t take cask request. If you want the cask included, you’ll have to submit the PR.

2021-03-03 19:06 UTC, noah-nuebling commented
@vitorgalvao Alright thanks for letting me know. I'll look into it at some point.

2021-03-03 19:17 UTC, ran-dall commented
@noah-nuebling I actually kept a copy of this cask alive on my personal tap (https://github.com/ran-dall/homebrew-tap/blob/master/Casks/mouse-fix.rb) and it's been used quite a bit by a number of folks. I'll update it and resubmit it if you'd like...

2021-03-03 19:21 UTC, noah-nuebling commented
@ran-dall Wow, that's great! I would really appreciate that.

2021-03-03 19:21 UTC, ran-dall commented
@noah-nuebling You got it. I'll get it submitted today for you guys.

2021-03-03 19:39 UTC, noah-nuebling commented
Thanks @ran-dall! :)