Add HyperRogue 11.3a
Homebrew/homebrew-cask pull request #85870
Opened 2020-07-13 23:22 UTC by SeekingMeaning

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] `brew cask audit --new-cask {{cask_file}}` worked successfully.
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).

2020-07-13 23:54 UTC, ran-dall requested changes
@SeekingMeaning Have you checked if this needs an `zap` stanza?

2020-07-14 01:46 UTC, SeekingMeaning commented
Not 100% sure how I would go about doing that, any pointers?

2020-07-14 02:55 UTC, ran-dall commented
@SeekingMeaning You can it manually with an uninstaller app or you can try @nrlquaker's [createzap project](https://github.com/nrlquaker/homebrew-createzap).

2020-07-14 04:36 UTC, miccal commented on Casks/hyperrogue.rb
> +  url "https://roguetemple.com/z/hyper/hyperrogue-#{version.tr('.', '')}.dmg"
Please change this to:
```
url "https://roguetemple.com/z/hyper/hyperrogue-#{version.no_dots}.dmg"
```

2020-07-14 04:36 UTC, miccal commented on Casks/hyperrogue.rb
> +  appcast 'https://github.com/zenorogue/hyperrogue/releases.atom'
I am not sure that is is a suitable `appcast` -- it lists version 11.3o as the latest, and seems to only provide the source code.

2020-07-14 04:55 UTC, ran-dall commented on Casks/hyperrogue.rb
> +  appcast 'https://github.com/zenorogue/hyperrogue/releases.atom'
@SeekingMeaning `https://roguetemple.com/z/hyper/download.php` maybe?

2020-08-05 13:54 UTC, vitorgalvao commented
@SeekingMeaning Still interested in this?

2020-08-05 16:02 UTC, SeekingMeaning commented
Whoops, closing this for now

2020-08-05 16:02 UTC, closed without merging