Add slippi (a fork of Dolphin) v2.2.0
Homebrew/homebrew-cask pull request #86219
Opened 2020-07-19 00:29 UTC by lukebrb

Project slippi is a fork of Dolphin that implements rollback netplay.

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [✅ ] `brew cask audit --download {{cask_file}}` is error-free.
- [✅ ] `brew cask style --fix {{cask_file}}` reports no offenses.
- [✅ ] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [✅] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, **if adding a new cask**:

- [✅ ] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [ ✅] `brew cask audit --new-cask {{cask_file}}` worked successfully.
- [ ✅] `brew cask install {{cask_file}}` worked successfully.
- [✅ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ✅] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ✅] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).

2020-07-19 02:49 UTC, miccal commented on Casks/slippi.rb
> +  sha256 :no_check
[The `sha256` needs to be set.](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md)

2020-07-19 02:49 UTC, miccal commented on Casks/slippi.rb
> +
Please add the following lone above the `url` stanza:
```
# github.com/project-slippi/Ishiiruka/ was verified as official when first introduced to the cask
```

2020-07-19 02:49 UTC, miccal commented on Casks/slippi.rb
> +  homepage 'https://slippi.gg'
Please add a trailing slash `/`:
```
homepage 'https://slippi.gg/'
```

2020-07-19 02:49 UTC, miccal commented
See https://slippi.gg/netplay for some justification of using `target:`.

2020-07-20 19:19 UTC, lukebrb commented
Hi, the revisions are done — thank you for your thorough feedback!

> See https://slippi.gg/netplay for some justification of using `target:`.

As an addendum to this, since Project Slippi is a fork of Dolphin, users might already have the main Dolphin distribution installed on their machine. Using `target` allows us to get around this potential edge case, as users might want to have both editions of Dolphin installed.

2020-07-20 19:33 UTC, vitorgalvao requested changes

2020-07-20 19:33 UTC, vitorgalvao commented on Casks/slippi.rb
> +cask 'slippi' do
Does not follow the [token reference](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md). Must be `project-slippi-dolphin`.

2020-07-20 19:33 UTC, vitorgalvao commented on Casks/slippi.rb
> +  name 'Project Slippi'
No “Project”.

2020-07-20 19:33 UTC, vitorgalvao commented on Casks/slippi.rb
> +  app 'Dolphin.app', target: 'Slippi-Dolphin.app'
Remove the `target`. This is a fork of a fork of a fork and doesn’t have many stars; it doesn’t warrant an exception to the token rules.

2020-07-20 20:00 UTC, lukebrb commented
Done, thanks again!

2020-07-21 00:54 UTC, ran-dall commented
@lukebrb Have you checked if this requires a `zap` stanza?

2020-07-21 01:26 UTC, lukebrb commented
> @lukebrb Have you checked if this requires a `zap` stanza?

Good catch, didn't realize that Dolphin emu left cache artifacts. Added.

2020-07-21 01:48 UTC, lukebrb commented
> @lukebrb Have you checked if this requires a `zap` stanza?

Good catch, added one based on the standard Dolphin emu cask. Thanks for your patience, everyone!

2020-07-21 13:32 UTC, merged