Add Gmail Desktop v2.20.0
Homebrew/homebrew-cask pull request #86433
Opened 2020-07-23 02:24 UTC by weichenw

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] `brew cask audit --new-cask {{cask_file}}` worked successfully.
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).

2020-07-23 04:41 UTC, miccal commented on Casks/gmail-desktop.rb
> +  url "https://github.com/timche/gmail-desktop/releases/download/v2.20.0/gmail-desktop-#{version}-mac.dmg"
Please change this to:
```
url "https://github.com/timche/gmail-desktop/releases/download/v#{version}/gmail-desktop-#{version}-mac.dmg"
```

2020-07-23 04:48 UTC, weichenw commented on Casks/gmail-desktop.rb
> +  url "https://github.com/timche/gmail-desktop/releases/download/v2.20.0/gmail-desktop-#{version}-mac.dmg"
Fixed the url. Thanks

2020-07-24 12:39 UTC, vitorgalvao requested changes

2020-07-24 12:39 UTC, vitorgalvao commented on Casks/gmail-desktop.rb
> +cask 'gmail-desktop' do
Needs to be `timche-gmail-desktop`. Otherwise it looks erroneously official.

2020-07-25 09:06 UTC, weichenw commented on Casks/gmail-desktop.rb
> +cask 'gmail-desktop' do
You got a valid point there. I have renamed it to timche-gmail-desktop

2020-07-25 11:41 UTC, merged