Make `zap` a requriement
Homebrew/homebrew-cask pull request #86432
Opened 2020-07-23 02:08 UTC by ran-dall

Updated `zap` and related documentation to make `zap` a requirement.

2020-07-23 11:49 UTC, miccal commented
Below are my thoughts on this:

- I don't think `appcast` should be moved from _Required_ to _Optional_, as there are many casks for which there is no suitable `appcast`; and of course there are casks that use `version :latest` and `sha256 :no_check` and thus by definition do not have an `appcast`.

- For `zap` the _simplest_ way to find any user files and the shared resources associated with a particular cask in my opinion is to run the command `sudo find / -iname "*{search item}*"` and an inspection of the output (well, at least that is how I do it). I do think it is fine to also mention the "CreateZap Project" and an app such as "AppCleaner" as other examples.

- As for making the `zap` _Required_ for new casks, I do not agree with this. In my years of using `homebrew-cask` I have found that the `zap` stanza is greatly influenced by the macOS version and the version of the cask, and can change quite a lot -- see [this issue](https://github.com/Homebrew/homebrew-cask/issues/40557), for example. I have also found that one has to use a particular cask for a while (involving opening the app, creating new files, opening existing files, saving new and existing files, exporting, etc.) before one would get a _complete_ list of user files and shared resources associated with a particular cask -- the many contributors to `homebrew-cask` (and the other cask repo's) already do a great job of adding and /or updating the `zap` stanza based on their personal experience of using the app, and this should continue to be encouraged.

2020-07-23 12:22 UTC, miccal commented
Here is an example of my thoughts behind `zap` [this PR](https://github.com/Homebrew/homebrew-cask/pull/85691) added a new cask for `Apparency.app`, a wonderful and interesting app that I have been using since it was added. Running `sudo find` just now revealed [another file](https://github.com/Homebrew/homebrew-cask/pull/86443) that needed to be added to `zap`.

2020-07-23 15:32 UTC, core-code commented
i agree that appcasts are absolutely essential to keep casks updated. that said, sometimes there are just none...

regarding the zap stanza, i think we've already talked about the idea that if homebrew knew the bundle-identifier of the installed app, all the 'standard' locations could be zapped automatically. i think this would be great. but unless someone is willing to actually implement this...

2020-07-23 17:00 UTC, ran-dall commented
> i think we've already talked about the idea that if homebrew knew the bundle-identifier of the installed app, all the 'standard' locations could be zapped automatically

I like this idea.

2020-07-23 17:31 UTC, vitorgalvao requested changes

2020-07-23 17:31 UTC, vitorgalvao commented on doc/cask_language_reference/stanzas/zap.md
> +There are several ways to create a `zap` stanza. The simplest method is to use @nrlquaker's [CreateZap Project](https://github.com/nrlquaker/homebrew-createzap), which can automatically generate the
The first sentence can be cut and the paragraph will retain the meaning.

2020-07-23 17:31 UTC, vitorgalvao commented on doc/cask_language_reference/all_stanzas.md
> +| `appcast`          | no                            | a URL providing an appcast feed to find updates for this Cask (see also [Appcast Stanza Details](stanzas/appcast.md))
This part needs to be reverted. A required stanza isn’t one that we want, but one without which a cask will not function and will fail `audit`.

That doesn’t apply to neither `appcast` nor `zap`, and it never can because there are situations when indeed we don’t have those.

2020-07-23 17:40 UTC, vitorgalvao commented
> I was under the impression that `appcast`s are now required, unless it's a special case

Heavily encouraged, but not required.

> I know it's not a 'hard' rule, but it's a harder rule than `optional`

As hinted in the review, it’s optional in the sense it’s not mandatory for the cask to be functional, not in the sense of “do it only if you want to”.

> and I think people should make an effort to find the `appcast` or ask for help in finding it.

I do too, but I don’t think changing its position on that list will accomplish that. Adding the appcast in the PR itself, before being merged, is an effective step we take.

> I still believe in practice we should have a way of getting rid of what we install in a end-users computer.

I agree with the sentence, but I don’t agree that’s the reality. We’re not the ones installing the preference files, the apps are.

2020-07-23 18:07 UTC, ran-dall commented
> I agree with the sentence, but I don’t agree that’s the reality. We’re not the ones installing the preference files, the apps are.

I see what you're saying, but the apps are there because they were installed with HBC. So I'd argue there's a level of 'cause' to the 'effect' that separates us from being directly responsible; but I still feel that we're the force that pushed the events forwarded. 

Furthermore, if a user where to remove a `cask`, then removing the remaining 'support' files become exponentially harder because you can't use something like 'AppCleaner' to remove them. You'd have to use something like 'CleanMyMac X' or 'Onyx' and hope they pick up the orphans.

2020-07-23 18:08 UTC, vitorgalvao commented on doc/cask_language_reference/all_stanzas.md
> +| `zap`              | yes                           | additional procedures for a more complete uninstall, including user files and shared resources (see also [Zap Stanza Details](stanzas/zap.md))
I meant both. Even if we start requesting `zap`s on submissions, “required” should mean “the simplest possible cask”.

2020-07-23 22:43 UTC, vitorgalvao commented
> Furthermore, if a user where to remove a `cask`, then removing the remaining 'support' files become exponentially harder because you can't use something like 'AppCleaner' to remove them. You'd have to use something like 'CleanMyMac X' or 'Onyx' and hope they pick up the orphans.

That’s a good point. Though we still fail there—you can’t `zap` an uninstalled cask, but we should be able to.

2020-07-24 01:01 UTC, ran-dall commented
I like @core-code's idea and it's something I'll be looking into the upcoming days. Still I think making `zap` required now it a step in the right direction.

That said, should I look into doing some modifications so that we can run `zap` even if the cask isn't installed?

2020-07-24 12:27 UTC, vitorgalvao commented
> should I look into doing some modifications so that we can run `zap` even if the cask isn't installed?

That would be great, thank you. Note that `zap` implicitly calls `uninstall` so the goal here would be to, if `zap` is called but the cask isn’t installed, skip `uninstall` and proceed to `zap` only.

`zap` can do everything `uninstall` can. I f that becomes a problem, if would be fine to make it so that a `zap` on an uninstalled cask only does the path operations (`rmdir`, `delete`, `trash`).

2020-07-24 13:18 UTC, core-code commented
> That would be great, thank you. Note that zap implicitly calls uninstall so the goal here would be to, if zap is called but the cask isn’t installed, skip uninstall and proceed to zap only.

why? wouldn't the ability to 'uninstall' *also* be benificial even if the cask isn't installed? i only ever install manually and the removal of launchctl jobs and other things would also be great without actually having to install it...

2020-07-24 16:54 UTC, vitorgalvao commented
> wouldn't the ability to 'uninstall' _also_ be benificial even if the cask isn't installed?

Our uninstallation isn’t robust enough for that. As is it, I wouldn’t even say we’re good at uninstall what we install (https://github.com/Homebrew/homebrew-cask/issues/62223). That’s why I mentioned:

> If that becomes a problem, if would be fine to make it so that a `zap` on an uninstalled cask only does the path operations (`rmdir`, `delete`, `trash`).

2020-10-25 15:15 UTC, claui commented on doc/cask_language_reference/stanzas/zap.md
> +The simplest method is to use @nrlquaker's [CreateZap Project](https://github.com/nrlquaker/homebrew-createzap), which can automatically generate the stanza. In the few instances, it fails to pick an
```suggestion
The simplest method is to use @nrlquaker's [CreateZap Project](https://github.com/nrlquaker/homebrew-createzap), which can automatically generate the stanza. In a few instances, it fails to pick anything up so manual creation may be required.

Manual creation can be facilitated with:
- some of the developer tools that are already available in Homebrew Cask,
- `sudo find / -iname "*{search item}*"`,
- an uninstaller tool (such as [AppCleaner](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/appcleaner.rb))
- or visually inspecting the usual suspects, i.e. `/Library/{'Application Support',LaunchAgents,LaunchDaemons,Frameworks,Logs,Preferences,PrivilegedHelperTools}` and `~/Library/{'Application Support',Caches,Containers,LaunchAgents,Logs,Preferences,'Saved Application State'}`.
```

2020-10-25 15:20 UTC, claui commented
> you can’t `zap` an uninstalled cask, but we should be able to.

@vitorgalvao I think we can do it with `zap --force`. I use it regularly while working on `zap` stanza entries.

2020-12-12 03:21 UTC, vitorgalvao commented
These instructions don’t suggest `zap` is mandatory, but encourage it and explain how to make it. I don’t expect there to be controversy in merging this.

2020-12-12 03:22 UTC, vitorgalvao approved these changes

2020-12-12 04:15 UTC, merged