[wip] Add descript.app
Homebrew/homebrew-cask pull request #86696
Opened 2020-07-28 17:46 UTC by freeslugs

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [ ] `brew cask audit --download {{cask_file}}` is error-free.
- [ ] `brew cask style --fix {{cask_file}}` reports no offenses.
- [ ] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [ ] `brew cask audit --new-cask {{cask_file}}` worked successfully.
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).

2020-07-28 19:09 UTC, freeslugs commented
Installation and uninstallation work with a few caveats would love to get some help on:
1. I'm using `export HOMEBREW_FORCE_BREWED_CURL=1` to avoid a curl SSL error 
2. The installation opens the app and prints the logs of the app into the terminal -> should we pipe the output to dev/null? 
3. Uninstall uses `delete`, as per their docs, just remove the app from applications folder.

2020-07-28 19:09 UTC, freeslugs commented
And they don't use versioning on the download page.

2020-07-29 13:42 UTC, freeslugs commented
Any ideas why the CI timed out?

2020-07-29 17:04 UTC, vitorgalvao requested changes

2020-07-29 17:04 UTC, vitorgalvao commented on Casks/descript.rb
> +  installer script: "Descript Installer.app/Contents/MacOS/Descript Installer"
This needs to use [`installer :manual`](https://github.com/homebrew/homebrew-cask/blob/c129758c8086d86b3d33cc8c2045b4a26bee2a83/doc/cask_language_reference/stanzas/installer.md#installer-manual).

2020-07-29 17:04 UTC, vitorgalvao commented on Casks/descript.rb
> +  # uninstall pkgutil: 'com.descript.beachcube' # this didnt remove the app
Remove. This is not a `pkg`.

2020-07-29 17:04 UTC, vitorgalvao commented on Casks/descript.rb
> +  uninstall delete: "/Applications/Descript.app"
> Uninstall uses delete, as per their docs

Can you link me?

2020-07-29 17:08 UTC, vitorgalvao commented
Just tried it on a VM and this is one of those bad “installers” which needs to be opened manually and just downloads the app which is *1.5GB*.

Thank you for the submission, but we won’t accept this one, they’re an awful user experience that we can do nothing to improve.

2020-07-29 17:08 UTC, closed without merging