Add Avid Link.app v20.6.0
Homebrew/homebrew-cask pull request #86933
Opened 2020-08-01 05:32 UTC by targendaz2

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [ ] `brew cask audit --download {{cask_file}}` is error-free.
- [ ] `brew cask style --fix {{cask_file}}` reports no offenses.
- [ ] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [ ] `brew cask audit --new-cask {{cask_file}}` worked successfully.
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).

2020-08-01 05:34 UTC, targendaz2 commented
I could not find a suitable page to use as an appcast.

2020-08-01 12:55 UTC, miccal commented
https://github.com/Homebrew/homebrew-cask/pull/86934#discussion_r463959354

2020-08-03 12:12 UTC, vitorgalvao requested changes

2020-08-03 12:12 UTC, vitorgalvao commented on Casks/avid-link.rb
> +  uninstall_script = "#{appdir}/Avid_Uninstallers/Avid Link/Avid Link Uninstaller.app/Contents/MacOS/AvidUninstaller"
No point in a variable that will only be used once. Use it directly further down.

2020-08-05 18:54 UTC, targendaz2 commented
Closing this. App will be installed as part of cask `sibelius` ( #86934 )

2020-08-05 18:54 UTC, closed without merging