Add Sibelius.app v2020.6
Homebrew/homebrew-cask pull request #86934
Opened 2020-08-01 10:06 UTC by targendaz2

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [ ] `brew cask audit --download {{cask_file}}` is error-free.
- [ ] `brew cask style --fix {{cask_file}}` reports no offenses.
- [ ] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [ ] `brew cask audit --new-cask {{cask_file}}` worked successfully.
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).

2020-08-01 12:55 UTC, miccal commented on Casks/sibelius.rb
> +  # avid.secure.force.com was verified as official when first introduced to the cask
Please remove this comment, it is not necessary.

2020-08-01 12:55 UTC, miccal commented on Casks/sibelius.rb
> +          "attributeSetting" => 0,
If you set this to `1`, would your [other PR](https://github.com/Homebrew/homebrew-cask/pull/86933) be necessary?

2020-08-01 12:55 UTC, miccal commented on Casks/sibelius.rb
> +             cask:  "avid-link"
If you set `"attributeSetting" => 1` for `com.avid.tmp.AvidLink.pkg` below in `choices:`, would this be necessary?

2020-08-01 12:55 UTC, miccal commented on Casks/sibelius.rb
> +  end
Please remove the `caveats`; license information is not necessary for casks.

2020-08-01 18:47 UTC, targendaz2 commented on Casks/sibelius.rb
> +             cask:  "avid-link"
@miccal if the `attributeSetting` for `com.avid.tmp.AvidLink.pkg` in `choices:` was set to `1`, the `depends_on` wouldn't be necessary. However, there are other apps that depend on Avid Link that might be submitted in the future. I was using `microsoft-auto-update` being split into its own cask as a precedent.

2020-08-01 18:48 UTC, targendaz2 commented on Casks/sibelius.rb
> +          "attributeSetting" => 0,
See below comment.

2020-08-03 12:14 UTC, vitorgalvao requested changes

2020-08-03 12:14 UTC, vitorgalvao commented on Casks/sibelius.rb
> +             cask:  "avid-link"
> However, there are other apps that depend on Avid Link that might be submitted in the future.

*If* that happens we can think about it then. In the meantime, this should have as few moving parts (dependencies) as possible.

2020-08-05 19:11 UTC, targendaz2 commented on Casks/sibelius.rb
> +             cask:  "avid-link"
I've added the info from the Avid Link cask into this one and closed that PR.

2020-08-05 22:13 UTC, vitorgalvao commented on Casks/sibelius.rb
> +  uninstall launchctl: "com.avid.AvidLink.uninstall.HelperTool",
Is this one related to AvidLink only? If so it may be better added to `zap`. Same with `pkgutil: "com.avid.tmp.AvidLink.pkg"`.

2020-08-11 17:25 UTC, targendaz2 commented on Casks/sibelius.rb
> +  uninstall launchctl: "com.avid.AvidLink.uninstall.HelperTool",
Yeah, they are. I only added them at all since the CI check said they were still remaining after uninstall. Should I move them to `zap`?

2020-08-12 13:50 UTC, vitorgalvao commented on Casks/sibelius.rb
> +  uninstall launchctl: "com.avid.AvidLink.uninstall.HelperTool",
> Should I move them to `zap`?

Yes, please.

2020-08-28 00:58 UTC, targendaz2 commented on Casks/sibelius.rb
> +  uninstall launchctl: "com.avid.AvidLink.uninstall.HelperTool",
Done

2020-08-28 21:02 UTC, reitermarkus commented on Casks/sibelius.rb
> +             cask:  "avid-link"
I disagree with this. If we can depend on `avid-link`, we should do that, otherwise we will need to add hacky workarounds again to properly uninstall this (and get this passing) on CI.

2020-08-28 21:16 UTC, vitorgalvao commented on Casks/sibelius.rb
> +             cask:  "avid-link"
@reitermarkus Alright. I don’t feel strongly about it, so if you do, let’s do that.

Apologies @targendaz2, could you revert to the separate submissions?

2020-10-19 22:40 UTC, miccal commented
Closing due to lack of response.

2020-10-19 22:40 UTC, closed without merging