Add flutter SDK v1.20.1
Homebrew/homebrew-cask pull request #87344
Opened 2020-08-10 09:17 UTC by jota3

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [ ] `brew cask audit --download {{cask_file}}` is error-free.
- [ ] `brew cask style --fix {{cask_file}}` reports no offenses.
- [ ] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [ ] `brew cask audit --new-cask {{cask_file}}` worked successfully.
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).

2020-08-10 12:01 UTC, miccal commented on Casks/flutter.rb
> +  app "flutter"
There is no `app` for this, only a `binary`, correct?

2020-08-10 12:03 UTC, miccal commented
Does this not also require the Android SDK, Android Studio, CocoaPods and a full install of Xcode to be functional?

2020-08-10 12:17 UTC, jota3 commented on Casks/flutter.rb
> +  app "flutter"
It's a full sdk so it includes a few binaries (main one being `flutter`), sources, examples ... so I used `app` to expose the whole set in the Applications folder. Do you have any better suggestion ?

2020-08-10 12:22 UTC, jota3 commented
> Does this not also require the Android SDK, Android Studio, CocoaPods and a full install of Xcode to be functional?

@miccal They are not part of the system requirements of the SDK (see the [official docs](https://flutter.dev/docs/get-started/install/macos)).

2020-08-10 12:26 UTC, miccal commented on Casks/flutter.rb
> +  app "flutter"
[`suite`](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/suite.md) maybe?

2020-08-10 12:28 UTC, miccal commented
> > Does this not also require the Android SDK, Android Studio, CocoaPods and a full install of Xcode to be functional?
> 
> @miccal They are not part of the system requirements of the SDK (see the [official docs](https://flutter.dev/docs/get-started/install/macos)).

True, but won't `flutter doctor` immediately report all these things missing as an issue, and hence not immediately function without them?

2020-08-10 12:34 UTC, miccal commented
Please also not that the addition of `flutter` has been refused in the past:

https://github.com/Homebrew/homebrew-cask/pull/72679
https://github.com/Homebrew/homebrew-cask/pull/63170
https://github.com/Homebrew/homebrew-cask/pull/46579

and hence it may be wise to wait until @vitorgalvao has had a chance to review and comment on this PR before making any changes.

2020-08-10 12:40 UTC, vitorgalvao commented on Casks/flutter.rb
> +  app "flutter"
Yes, `suite` seems correct.

2020-08-10 12:40 UTC, vitorgalvao commented on Casks/flutter.rb
> +  uninstall rmdir: [
`rmdir` is for empty directories. You want `delete`. But this can be removed, this would already be done automatically.

2020-08-10 12:41 UTC, vitorgalvao commented on Casks/flutter.rb
> +  caveats <<~EOS
Remove this. If we had this caveat for every app that needed it, half the casks would have it.

2020-08-10 12:43 UTC, vitorgalvao commented on Casks/flutter.rb
> +  url "https://storage.googleapis.com/flutter_infra/releases/stable/macos/flutter_macos_#{version}-stable.zip"
How do we get here from the homepage?

2020-08-10 14:42 UTC, vitorgalvao commented
> Please also note that the addition of flutter to Cask has been refused in the past

Thank you for remembering those things!

This name did ring a bell and I checked. The last time this was discussed, good arguments were made for this as a cask and [I gave the thumbs up](https://github.com/Homebrew/homebrew-cask/issues/78848#issuecomment-603526463) but the user ended up not submitting.

2020-08-11 14:22 UTC, jota3 commented on Casks/flutter.rb
> +  url "https://storage.googleapis.com/flutter_infra/releases/stable/macos/flutter_macos_#{version}-stable.zip"
flutter.dev > Get Started > macOS > Get the Flutter SDK

2020-08-11 14:23 UTC, jota3 commented on Casks/flutter.rb
> +  uninstall rmdir: [
Ok, removed, thanks.

2020-08-11 14:25 UTC, jota3 commented on Casks/flutter.rb
> +  app "flutter"
Ok, updated, thanks.

2020-08-11 14:25 UTC, jota3 commented on Casks/flutter.rb
> +  caveats <<~EOS
Ok, I wasn't sure but I couldn't find anything regarding this in the docs, I may have missed it though. Otherwise it might be worth a note ?

2020-08-11 14:36 UTC, jota3 commented
@vitorgalvao CI is failing now. Is `desc` stanza only mandatory for `suite` type ?

2020-08-12 00:06 UTC, miccal commented
@jota3 the `desc` stanza is relatively new -- see https://github.com/Homebrew/brew/pull/8137 and https://github.com/Homebrew/homebrew-cask/pull/87436.

2020-08-16 17:15 UTC, andreiborisov commented on Casks/flutter.rb
> +  binary "flutter/bin/flutter"
Please also symlink `dart` binary:
```ruby
  binary "flutter/bin/dart"
```

2020-08-16 17:16 UTC, andreiborisov requested changes
Seems to work fine, would love for it to be merged😍 Let me know if I can help.

2020-08-16 17:18 UTC, andreiborisov requested changes
Please also symlink `dart` binary:
```ruby
  binary "flutter/bin/dart"
```

2020-08-16 17:18 UTC, andreiborisov commented on Casks/flutter.rb
> +  binary "flutter/bin/flutter"
```suggestion
  binary "flutter/bin/dart"
  binary "flutter/bin/flutter"
```

2020-08-16 17:35 UTC, andreiborisov requested changes

2020-08-16 17:35 UTC, andreiborisov commented on Casks/flutter.rb
> +  suite "flutter"
```suggestion

```

I don't think there is a point in installing SDK in the Applications folder. It's just a Git repo without any GUI applications. Probably should be deleted.

2020-08-16 18:25 UTC, andreiborisov commented
An updated version of the PR: https://github.com/Homebrew/homebrew-cask/pull/87690

2020-08-19 11:54 UTC, laeo commented
Hello, any updates on this PR? When it can be merged?

2020-08-19 12:01 UTC, vitorgalvao commented
Closing in favour of https://github.com/Homebrew/homebrew-cask/pull/87690.

2020-08-19 12:01 UTC, closed without merging