Add new cask Firefly.app (firefly) v0.9.8
Homebrew/homebrew-cask pull request #87491
Opened 2020-08-12 09:41 UTC by tddschn

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] `brew cask audit --new-cask {{cask_file}}` worked successfully.
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).

2020-08-12 13:30 UTC, vitorgalvao requested changes

2020-08-12 13:30 UTC, vitorgalvao commented on Casks/firefly.rb
> +  url "https://raw.githubusercontent.com/cdtmirrors/yhc/master/yhc.dmg"
Please add an [`appcast`](https://github.com/homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/appcast.md).

2020-08-12 13:30 UTC, vitorgalvao commented on Casks/firefly.rb
> +  # raw.githubusercontent.com was verified as official when first introduced to the cask
`raw.githubusercontent.com/cdtmirrors/yhc`.

2020-08-12 15:48 UTC, tddschn commented
this app is no longer being maintained / updated but many people are still using it - is an `appcast` needed in this case?

2020-08-12 15:49 UTC, tddschn commented on Casks/firefly.rb
> +  # raw.githubusercontent.com was verified as official when first introduced to the cask
this app is no longer being maintained / updated but many people are still using it - is an `appcast` needed in this case?

2020-08-12 15:50 UTC, tddschn commented on Casks/firefly.rb
> +  url "https://raw.githubusercontent.com/cdtmirrors/yhc/master/yhc.dmg"
this app is no longer being maintained / updated but many people are still using it - is an `appcast` needed in this case?

2020-08-17 00:52 UTC, vitorgalvao commented
Thank you, but we’d rather not accept apps that are already discontinued.

2020-08-17 00:52 UTC, closed without merging