Update gureumkim from 1.10.1 to 1.11.1
Homebrew/homebrew-cask pull request #87560
Opened 2020-08-13 17:17 UTC by Doosies

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [ ] `brew cask audit --download {{cask_file}}` is error-free.
- [ ] `brew cask style --fix {{cask_file}}` reports no offenses.
- [ ] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

2020-08-13 23:47 UTC, miccal requested changes

2020-08-13 23:47 UTC, miccal commented on Casks/gureumkim.rb
> +  sha256 "f1e7db79b49a7675dbfc8ff57b4b55eaa55b3018803c6c46671c88b402b496c2"
Please add a blank line between the `sha256` stanza and the `url` comment.

2020-08-13 23:50 UTC, miccal commented
You have a `.DS_Store` file added to this pull request, please remove it.

2020-08-14 19:10 UTC, core-code commented
thanks there. i've opened a new PR without the .DS_store file https://github.com/Homebrew/homebrew-cask/pull/87605

2020-08-14 19:10 UTC, closed without merging