add Clover Theme Manager
Homebrew/homebrew-cask pull request #87643
Opened 2020-08-15 08:52 UTC by ye4241

HELP NEEDED, I cannot found the correct the url and appcast url started with https://downloads.sourceforge.net due to the download url is not in files of sourceforge projects.

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [ ] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [ ] `brew cask audit --new-cask {{cask_file}}` worked successfully.
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).

2020-08-17 00:51 UTC, vitorgalvao requested changes

2020-08-17 00:51 UTC, vitorgalvao commented on Casks/clover-theme-manager.rb
> +cask "clover-theme-manager" do
No hyphens.

2020-08-17 00:51 UTC, vitorgalvao commented on Casks/clover-theme-manager.rb
> +  url "https://sourceforge.net/p/cloverefiboot/themes/ci/master/tree/CloverThemeManagerApp/Updates/CloverThemeManager.zip?format=raw"
See other sourceforge casks and follow their pattern.

2020-08-20 21:25 UTC, yurikoles commented
From official [thread](https://www.insanelymac.com/forum/topic/302674-clover-theme-manager/):
>Clover Theme Manager has now been retired
>This is due to the lack of time to maintain and develop any further
>Please see Clover.app instead which includes a theme manager

The problem of obtaining URL in official format is that it was never released in files section, it's a binary that's committed to Git repo.

2020-08-20 22:42 UTC, vitorgalvao commented
If it’s been discontinued, we’d rather not add it.

2020-08-20 22:42 UTC, closed without merging