Use Backblaze Uninstaller and switch to latest version as Backblaze downloads are unversioned
Homebrew/homebrew-cask pull request #88039
Opened 2020-08-23 14:48 UTC by mudge

Backblaze [do not offer versioned downloads of their installer](https://secure.backblaze.com/download.htm) so attempting to upgrade the Cask causes issues with mismatched checksums if the previous installer is still cached.
    
This means we lose the ability to detect updates but forcibly upgrading the Cask (e.g. with `brew cask upgrade backblaze`) should now work as expected.

Rather than having to manually delete the various applications, preference panes and `launchctl` jobs installed by the Backblaze Installer ourselves, use the included Backblaze Uninstaller script instead.
    
Note that the Uninstaller will not delete user-specific files so we retain the existing zap stanza.

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [ ] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

2020-08-23 23:46 UTC, miccal commented on Casks/backblaze.rb
> +  uninstall script: "Backblaze Uninstaller.app/Contents/MacOS/Backblaze Uninstaller"
Please change this to:
```
uninstall script: "#{staged_path}/Backblaze Uninstaller.app/Contents/MacOS/Backblaze Uninstaller"
```

2020-08-24 06:30 UTC, mudge commented on Casks/backblaze.rb
> +  uninstall script: "Backblaze Uninstaller.app/Contents/MacOS/Backblaze Uninstaller"
Updated to use `staged_path`.

2020-08-24 13:51 UTC, vitorgalvao requested changes

2020-08-24 13:51 UTC, vitorgalvao commented on Casks/backblaze.rb
> +  uninstall script: "#{staged_path}/Backblaze Uninstaller.app/Contents/MacOS/Backblaze Uninstaller"
This is not a script, it will call a GUI which complicates automation and which we do not want [until we can do it properly](https://github.com/Homebrew/homebrew-cask/issues/24377).

2020-08-24 13:51 UTC, vitorgalvao commented on Casks/backblaze.rb
> -  appcast "https://secure.backblaze.com/api/clientversion.xml",
The whole point of the appcast is that we can detect when updates are available.

2020-08-24 13:51 UTC, vitorgalvao commented on Casks/backblaze.rb
> -  version "7.0.2.464"
It’s by having a version that `brew upgrade` can work properly. You’re removing that ability.

2020-08-24 13:51 UTC, vitorgalvao commented
The cask is correct as is. Everything you mentioned is done intentionally.

2020-08-24 13:51 UTC, closed without merging

2020-08-24 14:03 UTC, mudge commented
Thanks for reviewing, @vitorgalvao.

It's especially useful to know [support for GUI uninstalls are a separate issue](https://github.com/Homebrew/homebrew-cask/issues/24377).

Re the versioning of Backblaze: in retrospect, sacrificing the functioning `appcast` and `version` is overkill when my original issue is a much smaller one: that upgrading Backblaze in-place fails because the checksum fails due to all versions of the installer being cached as `install_backblaze.dmg`.

Frustratingly, this is hard to reproduce due to the fact it's not possible to download an older version of the installer and I notice that all downloads in `~/Library/Caches/Homebrew/downloads` seem to be prefixed with a checksum.

I'll re-test when a new version of the Backblaze installer is released to see if I can reproduce the problem more thoroughly then.