add swiftjsonmodeler cask
Homebrew/homebrew-cask pull request #88108
Opened 2020-08-25 09:48 UTC by CodeOcenS

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [ ] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] `brew cask audit --new-cask {{cask_file}}` worked successfully.
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).

2020-08-25 14:03 UTC, vitorgalvao requested changes

2020-08-25 14:03 UTC, vitorgalvao commented on Casks/swiftjsonmodeler.rb
> +cask "swiftjsonmodeler" do
`swiftjsonmodeler-for-xcode`

2020-08-25 14:03 UTC, vitorgalvao commented on Casks/swiftjsonmodeler.rb
> +  sha256 :no_check
`sha256` also needs to be set. You can find what it is by running `shasum --algorithm 256` on the downloaded file.

2020-08-25 14:03 UTC, vitorgalvao commented on Casks/swiftjsonmodeler.rb
> +  desc "The Swift JSON Model generator for Xcode extension(Swift JSON 转模 Xcode 插件)"
Remove the parenthetical.

2020-08-25 14:03 UTC, vitorgalvao commented
Thank you, but we’ll be rejecting this on account of [not being notable enough](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/rejected_casks.md):

> + The Cask is too obscure. Examples:
>   + A self-submitted app from a GitHub repository that is [not notable enough](https://github.com/Homebrew/homebrew-cask/pull/28103) (under 30 forks, 30 watchers, and 75 stars).
>   + [Electronic Identification (eID) software](https://github.com/Homebrew/homebrew-cask/issues/59021).

2020-08-25 14:03 UTC, closed without merging

2020-08-26 03:33 UTC, CodeOcenS commented
OK, I understand. Thank you.