Create gotomeeting
Homebrew/homebrew-cask pull request #88180
Opened 2020-08-26 09:00 UTC by iMonZ

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [ ] `brew cask audit --download {{cask_file}}` is error-free.
- [ ] `brew cask style --fix {{cask_file}}` reports no offenses.
- [ ] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [ ] `brew cask audit --new-cask {{cask_file}}` worked successfully.
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).

2020-08-26 09:02 UTC, iMonZ commented
The issue: #42312 is now fixed so the cask can now be added again to the repo

2020-08-26 10:40 UTC, miccal commented
The cask file is missing the `.rb` extension, and please read the documentation concerning [how to add a cask](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md) carefully to ensure that _both_ `brew cask audit gotomeeting --download` and `brew cask style --fix gotomeeting` pass.

2020-08-26 10:55 UTC, iMonZ commented
@miccal the command  `brew cask style --fix gotomeeting` is not working on my machine!
Could you please help me with that and run this on your machine?

`brew cask style --fix gotomeeting                     
Fetching gem metadata from https://rubygems.org/.........
Could not find sorbet-static-0.5.5869-universal-darwin-14 in any of the sources
Error: failed to run `/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/bundle install`!`

2020-08-26 13:37 UTC, iMonZ commented
Everything is fixed now!

2020-08-26 15:59 UTC, vitorgalvao requested changes

2020-08-26 15:59 UTC, vitorgalvao commented on Casks/gotomeeting.rb
> +  app "GotoMeeting.app"
Please add [`zap`](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/zap.md).

2020-08-26 22:50 UTC, miccal commented on Casks/gotomeeting.rb
> +  version "10.12.0-b18425"
Please change this to:
```
version "10.12.0,b18425"
```

2020-08-26 22:50 UTC, miccal commented on Casks/gotomeeting.rb
> +  url "https://link.gotomeeting.com/latest-dmg"
Please change this to:
```
# builds.cdn.getgo.com/builds/g2m/ was verified as official when first introduced to the cask
url "https://builds.cdn.getgo.com/builds/g2m/#{version.after_comma}/GoToMeeting.dmg"
```

2020-08-26 22:50 UTC, miccal commented on Casks/gotomeeting.rb
> +  desc "It's an online meeting, desktop sharing, and video conferencing software package"
Please change this to:
```
desc "An online meeting, desktop sharing and video conferencing software package"
```

2020-08-26 22:50 UTC, miccal commented on Casks/gotomeeting.rb
> +  appcast "https://support.goto.com/meeting/help/whats-new-g2m010012"
Please change this to:
```
appcast "https://support.goto.com/meeting/help#g2m-whats-new"
```
This one does not have a weird version string (like `010012`).

2020-08-27 08:05 UTC, miccal commented on Casks/gotomeeting.rb
> +  appcast "https://support.goto.com/meeting/help#g2m-whats-new"
There need to be a comma `,` at the end of the `appcast`, like so:
```
appcast "https://support.goto.com/meeting/help#g2m-whats-new",
```
I omitted that earlier, apologies.

2020-08-27 08:05 UTC, miccal commented on Casks/gotomeeting.rb
> +    "~/Library/Application\ Support/LogMeInInc/GoToMeetingElectron",
You do not need to escape the spaces here -- please remove the `\`'s.

2020-08-27 08:19 UTC, iMonZ commented
Thanks!
This should be fine now

2020-08-27 08:19 UTC, iMonZ commented
Thanks!
This should be fine now

2020-08-27 08:19 UTC, iMonZ commented
Thanks!
This should be fine now

2020-08-27 08:19 UTC, iMonZ commented
Thanks!
This should be fine now

2020-08-27 08:19 UTC, iMonZ commented
Thanks!
This should be fine now

2020-08-27 08:19 UTC, iMonZ commented
Thanks!
This should be fine now

2020-08-27 08:19 UTC, iMonZ commented
Thanks!
This should be fine now

2020-08-29 01:33 UTC, miccal commented
@iMonZ there are still some `style` errors that need to be fixed:
```
Error: Style check failed.
== /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/gotomeeting.rb ==
C: 10:  9: Description shouldn't start with an indefinite article, i.e. "An".
C: 14:  1: stanza groups should be separated by a single empty line
C: 14:  1: Trailing whitespace detected.
C: 17: 68: Trailing whitespace detected.
```

2020-09-02 10:33 UTC, iMonZ commented
The Style Command was fixed by homebrew so its working again that's why It took so long!
This should be fine now!

2020-09-02 12:01 UTC, vitorgalvao commented on Casks/gotomeeting.rb
> +  url "https://builds.cdn.getgo.com/builds/g2m/#{version.after_comma}/GoToMeeting.dmg"
How can we get here from the homepage and without login in?

2020-09-02 12:02 UTC, vitorgalvao commented on Casks/gotomeeting.rb
> +  appcast "https://support.goto.com/meeting/help#g2m-whats-new"
https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/appcast.md#parameters

> If no `must_contain` is given, the check considers from the beginning of the `version` string until the first character that isn’t alphanumeric or a period. Example: if `version` is `6.26b-14,40`, the check will see `6.26b`. This is so it covers most cases by default, while still allowing complex `version`s suitable for interpolation on the rest of the cask.

2020-09-02 12:04 UTC, iMonZ commented on Casks/gotomeeting.rb
> +  url "https://builds.cdn.getgo.com/builds/g2m/#{version.after_comma}/GoToMeeting.dmg"
From the Change-log Website (Appcast)

2020-09-02 15:16 UTC, miccal commented on Casks/gotomeeting.rb
> +  url "https://builds.cdn.getgo.com/builds/g2m/#{version.after_comma}/GoToMeeting.dmg"
@vitorgalvao the `appcast` lists the link `https://link.gotomeeting.com/latest-dmg`, [and I suggested that this be changed to](https://github.com/Homebrew/homebrew-cask/pull/88180#discussion_r477633793) `https://builds.cdn.getgo.com/builds/g2m/#{version.after_comma}/GoToMeeting.dmg` by carefully following the re-directs from `https://link.gotomeeting.com/latest-dmg`.

2020-09-02 15:22 UTC, miccal commented on Casks/gotomeeting.rb
> +  appcast "https://support.goto.com/meeting/help#g2m-whats-new"
Actually, the `appcast` should probably be changed back to the original one, namely `https://support.goto.com/meeting/help/whats-new-g2m010012`, since `https://support.goto.com/meeting/help#g2m-whats-new` has `https://support.goto.com/meeting/help/whats-new-g2m010012` embedded in it, and hence the `version` is not being shown in the page source of `https://support.goto.com/meeting/help#g2m-whats-new` but is in the page source of `https://support.goto.com/meeting/help/whats-new-g2m010012`.

This should not be an issue, however -- the string `010012` is I think a support page reference/product reference, and _not_ a reference to the `version` -- the fact that it contains a `10` and a `12` is a coincidence.

2020-09-02 20:34 UTC, vitorgalvao commented on Casks/gotomeeting.rb
> +  url "https://builds.cdn.getgo.com/builds/g2m/#{version.after_comma}/GoToMeeting.dmg"
It’s fine to use a `url` from the appcast, but in this case the `appcast` isn’t from inside the app and is from a different domain as the homepage.

2020-09-03 00:41 UTC, miccal commented on Casks/gotomeeting.rb
> +  url "https://builds.cdn.getgo.com/builds/g2m/#{version.after_comma}/GoToMeeting.dmg"
Finding the `url` is very convoluted  -- [I suppose this is why it was removed in the first place.](https://github.com/Homebrew/homebrew-cask/pull/42312)

2020-09-04 12:09 UTC, iMonZ commented on Casks/gotomeeting.rb
> +  url "https://builds.cdn.getgo.com/builds/g2m/#{version.after_comma}/GoToMeeting.dmg"
Hey I am confused now what should or could I do?

2020-09-06 02:28 UTC, vitorgalvao commented on Casks/gotomeeting.rb
> +  url "https://builds.cdn.getgo.com/builds/g2m/#{version.after_comma}/GoToMeeting.dmg"
Even the unversioned link was from a different domain to the homepage. So this looks to be a [walled build](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask), meaning [we will not accept it](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#unofficial-vendorless-and-walled-builds).

Thank you anyway.

2020-09-06 04:17 UTC, iMonZ commented on Casks/gotomeeting.rb
> +  url "https://builds.cdn.getgo.com/builds/g2m/#{version.after_comma}/GoToMeeting.dmg"
This is just a link from a different domain

2020-09-06 04:18 UTC, iMonZ commented on Casks/gotomeeting.rb
> +  url "https://builds.cdn.getgo.com/builds/g2m/#{version.after_comma}/GoToMeeting.dmg"
@miccal it was removed first because you have an strange installer package but now you get a normal dmg with the Application itself inside it

2020-09-06 04:21 UTC, iMonZ commented on Casks/gotomeeting.rb
> +  url "https://builds.cdn.getgo.com/builds/g2m/#{version.after_comma}/GoToMeeting.dmg"
@vitorgalvao you find the Download url inside the Appcast Website so the official website is goto.com and inside this domain you get a download link to the getgo server

2020-09-06 12:23 UTC, vitorgalvao commented on Casks/gotomeeting.rb
> +  url "https://builds.cdn.getgo.com/builds/g2m/#{version.after_comma}/GoToMeeting.dmg"
> This is just a link from a different domain

Which is a potential security risk. If the `url` pointed to a random Dropbox directory, would you trust it were official unless you could verify it? Please don’t make me repeat the linked documentation. It’s written down (and I linked to it) for a reason.

> you find the Download url inside the Appcast Website so the official website is goto.com

Then don’t you agree you should’ve used the official website as the `homepage` in the first place?

2020-09-06 12:26 UTC, vitorgalvao approved these changes

2020-09-06 12:56 UTC, merged

2020-09-06 14:47 UTC, iMonZ commented
Thank you!