Update app_not_upgrading.md:: `brew cask upgrade` -> `brew upgrade --cask`
Homebrew/homebrew-cask pull request #88681
Opened 2020-09-04 00:00 UTC by miccal

https://github.com/Homebrew/homebrew-cask/issues/88679

```
|-> brew cask upgrade
Error: Calling brew cask upgrade is deprecated! Use brew upgrade --cask instead.
```

2020-09-04 01:51 UTC, reitermarkus commented on doc/faq/app_not_upgrading.md
> +Refer to the `upgrade` section of the `brew` manual page by running `man -P 'less --pattern "^ {7}upgrade"' brew`.
This `man` command doesn't seem to work.

2020-09-04 02:20 UTC, miccal commented on doc/faq/app_not_upgrading.md
> +Refer to the `upgrade` section of the `brew` manual page by running `man -P 'less --pattern "^ {7}upgrade"' brew`.
Should be `man -P 'less --pattern "^ {3}upgrade"' brew``, fixed now.

2020-09-05 03:06 UTC, reitermarkus commented on doc/faq/app_not_upgrading.md
> +* Reference it specifically in the `upgrade` command. While `brew upgrade` ignores it, `brew upgrade --cask {{cask_name}}` doesn’t.
> While `brew upgrade` ignores it

Seems like this isn't actually true.

2020-09-05 03:48 UTC, miccal commented on doc/faq/app_not_upgrading.md
> +* Reference it specifically in the `upgrade` command. While `brew upgrade` ignores it, `brew upgrade --cask {{cask_name}}` doesn’t.
> > While `brew upgrade` ignores it
> 
> Seems like this isn't actually true.

Fixed, thank you.

2020-09-05 13:46 UTC, vitorgalvao commented on doc/faq/app_not_upgrading.md
> +After running `brew upgrade --cask`, you may notice some casks you think should be upgrading, aren’t.
I think this will raise some confusion (same on line `18`) and make people think `--cask` is now required. We should call it `brew upgrade` throughout to make it clear the one command does everything.

2020-09-06 03:37 UTC, miccal commented on doc/faq/app_not_upgrading.md
> +After running `brew upgrade --cask`, you may notice some casks you think should be upgrading, aren’t.
Fixed, thank you.

2020-09-06 12:44 UTC, vitorgalvao requested changes

2020-09-06 12:44 UTC, vitorgalvao commented on doc/faq/app_not_upgrading.md
> +After running `brew upgrade` or `brew upgrade --cask`, you may notice some casks you think should be upgrading, aren’t.
We can remove the `brew upgrade --cask` mention if we handle it well in https://github.com/Homebrew/homebrew-cask/pull/88682. This is a FAQ page for a specific issue, and the difference between the commands isn’t relevant.

2020-09-06 13:47 UTC, miccal commented on doc/faq/app_not_upgrading.md
> +After running `brew upgrade` or `brew upgrade --cask`, you may notice some casks you think should be upgrading, aren’t.
Fixed.

2020-09-06 14:26 UTC, vitorgalvao approved these changes

2020-09-06 14:31 UTC, merged