Add duoshao.app v0.1.7
Homebrew/homebrew-cask pull request #88901
Opened 2020-09-08 14:10 UTC by wangkezun

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [ ] `brew cask audit --download {{cask_file}}` is error-free.
- [ ] `brew cask style --fix {{cask_file}}` reports no offenses.
- [ ] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [ ] `brew cask audit --new-cask {{cask_file}}` worked successfully.
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).

2020-09-08 22:08 UTC, miccal commented on Casks/duoshao.rb
> +  # haokuai.cdn.tinyservices.net was verified as official when first introduced to the cask
Please change this to:
```
# haokuai.cdn.tinyservices.net/duoshao/ was verified as official when first introduced to the cask
```

2020-09-08 22:08 UTC, miccal commented on Casks/duoshao.rb
> +  url "https://haokuai.cdn.tinyservices.net/duoshao/Duoshao-#{version}.dmg"
Please add the following `appcast`:
```
appcast "https://electron-releases-1259797650.cos.ap-nanjing.myqcloud.com/duoshao/latest-mac.yml"
```
I am not certain if the `1259797650` string changes, though.

2020-09-08 22:08 UTC, miccal commented on Casks/duoshao.rb
> +  desc "多少记账"
Please change this to an English version of the `desc`.

2020-09-11 17:24 UTC, vitorgalvao requested changes

2020-09-11 17:24 UTC, vitorgalvao commented on Casks/duoshao.rb
> +  desc "duoshao"
This is not a description, it’s the name of the software. It needs to explain what this is or does.

2020-09-13 11:35 UTC, vitorgalvao approved these changes

2020-09-13 11:48 UTC, merged