anka software casks + anka flow description and formatting fixes
Homebrew/homebrew-cask pull request #89249
Opened 2020-09-14 21:45 UTC by NorseGaud

Veertu Inc is taking over the management of the casks for our software as well as adding a few.

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [X] `brew cask audit --download {{cask_file}}` is error-free.
```
audit for anka-virtualization: passed
audit for anka-flow: passed
audit for anka-build-cloud-registry: passed
audit for anka-build-cloud-controller-and-registry: passed
```
- [X] `brew cask style --fix {{cask_file}}` reports no offenses.
The only problem with this is that my description of the software requires "macOS VM" in it and it's saying `Description shouldn't contain the platform.`
- [X] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [X] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, **if adding a new cask**:

- [X] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [X] `brew cask audit --new-cask {{cask_file}}` worked successfully.
```
audit for anka-virtualization: passed
audit for anka-flow: passed
audit for anka-build-cloud-registry: passed
audit for anka-build-cloud-controller-and-registry: passed
```
- [X] `brew cask install {{cask_file}}` worked successfully.
- [X] `brew cask uninstall {{cask_file}}` worked successfully.
- [X] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [X] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).

2020-09-14 22:17 UTC, reitermarkus commented on Casks/anka-build-cloud-controller-and-registry.rb
> +  appcast "https://macupdater.net/cgi-bin/check_urls/check_url_redirect.cgi?url=https://veertu.com/downloads/ankacontroller-registry-mac-latest"
@NorseGaud, given you work for upstream, it would be nice if a proper appcast could be provided.

2020-09-14 22:19 UTC, reitermarkus commented on Casks/anka-virtualization.rb
> +cask "anka-virtualization" do
Where is the difference here to `anka-flow`? It installs the same thing.

2020-09-14 22:23 UTC, reitermarkus commented on Casks/anka-build-cloud-registry.rb
> +  ], delete: [
Split this (and similar lines) into two separate lines.

2020-09-14 23:03 UTC, NorseGaud commented on Casks/anka-virtualization.rb
> +cask "anka-virtualization" do
There isn't actually. Flow is just a license type. I worried someone would complain if we just deleted the cask, but if you suggest pulling it, I'm ok with that.

2020-09-15 11:30 UTC, reitermarkus commented on Casks/anka-virtualization.rb
> +cask "anka-virtualization" do
In that case delete/rename the other one.

2020-09-15 15:15 UTC, reitermarkus requested changes

2020-09-15 15:15 UTC, reitermarkus commented on Casks/anka-virtualization.rb
> +  # ANKA-1950: remove the need for unload and handle it in the uninstall.sh
Remove this comment.

2020-09-15 15:15 UTC, reitermarkus commented on Casks/anka-virtualization.rb
> +  desc "Anka is a suite of software for creating and managing macOS VMs to run on top of Apple hardware and macOS. It enables the creation of or integration with existing container-like DevOps workfl
The descriptions are all too long. As for the word macOS, please try rewording it to not use it if possible.

2020-09-15 15:27 UTC, NorseGaud commented on Casks/anka-virtualization.rb
> +  desc "Anka is a suite of software for creating and managing macOS VMs to run on top of Apple hardware and macOS. It enables the creation of or integration with existing container-like DevOps workfl
Hmm, I'm not sure it's possible to reword to get around using macOS. The software is `...a suite of software for creating and managing macOS VMs to run on top of Apple hardware and macOS.` If we just said VMs, it wouldn't be clear whether they're macOS, Linux, or Windows. What do you suggest here? I can shorten, regardless.

2020-09-16 17:07 UTC, reitermarkus commented on Casks/anka-virtualization.rb
> +  desc "Anka is a suite of software for creating and managing macOS VMs to run on top of Apple hardware and macOS. It enables the creation of or integration with existing container-like DevOps workfl
Yes, please shorten them. Also, currently all describe the whole suite instead of the individual parts.

2020-09-16 17:19 UTC, NorseGaud commented on Casks/anka-virtualization.rb
> +  desc "Anka is a suite of software for creating and managing macOS VMs to run on top of Apple hardware and macOS. It enables the creation of or integration with existing container-like DevOps workfl
✅

2020-09-16 22:23 UTC, reitermarkus requested changes
Descriptions are still too long. Also please run `brew cask style` and fix the other errors.

2020-09-16 22:23 UTC, reitermarkus commented on Casks/anka-flow.rb
> -  zap trash: [
This should still be present.

2020-09-16 22:26 UTC, NorseGaud commented on Casks/anka-flow.rb
> -  zap trash: [
The files it's removing are handled by the uninstall.sh script. I'm not sure any of those are needed. What does zap do? I'm having trouble finding the docs for it :(

2020-09-16 22:49 UTC, miccal commented on Casks/anka-flow.rb
> -  zap trash: [
[Documentation for `zap`.](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/zap.md)

2020-09-16 22:53 UTC, reitermarkus commented on Casks/anka-flow.rb
> -  zap trash: [
So `uninstall.sh` removed user-generated files like logs and preferences?

2020-09-16 22:54 UTC, NorseGaud commented
> Descriptions are still too long. Also please run `brew cask style` and fix the other errors.

Are you saying that we can't get around the "macOS" in the description?

2020-09-16 23:00 UTC, reitermarkus commented
> Are you saying that we can't get around the "macOS" in the description?

Not for now. If we indeed can't find a way to reword this we'll have to add an exception for this.

2020-09-17 07:40 UTC, core-code commented
> Not for now. If we indeed can't find a way to reword this we'll have to add an exception for this.

maybe this would be a warning instead of an error?

2020-09-17 12:55 UTC, NorseGaud commented on Casks/anka-flow.rb
> -  zap trash: [
Ah, yes, thanks for those docs! Zap makes more sense now! I've added proper zaps to all of the files.

2020-09-17 15:22 UTC, vitorgalvao commented
`Suite for creating and managing virtual machines` is more than enough as a description. There no need to mention the software’s name or that it is a “suite *of software*” (all casks are).

Descriptions should be thought of as helpers for searchability and disambiguation, not as ways to browse for stuff that might be interesting. In that sense, there’s no need to mention this only handles macOS VMs, the user should already have that notion.

2020-09-17 15:30 UTC, NorseGaud commented
> `Suite for creating and managing virtual machines` is more than enough as a description. There no need to mention the software’s name or that it is a “suite _of software_” (all casks are).
> 
> Descriptions should be thought of as helpers for searchability and disambiguation, not as ways to browse for stuff that might be interesting. In that sense, there’s no need to mention this only handles macOS VMs, the user should already have that notion.

Can I just remove the desc entirely then? What is the reason for not allowing macOS in the description? I personally find it extremely useful when I run brew info.

2020-09-17 15:33 UTC, reitermarkus commented
> What is the reason for not allowing macOS

Casks only work on macOS, so that is redundant information in a description.

2020-09-17 15:35 UTC, NorseGaud commented
> > What is the reason for not allowing macOS
> 
> Casks only work on macOS, so that is redundant information in a description.

Hmm, but the software itself runs macOS VMs. Is the desc used for explaining what will be installed? Or what the software is for?

2020-09-17 15:38 UTC, core-code commented
> Descriptions should be thought of as helpers for searchability and disambiguation, not as ways to browse for stuff that might be interesting.

hm, if the description isn't meant to 'describe' but just help with searching, maybe we should have added a taglist or category system instead

2020-09-17 15:43 UTC, NorseGaud commented
Side question: How do I handle this?
```
❯ brew cask style --fix Casks/anka-virtualization.rb
Casks/anka-virtualization.rb:1:1: C: Block has too many lines. [35/25]
cask "anka-virtualization" do ...
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Casks/anka-virtualization.rb:1:1: C: Missing frozen string literal comment.
cask "anka-virtualization" do
^

1 file inspected, 2 offenses detected, 1 more offense can be corrected with `rubocop -A`
Error: Style check failed.```

2020-09-17 15:56 UTC, NorseGaud commented
> > Descriptions should be thought of as helpers for searchability and disambiguation, not as ways to browse for stuff that might be interesting.
> 
> hm, if the description isn't meant to 'describe' but just help with searching, maybe we should have added a taglist or category system instead.
> 
> i believe handling macOS VMs is a distinctive features because normally VMs run Linux or Windows clients.

If I use `macintosh VMs`, it passes. Not sure I like that though :\

2020-09-17 16:18 UTC, vitorgalvao commented
> Can I just remove the desc entirely then?

No, because `desc` is mandatory for new casks. Unlike other cask features—such as installation and uninstallation—descriptions don’t need to be exact to be useful, removing one because it isn’t perfect isn’t a step in the right direction.

> hm, if the description isn't meant to 'describe' but just help with searching, maybe we should have added a taglist or category system instead.

`desc` was already available in HB so it makes sense to use the same stanza. They are meant to describe, yes, and my suggestion still does that. My point is that what descriptions *do* (describe) has a goal (what they *are for*), and that goal isn’t to make HBC a browsable directory, so they don’t need to be comprehensive.

While 80 characters might sometimes be too short, 277 characters and two sentences is definitely too long. This description in particular has a bunch of fluff: “to run on top of Apple hardware and macOS”, that it has a GUI, and mentioning all the CI systems it runs on is too much non-essential information.

For the record, I do think the description would be better if it mentioned it only runs macOS VMs (and `Suite for creating and managing macOS VMs` would still be more than enough and cover all that’s important). But I don’t think it’s at all worth it to [make an exception](https://github.com/Homebrew/homebrew-cask/pull/89249#issuecomment-693710046) for this cask, *it’s not important enough for the added complexity*.

> maybe this would be a warning instead of an error?

Agreed.

> How do I handle this?

That looks like an error on our part. Casks shouldn’t have a limit.

> If I use `macintosh VMs`, it passes. Not sure I like that though :\

Does `mac VMs` work?

2020-09-17 16:39 UTC, NorseGaud commented
> > Can I just remove the desc entirely then?
> 
> No, because `desc` is mandatory for new casks. Unlike other cask features—such as installation and uninstallation—descriptions don’t need to be exact to be useful, removing one because it isn’t perfect isn’t a step in the right direction.
> 
> > hm, if the description isn't meant to 'describe' but just help with searching, maybe we should have added a taglist or category system instead.
> 
> `desc` was already available in HB so it makes sense to use the same stanza. They are meant to describe, yes, and my suggestion still does that. My point is that what descriptions _do_ (describe) has a goal (what they _are for_), and that goal isn’t to make HBC a browsable directory, so they don’t need to be comprehensive.
> 
> While 80 characters might sometimes be too short, 277 characters and two sentences is definitely too long. This description in particular has a bunch of fluff: “to run on top of Apple hardware and macOS”, that it has a GUI, and mentioning all the CI systems it runs on is too much non-essential information.
> 
> For the record, I do think the description would be better if it mentioned it only runs macOS VMs (and `Suite for creating and managing macOS VMs` would still be more than enough and cover all that’s important). But I don’t think it’s at all worth it to [make an exception](https://github.com/Homebrew/homebrew-cask/pull/89249#issuecomment-693710046) for this cask, _it’s not important enough for the added complexity_.
> 
> > maybe this would be a warning instead of an error?
> 
> Agreed.
> 
> > How do I handle this?
> 
> That looks like an error on our part. Casks shouldn’t have a limit.
> 
> > If I use `macintosh VMs`, it passes. Not sure I like that though :\
> 
> Does `mac VMs` work?

Really appreciate your taking the time for a thorough reply. Time is valuable and I want to thank everyone for trying to help me with this PR.

For the last question:
```
Casks/anka-virtualization.rb:11:54: C: [Corrected] Description shouldn't contain the platform.
  desc "Anka is a CLI tool for managing and creating mac VMs"
                                                     ^^^
```

2020-09-17 16:49 UTC, NorseGaud commented
Ok, I believe the current desc for each of these files is as short and clear as possible. It passes too. I ran fix on each file too.

2020-09-17 16:59 UTC, vitorgalvao requested changes

2020-09-17 16:59 UTC, vitorgalvao commented on Casks/anka-virtualization.rb
> +  desc "Anka is a CLI tool for managing and creating macintosh VMs"
`CLI tool for managing and creating macintosh VMs`.

2020-09-17 16:59 UTC, vitorgalvao commented on Casks/anka-build-cloud-registry.rb
> +  desc "The Anka Build Cloud Registry stores Anka's macintosh VMs in a central location"
`Stores Anka’s macintosh VMs in a central location`.

2020-09-17 16:59 UTC, vitorgalvao commented on Casks/anka-build-cloud-controller-and-registry.rb
> +  desc "The Anka Build Cloud includes a management GUI/API and macintosh VM registry"
This one you’ll probably make one better than me (just removing `The Anka Build Cloud` is weird). Essentially, the software’s name shouldn’t be part of the description (`audit` or `style` were supposed to catch that).

2020-09-17 16:59 UTC, vitorgalvao commented on Casks/anka-build-cloud-controller-and-registry.rb
> +  zap trash: [
When there’s only one element on the array, make it a string instead (we support that).

2020-09-17 17:55 UTC, reitermarkus commented on Casks/anka-build-cloud-controller-and-registry.rb
> +  desc "The Anka Build Cloud includes a management GUI/API and macintosh VM registry"
> `audit` or `style` were supposed to catch that

This is only part of the name, so not really that easy to detect without false positives.

2020-09-17 20:25 UTC, vitorgalvao approved these changes, later dismissed

2020-09-17 20:27 UTC, vitorgalvao commented
Thank you for the good (and fast!) work, @NorseGaud. I’m happy with it as it is. Will let someone else approve, so it’s not merged only by my agreement (someone else may have a note still).

2020-09-17 22:05 UTC, miccal commented on Casks/anka-build-cloud-controller-and-registry.rb
> +    executable: "/Library/Application\ Support/Veertu/Anka/tools/controller/uninstall.sh",
You do not need to escape the spaces here -- please remove the `\`'s.

2020-09-17 22:06 UTC, NorseGaud commented on Casks/anka-build-cloud-controller-and-registry.rb
> +    executable: "/Library/Application\ Support/Veertu/Anka/tools/controller/uninstall.sh",
Good catch, thanks

2020-09-17 23:19 UTC, reitermarkus commented on Casks/anka-build-cloud-controller-and-registry.rb
> +  desc "VM management GUI/API with macintosh VM registry"
@Homebrew/cask, are we confident we can't come up with a reworded version of this? If not, I'd rather allow the term “macOS virtual machine” than this “macintosh VM” workaround.

2020-09-18 00:21 UTC, vitorgalvao commented on Casks/anka-build-cloud-controller-and-registry.rb
> +  desc "VM management GUI/API with macintosh VM registry"
> are we confident we can't come up with a reworded version of this?

* Apple desktop OS virtual machines (joking).
* Catalina-and-later virtual machines (replacing “Catalina” with whatever the lowest version this runs on is).

2020-09-18 16:10 UTC, NorseGaud commented on Casks/anka-build-cloud-controller-and-registry.rb
> +  desc "VM management GUI/API with macintosh VM registry"
@reitermarkus I would love for you to allow "macOS VM"

Let me know and I can make the necessary changes

2020-09-19 04:35 UTC, reitermarkus commented on Casks/anka-build-cloud-controller-and-registry.rb
> +  desc "VM management GUI/API with macintosh VM registry"
You can reword this with “macos virtual machine” now.

2020-09-19 16:05 UTC, reitermarkus commented on Casks/anka-build-cloud-controller-and-registry.rb
> +  desc "MacOS virtual machine management GUI/API and registry"
macOS

2020-09-19 16:12 UTC, NorseGaud commented on Casks/anka-build-cloud-controller-and-registry.rb
> +  desc "MacOS virtual machine management GUI/API and registry"
This seems a little strict, but ok.

2020-09-19 16:27 UTC, reitermarkus commented
Any idea why the uninstall script for `anka-build-cloud-controller-and-registry` is failing?

2020-09-19 16:27 UTC, NorseGaud commented
Strange... The uninstall script is throwing a bad exit code... I'm looking into it now. We can put this PR on hold for a few days since it's the weekend here.

2020-09-19 16:27 UTC, reitermarkus commented
You can also split this into a separate PR so we can merge the other ones.

2020-09-21 16:50 UTC, reitermarkus approved these changes

2020-09-21 16:51 UTC, merged

2020-09-21 16:51 UTC, reitermarkus commented
Thanks, @NorseGaud!