Add Multi.app v2.0.7
Homebrew/homebrew-cask pull request #89334
Opened 2020-09-15 19:58 UTC by karbassi

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [ ] `brew cask audit --download {{cask_file}}` is error-free.
- [ ] `brew cask style --fix {{cask_file}}` reports no offenses.
- [ ] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [ ] `brew cask audit --new-cask {{cask_file}}` worked successfully.
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).

2020-09-18 23:47 UTC, vitorgalvao requested changes

2020-09-18 23:47 UTC, vitorgalvao commented on Casks/multi.rb
> +  app "Multi.app"
Please add a [`zap`](https://github.com/homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/zap.md).

2020-09-18 23:47 UTC, vitorgalvao requested changes

2020-09-18 23:47 UTC, vitorgalvao commented on Casks/multi.rb
> +  desc "Create a custom, lightweight app from a group of websites"
```suggestion
  desc "Create apps from groups of websites"
```

2020-09-21 13:49 UTC, karbassi commented on Casks/multi.rb
> +  desc "Create a custom, lightweight app from a group of websites"
I took the description from the developers' GitHub. Should we write our own? I'm fine either way.

2020-09-21 17:18 UTC, vitorgalvao commented on Casks/multi.rb
> +  desc "Create a custom, lightweight app from a group of websites"
> I took the description from the developers' GitHub. Should we write our own?

Developer’s own descriptions tend to be full of marketing fluff and buzzwords. We want to describe want the app does, not be a promotional tool.

2020-09-21 21:09 UTC, karbassi commented on Casks/multi.rb
> +  app "Multi.app"
@vitorgalvao there is nothing to `zap` or `uninstall` other than `Multi.app` app. Should I add an empty `zap`?

2020-09-21 22:34 UTC, vitorgalvao approved these changes

2020-09-21 22:34 UTC, merged

2020-09-21 23:17 UTC, reitermarkus commented on Casks/multi.rb
> +  app "Multi.app"
Does it not store any preferences or any other user-generated files?