Add Nova 1.0
Homebrew/homebrew-cask pull request #89421
Opened 2020-09-16 19:25 UTC by hugo

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] `brew cask audit --new-cask {{cask_file}}` worked successfully.
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).

2020-09-17 23:11 UTC, reitermarkus requested changes

2020-09-17 23:11 UTC, reitermarkus commented on Casks/nova.rb
> +  desc "Native code editor, from Panic"
Add the vendor to the name instead.

2020-09-17 23:11 UTC, reitermarkus commented on Casks/nova.rb
> +    "/usr/local/bin/nova",
Add this as a `binary`.

2020-09-18 05:42 UTC, hugo commented on Casks/nova.rb
> +    "/usr/local/bin/nova",
I don’t know what this means. It would have been helpful if you pointed to documentation that described what you are asking for.

2020-09-18 05:45 UTC, hugo commented on Casks/nova.rb
> +  desc "Native code editor, from Panic"
I don’t see any guidance or documentation about this. If you want the change, please make it yourself. Otherwise, you are welcome to close the PR.

2020-09-18 14:44 UTC, reitermarkus commented on Casks/nova.rb
> +  desc "Native code editor, from Panic"
> I don’t see any guidance or documentation about this.

You're right, there wasn't much at the time you submitted this. We have since added some examples here: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/desc.md

2020-09-18 14:48 UTC, reitermarkus commented on Casks/nova.rb
> +    "/usr/local/bin/nova",
Take a look at https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/binary.md.

2020-09-18 15:43 UTC, hugo commented on Casks/nova.rb
> +    "/usr/local/bin/nova",
I'm not sure I understand from that document why this stanza would be appropriate here. This binary is installed optionally via the Nova UI. There isn't a guarantee, as far as I know, of where the source file will reside. Arguably it's also not guaranteed that it will be copied to `/usr/local/bin/nova` and so we might be deleting the wrong binary inadvertently... I'm not sure what the best approach is here honestly.

2020-09-18 15:48 UTC, reitermarkus commented on Casks/nova.rb
> +    "/usr/local/bin/nova",
Well, it has to be copied from within the `.app` bundle, so we might as well link it ourselves, which also avoids deleting a wrong binary if one is already present and the manual installation step using the GUI.

2020-09-18 15:54 UTC, hugo commented on Casks/nova.rb
> +    "/usr/local/bin/nova",
Would I be right to expect that the `audit` command would catch if the source binary moved location or was renamed?

2020-09-18 15:59 UTC, hugo commented on Casks/nova.rb
> +  desc "Native code editor, from Panic"
Thanks for the link, I've made the recommende change.

2020-09-18 23:44 UTC, vitorgalvao approved these changes

2020-09-19 02:56 UTC, reitermarkus approved these changes

2020-09-19 03:05 UTC, merged