Add JetBrains Space 2020.1.8
Homebrew/homebrew-cask pull request #89474
Opened 2020-09-17 16:24 UTC by tiulpin

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] `brew cask audit --new-cask {{cask_file}}` worked successfully.
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).

2020-09-17 18:19 UTC, reitermarkus requested changes

2020-09-17 18:19 UTC, reitermarkus commented on Casks/jetbrains-space.rb
> +  desc "The integrated team environment"
This sounds more like a slogan than a description. I don't know what this is just from reading this.

2020-09-17 18:20 UTC, tiulpin commented on Casks/jetbrains-space.rb
> +  desc "The integrated team environment"
OK, I'll remove the description then. Will it be OK?

2020-09-17 18:59 UTC, tiulpin commented on Casks/jetbrains-space.rb
> +  desc "The integrated team environment"
Sorry, the description is needed, will try to add it ASAP

2020-09-17 19:02 UTC, tiulpin commented
Some casks (e.g. https://github.com/Homebrew/homebrew-cask/blob/master/Casks/jira-client.rb) don't have descriptions. It's difficult for me to write the good description in one line for that cask. Is it OK to add package without a description?

2020-09-17 19:28 UTC, reitermarkus commented
It's required for new casks and encouraged for existing ones so we eventually have descriptions for all casks.

2020-09-17 19:32 UTC, tiulpin commented
OK, added the most correct description I could think of.

2020-09-18 05:01 UTC, tiulpin commented
@reitermarkus thank you for the edit! Can this PR be accepted now?

2020-09-18 15:08 UTC, reitermarkus approved these changes

2020-09-18 16:07 UTC, merged