Add Home Assistant.app v2020.7,1
Homebrew/homebrew-cask pull request #89544
Opened 2020-09-18 22:47 UTC by ngdio

Cask for the Home Assistant companion app.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or **[documented exception]**(https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] `brew cask audit --new-cask {{cask_file}}` worked successfully.
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).

2020-09-18 23:42 UTC, vitorgalvao requested changes

2020-09-18 23:42 UTC, vitorgalvao commented on Casks/home-assistant.rb
> +  # github.com was verified as official when first introduced to the cask
```suggestion
  # github.com/home-assistant/iOS/ was verified as official when first introduced to the cask
```

2020-09-18 23:42 UTC, vitorgalvao commented on Casks/home-assistant.rb
> +  app "Home Assistant.app"
Please add a [`zap`](https://github.com/homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/zap.md).

2020-09-19 00:33 UTC, vitorgalvao approved these changes, later dismissed

2020-09-19 09:10 UTC, vitorgalvao approved these changes

2020-09-19 10:05 UTC, merged

2020-09-19 13:42 UTC, mweinelt commented
This creates a mixup on repology, as this is not home-assistant but home-assistant companion.

https://repology.org/project/home-assistant/versions

Can you maybe rename this cask?

2020-09-19 14:42 UTC, vitorgalvao commented
> Can you maybe rename this cask?

Not really something we want to do. We follow a strict token reference and by changing the casks name to be convenient to someone else it would be less convenient for us.

If you get upstream to change the app bundle’s name, the cask name will follow.