Add Eshelper 3.9.10, 2020-08-19
Homebrew/homebrew-cask pull request #89572
Opened 2020-09-20 05:40 UTC by integzz

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] `brew cask audit --new-cask {{cask_file}}` worked successfully.
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).

2020-09-20 15:37 UTC, miccal commented
For me clicking the "download now" link on the `homepage` just re-loads the `homepage` -- how can one find the `url` you provided?

2020-09-20 15:49 UTC, integzz commented
> For me clicking the "download now" link on the `homepage` just re-loads the `homepage` -- how can one find the `url` you provided?

Hi, I know the circumstances that you describe. I guess it is a bug of the official website. If you try to click more times, you will be redirected to `https://www.eudic.net/v4/es/app/download`.

In the script, the `url` should be `https://static.frdic.com/pkg/ehmac.dmg?v=2020-08-20`, and this will redirect to the download link.

2020-09-21 01:35 UTC, miccal commented
> > For me clicking the "download now" link on the `homepage` just re-loads the `homepage` -- how can one find the `url` you provided?
> 
> Hi, I know the circumstances that you describe. I guess it is a bug of the official website. If you try to click more times, you will be redirected to `https://www.eudic.net/v4/es/app/download`.

In that case please change the `homepage` to `https://www.eudic.net/v4/es/app/download`.

2020-09-21 01:39 UTC, miccal commented on Casks/eshelper.rb
> +  desc "Spanish Learning Helper"
```suggestion
  desc "Spanish dictionary"
```

2020-09-21 01:39 UTC, miccal commented on Casks/eshelper.rb
> +  name "Eshelper"
```suggestion
  name "Spanish Assistant"
```

2020-09-21 01:39 UTC, miccal commented on Casks/eshelper.rb
> +  app "Eudic_es.app"
Please re-name this Cask to `eudic-es` to follow the [token reference.](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md)

2020-09-21 03:52 UTC, integzz commented on Casks/eshelper.rb
> +  name "Eshelper"
This cask is a variant of the accepted casks [Frhelper](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/frhelper.rb) and [Eudic](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/eudic.rb). For ones who are familiar with this series of applications, `Eshelper` is not hard to understand.
For the consistency of these casks, I prefer to keep this name.

2020-09-21 03:55 UTC, integzz commented on Casks/eshelper.rb
> +  app "Eudic_es.app"
I do not like this token name, either. However, I can not accept this suggestion, because if I change the `app` value, brew will not be able to locate the app.

<img width="774" alt="brew" src="https://user-images.githubusercontent.com/46377665/93731794-2db19100-fc01-11ea-8bb8-f2eb766136b7.png">

2020-09-21 17:38 UTC, vitorgalvao requested changes, later dismissed

2020-09-21 17:38 UTC, vitorgalvao commented on Casks/eshelper.rb
> +  app "Eudic_es.app"
> if I change the `app` value, Homebrew will not be able to locate the App source.

@miccal isn’t referring to changing this line, but the first one *because of this one*. So instead of `cask "eshelper" do`, make it `cask "eudic-es" do`.

2020-09-21 17:51 UTC, integzz commented
Do I have to replace `cask "eshelper" do` with `cask "eudic-es" do`? Honestly, I prefer keeping it consistent with the accepted cask [frhelper](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/frhelper.rb), because they are products of the same company, the suggested change may confuse the users.

2020-09-21 17:54 UTC, vitorgalvao commented
> Do I have to replace `cask "eshelper" do` with `cask "eudic-es" do`?

Yes. It needs to follow the [token reference](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md) also linked by @miccal.

> Honestly, I prefer keeping it consistent with the accepted cask [frhelper](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/frhelper.rb),

And to keep it consistent, you need to rename it. That cask is consistent with the token reference. Cask naming isn’t a matter of preference, it’s all about consistency.

> because they are products of the same company, the suggested change may confuse the users.

What will confuse users is the cask being inconsistently named, especially if we end up having duplicates because the reference wasn’t followed.

2020-09-21 17:57 UTC, vitorgalvao commented on Casks/eshelper.rb
> +  name "Eshelper"
Specifically for the `name`, I’m fine with keeping `Eshelper`. We can have both.

2020-09-22 00:27 UTC, integzz commented
Okay, I have revised the manuscript. I just realized it is the bad of the company.

2020-09-22 00:55 UTC, miccal commented
> Okay, I have revised the manuscript. I just realized it is the bad of the company.
> 
> However, I got this, it seems that I have to rename the filename and commit another PR. Is there any compromising solution? Please help. @vitorgalvao
> 
> ![image](https://user-images.githubusercontent.com/46377665/93834601-06190200-fcaf-11ea-8a7e-2d95e61ebb22.png)

That is because the file name must match the Cask name -- I have now re-named the file from `eshelper.rb` to `eudic-es.rb` to match the `cask "eudic-es" do` bit.

2020-09-22 01:02 UTC, integzz commented
Thank you @miccal .

2020-09-22 22:18 UTC, miccal approved these changes

2020-09-22 23:05 UTC, merged