Add cernbox.app v2.5.4.2623
Homebrew/homebrew-cask pull request #89575
Opened 2020-09-20 11:11 UTC by adavidzh

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) ~~or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).~~

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] `brew cask audit --new-cask {{cask_file}}` worked successfully.
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).

Please have a look at the uninstall section; I am not completely sure it is the best it can be.

2020-09-20 15:53 UTC, miccal requested changes

2020-09-20 15:53 UTC, miccal commented on Casks/cernbox.rb
> +  desc "Acccess to cloud storage for users with a regular CERN computing account"
```suggestion
  desc "Cloud storage for CERN users"
```

2020-09-20 15:53 UTC, miccal commented on Casks/cernbox.rb
> +  uninstall signal:     [["TERM", "ch.cern.cernbox"]],
The `.pkg` runs a preinstall script `cernbox-2.5.4.2623.pkg/CERNBox.pkg/Scripts/preinstall`, the contents of which is simply:
```
#!/bin/sh

# kill the old version. see issue #2044
killall cernbox

exit 0
```
which suggests why a regular `uninstall quit:` failed.

2020-09-20 15:53 UTC, miccal commented on Casks/cernbox.rb
> +  url "https://cernbox.cern.ch/cernbox/doc/MacOSX/cernbox-#{version}.pkg"
Please add the following `appcast`:
```
appcast "https://cernbox.web.cern.ch/cernbox/downloads/"
```

2020-09-20 17:58 UTC, adavidzh commented on Casks/cernbox.rb
> +  url "https://cernbox.cern.ch/cernbox/doc/MacOSX/cernbox-#{version}.pkg"
Added in 5882309f1a1d05ace5e7937c9770a599c67bf025

2020-09-20 17:59 UTC, adavidzh commented
While adding the `appcast` stanza I have found that there are also other versions, including a `latest` link at [this URL](https://cernbox.cern.ch/cernbox/doc/MacOSX/). Could that URL be put to good use?

2020-09-21 01:41 UTC, miccal commented
> While adding the `appcast` stanza I have found that there are also other versions, including a `latest` link at [this URL](https://cernbox.cern.ch/cernbox/doc/MacOSX/). Could that URL be put to good use?

Yes it could -- please change the  `appcast` to:
```
appcast "https://cernbox.cern.ch/cernbox/doc/MacOSX/latest.link"
```

2020-09-21 01:45 UTC, miccal commented
> While adding the `appcast` stanza I have found that there are also other versions, including a `latest` link at [this URL](https://cernbox.cern.ch/cernbox/doc/MacOSX/). Could that URL be put to good use?

That link seems to list pre-releases, and the `latest` link has not been updated since 2015, so I do not think so.

2020-09-21 01:48 UTC, miccal approved these changes

2020-09-21 01:48 UTC, miccal commented
Thank you @adavidzh.

2020-09-21 02:06 UTC, merged

2020-09-21 03:13 UTC, miccal commented
@reitermarkus and @vitorgalvao is there a way I can approve something without the Bot auto-merging?

2020-09-21 18:04 UTC, vitorgalvao commented
> is there a way I can approve something without the Bot auto-merging?

Nope (I think). I agree there are certain situations when it’s inconvenient, but to disable it we’d lose the situations where it is convenient.

2020-09-21 18:08 UTC, reitermarkus commented
You can add the `do not merge` label.

2020-09-21 18:09 UTC, reitermarkus commented
We an also make the `awaiting` labels behave that way.

2020-09-21 18:10 UTC, vitorgalvao commented
> You can add the `do not merge` label.

Hadn’t thought of that. Nice thinking.

> We can also make the `awaiting` labels behave that way.

Just `awaiting-maintainer-feedback` should do it, I’d say.