prowritingaid: update must_contain, add desc
Homebrew/homebrew-cask pull request #90157
Opened 2020-10-01 00:32 UTC by miccal

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [X] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

2020-10-01 03:52 UTC, reitermarkus requested changes

2020-10-01 03:52 UTC, reitermarkus commented on Casks/prowritingaid.rb
> +          must_contain: "GMT"
How is that helpful?

2020-10-01 04:00 UTC, miccal commented on Casks/prowritingaid.rb
> +          must_contain: "GMT"
[See the comment here](https://github.com/Homebrew/homebrew-cask/pull/90018#issuecomment-700867090) for more background.

It was noticed that having `""` or `" "` was not working.

2020-10-01 04:36 UTC, reitermarkus commented on Casks/prowritingaid.rb
> +          must_contain: "GMT"
This is beginning to look very workaround-y. I'd rather this functionality be implemented in `brew cask audit`.

2020-10-01 04:40 UTC, miccal commented on Casks/prowritingaid.rb
> +          must_contain: "GMT"
I do not have much knowledge of the ML update system, so I will leave it to @ran-dall and @core-code to explain.

However, I think that if _no other_ suitable `appcast` can be found, then it does no harm to have _something_, no?

2020-10-01 05:06 UTC, reitermarkus commented on Casks/prowritingaid.rb
> +          must_contain: "GMT"
Sure it does no harm to have *something*, but it would be better to have something *official*.

2020-10-01 10:06 UTC, core-code commented on Casks/prowritingaid.rb
> +          must_contain: "GMT"
feel free to find something better :) for some casks the only way to detect updates is to look at the file itself. this is also similar to having a checksum file in the appcast, which is already done for a handful.

2020-10-01 10:08 UTC, core-code commented on Casks/prowritingaid.rb
> +          must_contain: "GMT"
also, looking at the downloaded file from the homepage kind-of is official, no? the appcast will only change if they modify the official download.

2020-10-01 18:48 UTC, reitermarkus commented on Casks/prowritingaid.rb
> +          must_contain: "GMT"
> looking at the downloaded file from the homepage kind-of is official, no?

It's not the homepage itself I am talking about. I am talking about the various CGI scripts which are living on your server instead of being incorporated into `brew`. There's currently no official way to do anything useful with just the file size/modified time unless you keep track of these yourself with some custom tool or script. Then again, there's also no official tool to do anything useful with the appcast itself either … so I guess my point is moot until `livecheck` works for casks.

2020-10-01 20:05 UTC, core-code commented on Casks/prowritingaid.rb
> +          must_contain: "GMT"
> I am talking about the various CGI scripts which are living on your server instead of being incorporated into brew.

i did offer to provide (and pay for) a server to host these and other stuff for HBC with full access for HBC member(s). i even offered to buy a suitable domain name. the response was that there is no interest. i am not sure it would have been possible to offer anything more than that.

> There's currently no official way to do anything useful with just the file size/modified time unless you keep track of these yourself with some custom tool or script. 

indeed. we obviously check each and every appcast every day, but publish only the changes

http://macupdater.net/cask-repair/

publishing the contents of each appcast every day could become expensive since it is around 60MB per day

> Then again, there's also no official tool to do anything useful with the appcast itself either

yes, everyone is free to check appcasts himself whether they refer to our server or any other server. no real distinction here.

2020-10-01 20:58 UTC, reitermarkus commented on Casks/prowritingaid.rb
> +          must_contain: "GMT"
> the response was that there is no interest

I think there is no interest because this doesn't need to exist on a server at all. The same checks can be implemented without having a server running by just doing what the CGI scripts are doing locally.

2020-10-01 21:00 UTC, core-code commented on Casks/prowritingaid.rb
> +          must_contain: "GMT"
sure, and i've advocated the very same thing in the past.

but who will implement it?

2020-10-01 21:03 UTC, core-code commented on Casks/prowritingaid.rb
> +          must_contain: "GMT"
if there is ever work in that direction, i think the first step is disentangling the dual use of the 'appcast' stanza. it is used 1.) to detect new updates and 2.) to find out which updates are valid and can be automerged

those do sometimes overlap, but not always.

2020-10-02 08:55 UTC, core-code commented
we could just omit the 'must_contain' stanza.  since the version number is not contained in the appcast, we cannot automatically reject bad PRs. it may be better if a maintainer verifies upcoming PRs anyway.

2020-10-05 05:50 UTC, miccal commented
/rebase

2020-10-05 09:46 UTC, core-code commented
i don't get it. CI fails with appcast error despite the 'ci-skip-appcast' label

2020-10-05 21:41 UTC, miccal commented
/rebase

2020-10-06 08:46 UTC, core-code approved these changes

2020-10-06 12:12 UTC, reitermarkus approved these changes

2020-10-06 13:06 UTC, merged