Add Modern CSV.app v1.3.
Homebrew/homebrew-cask pull request #90840
Opened 2020-10-14 13:44 UTC by evanemm

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [ x] `brew cask audit --download {{cask_file}}` is error-free.
- [ x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x ] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [ x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, **if adding a new cask**:

- [ x] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x ] `brew cask audit --new-cask {{cask_file}}` worked successfully.
- [ x] `brew cask install {{cask_file}}` worked successfully.
- [ x] `brew cask uninstall {{cask_file}}` worked successfully.
- [ x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x ] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).

2020-10-14 17:56 UTC, vitorgalvao requested changes

2020-10-14 17:56 UTC, vitorgalvao commented on Casks/moderncsv.rb
> +cask "moderncsv" do
Does not follow [token reference](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md). Needs to be `modern-csv`.

2020-10-14 17:56 UTC, vitorgalvao commented on Casks/moderncsv.rb
> +  url "https://www.moderncsv.com/release/ModernCSV-Mac-v1.3.dmg"
```suggestion
  url "https://www.moderncsv.com/release/ModernCSV-Mac-v#{version}.dmg"
```

2020-10-14 17:56 UTC, vitorgalvao commented on Casks/moderncsv.rb
> +  url "https://www.moderncsv.com/release/ModernCSV-Mac-v1.3.dmg"
Please add an [`appcast`](https://github.com/homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/appcast.md).

2020-10-14 17:56 UTC, vitorgalvao commented on Casks/moderncsv.rb
> +  app "Modern CSV.app"
Please add a [`zap`](https://github.com/homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/zap.md).

2020-10-15 11:12 UTC, evanemm commented
My bad. Just fixed.

2020-10-15 12:21 UTC, reitermarkus approved these changes

2020-10-15 13:09 UTC, vitorgalvao approved these changes

2020-10-15 13:09 UTC, merged