Add Messenger desktop latest
Homebrew/homebrew-cask pull request #90957
Opened 2020-10-16 08:50 UTC by Baltoli

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [ ] `brew cask style --fix {{cask_file}}` reports no offenses.
    - Gem installs for brew style seem to be broken on Catalina somehow - happy to fix any glaring issues, I just can't manage to get the style checker to run myself. 
- [x] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] `brew cask audit --new-cask {{cask_file}}` worked successfully.
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
    - Previous PR was closed as the author couldn't find the URL - I've got a non-timestamped link for the latest version in this PR.
- [x] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).

2020-10-16 15:24 UTC, vitorgalvao requested changes

2020-10-16 15:24 UTC, vitorgalvao commented on Casks/messenger.rb
> +  app "Messenger.app"
Please add a [`zap`](https://github.com/homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/zap.md).

2020-10-16 15:34 UTC, vitorgalvao approved these changes, later dismissed

2020-10-16 15:41 UTC, vitorgalvao commented
/rebase

2020-10-16 15:41 UTC, vitorgalvao approved these changes, later dismissed

2020-10-16 23:56 UTC, miccal commented
Not sure what is going on with the `appcast` -- in a browser the `.yml` file is downloaded, by via `curl`:
```
|-> curl https://www.facebook.com/messenger/desktop/update/latest-mac.yml
version: 73.2.121
releaseDate: '2020-10-13T06:07:24-07:00'
path: 'https://www.facebook.com/messenger/desktop/update/249985498.zip/'
sha512: 7c8ba308188ff15a03314593bec863ba45c5b7d15f17e4014a1d7d63a54c11a8a3eb2bec0ca36c19ff62b07ed4aa5cda82aef94c41746afff78cd2da70b51c2d
```

2020-10-16 23:59 UTC, vitorgalvao commented
`must_contain: version.before_comma` is never needed, because the appcast check always does that (if it’s failing because of that now, there’s a bug that affects a lot more casks.

2020-10-17 00:00 UTC, vitorgalvao approved these changes, later dismissed

2020-10-17 00:31 UTC, vitorgalvao approved these changes, later dismissed

2020-10-17 03:40 UTC, miccal commented
The `appcast` may not be useful here:
```
|-> curl -sLI https://www.facebook.com/messenger/desktop/update/latest-mac.yml
HTTP/1.1 200 OK
Vary: Accept-Encoding
Pragma: no-cache
Cache-Control: private, no-cache, no-store, must-revalidate
Expires: Sat, 01 Jan 2000 00:00:00 GMT
Strict-Transport-Security: max-age=15552000; preload
Content-Type: application/octet-stream
X-Content-Type-Options: nosniff
X-XSS-Protection: 0
X-Frame-Options: SAMEORIGIN
X-FB-Debug: GSWdL2/66uuv/jOe0jtfZgiNPNR03a5sQ6Sh5eJHA0/i7+6NlqLq6NiKhpTvIIopFlZGhEszEyM3ond2tpfr5w==
Date: Sat, 17 Oct 2020 03:37:37 GMT
Transfer-Encoding: chunked
Alt-Svc: h3-29=":443"; ma=3600,h3-27=":443"; ma=3600
Connection: keep-alive
```
&nbsp;
In particular note the line:
```
Cache-Control: private, no-cache, no-store, must-revalidate
```
&nbsp;
@core-code can you think of a way to utilise this `appcast`?

2020-10-17 12:50 UTC, core-code commented
> must_contain: version.before_comma is never needed

for some reason other casks have it too:` bluestacks, get-iplayer-automator qiyimedia qtvlm`

2020-10-17 12:51 UTC, core-code commented
> @core-code can you think of a way to utilise this appcast?

sorry, slow thinking today. i don't get the problem. it contains the version number just fine, no?

 ```
~ % curl https://www.facebook.com/messenger/desktop/update/latest-mac.yml
version: 73.2.121
[…]
```

2020-10-18 07:13 UTC, miccal commented
/rebase

2020-10-19 22:39 UTC, miccal approved these changes

2020-10-19 22:39 UTC, miccal commented
Thank you @Baltoli.

2020-10-19 23:06 UTC, merged