Add Binance.app
Homebrew/homebrew-cask pull request #91304
Opened 2020-10-23 13:03 UTC by pgreze

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] `brew cask audit --new-cask {{cask_file}}` worked successfully.
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).

2020-10-24 00:52 UTC, vitorgalvao requested changes

2020-10-24 00:52 UTC, vitorgalvao commented on Casks/binance.rb
> +  app "Binance.app"
Please add a [`zap`](https://github.com/homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/zap.md).

2020-10-26 17:37 UTC, core-code commented
i think there is an appcast here: https://ftp.binance.com/desktop/appcast.xml

2020-10-26 17:41 UTC, vitorgalvao commented
> i think there is an appcast here: https://ftp.binance.com/desktop/appcast.xml

It’s behind. It shows `1.2.23` but the unversioned URL on this PR downloads `1.5.0`.

2020-10-26 17:45 UTC, core-code commented
next try :->

`https://ftp.binance.com/electron-desktop/mac/production/latest-mac.yml`

2020-10-26 17:48 UTC, vitorgalvao requested changes

2020-10-26 17:48 UTC, vitorgalvao commented on Casks/binance.rb
> +  url "https://ftp.binance.com/electron-desktop/mac/production/binance.dmg"
Please add an [`appcast`](https://github.com/homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/appcast.md), the latest one pointed out by @core-code: https://ftp.binance.com/electron-desktop/mac/production/latest-mac.yml.

2020-10-26 17:48 UTC, vitorgalvao commented on Casks/binance.rb
> +  version :latest
Set to `1.5.0`.

2020-10-26 17:48 UTC, vitorgalvao commented on Casks/binance.rb
> +  sha256 :no_check
`sha256` also needs to be set. You can find what it is by running `shasum --algorithm 256` on the downloaded file.

2020-10-28 08:05 UTC, pgreze commented on Casks/binance.rb
> +  url "https://ftp.binance.com/electron-desktop/mac/production/binance.dmg"
@vitorgalvao thx for your help with @core-code , I could update the Cask with the appcast url (even if I have no idea what's appcast 😆 )

2020-10-28 08:06 UTC, pgreze commented on Casks/binance.rb
> +  version :latest
I chose the 1.5.1, version returned by my current latest-mac.yaml fetch

2020-10-28 08:10 UTC, pgreze commented on Casks/binance.rb
> +  sha256 :no_check
Thank you for giving me the command, the appcast was using sha512 which was misleading me...

2020-10-28 08:10 UTC, pgreze commented
@vitorgalvao let me reassign you now that I've updated the Cast file. My `reinstall` command worked as expected 👍

2020-10-28 21:01 UTC, vitorgalvao requested changes

2020-10-28 21:01 UTC, vitorgalvao commented on Casks/binance.rb
> +  app "Binance.app"
@pgreze Still missing the `zap`.

2020-10-29 01:45 UTC, pgreze commented on Casks/binance.rb
> +  app "Binance.app"
@vitorgalvao oh I missed this one.

I searched for created files by this app with "find . | grep -i binance" command and after an install + use of the app including a login, here are logs of the `zap` command:

```
$ brew cask zap binance
==> Implied "brew cask uninstall binance"
==> Backing App 'Binance.app' up to '/usr/local/Caskroom/binance/1.5.1/Binance.app'.
==> Removing App '/Applications/Binance.app'.
==> Dispatching zap stanza
==> Trashing files:
~/Library/Application Support/Binance
~/Library/Saved Application State/com.binance.BinanceDesktop.savedState
~/Library/Logs/Binance
==> Removing all staged versions of Cask 'binance'
```

2020-10-29 04:29 UTC, vitorgalvao requested changes

2020-10-29 04:29 UTC, vitorgalvao commented on Casks/binance.rb
> +               '~/Library/Application Support/Binance',
These don’t have the correct indentations and have the wrong quote type. `brew cask style --fix`, as in the template, should fix it.

2020-10-29 13:56 UTC, pgreze commented on Casks/binance.rb
> +               '~/Library/Application Support/Binance',
@vitorgalvao argh, I followed the [given dropbox.rb example](https://github.com/Homebrew/homebrew-cask/blob/31cd96cc0e00dab1bff74d622e32d816bafd1f6f/Casks/dropbox.rb#L17-L35) given in [this page](https://github.com/homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/zap.md) but I guess it's referring a commit before this styling change.

I just pushed a commit fixing the styling issue.

2020-10-29 14:01 UTC, pgreze commented on Casks/binance.rb
> +               '~/Library/Application Support/Binance',
https://github.com/Homebrew/homebrew-cask/pull/91671

2020-10-29 14:52 UTC, vitorgalvao approved these changes

2020-10-29 14:53 UTC, vitorgalvao commented
Looking good. Thank you.

2020-10-29 14:53 UTC, merged

2020-10-30 01:24 UTC, pgreze commented
@vitorgalvao thank you for your support, it was my first PR in this project for an app I'm not maintaining, so I really appreciated your support 🙏