Update Aptible to v0.16.8
Homebrew/homebrew-cask pull request #91344
Opened 2020-10-23 20:18 UTC by robertfairhead

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [X] `brew cask audit --download {{cask_file}}` is error-free.
- [X] `brew cask style --fix {{cask_file}}` reports no offenses.
- [X] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [X] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [ ] `brew cask audit --new-cask {{cask_file}}` worked successfully.
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).

2020-10-24 00:48 UTC, vitorgalvao requested changes

2020-10-24 00:48 UTC, vitorgalvao commented on Casks/aptible.rb
> +  desc "Command-line tool for Aptible Deploy"
There should be a hint of what “Aptible Deploy” is. As it stands, the description doesn’t clarify anything for people who don’t already know what the software is.

2020-10-26 13:40 UTC, robertfairhead commented on Casks/aptible.rb
> +  desc "Command-line tool for Aptible Deploy"
I added some additional context on what "Aptible Deploy" is to the description. Let me know me if any further context will be helpful there!

2020-10-26 15:42 UTC, vitorgalvao approved these changes

2020-10-26 15:42 UTC, merged