parallels: improve uninstall procedure
Homebrew/homebrew-cask pull request #91805
Opened 2020-10-31 04:53 UTC by emilazy

This allows the package to be cleanly uninstalled even while running, unloads the kexts, and removes a bunch of extra leftover files and other remnants I found.

Things I’m unsure about:
* I don’t know if all of these `uninstall` parameters are required or if some can be inferred automatically.
* I couldn’t get the files outside `$HOME` to be trashed, so they’re just `delete:`d currently.
* The `pkill`/`sed` scripts could probably use review.

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [ ] `brew cask audit --new-cask {{cask_file}}` worked successfully.
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).

2020-10-31 11:05 UTC, miccal commented on Casks/parallels.rb
> +    "/private/var/root/Library/Preferences/com.parallels.desktop.plist",
These files and folders in `/private` should not be removed by Cask.

2020-10-31 11:05 UTC, miccal commented on Casks/parallels.rb
> +    "/Library/Preferences/Parallels",
These three `/Library` entries are not user-specified files, so they belong in `uninstall delete`.

2020-10-31 11:05 UTC, miccal commented on Casks/parallels.rb
> +
Remove this blank line.

2020-10-31 18:27 UTC, emilazy commented on Casks/parallels.rb
> +    "/Library/Preferences/Parallels",
Surely `uninstall` shouldn’t destructively erase logs and preferences? There seem to be a lot of casks with `/Library/{Logs,DiagnosticReports}` paths and the like in `zap` stanzas; e.g. (from a quick `rg '[^~]/Library/Logs'` and verifying the stanza) `vmware-fusion`, `firefox`, `keybase`, `little-snitch`.

2020-10-31 18:28 UTC, emilazy commented on Casks/parallels.rb
> +    "/private/var/root/Library/Preferences/com.parallels.desktop.plist",
As with https://github.com/Homebrew/homebrew-cask/pull/91805#discussion_r515525079, these are just leftover cache and preference files, so `zap`? Is the problem just that they're not owned by the user? The uninstall procedure for Parallels already requires `sudo`, and there seem to be a few casks removing `/var/folders` paths already.

2020-11-02 00:31 UTC, emilazy commented on Casks/parallels.rb
> +
Rebased to remove the blank line and also the `/Users/Shared/Parallels` zap (since it's the storage location for actual VMs, a la `~/Parallels`, which probably shouldn't get erased); I could still use some elaboration on the other issues, per my comments.

2020-12-13 06:06 UTC, emilazy commented on Casks/parallels.rb
> +            delete:       [
The ordering here is sensitive; `com.parallels.kext.netbridge` has to be the first entry.

2020-12-25 16:35 UTC, vitorgalvao requested changes

2020-12-25 16:35 UTC, vitorgalvao commented on Casks/parallels.rb
> +            script:       {
`script` is for scripts, not commands. This should be in an `uninstall_postflight`.

2020-12-25 16:35 UTC, vitorgalvao commented on Casks/parallels.rb
> +  uninstall early_script: {
`script` is for scripts, not commands. This should be in an `uninstall_preflight`. Or better yet, if `quit` can’t do it maybe [`signal`](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/uninstall.md#uninstall-key-signal) might.

2021-01-19 03:09 UTC, emilazy commented on Casks/parallels.rb
> +  uninstall early_script: {
Moved these to the `uninstall_{pre,post}flight` blocks; I'm not sure `signal` would suffice here since they're just random executables inside `/Applications/Parallels Desktop.app/Contents/MacOS` spawned outside of the normal app flow?

2021-01-19 03:21 UTC, emilazy commented
Not sure I understand [the CI failure](https://github.com/Homebrew/homebrew-cask/runs/1725252527?check_suite_focus=true); shouldn’t the main application bundle get removed automatically?

2021-01-19 10:07 UTC, emilazy commented
I see; it’s because the `pkill` is failing. I’m not sure why, though, as I used `system_command` rather than `system_command!`.

2021-01-20 18:04 UTC, vitorgalvao commented on Casks/parallels.rb
> +    "/private/var/root/Library/Preferences/com.parallels.desktop.plist",
> and there seem to be a few casks removing `/var/folders` paths already.

We might want to rethink that as well. These should be deleted by the system.

2021-01-20 18:11 UTC, vitorgalvao commented on Casks/parallels.rb
> +                    args: ["-i", ".orig", "/#prl_hostonly/d", "/etc/hosts"],
Good thinking to delete these, but at the same time you’re creating another file. `.orig` isn’t descriptive when someone bumps into it later on.

More explicit solution: Make the extension `.before_cask_uninstall_parallels`; move the file somewhere else (like the Trash); warn the user this is going on.

2021-02-18 00:25 UTC, closed without merging