Add Pitch.app v1.2.2
Homebrew/homebrew-cask pull request #91875
Opened 2020-11-02 08:02 UTC by timrogers

This commit adds v1.2.2 of [Pitch][1]: "collaborative presentation software for modern teams".

The cask downloads a `.dmg` and extracts the `Pitch.app` file.

[1]: https://pitch.com

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [ ] `brew cask audit --download {{cask_file}}` is error-free.
- [ ] `brew cask style --fix {{cask_file}}` reports no offenses.
- [ ] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [ ] `brew cask audit --new-cask {{cask_file}}` worked successfully.
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).

2020-11-02 15:59 UTC, vitorgalvao requested changes

2020-11-02 15:59 UTC, vitorgalvao commented on Casks/pitch.rb
> +  app "Pitch.app"
Please add a [`zap`](https://github.com/homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/zap.md). See [`homebrew-createzap`](https://github.com/nrlquaker/homebrew-createzap) for an external project which can help.

2020-11-02 15:59 UTC, vitorgalvao commented on Casks/pitch.rb
> +  url "https://desktop-app-builds.pitch.com/Pitch-#{version}.dmg"
Please add an [`appcast`](https://github.com/homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/appcast.md): `https://desktop-app-builds.pitch.com/latest-mac.yml`.

2020-11-03 08:29 UTC, timrogers commented on Casks/pitch.rb
> +  url "https://desktop-app-builds.pitch.com/Pitch-#{version}.dmg"
Thanks! I looked for this but didn't spot the explanation page that showed you how to find it.

2020-11-03 08:31 UTC, timrogers commented
Thanks for the quick review @vitorgalvao - I've added the `appcast` and the `zap` and have amended the commit.

2020-11-03 17:53 UTC, vitorgalvao approved these changes

2020-11-03 17:53 UTC, merged