Add napari.app v0.4.2
Homebrew/homebrew-cask pull request #93839
Opened 2020-11-29 04:33 UTC by tlambert03

Please consider this new cask for napari, a fast multidimensional image viewer written in python:
https://github.com/napari/napari
https://napari.org

Verified:

- [x] `brew audit --cask {{cask_file}}` is error-free.
- [ ] `brew style --fix {{cask_file}}` reports no offenses.  
  _(I'm sorry, I was unable to run this, got "Failed to build gem native extension." ... )_
- [x] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions)

**I'm adding a new cask**:

- [x] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] `brew audit --new-cask {{cask_file}}` worked successfully.
- [x] `brew install --cask {{cask_file}}` worked successfully.
- [x] `brew uninstall --cask {{cask_file}}` worked successfully.
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).

2020-11-29 05:04 UTC, tlambert03 commented
one more note: I see that a `zap` is usually requested.  In this case, there are no settings/preferences saved by the app outside of the .app bundle (yet).  In the future, we plan to look for user-editable config files in `~/.config/napari/` ... but since these are both directly user-editable and program editable, I'm not sure that they fall under the [zap stanza purpose](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/zap.md#zap-stanza-purpose) ... but let me know if I should add it.

2020-11-29 16:28 UTC, vitorgalvao requested changes, later dismissed
Welcome. In the future please don’t untick the box that allows edits from maintainers. It makes our work considerably slower and harder with unnecessary back and forth.

2020-11-29 16:28 UTC, vitorgalvao commented on Casks/napari.rb
> +  desc "Fast, interactive, multi-dimensional image viewer for Python"
“Fast, interactive, multi-dimensional” is marketing fluff. Just `Image viewer for Python`.

2020-11-29 16:28 UTC, vitorgalvao commented on Casks/napari.rb
> +  depends_on macos: "<= :catalina"
Why? Will it ever support Big Sur?

2020-11-29 16:28 UTC, vitorgalvao commented on Casks/napari.rb
> +  # github.com/napari/napari was verified as official when first introduced to the cask
Need a trailing slash on `github.com/napari/napari`

2020-11-29 16:28 UTC, vitorgalvao commented on Casks/napari.rb
> +  app "napari.app"
Yes, please add the `zap`.

2020-11-29 18:06 UTC, tlambert03 commented on Casks/napari.rb
> +  desc "Fast, interactive, multi-dimensional image viewer for Python"
> Welcome. In the future please don’t untick the box that allows edits from maintainers. It makes our work considerably slower and harder with unnecessary back and forth.

Thanks for the review!  Definitely didn't untick that box... would be more than happy to have you edit it directly.  Not sure why it's disabled ... (maybe creating the PR view the `gh` cli?).  Sorry, I don't see it available on the right to re-enable either.

2020-11-29 18:08 UTC, tlambert03 commented on Casks/napari.rb
> +  depends_on macos: "<= :catalina"
Yep, probably the next patch release (0.4.3), napari itself _does_ support big sur, but the openGL dependencies require python 3.9, and one of our dependencies needs to release a patch update to support 3.9, so we are still shipping the bundle with py3.8 for now.  But will remove the Catalina pin as soon as we can reliably support it.

2020-11-29 18:08 UTC, vitorgalvao commented on Casks/napari.rb
> +  desc "Fast, interactive, multi-dimensional image viewer for Python"
> Not sure why it's disabled ... (maybe creating the PR view the `gh` cli?).

Probably that, yes.

> Sorry, I don't see it available on the right to re-enable either.

Don’t worry about it for now, if you can do the requested fixes.

2020-11-29 18:08 UTC, tlambert03 commented on Casks/napari.rb
> +  app "napari.app"
will do!

2020-11-29 18:09 UTC, vitorgalvao commented on Casks/napari.rb
> +  depends_on macos: "<= :catalina"
Sound good.

2020-11-29 18:10 UTC, tlambert03 commented on Casks/napari.rb
> +  desc "Fast, interactive, multi-dimensional image viewer for Python"
> “Fast, interactive, multi-dimensional” is marketing fluff.

absolutely, that was just the standard description from the app.  Mind if I leave in the "multi-dimensional" part?  that's kinda the main differentiating point of the app compared to standard image viewers.

2020-11-29 18:13 UTC, tlambert03 commented
changes made, thanks for your time.

2020-11-29 18:40 UTC, vitorgalvao commented
It’s failing the `style` check ([issues are pointed out](https://github.com/Homebrew/homebrew-cask/pull/93839/files)).

2020-11-29 21:50 UTC, tlambert03 commented
whoops.  fixed now, thanks

2020-11-30 06:30 UTC, miccal commented
Thank you for your contribution to `homebrew-cask` @tlambert03.

2020-11-30 06:30 UTC, miccal approved these changes

2020-11-30 06:31 UTC, merged