Test `livecheck`.
Homebrew/homebrew-cask pull request #95419
Opened 2020-12-14 01:39 UTC by reitermarkus

Depends on https://github.com/Homebrew/brew/pull/9529.

2020-12-14 16:15 UTC, vitorgalvao commented on Casks/8bitdo-ultimate-software.rb
> +  livecheck do
Can’t these simpler cases be on a single line, like `livecheck { url :appcast }`?

2020-12-14 18:02 UTC, reitermarkus commented on Casks/8bitdo-ultimate-software.rb
> +  livecheck do
https://github.com/Homebrew/brew/pull/9529#discussion_r541956544

2020-12-20 08:00 UTC, samford commented
I'm planning to go through the `livecheck` blocks here and bring them up to our existing standards, so please don't merge this until I have a chance to go through it (tomorrow).

Mainly, there are a number of regexes that need to be brought up to our existing standards. Also, since we've only recently introduced `strategy` blocks, I would like to review the usage here to make sure we're providing good examples early on.

It's very late over here and I'm going to bed but I'm planning to work through this PR tomorrow, as I don't want to hold you up too much. I do think it's important to address these issues now rather than later, as it's comparatively fast/easy to review/fix in this PR (rather than having to hunt down each individual `livecheck` block after it's merged). Besides that, addressing these issues here will prevent them from being perpetuated after merging (when folks inevitably copy and paste existing `livecheck` blocks to create new ones) and this saves us work down the road.

Thanks again for your patience 🙏

2020-12-21 15:53 UTC, samford commented
I ended up working on advancing/finishing/closing some Homebrew/brew livecheck PRs yesterday and didn't find the time to go through this.

I'm currently looking through these to identify which `livecheck` blocks need changes but, since they're already being actively merged, I'll wait until you've finished and create follow-up PRs for any changes.

2020-12-21 15:54 UTC, samford commented on Casks/8bitdo-ultimate-software.rb
> +  livecheck do
While the one-liner is succinct, we've standardized on always using a `do`-`end` block in homebrew/core. The reason for this is because it makes it easier to add additional method calls (e.g., `regex`, `strategy`, etc.) and allows for cleaner commit diffs. I think those benefits arguably outweigh the simplicity of a single-line approach, so I remain in favor of always using `do`-`end` for `livecheck` blocks.

2020-12-21 16:15 UTC, reitermarkus commented
@samford, so far I have only merged the `:sparkle` ones without any regex. Can you give an example of what “existing standards” a regex should follow?

2020-12-21 16:20 UTC, reitermarkus commented on Casks/8bitdo-ultimate-software.rb
> +  livecheck do
If anything, we should have 

```ruby
livecheck "https://example.com"
```

as a shortcut, but given that the `strategy` is not specified explicitly everywhere, we have at least two lines everywhere anyways.

2020-12-21 19:21 UTC, samford commented on Casks/8bitdo-ultimate-software.rb
> +  livecheck do
I've thought about adding more explicit `livecheck` blocks in formulae to specify the URL to use (instead of having livecheck guess) but adding a `livecheck` block that only contains the `url` has felt like overkill.

Though I'm not fond of the above one-line block format (e.g., `livecheck { url :cask_url }`), I could get behind the idea of an alternative method call format (e.g., `livecheck "https://example.com"` or `livecheck :cask_url`) as a shortcut for a `url`-only block.

2020-12-21 19:35 UTC, samford commented
> so far I have only merged the `:sparkle` ones without any regex.

I'm primarily interested in reviewing the `livecheck` blocks with a `regex` (bringing them up to existing guidelines) or a `strategy` block (understanding common usage and identifying if there's any room for improvement). I'm good with the `livecheck` blocks that simply use `header_match` and `sparkle` with no `strategy` block being merged but I would like to work through the others I mentioned.

> Can you give an example of what “existing standards” a regex should follow?

The current guidelines for regexes in `livecheck` blocks can be found in my draft docs PR: https://github.com/Homebrew/brew/blob/68f5b564468a21f67a8ed532aa86a5afa5dd8d00/docs/Brew-Livecheck.md#regex-guidelines [I haven't pushed my latest changes yet but the differences in that section are minor.]

These are the guidelines I created over the past year as I've worked to improve livecheck. Since we've only recently added cask support, some of the guidelines are geared toward a formula context. Part of the reason I've wanted to review this (before we really get into creating `livecheck` blocks for casks in earnest) is to understand the contextual differences and how they may impact the existing guidelines (and/or the creation of new ones).

The easiest way of explaining this is through examples, so I'll provide some brief commentary in my feedback for some of these. At the moment, I'm skimming these to identify which may need changes and then I'll start reviewing them.

2020-12-22 02:19 UTC, samford requested changes
I'm going to review this in phases to make it manageable. This first pass is for a few straightforward issues (functional or merely stylistic). The next pass will be to work on regexes.

2020-12-22 02:19 UTC, samford commented on Casks/hex-fiend.rb
> +    strategy :github_latest
```suggestion
    url :cask_url
    strategy :github_latest
```

`url` is required in a `livecheck` block.

2020-12-22 02:19 UTC, samford commented on Casks/odrive.rb
> +    # https://docs.odrive.com/docs/odrive-usage-guide#install-desktop-sync
```suggestion
  # From: https://docs.odrive.com/docs/odrive-usage-guide#install-desktop-sync
  livecheck do
```

I always put explanatory comments before the `livecheck` block, so it wouldn't hurt to maintain consistency here.

2020-12-22 02:19 UTC, samford commented on Casks/ifunbox.rb
> +
```suggestion
```

This cask already has the same `livecheck` block, so the added one here is a duplicate.

2020-12-24 22:54 UTC, samford requested changes
These suggested changes should bring these regexes more in line with the existing guidelines. I tried to only explain each category of change once, so I wouldn't have to repeat the same thing over and over. Past that, let me know if you have any questions/comments.

I know the holidays are upon us, so don't feel like there's a pressing need to address this.

Looking forward, I'm going to go through the existing `strategy` blocks to understand what's commonly done and if there's any room for improvement. From what I've seen in passing, there's at least one potential area for improvement that I'll be addressing in a forthcoming brew PR. I'll leave a comment to start a discussion once I get through them but it may not be until the weekend.

2020-12-24 22:54 UTC, samford commented on Casks/0-ad.rb
> +    regex(/0ad-(.*?)-osx64\.dmg/i)
```suggestion
    regex(/href=.*?0ad[._-]v?(.*?)-osx64\.dmg/i)
```

* Since we're matching a file on an HTML page, this restricts matching to an `href` attribute.
* Uses the generic `[._-]` between the software name and numeric version (this is something we commonly do with filename regexes).

Past that, this cask uses an alpha version, so I've left the capture group loose.

2020-12-24 22:54 UTC, samford commented on Casks/applepi-baker.rb
> +    regex(%r{/downloads/raspberrypi/ApplePi-Baker-v(.*?)\.dmg"}i)
```suggestion
    regex(/href=.*?ApplePi-Baker[._-]v?(\d+(?:\.\d+)+)\.dmg/i)
```

Besides previously mentioned changes:

* Use the standard regex for versions like `1.2`/`1.2.3`/`v1.2`/etc. (`v?(\d+(?:\.\d+)+)`).
* Omits the trailing `"` since it didn't seem technically necessary. However, when it's necessary to target the end of the attribute, we use `["' >]`.

2020-12-24 22:54 UTC, samford commented on Casks/araxis-merge.rb
> +    regex(/Araxis Merge\s+(\d+\.\d+)\s+for macOS/i)
```suggestion
    url "https://www.araxis.com/merge/download.en"
    regex(/href=.*?Merge[._-]?v?(\d+(?:\.\d+)+)-macOS\.dmg/i)
```

The Merge download page links to the disk image file, so it would arguably be better to check that.

The standard regex for versions like `1.2`/`1.2.3`/etc. works for `2020.5479`, so it wouldn't hurt to use it here. Standardizing on common regex components means that we can easily substitute them with a built-in regex snippet if/when we implement this in the future.

2020-12-24 22:54 UTC, samford commented on Casks/arduino.rb
> +    regex(/arduino-(\d+(?:\.\d+)*)-macosx\.zip/i)
```suggestion
    regex(/href=.*?arduino[._-]v?(\d+(?:\.\d+)+)-macosx\.zip/i)
```

2020-12-24 22:54 UTC, samford commented on Casks/bbedit.rb
> +    regex(%r{<key>SUFeedEntryShortVersionString</key>\s*<string>(\d+(?:\.\d+)+)</string>}i)
```suggestion
    regex(/BBEdit[._-]v?(\d+(?:\.\d+)+)\.dmg/i)
```

We generally prefer to identify versions from filenames when possible, as this also indicates that an available version is suitable to be used in the formula/cask.

2020-12-24 22:54 UTC, samford commented on Casks/boinc.rb
> +    regex(/boinc_(.*)_macOSX_universal\.zip/i)
```suggestion
    regex(%r{href=.*?/dl/boinc[._-]v?(\d+(?:\.\d+)+)_macOSX_universal\.zip}i)
```

With this version of the regex, it's necessary to include `/dl/` or else it will return a version like `berkeley.edu/dl/boinc_7.16.14`.

2020-12-24 22:54 UTC, samford commented on Casks/charles.rb
> +    regex(/\d+(?:\.\d+)*/)
```suggestion
    regex(/v?(\d+(?:\.\d+)+)/i)
```

We use a capture group around the version in regexes.

2020-12-24 22:54 UTC, samford commented on Casks/chromedriver.rb
> +    regex(/.*/)
```suggestion
    regex(/v?(\d+(?:\.\d+)+)/i)
```

Unless the looseness is necessary, we should bring this more in line with `charles`/`chromium`.

2020-12-24 22:54 UTC, samford commented on Casks/chromium.rb
> +    regex(/\d+(?:\.\d+)*/)
```suggestion
    regex(/v?(\d+(?:\.\d+)*)/i)
```

We use a capture group around the version in regexes.

2020-12-24 22:54 UTC, samford commented on Casks/cmake.rb
> +    regex(/cmake-(.*?)-Darwin-x86_64\.dmg/i)
```suggestion
    regex(/href=.*?cmake[._-]v?(\d+(?:\.\d+)+)-Darwin-x86_64\.dmg/i)
```

2020-12-24 22:54 UTC, samford commented on Casks/crystalmaker.rb
> +    regex(/<version number="(\d+(?:\.\d+)*)">/i)
```suggestion
    regex(/<version[^>]+?number=["']?v?(\d+(?:\.\d+)+)["']?[^>]*?>/i)
```

This would continue to match if the XML changes to include additional attributes in `version` elements before and/or after the `number` attribute.

It also works in situations where the attribute is enclosed by double quotes, single quotes, or no quotes at all. We'll likely never see anything other than double quotes in this particular source but I've seen all sorts of nonsense while working on livecheck, so I try not to assume.

2020-12-24 22:54 UTC, samford commented on Casks/daisydisk.rb
> +    regex(/Version (\d+(?:\.\d+)+)/i)
```suggestion
    regex(/>\s*?Version\s+?v?(\d+(?:\.\d+)+)\s*?</)
```

Anchoring this (using `>`/`<` at the start/end) will help to ensure we only match the heading text, instead of something in the description. For example, the original regex could run into a problem if the description contained something like, "Version 1.2.3 will be released in the future after more testing". If the latest version at the time was 1.2.2, then livecheck would return the nonexistent 1.2.3 version as newest.

This also loosens the regex with regard to whitespace.

2020-12-24 22:54 UTC, samford commented on Casks/dbeaver-enterprise.rb
> +    regex(%r{<number>(\d+(?:\.\d+)*)</number>}i)
```suggestion
    regex(%r{<number[^>]*?>v?(\d+(?:\.\d+)+)</number>}i)
```

Though this element doesn't have any attributes, it wouldn't hurt to defensively account for them (to prevent this from breaking if it happens).

2020-12-24 22:54 UTC, samford commented on Casks/filebot.rb
> +    regex(/FileBot (\d(?:\.\d+)*)/i)
```suggestion
    url "https://www.filebot.net/download.html"
    regex(/href=.*?FileBot[._-]v?(\d+(?:\.\d+)+)\.app\.t/i)
```

The XML file only links to the first-party download page, rather than the archive file used in the cask `url`. The first-party download page links to the `app.tar.xz` file, so it would be better to check that.

2020-12-24 22:54 UTC, samford commented on Casks/fluor.rb
> +    regex(/%20(\d+(?:\.\d+)*)\.dmg/i)
```suggestion
    regex(/href=.*?Fluor(?:%20|[._-])v?(\d+(?:\.\d+)+)\.dmg/i)
```

Among the usual changes, this matches the encoded space (`%20`) after the software name but also allows the usual delimiters (`[._-]`), in case it changes in the future.

2020-12-24 22:54 UTC, samford commented on Casks/hex-fiend.rb
> +    url "https://github.com/ridiculousfish/HexFiend/releases.atom"
```suggestion
    url :cask_url
```

We try to align the `livecheck` source with the `stable` URL in formulae, so we should aim to check as close to the `cask_url` as possible, too. There isn't any benefit to using the `.atom` URL here, since the `GithubLatest` strategy simply generates the `/releases/latest` URL from it (i.e., not checking the supplied URL directly).

2020-12-24 22:54 UTC, samford commented on Casks/keycue.rb
> +    regex(/Version.*?(\d+(?:\.\d+)*)/i)
```suggestion
    url "https://www.ergonis.com/products/keycue/history.html"
    regex(/<h\d>\s*?KeyCue\s+?v?(\d+(?:\.\d+)+)/i)
```

I worry that the looseness of the original regex could lead to it matching something other than what we intend. The latest version is 9.8 but if the page contained some text like "Version 10.0 is on the way!", livecheck would match that as well.

How do you feel about checking the history page (i.e., release information)?

2020-12-24 22:54 UTC, samford commented on Casks/livereload.rb
> +    regex(/LiveReload-(\d+(?:\.\d+)*)\.zip/i)
```suggestion
    regex(/href=.*?LiveReload[._-]v?(\d+(?:\.\d+)+)\.zip/i)
```

For what it's worth, the URL on this page is `https://s3.amazonaws.com/download.livereload.com/LiveReload-2.3.84.zip` but the cask URL would be `http://download.livereload.com/LiveReload-2.3.84.zip`. Should the cask `url` be updated to use the S3 URL?

2020-12-24 22:54 UTC, samford commented on Casks/nestopia.rb
> +    regex(/Nestopia v(\d+(?:\.\d+)*)/i)
```suggestion
    url :homepage
    regex(/>\s*?Nestopia\s+?v?(\d+(?:\.\d+)+)\s*?</i)
```

This URL is the same as the homepage, so it should use `:homepage` instead.

We have a [livecheck RuboCop](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/rubocops/livecheck.rb#L109-L116) that enforces uses of symbols for `livecheck` block `url`s that match one of the related URLs in the formula (e.g., `head`, `stable`, `homepage`). For casks, these URLs would be `appcast` (for now?), `cask_url`, and `homepage`.

Ideally, our `livecheck` RuboCops would apply to both casks and formulae (outside of cops that should only apply to one or the other) but I haven't looked into it to determine the best way to go about it. Ideally the code would be shared but, off the top of my head, I don't know if that's technically possible.

2020-12-24 22:54 UTC, samford commented on Casks/qsync-client.rb
> +    regex(/QNAPQsyncClientMac-(\d+(?:\.\d+)*)\.dmg/i)
```suggestion
    regex(/QNAPQsyncClientMac[._-]v?(\d+(?:\.\d+)+)\.dmg/i)
```

2020-12-24 22:54 UTC, samford commented on Casks/screenfocus.rb
> +    regex(/-(\d+(?:\.\d+)*)\.zip/i)
```suggestion
    regex(/href=.*?ScreenFocus[._-]v?(\d+(?:\.\d+)+)\.zip/i)
```

2020-12-24 22:54 UTC, samford commented on Casks/steermouse.rb
> +    regex(/SteerMouse(\d+(?:\.\d+)*)\.dmg/i)
```suggestion
    regex(/href=.*?SteerMouse[._-]?v?(\d+(?:\.\d+)+)\.dmg/i)
```

2020-12-24 22:54 UTC, samford commented on Casks/teamspeak-client.rb
> +    regex(/stable.*?(\d+(?:\.\d+)*)/i)
```suggestion
    regex(/stable.*?v?(\d+(?:\.\d+)+)/i)
```

2020-12-24 22:54 UTC, samford commented on Casks/thumbsup.rb
> +    regex(%r{<td>ThumbsUp</td>\s*<td>(\d+(?:\.\d+)+)</td>}i)
```suggestion
    url :homepage
    regex(%r{href=.*?/thumbsup/v?(\d+(?:\.\d+)+)/ThumbsUp\.app\.zip}i)
```

I'm not quite sure why the download page doesn't contain a link to the zip file when fetching the page with livecheck or `curl`. It appears in the source when fetching with a browser, even with JavaScript disabled. I tried setting a user agent string in `curl` and it still doesn't appear in the source. Rather strange.

Regardless, the homepage contains a link to the file that's used as the cask `url`, so it would be preferable to check that anyway.

2020-12-24 22:54 UTC, samford commented on Casks/yed.rb
> +    regex(%r{/yEd-(\d+(?:\.\d+)*)_with-JRE14\.dmg}i)
```suggestion
    regex(/yEd[._-]v?(\d+(?:\.\d+)+)[._-]with[._-]JRE\d+?\.dmg/i)
```

This is a bit looser about the `JRE` version, so the check will continue to work without needing to be manually updated. If we only target files that end with `JRE14`, livecheck wouldn't match newer versions and this wouldn't be apparent until the cask is updated to a newer version (at which point it becomes apparent in livecheck's output).

Besides that, I've found that any maintainers/contributors who aren't already familiar with livecheck will simply ignore the block when updating the `url` in a formula/cask. I periodically identify and address these issues but it's better to avoid the problem entirely.

2020-12-24 22:54 UTC, samford commented on Casks/yojimbo.rb
> +    regex(%r{<key>SUFeedEntryShortVersionString</key>\s*<string>(\d+(?:\.\d+)+)</string>}i)
```suggestion
    regex(/Yojimbo[._-]v?(\d+(?:\.\d+)+)\.dmg/i)
```

2020-12-24 23:33 UTC, reitermarkus commented on Casks/hex-fiend.rb
> +    url "https://github.com/ridiculousfish/HexFiend/releases.atom"
I'd like to change this to `:url`. Naming it `:cask_url` is redundant, given this is in a cask.

2020-12-24 23:38 UTC, reitermarkus commented on Casks/livereload.rb
> +    regex(/LiveReload-(\d+(?:\.\d+)*)\.zip/i)
I'd say it is preferable to have a URL which matches the homepage domain.

2020-12-24 23:40 UTC, reitermarkus commented on Casks/nestopia.rb
> +    regex(/Nestopia v(\d+(?:\.\d+)*)/i)
I don't think we need `:appcast`. `livecheck` is a replacement for `appcast` so there shouldn't be an `appcast` if there is also a `livecheck`.

2020-12-25 00:09 UTC, samford commented on Casks/hex-fiend.rb
> +    url "https://github.com/ridiculousfish/HexFiend/releases.atom"
Makes sense to me, since it's just referred to as `url` in cask objects (e.g., some_cask.url`). We use the `:stable` symbol to refer to `url` in formulae since you access that URL on a formula object like `some_formula.stable.url`.

2021-01-03 14:59 UTC, samford requested changes

2021-01-03 15:10 UTC, samford commented
I'm working on creating a script to go through casks with a GitHub `url` to identify which would benefit from using `GithubLatest`.

I believe I've mentioned it before but we try to use `GithubLatest` somewhat sparingly at the moment, since github.com is rate limited. If we check github.com (rather than Git tags) for a lot of formulae/casks, this can become a problem on CI (we encountered this in Homebrew/homebrew-livecheck, so it's likely to happen in homebrew-core) or on livecheck runs across large taps like homebrew-core or homebrew-cask.

A livecheck failure on CI simply due to rate limiting will unnecessarily hold up PRs, so reliability is important. Usually we use the `Git` strategy until/unless `GithubLatest` becomes necessary (i.e., `Git` returns a newer version than the "latest" release) and we should do the same here for now.

I'll let you know once I have a list of casks that currently need `GithubLatest`.

2021-01-03 17:08 UTC, reitermarkus commented
> I'm working on creating a script to go through casks with a GitHub url to identify which would benefit from using GithubLatest.

I already converted all the GitHub appcasts in this PR to use `:github_latest`. You mean your script tries to use `:git` first?

2021-01-03 17:24 UTC, samford commented
> I already converted all the GitHub appcasts in this PR to use `:github_latest`. You mean your script tries to use `:git` first?

My script is going through all casks with a checkable GitHub URL and comparing the latest version obtained using the `Git` strategy and `GithubLatest`. For the casks where they're the same (or could be with a regex), we should use `Git` until `GithubLatest` becomes necessary.

If rate limiting wasn't a concern, we would use `GithubLatest` wherever it's available and correct but this is how we're currently minimizing the number of github.com checks.

2021-01-07 21:26 UTC, samford commented
Just a heads up, I've been working through casks with a GitHub `url` to create appropriate `livecheck` blocks and I'll push a branch when I've finished. There are at least a couple hundred that require a `livecheck` block in some form and those are the ones I've been working through.

I'm not adding `livecheck` blocks for the casks that use the `Git` strategy by default and don't need to use `GithubLatest`, as we currently only add `livecheck` blocks when it's technically necessary.

2021-01-07 22:10 UTC, reitermarkus commented
> There are at least a couple hundred that require a `livecheck` block in some form and those are the ones I've been working through over the past few days.

Are you saying we did the same work (https://github.com/Homebrew/homebrew-cask/pull/97418)? Except I explicitly added `livecheck` blocks also for the `:git` strategy.

2021-01-07 22:36 UTC, samford commented
> Are you saying we did the same work (#97418, extracted from this PR)? Except I explicitly added `livecheck` blocks also for the `:git` strategy.

As mentioned earlier, we should only use `GithubLatest` when it's necessary and correct. Your PR is using `GithubLatest` for a number of casks where it isn't necessary and I'm accounting for this using the data that I produced with my script. From a cursory glance, there are also a number of checks in that PR with issues that need to be addressed (e.g., checking the GitHub releases page (`aquamacs`, `picgo`, etc.)) but it's currently difficult to wade through the thousands of unnecessary `strategy :git` changes.

Besides what I handled with my script, there are others that are a bit more complicated and I've been investigating/handling those manually over the past few days. In the end, all the casks with a GitHub URL should be using an appropriate strategy along with a regex/strategy block where necessary.

Once I've finished, I'll compare my work to your PR (to ensure we're taking the best of both branches) and then we can discuss how to move forward. #97418 shouldn't be merged as-is, for the aforementioned reasons. It would be helpful to remove the `livecheck` blocks from that PR that use `strategy :git` where it isn't necessary and I can provide you with a list once I'm finished working through this.

2021-05-01 12:46 UTC, SMillerDev commented
I think this can be closed right?

2021-05-14 08:49 UTC, closed without merging