WIP: feat: add Stringz
Homebrew/homebrew-cask pull request #97002
Opened 2020-12-27 12:33 UTC by nuomi1

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).
- [ ] `brew audit --cask {{cask_file}}` is error-free.
- [ ] `brew style --fix {{cask_file}}` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask {{cask_file}}` worked successfully.
- [ ] `brew install --cask {{cask_file}}` worked successfully.
- [ ] `brew uninstall --cask {{cask_file}}` worked successfully.

2020-12-29 10:07 UTC, miccal commented
Thank you for your contribution to `homebrew-cask` @nuomi1.

Could you please try to add a [`zap` stanza](https://github.com/homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/zap.md), thanks.

2020-12-30 01:09 UTC, nuomi1 commented
> Thank you for your contribution to `homebrew-cask` @nuomi1.
> 
> Could you please try to add a [`zap` stanza](https://github.com/homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/zap.md), thanks.

Added.

2020-12-30 21:00 UTC, miccal approved these changes, later dismissed

2020-12-31 02:35 UTC, vitorgalvao approved these changes

2020-12-31 02:36 UTC, vitorgalvao requested changes

2020-12-31 02:36 UTC, vitorgalvao commented on Casks/stringz.rb
> +  version "0.4.0"
It’s at `0.4.3` now.

2021-01-04 01:36 UTC, vitorgalvao approved these changes

2021-01-05 08:41 UTC, merged