Update p4v
Homebrew/homebrew-cask pull request #97257
Opened 2021-01-03 21:07 UTC by mystygage

Created with `brew bump-cask-pr`.

2021-01-04 10:23 UTC, michalsvec requested changes

2021-01-04 10:23 UTC, michalsvec commented on Casks/p4v.rb
>    version "20.3,2059355"
the version changed as well: 

```  
version "20.3,2060285"
sha256 "8b42a0e1dfe13da490a52bf03f65947b48b58a28bedb6277a1caf3a320a596c3"
```

2021-01-04 12:35 UTC, mystygage commented on Casks/p4v.rb
>    version "20.3,2059355"
Sorry, I didn't double checked the version, I trusted the latest information on the website :/
![image](https://user-images.githubusercontent.com/1107406/103535438-fd7cbe00-4e90-11eb-9cc9-8b77942a4cd2.png)

2021-01-04 12:57 UTC, michalsvec commented on Casks/p4v.rb
>    version "20.3,2059355"
I'd do the same, but over the years I learned to not trust perforce :)

2021-01-06 12:24 UTC, reitermarkus commented
/rebase

2021-01-06 12:27 UTC, mystygage commented
PR can be closed, #97299 was faster

2021-01-06 12:27 UTC, closed without merging