Fix pkg file name for mbed-studio
Homebrew/homebrew-cask pull request #97261
Opened 2021-01-03 22:59 UTC by GHF

Download URL redirects to a file with a versioned file name

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).
- [x] `brew audit --cask {{cask_file}}` is error-free.
- [x] `brew style --fix {{cask_file}}` reports no offenses.

2021-01-04 01:26 UTC, vitorgalvao requested changes
This is a case which should have a `sha256`, because the version number matters, even if not on `url`.

2021-01-04 01:31 UTC, reitermarkus commented
Doesn't `https://studio.mbed.com/installers/latest/mac/MbedStudio.pkg` redirect to a versioned URL?

2021-01-04 01:34 UTC, vitorgalvao commented
> Doesn't `https://studio.mbed.com/installers/latest/mac/MbedStudio.pkg` redirect to a versioned URL?

Nope. It’s `content-disposition: attachment; filename=MbedStudio-1.3.1.pkg`, not a redirect.

2021-01-04 05:42 UTC, GHF commented
> This is a case which should have a `sha256`, because the version number matters, even if not on `url`.

Good catch! I didn't even realize it was `:no_check`.

> > Doesn't `https://studio.mbed.com/installers/latest/mac/MbedStudio.pkg` redirect to a versioned URL?
> 
> Nope. It’s `content-disposition: attachment; filename=MbedStudio-1.3.1.pkg`, not a redirect.

Today I learned. 😁

2021-01-04 16:54 UTC, vitorgalvao approved these changes

2021-01-05 19:39 UTC, GHF commented
Hmmm...

```
audit for mbed-studio: failed
11
 - Use `sha256 :no_check` when URL is unversioned.
```

Any way to suppress that audit diagnostic?

2021-01-05 19:48 UTC, vitorgalvao commented
I had a fling that might be an issue. Ignoring that check for this PR, but we should make the `audit` take these into account, @reitermarkus.

2021-01-05 19:49 UTC, vitorgalvao approved these changes

2021-01-08 06:41 UTC, merged

2021-01-08 09:19 UTC, MikeMcQuaid commented
@vitorgalvao @reitermarkus Need to figure out a way to make these checks not get ignored as they break CI for all PRs on Homebrew/brew. Perhaps this should be a `required` CI check?

2021-01-08 09:36 UTC, reitermarkus commented
It is a required check, but applying the `ci-syntax-only` of course skipped. This should not have been marked with that label as it clearly isn't a syntax-only change.

2021-01-08 09:39 UTC, MikeMcQuaid commented
Thanks @reitermarkus. Reverted in https://github.com/Homebrew/homebrew-cask/pull/97518

2021-01-08 09:45 UTC, reitermarkus commented
It should just use `sha256 :no_check`, as the audit suggests.

2021-01-08 14:27 UTC, vitorgalvao commented
> It should just use `sha256 :no_check`, as the audit suggests.

I disagree. It’s the `audit` that is inadequate—as pointed out above—because it’s not fulfilling its purpose.

The version number is very much required for this cask to be installed correctly and not break. If this case doesn’t require a checksum, then neither do any of the other casks.

Blindly following the `audit` here is ignoring the problem; it’s changing the rules to fit the system, when it should always be the other way around.

2021-01-08 14:51 UTC, reitermarkus commented
> it’s changing the rules to fit the system

The rule is: Unversioned URLs should use `sha256 :no_check`. Why should it use a checksum in this case?

2021-01-08 14:56 UTC, reitermarkus commented
> The version number is very much required for this cask to be installed correctly and not break.

The cask will fail to install either way: If we add a checksum and the download changes, or if the version is wrong. So why not remove one of the possible ways this can fail?

2021-01-08 15:00 UTC, reitermarkus commented
We could potentially do something like this so it doesn't depend on the version and never fails:

```ruby
preflight do
  FileUtils.mv Dir["#{staged_path}/*.pkg"].first, "#{staged_path}/MbedStudio.pkg"
end
```

2021-01-08 17:45 UTC, vitorgalvao commented
> The rule is: Unversioned URLs should use `sha256 :no_check`.

Correct. But I was arguing the rule should be “Require `sha256 :no_check` when there’s no version interpolation *anywhere* on the case”.

> The cask will fail to install either way: If we add a checksum and the download changes, or if the version is wrong.

Correct, but it’s better to fail at the download stage than at the installation stage, because the former is easier to diagnose and a more common error we even reference on the issue template. Meaning that given the choice, that’s a better error to have because it will lead to quicker fixes.

> We could potentially do something like this so it doesn't depend on the version and never fails

[Agreed. That’s better.](https://github.com/Homebrew/homebrew-cask/pull/97539) Don’t we have access to `pathname` (without `require`), though? That reads way nicer.