Upgrade Wavebox.app to v10.0.389.2 and update the urls from core to s…
Homebrew/homebrew-cask pull request #97280
Opened 2021-01-04 17:49 UTC by Thomas101

…table. Core was deprecated & frozen mid-2020 and when installing the core version it immediately prompts to update to the stable version. Add a description to the cask

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).
- [x] `brew audit --cask {{cask_file}}` is error-free.
- [x] `brew style --fix {{cask_file}}` reports no offenses.

2021-01-04 17:59 UTC, vitorgalvao commented on Casks/wavebox.rb
> +  desc "Powerful productivity browser like no other"
From the [`desc` documentation](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/desc.md):

> `desc` is not for app slogans! Vendors’ descriptions tend to be filled with generic adjectives such as “modern” and “lightweight”. Those are meaningless marketing fluff (do you ever see apps proudly describing themselves as outdated and bulky?) which must the deleted. It’s fine to use the information on the software’s website as a starting point, but it will require editing in almost all cases.

2021-01-04 18:01 UTC, vitorgalvao requested changes

2021-01-04 18:01 UTC, vitorgalvao commented on Casks/wavebox.rb
> +  desc "Powerful productivity browser like no other"
From the [`desc` documentation](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/desc.md):

> `desc` is not for app slogans! Vendors’ descriptions tend to be filled with generic adjectives such as “modern” and “lightweight”. Those are meaningless marketing fluff (do you ever see apps proudly describing themselves as outdated and bulky?) which must the deleted. It’s fine to use the information on the software’s website as a starting point, but it will require editing in almost all cases.

The correct `desc` is `Web browser`.

Also, please don’t disable edits by maintainers, as this could have already be fixed otherwise.

2021-01-05 07:59 UTC, Thomas101 commented on Casks/wavebox.rb
> +  desc "Powerful productivity browser like no other"
Apologies, I've updated this now

2021-01-05 19:49 UTC, vitorgalvao commented on Casks/wavebox.rb
> +  desc "Powerful productivity browser like no other"
Thank you.

2021-01-05 19:50 UTC, vitorgalvao approved these changes

2021-01-07 04:34 UTC, merged