Add Space Saver.app v0.5
Homebrew/homebrew-cask pull request #97958
Opened 2021-01-11 16:17 UTC by J3n50m4t

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).
- [x] `brew audit --cask {{cask_file}}` is error-free.
- [ ] `brew style --fix {{cask_file}}` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask {{cask_file}}` worked successfully.
- [x] `brew install --cask {{cask_file}}` worked successfully.
- [x] `brew uninstall --cask {{cask_file}}` worked successfully.

2021-01-11 18:51 UTC, vitorgalvao requested changes

2021-01-11 18:51 UTC, vitorgalvao commented on Casks/space-saver.rb
> +  app "Space Saver.app"
Please add a [`zap`](https://github.com/homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/zap.md), if applicable. See [`homebrew-createzap`](https://github.com/nrlquaker/homebrew-createzap) for an external project which can help.

2021-01-11 22:17 UTC, J3n50m4t commented on Casks/space-saver.rb
> +  app "Space Saver.app"
❯ brew cask createzap space-saver
No space-saver settings found.
I've also manually checked and used AppCleaner, which usually also shows these paths and it didn't return anything as well.

2021-01-12 03:10 UTC, vitorgalvao commented on Casks/space-saver.rb
> +  app "Space Saver.app"
Thank you for checking.

2021-01-12 03:11 UTC, vitorgalvao approved these changes

2021-01-12 03:17 UTC, merged