move deadbeef from cask-versions
Homebrew/homebrew-cask pull request #98099
Opened 2021-01-13 14:53 UTC by yurikoles

Signed-off-by: Yurii Kolesnykov <root@yurikoles.com>

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).
- [x] `brew audit --cask {{cask_file}}` is error-free.
- [x] `brew style --fix {{cask_file}}` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask {{cask_file}}` worked successfully.
- [x] `brew install --cask {{cask_file}}` worked successfully.
- [x] `brew uninstall --cask {{cask_file}}` worked successfully.

2021-01-13 18:12 UTC, vitorgalvao requested changes

2021-01-13 18:12 UTC, vitorgalvao commented on Casks/deadbeef.rb
> +  version :latest
Add the `version`, but not the `sha256`.

2021-01-13 23:34 UTC, vitorgalvao requested changes, later dismissed

2021-01-13 23:34 UTC, vitorgalvao commented on Casks/deadbeef.rb
> +  appcast "https://sourceforge.net/projects/deadbeef/rss?path=/travis/osx/master"
This appcast contains no part of `version`.

2021-01-14 06:42 UTC, yurikoles commented on Casks/deadbeef.rb
> +  appcast "https://sourceforge.net/projects/deadbeef/rss?path=/travis/osx/master"
You had requested to add `version`, I took it from app's Info.plist. After this HBC's lint asked to specify `appcast`.

2021-01-14 16:37 UTC, vitorgalvao commented on Casks/deadbeef.rb
> +  appcast "https://sourceforge.net/projects/deadbeef/rss?path=/travis/osx/master"
> I took it from app's Info.plist.

Which looks broken. That’s not a version, it’s a `1.0` with a checksum. An `appcast` with no `version` in it is useless.

2021-01-14 17:10 UTC, yurikoles commented on Casks/deadbeef.rb
> +  appcast "https://sourceforge.net/projects/deadbeef/rss?path=/travis/osx/master"
Now we have
```
audit for deadbeef: failed
 - Download is hosted on SourceForge, please add an appcast. See https://github.com/Homebrew/homebrew-cask/blob/HEAD/doc/cask_language_reference/stanzas/appcast.md
Error: 1 problem in 1 cask detected
```

2021-01-14 19:09 UTC, vitorgalvao commented on Casks/deadbeef.rb
> +  appcast "https://sourceforge.net/projects/deadbeef/rss?path=/travis/osx/master"
Because the problem is the `version`, not the `appcast`. Use the `1.8.5-beta2` download they provide.

Even if it’s a version behind, it’s better than breaking checks. You should consider asking upstream to fix the internal versioning and provide versioned downloads of the latest version.

2021-01-14 22:46 UTC, miccal approved these changes

2021-01-14 22:47 UTC, merged