Update eudic-es from 4.0.1,2020-11-16 to 2020-12-19
Homebrew/homebrew-cask pull request #98359
Opened 2021-01-19 14:28 UTC by 12Yue

Created with `brew bump-cask-pr`.

2021-01-19 17:59 UTC, vitorgalvao requested changes

2021-01-19 17:59 UTC, vitorgalvao commented on Casks/eudic-es.rb
> +  version "2020-12-19"
Please keep (update) the version, not just the date.

2021-01-20 02:52 UTC, 12Yue commented
I'm sorry, this is my very first time using github and I'm not familiar with all these things.
Also, the sha256 was automatically changed when I use "bump-cask-pr", but when I was checking the dmg file this morning, I found the update time was changed to 2020-12-20, I am not sure if the sha256 was changed. This might be a problem.
Should I close this pull request and start a new one?

2021-01-20 16:05 UTC, vitorgalvao commented
Thank you for the fast fix. And welcome!

2021-01-20 16:05 UTC, vitorgalvao approved these changes

2021-01-20 16:05 UTC, merged