Add Xcodes.app v1.0.3
Homebrew/homebrew-cask pull request #99034
Opened 2021-01-29 05:02 UTC by interstateone

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).
- [x] `brew audit --cask {{cask_file}}` is error-free.
- [x] `brew style --fix {{cask_file}}` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask {{cask_file}}` worked successfully.
- [x] `brew install --cask {{cask_file}}` worked successfully.
- [x] `brew uninstall --cask {{cask_file}}` worked successfully.

2021-01-30 14:49 UTC, vitorgalvao requested changes

2021-01-30 14:49 UTC, vitorgalvao commented on Casks/xcodes.rb
> +  desc "Easiest way to install and switch between multiple versions of Xcode"
From the [`desc` documentation](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/desc.md):

> `desc` is not for app slogans! Vendors’ descriptions tend to be filled with generic adjectives such as “modern” and “lightweight”. Those are meaningless marketing fluff (do you ever see apps proudly describing themselves as outdated and bulky?) which must the deleted. It’s fine to use the information on the software’s website as a starting point, but it will require editing in almost all cases.

Essentially, “Easiest way to ” is marketing fluff and must be removed. Please don’t disable the checkbox that allows edits from maintainers; this could have already been fixed and merged otherwise.

Fantastic first contribution, though! Thank you and welcome.

2021-01-30 16:55 UTC, interstateone commented on Casks/xcodes.rb
> +  desc "Easiest way to install and switch between multiple versions of Xcode"
Ah okay, that must have been the one stanza doc I didn't read. I've removed the fluff 😄

I think the "allow edits from maintainers" feature isn't available here because this fork is in an org and not an individual account, which is too bad... I'll consider using an individual fork instead for updates in the future to make this smoother.

Thanks for the review!

2021-01-31 00:37 UTC, vitorgalvao approved these changes

2021-01-31 00:37 UTC, merged