Add redream cask
Homebrew/homebrew-cask pull request #99890
Opened 2021-02-14 19:02 UTC by larsenv

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).
- [x] `brew audit --cask {{cask_file}}` is error-free.
- [x] `brew style --fix {{cask_file}}` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask {{cask_file}}` worked successfully.
- [x] `brew install --cask {{cask_file}}` worked successfully.
- [x] `brew uninstall --cask {{cask_file}}` worked successfully.

2021-02-14 22:25 UTC, vitorgalvao requested changes
Welcome.

Please add a [`zap`](https://github.com/homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/zap.md). See [`homebrew-createzap`](https://github.com/nrlquaker/homebrew-createzap) for an external project which can help.

2021-02-14 22:25 UTC, vitorgalvao commented on Casks/redream.rb
> +  name "redream"
```suggestion
  name "Redream"
```

2021-02-18 16:27 UTC, larsenv commented
@vitorgalvao is zap just to uninstall program settings?

2021-02-18 17:23 UTC, vitorgalvao commented
> is zap just to uninstall program settings?

From the docs:

> `zap` stanzas may remove:
>
> * Preference files and caches stored within the user’s `~/Library` directory.
> * Shared resources such as application updaters. Since shared resources may be removed, other applications may be affected by `brew uninstall --zap`. Understanding that is the responsibility of the end user.
>
> `zap` stanzas should not remove:
>
> * Files created by the user directly.

If the user created it as an output of using the program, keep it. Otherwise, delete it.

2021-02-19 18:04 UTC, larsenv commented on Casks/redream.rb
> +  name "redream"
No. The emulator name is officially capitalized as "redream", all lowercase.

2021-02-19 18:04 UTC, larsenv commented
OK, I added a zap, sorry for the delay.

2021-02-19 18:20 UTC, vitorgalvao commented on Casks/redream.rb
> +  name "redream"
> The emulator name is officially capitalized as "redream", all lowercase

Officially, it’s bloody inconsistent.

The logo is all uppercase; the app and support files are all lowercase; on the download page only the first letter is uppercase.

2021-02-19 18:21 UTC, vitorgalvao approved these changes

2021-02-23 05:03 UTC, merged