Kaleidoscope 2.4
Homebrew/homebrew-cask pull request #99937
Opened 2021-02-16 16:43 UTC by florian-muc

Updating Kaleidoscope and ksdiff to the most recent release.

After making all changes to a cask, verify:

- [X] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).
- [X] `brew audit --cask {{cask_file}}` is error-free.
- [X] `brew style --fix {{cask_file}}` reports no offenses.

2021-02-16 19:50 UTC, vitorgalvao requested changes

2021-02-16 19:50 UTC, vitorgalvao commented on Casks/kaleidoscope.rb
> +  desc "Spots and merge differences in text and image files or folders"
```suggestion
  desc "Spot and merge differences in text and image files or folders"
```

2021-02-16 19:50 UTC, vitorgalvao commented on Casks/ksdiff.rb
> +  desc "Command-line tool for App Store version Kaleidoscope"
```suggestion
  desc "Command-line tool for the App Store version of Kaleidoscope"
```

2021-02-17 09:56 UTC, florian-muc commented on Casks/kaleidoscope.rb
> +  desc "Spots and merge differences in text and image files or folders"
Thanks, will update.

2021-02-17 09:56 UTC, florian-muc commented on Casks/ksdiff.rb
> +  desc "Command-line tool for App Store version Kaleidoscope"
Thanks, will update.

2021-02-17 15:13 UTC, vitorgalvao approved these changes

2021-02-17 15:13 UTC, merged